### PR TITLE
Sketcher: Fix Constraint Filter Handling

### LINKED ISSUE #9476: [Problem] Sketcher: constraint filter choosing "Associated constraints" ruins the constraint list
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

https://forum.freecad.org/viewtopic.php?p=678955#p678955

### Version

0.20 (Release)

### Full version info

```shell
OS: Ubuntu 22.04.2 LTS (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.21.0.33021 (Git)
Build type: Debug
Branch: master
Hash: c77b2f33c29b9f0f24ddadae4d43900fa720758b
Python 3.10.6, Qt 5.15.3, Coin 4.0.0, Vtk 7.1.1, OCC 7.5.2
Locale: English/United States (en_US)
```

### Subproject(s) affected?

Sketcher

### Issue description

To reproduce :
* New doc, new sketch
* Draw a rectangle to get some constraints displayed
* Go to constraints filter and choose "Associated constraints"
* Go again and revert to "Selected constraints" => :exclamation: The constraint list is empty and there is nothing to do to get it back but closing and reopening the sketch.

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by matthiasdanner**
## Issues
Fixes #9476 and #9373

It fixes the problem, that "Special Filters" of constraints are not applied correctly.
To reproduce the bug see https://github.com/FreeCAD/FreeCAD/issues/9476#issuecomment-2017384091

The problem was when initializing the filters all special filters were initialized and the first special filter (selected constraints) disabled the second filter (associated constraints). Then the second filter was initialized (which was disabled) and reset the specialFilterMode variable to none. However the selected constraints checkbox stayed checked but the filtermode for selected constraints was not enabled..

While testing I found another problem. The show only filtered constraints checkbox from the settings button also doesn't work correctly. If there are no filtered constraints and you uncheck the ckeckbox the constraints don't appear in the 3d view again. Fixed with this PR as well

Steps to reproduce:
1. open sketch
2. create geometry with contstraints
3. check filter checkbox to filter only selected constraints (constraint list should now be empty, constraints in sketch are displayed)
4. check settings checkbox to only show filtered constraints (constraints in sketch disappear)
5. uncheck settings checkbox to only show filtered constraints (constraints in sketch should appear again, but they don't)
EDIT: just realized there also exists an issue for that #9373

**Heads up**
I changed the default settings of the constraint filter. So by now the special filters (selected and associated constraints) are disabled for new users. However, since they are saved in the preferences for users who started the sketcher before this fix most likely have the selected constraints setting enabled. And now with this setting working no constraints will be displayed in the constraint list. They have to manually uncheck the checkbox.
I think the most user friendly way would be to update the preferences and uncheck all special filters. Is there a way to achieve this?

### CODE REVIEW

**Comment by matthiasdanner** [comment]
> function 'change3DViewVisibilityToTrackFilter' has cognitive complexity of 29 (threshold 25) [readability-function-cognitive-complexity]

I fixed this linting comment and I found another case where the displayed constraints in the 3d viewer where not correct.

Steps to Reproduce:
* Check Checkbox to filter for selected constraints
* Check settings checkbox to only show filtered constraints
* create new Geometry with constraints (e.g. square)
  * expected: constraints should not be shown in the 3d viewer
  * the constraints for the new geometry are shown even if they shouldn't
* if you create another new geometry with constraints the constraints from the first geometry disappear (correctly) and the constraints from the new geometry stay on screen.

I fixed that as well with this commit

**Comment by chennes** [comment]
@theo-vt is going to test this. Thanks all!

**Comment by matthiasdanner** [comment]
If there is no such functionality to update the preferences on a freecad update we could just rename the constraintfilterstate property name and reset this property. So everyone would start with all constraints showing instead of none. What do you think about this?
This would only affect Users who disabled some constraints to show and they would have to disable them again. Instead of all Users updating from an older Version to Not show constraints at all in the list until they disable the setting to only show selected constraints.

**Comment by theo-vt** [comment]
hey @matthiasdanner I am having trouble with the protocol in #9373, in main it reacts as it said it would (bug included) but when I tried on your branch the datum constraint does not show up in the list even before disabling "Datums", do you know what is going on?

Screenshot From 2025-06-25 16-41-03

Thanks!

**Comment by theo-vt** [comment]
Ok once I unchecked "Selected" it worked as expected! I think it should really be reset somehow because it felt broken :(

Thanks!

**Comment by matthiasdanner** [comment]
Yes that is what I meant with my heads up. I didn't find a Solution to Update the preferences so in my opinion the best way is to reset the to the new default (with the selected constraints disabled)

**Comment by matthiasdanner** [comment]
@theo-vt I changed the name of the preference. So on an update to this branch the constraint filter will be reset to default.

if you want to test this behaviour, (since you already updated to my branch) you have to reset your preferences to the state in the current main branch. In order to do this you have to do a few steps:
1. open FreeCAD in an older version (main branch, weekly build, release build, ... it doesn't really matter which version, but it has to be without my changes here)
2. reset preferences via the preferences menu (if you don't want to lose your preferences just export them before resetting and import them after this test)
3. open sketcher
Now you can open this branch and the constraint filter will be reset to default (all normal constraint filters enabled and the special ones (selected and associated) disabled and you see all constraints in the filter list by default.

**Comment by theo-vt** [comment]
Nice, it works as expected!

I don't know how we should handle such 'ghost' parameters in general, but it probably should not be solved in this pr

**Comment by matthiasdanner** [comment]
Thanks for testing 👍 

My 2 cents on this ghost parameter:
I checked and didn't find any existing update function for the preferences. And I think it's a bit overkill to implement such a versioning tool just for this parameter. 
If something like that is needed, this should be implemented with a broader goal in mind than just deleting a parameter which is no more needed.
And, I assume the likeliness of one using exact the same ParameterName in the exact same ParameterGroup in the future is rather small.

**Comment by yorikvanhavre** [comment]
Waiting for chennes to review

File: src/Mod/Sketcher/Gui/TaskSketcherConstraints.cpp [hunk 1]
```diff
@@ -1133,35 +1137,7 @@ void TaskSketcherConstraints::changeFilteredVisibility(bool show, ActionTarget t
...
-                sketch, "setVirtualSpace(%s, %s)", constrIdList, show ? "False" : "True");
-        }
-        catch (const Base::Exception&) {
-            Gui::Command::abortCommand();
-
-            Gui::TranslatedUserError(
-                sketch, tr("Error"), tr("Impossible to update visibility tracking"));
-
-            return;
-        }
```
Comment (chennes) [inline src/Mod/Sketcher/Gui/TaskSketcherConstraints.cpp:1162]: Removing this block eliminates the need for line 1104, 
```
    const Sketcher::SketchObject* sketch = sketchView->getSketchObject();
```

Comment (matthiasdanner) [reply src/Mod/Sketcher/Gui/TaskSketcherConstraints.cpp:1162]: oh yes, thanks for your review and directly fixing this :)

**Comment by matthiasdanner** [comment]
@chennes #9373 should be fixed as well by this PR
