### PR TITLE
Sketcher: Fix: Arc of ellipse when first and second X coordinates are the same

### LINKED ISSUE #13175: Sketcher: Incorrect centering of Arc of ellipse due to 2nd point having the exact same X coordinate as the 1st (Snapping to the grid causes the problem)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Windows 10/11: 
- Sketcher 
- Arc of ellipse

Can't complete, makes distorted ellipse 

How to reproduce: 

When trying to use - in Sketcher - Arc of ellipse:
0. Click the function OK
1. 1st click - Placing start of arc OK
2. 2nd click - Placing vertical radius OK
3. Before 3rd click - trying to set horizontal radius - line starts jumping / flickering
4. 3rd click - Placing horizontal radius get all wrong

### Full version info

```shell
Missing Full About info
```

### Subproject(s) affected?

Sketcher

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Lokestrom**
Fixed a bug that causes the ellipse to flicker and not be correct to the user input when placing the 3. point, when the X coordinates of the 1. and 2. points are the same. Happened do to the angle between them being 90 degrees then this angle was used in a tangent function, where `tan(90)` becomes unbounded, leading to severe numerical instability.

This code only changes the GUI to show the expected result.

## Issue
Fixes #13175 

## Before and After

Before:

https://github.com/user-attachments/assets/fb6e29d1-62d6-4190-b199-fa8105d85a54

After:

https://github.com/user-attachments/assets/f4fa03e1-1e19-4288-b0b7-61a57dbd6065

### CODE REVIEW

**Comment by theo-vt** [comment]
Works as expected!

File: src/Mod/Sketcher/Gui/DrawSketchHandlerArcOfEllipse.h [hunk 1]
```diff
@@ -149,48 +157,44 @@ class DrawSketchHandlerArcOfEllipse: public DrawSketchHandler
...
-            double angle1 = atan2(
-                                a
-                                    * ((onSketchPos.y - centerPoint.y) * cos(phi)
-                                       - (onSketchPos.x - centerPoint.x) * sin(phi)),
-                                b
-                                    * ((onSketchPos.x - centerPoint.x) * cos(phi)
-                                       + (onSketchPos.y - centerPoint.y) * sin(phi))
-                            )
-                - startAngle;
+            double cosT = max(-1.0, min(1.0, delta13Prime.x / a));
```
Comment (chennes) [inline src/Mod/Sketcher/Gui/DrawSketchHandlerArcOfEllipse.h:172]: Since it's possible for `a` to be zero here this line is pretty fragile (if `delta13Prime.x` is zero you're going to get a NaN). It's probably advisable to handle the degenerate case explicitly. Same goes for `sinT` and `b`.

File: src/Mod/Sketcher/Gui/DrawSketchHandlerArcOfEllipse.h [hunk 2]
```diff
@@ -202,35 +203,43 @@ class DrawSketchHandlerArcOfEllipse: public DrawSketchHandler
...
         }
-        else {  // Fourth
+        else if (Mode == SelectMode::Fourth && centerPoint != onSketchPos && arcAngle != 0
+                 && abs(arcAngle) != 2 * pi) {
             endPoint = onSketchPos;
 
             setAngleSnapping(false);
-            Mode = STATUS_Close;
+            Mode = SelectMode::End;
         }
```
Comment (chennes) [inline src/Mod/Sketcher/Gui/DrawSketchHandlerArcOfEllipse.h:243]: Now there's no "else" condition -- what happens if we fall out of this conditional without actually hitting anything?

Comment (Lokestrom) [reply src/Mod/Sketcher/Gui/DrawSketchHandlerArcOfEllipse.h:243]: When hitting non of the conditions the SelectMode is not updated so the user just continues in the SelectMode they are in until they chose a valid point.
