### PR TITLE
Fix the crash when closing a document

### LINKED ISSUE #14189: Gui: Segfault on closing a document in Qt 6
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

In Qt 6, an assertion fails when closing a document causing FreeCAD to deliberately segfault.  To reproduce:
- Open FreeCAD
- Open a new empty document
- Close the document

This behavior is not present in Qt 5.

The assertion:
```
ASSERT failure in QOpenGLWidget: "Called object is not of the correct type (class destructor may have already run)", file /usr/include/qt6/QtCore/qobjectdefs_impl.h, line 129
```

Stacktrace:
```
#0  0x00007ffff04a8e44 in ??? () at /usr/lib/libc.so.6
#1  0x00007ffff0450a30 in raise () at /usr/lib/libc.so.6
#2  0x00007ffff04384c3 in abort () at /usr/lib/libc.so.6
#3  0x00007ffff678af93 in messageHandler (type=QtFatalMsg, context=..., msg=...) at /home/pieter/freecad-add-prop-varset/src/Gui/Application.cpp:1804
#4  0x00007ffff0adae34 in ??? () at /usr/lib/libQt6Core.so.6
#5  0x00007ffff0adaf80 in ??? () at /usr/lib/libQt6Core.so.6
#6  0x00007ffff0a8ce27 in QMessageLogger::fatal(char const*, ...) const () at /usr/lib/libQt6Core.so.6
#7  0x00007ffff0a8ceda in qt_assert_x(char const*, char const*, char const*, int) () at /usr/lib/libQt6Core.so.6
#8  0x00007ffff6edb9c8 in QtPrivate::assertObjectType<CustomGLWidget> (o=0x555559315dd0) at /usr/include/qt6/QtCore/qobjectdefs_impl.h:129
#9  0x00007ffff6edb3d6 in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (CustomGLWidget::*)()>::call(void (CustomGLWidget::*)(), CustomGLWidget*, void**) (f=(void (CustomGLWidget::*)(CustomGLWidget * const)) 0x7ffff6ed9356 <CustomGLWidget::aboutToDestroyGLContext()>, o=0x555559315dd0, arg=0x7fffffffbf18) at /usr/include/qt6/QtCore/qobjectdefs_impl.h:144
#10 0x00007ffff6edab82 in QtPrivate::FunctionPointer<void (CustomGLWidget::*)()>::call<QtPrivate::List<>, void>(void (CustomGLWidget::*)(), CustomGLWidget*, void**) (f=(void (CustomGLWidget::*)(CustomGLWidget * const)) 0x7ffff6ed9356 <CustomGLWidget::aboutToDestroyGLContext()>, o=0x555559315dd0, arg=0x7fffffffbf18) at /usr/include/qt6/QtCore/qobjectdefs_impl.h:182
#11 0x00007ffff6eda639 in QtPrivate::QCallableObject<void (CustomGLWidget::*)(), QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) (which=1, this_=0x555555cc8f40, r=0x555559315dd0, a=0x7fffffffbf18, ret=0x0) at /usr/include/qt6/QtCore/qobjectdefs_impl.h:553
#12 0x00007ffff0b9b57f in ??? () at /usr/lib/libQt6Core.so.6
#13 0x00007ffff1497753 in QOpenGLContext::destroy() () at /usr/lib/libQt6Gui.so.6
#14 0x00007ffff14979bf in QOpenGLContext::~QOpenGLContext() () at /usr/lib/libQt6Gui.so.6
#15 0x00007ffff534030b in ??? () at /usr/lib/libQt6OpenGLWidgets.so.6
#16 0x00007ffff53403ad in QOpenGLWidget::~QOpenGLWidget() () at /usr/lib/libQt6OpenGLWidgets.so.6
#17 0x00007ffff6ed91be in CustomGLWidget::~CustomGLWidget (this=0x555559315dd0, __in_chrg=<optimized out>) at /home/pieter/freecad-add-prop-varset/src/Gui/Quarter/QuarterWidget.cpp:169
#18 0x00007ffff6ed91e0 in CustomGLWidget::~CustomGLWidget (this=0x555559315dd0, __in_chrg=<optimized out>) at /home/pieter/freecad-add-prop-varset/src/Gui/Quarter/QuarterWidget.cpp:169
#19 0x00007ffff0b8a39b in QObjectPrivate::deleteChildren() () at /usr/lib/libQt6Core.so.6
#20 0x00007ffff1b31709 in QWidget::~QWidget() () at /usr/lib/libQt6Widgets.so.6
#21 0x00007ffff6ed6284 in SIM::Coin3D::Quarter::QuarterWidget::~QuarterWidget (this=0x555557ff6a40, __in_chrg=<optimized out>) at /home/pieter/freecad-add-prop-varset/src/Gui/Quarter/QuarterWidget.cpp:356
#22 0x00007ffff6ee1723 in SIM::Coin3D::Quarter::SoQTQuarterAdaptor::~SoQTQuarterAdaptor (this=0x555557ff6a40, __in_chrg=<optimized out>) at /home/pieter/freecad-add-prop-varset/src/Gui/Quarter/SoQTQuarterAdaptor.cpp:182
#23 0x00007ffff6f31c6b in Gui::View3DInventorViewer::~View3DInventorViewer (this=0x555557ff6a40, __in_chrg=<optimized out>) at /home/pieter/freecad-add-prop-varset/src/Gui/View3DInventorViewer.cpp:638
#24 0x00007ffff6f31cb4 in Gui::View3DInventorViewer::~View3DInventorViewer (this=0x555557ff6a40, __in_chrg=<optimized out>) at /home/pieter/freecad-add-prop-varset/src/Gui/View3DInventorViewer.cpp:638
#25 0x00007ffff6f2615e in Gui::View3DInventor::~View3DInventor (this=0x555559268230, __in_chrg=<optimized out>) at /home/pieter/freecad-add-prop-varset/src/Gui/View3DInventor.cpp:174
#26 0x00007ffff6f261d4 in Gui::View3DInventor::~View3DInventor (this=0x555559268230, __in_chrg=<optimized out>) at /home/pieter/freecad-add-prop-varset/src/Gui/View3DInventor.cpp:175
#27 0x00007ffff0b8bf1c in QObject::event(QEvent*) () at /usr/lib/libQt6Core.so.6
#28 0x00007ffff1afc44d in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt6Widgets.so.6
#29 0x00007ffff6933112 in Gui::GUIApplication::notify (this=0x7fffffffced0, receiver=0x555559268230, event=0x555559317fe0) at /home/pieter/freecad-add-prop-varset/src/Gui/GuiApplication.cpp:83
#30 0x00007ffff0b3fe18 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt6Core.so.6
#31 0x00007ffff0b401d2 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /usr/lib/libQt6Core.so.6
#32 0x00007ffff0d959ac in ??? () at /usr/lib/libQt6Core.so.6
#33 0x00007fffed90ea89 in ??? () at /usr/lib/libglib-2.0.so.0
#34 0x00007fffed9709b7 in ??? () at /usr/lib/libglib-2.0.so.0
#35 0x00007fffed90df95 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#36 0x00007ffff0d93389 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt6Core.so.6
#37 0x00007ffff0b48350 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt6Core.so.6
#38 0x00007ffff0b43c1d in QCoreApplication::exec() () at /usr/lib/libQt6Core.so.6
#39 0x00007ffff678be50 in (anonymous namespace)::tryRunEventLoop (mainApp=...) at /home/pieter/freecad-add-prop-varset/src/Gui/Application.cpp:2042
#40 0x00007ffff678c19b in (anonymous namespace)::runEventLoop (mainApp=...) at /home/pieter/freecad-add-prop-varset/src/Gui/Application.cpp:2062
#41 0x00007ffff678c554 in Gui::Application::runApplication () at /home/pieter/freecad-add-prop-varset/src/Gui/Application.cpp:2139
#42 0x000055555557a579 in main (argc=1, argv=0x7fffffffd6b8) at /home/pieter/freecad-add-prop-varset/src/Main/MainGui.cpp:278
```

### Full version info

```shell
OS: Arch Linux
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37438 (Git)
Build type: DEBUG
Branch: main
Hash: 58083879b765846daaeab4fdb125e418138e5874
Python 3.12.3, Qt 6.7.0, Coin 4.0.2, Vtk , OCC 7.7.2
Locale: English/United States (en_US)
Installed mods: 
  * OpenTheme 2024.5.16
```

### Subproject(s) affected?

Core

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by xtemp09**
Closes #14189. This commit partially reverts d15c7d067341eacd10245b58465902546cdedea6 and fb372012991c3b6da359115f3e329f3166ebc5bc.

This pull request must be carefully checked before merge; perhaps, ven. @wwmayer might want to look at it.

I don't know the cause of the crash.

### CODE REVIEW

**Comment by wwmayer** [comment]
> I don't know the cause of the crash.

Are you able to reproduce this crash? What's your Qt version?

**Comment by xtemp09** [comment]
> Are you able to reproduce this crash?

Of course. This patch seems to fix it.


```ruby
OS: Ubuntu 22.04.4 LTS (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37573 (Git)
Build type: Debug
Branch: main
Hash: 91aac05021023c946dc1545f2b13512ccf326550
Python 3.10.12, Qt 6.7.1, Coin 4.0.0, Vtk 9.1.0, OCC 7.5.1
Locale: English/United States (en_US)
```

File: src/Gui/Quarter/QuarterWidget.cpp [hunk 1]
```diff
@@ -200,17 +200,17 @@ class CustomGLWidget : public QOpenGLWidget {
...
-            return;
-        QMetaObject::invokeMethod(parent(), "aboutToDestroyGLContext",
-            Qt::DirectConnection,
-            QGenericReturnArgument());
-    }
+
+
+
+
+
```
Comment (kadet1090) [inline src/Gui/Quarter/QuarterWidget.cpp:207]: This empty space is not needed

**Review by kadet1090 — APPROVED** [review]
Works fine on Qt6!

**Comment by wwmayer** [comment]
On none of my system I can reproduce this crash. Here I have Qt 6.2.4, on my Debian it's Qt 6.4.2 and on Windows using MSYS2 it's also Qt 6.4.2.

All what I can do is to test the PR and check if it causes a regression.

**Comment by xtemp09** [comment]
The crash was reported on Qt 6.7.0, I reproduced it and tested the PR on Qt 6.7.1.


Apparently, Qt has undergone some internal changes.

**Comment by wwmayer** [comment]
I have tested the PR on all my systems with Qt5 and Qt6 and haven't observed any regressions. So, it's probably fine to merge it.

Just for the record: handling of destruction of the GL context once was added with d15c7d0673. But I can't remember what the use of `QMetaObject::invokeMethod` was good for -- maybe an issue with Qt4.
