### PR TITLE
Core: Add shortcut for Recompute object

### LINKED ISSUE #24900: Recompute object has not a keyboard shortcut
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Problem description

Greetings to everyone!

Steps to reproduce:
1.Open the file
2.Set working plane to wall face
3. Move window sketch (Not the window itself)  on the wall
4. There you will need to recompute the wall but F5 itself not work, insstead you have to select the wall, right click and choose the recompute object.

I think there should be a keyboard shortcut for a fast workflow.

https://github.com/user-attachments/assets/4b994aca-6ad0-48b4-99b8-cf9a72b253ac

 
[recompute_test.zip](https://github.com/user-attachments/files/23187753/recompute_test.zip)

### Full version info

```shell
OS: Windows 10 build 19045
Architecture: x86_64
Version: 1.1.0dev.14555 (Git shallow)
Build date: 2025/10/21 12:07:13
Build type: Release
Branch: main
Hash: 2096d0bd8603b429fdc0c746c34b3d73c3289fe1
Python 3.11.14, Qt 6.8.3, Coin 4.0.3, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.3.0, IfcOpenShell 0.8.2, OCC 7.8.1
Locale: Turkish/Türkiye (tr_TR)
Navigation Style/Orbit Style/Rotation Mode: Blender/Trackball/Drag at cursor
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/fusion
Logical DPI/Physical DPI/Pixel Ratio: 96/81.5973/1
Installed mods: 
  * CurvedShapes 1.0.13
  * Curves 0.6.61
```

### Subproject(s) affected?

None

### Anything else?

_No response_

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Bojan9597**
## Summary
Implement `Std_Recompute` so it recomputes selected objects (from tree selection), or recomputes the active document when nothing is selected.

Also:
- Set default shortcut for `Std_Recompute` to `Ctrl+Shift+R`
- Show the shortcut in the tree context menu for **Recompute Object**
- Route tree context menu recompute action through `Std_Recompute` command path

## Issues
Closes #24900

## Before and After Images
Before:
- No keyboard shortcut shown/available for **Recompute Object** in tree context menu.

After:
- **Recompute Object** shows `Ctrl+Shift+R` in tree context menu.
- `Ctrl+Shift+R` triggers recompute on selected tree object(s).

### CODE REVIEW

File: src/Gui/Tree.cpp [hunk 1]
```diff
@@ -735,6 +735,15 @@ TreeWidget::TreeWidget(const char* name, QWidget* parent)
...
     this->recomputeObjectAction = new QAction(this);
     connect(this->recomputeObjectAction, &QAction::triggered, this, &TreeWidget::onRecomputeObject);
+    if (auto recomputeCmd
+        = Gui::Application::Instance->commandManager().getCommandByName("Std_Recompute")) {
+        // Register command action on the tree so its shortcut can trigger from the main window.
+        recomputeCmd->addTo(this);
+        this->recomputeObjectAction->setShortcut(recomputeCmd->getShortcut());
+#if QT_VERSION >= QT_VERSION_CHECK(5, 10, 0)
+        this->recomputeObjectAction->setShortcutVisibleInContextMenu(true);
+#endif
```
Comment (chennes) [inline src/Gui/Tree.cpp]: We only technically support Qt 6.4 and above now, and even in a non-technical sense the oldest version you can compile with is 5.15, so you can drop these conditionals.
```suggestion
        this->recomputeObjectAction->setShortcutVisibleInContextMenu(true);
```

File: src/Gui/Tree.cpp [hunk 2]
```diff
@@ -1546,23 +1555,11 @@ void TreeWidget::onMarkRecompute()
...
 {
-    std::vector<App::DocumentObject*> objs;
-    const auto items = selectedItems();
-    for (auto ti : items) {
-        if (ti->type() == ObjectType) {
-            auto objitem = static_cast<DocumentObjectItem*>(ti);
-            objs.push_back(objitem->object()->getObject());
-            objs.back()->enforceRecompute();
-        }
+    if (auto cmd = Gui::Application::Instance->commandManager().getCommandByName("Std_Recompute")) {
```
Comment (chennes) [inline src/Gui/Tree.cpp:1601]: If you're going to bother having a conditional here (obviously it would be very odd for this to fail!), then we may as well log the failure instead of silently doing nothing. I'd add a `Base::Console().Error()`-type message if this condition isn't met.

File: src/Gui/CommandFeat.cpp [hunk 3]
```diff
@@ -56,12 +58,42 @@ StdCmdFeatRecompute::StdCmdFeatRecompute()
     sWhatsThis = "Std_Recompute";
     sStatusTip = sToolTipText;
     sPixmap = "view-refresh";
-    sAccel = "Ctrl+R";
+    sAccel = "Ctrl+Shift+R";
```
Comment (hyarion) [inline src/Gui/CommandFeat.cpp:61]: What's the reason to change the default accelerator/shortcut?
Was it colliding with something else or bad UX for some reason? 🤔

Comment (Bojan9597) [reply src/Gui/CommandFeat.cpp:61]: Hi,  I have Changed to Ctrl+Shift+R to avoid collision with Std_Refresh which already uses Ctrl+R. I can change it back if you want different approach.

Comment (hyarion) [reply src/Gui/CommandFeat.cpp:61]: Oh, right `Std_Recompute` != `Std_Refresh`
No need to change that right away, I just wanted to understand the reason behind it 🙂

**Comment by hyarion** [comment]
There's still some discussion going on within the design-working-group regarding the behavior.

**Comment by chennes** [comment]
@hyarion I'm dumping this in your lap 😁 -- merge or not as you and the @FreeCAD/design-working-group see fit.
