### PR TITLE
Fix tooltips on mirror checkboxes in sketcher

### LINKED ISSUE #27130: Sketcher: Mirror: missing checkbox tooltips
### Problem description

Select the mirror tool in the sketcher, notice checkbox tooltips under "symmetry parameters" are missing.  Screenshot taken with 1.0.2, problem persists with 1.2 dev branch.  Very similar issue as #25705, PR #26114.

Image

### Workbench affected?

None

### Steps to reproduce

In sketcher, click mirror, notice checkbox tooltips are missing as shown in the screenshot.

### Expected behavior

Tooltips should be populated with useful text.

### Actual behavior

Tooltips not populated with useful text.

### Development version About Info (in Safe Mode)

```shell
Confirmed issue still present in development release.
```

### Last known good version (optional)

```shell

```

### PR DESCRIPTION
**Pull request by skelliam**
Added tooltips for mirror feature in the sketcher.

## Issues
Closes #27130 

## Before and After Images
Before screenshot is in issue #27130, here is the after video:

mirror_tooltips

### CODE REVIEW

File: src/Mod/Sketcher/Gui/DrawSketchHandlerSymmetry.h [hunk 1]
```diff
@@ -280,10 +280,24 @@ void DSHSymmetryController::configureToolWidget()
             WCheckbox::FirstBox,
             QApplication::translate("TaskSketcherTool_c1_symmetry", "Delete original geometries (U)")
         );
+        toolWidget->setCheckboxToolTip(
+            WCheckbox::FirstBox,
+            QApplication::translate(
+                "TaskSketcherTool_c1_symmetry",
+                "Deletes the original geometry; this effectively performs a 'Move' operation."
```
Comment (maxwxyz) [inline src/Mod/Sketcher/Gui/DrawSketchHandlerSymmetry.h]:
```suggestion
                "Deletes the original geometry. This effectively performs a 'Move' operation."

```

**Comment by xtemp09** [comment]
If it is done around a point, it is called inversion.

**Comment by skelliam** [comment]
> I don't know how things are made in _FreeCAD_, but _move_ is a translation operator, while _mirror_ is a reflection one.
> 
> @skelliam, you can look in a mirror. The image you see is not you moved, but reflected.
> 
> You can also take a look at your gloves. They are not moved, they are reflected.

@xtemp09  The tooltip change you're referencing is for the checkbox that says "delete original geometries".  If you check that box, you've moved the geometry from one location to the other location.  Doesn't matter if it's reflected, inverted, offset, whatever.  The geometry was in one place, now it's in the other place.  This is a tooltip for a specific checkbox, not suggestion to rename the action of mirroring.

Similar language used in #26114.

**Comment by skelliam** [comment]
> You can also take a look at your gloves. They are not moved, they are reflected.

If I have a left glove on and I mirror it, yes, it is reflected and now I have a left and a right glove.

If I check a box that says "delete original geometry", now I have only a right glove and no longer have a left glove.

The tooltip only clarifies what checking the box does.  Right now it says "Checkbox 1 tooltip".

**Comment by skelliam** [comment]
Updated screenshot to reflect the latest changes.

**Comment by xtemp09** [comment]
>  Doesn't matter if it's reflected, inverted, offset, whatever. 


I have just checked, it does.



> Similar language used in https://github.com/FreeCAD/FreeCAD/pull/26114.


@skelliam, your words oppose everything I expected. How is this PR relevant? Let's wait until somebody wise comes.

**Comment by skelliam** [comment]
> > Doesn't matter if it's reflected, inverted, offset, whatever.
> 
> I have just checked, it does.
> 
> > Similar language used in #26114.
> 
> @skelliam, your words oppose everything I expected. How is this PR relevant? Let's wait until somebody wise comes

A wording change was already proposed, and the PR was approved.  Propose a wording that you'd like?

**Comment by skelliam** [comment]
I checked two competitors.

* Major Competitor A: Sketch mirror option simply has one checkbox `Copy`, which is selected by default.  If the box is unchecked the original geometry is deleted after the mirror.  There is no tooltip.  Symmetry constraint is added by default and cannot be changed.

`[x] Copy`  (no tooltip)

* Major Competitor B:  Symmetry constraints is added by default and copy is the default behavior, neither can be changed.  There is no option to delete original geometry.

@maxwxyz maybe you can offer a suggestion here?

**Comment by xtemp09** [comment]
@skelliam, I "requested change" because I don't want this PR to be merged automatically or by accident. Your words clearly show that you do not understand.


I say that move is translation, mirror is reflection, this wording is misleading. This link, I hope, will help.


https://www.brainfuse.com/jsp/alc/resource.jsp?s=gre&c=37810&cc=108830

**Comment by skelliam** [comment]
@xtemp09 You want a technical, mathematical explanation in a tooltip.  I'm a mechanical engineer with 27 years of experience.  This is UX versus Engineering, and this PR is a UX change.  The "feeling" or "experience" of the user will be that of "moving" the geometry.

The examples I provided are from SolidWorks (A) and Fusion 360 (B).  SolidWorks has a checkbox labeled "Copy", and no tooltip.  This is not a mathematically precise checkbox (do you agree?), yet millions of users understand what it does and use it every day.  In my opinion, FreeCAD struggles with excessive verbosity in many places.  The checkbox itself is accompanied by a sentence that the user has to stop and comprehend, the tooltip's job is to offer clarification.  The word 'move' is what is triggering to you.

How about: "Removes the original geometry and keeps only the mirrored result."  (introducing the word "reflect" in my opinion adds further confusion, the tool itself is called "mirror")

Would this unblock this PR for you, or do we need to wait for someone wise?

**Comment by xtemp09** [comment]
Yes, sounds good.

File: src/Mod/Sketcher/Gui/DrawSketchHandlerSymmetry.h [hunk 2]
```diff
@@ -280,10 +280,25 @@ void DSHSymmetryController::configureToolWidget()
             WCheckbox::FirstBox,
             QApplication::translate("TaskSketcherTool_c1_symmetry", "Delete original geometries (U)")
         );
+        toolWidget->setCheckboxToolTip(
+            WCheckbox::FirstBox,
+            QApplication::translate(
+                "TaskSketcherTool_c1_symmetry",
+                "Deletes the original geometry. This effectively performs a 'Move' operation."
```
Comment (skelliam) [inline src/Mod/Sketcher/Gui/DrawSketchHandlerSymmetry.h]:
```suggestion
                "Removes the original geometry and keeps only the mirrored result."
```

**Comment by skelliam** [comment]
> > The "feeling" or "experience" of the user will be that of "moving" the geometry.
> 
> You are talking about offset.

No, I'm not.  When something removed from one place but put in another place it is moved.  You don't like the word move because the geometry is also transformed in the process, **and I can see this point**.  It is a deeply technical argument.  SolidWorks just calls this exact checkbox "copy", with no tooltip or clarification, and it absolutely clear what this box does, because it is within the context of the mirror tool.  I assume you take issue with it, because it is not copied, it is mirrored about an axis.

**Comment by skelliam** [comment]
Changing this checkbox to simply `[x] Move` and making the tooltip clarify that statement by saying, "delete original geometry after mirror operation" would simplify this whole thing greatly, but then we would be back to the whole 'move' argument.   The checkbox is already within the context of mirror -- that's how you get to it, is by clicking mirror.  In my opinion, there's no further explanation needed at that point.

**Comment by xtemp09** [comment]
I looked into vocabulary and found that "to move" means "to change place".

**Comment by skelliam** [comment]
> I looked into vocabulary and found that "to move" means "to change place".

And copy?  "a thing made to be similar or identical to another."

Yet everyone understands what is meant when you first click Mirror and then you enable a checkbox option that says "Copy".   There is no question that you are no longer mirroring and instead copying.  This is an option of the mirror feature.

The same if you click "Mirror" and then enable a checkbox option that says "Move", to me there is zero doubt what is happening.  You are mirroring but deleting the original.

Common file system operations, all of them copy to a new location and delete the original:
- `mv` in Linux
- `move` in cmd shell
- `Move-Item` in powershell
- `std::memmove` in C++

**Comment by xtemp09** [comment]
"Copy" and "move" do not change the object, while reflection does.


> And copy? "a thing made to be similar or identical to another."


Mirror does not produce identical object, it produces a transformed (reflected) object.

**Comment by skelliam** [comment]
> "Copy" and "move" do not change the object, while reflection does.
> 
> > And copy? "a thing made to be similar or identical to another."
> 
> Mirror does not produce identical object, it produces a transformed (reflected) object.

You are repeating what I [already said](https://github.com/FreeCAD/FreeCAD/pull/27131#issuecomment-3800000179).  I understand there is a transformation and this point is taken.

This is about user experience and simplicity.  If FreeCAD wants every checkbox and tooltip to be full sentences, ok, that's definitely an approach.

------

You don't agree with the word copy, but millions of users understand what is happening here without a tooltip, even if you don't agree with it.

### SolidWorks (7.5 million users, 400k companies)
Mirror (action taken by user)
- [x] Copy (option provided by the action)

------

Current situation.  Unnecessarily verbose, but ok.

### FreeCAD
Mirror (action)
- [ ] Delete original geometries (U) --> tooltip:  "Removes the original geometry and keeps only the mirrored result."

------

This would be understood by everyone with no tooltip necessary, even though you disagree with it.

### FreeCAD
Mirror (action)
- [ ] Move 

------

This is my last comment on this topic, because it isn't productive.
