### PR TITLE
Base: use magnitude for unit schema thresholds

### LINKED ISSUE #28409: FEM: unit prefixes not applied to negative values (FC 1.1 RC3)
### Problem description

FEM results like stresses have a minimum and a maximum value in the "Show Result" dialog. Values include units, like "Pa", and for very large values, correct prefixes are used (like "MPa"). But for negative values, prefixes seem to fail.

I see for example:

Minimum value: -34479400.00 Pa
Maximum value: 44.50 MPa

FreeCAD 1.1 RC3

### Workbench affected?

FEM

### Steps to reproduce

Run any FEM simulation and enter the **CCX_Results** window. Select some "stress" value.

### Expected behavior

Both positive and negative values should use proper prefixes. For the example above:

Minimum value: -34.48 MPa
Maximum value: 44.50 MPa

### Actual behavior

Negative values show values without unit multiple prefix, harder to read.

Same seems to happen with "displacements" in "mm". Positive values can show micrometers but negatives are always "mm".

### Development version About Info (in Safe Mode)

```shell
OS: Windows 10 build 19045
Architecture: x86_64
Version: 1.1.0rc3.20260223 (Git shallow)
Build date: 2026/02/23 23:43:19
Build type: Release
Branch: (HEAD detached at adf7760)
Hash: adf77600e2526bf02804524f0d1991ab1c534abe
Python 3.11.14, Qt 6.8.3, Coin 4.0.3, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.3.0, IfcOpenShell 0.8.4, OCC 7.8.1
Locale: Spanish/Spain (es_ES)
Navigation Style/Orbit Style/Rotation Mode: CAD/Trackball/Drag at cursor
Stylesheet/Theme/QtStyle: FreeCAD.qss/FreeCAD Light/
Logical DPI/Physical DPI/Pixel Ratio: 96/102.299/1
```

### Last known good version (optional)

```shell

```

### PR DESCRIPTION
**Pull request by czarflix**
Fix unit schema threshold selection for negative quantities by choosing the
display prefix from the quantity magnitude instead of the signed value.

This fixes FEM result displays where negative values could fall back to the
smallest unit band, for example showing `-34479400.00 Pa` instead of
`-34.479400 MPa`, or keeping small negative displacements in `mm` instead of
displaying them in `µm`.

## Issues
Closes #28409

## Before and After Images
No layout changes. This PR fixes numeric/unit formatting in the existing FEM
result dialog.

Before:
- negative stress values could be shown without the expected prefix, e.g.
  `-34479400.00 Pa`

After:
- negative values use the same threshold selection by magnitude as positive
  values, e.g.
  `-34.479400 MPa`

## Verification
- Added regression coverage in `tests/src/Base/SchemaTests.cpp` for:
  - negative stress remaining in `MPa`
  - negative sub-millimeter length displaying in `µm`
- Ran locally:
  - `Base_tests_run --gtest_filter=SchemaTest.mks_negative_values_use_magnitude_for_threshold_selection`
  - `Base_tests_run --gtest_filter=SchemaTest.sweep_mks:SchemaTest.sweep_internal`
- Manually verified the FEM `Show Result` dialog with negative result values and
  confirmed that negative values now keep the expected unit prefixes.

### CODE REVIEW

File: tests/src/Base/SchemaTests.cpp [hunk 1]
```diff
@@ -1233,6 +1233,24 @@ TEST_F(SchemaTest, sweep_mks)
...
+        auto quantity = Quantity::parse(raw);
+        QuantityFormat fmt(QuantityFormat::Default);
+        quantity.setFormat(fmt);
+        double factor {};
+        std::string unitString;
+        return UnitsApi::schemaTranslate(quantity, factor, unitString);
+    };
+
+    EXPECT_EQ(translate("-34.479400 MPa"), "-34.479400 MPa");
+    EXPECT_EQ(translate("-0.001000 mm"), "-1.000000 \xC2\xB5m");
```
Comment (hyarion) [inline tests/src/Base/SchemaTests.cpp]: IIRC locale causes issues with comma separators in unit tests. Is it possible to use something which doesn't require decimals?

Comment (czarflix) [reply tests/src/Base/SchemaTests.cpp]: I’ll update the test to ignore decimal padding and just check that the correct unit band is selected for negative values.
