### PR TITLE
Gui: Fix crash in measuring tool after an undo.

### LINKED ISSUE #25038: Crash with measuring tool
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Problem description

I occasionally get a crash when selecting edges of an imported solid to measure.  I haven't yet been able to reproduce it consistently.  It looks like there's a null pointer dereference.

### Full version info

```shell
OS: macOS 15.6.1
Architecture: x86_64
Version: 1.1.0dev.14555 (Git shallow)
Build date: 2025/10/14 15:14:51
Build type: Release
Branch: main
Hash: 41ce37233d64c81c2f105de085635d4dcd669943
Python 3.11.14, Qt 6.8.3, Coin 4.0.3, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.3.0, IfcOpenShell 0.8.2, OCC 7.8.1
Locale: English/United States (en_US)
Navigation Style/Orbit Style/Rotation Mode: Touchpad/Trackball/Drag at cursor
Stylesheet/Theme/QtStyle: FreeCAD Light.qss/FreeCAD Light/
Logical DPI/Physical DPI/Pixel Ratio: 72/132.25/2
Installed mods: 
  * InventorLoader 1.5.1
  * Manipulator 1.6.3
  * sheetmetal 0.7.58
```

### Subproject(s) affected?

Measurement

### Anything else?

Here's the stack trace:

```
Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000
Exception Codes:       0x0000000000000001, 0x0000000000000000

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [16819]

VM Region Info: 0 is not in any region.  Bytes before following region: 4373360640
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                      104ac3000-104ae6000    [  140K] r-x/r-x SM=COW  /Applications/FreeCAD-dev/FreeCAD.app/Contents/Resources/bin/freecad

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   libsystem_platform.dylib      	    0x7ff810effe92 _platform_strlen + 18
1   libFreeCADApp.dylib           	       0x105244067 App::Document::removeObject(char const*) + 55
2   MeasureGui.so                 	       0x126015db7 MeasureGui::TaskMeasure::tryUpdate() + 1575
3   MeasureGui.so                 	       0x1260168ea MeasureGui::TaskMeasure::onSelectionChanged(Gui::SelectionChanges const&) + 218
4   libFreeCADGui.dylib           	       0x107c34768 Gui::SelectionObserver::_onSelectionChanged(Gui::SelectionChanges const&) + 40
5   libFreeCADGui.dylib           	       0x10773e0ad boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, Gui::SelectionChanges const&>, std::__1::__list_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::__1::pair<boost::signals2::detail::slot_meta_group, boost::optional<int>>, boost::signals2::slot<void (Gui::SelectionChanges const&), boost::function<void (Gui::SelectionChanges const&)>>, boost::signals2::mutex>>, void*>, boost::signals2::detail::connection_body<std::__1::pair<boost::signals2::detail::slot_meta_group, boost::optional<int>>, boost::signals2::slot<void (Gui::SelectionChanges const&), boost::function<void (Gui::SelectionChanges const&)>>, boost::signals2::mutex>>::dereference() const + 77
6   libFreeCADGui.dylib           	       0x10773dbb1 boost::signals2::detail::signal_impl<void (Gui::SelectionChanges const&), boost::signals2::optional_last_value<void>, int, std::__1::less<int>, boost::function<void (Gui::SelectionChanges const&)>, boost::function<void (boost::signals2::connection const&, Gui::SelectionChanges const&)>, boost::signals2::mutex>::operator()(Gui::SelectionChanges const&) + 609
7   libFreeCADGui.dylib           	       0x107c38d67 Gui::SelectionSingleton::slotSelectionChanged(Gui::SelectionChanges const&) + 311
8   libFreeCADGui.dylib           	       0x10773e0ad boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type, Gui::SelectionChanges const&>, std::__1::__list_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::__1::pair<boost::signals2::detail::slot_meta_group, boost::optional<int>>, boost::signals2::slot<void (Gui::SelectionChanges const&), boost::function<void (Gui::SelectionChanges const&)>>, boost::signals2::mutex>>, void*>, boost::signals2::detail::connection_body<std::__1::pair<boost::signals2::detail::slot_meta_group, boost::optional<int>>, boost::signals2::slot<void (Gui::SelectionChanges const&), boost::function<void (Gui::SelectionChanges const&)>>, boost::signals2::mutex>>::dereference() const + 77
9   libFreeCADGui.dylib           	       0x10773dbb1 boost::signals2::detail::signal_impl<void (Gui::SelectionChanges const&), boost::signals2::optional_last_value<void>, int, std::__1::less<int>, boost::function<void (Gui::SelectionChanges const&)>, boost::function<void (boost::signals2::connection const&, Gui::SelectionChanges const&)>, boost::signals2::mutex>::operator()(Gui::SelectionChanges const&) + 609
10  libFreeCADGui.dylib           	       0x107c379ec Gui::SelectionSingleton::notify(Gui::SelectionChanges&&) + 428
11  libFreeCADGui.dylib           	       0x107c3f436 Gui::SelectionSingleton::clearCompleteSelection(bool) + 1606
12  libFreeCADGui.dylib           	       0x1078275d6 Gui::SoFCUnifiedSelection::setSelection(std::__1::vector<Gui::SoFCUnifiedSelection::PickedInfo, std::__1::allocator<Gui::SoFCUnifiedSelection::PickedInfo>> const&, bool) + 5030
13  libFreeCADGui.dylib           	       0x10782874e Gui::SoFCUnifiedSelection::handleEvent(SoHandleEventAction*) + 398
14  libCoin.80.0.3.dylib          	       0x10b2fa489 SoAction::traverse(SoNode*) + 105
15  libCoin.80.0.3.dylib          	       0x10b4c5293 SoChildList::traverse(SoAction*, int, int) + 131
16  libCoin.80.0.3.dylib          	       0x10b518b75 SoGroup::doAction(SoAction*) + 101
17  libCoin.80.0.3.dylib          	       0x10b534658 SoSeparator::handleEvent(SoHandleEventAction*) + 40
18  libCoin.80.0.3.dylib          	       0x10b2fa489 SoAction::traverse(SoNode*) + 105
19  libCoin.80.0.3.dylib          	       0x10b30523d SoHandleEventAction::beginTraversal(SoNode*) + 157
20  libCoin.80.0.3.dylib          	       0x10b2fa1da SoAction::apply(SoNode*) + 362
21  libCoin.80.0.3.dylib          	       0x10b4e0391 SoEventManager::actuallyProcessEvent(SoEvent const*) + 97
22  libFreeCADGui.dylib           	       0x107976f5c SIM::Coin3D::Quarter::QuarterWidget::processSoEvent(SoEvent const*) + 28
23  libFreeCADGui.dylib           	       0x10797e293 SIM::Coin3D::Quarter::SoQTQuarterAdaptor::processSoEvent(SoEvent const*) + 131
24  libFreeCADGui.dylib           	       0x1079f710f Gui::NavigationStyle::processSoEvent(SoEvent const*) + 79
25  libFreeCADGui.dylib           	       0x107a033f8 Gui::TouchpadNavigationStyle::processSoEvent(SoEvent const*) + 1480
26  libFreeCADGui.dylib           	       0x1079f6e34 Gui::NavigationStyle::processEvent(SoEvent const*) + 180
27  libFreeCADGui.dylib           	       0x10799ddff Gui::View3DInventorViewer::processSoEvent(SoEvent const*) + 175
28  libFreeCADGui.dylib           	       0x107970e9f SIM::Coin3D::Quarter::EventFilter::eventFilter(QObject*, QEvent*) + 335
29  libQt6Core.6.8.3.dylib        	       0x106e38940 QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) + 240
30  libQt6Widgets.6.8.3.dylib     	       0x109e90934 QApplicationPrivate::notify_helper(QObject*, QEvent*) + 292
31  libQt6Widgets.6.8.3.dylib     	       0x109e92e7e QApplication::notify(QObject*, QEvent*) + 6014
32  libFreeCADGui.dylib           	       0x1073c122c Gui::GUIApplication::notify(QObject*, QEvent*) + 92
33  libQt6Core.6.8.3.dylib        	       0x106e38602 QCoreApplication::notifyInternal2(QObject*, QEvent*) + 162
34  libQt6Widgets.6.8.3.dylib     	       0x109e90f5b QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) + 875
35  libQt6Widgets.6.8.3.dylib     	       0x109dfd988 QWidgetWindow::handleMouseEvent(QMouseEvent*) + 2040
36  libQt6Widgets.6.8.3.dylib     	       0x109dfc613 QWidgetWindow::event(QEvent*) + 115
37  libQt6Widgets.6.8.3.dylib     	       0x109e90948 QApplicationPrivate::notify_helper(QObject*, QEvent*) + 312
38  libQt6Widgets.6.8.3.dylib     	       0x109e918ee QApplication::notify(QObject*, QEvent*) + 494
39  libFreeCADGui.dylib           	       0x1073c122c Gui::GUIApplication::notify(QObject*, QEvent*) + 92
40  libQt6Core.6.8.3.dylib        	       0x106e38602 QCoreApplication::notifyInternal2(QObject*, QEvent*) + 162
41  libQt6Gui.6.8.3.dylib         	       0x10a698102 QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) + 2562
42  libQt6Gui.6.8.3.dylib         	       0x10a5e2e3b QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 459
43  libqcocoa.dylib               	       0x10caab6b0 QCocoaEventDispatcherPrivate::postedEventsSourceCallback(void*) + 448
44  CoreFoundation                	    0x7ff810fb2ab0 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
45  CoreFoundation                	    0x7ff810fb2a52 __CFRunLoopDoSource0 + 157
46  CoreFoundation                	    0x7ff810fb280d __CFRunLoopDoSources0 + 203
47  CoreFoundation                	    0x7ff810fb1476 __CFRunLoopRun + 973
48  CoreFoundation                	    0x7ff810fb0a72 CFRunLoopRunSpecific + 536
49  HIToolbox                     	    0x7ff81caa20d4 RunCurrentEventLoopInMode + 281
50  HIToolbox                     	    0x7ff81caa4e60 ReceiveNextEventCommon + 188
51  HIToolbox                     	    0x7ff81cc2e19a _BlockUntilNextEventMatchingListInModeWithFilter + 63
52  AppKit                        	    0x7ff814a15db1 _DPSNextEvent + 912
53  AppKit                        	    0x7ff8154a4137 -[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1263
54  AppKit                        	    0x7ff814a06e99 -[NSApplication run] + 610
55  libqcocoa.dylib               	       0x10caa8e28 QCocoaEventDispatcher::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 2808
56  libQt6Core.6.8.3.dylib        	       0x106e39296 QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 534
57  libQt6Core.6.8.3.dylib        	       0x106e38efc QCoreApplication::exec() + 156
58  libFreeCADGui.dylib           	       0x1072d601f Gui::Application::runApplication() + 2511
59  freecad                       	       0x104ac7b9e main + 3646
60  dyld                          	    0x7ff810b24530 start + 3056
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by pjcreath**
Updates TaskMeasure to listen for object deletion signals to update its internal state.

## Issues
Fixes #25038.

### CODE REVIEW

File: src/Mod/Measure/Gui/TaskMeasure.cpp [hunk 1]
```diff
@@ -163,6 +163,11 @@ TaskMeasure::TaskMeasure()
     // engage the selectionObserver
     attachSelection();
 
+    if (auto* doc = App::GetApplication().getActiveDocument()) {
+        m_deletedConnection = doc->signalDeletedObject.connect(
+            std::bind(&TaskMeasure::onObjectDeleted, this, std::placeholders::_1));
```
Comment (chennes) [inline src/Mod/Measure/Gui/TaskMeasure.cpp]: The linter is proposing a slight simplification:
```suggestion
            [this](auto && obj) { onObjectDeleted(obj); });
```

**Comment by chennes** [comment]
Thanks for the fix, @pjcreath  -- I can confirm that this fixes #25038. I don't really feel that strongly about the linter complaint, but the code it proposes is indeed slightly more readable. I can include that suggestion when I merge the PR, unless you object.
