### PR TITLE
PartDesign: Enable multi-selection in Additive/Subtractive Pipe edges list

### LINKED ISSUE #24368: PartDesign: Cannot select multiple items on the Edges list on Additive/Subtractive Loft/Pipe
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Problem description

Cannot select multiple items on the Edges list manually on the PartDesign Subtractive Pipe Edges List.
Ctrl or Shift doesn't work there. 
Ctrl+A doesn't work either. It selects all the objects in the Tree view instead.

The add Edge is horrible to use.
I have to click on it for EVERY edge I have to select. 

Image

### Full version info

```shell
OS: Ubuntu 25.04 (ubuntu:GNOME/ubuntu-xorg/xcb)
Architecture: x86_64
Version: 1.1.0dev.14555 (Git shallow)
Build date: 2025/09/30 23:55:55
Build type: Release
Branch: main
Hash: b08a0f87d68dd38cfcf39046209a7075adf11576
Python 3.11.13, Qt 6.8.3, Coin 4.0.3, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.3.0, IfcOpenShell 0.8.2, OCC 7.8.1
Locale: English/United States (en_US)
Navigation Style/Orbit Style/Rotation Mode: Touchpad/Trackball/Drag at cursor
Stylesheet/Theme/QtStyle: OpenDark.qss/OpenDark/
Logical DPI/Physical DPI/Pixel Ratio: 96/94.0767/1
Installed mods: 
  * Assembly4.1 0.60.2-0.1
  * Cables 0.2.1
  * CurvesWB 0.6.64
  * FreeCAD-render 2024.12.15
  * Assembly4 0.60.2
  * sheetmetal 0.7.55
  * DynamicData 2.75.0
  * Curves 0.6.70
  * InventorLoader 1.5.1
  * diff-tools 0.1.0
  * ose-piping
  * Assembly4.1_mod 0.60.2-0.1
  * OpenTheme 2025.5.20
  * fasteners 0.5.42
  * Silk 0.2.0
  * osh-autodoc-workbench 0.2.3
  * CurvedShapes 1.0.13
  * freecad-povray-render
  * OpticsWorkbench 1.2.2
  * lattice2 1.0.0
  * kicadStepUpMod 11.7.6
```

### Subproject(s) affected?

PartDesign

### Anything else?

_No response_

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Gaurang-2005**
Fixes #24368

This PR enables proper multi-selection in the PartDesign Additive/Subtractive Pipe edges list.

Changes:
- Allow Ctrl/Shift multi-selection in edges list
- Fix "Remove edge" button to delete multiple selected edges
- Add Ctrl+A support for selecting all edges

This improves usability and makes the Pipe tool consistent with other tools like Fillet/Chamfer.

## Before and After Images

Before: Could only add/remove one edge at a time  

image

After: Multiple edges can be selected and removed together
Screenshot 2026-02-28 225128

### CODE REVIEW

File: src/Mod/PartDesign/Gui/TaskPipeParameters.cpp [hunk 1]
```diff
@@ -73,6 +73,19 @@ TaskPipeParameters::TaskPipeParameters(ViewProviderPipe* PipeView, bool /*newObj
     // we need a separate container widget to add all controls to
     proxy = new QWidget(this);
     ui->setupUi(proxy);
+    // Enable multi-selection in edges list
+    ui->listWidgetReferences->setSelectionMode(QAbstractItemView::ExtendedSelection);
+
+    // Make Remove edge button work on selection
+    connect(ui->buttonRefRemove, &QToolButton::clicked, this, &TaskPipeParameters::onDeleteEdge);
```
Comment (chennes) [inline src/Mod/PartDesign/Gui/TaskPipeParameters.cpp]: `buttonRefRemove` is a mode toggle button -- I don't understand connecting it directly to an action. Can you explain?

Comment (Gaurang-2005) [reply src/Mod/PartDesign/Gui/TaskPipeParameters.cpp]: Good point. I connected the `clicked` signal here only to trigger deletion
of the currently selected references from `listWidgetReferences`.

I wasn't intending to use `buttonRefRemove` as a persistent "remove mode",
but rather as a convenience action to remove the selected edges.

If the intended design is to use it strictly as a mode toggle (using
`toggled(bool)` and enabling a removal mode), I can update the implementation
accordingly.

Comment (chennes) [reply src/Mod/PartDesign/Gui/TaskPipeParameters.cpp]: It's possible I'm misunderstanding: I thought that `buttonRefRemove` existed prior to this PR, and was used *only* as a mode toggle. It is `checkable` according to the ui file, and its only handling that I can see is via the changed signal in the button group.

Comment (Gaurang-2005) [reply src/Mod/PartDesign/Gui/TaskPipeParameters.cpp]: Thank you for the clarification — I appreciate you pointing that out.

I hadn't noticed that `buttonRefRemove` was already defined as checkable in the UI and intended to function as a mode toggle. My change effectively treated it as a direct action, which doesn't align with that design.

I'll update the implementation to respect the toggle behavior instead of triggering deletion directly from the `clicked` signal.

Comment (Gaurang-2005) [reply src/Mod/PartDesign/Gui/TaskPipeParameters.cpp]: I have removed that connect and pushed the updated code
