### PR TITLE
PartDesign: Attachment dialog on new sketch

### LINKED ISSUE #11133: PartDesign/Sketcher: Ability to open Attachment task at Sketch creation
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Hi,
At sketch creation a "Select Plane" task is opened. It's very limited as it doesn't offer to offset the plane or to rotate it and user has to change the MapMode or the Attachment Offset after the creation.

If the Attachment task could be opened it would improve the workflow.

### Full version info

```shell
[code]
OS: Debian GNU/Linux trixie/sid (XFCE/lightdm-xsession)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.34594 (Git)
Build type: Unknown
Branch: main
Hash: 3d9e3fa809e7dbc3ec60ed23195759b5aff4ed54
Python 3.11.6, Qt 5.15.10, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: French/France (fr_FR)
[/code]
```

### Subproject(s) affected?

PartDesign

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #22507: PartDesign: Sketch Attachment does not open with preselection
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Problem description

Follow up to https://github.com/FreeCAD/FreeCAD/pull/18441

When setting `Preferences/Mod/PartDesign/NewSketchUseAttachmentDialog` to `true` the attachment dialog opens when clicking on the new sketch button in Part Design.

However, if a face or datum is already preselected, the dialog does not open, instead the sketch edit mode opens.

If this is fixed, IMO the Preferences/Mod/PartDesign/NewSketchUseAttachmentDialog should be set to true by default.

### Full version info

```shell
OS: Windows 11 build 22631
Architecture: x86_64
Version: 1.1.0dev.42325 (Git)
Build date: 2025/06/24 17:49:05
Build type: Release
Branch: main
Hash: f3980c8a6fd65f82d3e61d229d26ad0eb57265c1
Python 3.11.13, Qt 6.8.3, Coin 4.0.3, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.2.5, IfcOpenShell 0.8.2, OCC 7.8.1
Locale: German/Germany (de_DE)
Navigation Style/Orbit Style/Rotation Mode: CAD/Rounded Arcball/Window center
Stylesheet/Theme/QtStyle: FreeCAD Light.qss/FreeCAD Light/
Logical DPI/Physical DPI/Pixel Ratio: 96/92.6073/1
Installed mods: 
  * Cables 0.2.0
  * Curves 0.6.63
  * Defeaturing 1.2.6
  * FusedFilamentDesign 0.25.220
  * OpticsWorkbench 1.2.2
```

### Subproject(s) affected?

PartDesign

### Anything else?

_No response_

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### LINKED ISSUE #26760: Core: Clicking OK without selecting the attachment reference changes the appearance of the origin and datum planes
### Problem description

This is what remains after fixing #24309 - transparency is not affected anymore, but the planes still become smaller and lose their labels:

Image

Image

### Workbench affected?

Core (App, Gui,...)

### Steps to reproduce

1. In an empty file, go to Part Design.
2. Click New Sketch.
3. Instead of selecting a plane, click OK.

OR:

1. Click Coordinate System or Datum Plane in any workbench.
2. Without selecting any attachment reference, click OK.

### Expected behavior

The appearance of origin/datum planes doesn't change.

### Actual behavior

The planes become smaller and lose their labels.

### Development version About Info (in Safe Mode)

```shell
OS: Windows 10 build 19045
Architecture: x86_64
Version: 1.2.0dev.20260106 (Git shallow)
Build date: 2026/01/06 15:36:19
Build type: Release
Branch: (HEAD detached at 9b64da8)
Hash: 9b64da827a112d88a025be26316e3d023ff491dc
Python 3.11.14, Qt 6.8.3, Coin 4.0.3, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.3.0, IfcOpenShell 0.8.2, OCC 7.8.1
Locale: Polish/Poland (pl_PL)
Navigation Style/Orbit Style/Rotation Mode: CAD/Rounded Arcball/Window center
Stylesheet/Theme/QtStyle: unset/FreeCAD Light/
Logical DPI/Physical DPI/Pixel Ratio: 96/90.0633/1
```

### Last known good version (optional)

```shell

```

### PR DESCRIPTION
**Pull request by maxwxyz**
1. Adds a preference for the already existing parameter to open the attachment dialog when a new sketch is created in Part Design
2. Fix issue to show attachment dialog also with a preselection

With AI help.

Based on DWG discussion this default behavior:

- show attachment when nothing is selected
- show attachment when something is selected that is not planar
- do NOT show attachment when ONE planar element is selected (face, datum,...)
- show attachment when a Sketch is preselected and do NOT populate attachment dialog with that sketch
- show attachment with Shift+Click regardless of selection
- confirm attachment when double clicking the first selection entry in the 3D view
- preference to show attachment always (default off)

## Issues

Fixes https://github.com/FreeCAD/FreeCAD/issues/11133
Fixes https://github.com/FreeCAD/FreeCAD/issues/22507

#### Before:
This thing:

Bildschirmfoto 2026-04-08 um 08 17 07

#### After: 

https://github.com/user-attachments/assets/c0424fcf-f991-47d1-af1b-072dee1792f2

### CODE REVIEW

**Review by PaddleStroke — APPROVED** [review]
Looks good to me

File: src/Mod/PartDesign/Gui/SketchWorkflow.cpp [hunk 1]
```diff
@@ -584,12 +584,46 @@ class SketchRequestSelection
...
+        // Don't pre-populate when the selection contains sketches. A sketch selected
+        // from prior work should not automatically become the attachment reference —
+        // the user can choose a face or plane in the dialog.
+        bool hasSketch = std::any_of(
+            support.getValues().begin(),
+            support.getValues().end(),
+            [](App::DocumentObject* obj) {
+                return obj && obj->isDerivedFrom(Part::Part2DObject::getClassTypeId());
+            }
+        );
```
Comment (hyarion) [inline src/Mod/PartDesign/Gui/SketchWorkflow.cpp]:
```suggestion
        bool hasSketch = std::ranges::any_of(
            support.getValues(),
            [](App::DocumentObject* obj) {
                return obj && obj->isDerivedFrom(Part::Part2DObject::getClassTypeId());
            }
        );
```

**Review by hyarion — COMMENTED** [review]
we can use ranges in c++20 so we don't need to use the begin and end iterator

**Review by FEA-eng — APPROVED** [review]
Tested, works as expected. There's some failed CI, though.

File: src/Mod/PartDesign/Gui/SketchWorkflow.cpp [hunk 2]
```diff
@@ -584,12 +584,42 @@ class SketchRequestSelection
...
+        // This mirrors UnifiedDatumCommand: use attacher to find the best fit mode.
+        App::PropertyLinkSubList support;
+        Gui::Selection().getAsPropertyLinkSubList(support);
+        support.removeValue(activeBody);
+
+        // Don't pre-populate when the selection contains sketches. A sketch selected
+        // from prior work should not automatically become the attachment reference —
+        // the user can choose a face or plane in the dialog.
+        bool hasSketch = std::ranges::any_of(support.getValues(), [](App::DocumentObject* obj) {
+            return obj && obj->isDerivedFrom(Part::Part2DObject::getClassTypeId());
```
Comment (hyarion) [inline src/Mod/PartDesign/Gui/SketchWorkflow.cpp]:
```suggestion
            return obj && obj->isDerivedFrom<Part::Part2DObject>();
```

File: src/Mod/PartDesign/Gui/SketchWorkflow.cpp [hunk 3]
```diff
@@ -584,12 +584,42 @@ class SketchRequestSelection
...
+
         // Create sketch
         App::Document* doc = activeBody->getDocument();
         std::string FeatName = doc->getUniqueObjectName("Sketch");
         FCMD_OBJ_CMD(activeBody, "newObject('Sketcher::SketchObject','" << FeatName << "')");
         auto sketch = doc->getObject(FeatName.c_str());
 
+        if (!hasSketch && support.getSize() > 0) {
+            auto* pcAttach = sketch->getExtensionByType<Part::AttachExtension>();
+            if (pcAttach) {
```
Comment (hyarion) [inline src/Mod/PartDesign/Gui/SketchWorkflow.cpp]:
```suggestion
            if (auto* pcAttach = sketch->getExtensionByType<Part::AttachExtension>()) {
```

File: src/Mod/Part/Gui/TaskAttacher.cpp [hunk 4]
```diff
@@ -1451,6 +1454,48 @@ void TaskAttacher::visibilityAutomation(bool opening_not_closing)
 // TaskDialog
 //++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 
+// Installs an application-wide double-click filter for the lifetime of a
+// TaskDlgAttacher created with an onAccept callback (i.e. new-object creation).
+// When the user double-clicks while the dialog is open and at least one
+// attachment reference has been set, the dialog is accepted automatically.
+class AttachmentDblClickAccepter: public QObject
```
Comment (kadet1090) [inline src/Mod/Part/Gui/TaskAttacher.cpp:1461]: That seems like really strange solution, why install it application wide? It should be handled with Coin probably - see how sketcher implements it.

**Review by FEA-eng — APPROVED** [review]
Still works very well. It's a really handy feature!

**Comment by kadet1090** [comment]
Seems to work well. As a follow-up please add input hints to the feature so users are aware about the double click.
