### PR TITLE
App: Random fixes 1

### LINKED ISSUE #21095: Mesh: Weird crash at `App::Transaction::addObjectChange`
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Problem description

I have a macro that fixes a mesh, converts to solid, then deletes mesh object:
```
# -*- coding: utf-8 -*-

import FreeCAD
import Mesh
import Part
import OpenSCADUtils

sel = FreeCADGui.Selection.getSelection()
print(sel)
for x in sel:
	if x.Mesh.CountFacets == 0:
		App.ActiveDocument.removeObject(x.Label)
		continue
	if not x.Mesh.isSolid():
		x.Mesh.fillupHoles(5000)
	if x.Mesh.isSolid():
		s = Part.Shape()
		s.makeShapeFromMesh(x.Mesh.Topology, 0.100000, True)
		s = s.removeSplitter()
		o = App.ActiveDocument.addObject("Part::Feature",x.Label+ "_solid")
		o.Shape = Part.Solid(s)
		App.ActiveDocument.removeObject(x.Name)
App.ActiveDocument.recompute()
```
As part of my workflow I often encountered the following stacktrace SIGSEGV
```
(gdb) bt
#0  0x00007ffff569367a in App::Transaction::addObjectChange(App::TransactionalObject const*, App::Property const*) () at /usr/lib/freecad-daily-python3/lib/libFreeCADApp.so
#1  0x00007ffff62865d4 in Gui::ViewProviderDocumentObject::onBeforeChange(App::Property const*) () at /usr/lib/freecad-daily-python3/lib/libFreeCADGui.so
#2  0x00007ffff571dd87 in App::PropertyEnumeration::setEnums(char const**) () at /usr/lib/freecad-daily-python3/lib/libFreeCADApp.so
#3  0x00007ffff6291db6 in Gui::ViewProviderDocumentObject::attach(App::DocumentObject*) () at /usr/lib/freecad-daily-python3/lib/libFreeCADGui.so
#4  0x00007fff29f0f2bd in MeshGui::ViewProviderFace::attach(App::DocumentObject*) () at /usr/lib/freecad-daily-python3/lib/MeshGui.so
#5  0x00007fff29f0d5f6 in MeshGui::MeshFaceAddition::startEditing(MeshGui::ViewProviderMesh*) () at /usr/lib/freecad-daily-python3/lib/MeshGui.so
#6  0x00007fff29f10f55 in CmdMeshAddFacet::activated(int) () at /usr/lib/freecad-daily-python3/lib/MeshGui.so
#7  0x00007ffff5f4718f in Gui::Command::_invoke(int, bool) () at /usr/lib/freecad-daily-python3/lib/libFreeCADGui.so
#8  0x00007ffff5f4753e in Gui::Command::invoke(int, Gui::Command::TriggerSource) () at /usr/lib/freecad-daily-python3/lib/libFreeCADGui.so
#9  0x00007ffff3312e16 in ??? () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#10 0x00007ffff3f64f94 in QAction::triggered(bool) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#11 0x00007ffff3f67eab in QAction::activate(QAction::ActionEvent) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#12 0x00007ffff406967a in ??? () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#13 0x00007ffff40697b8 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#14 0x00007ffff416d446 in QToolButton::mouseReleaseEvent(QMouseEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#15 0x00007ffff3fb0df8 in QWidget::event(QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#16 0x00007ffff3f6bd45 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#17 0x00007ffff3f746b0 in QApplication::notify(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#18 0x00007ffff5f052fe in Gui::GUIApplication::notify(QObject*, QEvent*) () at /usr/lib/freecad-daily-python3/lib/libFreeCADGui.so
#19 0x00007ffff32d8118 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#20 0x00007ffff3f72874 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#21 0x00007ffff3fcaa39 in ??? () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#22 0x00007ffff3fcdfbf in ??? () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#23 0x00007ffff3f6bd45 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#24 0x00007ffff5f052fe in Gui::GUIApplication::notify(QObject*, QEvent*) () at /usr/lib/freecad-daily-python3/lib/libFreeCADGui.so
#25 0x00007ffff32d8118 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#26 0x00007ffff3745a3b in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#27 0x00007ffff3717bfc in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#28 0x00007fffed57bd06 in ??? () at /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#29 0x00007ffff15145b5 in ??? () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#30 0x00007ffff1573717 in ??? () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#31 0x00007ffff1513a53 in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#32 0x00007ffff3335279 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#33 0x00007ffff32d6a7b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#34 0x00007ffff32df3e8 in QCoreApplication::exec() () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#35 0x00007ffff5e814bf in Gui::Application::runApplication() () at /usr/lib/freecad-daily-python3/lib/libFreeCADGui.so
#36 0x000055555555a3da in ??? ()
#37 0x00007ffff282a1ca in __libc_start_call_main (main=main@entry=0x555555559dd0, argc=argc@entry=1, argv=argv@entry=0x7fffffffdd28) at ../sysdeps/nptl/libc_start_call_main.h:58
#38 0x00007ffff282a28b in __libc_start_main_impl (main=0x555555559dd0, argc=1, argv=0x7fffffffdd28, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffdd18) at ../csu/libc-start.c:360
#39 0x000055555555b4a5 in ??? ()

```

#### Steps to reproduce:
1. document with 2 closed meshes (eg 2 cubes, and then mesh -> Create mesh from shape)
1. select one mesh.
1. run macro 
1. select other mesh
1. click  on Mesh -> Add triangle  
Result: crash

Let me know if you need anything more

### Full version info

```shell
OS: Linux Mint 22.1 (X-Cinnamon/cinnamon/xcb)
Architecture: x86_64
Version: 1.1.0dev.40971 (Git)
Build date: 2025/03/24 18:02:34
Build type: Release
Branch: main
Hash: b33c2363226a5fc1e8222a02659118c95e1a5119
Python 3.12.3, Qt 5.15.13, Coin 4.0.2, Vtk 9.1.0, OCC 7.8.1
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Dark/Qt default
Logical DPI/Physical DPI/Pixel Ratio: 96/92.6073/1
Installed mods: 
  * MeshRemodel 1.10.37
  * boltsfc 2022.11.5
  * fasteners 0.5.38
  * ThreadProfile 1.93.0
```

### Subproject(s) affected?

Mesh

### Anything else?

_No response_

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by 3x380V**
These are random, hopefully non controversial, fixes from @wwmayer's branch plus one fix inspired by #27148

Mitigates #19866
Fixes #21095

### CODE REVIEW

File: src/App/Property.cpp [hunk 1]
```diff
@@ -114,36 +116,36 @@ std::string Property::getFileName(const char* postfix, const char* prefix) const
...
-    GET_PTYPE(Hidden);
-    GET_PTYPE(Output);
-    GET_PTYPE(Transient);
-    GET_PTYPE(NoRecompute);
-    GET_PTYPE(NoPersist);
+    std::for_each(mapProps.begin(), mapProps.end(), [&type, this](const auto& item) {
+        if (testStatus(std::get<0>(item))) {
+            type |= std::get<1>(item);
+        }
+    });
```
Comment (kadet1090) [inline src/App/Property.cpp]: Is there any benefit of using for_each here instead of simply range-based for loop? With the for loop you could use structured bindings to make the code more readable and give the properties meaningful names instead of relying on indices:

Same thing applies to other for_each uses.

```suggestion
    for (const auto& [propertyStatus, propertyType] : mapProps) {
        if (testStatus(propertyStatus)) {
            type |= propertyType;
        }
    }
```

File: src/App/PropertyLinks.cpp [hunk 2]
```diff
@@ -4281,14 +4281,12 @@ void PropertyXLink::Restore(Base::XMLReader& reader)
...
 
-    assert(getContainer()->isDerivedFrom<App::DocumentObject>());
     DocumentObject* object = nullptr;
     if (!name.empty() && file.empty()) {
-        DocumentObject* parent = static_cast<DocumentObject*>(getContainer());
-        Document* document = parent->getDocument();
-        object = document ? document->getObject(name.c_str()) : nullptr;
-        if (!object) {
-            if (reader.isVerbose()) {
+        if (auto parent = dynamic_cast<DocumentObject*>(getContainer())) {
```
Comment (kadet1090) [inline src/App/PropertyLinks.cpp]:
```suggestion
        if (auto parent = freecad_cast<DocumentObject*>(getContainer())) {
```
