### PR TITLE
Gui: FileDialog: fix Windows issues introduced in #23209

### LINKED ISSUE #29212: Latest nightly build can not export to IGES - unless the user put the correct extenson on the filename
### Problem description

When exporting - FreeCAD no longer puts the correct file-extenion on by itself

If I e.g. want to export to IGES and just put in a file-name (without an extension) then:
```
11:56:52  <Gui> Exporting with 'Part' is deprecated, use 'ImportGui' instead
11:56:52  <Exception> Unknown extension
11:56:52  pyException: Traceback (most recent call last):
  File "<string>", line 8, in <module>
<class 'RuntimeError'>: FreeCAD exception thrown (Unknown extension)
```

FreeCAD version:
```
OS: Windows 11 build 26200
Architecture: x86_64
Version: 1.2.0dev.20260407 (Git shallow)
Build date: 2026/04/07 22:56:13
Build type: Release
Branch: (HEAD detached at 6db886fe0)
Hash: 6db886fe0e79bf060ffeaa50198da25702a17e31
Python 3.11.15, Qt 6.8.3, Coin 4.0.8, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.3.0, IfcOpenShell 0.8.2, OCC 7.8.1
Locale: C/Default (C) [ OS: Danish/Denmark (da_DK) ]
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/
Navigation Style/Orbit Style/Rotation Mode: Blender/Trackball/Drag at cursor
Logical DPI/Physical DPI/Pixel Ratio: 96/141.951/1
Installed mods:
  * A2plus 0.4.68
  * CfdOF 1.34.8
  * Defeaturing Workbench 1.3.1
  * Optics Design Workbench 0.7.3
  * Manipulator Workbench 1.6.4
  * Mesh Remodel 1.11.0
  * Optics 1.2.2
  * Quick Measure 2022.10.28
  * SheetMetal Workbench 0.8.10
  * toSketch 1.0.1
  * workfeature

```

### Workbench affected?

None

### Steps to reproduce

[box.zip](https://github.com/user-attachments/files/26599359/box.zip)

Select the boly named "body" in the tree
Goto "File" -> "Export" 
Choose "IGES" format
write a file-name
Choose "export"

### Expected behavior

An exported IGES-file with the correct extension

### Actual behavior

11:56:52  <Gui> Exporting with 'Part' is deprecated, use 'ImportGui' instead
11:56:52  <Exception> Unknown extension
11:56:52  pyException: Traceback (most recent call last):
  File "<string>", line 8, in <module>
<class 'RuntimeError'>: FreeCAD exception thrown (Unknown extension)

### Development version About Info (in Safe Mode)

```shell
OS: Windows 11 build 26200
Architecture: x86_64
Version: 1.2.0dev.20260407 (Git shallow)
Build date: 2026/04/07 22:56:13
Build type: Release
Branch: (HEAD detached at 6db886fe0)
Hash: 6db886fe0e79bf060ffeaa50198da25702a17e31
Python 3.11.15, Qt 6.8.3, Coin 4.0.8, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.3.0, IfcOpenShell 0.8.2, OCC 7.8.1
Locale: C/Default (C) [ OS: Danish/Denmark (da_DK) ]
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/
Navigation Style/Orbit Style/Rotation Mode: Blender/Trackball/Drag at cursor
Logical DPI/Physical DPI/Pixel Ratio: 96/141.951/1
Installed mods:
  * A2plus 0.4.68
  * CfdOF 1.34.8
  * Defeaturing Workbench 1.3.1
  * Optics Design Workbench 0.7.3
  * Manipulator Workbench 1.6.4
  * Mesh Remodel 1.11.0
  * Optics 1.2.2
  * Quick Measure 2022.10.28
  * SheetMetal Workbench 0.8.10
  * toSketch 1.0.1
  * workfeature
```

### Last known good version (optional)

```shell
OS: Windows 11 build 26200
Architecture: x86_64
Version: 1.2.0dev.20260324 (Git shallow)
Build date: 2026/03/24 17:14:33
Build type: Release
Branch: (HEAD detached at 1bc5980a7)
Hash: 1bc5980a7ff302a55c617181e774cd5cd2a9443a
Python 3.11.15, Qt 6.8.3, Coin 4.0.8, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.3.0, IfcOpenShell 0.8.2, OCC 7.8.1
Locale: Danish/Denmark (da_DK)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/
Navigation Style/Orbit Style/Rotation Mode: Blender/Trackball/Drag at cursor
Logical DPI/Physical DPI/Pixel Ratio: 96/141.951/1
Installed mods:
  * A2plus 0.4.68
  * CfdOF 1.34.8
  * Defeaturing Workbench 1.3.1
  * Optics Design Workbench 0.7.3
  * Manipulator Workbench 1.6.4
  * Mesh Remodel 1.11.0
  * Optics 1.2.2
  * Quick Measure 2022.10.28
  * SheetMetal Workbench 0.8.10
  * toSketch 1.0.1
  * workfeature
```

### LINKED ISSUE #29238: core: using the gui version of freecad the file open dialogue crashes freecad whenever attempting to open a file.
### Problem description

freecad crashes when using file -> open from the freecad gui when attempting to open a file.

### Workbench affected?

None

### Steps to reproduce

stated above

### Expected behavior

to not have the application crash

### Actual behavior

crash.

stack trace from crash.

```
╰─λ /opt/code/fcgit/installs/issue.tshooting.qt6.py313/bin/FreeCAD
FreeCAD 1.2.0, Libs: 1.2.0devR46320 (Git)
(C) 2001-2026 FreeCAD contributors
FreeCAD is free and open-source software licensed under the terms of LGPL2+ license.

Program received signal SIGSEGV, Segmentation fault.
#0  linux-vdso.so.1(__kernel_rt_sigreturn+0) [0xffffaacd8860]
#1  /home/capin/homebrew/lib/libQt6Core.so.6(+0x5099dc) [0xffffa46199dc]
#2  0xffffa43cacb8 in QString::operator=(QString const&) from /home/capin/homebrew/lib/libQt6Core.so.6+0x38
#3  0xffffa8fc0820 in Gui::FileDialog::getOpenFileNames(QWidget*, QString const&, QString const&, QList<QString> const&, QString*, QFlags<QFileDialog::Option>) from /opt/code/fcgit/installs/issue.tshooting.qt6.py313/lib/libFreeCADGui.so+0x20c
#4  0xffffa8bc6100 in StdCmdOpen::activated(int) from /opt/code/fcgit/installs/issue.tshooting.qt6.py313/lib/libFreeCADGui.so+0x400
#5  0xffffa8bb678c in Gui::Command::_invoke(int, bool) from /opt/code/fcgit/installs/issue.tshooting.qt6.py313/lib/libFreeCADGui.so+0x1a4
#6  0xffffa8bb6580 in Gui::Command::invoke(int, Gui::Command::TriggerSource) from /opt/code/fcgit/installs/issue.tshooting.qt6.py313/lib/libFreeCADGui.so+0x1b4
#7  /home/capin/homebrew/lib/libQt6Core.so.6(+0x21b390) [0xffffa432b390]
#8  0xffffa4f33f44 in QAction::triggered(bool) from /home/capin/homebrew/lib/libQt6Gui.so.6+0x44
#9  0xffffa4f36ef8 in QAction::activate(QAction::ActionEvent) from /home/capin/homebrew/lib/libQt6Gui.so.6+0xd0
#10  /home/capin/homebrew/lib/libQt6Widgets.so.6(+0x3aa79c) [0xffffa570a79c]
#11  /home/capin/homebrew/lib/libQt6Widgets.so.6(+0x3b2c28) [0xffffa5712c28]
#12  0xffffa558af2c in QWidget::event(QEvent*) from /home/capin/homebrew/lib/libQt6Widgets.so.6+0x22c
#13  0xffffa5525850 in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /home/capin/homebrew/lib/libQt6Widgets.so.6+0x60
#14  0xffffa552ee38 in QApplication::notify(QObject*, QEvent*) from /home/capin/homebrew/lib/libQt6Widgets.so.6+0x338
#15  0xffffa8b5762c in Gui::GUIApplication::notify(QObject*, QEvent*) from /opt/code/fcgit/installs/issue.tshooting.qt6.py313/lib/libFreeCADGui.so+0x70
#16  0xffffa42b7a04 in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /home/capin/homebrew/lib/libQt6Core.so.6+0x184
#17  /home/capin/homebrew/lib/libQt6Widgets.so.6(+0x3b3b30) [0xffffa5713b30]
#18  0xffffa5713e04 in QMenu::mouseReleaseEvent(QMouseEvent*) from /home/capin/homebrew/lib/libQt6Widgets.so.6+0x78
#19  0xffffa558af2c in QWidget::event(QEvent*) from /home/capin/homebrew/lib/libQt6Widgets.so.6+0x22c
#20  0xffffa5525850 in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /home/capin/homebrew/lib/libQt6Widgets.so.6+0x60
#21  0xffffa552ee38 in QApplication::notify(QObject*, QEvent*) from /home/capin/homebrew/lib/libQt6Widgets.so.6+0x338
#22  0xffffa8b5762c in Gui::GUIApplication::notify(QObject*, QEvent*) from /opt/code/fcgit/installs/issue.tshooting.qt6.py313/lib/libFreeCADGui.so+0x70
#23  0xffffa42b7a04 in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /home/capin/homebrew/lib/libQt6Core.so.6+0x184
#24  0xffffa552e3c8 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) from /home/capin/homebrew/lib/libQt6Widgets.so.6+0x568
#25  /home/capin/homebrew/lib/libQt6Widgets.so.6(+0x23f284) [0xffffa559f284]
#26  /home/capin/homebrew/lib/libQt6Widgets.so.6(+0x241550) [0xffffa55a1550]
#27  0xffffa5525850 in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /home/capin/homebrew/lib/libQt6Widgets.so.6+0x60
#28  0xffffa8b5762c in Gui::GUIApplication::notify(QObject*, QEvent*) from /opt/code/fcgit/installs/issue.tshooting.qt6.py313/lib/libFreeCADGui.so+0x70
#29  0xffffa42b7a04 in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /home/capin/homebrew/lib/libQt6Core.so.6+0x184
#30  0xffffa4b74844 in QWindowPrivate::forwardToPopup(QEvent*, QWindow const*) from /home/capin/homebrew/lib/libQt6Gui.so.6+0x434
#31  0xffffa4b0b2e8 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) from /home/capin/homebrew/lib/libQt6Gui.so.6+0x258
#32  0xffffa4b7e4b8 in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /home/capin/homebrew/lib/libQt6Gui.so.6+0xd8
#33  /home/capin/homebrew/Cellar/qtbase/6.11.0/share/qt/plugins/platforms/../../../../lib/libQt6XcbQpa.so.6(+0x5ece8) [0xffff910aece8]
#34  /home/capin/homebrew/lib/libglib-2.0.so.0(+0x63458) [0xffff9ded3458]
#35  /home/capin/homebrew/lib/libglib-2.0.so.0(+0x6693c) [0xffff9ded693c]
#36  /home/capin/homebrew/lib/libglib-2.0.so.0(g_main_context_iteration+0x38) [0xffff9ded7198]
#37  0xffffa45e81c4 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /home/capin/homebrew/lib/libQt6Core.so.6+0x58
#38  0xffffa42c5544 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) from /home/capin/homebrew/lib/libQt6Core.so.6+0x19c
#39  0xffffa42c04a8 in QCoreApplication::exec() from /home/capin/homebrew/lib/libQt6Core.so.6+0x9c
#40  0xffffa8acb13c in Gui::Application::runApplication() from /opt/code/fcgit/installs/issue.tshooting.qt6.py313/lib/libFreeCADGui.so+0x8ec
#41  /opt/code/fcgit/installs/issue.tshooting.qt6.py313/bin/FreeCAD(+0x925c) [0xaaab214d925c]
#42  /lib64/libc.so.6(+0x2621c) [0xffffa3ac621c]
#43  /lib64/libc.so.6(__libc_start_main+0x9c) [0xffffa3ac62fc]
#44  /opt/code/fcgit/installs/issue.tshooting.qt6.py313/bin/FreeCAD(+0x8530) [0xaaab214d8530]
```

### Development version About Info (in Safe Mode)

```shell
OS: Fedora Linux 42 (Adams) (tty)
Architecture: arm64
Version: 1.2.0dev.46319 (Git)
Build date: 2026/04/10 00:00:20
Build type: Release
Branch: main
Hash: b9f467a221404d96f52c57741ac105714580042d
Python 3.13.12, Qt 6.11.0, Coin 4.0.8, Vtk 9.5.2, boost 1_90, Eigen3 5.0.1, PySide 6.11.0
shiboken 6.11.0, SMESH 7.7.1.0, xerces-c 3.3.0, IfcOpenShell 0.8.4.post1, OCC 7.9.3
Locale: English/United States (en_US) [ OS: English/United States (en_US) ]
Stylesheet/Theme/QtStyle: FreeCAD.qss/FreeCAD Light/
Navigation Style/Orbit Style/Rotation Mode: Blender/Trackball/Drag at cursor
Logical DPI/Physical DPI/Pixel Ratio: 96/95.958/1
```

### Last known good version (optional)

```shell
wasn't happening a day ago.
```

### LINKED ISSUE #29302: Core: Access violation when canceling save
### Problem description

Perhaps it's related to the crashes that recently started to appear (likely after the multidocument PR), but this one is very easy to reproduce.

### Workbench affected?

Core (App, Gui,...)

### Steps to reproduce

1. Start FreeCAD.
2. Create new document.
3. Click Save.
4. Click Cancel.

### Expected behavior

no Access Violation / crash

### Actual behavior

Access Violation / crash

### Development version About Info (in Safe Mode)

```shell
OS: Windows 11 build 26200
Architecture: x86_64
Version: 1.2.0dev.20260407 (Git shallow)
Build date: 2026/04/07 22:56:13
Build type: Release
Branch: (HEAD detached at 6db886fe0)
Hash: 6db886fe0e79bf060ffeaa50198da25702a17e31
Python 3.11.15, Qt 6.8.3, Coin 4.0.8, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.3.0, OCC 7.8.1
Locale: Polish/Poland (pl_PL)
Stylesheet/Theme/QtStyle: FreeCAD.qss/FreeCAD Light/
Navigation Style/Orbit Style/Rotation Mode: Blender/Rounded Arcball/Window center
Logical DPI/Physical DPI/Pixel Ratio: 96/81.5973/1
```

### Last known good version (optional)

```shell

```

### LINKED ISSUE #29451: Windows weekly regression: Export dialog filename is blank, and closing Export dialog can trigger Access Violation
### Problem description

In weekly-2026.04.08 and weekly-2026.04.15 on Windows, opening File → Export shows an empty filename field instead of a prefilled default name.
In the same builds, exporting to STL may trigger an "Access violation" exception.
In some cases, even just opening the Export dialog and then closing it without exporting can already trigger the exception.
weekly-2026.04.01 does not show this behavior.

### Workbench affected?

None

### Steps to reproduce

Open a Part Design file with a Body / Pad / Pocket.
Select the object to export.
Click File → Export.
Observe that the filename field is blank in affected builds.
Either:
try exporting as STL, or
simply close the Export dialog.
An Access violation exception may appear.

Image

Image

### Expected behavior

Export dialog should prefill a default filename based on the selected object or document name.
Closing the Export dialog without exporting should not trigger any exception.
Export to STL should complete normally.

### Actual behavior

In recent Windows weekly builds, the Export dialog behaves incorrectly.

In weekly-2026.04.08 and weekly-2026.04.15, when I open File → Export, the filename field is empty instead of being automatically prefilled as in earlier builds.

If I try to export to STL, FreeCAD may show an "Access violation" exception.

In some cases, even if I only open the Export dialog and then close it without exporting anything, the same "Access violation" exception still appears.

This did not happen in weekly-2026.04.01, where the Export dialog correctly prefilled the filename and no exception occurred.

### Development version About Info (in Safe Mode)

```shell
OS: Windows 11 build 26200
Architecture: x86_64
Version: 1.2.0dev.20260415 (Git shallow)
Build date: 2026/04/15 00:45:21
Build type: Release
Branch: (HEAD detached at 36786d479)
Hash: 36786d47949a449b3a8585354ef8c75a1c67c03b
Python 3.11.15, Qt 6.8.3, Coin 4.0.8, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.3.0, IfcOpenShell 0.8.2, OCC 7.8.1
Locale: Chinese/Taiwan (zh_TW) [ OS: Chinese/Taiwan (zh_TW) ]
Stylesheet/Theme/QtStyle: FreeCAD.qss/FreeCAD Light/
Navigation Style/Orbit Style/Rotation Mode: CAD/Rounded Arcball/Window center
Logical DPI/Physical DPI/Pixel Ratio: 96/36.1069/1.75
```

### Last known good version (optional)

```shell
OS: Windows 11 build 26200
Architecture: x86_64
Version: 1.2.0dev.20260401 (Git shallow)
Build date: 2026/04/01 04:43:57
Build type: Release
Branch: (HEAD detached at 33dcd31f5)
Hash: 33dcd31f5e2175e7dcdfd3caf1d9d86440919bfc
Python 3.11.15, Qt 6.8.3, Coin 4.0.8, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.3.0, IfcOpenShell 0.8.2, OCC 7.8.1
Locale: Chinese/Taiwan (zh_TW)
Stylesheet/Theme/QtStyle: FreeCAD.qss/FreeCAD Dark/
Navigation Style/Orbit Style/Rotation Mode: OpenSCAD/Turntable/Drag at cursor
Logical DPI/Physical DPI/Pixel Ratio: 96/36.1069/1.75
Installed mods:
  * Fasteners Workbench 0.5.38
  * FEMbyGEN 2.4.0
  * OpenTheme 2024.9.1
  * ThreadProfile 1.96.0
```

### LINKED ISSUE #29453: FreeCAD_weekly-2026.04.15-Linux-x86_64.AppImage crashes when opening any file
### Problem description

FreeCAD crashes during opening any .FCStd file.

Even opening a file just created with exactly the same version does cause the crash

Callstack:
```
Program received signal SIGSEGV, Segmentation fault.
#0  /lib/x86_64-linux-gnu/libc.so.6(+0x45f60) [0x743d69845f60]
#1  0x743d6a273299 in QString::operator=(QString const&) from /tmp/.mount_FreeCAlodppb/usr/bin/../lib/libQt6Core.so.6+0x19
#2  0x743d703f5c2d in Gui::FileDialog::getOpenFileNames(QWidget*, QString const&, QString const&, QList<QString> const&, QString*, QFlags<QFileDialog::Option>) from /tmp/.mount_FreeCAlodppb/usr/bin/../lib/libFreeCADGui.so+0x28d
#3  0x743d6ff51fe5 in StdCmdOpen::activated(int) from /tmp/.mount_FreeCAlodppb/usr/bin/../lib/libFreeCADGui.so+0x6d5
#4  0x743d6ff3ef58 in Gui::Command::_invoke(int, bool) from /tmp/.mount_FreeCAlodppb/usr/bin/../lib/libFreeCADGui.so+0x208
#5  0x743d6ff3ed00 in Gui::Command::invoke(int, Gui::Command::TriggerSource) from /tmp/.mount_FreeCAlodppb/usr/bin/../lib/libFreeCADGui.so+0x150
#6  /tmp/.mount_FreeCAlodppb/usr/bin/../lib/libQt6Core.so.6(+0x31684a) [0x743d6a31684a]
#7  0x743d6adca8c7 in QAction::triggered(bool) from /tmp/.mount_FreeCAlodppb/usr/bin/../lib/libQt6Gui.so.6+0x47
#8  0x743d6adcddc6 in QAction::activate(QAction::ActionEvent) from /tmp/.mount_FreeCAlodppb/usr/bin/../lib/libQt6Gui.so.6+0xf6
#9  /tmp/.mount_FreeCAlodppb/usr/bin/../lib/libQt6Widgets.so.6(+0x4adb49) [0x743d6b6adb49]
#10  0x743d6b6add6d in QAbstractButton::mouseReleaseEvent(QMouseEvent*) from /tmp/.mount_FreeCAlodppb/usr/bin/../lib/libQt6Widgets.so.6+0xbd
#11  0x743d6b4da9fd in QToolButton::mouseReleaseEvent(QMouseEvent*) from /tmp/.mount_FreeCAlodppb/usr/bin/../lib/libQt6Widgets.so.6+0x2d
#12  0x743d6b7c3864 in QWidget::event(QEvent*) from /tmp/.mount_FreeCAlodppb/usr/bin/../lib/libQt6Widgets.so.6+0xa64
#13  0x743d6b7b3e48 in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /tmp/.mount_FreeCAlodppb/usr/bin/../lib/libQt6Widgets.so.6+0x88
#14  0x743d6b7b4cbd in QApplication::notify(QObject*, QEvent*) from /tmp/.mount_FreeCAlodppb/usr/bin/../lib/libQt6Widgets.so.6+0xdad
#15  0x743d6fecff88 in Gui::GUIApplication::notify(QObject*, QEvent*) from /tmp/.mount_FreeCAlodppb/usr/bin/../lib/libFreeCADGui.so+0x78
#16  0x743d6a35fb8a in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /tmp/.mount_FreeCAlodppb/usr/bin/../lib/libQt6Core.so.6+0x17a
#17  0x743d6b7bbe7c in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) from /tmp/.mount_FreeCAlodppb/usr/bin/../lib/libQt6Widgets.so.6+0x1ec
#18  /tmp/.mount_FreeCAlodppb/usr/bin/../lib/libQt6Widgets.so.6(+0x5be8c7) [0x743d6b7be8c7]
#19  /tmp/.mount_FreeCAlodppb/usr/bin/../lib/libQt6Widgets.so.6(+0x5c5440) [0x743d6b7c5440]
#20  0x743d6b7b3e48 in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /tmp/.mount_FreeCAlodppb/usr/bin/../lib/libQt6Widgets.so.6+0x88
#21  0x743d6fecff88 in Gui::GUIApplication::notify(QObject*, QEvent*) from /tmp/.mount_FreeCAlodppb/usr/bin/../lib/libFreeCADGui.so+0x78
#22  0x743d6a35fb8a in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /tmp/.mount_FreeCAlodppb/usr/bin/../lib/libQt6Core.so.6+0x17a
#23  0x743d6a9d1970 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) from /tmp/.mount_FreeCAlodppb/usr/bin/../lib/libQt6Gui.so.6+0x810
#24  0x743d6aa31e14 in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /tmp/.mount_FreeCAlodppb/usr/bin/../lib/libQt6Gui.so.6+0xb4
#25  /tmp/.mount_FreeCAlodppb/usr/lib/qt6/plugins/platforms/../../../libQt6XcbQpa.so.6(+0x58f90) [0x743d6616cf90]
#26  /tmp/.mount_FreeCAlodppb/usr/bin/../lib/./libglib-2.0.so.0(+0x5bde6) [0x743d67906de6]
#27  /tmp/.mount_FreeCAlodppb/usr/bin/../lib/./libglib-2.0.so.0(+0x5f0a7) [0x743d6790a0a7]
#28  /tmp/.mount_FreeCAlodppb/usr/bin/../lib/./libglib-2.0.so.0(g_main_context_iteration+0x2e) [0x743d6790a81e]
#29  0x743d6a0f6b12 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /tmp/.mount_FreeCAlodppb/usr/bin/../lib/libQt6Core.so.6+0x72
#30  0x743d6a39747c in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) from /tmp/.mount_FreeCAlodppb/usr/bin/../lib/libQt6Core.so.6+0x25c
#31  0x743d6a3977da in QCoreApplication::exec() from /tmp/.mount_FreeCAlodppb/usr/bin/../lib/libQt6Core.so.6+0x9a
#32  0x743d6fe3fcbc in Gui::Application::runApplication() from /tmp/.mount_FreeCAlodppb/usr/bin/../lib/libFreeCADGui.so+0xc4c
#33  /tmp/.mount_FreeCAlodppb/usr/bin/freecad(+0xa0bf) [0x59d8d33020bf]
#34  /lib/x86_64-linux-gnu/libc.so.6(+0x2a575) [0x743d6982a575]
#35  /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x88) [0x743d6982a628]
#36  /tmp/.mount_FreeCAlodppb/usr/bin/freecad(+0x9189) [0x59d8d3301189]

```

### Workbench affected?

None

### Steps to reproduce

Open an existing .FCStd file (any).

### Expected behavior

no crash when opening a file

### Actual behavior

crashes when opening any file, even a one just saved with  this version

### Development version About Info (in Safe Mode)

```shell
1. I am using the current development version
2. In Safe mode the problem does NOT occure
3. The problem still occures after disabling all AddOns
4. The problem still occures after renaming user.cfg to user.cfg.bck


Version Info:

OS: Ubuntu 25.10 (ubuntu:GNOME/ubuntu/wayland)
Architecture: x86_64
Version: 1.2.0dev.20260415 (Git shallow) AppImage
Build date: 2026/04/15 00:45:21
Build type: Release
Branch: (HEAD detached at 36786d479)
Hash: 36786d47949a449b3a8585354ef8c75a1c67c03b
Python 3.11.14, Qt 6.8.3, Coin 4.0.8, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.3.0, IfcOpenShell 0.8.2, OCC 7.8.1
Locale: German/Germany (de_DE)
Stylesheet/Theme/QtStyle: FreeCAD.qss/FreeCAD Dark/
Navigation Style/Orbit Style/Rotation Mode: Touchpad/Trackball/Drag at cursor
Logical DPI/Physical DPI/Pixel Ratio: 96/118.106/1
Installed mods:
  * Fasteners Workbench 0.5.51 (Disabled)
  * Curves workbench 0.6.71 (Disabled)
  * KicadStepUp Workbench 11.8.2 (Disabled)
  * Better Tool Library 0.9.9
  * Cables Workbench 0.3.5 (Disabled)


Version info (in SaveMode)
OS: Ubuntu 25.10 (ubuntu:GNOME/ubuntu/wayland)
Architecture: x86_64
Version: 1.2.0dev.20260415 (Git shallow) AppImage
Build date: 2026/04/15 00:45:21
Build type: Release
Branch: (HEAD detached at 36786d479)
Hash: 36786d47949a449b3a8585354ef8c75a1c67c03b
Python 3.11.14, Qt 6.8.3, Coin 4.0.8, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.3.0, IfcOpenShell 0.8.2, OCC 7.8.1
Locale: German/Germany (de_DE)
Stylesheet/Theme/QtStyle: FreeCAD.qss/FreeCAD Light/
Navigation Style/Orbit Style/Rotation Mode: CAD/Rounded Arcball/Window center
Logical DPI/Physical DPI/Pixel Ratio: 96/118.106/1
```

### Last known good version (optional)

```shell
FreeCAD_weekly-2026.04.01-Linux-x86_64.AppImage

Version info:
OS: Ubuntu 25.10 (ubuntu:GNOME/ubuntu/wayland)
Architecture: x86_64
Version: 1.2.0dev.20260401 (Git shallow) AppImage
Build date: 2026/04/01 04:43:57
Build type: Release
Branch: (HEAD detached at 33dcd31f5)
Hash: 33dcd31f5e2175e7dcdfd3caf1d9d86440919bfc
Python 3.11.14, Qt 6.8.3, Coin 4.0.8, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.3.0, IfcOpenShell 0.8.2, OCC 7.8.1
Locale: German/Germany (de_DE)
Stylesheet/Theme/QtStyle: FreeCAD.qss/FreeCAD Dark/
Navigation Style/Orbit Style/Rotation Mode: Touchpad/Trackball/Drag at cursor
Logical DPI/Physical DPI/Pixel Ratio: 96/118.106/1
Installed mods:
  * Fasteners Workbench 0.5.51 (Disabled)
  * Curves workbench 0.6.71 (Disabled)
  * KicadStepUp Workbench 11.8.2 (Disabled)
  * Better Tool Library 0.9.9
  * Cables Workbench 0.3.5 (Disabled)

Version info in SafeMode:
OS: Ubuntu 25.10 (ubuntu:GNOME/ubuntu/wayland)
Architecture: x86_64
Version: 1.2.0dev.20260401 (Git shallow) AppImage
Build date: 2026/04/01 04:43:57
Build type: Release
Branch: (HEAD detached at 33dcd31f5)
Hash: 33dcd31f5e2175e7dcdfd3caf1d9d86440919bfc
Python 3.11.14, Qt 6.8.3, Coin 4.0.8, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.3.0, IfcOpenShell 0.8.2, OCC 7.8.1
Locale: German/Germany (de_DE)
Stylesheet/Theme/QtStyle: FreeCAD.qss/FreeCAD Light/
Navigation Style/Orbit Style/Rotation Mode: CAD/Rounded Arcball/Window center
Logical DPI/Physical DPI/Pixel Ratio: 96/118.106/1
```

### PR DESCRIPTION
**Pull request by ElementW**
* Supersedes #29268
* Supersedes #29240
* Fixes #29212
* Fixes #29183
* Fixes #29302
* Fixes #29451
* Fixes #29238
* Fixes #29453
* Fixes name field not being populated with suggested file name
* Fixes Windows dialog not picking an extension if you did not specify one

My first FileDialog rework broke Windows support around the edges because the legacy file dialog APIs there simply do not behave like the modern `IFileDialog` ones used by Qt in ways that are either:
1. completely undocumented, or
2. badly expressed
   * Looking at you [need to call `IFileDialog::SetDefaultExtension()` even with an empty string to instruct the file dialog to append an extension on its own](https://learn.microsoft.com/en-us/windows/win32/api/shobjidl_core/nf-shobjidl_core-ifiledialog-setdefaultextension) for which no equivalent exist in the legacy API

This commit sequence (re-)introduces `IFileDialog` use into FreeCAD inherently fixing some of the observed differences. Doing this without reintroducing #23139 comes at the cost of using [undocumented APIs I have discovered](https://elementw.net/posts/microsoft-bs-ifiledialog/).

This required putting said impl in its own file as to not pollute the rest, which needed headers for sharing some of the FC `FileDialog` internal details, in turn meaning I might as well expose the `Filter` struct (name + patterns) and migrate `FileDialog` call sites to it; hence the large amount of files touched like last time[^1].

Also adds (from #29268) some amount of file naming enforcement should the platform APIs not append extensions/match patterns on their own—e.g. Qt/KDE dialogs that have a checkbox for that—but FC currently *depends* on extensions just about everywhere. Hopefully this enforcement can be lifted at some later date as said code would be reworked.

### Testing

Tested on both Linux (KDE) and Windows 11.
In the latter case, typing a name without extension but file filter correctly selected returns a filename with corresponding extension, and the system prompts the user on overwrite (e.g. on IGES filter selected, `abc` typed, `abc.iges` already exists).

Obviously I have not tested every dialog that exists in FC or every possible case with files and their naming, so more is needed.

[^1]: And mind you this is only batch 2 out of 3. Should time and motivation permit, I will attempt migrating most if not all raw pattern filters to a MIME-based system instead, eliminating a lot of the variation in filtering and format handling.

### CODE REVIEW

**Review by FEA-eng — APPROVED** [review]
@maxwxyz Tested on Windows, fixes the issues.

**Review by FEA-eng — APPROVED** [review]
Retested, fixes also #29302

File: src/Mod/Spreadsheet/Gui/Command.cpp [hunk 1]
```diff
@@ -194,16 +194,14 @@ CmdSpreadsheetImport::CmdSpreadsheetImport()
 void CmdSpreadsheetImport::activated(int iMsg)
 {
     Q_UNUSED(iMsg);
-    QString selectedFilter;
-    QStringList formatList;
-    formatList << QObject::tr("CSV (*.csv *.CSV)");
-    formatList << QObject::tr("All (*)");
+    Gui::FileDialog::FilterList formatList;
+    formatList.append({QObject::tr("CSV"), {"*.csv", "*.CSV"}});
```
Comment (xtemp09) [inline src/Mod/Spreadsheet/Gui/Command.cpp]: I noticed that everywhere only lowercase is used, while here the two options are present. Is it correct, or the last option can be safely removed?

File: src/Mod/Spreadsheet/Gui/ViewProviderSpreadsheet.cpp [hunk 2]
```diff
@@ -103,16 +103,15 @@ void ViewProviderSheet::showSheetMdi()
 void ViewProviderSheet::exportAsFile()
 {
     auto* sheet = getObject<Spreadsheet::Sheet>();
-    QString selectedFilter;
-    QStringList formatList;
-    formatList << QObject::tr("CSV (*.csv *.CSV)");
-    formatList << QObject::tr("All (*)");
+    const Gui::FileDialog::FilterList formatList {
+        {QObject::tr("CSV"), {"*.csv", "*.CSV"}},
```
Comment (xtemp09) [inline src/Mod/Spreadsheet/Gui/ViewProviderSpreadsheet.cpp]: The same here.

File: src/Mod/Spreadsheet/Gui/Command.cpp (hunk 1 above)
Comment (ElementW) [reply src/Mod/Spreadsheet/Gui/Command.cpp]: Honestly I don't know and that's a good question. Windows for sure doesn't care, Qt based dialogs (non-native or KDE) don't seem to either, not sure about GTK or macOS.
image
If someone can confirm macOS doesn't care either I guess I can use the opportunity to deduplicate the casings.

Comment (adrianinsaval) [reply src/Mod/Spreadsheet/Gui/Command.cpp]: I believe gtk used to care but I don't know if that's still the case

Comment (ElementW) [reply src/Mod/Spreadsheet/Gui/Command.cpp]: Right yes, GTK *does* care actually, you can see `a.CsV` is missing.
image
(and turns out `QT_QPA_PLATFORMTHEME=gtk3` changes Qt's file dialogs too)

Comment (ElementW) [reply src/Mod/Spreadsheet/Gui/Command.cpp]: I don't have access to a macOS machine so can't test myself but [Qt uses `UTType` objects](https://github.com/qt/qtbase/blob/000d6c62f7880bb8d3054724e8da0b8ae244130e/src/plugins/platforms/cocoa/qcocoafiledialoghelper.mm#L540) for the `NS{Open,Save}Pane` filters, and apparently their `public.filename-extension` property is a `public.case-insensitive-text`, so extension matches are case-insensitive there.

That leaves only GTK, where [the docs do mention the platform-dependent sensitivity](https://docs.gtk.org/gtk4/method.FileFilter.add_pattern.html), and 
* [with qgtkstyle a case-insensitive filter list is built](https://github.com/qt/qt/blob/0a2f2382541424726168804be2c90b91381608c6/src/gui/styles/qgtkstyle_p.cpp#L933-L949), but the RegExp used to extract said list utterly breaks since my previous FileDialog PR as the ext lists are duplicated:
  image
  image
* [with the `gtk3` platformtheme](https://github.com/qt/qtbase/blob/000d6c62f7880bb8d3054724e8da0b8ae244130e/src/plugins/platformthemes/gtk3/qgtk3dialoghelpers.cpp#L489), no case mixing is introduced. Alas it could've been, as the [same sort of extraction is done](https://github.com/qt/qtbase/blob/cd8a057fcf050f1fe7df1b59b9facb135d1518ff/src/gui/kernel/qplatformdialoghelper.cpp#L711-L729) but the regexp actually works, you can try the following in your browser console
  ```js
  [..."Hello (*.abc *.def) (*.real *.ext)".matchAll(/^(.*)\(([a-zA-Z0-9_.,*? +;#\-\[\]@\{\}/!<>\$%&=^~:\|]*)\)$/g)] 
  ```

Ugh. I'm going to explode.

**Comment by ElementW** [comment]
## Open question
Linux with GTK interprets file filters as case sensitive, while other platforms do not. What do?

* **Ignore:** leave as-is (status quo since many versions) where some code uses only one casing, some using more (typically uppercase & lowercase)
* **Hope nobody complains:** remove alternate casings not caring for the GTK consequences
* **Potentially difficult:** try and smoothe out the GTK platform difference and make extension patterns[^1] case-insensitive across the board
* **Menial work:** introduce alternate casings everywhere

[^1]: Specifically *extension/suffix* patterns, not full name patterns. The latter probably isn't supported everywhere anyway.

**Comment by andershol** [comment]
Filenames are case sensitive on linux and not on other platforms (mac is kinda best effort), so it seems correct and expected that filters would behave the same way.

**Comment by ElementW** [comment]
@andershol I'm not saying I'm *surprised* or disappointed by how GTK behaves, it makes sense given everything that's not Windows or macOS with the default HFS+/APFS options is case sensitive, it's just that it creates a difference not otherwise accounted for either in the `FileDialog` code or in how it's used by the rest of FreeCAD.

**Comment by xtemp09** [comment]
I've encountered many times `*.ZIP`, `*.XML`, `*.STP`, `*.OBJ`, `*.JPG`, `*.JPEG`, `*.PNG`, `*.BMP`.


I've never seen `*.PDF`, `*.PY` or `*.SVG`. I've encountered other formats in upper case occasionally.

**Comment by chennes** [comment]
>     * **Ignore:** leave as-is (status quo since many versions) where some code uses only one casing, some using more (typically uppercase & lowercase)

I suggest for the purposes of this PR, "ignore" is an appropriate option. In the long run it would be nice for devs to only have to include the lowercase version, and have some helper code working behind the scenes "fix" it on systems where that is needed. I'd call that "future work" so we don't stall this PR on it.

File: src/Gui/FileDialog.cpp [hunk 3]
```diff
@@ -21,6 +21,9 @@
  ***************************************************************************/
 
 
+#ifndef NDEBUG
+# include <cassert>
```
Comment (ElementW) [inline src/Gui/FileDialog.cpp]: Note to self: remove this blunder.

**Comment by adrianinsaval** [comment]
gtk has to be the snowflake don't it, maybe the solution is to force the qt dialog when `QT_QPA_PLATFORMTHEME=gtk3`, btw is there a gtk4 platform theme? if yes, is the problem still there? In any case chennes is right, that's for another time

**Comment by ElementW** [comment]
@adrianinsaval The environment variable is an override, not the main way Qt chooses the platform integration, of which there are many. No idea if it has an API to query what is in use.
There [doesn't seem to be a gtk4 platformtheme yet](https://github.com/qt/qtbase/tree/3cfa7e094a16eb6eb8eb1bca6da93284c54bad0e/src/plugins/platformthemes) and I'm not sure it's planned since GTK3 is still supported. There is, however, the XDG Portal integration for which [the filters are case-sensitive by spec](https://flatpak.github.io/xdg-desktop-portal/docs/doc-org.freedesktop.portal.FileChooser.html#org-freedesktop-portal-filechooser) (the `filters` param), though actual behavior is up to whatever implementation is running and KDE's evidently does not care; running `gdbus call --session --dest org.freedesktop.portal.Desktop --object-path /org/freedesktop/portal/desktop --method org.freedesktop.portal.FileChooser.OpenFile "" "Hello" "{\"filters\": <[('CSV', [(uint32 0, '*.csv')])]>}"` brings up a CSV-filtered picker that doesn't case about case:
image

File: src/Gui/FileDialogInternal.h [hunk 4]
```diff
@@ -1,9 +1,7 @@
-// SPDX-License-Identifier: LGPL-2.1-or-later
-
 /***************************************************************************
- *   Copyright (c) 2024 Shai Seger <shaise at gmail>                       *
+ *   Copyright (c) 2026 The FreeCAD Project Association AISBL              *
```
Comment (chennes) [inline src/Gui/FileDialogInternal.h]: Just a note that you are under no obligation to assign the copyright to the FPA, you're welcome to put your own info here.

File: src/Gui/FileDialogInternal.h
Comment (chennes) [inline src/Gui/FileDialogInternal.h]: Oh, didn't even notice on the first pass... this is the old header, see https://freecad.github.io/DevelopersHandbook/codeformatting/Copyright-Snippets#c

File: src/Mod/TechDraw/Gui/CommandDecorate.cpp [hunk 5]
```diff
@@ -355,9 +355,10 @@ void CmdTechDrawImage::activated(int iMsg)
     std::string PageName = page->getNameInDocument();
 
     // Reading an image
-    QStringList filterList;
-    filterList << QString::fromUtf8(QT_TR_NOOP("Image files (*.jpg *.jpeg *.png *.bmp)"));
-    filterList << QString::fromUtf8(QT_TR_NOOP("All files (*)"));
+    const Gui::FileDialog::FilterList filterList {
+        {QString::fromUtf8(QT_TR_NOOP("Image files")), {"*.jpg", "*.jpeg", "*.png", "*.bmp"}},
```
Comment (chennes) [inline src/Mod/TechDraw/Gui/CommandDecorate.cpp]: Not really this PR, just noting that `QT_TR_NOOP` looks wrong to me: as far as I can tell there is no later `tr`call, and certainly not one that is using the correct context. It should probably by `tr()` instead.

File: src/Mod/TechDraw/Gui/MDIViewPage.cpp [hunk 6]
```diff
@@ -589,9 +591,10 @@ void MDIViewPage::exportAsPdf() const
 
 QString MDIViewPage::getPdfFileName() const
 {
-    QStringList filter;
-    filter << QObject::tr("PDF (*.pdf)");
-    filter << QObject::tr("All Files (*.*)");
+    const Gui::FileDialog::FilterList filter {
+        {QObject::tr("PDF"), {"*.pdf"}},
```
Comment (chennes) [inline src/Mod/TechDraw/Gui/MDIViewPage.cpp]: Let's drop the `tr()` call from PDF.

File: src/Mod/TechDraw/Gui/Command.cpp [hunk 7]
```diff
@@ -1549,9 +1550,10 @@ void CmdTechDrawSymbol::activated(int iMsg)
     std::string PageName = page->getNameInDocument();
 
     // Reading an image
-    QStringList filterList;
-    filterList << QStringLiteral("%1 (*.svg *.svgz)").arg(QObject::tr("Scalable vector graphic"));
-    filterList << QStringLiteral("%1 (*.*)").arg(QObject::tr("All files"));
+    const Gui::FileDialog::FilterList filterList {
+        {QObject::tr("Scalable vector graphic"), {"*.svg", "*.svgz"}},
```
Comment (chennes) [inline src/Mod/TechDraw/Gui/Command.cpp]: I think we've decided not to translate this one, or spell it out, so may as well fix that while we're touching the line.
```suggestion
        {QStringLiteral("SVG"), {"*.svg", "*.svgz"}},
```

File: src/Mod/TechDraw/Gui/Command.cpp [hunk 8]
```diff
@@ -179,7 +179,7 @@ void CmdTechDrawPageTemplate::activated(int iMsg)
     QString templateDir = Preferences::defaultTemplateDir();
     QString templateFileName = Gui::FileDialog::getOpenFileName(
         Gui::getMainWindow(), QString::fromUtf8(QT_TR_NOOP("Select a template file")), templateDir,
-        QStringList(QString::fromUtf8(QT_TR_NOOP("Template (*.svg)"))));
+        Gui::FileDialog::FilterList{{QString::fromUtf8(QT_TR_NOOP("Template")), {"*.svg"}}});
```
Comment (chennes) [inline src/Mod/TechDraw/Gui/Command.cpp]: `QT_TR_NOOP` is probably wrong here, should be `tr`

File: src/Mod/TechDraw/Gui/Command.cpp [hunk 9]
```diff
@@ -179,7 +179,7 @@ void CmdTechDrawPageTemplate::activated(int iMsg)
     QString templateDir = Preferences::defaultTemplateDir();
     QString templateFileName = Gui::FileDialog::getOpenFileName(
         Gui::getMainWindow(), QString::fromUtf8(QT_TR_NOOP("Select a template file")), templateDir,
```
Comment (chennes) [inline src/Mod/TechDraw/Gui/Command.cpp]: Not your code, but this NOOP is also wrong.

File: src/Mod/Spreadsheet/Gui/ViewProviderSpreadsheet.cpp (hunk 2 above)
Comment (chennes) [inline src/Mod/Spreadsheet/Gui/ViewProviderSpreadsheet.cpp]: No `tr` call on CSV.

File: src/Mod/Spreadsheet/Gui/SpreadsheetView.cpp [hunk 10]
```diff
@@ -297,7 +297,7 @@ void SheetView::printPdf()
         this,
         tr("Export PDF"),
         QString(),
-        QStringList(QStringLiteral("%1 (*.pdf)").arg(tr("PDF file")))
+        FileDialog::FilterList {{tr("PDF file"), {"*.pdf"}}}
```
Comment (chennes) [inline src/Mod/Spreadsheet/Gui/SpreadsheetView.cpp]:
```suggestion
        FileDialog::FilterList {{QStringLiteral("PDF"), {"*.pdf"}}}
```

File: src/Mod/Spreadsheet/Gui/Command.cpp (hunk 1 above)
Comment (chennes) [inline src/Mod/Spreadsheet/Gui/Command.cpp]:
```suggestion
    formatList.append({QStringLiteral("CSV"), {"*.csv", "*.CSV"}});
```

File: src/Mod/Part/Gui/DlgPartImportIgesImp.cpp [hunk 11]
```diff
@@ -63,9 +63,10 @@ void DlgPartImportIgesImp::OnApply()
 
 void DlgPartImportIgesImp::onChooseFileName()
 {
-    QStringList filterList;
-    filterList << QStringLiteral("%1 (*.igs *.iges)").arg(QLatin1String("IGES"));
-    filterList << QStringLiteral("%1 (*.*)").arg(tr("All Files"));
+    const Gui::FileDialog::FilterList filterList {
+        {QLatin1String("IGES"), {"*.igs", "*.iges"}},
```
Comment (chennes) [inline src/Mod/Part/Gui/DlgPartImportIgesImp.cpp]: Just because I usually use QLatin1String as a search term when looking for broken UTF-8 support...
```suggestion
        {QStringLiteral("IGES"), {"*.igs", "*.iges"}},
```

File: src/Mod/Part/Gui/DlgPartImportStepImp.cpp [hunk 12]
```diff
@@ -63,9 +63,10 @@ void DlgPartImportStepImp::OnApply()
 
 void DlgPartImportStepImp::onChooseFileName()
 {
-    QStringList filterList;
-    filterList << QStringLiteral("%1 (*.stp *.step)").arg(QLatin1String("STEP"));
-    filterList << QStringLiteral("%1 (*.*)").arg(tr("All Files"));
+    const Gui::FileDialog::FilterList filterList {
+        {QLatin1String("STEP"), {"*.stp", "*.step"}},
```
Comment (chennes) [inline src/Mod/Part/Gui/DlgPartImportStepImp.cpp]:
```suggestion
        {QStringLiteral("STEP"), {"*.stp", "*.step"}},
```

File: src/Mod/Part/Gui/Command.cpp [hunk 13]
```diff
@@ -1144,22 +1145,23 @@ CmdPartExport::CmdPartExport()
...
-    filter << QStringLiteral("IGES (*.igs *.iges)");
-    filter << QStringLiteral("IGES with colors (*.igs *.iges)");
-    filter << QStringLiteral("BREP (*.brp *.brep)");
-
-    QString select;
+    const Gui::FileDialog::FilterList filter {
+        {QStringLiteral("STEP"), {"*.stp", "*.step"}},
+        {QStringLiteral("STEP with colors"), {"*.stp", "*.step"}},
+        {QStringLiteral("IGES"), {"*.igs", "*.iges"}},
+        {QStringLiteral("IGES with colors"), {"*.igs", "*.iges"}},
```
Comment (chennes) [inline src/Mod/Part/Gui/Command.cpp]:
```suggestion
        {tr("IGES with colors"), {"*.igs", "*.iges"}},
```

File: src/Mod/Part/Gui/Command.cpp [hunk 14]
```diff
@@ -1144,22 +1145,23 @@ CmdPartExport::CmdPartExport()
...
-    filter << QStringLiteral("STEP (*.stp *.step)");
-    filter << QStringLiteral("STEP with colors (*.stp *.step)");
-    filter << QStringLiteral("IGES (*.igs *.iges)");
-    filter << QStringLiteral("IGES with colors (*.igs *.iges)");
-    filter << QStringLiteral("BREP (*.brp *.brep)");
-
-    QString select;
+    const Gui::FileDialog::FilterList filter {
+        {QStringLiteral("STEP"), {"*.stp", "*.step"}},
+        {QStringLiteral("STEP with colors"), {"*.stp", "*.step"}},
```
Comment (chennes) [inline src/Mod/Part/Gui/Command.cpp]:
```suggestion
        {tr("STEP with colors"), {"*.stp", "*.step"}},
```

File: src/Mod/Part/Gui/Command.cpp [hunk 15]
```diff
@@ -1075,14 +1075,15 @@ CmdPartImport::CmdPartImport()
...
+        {QStringLiteral("IGES"), {"*.igs", "*.iges"}},
+        {QStringLiteral("IGES with colors"), {"*.igs", "*.iges"}},
```
Comment (chennes) [inline src/Mod/Part/Gui/Command.cpp]:
```suggestion
        {tr("IGES with colors"), {"*.igs", "*.iges"}},
```

File: src/Mod/Part/Gui/Command.cpp [hunk 16]
```diff
@@ -1075,14 +1075,15 @@ CmdPartImport::CmdPartImport()
...
-    filter << QStringLiteral("STEP (*.stp *.step)");
-    filter << QStringLiteral("STEP with colors (*.stp *.step)");
-    filter << QStringLiteral("IGES (*.igs *.iges)");
-    filter << QStringLiteral("IGES with colors (*.igs *.iges)");
-    filter << QStringLiteral("BREP (*.brp *.brep)");
-
-    QString select;
+    const Gui::FileDialog::FilterList filter {
+        {QStringLiteral("STEP"), {"*.stp", "*.step"}},
+        {QStringLiteral("STEP with colors"), {"*.stp", "*.step"}},
```
Comment (chennes) [inline src/Mod/Part/Gui/Command.cpp]:
```suggestion
        {tr("STEP with colors"), {"*.stp", "*.step"}},
```

File: src/Mod/Mesh/Gui/Command.cpp [hunk 17]
```diff
@@ -352,18 +352,20 @@ CmdMeshImport::CmdMeshImport()
...
+        {QObject::tr("All Mesh Files"),
+         {"*.stl", "*.ast", "*.bms", "*.obj", "*.off", "*.iv", "*.ply", "*.nas", "*.bdf"}},
+        {QObject::tr("Binary STL"), {"*.stl"}},
+        {QObject::tr("ASCII STL"), {"*.ast"}},
+        {QObject::tr("Binary Mesh"), {"*.bms"}},
+        {QObject::tr("Alias Mesh"), {"*.obj"}},
+        {QObject::tr("Object File Format"), {"*.off"}},
+        {QObject::tr("Inventor V2.1 ASCII"), {"*.iv"}},
+        {QObject::tr("Stanford Polygon"), {"*.ply"}},
+        {QObject::tr("NASTRAN"), {"*.nas", "*.bdf"}},
```
Comment (chennes) [inline src/Mod/Mesh/Gui/Command.cpp]:
```suggestion
        {QStringLiteral("NASTRAN"), {"*.nas", "*.bdf"}},
```

File: src/Mod/Import/Gui/Command.cpp [hunk 18]
```diff
@@ -153,7 +153,7 @@ void ImportIges::activated(int iMsg)
         Gui::getMainWindow(),
         QString(),
         QString(),
-        QStringList(QLatin1String("IGES (*.igs *.iges)"))
+        Gui::FileDialog::FilterList {{QLatin1String("IGES"), {"*.igs", "*.iges"}}}
```
Comment (chennes) [inline src/Mod/Import/Gui/Command.cpp]:
```suggestion
        Gui::FileDialog::FilterList {{QStringLiteral("IGES"), {"*.igs", "*.iges"}}}
```

File: src/Mod/Import/Gui/Command.cpp [hunk 19]
```diff
@@ -103,7 +103,7 @@ void ImportStep::activated(int iMsg)
         Gui::getMainWindow(),
         QString(),
         QString(),
-        QStringList(QLatin1String("STEP (*.stp *.step)"))
+        Gui::FileDialog::FilterList {{QLatin1String("STEP"), {"*.stp", "*.step"}}}
```
Comment (chennes) [inline src/Mod/Import/Gui/Command.cpp]:
```suggestion
        Gui::FileDialog::FilterList {{QStringLiteral("STEP"), {"*.stp", "*.step"}}}
```

File: src/Mod/Import/Gui/Command.cpp [hunk 20]
```diff
@@ -58,7 +58,7 @@ void FCCmdImportReadBREP::activated(int iMsg)
         Gui::getMainWindow(),
         QString(),
         QString(),
-        QStringList(QLatin1String("BREP (*.brep *.rle)"))
+        Gui::FileDialog::FilterList {{QLatin1String("BREP"), {"*.brep", "*.rle"}}}
```
Comment (chennes) [inline src/Mod/Import/Gui/Command.cpp]:
```suggestion
        Gui::FileDialog::FilterList {{QStringLiteral("BREP"), {"*.brep", "*.rle"}}}
```

File: src/Gui/View3DInventor.cpp [hunk 21]
```diff
@@ -288,7 +288,7 @@ void View3DInventor::printPdf()
         this,
         tr("Export PDF"),
         QString(),
-        QStringList(QStringLiteral("%1 (*.pdf)").arg(tr("PDF file")))
+        FileDialog::FilterList {{tr("PDF file"), {"*.pdf"}}}
```
Comment (chennes) [inline src/Gui/View3DInventor.cpp]:
```suggestion
        FileDialog::FilterList {{QStringLiteral("PDF"), {"*.pdf"}}}
```

File: src/Gui/MDIView.cpp [hunk 22]
```diff
@@ -284,7 +284,7 @@ void MDIView::printPdf()
         this,
         tr("Export PDF"),
         QString(),
-        QStringList(QStringLiteral("%1 (*.pdf)").arg(tr("PDF file")))
+        FileDialog::FilterList {{tr("PDF file"), {"*.pdf"}}}
```
Comment (chennes) [inline src/Gui/MDIView.cpp]:
```suggestion
        FileDialog::FilterList {{QStringLiteral("PDF"), {"*.pdf"}}}
```

File: src/Gui/GraphvizView.cpp [hunk 23]
```diff
@@ -598,14 +587,14 @@ void GraphvizView::print()
...
-    filter << QStringLiteral("%1 (*.pdf)").arg(tr("PDF format"));
-
-    QString selectedFilter;
-    QString fn
-        = Gui::FileDialog::getSaveFileName(this, tr("Export graph"), QString(), filter, &selectedFilter);
+    QString fn = Gui::FileDialog::getSaveFileName(
+        this,
+        tr("Export graph"),
+        QString(),
+        FileDialog::FilterList {{tr("PDF format"), {"*.pdf"}}}
```
Comment (chennes) [inline src/Gui/GraphvizView.cpp]:
```suggestion
        FileDialog::FilterList {{QStringLiteral("PDF"), {"*.pdf"}}}
```

File: src/Gui/GraphvizView.cpp [hunk 24]
```diff
@@ -474,47 +474,36 @@ QByteArray GraphvizView::exportGraph(const QString& format)
...
-            << qMakePair(QStringLiteral("%1 (*.svg)").arg(tr("SVG format")), QStringLiteral("svg"));
-        formatMap
-            << qMakePair(QStringLiteral("%1 (*.pdf)").arg(tr("PDF format")), QStringLiteral("pdf"));
-
-        QStringList filter;
+        formatMap << qMakePair(FileDialog::Filter {tr("GIF format"), {"*.gif"}}, QStringLiteral("gif"));
+        formatMap << qMakePair(FileDialog::Filter {tr("JPG format"), {"*.jpg"}}, QStringLiteral("jpg"));
+        formatMap << qMakePair(FileDialog::Filter {tr("SVG format"), {"*.svg"}}, QStringLiteral("svg"));
+        formatMap << qMakePair(FileDialog::Filter {tr("PDF format"), {"*.pdf"}}, QStringLiteral("pdf"));
+
```
Comment (chennes) [inline src/Gui/GraphvizView.cpp]:
```suggestion
            FileDialog::Filter {QStringLiteral("Graphviz"), {"*.gv"}},
QStringLiteral("gv")
);
        formatMap << qMakePair(FileDialog::Filter {tr("PNG"), {"*.png"}}, QStringLiteral("png"));
formatMap << qMakePair(
            FileDialog::Filter {tr("Bitmap"), {"*.bmp"}},
QStringLiteral("bmp")
);
        formatMap << qMakePair(FileDialog::Filter {QStringLiteral("GIF"), {"*.gif"}}, QStringLiteral("gif"));
        formatMap << qMakePair(FileDialog::Filter {QStringLiteral("JPG"), {"*.jpg"}}, QStringLiteral("jpg"));
        formatMap << qMakePair(FileDialog::Filter {QStringLiteral("SVG"), {"*.svg"}}, QStringLiteral("svg"));
        formatMap << qMakePair(FileDialog::Filter {QStringLiteral("PDF"), {"*.pdf"}}, QStringLiteral("pdf"));

```

File: src/Gui/EditorView.cpp [hunk 25]
```diff
@@ -508,7 +508,7 @@ void EditorView::printPdf()
         this,
         tr("Export PDF"),
         QString(),
-        QStringLiteral("%1 (*.pdf)").arg(tr("PDF file"))
+        FileDialog::FilterList {{tr("PDF file"), {"*.pdf"}}}
```
Comment (chennes) [inline src/Gui/EditorView.cpp]:
```suggestion
        FileDialog::FilterList {{QStringLiteral("PDF"), {"*.pdf"}}}
```

File: src/Gui/Document.cpp [hunk 26]
```diff
@@ -1786,7 +1786,7 @@ bool Document::saveCopy()
         getMainWindow(),
         QObject::tr("Save %1 Document").arg(exe),
         name,
-        QStringList(QObject::tr("%1 document (*.FCStd)").arg(exe))
+        FileDialog::FilterList {{QObject::tr("%1 document").arg(exe), {"*.FCStd"}}}
```
Comment (chennes) [inline src/Gui/Document.cpp:1789]: Oh sure, this one just has to be a little different... (pre-existing code, of course, no shade...)

```suggestion
        FileDialog::FilterList {{QStringLiteral("%1 %2").arg(exe, QObject::tr("Document")), {"*.FCStd"}}}
```

File: src/Gui/CommandDoc.cpp [hunk 27]
```diff
@@ -689,12 +703,11 @@ void StdCmdExportDependencyGraph::activated(int iMsg)
 {
     Q_UNUSED(iMsg);
     App::Document* doc = App::GetApplication().getActiveDocument();
-    QString format = QStringLiteral("%1 (*.gv)").arg(Gui::GraphvizView::tr("Graphviz format"));
     QString fn = Gui::FileDialog::getSaveFileName(
         Gui::getMainWindow(),
         Gui::GraphvizView::tr("Export Graph"),
         QString(),
-        QStringList(format)
+        FileDialog::FilterList {{Gui::GraphvizView::tr("Graphviz format"), {"*.gv"}}}
```
Comment (chennes) [inline src/Gui/CommandDoc.cpp]:
```suggestion
        FileDialog::FilterList {{QStringLiteral("Graphviz"), {"*.gv"}}}
```

File: src/Gui/CommandDoc.cpp [hunk 28]
```diff
@@ -602,7 +616,7 @@ void StdCmdMergeProjects::activated(int iMsg)
         Gui::getMainWindow(),
         QString::fromUtf8(QT_TR_NOOP("Merge Document")),
         FileDialog::getWorkingDirectory(),
-        QStringList(QString::fromUtf8(QT_TR_NOOP("%1 document (*.FCStd)")).arg(exe))
+        FileDialog::FilterList {{QString::fromUtf8(QT_TR_NOOP("%1 document")).arg(exe), {"*.FCStd"}}}
```
Comment (chennes) [inline src/Gui/CommandDoc.cpp]: How many different ways can we write the same thing? It's like a game...

```suggestion
        FileDialog::FilterList {{QStringLiteral("%1 %2").arg(exe, QObject::tr("Document")), {"*.FCStd"}}}
```

**Review by chennes — COMMENTED** [review]
OK, what started as a "make sure we aren't caching these translated strings anywhere" turned into a "^&*% me this is a translation mess" cleanup pass. Not your doing, obviously, but as long as we are touching all this code, let's make the translation team a bit happier... (probably all added as another commit, not squashed in).

File: src/Mod/TechDraw/Gui/CommandDecorate.cpp (hunk 5 above)
Comment (ElementW) [reply src/Mod/TechDraw/Gui/CommandDecorate.cpp]: Yea it's the second time I tip toe on fixing the i18n calls or not. Guess I will.

File: src/Gui/GraphvizView.cpp (hunk 24 above)
Comment (ElementW) [reply src/Gui/GraphvizView.cpp]: Translatable PNG? Seems like an omission.

Comment (chennes) [reply src/Gui/GraphvizView.cpp]: Yeah, missed that one.

File: src/Gui/Document.cpp (hunk 26 above)
Comment (ElementW) [reply src/Gui/Document.cpp:1789]: I'll object to this one, as your suggestion disallows things like French "Document FreeCAD" or Esperanto "FreeCAD-dokumento", and put `"%1 document"` on `Document::saveAs()` instead.

File: src/Gui/CommandDoc.cpp (hunk 28 above)
Comment (ElementW) [reply src/Gui/CommandDoc.cpp]: Yup it's madness, drove me mad and that's why I decided to not touch it initially. Same as before, I'll keep `"%1 document"`.

File: src/Gui/Document.cpp (hunk 26 above)
Comment (chennes) [reply src/Gui/Document.cpp:1789]: Yes, you're right, let's unify on the version of this string construct that allows that, then.

File: src/Gui/FileDialog.cpp [hunk 29]
```diff
@@ -288,240 +271,141 @@ static bool getPreferShowFilterExtensions()
...
-        const auto wasSeen = [&seen](QStringView ext) -> bool {
-            for (QStringView extSeen : seen) {
-                if (extSeen.compare(ext, Qt::CaseInsensitive) == 0) {
-                    return true;
-                }
-            }
+bool Filter::isWildcard() const
+{
+    for (const auto& pat : patterns) {
+        if (pat != "*" || pat != "*.*") {
```
Comment (chennes) [inline src/Gui/FileDialog.cpp]:
```
(pat != "*" || pat != "*.*")
```
I'm tying myself in knots here: isn't this _always_ true?

File: src/Gui/FileDialogWin32.cpp [hunk 30]
```diff
@@ -0,0 +1,433 @@
...
+        w10->lpVtbl->Release(w10);
+    }
+    else if (
+        SUCCEEDED(fileDialog->QueryInterface(IID_IFileDialogPrivate_W7, reinterpret_cast<void**>(&w7)))
+    ) {
+        FileDialogPrivateOptions flags;
+        w7->lpVtbl->GetPrivateOptions(w7, &flags);
+        w7->lpVtbl->SetPrivateOptions(w7, flags | FDPO_DONT_FORCE_SHOW_EXTS);
+        w7->lpVtbl->Release(w7);
+        w7->lpVtbl->Release(w7);
```
Comment (chennes) [inline src/Gui/FileDialogWin32.cpp]: Double-release?

File: src/Gui/FileDialog.cpp (hunk 29 above)
Comment (ElementW) [reply src/Gui/FileDialog.cpp]: Correct. I added the 1st part of the expression late because some filters use "*" (the portability of `*` vs `*.*` is a known mess) and didn't think it through enough.

File: src/Gui/FileDialogWin32.cpp (hunk 30 above)
Comment (ElementW) [reply src/Gui/FileDialogWin32.cpp]: Copy-paste skill issue on my end

**Comment by ElementW** [comment]
Rebased on latest `main`, and fixed the issues @chennes pointed out.
