### PR TITLE
Sketcher: Harden against flip with signed constraints

### LINKED ISSUE #17579: Sketcher: Solver Issues with Distant Constraints flip direction
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

https://github.com/user-attachments/assets/6187db1e-9a0a-49ee-9af7-f7b70a211e30

If you draw 2 circles and use a distance constraint between the 2, if you make the inner shapes dimensions larger then the outer shape the 2 will flip position (inner becomes outer).

This happens with more advance shapes as well such as:

_Figure 1: Other test cases._

In my testing this happens when the Distance constraint is used (see Figure 2), and not when the Vertical Distance constraint or the Horizontal distance constraint are used (see Figure 3).  When I went back and checked my other test case (Figure 1), I noticed that the corner that was flipping directions had 2 Distance constraint rather then 1 Vertical Distance and 1 Horizontal distance.  Changing them to Vertical/Horizontal constraints fixed the issue.

circle1
_Figure 2:  Flip issue happens when the Distance Tool is used to separate these 2 shapes._

circle2
_Figure 3: Flip issue does NOT happen when using a Horizontal Distance Constraint._

My working theory is that the dimension tool does not have a Vector, so changing the inner object too much it will pull the object to it, rather then push it away.

This issue also exists in 0.21.

v21
_Figure 4: Test on v0.21_

I feel that this is a big issue because with the new Dimensions tool it is very intuitive to click on 2 parallels lines if you want to create an offset between the 2.  When you do this it will create a Distance constraint by default,  and since all 3 of these tools look identical on the sketch surface,  it can leave to a lot of issues to new users.  In fact, this is exactly what I did in Figure 1.

In addition, when the inner/outers flip it can cause issues in other sketches that use external geometry, I tested this as well and it does in fact flip the external geometry in other sketches making it look like a possible TNP issue.

Let me know if you need an more information.

PS.  Big thanks to the whole FreeCAD team.  1.0 feels very nice, you can tell that a lot of love went into the release. Keep up the great work! 

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38946 (Git)
Build type: Release
Branch: main
Hash: e478192aa5393de9b7df190341a043f79ec6ac49
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
Installed mods: 
  * 3D_Printing_Tools
  * Assembly3 0.12.0
  * CfdOF 1.22.9
  * Curves 0.6.13
  * fasteners 0.4.66
  * fcgear 1.0.0
  * freecad.gears 1.0.0
  * FreeCAD_assembly3-master
  * Movie 2023.6.10
```

### Subproject(s) affected?

Sketcher

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #26634: Sketcher: circle-line distance fails when circle radius is free in some orientations
### Problem description

The circle-line distance fails when the circle diameter is unconstrained, the line intersects and the geometries are in a clockwise order:

Image

All circle-line constraints work except the second line from the left which fails

### Workbench affected?

Sketcher

### Steps to reproduce

1. Open the file
2. Go to the sketch
3. Try to add the missing circle-distance constraint

[circlelinedisttestbench2.zip](https://github.com/user-attachments/files/24417534/circlelinedisttestbench2.zip)

### Expected behavior

The constraint is added

### Actual behavior

The solve fails and the constraint is not added

### Development version About Info (in Safe Mode)

```shell
OS: Ubuntu 25.10 (ubuntu:GNOME/ubuntu/wayland)
Architecture: x86_64
Version: 1.1.0rc1.20251125 (Git shallow) AppImage
Build date: 2025/11/25 17:53:08
Build type: Release
Branch: (HEAD detached at 5376760)
Hash: 53767601ea65de7cd9f6590e7d5856afc0841635
Python 3.11.14, Qt 6.8.3, Coin 4.0.3, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.3.0, IfcOpenShell 0.8.2, OCC 7.8.1
Locale: English/United States (en_US)
Navigation Style/Orbit Style/Rotation Mode: Touchpad/Trackball/Window center
Stylesheet/Theme/QtStyle: FreeCAD.qss/FreeCAD Dark/
Logical DPI/Physical DPI/Pixel Ratio: 96/143.907/1
Installed mods: 
  * Defeaturing 1.2.9
  * FusedFilamentDesign 0.25.250
  * Telemetry 1.0.2
  * lattice2 1.0.0
  * fasteners 0.5.41
  * sheetmetal 0.7.52
  * Assembly4 0.60.2
  * freecad.gears 1.3.0
  * OpticsWorkbench 1.2.2
  * Cables 0.2.1
```

### Last known good version (optional)

```shell

```

### PR DESCRIPTION
**Pull request by theo-vt**
This PR adds a concept of orientation to 
* point-line distance
* circle-circle distance
* circle-line distance

to make sketches harder to flip

The orientation is saved to file and handled by the App::Constraint rather than the planegcs::Constraint to better capture design intent (it allows to react to external geometry movement, which the solver is blind to)

The orientation is computed on sketch restore so older files are upgraded seamlessly

The constraints can still be made driven or deactivated and their orientation is recomputed when made driving/reactivated so the user can manually flip them

### Point-Line distance

This PR makes point-line constraints signed which prevents flips when constraints values change drastically or a reference geometry moves around

Before:

https://github.com/user-attachments/assets/067c3eaa-dccc-41c4-bf05-593ff31fcc67

After:

https://github.com/user-attachments/assets/dc51966d-09bd-4e82-951d-146add91a0b1

### Circle-Circle distance

This PR adds a concept of relative size for circle-circle distance which allows to keep an inner circle and an outer circle when one of the circles is completely within the other 

Before:

https://github.com/user-attachments/assets/4a22a54f-5805-477d-b9ba-50ac31c54c6a

After:

https://github.com/user-attachments/assets/3f9d76b8-781e-4a32-bbca-a41cc3573e59

### Circle-Line distance

This PR adds an orientation concept to circle-line distances. 4 possible orientations are established with 2 flags: ccw and internal. 

A ccw orientation means that the sequence [line.pt1, line.pt2, circle.center] is and should remain ccw, this is the same as the point-line distance orientation from https://github.com/FreeCAD/FreeCAD/pull/26228/changes

An internal orientation means that the line is and should remain closer to the center then the radius of the circle

Before:

https://github.com/user-attachments/assets/c0e889eb-0232-4efc-a7fd-a041266ee6bf

After:

https://github.com/user-attachments/assets/8d47a307-3f2c-4805-aff1-fef320a8738c

## Issues
Fix: https://github.com/FreeCAD/FreeCAD/issues/26634
Fix https://github.com/FreeCAD/FreeCAD/issues/17579

### CODE REVIEW

File: src/Base/Vector3D.h [hunk 1]
```diff
@@ -283,6 +283,13 @@ template<class Pr1, class Pr2>
     return Vector3<Pr1>(static_cast<Pr1>(v.x), static_cast<Pr1>(v.y), static_cast<Pr1>(v.z));
 }
 
+// Returns true if the points A-B-C truncated to 2d (x, y) are in a ccw order
+template<class Pr1, class Pr2, class Pr3>
+[[nodiscard]] inline bool ccw2d(const Vector3<Pr1>& A, const Vector3<Pr2>& B, const Vector3<Pr3>& C)
+{
+    return B.x * C.y - B.y * C.x - A.x * C.y + A.y * C.x + A.x * B.y - A.y * B.x > 0.0;
+}
```
Comment (hyarion) [inline src/Base/Vector3D.h]: It looks like this is just used in `SketchObject::setOrientation()` could we move it into the function as a lambda or as a helper function in that file?

Comment (theo-vt) [reply src/Base/Vector3D.h]: Yup

File: src/Mod/Sketcher/App/SketchObject.cpp [hunk 2]
```diff
@@ -3056,6 +3066,75 @@ void SketchObject::addConstraint(Sketcher::ConstraintType constrType, int firstG
...
+    }
+
+    // Try to find the orientation of point-line distance
+    if (constr->FirstPos != PointPos::none && constr->Second != GeoEnum::GeoUndef) {
+        const Part::Geometry* secGeo = getGeometry(constr->Second);
+        if (!secGeo->is<Part::GeomLineSegment>()) {
+            return; // circle-point distance
+        }
+
+        auto* geoLine = static_cast<const Part::GeomLineSegment*>(secGeo);
```
Comment (hyarion) [inline src/Mod/Sketcher/App/SketchObject.cpp]: `freecad_cast<>` could be used here if we allow all `GeomLineSegment`-like objects to be used (nothing inherits `GeomLineSegment` yet).

If that is ok, then we could write:

```c++
        auto* geoLine = freecad_cast<const Part::GeomLineSegment>(secGeo);
        if (!geoLine) {
            return; // circle-point distance
        }

```

File: src/Mod/Sketcher/App/SketchObject.cpp [hunk 3]
```diff
@@ -3056,6 +3066,75 @@ void SketchObject::addConstraint(Sketcher::ConstraintType constrType, int firstG
 
     this->addConstraint(std::move(newConstr));
 }
+void SketchObject::setOrientation(Constraint* constr, bool reset)
+{
+    // Returns true if the points A-B-C truncated to 2d (x, y) are in a ccw order
+    auto ccw2d = [](const Base::Vector3d& A, const Base::Vector3d& B, const Base::Vector3d& C)
+    {
+        return B.x * C.y - B.y * C.x - A.x * C.y + A.y * C.x + A.x * B.y - A.y * B.x > 0.0;
+    };
```
Comment (hyarion) [inline src/Mod/Sketcher/App/SketchObject.cpp]: Do we need to worry about the degenerate step when it is close to `0`?

Instead of returning a bool, should we return `ConstraintOrientations` as it would simplify where we're calling this lambda` like:


```c++
    auto ccw2d = [](const Base::Vector3d& A, const Base::Vector3d& B, const Base::Vector3d& C)
    {
        auto signedArea = B.x * C.y - B.y * C.x - A.x * C.y + A.y * C.x + A.x * B.y - A.y * B.x;
        return signedArea > 0 ? ConstraintOrientations::CounterClockwise
                              : ConstraintOrientations::Clockwise;
    };
```

File: src/Mod/Sketcher/App/SketchObject.cpp [hunk 4]
```diff
@@ -3056,6 +3066,75 @@ void SketchObject::addConstraint(Sketcher::ConstraintType constrType, int firstG
...
+    }
+
+    // Try to find the orientation of circle-circle distance or circle-line
+    if (constr->FirstPos == PointPos::none && constr->SecondPos == PointPos::none && constr->Second != GeoEnum::GeoUndef) {
+        const Part::Geometry* firGeo = getGeometry(constr->First);
+        const Part::Geometry* secGeo = getGeometry(constr->Second);
+
+        if (firGeo->is<Part::GeomCircle>() && secGeo->is<Part::GeomCircle>()) { // circle-circle distance
+            auto* geoCirc1 = static_cast<const Part::GeomCircle*>(firGeo);
+            auto* geoCirc2 = static_cast<const Part::GeomCircle*>(secGeo);
```
Comment (hyarion) [inline src/Mod/Sketcher/App/SketchObject.cpp]: An alternative way to this is to use freecad_cast<> to avoid some repetition. That would also run the code if something inherits `Part::GeomCircle` which currently isn't the case. What do you think do we want that?

The code would then look like:

```c++
        auto* geo1asCirc = freecad_cast<const Part::GeomCircle>(firGeo);
        auto* geo2asCirc = freecad_cast<const Part::GeomCircle>(secGeo);
        if (geo1asCirc && geo2asCirc) { // circle-circle distance
```

The downside would be that we don't scope the nullable pointers, but in this case we want to use `geo1asCirc` later anyway.

File: src/Mod/Sketcher/App/SketchObject.cpp [hunk 5]
```diff
@@ -3056,6 +3066,75 @@ void SketchObject::addConstraint(Sketcher::ConstraintType constrType, int firstG
...
+            // it is internal, if they are not within each other or intersect we won't
+            // make a call
+
+            double centerDistance = Base::Distance(geoCirc1->getLocation(), geoCirc2->getLocation());
+
+            if (centerDistance + geoCirc1->getRadius() < geoCirc2->getRadius()) {
+                constr->Orientation = ConstraintOrientations::Internal; // Circ1 is within circ2
+            } else if (centerDistance + geoCirc2->getRadius() < geoCirc1->getRadius()) {
+                constr->Orientation = ConstraintOrientations::External; // Circ2 is within circ1
+            }
```
Comment (hyarion) [inline src/Mod/Sketcher/App/SketchObject.cpp]: Extracting the variables that are reused makes it slightly more readable to me:
```c++
            auto circ1Radius = geoCirc1->getRadius();
            auto circ2Radius = geoCirc2->getRadius();
            if (centerDistance + circ1Radius < circ2Radius) {
                constr->Orientation = ConstraintOrientations::Internal; // Circ1 is within circ2
            } else if (centerDistance + circ2Radius < circ1Radius) {
                constr->Orientation = ConstraintOrientations::External; // Circ2 is within circ1
            }
```

File: src/Mod/Sketcher/App/SketchObject.cpp [hunk 6]
```diff
@@ -3056,6 +3066,75 @@ void SketchObject::addConstraint(Sketcher::ConstraintType constrType, int firstG
...
+            return;
+        }
+
+        if (firGeo->is<Part::GeomCircle>() && secGeo->is<Part::GeomLineSegment>()) { // circle-line distance
+            auto* geoCirc = static_cast<const Part::GeomCircle*>(firGeo);
+            auto* geoLine = static_cast<const Part::GeomLineSegment*>(secGeo);
```
Comment (hyarion) [inline src/Mod/Sketcher/App/SketchObject.cpp]: if we use `freecad_cast<>` then we could reuse `geoCirc` from above:
```suggestion
        auto* geo2asLine = freecad_cast<const Part::GeomLineSegment>(secGeo);
        if (geo1asCirc && geo2asLine) {
```

File: src/Mod/Sketcher/App/SketchObject.cpp [hunk 7]
```diff
@@ -11133,8 +11212,17 @@ void SketchObject::migrateSketch()
...
     auto constraints = Constraints.getValues();
+    for (auto& constr : constraints) {
+        setOrientation(constr, false);
+    }
+
+    Constraints.setValues(std::move(constraints));
+
+
+    /* parabola axis as internal geometry */
+    constraints = Constraints.getValues();
```
Comment (hyarion) [inline src/Mod/Sketcher/App/SketchObject.cpp]: I always get a bit nervous `with std::move` without an explicit ending.
While we have the overwrite a few lines down here, could we avoid reusing the moved variable?

Would scoping it work:

```c++
    {
        auto constraints = Constraints.getValues();
        for (auto& constr : constraints) {
            setOrientation(constr, false);
        }
        Constraints.setValues(std::move(constraints));
    }

    /* parabola axis as internal geometry */
    auto constraints = Constraints.getValues();
```

Wait, why do we even `std::move` it if we resurrect it directly anyway?
isn't:
```c++
    Constraints.setValues(std::move(constraints));
    auto constraints = Constraints.getValues();
```
the same as just:
```c++
    Constraints.setValues(constraints);
```
What am I missing? 🤔

File: src/Mod/Sketcher/App/SketchObject.cpp (hunk 2 above)
Comment (theo-vt) [reply src/Mod/Sketcher/App/SketchObject.cpp]: Cleaner!

File: src/Mod/Sketcher/App/SketchObject.cpp (hunk 3 above)
Comment (theo-vt) [reply src/Mod/Sketcher/App/SketchObject.cpp]: I agree,

File: src/Mod/Sketcher/App/SketchObject.cpp (hunk 7 above)
Comment (theo-vt) [reply src/Mod/Sketcher/App/SketchObject.cpp]: Yup seems so, I think it made sense before I rebased on top of the big sketchobject refactor,, or perhaps I just missed it,, either way I'll remove a move

Comment (theo-vt) [reply src/Mod/Sketcher/App/SketchObject.cpp]: oh I found it,

there are early returns so the constraints may not get updated, I'll scope it instead

**Comment by theo-vt** [comment]
Here are builds if people want to test!
https://github.com/theo-vt/FreeCAD/releases/tag/weekly-2026.03.02

**Review by hyarion — APPROVED** [review]

**Review by maxwxyz — APPROVED** [review]
I have played around a bit and did not find any issues

**Comment by jffmichi** [comment]
I have another file that fails with this PR merged, this time when changing one of the constraints. Reproduce by going into Sketch097 and change the 93.25 mm constraint to something like 100 mm. Bisected to this PR.

[sketch_solve_issue.zip](https://github.com/user-attachments/files/26448903/sketch_solve_issue.zip)

**Comment by Timothy-Ecc19** [comment]
My apologies if I should have posted this somewhere else, but I have a file that fails in what I believe would be a similar problem. I tested in version 1.1.1 and Development Build weekly-2026.04.15.

If I divide constraint 1 by 2.7 in the sketch the constraint moves from one side of my rectangle to the other.
The same problem occurs if I just change the measurement of constraint 1 to 3.7.

[coincident moving error 4-17-26 example.zip](https://github.com/user-attachments/files/26845301/coincident.moving.error.4-17-26.example.zip)

Please let me know if you need any other information.

**Comment by theo-vt** [comment]
Hello @Timothy-Ecc19! I tested your file and from what I can see it behaves the same in 1.1 and dev,, are you providing an example of flip for further work or are you saying this PR made a regression?

**Comment by Timothy-Ecc19** [comment]
Hello @theo-vt I believe this would be a flip for further work. 

I originally noticed the problem in version 1.0, but waited for this PR to be merged to check if the work already done would fix the problem.

**Comment by theo-vt** [comment]
Such flip is in the work but it takes a little longer then I would like unfortunately

in the mean time you can prevent such flip in your file by using a vertical/horizontal constraint on the line (the one that has 1.25...mm dimension) - you can do it manually, but the auto dimension tool should select the right constraint in the latest dev version

otherwise you can do a line-line or point-line distance which are now signed (this is from this PR)

**Comment by Timothy-Ecc19** [comment]
Thank you, I just figured I would make sure that this was a known flip. Good to know the best practices to avoid this issue, I was making a model of pvc pipe thicknesses when this problem originally came up and was rather confused when my 3d model was a significantly different size than I thought it would be.
