### PR TITLE
Gui: Fix value field for DlgAddPropertyVarSet

### LINKED ISSUE #16189: VarSet: must enter Name of new property first
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When adding a property to a VarSet you must enter the Name first.

If you don't and click on the down arrow of the Group or the Type combo there are 2 popups.

### Full version info

```shell
OS: Windows 8 build 9600
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38553 (Git)
Build type: Release
Branch: main
Hash: 59c1ccec3e6b70f56eeee8f94d361019b84bd850
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: C/Default (C) [ OS: Dutch/Netherlands (nl_NL) ]
Installed mods:
```

### Subproject(s) affected?

Core

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #17474: VarSet: Unintuitive behaviour of dialog
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When the user enters some text into the Name field then the OK button doesn't become active. In order to make it active the user has to click on any of the other controls, first.

The expected behaviour is to make the OK button active as soon as a valid name is entered.

### Full version info

```shell
FreeCAD 1.1.0, Libs: 1.1.0devR39035 (Git)
```

### Subproject(s) affected?

Core

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by pieterhijma**
The value field would only appear if a name was provided resulting in a strange user experience.  This commit fixes this and simplifies the logic of the dialog. It is now possible to assign a value first and then come up with a name. 

This PR is a major rewrite of the dialog but it is now much simpler and robust. It is still necessary to create a property, but I now create a temporary property that I can delete after the PropertyItem has been created and the data of the editor has been set.

Closes #16189
Closes #17474

### CODE REVIEW

File: src/Gui/Dialogs/DlgAddPropertyVarSet.cpp [hunk 1]
```diff
@@ -25,30 +26,28 @@
...
 
 using namespace Gui;
 using namespace Gui::Dialog;
 
-const std::string DlgAddPropertyVarSet::GROUP_BASE = "Base";
-
-const bool CLEAR_NAME = true;
-const bool ABORT = true;
-const bool COMMIT = false;
+const std::string DlgAddPropertyVarSet::Group_Base = "Base";
```
Comment (kadet1090) [inline src/Gui/Dialogs/DlgAddPropertyVarSet.cpp:50]:
```suggestion
const std::string DlgAddPropertyVarSet::GroupBase = "Base";
```

?

File: src/Gui/Dialogs/DlgAddPropertyVarSet.cpp [hunk 2]
```diff
@@ -77,63 +76,69 @@ void DlgAddPropertyVarSet::initializeGroup()
...
     }
 
-    std::vector<Base::Type> types;
-    getSupportedTypes(types);
+    std::vector<Base::Type> types = getSupportedTypes();
 
     for(const auto& type : types) {
         ui->comboBoxType->addItem(QString::fromLatin1(type.getName()));
-        if(type == lastType)
+        if(type == lastType) {
```
Comment (kadet1090) [inline src/Gui/Dialogs/DlgAddPropertyVarSet.cpp:139]:
```suggestion
        if (type == lastType) {
```

File: src/Gui/Dialogs/DlgAddPropertyVarSet.cpp [hunk 3]
```diff
@@ -158,21 +174,152 @@ static void printFocusChain(QWidget *widget) {
...
+"None") << std::endl << std::endl);
 }
 */
 
+void DlgAddPropertyVarSet::addEditor(PropertyEditor::PropertyItem* propertyItem)
+{
+    editor.reset(propertyItem->createEditor(this, [this]() {
+        this->valueChanged();
+    }));
+    if (editor) {
```
Comment (kadet1090) [inline src/Gui/Dialogs/DlgAddPropertyVarSet.cpp:187]: Wouldn't it be better to change it into early exit? I think that the best rule of thumb is that the "happy path" / most typical should be not indented, indentations should be for edge cases etc.

File: src/Gui/Dialogs/DlgAddPropertyVarSet.cpp [hunk 4]
```diff
@@ -158,21 +174,152 @@ static void printFocusChain(QWidget *widget) {
...
+        editor->blockSignals(true);
```
Comment (kadet1090) [inline src/Gui/Dialogs/DlgAddPropertyVarSet.cpp:188]: The pair of `blockSignals` should be changed into QSignalBlocker blocker(editor);

File: src/Gui/Dialogs/DlgAddPropertyVarSet.cpp [hunk 5]
```diff
@@ -158,21 +174,152 @@ static void printFocusChain(QWidget *widget) {
...
+        // To set the data in the editor, we need to set the data in the
+        // propertyItem.  The propertyItem needs to have a property set to make
+        // sure that we get a correct value and the unit.
+        propertyItem->setEditorData(
+                editor.get(),
+                propertyItem->data(PropertyEditor::PropertyItem::ValueColumn, Qt::EditRole));
+        editor->setSizePolicy(QSizePolicy::Preferred, QSizePolicy::Preferred);
+        editor->setObjectName(QStringLiteral("editor"));
+        auto formLayout = qobject_cast<QFormLayout*>(layout());
+        formLayout->setWidget(3, QFormLayout::FieldRole, editor.get());
```
Comment (kadet1090) [inline src/Gui/Dialogs/DlgAddPropertyVarSet.cpp:198]: Can we do something so it is not dependent on order? This is layout, so it might be not possible, but referring to widgets by their index is in general not a good practice as the code will silently break if for some reason order of widget changes.

File: src/Gui/Dialogs/DlgAddPropertyVarSet.cpp [hunk 6]
```diff
@@ -158,21 +174,152 @@ static void printFocusChain(QWidget *widget) {
...
+
+        QWidget::setTabOrder(ui->comboBoxType, editor.get());
+        QWidget::setTabOrder(editor.get(), ui->checkBoxAdd);
+
+        removeSelectionEditor();
+        editor->blockSignals(false);
+    }
+
+    // FC_ERR("add editor");
+    // printFocusChain(editor.get());
```
Comment (kadet1090) [inline src/Gui/Dialogs/DlgAddPropertyVarSet.cpp:208]: Not needed anymore I think?

File: src/Gui/Dialogs/DlgAddPropertyVarSet.cpp [hunk 7]
```diff
@@ -158,21 +174,152 @@ static void printFocusChain(QWidget *widget) {
...
+}
+
+bool DlgAddPropertyVarSet::isTypeWithEditor(const Base::Type& type)
+{
+    static const std::array<Base::Type, 5> subTypesWithEditor = {
```
Comment (kadet1090) [inline src/Gui/Dialogs/DlgAddPropertyVarSet.cpp:213]: You can also use `std::initializer_list<Base::Type>` and then you don't need to specify the count.

File: src/Gui/Dialogs/DlgAddPropertyVarSet.cpp [hunk 8]
```diff
@@ -158,21 +174,152 @@ static void printFocusChain(QWidget *widget) {
...
+        // These types and their subtypes have editors.
+        App::PropertyBool::getClassTypeId(),
+        App::PropertyColor::getClassTypeId(),
+        App::PropertyFileIncluded::getClassTypeId(),
+        App::PropertyFloat::getClassTypeId(),
+        App::PropertyInteger::getClassTypeId()
+    };
+
+    static const std::array<Base::Type, 9> typesWithEditor = {
```
Comment (kadet1090) [inline src/Gui/Dialogs/DlgAddPropertyVarSet.cpp:222]: Same as above

File: src/Gui/Dialogs/DlgAddPropertyVarSet.cpp [hunk 9]
```diff
@@ -158,21 +174,152 @@ static void printFocusChain(QWidget *widget) {
...
+        App::PropertyStringList::getClassTypeId(),
+        App::PropertyVectorList::getClassTypeId()
+    };
+
+    return std::ranges::find(typesWithEditor, type) != typesWithEditor.end() ||
+        std::ranges::any_of(subTypesWithEditor,
+                            [&type](const Base::Type& t) {
+                                return type.isDerivedFrom(t);
+                            });
+}
```
Comment (kadet1090) [inline src/Gui/Dialogs/DlgAddPropertyVarSet.cpp:240]: extracting it into variable like `const auto isDerivedFromType = [](...) { ... }` would yield a more readable code I think.

File: src/Gui/Dialogs/DlgAddPropertyVarSet.cpp [hunk 10]
```diff
@@ -158,21 +174,152 @@ static void printFocusChain(QWidget *widget) {
...
+{
+    Base::Type propType =
+        Base::Type::getTypeIfDerivedFrom(type.c_str(), App::Property::getClassTypeId(), true);
+    return isTypeWithEditor(propType);
+}
+
+static PropertyEditor::PropertyItem *createPropertyItem(App::Property *prop)
+{
+    const char *editor = prop->getEditorName();
+    if (!editor || std::strlen(editor) == 0) {
```
Comment (kadet1090) [inline src/Gui/Dialogs/DlgAddPropertyVarSet.cpp:252]: We have utility for that: `Base::Tools::isNullOrEmpty(editor)`

File: src/Gui/Dialogs/DlgAddPropertyVarSet.cpp [hunk 11]
```diff
@@ -158,21 +174,152 @@ static void printFocusChain(QWidget *widget) {
...
+        return nullptr;
+    }
+    return static_cast<PropertyEditor::PropertyItem*>(
+            PropertyEditor::PropertyItemFactory::instance().createPropertyItem(editor));
```
Comment (kadet1090) [inline src/Gui/Dialogs/DlgAddPropertyVarSet.cpp:256]: Is this static cast even required?

File: src/Gui/Dialogs/DlgAddPropertyVarSet.cpp [hunk 12]
```diff
@@ -186,28 +333,44 @@ void DlgAddPropertyVarSet::initializeWidgets(ViewProviderVarSet* viewProvider)
...
 {
-    QPushButton *okButton = ui->buttonBox->button(QDialogButtonBox::Ok);
-    okButton->setEnabled(enabled);
+    std::string name = ui->lineEditName->text().toStdString();
+
+    return !(name.empty() ||
+             name != Base::Tools::getIdentifier(name) ||
+             App::ExpressionParser::isTokenAConstant(name) ||
+             App::ExpressionParser::isTokenAUnit(name) ||
+             propertyExists(name));
```
Comment (kadet1090) [inline src/Gui/Dialogs/DlgAddPropertyVarSet.cpp:350]: That ! at the beginning is very easy to miss, wouldn't it be better to move it inside?

File: src/Gui/Dialogs/DlgAddPropertyVarSet.cpp [hunk 13]
```diff
@@ -186,28 +333,44 @@ void DlgAddPropertyVarSet::initializeWidgets(ViewProviderVarSet* viewProvider)
...
-        bool beforeBlocked = ui->lineEditName->blockSignals(true);
-        ui->lineEditName->clear();
-        ui->lineEditName->blockSignals(beforeBlocked);
-    }
-    removeEditor();
-    ui->lineEditToolTip->clear();
-    setOkEnabled(false);
-    namePropertyToAdd.clear();
+    std::string group = comboBoxGroup.currentText().toStdString();
+    return !(group.empty() || group != Base::Tools::getIdentifier(group));
```
Comment (kadet1090) [inline src/Gui/Dialogs/DlgAddPropertyVarSet.cpp:356]:
```suggestion
    return !group.empty() && group == Base::Tools::getIdentifier(group);
```

File: src/Gui/Dialogs/DlgAddPropertyVarSet.cpp [hunk 14]
```diff
@@ -304,26 +455,113 @@ void DlgAddPropertyVarSet::createProperty()
...
-    if (propertyItem && isTypeWithEditor(type)) {
+    if (propertyItem) {
+        objectIdentifier = std::make_unique<App::ObjectIdentifier>(*prop);
         propertyItem->setPropertyData({prop});
         propertyItem->bind(*objectIdentifier);
-        addEditor(propertyItem.get(), type);
+
+        QVariant data;
+        data = propertyItem->editorData(editor.get());
+        propertyItem->setData(data);
```
Comment (kadet1090) [inline src/Gui/Dialogs/DlgAddPropertyVarSet.cpp:468]: Same thing

**Review by kadet1090 — CHANGES_REQUESTED** [review]

File: src/Gui/Dialogs/DlgAddPropertyVarSet.cpp (hunk 1 above)
Comment (pieterhijma) [reply src/Gui/Dialogs/DlgAddPropertyVarSet.cpp]: Yes, totally agree, missed it.

File: src/Gui/Dialogs/DlgAddPropertyVarSet.cpp (hunk 3 above)
Comment (pieterhijma) [reply src/Gui/Dialogs/DlgAddPropertyVarSet.cpp:187]: Yes, totally agree.

File: src/Gui/Dialogs/DlgAddPropertyVarSet.cpp (hunk 4 above)
Comment (pieterhijma) [reply src/Gui/Dialogs/DlgAddPropertyVarSet.cpp:188]: Yes, totally agree.

File: src/Gui/Dialogs/DlgAddPropertyVarSet.cpp (hunk 5 above)
Comment (pieterhijma) [reply src/Gui/Dialogs/DlgAddPropertyVarSet.cpp:198]: Yes, totally agree. I looked into it and found a satisfying solution where I look up the row of the label and then set the field in that row.

File: src/Gui/Dialogs/DlgAddPropertyVarSet.cpp (hunk 6 above)
Comment (pieterhijma) [reply src/Gui/Dialogs/DlgAddPropertyVarSet.cpp]: No, not really. I removed all of the debugging code.

File: src/Gui/Dialogs/DlgAddPropertyVarSet.cpp (hunk 7 above)
Comment (pieterhijma) [reply src/Gui/Dialogs/DlgAddPropertyVarSet.cpp]: Yep, true.

File: src/Gui/Dialogs/DlgAddPropertyVarSet.cpp (hunk 9 above)
Comment (pieterhijma) [reply src/Gui/Dialogs/DlgAddPropertyVarSet.cpp]: Sure.

File: src/Gui/Dialogs/DlgAddPropertyVarSet.cpp (hunk 10 above)
Comment (pieterhijma) [reply src/Gui/Dialogs/DlgAddPropertyVarSet.cpp]: Ah right, thanks!

File: src/Gui/Dialogs/DlgAddPropertyVarSet.cpp [hunk 15]
```diff
@@ -304,26 +455,113 @@ void DlgAddPropertyVarSet::createProperty()
...
-    setOkEnabled(true);
+    return true;
+}
+
+void DlgAddPropertyVarSet::closeTransaction(TransactionOption option)
+{
+    if (transactionID != 0) {
+        App::GetApplication().closeActiveTransaction(static_cast<bool>(option), transactionID);
+        transactionID = 0;
+    }
```
[the remark this answers is not in the document]
Comment (pieterhijma) [reply src/Gui/Dialogs/DlgAddPropertyVarSet.cpp]: Yep, agree.

File: src/Gui/Dialogs/DlgAddPropertyVarSet.cpp [hunk 16]
```diff
@@ -304,26 +455,113 @@ void DlgAddPropertyVarSet::createProperty()
...
+    // if (!namePropertyToAdd.empty() && text.toStdString() != namePropertyToAdd) {
+    //     // The user decided to change the name of the property.  This
+    //     // invalidates the editor that is strictly associated with the property.
+    //     clearCurrentProperty();
+    // }
+}
+
+// unused
+
+// unused
```
[the remark this answers is not in the document]
Comment (pieterhijma) [reply src/Gui/Dialogs/DlgAddPropertyVarSet.cpp]: Oh, apparently I only removed it from the header file...

File: src/Gui/Dialogs/DlgAddPropertyVarSet.cpp [hunk 17]
```diff
@@ -67,73 +66,113 @@ DlgAddPropertyVarSet::DlgAddPropertyVarSet(QWidget* parent,
 
 DlgAddPropertyVarSet::~DlgAddPropertyVarSet() = default;
 
+int DlgAddPropertyVarSet::findRowLabel(const char* nameLabel, QFormLayout* layout)
```
Comment (kadet1090) [inline src/Gui/Dialogs/DlgAddPropertyVarSet.cpp:69]: I feel that `findLabelRow` would be more readable? For me `findRowLabel` means that it finds label of the row, while it finds row of the label.

File: src/Gui/Dialogs/DlgAddPropertyVarSet.cpp [hunk 18]
```diff
@@ -67,73 +66,113 @@ DlgAddPropertyVarSet::DlgAddPropertyVarSet(QWidget* parent,
...
+        if (auto label = qobject_cast<QLabel*>(labelItem->widget())) {
+            if (label->objectName() == QString::fromLatin1(nameLabel)) {
+                return row;
+            }
+        }
+    }
+    return -1;
+}
+
+void DlgAddPropertyVarSet::placeInLayout(const char* nameLabel, QWidget* widget)
```
Comment (kadet1090) [inline src/Gui/Dialogs/DlgAddPropertyVarSet.cpp:86]: `setWidgetForLabel` would be more fitting name I think

File: src/Gui/Dialogs/DlgAddPropertyVarSet.cpp [hunk 19]
```diff
@@ -256,254 +196,244 @@ void DlgAddPropertyVarSet::removeSelectionEditor()
...
-        // no check for tooltip, we accept any string
-    }
-    catch (const CreatePropertyException&) {
-        if (!namePropertyToAdd.empty()) {
-            clearCurrentProperty();
-        }
-        return;
+void DlgAddPropertyVarSet::onTextFieldChanged([[maybe_unused]] const QString& text)
+{
+    setOkEnabled(areFieldsValid());
```
Comment (kadet1090) [inline src/Gui/Dialogs/DlgAddPropertyVarSet.cpp:385]: That comment is not to be addressed in that PR, but in general disabling button that is used for confirmation when there are errors is considered as bad UX practice. User knows that _something_ is wrong, but button being disabled is binary information. It is basically the same thing as telling "Something is wrong" without explanation what that something is. Instead of disabling button it should perform validation on click and then show the user what is wrong. I'm not sure if we have good framework in place and precedence to achieve such result so there is nothing to do here, I'm just leaving it as something that is nice to know.

https://ux.stackexchange.com/questions/9788/disabled-submit-button-on-form-vs-allow-submit-then-show-errors
https://blog.thms.uk/2023/03/stop-disabling-form-submit-buttons

File: src/Gui/Dialogs/DlgAddPropertyVarSet.cpp [hunk 20]
```diff
@@ -256,254 +196,244 @@ void DlgAddPropertyVarSet::removeSelectionEditor()
...
+}
+
+void DlgAddPropertyVarSet::removeEditor()
+{
+    if (editor) {
+        layout()->removeWidget(editor.get());
+        QWidget::setTabOrder(ui->comboBoxType, ui->checkBoxAdd);
+        editor = nullptr;
     }
```
Comment (kadet1090) [inline src/Gui/Dialogs/DlgAddPropertyVarSet.cpp:394]: early exit?

File: src/Gui/Dialogs/DlgAddPropertyVarSet.cpp [hunk 21]
```diff
@@ -515,72 +445,92 @@ void DlgAddPropertyVarSet::critical(const QString& title, const QString& text) {
...
-    QDialog::accept();
+    App::GetApplication().closeActiveTransaction(static_cast<bool>(option), transactionID);
+    transactionID = 0;
+}
+
+void DlgAddPropertyVarSet::clearFields()
+{
+    bool beforeBlocked = ui->lineEditName->blockSignals(true);
+    ui->lineEditName->clear();
+    ui->lineEditName->blockSignals(beforeBlocked);
```
Comment (kadet1090) [inline src/Gui/Dialogs/DlgAddPropertyVarSet.cpp:495]:
```suggestion
    {
        QSignalBlocker blocker(ui->lineEditName);
        ui->lineEditName->clear();
    }
```

That would be the idiomatic way to achieve that.

File: src/Gui/Dialogs/DlgAddPropertyVarSet.h [hunk 22]
```diff
@@ -24,12 +25,13 @@
...
 
 #include <qcompleter.h>
-#include <unordered_set>
+
 #include <QDialog>
 #include <QComboBox>
 #include <FCGlobal.h>
 
 #include <App/VarSet.h>
+#include <qformlayout.h>
```
Comment (kadet1090) [inline src/Gui/Dialogs/DlgAddPropertyVarSet.h:34]: I presume VS Code included that for you - it should be put higher (above `<FCGlobal.h>`) and as `<QFormLayout>`

File: src/Gui/Dialogs/DlgAddPropertyVarSet.h [hunk 23]
```diff
@@ -82,67 +90,62 @@ public Q_SLOTS:
     void valueChanged();
 
 private:
+    enum class TransactionOption : bool {
+        COMMIT = false,
+        ABORT = true
```
Comment (kadet1090) [inline src/Gui/Dialogs/DlgAddPropertyVarSet.h:95]:
```suggestion
        Commit = false,
        Abort = true
```

Enums should use PascalCase I think?

**Review by kadet1090 — CHANGES_REQUESTED** [review]
Thanks! I found few more minor issues, mostly related to naming - apart from that looks good!

File: src/Gui/Dialogs/DlgAddPropertyVarSet.cpp (hunk 19 above)
Comment (pieterhijma) [reply src/Gui/Dialogs/DlgAddPropertyVarSet.cpp:385]: Right, thanks. The current implementation is based on comments in the two issues (popups disruptive and enable the button when a valid identifier is chosen). Reading the your references, I agree it is bad practice. I also think that indeed we don't have a good practice for these kinds of notifications.  I'll leave it for now and we can always revisit later.

File: src/Gui/Dialogs/DlgAddPropertyVarSet.cpp (hunk 17 above)
Comment (pieterhijma) [reply src/Gui/Dialogs/DlgAddPropertyVarSet.cpp:69]: Ok, was discussed in the CQWG and indeed this style of naming was preferred.

File: src/Gui/Dialogs/DlgAddPropertyVarSet.cpp (hunk 18 above)
Comment (pieterhijma) [reply src/Gui/Dialogs/DlgAddPropertyVarSet.cpp:86]: Ok

File: src/Gui/Dialogs/DlgAddPropertyVarSet.cpp (hunk 21 above)
Comment (pieterhijma) [reply src/Gui/Dialogs/DlgAddPropertyVarSet.cpp:495]: Yes, I agree.

File: src/Gui/Dialogs/DlgAddPropertyVarSet.h (hunk 22 above)
Comment (pieterhijma) [reply src/Gui/Dialogs/DlgAddPropertyVarSet.h:34]: Indeed.

File: src/Gui/Dialogs/DlgAddPropertyVarSet.h (hunk 23 above)
Comment (pieterhijma) [reply src/Gui/Dialogs/DlgAddPropertyVarSet.h:95]: Yes, I agree.

File: src/Gui/Dialogs/DlgAddPropertyVarSet.cpp (hunk 20 above)
Comment (pieterhijma) [reply src/Gui/Dialogs/DlgAddPropertyVarSet.cpp]: yes, better.
