### PR TITLE
Sketcher: prevent undo/redo crash when selected geometry goes away.

### LINKED ISSUE #25497: Sketcher: undo/redo with a selected item crashes
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Problem description

Performing an undo/redo in Sketcher that causes the selected geometry to disappear produces a crash.

1. Create a new document.
2. Create a new sketch in Part Designer.
3. Create a circle, then hit `Esc` to exit the circle tool.
4. Select the circle.
5. Undo.

The crash also happens if you create the circle, delete it, undo, select it, then redo the deletion.

<details><summary>Stack trace of crash</summary>
<pre>
0   SketcherGui.so                	       0x14063eac0 SketcherGui::isBsplineKnotOrEndPoint(Sketcher::SketchObject const*, int, Sketcher::PointPos) + 112
1   SketcherGui.so                	       0x140797b63 isCommandNeedingBSplineKnotActive(Gui::Document*) + 211
2   libFreeCADGui.dylib           	       0x1033996ea Gui::Command::testActive() + 442
3   libFreeCADGui.dylib           	       0x1033a6c71 Gui::CommandManager::testActive() + 49
4   libFreeCADGui.dylib           	       0x103a422ed Gui::MainWindow::_updateActions() + 749
5   libQt6Core.6.8.3.dylib        	       0x102cd1beb void doActivate<false>(QObject*, int, void**) + 1579
6   libQt6Core.6.8.3.dylib        	       0x102cde2de QTimer::timerEvent(QTimerEvent*) + 142
7   libQt6Core.6.8.3.dylib        	       0x102cc8db8 QObject::event(QEvent*) + 104
8   libQt6Widgets.6.8.3.dylib     	       0x105e44948 QApplicationPrivate::notify_helper(QObject*, QEvent*) + 312
9   libQt6Widgets.6.8.3.dylib     	       0x105e458ee QApplication::notify(QObject*, QEvent*) + 494
10  libFreeCADGui.dylib           	       0x103340a9c Gui::GUIApplication::notify(QObject*, QEvent*) + 92
11  libQt6Core.6.8.3.dylib        	       0x102d87602 QCoreApplication::notifyInternal2(QObject*, QEvent*) + 162
12  libQt6Core.6.8.3.dylib        	       0x102c2e0b1 QTimerInfoList::activateTimers() + 1329
13  libqcocoa.dylib               	       0x10895beea QCocoaEventDispatcherPrivate::activateTimersSourceCallback(void*) + 426
14  CoreFoundation                	    0x7ff810fb2ab0 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
15  CoreFoundation                	    0x7ff810fb2a52 __CFRunLoopDoSource0 + 157
16  CoreFoundation                	    0x7ff810fb280d __CFRunLoopDoSources0 + 203
17  CoreFoundation                	    0x7ff810fb1476 __CFRunLoopRun + 973
18  CoreFoundation                	    0x7ff810fb0a72 CFRunLoopRunSpecific + 536
19  HIToolbox                     	    0x7ff81caa20d4 RunCurrentEventLoopInMode + 281
20  HIToolbox                     	    0x7ff81caa4e60 ReceiveNextEventCommon + 188
21  HIToolbox                     	    0x7ff81cc2e19a _BlockUntilNextEventMatchingListInModeWithFilter + 63
22  AppKit                        	    0x7ff814a15db1 _DPSNextEvent + 912
23  AppKit                        	    0x7ff8154a4137 -[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1263
24  AppKit                        	    0x7ff814a06e99 -[NSApplication run] + 610
25  libqcocoa.dylib               	       0x10895ce28 QCocoaEventDispatcher::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 2808
26  libQt6Core.6.8.3.dylib        	       0x102d88296 QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 534
27  libQt6Core.6.8.3.dylib        	       0x102d87efc QCoreApplication::exec() + 156
28  libFreeCADGui.dylib           	       0x103254c6f Gui::Application::runApplication() + 2511
29  freecad                       	       0x100a14b9e main + 3646
30  dyld                          	    0x7ff810b24530 start + 3056
</pre>
</details>

PR to follow.

### Full version info

```shell
OS: macOS 15.6.1
Architecture: x86_64
Version: 1.2.0dev.44355 (Git)
Build date: 2025/11/19 23:28:17
Build type: Unknown
Branch: main
Hash: deab0abf8e61d69f2208b794f64ac56428467fef
Python 3.11.13, Qt 6.8.3, Coin 4.0.3, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.3.0, IfcOpenShell 0.8.2, OCC 7.8.1
Locale: English/United States (en_US)
Navigation Style/Orbit Style/Rotation Mode: Touchpad/Turntable/Object center
Stylesheet/Theme/QtStyle: FreeCAD Light.qss/FreeCAD Light/
Logical DPI/Physical DPI/Pixel Ratio: 72/132.25/2
Installed mods: 
  * InventorLoader 1.5.1
  * Manipulator 1.6.3
  * sheetmetal 0.7.58
```

### Subproject(s) affected?

None

### Anything else?

This is possibly related to #13152, though I was unable to reproduce its crash, even on 1.0.2.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by pjcreath**
Check for two null pointers when walking selection geometry to update the UI after an undo/redo.

## Issues
Fixes #25497

This should be backported to the 1.1.0 release branch.

### CODE REVIEW

**Comment by chennes** [comment]
I can confirm that this fixes the crash -- @PaddleStroke I'm not sure this is a complete fix for the underlying problem, though. With the crash fixed I now get errors from Sketcher that it `cannot find subname` when I undo in a way that causes selected geometry to disappear.

**Comment by pjcreath** [comment]
True.  I considered those error messages an acceptable alternative to crashing!

**Comment by chennes** [comment]
It's a good fix that I am planning to merge (unless @PaddleStroke objects of course), but I wanted to get his eyes on it in case there's a better, or additional, fix needed.

File: src/Mod/Sketcher/Gui/CommandSketcherBSpline.cpp [hunk 1]
```diff
@@ -359,6 +359,9 @@ bool isCommandNeedingBSplineKnotActive(Gui::Document* doc)
         }
 
         auto* Obj = static_cast<Sketcher::SketchObject*>(sel[0].getObject());
+        if (!Obj) {
+            return false;
+        }
```
Comment (PaddleStroke) [inline src/Mod/Sketcher/Gui/CommandSketcherBSpline.cpp:364]: This check is not necessary I think. It does not play a role fixing the bug and I have not seen selection objects getObject being tested before. Although I may be wrong about this.
Anyway an additional check like this does not hurt and is good practice I guess.

File: src/Mod/Sketcher/Gui/Utils.cpp [hunk 2]
```diff
@@ -355,7 +355,7 @@ bool SketcherGui::isBsplineKnotOrEndPoint(
 
     const Part::Geometry* geo = Obj->getGeometry(GeoId);
     // end points of B-Splines are also knots
-    if (geo->is<Part::GeomBSplineCurve>()
+    if (geo && geo->is<Part::GeomBSplineCurve>()
```
Comment (PaddleStroke) [inline src/Mod/Sketcher/Gui/Utils.cpp:358]: This is the core fix. So what happens is that if you have a single circle, select it, the selection is now : 
object = Sketch
Subname = Edge1
The undo does not change the selection! So it stays this Sketch.Edge 1.
But the circle is not here so `getGeometry(GeoId)` returns nullptr. And then crash.

So this check is definitely needed. It should be merged.

But it does not solve the underlying problem : Undo does not clear selection. So even if it does not crash anymore, the selection is still `Sketch.Edge1`. Hence the error messages.

If you have more than 1 edge in your sketch, the edge2 becomes edge1 because of the undo, and becomes selected.

**Comment by PaddleStroke** [comment]
@chennes about the wider issue, I think it is reasonable that an undo command clears the selection. Because this problem may happen in other situations, not only in sketcher.

**Comment by PaddleStroke** [comment]
@chennes I opened an issue about it for discussion : https://github.com/FreeCAD/FreeCAD/issues/25512

File: src/Mod/Sketcher/Gui/CommandSketcherBSpline.cpp (hunk 1 above)
Comment (pjcreath) [reply src/Mod/Sketcher/Gui/CommandSketcherBSpline.cpp:364]: I think you're right that it's not necessary, but agree that it's good practice.

I'd like to figure out a more general way to prevent these kinds of crashes, but that's out of scope for 1.1!
