### PR TITLE
Gui: Fix Sketcher toolbar state not persisting across workbench switches

### LINKED ISSUE #28602: Repro steps to mess up the Sketcher toolbars
### Problem description

Not sure exactly how to title this, so feel free to tweak, just found seemingly consistent steps to mess up the Sketcher toolbars.

What follows has been tested in all versions (1.0.2, 1.1.rc3, 2026-03-18 weekly, own build from source on Windows) with exactly the same outcome in all, at least for me.

Video in the "actual behavior" section.

### Workbench affected?

Sketcher

### Steps to reproduce

First phase:
- be in sketcher editing
- disable one or more sketcher toolbars
- switch to another WB and come back to the sketcher WB
- check the state of the toolbars

Second phase:
- move one of the sketcher toolbars
- switch WB back and forth as above
- check the state of the toolbars

### Expected behavior

Phase one: 
- toolbars should not come back after I disabled them

Phase two: 
- toolbars should not get messed up in a single line

### Actual behavior

Phase one: 
- toolbars come back after I disabled them

Phase two: 
- toolbars get messed up in a single line

https://github.com/user-attachments/assets/2c015a3b-69ce-49d1-a11f-f90b2aec179f

### Development version About Info (in Safe Mode)

```shell
OS: Windows 10 build 19045
Architecture: x86_64
Version: 1.2.0dev.20260318 (Git shallow)
Build date: 2026/03/18 23:42:42
Build type: Release
Branch: grafted,grafted
Hash: 7886ebae105b99f176cddbfc62a106ab06a6d021
Python 3.11.15, Qt 6.8.3, Coin 4.0.3, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.3.0, IfcOpenShell 0.8.2, OCC 7.8.1
Locale: English/United States (en_US)
Navigation Style/Orbit Style/Rotation Mode: Blender/Rounded Arcball/Window center
Stylesheet/Theme/QtStyle: FreeCAD.qss/FreeCAD Dark/
Logical DPI/Physical DPI/Pixel Ratio: 96/81.5973/1
```

### Last known good version (optional)

```shell
none
```

### PR DESCRIPTION
**Pull request by ayyaz20003**
Simplify the ignoreSave lambda in ToolBarManager::saveState() to rely solely on the toggle-action visibility. The previous logic also checked the DefaultVisibility property, which prevented saving toolbar state for toolbars whose visibility is temporarily controlled by client code (e.g. Sketcher edit-mode toolbars using ForceAvailable). This caused disabled or repositioned toolbars to reappear/lose their layout after switching workbenches.

## Issues

Fixes #28602

### CODE REVIEW

File: src/Gui/ToolBarManager.cpp [hunk 1]
```diff
@@ -841,21 +841,12 @@ void ToolBarManager::onTimer()
...
-
-        // If DefaultVisibility is Unavailable then never save the state because it's
-        // always controlled by the client code.
-        auto value = static_cast<ToolBarItem::DefaultVisibility>(property.toInt());
-        return value == ToolBarItem::DefaultVisibility::Unavailable;
+        // If the toggle action is invisible then the toolbar is in its default
+        // unavailable state, controlled entirely by the application. Don't save.
+        // If the toggle action IS visible, client code has made it available to
+        // the user (e.g. Sketcher edit mode toolbars via ForceAvailable), so the
+        // user's visibility choice should be persisted.
```
Comment (chennes) [inline src/Gui/ToolBarManager.cpp]: This is kind of wordy... maybe just
```suggestion
        // Only save state for toolbars whose toggle action is user-visible.
```
