### PR TITLE
Gui: Add show placement to Part Datums

### LINKED ISSUE #6046: Add visual orientation while creating datum plane
Issue imported from https://tracker.freecad.org/view.php?id=4314

* **Reporter:** drmacro
* **Date submitted:** 4/14/2020
* **FreeCAD version:** 
* **Category:** Feature
* **Status:** new
* **Tags:** planes

# Original report text

https://forum.freecadweb.org/viewtopic.php?f=3&t=45159

During creation of a datum plane provide visual feedback depicting the orientation of the X,Y,Z. For example while selecting 3 point plane.

Possibly toggle on for reference at later times, to clarify orientation when creating attached sketches.

# Steps to reproduce

Create a datum plane based on existing geometry.

# FreeCAD Info

```
OS: Ubuntu 19.10 (XFCE/ubuntustudio)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.
Build type: Release
Python version: 3.7.5
Qt version: 5.12.4
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: English/United States (en_US)

```

# Other bug information

* **Priority:** normal
* **Severity:** feature
* **Category:** Feature
* **OS: All All**
* **Platform:** All
* **Updated:** 2/6/2021

### LINKED ISSUE #19894: Show placement helper visibility issues
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Problem description

The new show placement property (https://github.com/FreeCAD/FreeCAD/pull/19671) currently has three issues:
- it is always visible, even when the object is hidden:

Image

- it is not visible if it is behind geometry:

Image

- it sometimes displays multiple placement axes at different locations for one body:

Image

### Full version info

```shell
OS: Windows 10 build 19045
Architecture: x86_64
Version: 1.1.0dev.40421 (Git) Conda
Build type: Release
Branch: main
Hash: f9bb6508ffb420502d7b91592d87ea4f95c399d4
Python 3.11.11, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, IfcOpenShell 0.0.0, OCC 7.8.1
Locale: German/Germany (de_DE)
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Dark/Fusion
Logical/physical DPI: 96/141.951
Installed mods: 
  * Curves 0.6.58
  * fasteners 0.5.37
  * freecad.gears 1.3.0
  * Manipulator 1.5.7
```

### Subproject(s) affected?

Core

### Anything else?

_No response_

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by maxwxyz**
https://github.com/FreeCAD/FreeCAD/pull/19671 introduced a helper to show the placement in the 3D view.
It workes for all objects but the core datums.
This PR adds this to the Core Datums.
AI helped.

Fixes https://github.com/FreeCAD/FreeCAD/issues/6046
Fixes https://github.com/FreeCAD/FreeCAD/issues/19894

Bildschirmfoto 2026-04-08 um 12 48 08

### CODE REVIEW

File: src/Gui/ViewProviderDatum.cpp [hunk 1]
```diff
@@ -46,6 +47,14 @@ PROPERTY_SOURCE(Gui::ViewProviderDatum, Gui::ViewProviderGeometryObject)
 
 ViewProviderDatum::ViewProviderDatum()
 {
+    ADD_PROPERTY_TYPE(
+        ShowPlacement,
+        (false),
+        "Display Options",
+        App::Prop_None,
+        "If true, placement of object is additionally rendered."
+    );
```
Comment (kadet1090) [inline src/Gui/ViewProviderDatum.cpp]: That propery shall not be duplicated across codebase. If needed it probably should be moved to ViewProviderGeometryObject? Or maybe VP extension.

File: src/Mod/Part/Gui/ViewProviderDatum.cpp [hunk 2]
```diff
@@ -81,6 +84,39 @@ PROPERTY_SOURCE_WITH_EXTENSIONS(PartGui::ViewProviderLCS, Gui::ViewProviderCoord
...
+}
+
+void ViewProviderLCS::onChanged(const App::Property* prop)
+{
+    if (prop == &ShowPlacement || prop == &Visibility) {
+        pcPlacement->whichChild = (ShowPlacement.getValue() && Visibility.getValue())
+            ? SO_SWITCH_ALL
+            : SO_SWITCH_NONE;
+    }
+    Gui::ViewProviderCoordinateSystem::onChanged(prop);
```
Comment (kadet1090) [inline src/Mod/Part/Gui/ViewProviderDatum.cpp]: yep duplicated too

**Review by kadet1090 — CHANGES_REQUESTED** [review]

**Comment by maxwxyz** [comment]
@kadet1090 I've moved it to ViewProviderDragger

File: src/Mod/Part/Gui/TaskAttacher.cpp [hunk 3]
```diff
@@ -1259,8 +1259,9 @@ void TaskAttacher::showPlacementUtilities()
         overrides.override(planarViewProvider->ShowPlane, true);
     }
 
-    if (auto partViewProvider = freecad_cast<PartGui::ViewProviderPartExt*>(ViewProvider)) {
-        overrides.override(partViewProvider->ShowPlacement, true);
+    if (auto* prop
+        = dynamic_cast<App::PropertyBool*>(ViewProvider->getPropertyByName("ShowPlacement"))) {
+        overrides.override(*prop, true);
```
Comment (kadet1090) [inline src/Mod/Part/Gui/TaskAttacher.cpp]: Is that change needed?

Comment (maxwxyz) [reply src/Mod/Part/Gui/TaskAttacher.cpp]: Yes, datums inherit from VPdragger, VPPartExt is not in that chain

Comment (kadet1090) [reply src/Mod/Part/Gui/TaskAttacher.cpp]: VPPartExt inherits from VPDragger, so if you do freecad_cast to dragger and do

```
if (auto draggerViewProvider = freecad_cast<Gui::ViewProviderDragger*>(ViewProvider)) {
```

it should work?

Comment (maxwxyz) [reply src/Mod/Part/Gui/TaskAttacher.cpp]: It works!

**Comment by kadet1090** [comment]
@FEA-eng can you retest after changes?

**Review by kadet1090 — APPROVED** [review]

**Comment by FEA-eng** [comment]
> @FEA-eng can you retest after changes?

Sure, I will check it tomorrow.

**Review by FEA-eng — APPROVED** [review]
@kadet1090 I retested it, and it works - shows placement when editing attachment, otherwise disables it by default (but can be enabled with a property). LCS now doesn't have that, as I suggested above.
