### PR TITLE
Fem: Add support for 2D loads with CalculiX

### LINKED ISSUE #12778: FEM: pressure load doesn't work in 2D analyses with CalculiX
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Currently, pressure load can only be applied to faces. The selector rejects edges even though they can be loaded with pressure in 2D analyses:

pressure 2D

Maybe it could also work for beams (uniformly distributed load) and shells (shell edge load).

CalculiX offers the `*DLOAD` keyword with proper face/edge IDs for such loads.

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36277 (Git)
Build type: Release
Branch: main
Hash: 9e1903d46112b3660bf10c6a4537d728101d560b
Python 3.10.13, Qt 5.15.8, Coin 4.0.2, Vtk 9.2.6, OCC 7.6.3
Locale: Polish/Poland (pl_PL)
```

### Subproject(s) affected?

FEM

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #13280: FEM: Contact and tie constraint should be applicable to edges in 2D analyses
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

An option to apply contact and tie constraints to edges (currently only faces can be selected) would be very useful for 2D analyses with CalculiX. Internally, edges of 2D elements (plane stress/strain and axisymmetric) are treated as faces (and numbered properly) in CalculiX.

@marioalexis84 FYI

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36731 (Git)
Build type: Release
Branch: main
Hash: ac1d887336826c59321352f49a195bf1ef8be2f0
Python 3.11.8, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: Polish/Poland (pl_PL)
```

### Subproject(s) affected?

FEM

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by marioalexis84**
Add support for 2D loads for CalculiX to:
* Tie constraint
* Contact constraint
* Pressure constraint
* Heat Flux constraint
* Body Heat Source constraint

Edges and faces behave like faces and solids in 3D models, respectively.
2D thermal analysis should be tested with the new CalculiX solver (the old one does not load heat flux values ​​correctly).

TODO: The orientation of the symbols for the 2D case remains to be corrected. Currently, they point along the normal direction to the surface.

@FEA-eng 

## Issues

fixes #13280, fixes #12778

### CODE REVIEW

File: src/Mod/Fem/Gui/TaskFemConstraintContact.cpp [hunk 1]
```diff
@@ -227,8 +227,10 @@ void TaskFemConstraintContact::addToSelectionSlave()
         }
         for (const auto& subName : subNames) {  // for every selected sub element
             bool addMe = true;
-            if (subName.substr(0, 4) != "Face") {
-                QMessageBox::warning(this, tr("Selection error"), tr("Only faces can be picked"));
+            if ((subName.substr(0, 4) != "Face") && (subName.substr(0, 4) != "Edge")) {
+                QMessageBox::warning(this,
+                                     tr("Selection error"),
+                                     tr("Only faces or can be picked (edges in 2D models)"));
```
Comment (FEA-eng) [inline src/Mod/Fem/Gui/TaskFemConstraintContact.cpp]: Here and below you should remove "or" from the error message.

**Review by FEA-eng — APPROVED** [review]
Tested (also verified with other preprocessor). Everything works flawlessly.

**Comment by stefano2734** [comment]
Calculix 2.23 is available.
perhaps a test shoulde be done also with 2.23

**Comment by FEA-eng** [comment]
> Calculix 2.23 is available. perhaps a test shoulde be done also with 2.23

From what I know, there are no changes in this aspect. And 2.23 may not make it to FreeCAD 1.1.0. But once this new ccx version is normally available for Windows (for now, it's provided as an archive needing an unknown password), I will probably do some testing in general (just more regarding bugs that should be fixed now).
