### PR TITLE
fix #10514

### LINKED ISSUE #10514: [Problem] Failed to compute left/right minimum bearings for "cursor.pcf"
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

If I try to use the provided "Dark theme" or the "Light theme" preference packs and then try to open the "view > panels > report view" freecad starts reporting: `Failed to compute left/right minimum bearings for "cursor.pcf"` repeatedly. Eventually consumes 100% of a core and becomes unresponsive.

I also tried getting other themes with "tools > addon manager" and they exhibited the same behaviour.

Reason I'd like to use the "Dark theme" is that otherwise I'll have white text on white background in the spreadsheet rendering it unusable. Should this be reported separately?

### Full version info

```shell
[code]
OS: Arch Linux (openbox)
Word size of FreeCAD: 64-bit
Version: 0.21.1.33694 (Git)
Build type: Release
Branch: makepkg
Hash: f6708547a9bb3f71a4aaade12109f511a72c207c
Python 3.11.5, Qt 5.15.10, Coin 4.0.1, Vtk 9.2.6, OCC 7.6.3
Locale: English/United States (en_US)
[/code]
```

### Subproject(s) affected?

None

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by julian1**
Fix https://github.com/FreeCAD/FreeCAD/issues/10514

This change blacklists the cursor.pcf font from being background saved into the preferences serialization file.
When this font is loaded, extents cannot be computed, and Freecad freezes at 100% cpu, with errors streamed to stderr.

A proposed workaround, that involves manually editing ~/.config/FreeCAD/user.cfg, to clear the cursor.pcf field when modified, only goes so far.

Since some actions that trigger the behavior - such as DXF import and export - don't provide any opportunity to save work, before one has to perform the pkil, and re-edit the user.cfg, so it is not possible to progress the design.

I believe this change is low risk, since it follows https://github.com/FreeCAD/FreeCAD/pull/10555

tested on nixos with freecad v1.0.1.

Direct nixos patch, https://github.com/NixOS/nixpkgs/pull/412903

### CODE REVIEW

**Comment by chennes** [comment]
Thanks for the PR, @julian1 -- for those who don't feel like reading the entire issue (which does a wonderful job of diagnosing the underlying problem) the upshot is that this is really a sort of stopgap solution to solve an immediate problem, but that fundamentally Qt's font manager is at fault. There's some discussion in the issue, but it seems there is not a really good general solution to the problem, so in order to prevent what is otherwise a quite serious bug on some systems, I think this is a reasonable way forward. I'm going to propose adding a comment in the code that points to that issue so that future code archaeologists can figure out why it's been done, though.

File: src/Gui/PreferencePages/DlgSettingsEditor.cpp [hunk 1]
```diff
@@ -273,7 +273,9 @@ void DlgSettingsEditor::loadSettings()
     QStringList fixedFamilyNames;
     for (const auto& name : familyNames) {
         if (QFontDatabase().isFixedPitch(name)) {
-            if (name.compare(QLatin1String("8514oem"), Qt::CaseInsensitive) != 0) {
+            if (name.compare(QLatin1String("8514oem"), Qt::CaseInsensitive) != 0
```
Comment (chennes) [inline src/Gui/PreferencePages/DlgSettingsEditor.cpp:278]:
```suggestion
            // cursor.pcf was removed to cope with a problem with the Qt Font Manager
            // See https://github.com/FreeCAD/FreeCAD/issues/10514 for details
            if (name.compare(QLatin1String("8514oem"), Qt::CaseInsensitive) != 0
```

File: src/Gui/PreferencePages/DlgSettingsEditor.cpp [hunk 2]
```diff
@@ -283,7 +285,9 @@ void DlgSettingsEditor::loadSettings()
     QStringList fixedFamilyNames;
     for (const auto& name : familyNames) {
         if (QFontDatabase::isFixedPitch(name)) {
-            if (name.compare(QLatin1String("8514oem"), Qt::CaseInsensitive) != 0) {
+            if (name.compare(QLatin1String("8514oem"), Qt::CaseInsensitive) != 0
```
Comment (chennes) [inline src/Gui/PreferencePages/DlgSettingsEditor.cpp:292]:
```suggestion
            // cursor.pcf was removed to cope with a problem with the Qt Font Manager
            // See https://github.com/FreeCAD/FreeCAD/issues/10514 for details
            if (name.compare(QLatin1String("8514oem"), Qt::CaseInsensitive) != 0
```

**Comment by julian1** [comment]
I have accepted [chennes](https://github.com/chennes) proposed changes to better document the source of the mischief.

I am not sure what is good github etiquette, but I squashed and forced pushed-back the changes, to keep everything tidy and in one commit, although I note the co-authorship attribution is lost which was not intended.

**Comment by chennes** [comment]
Squashing and force-pushing is just fine (and the co-authorship was not lost, it's still present, GitHub just doesn't do a great job of displaying it).
