### PR TITLE
Horrible hack to work around bug in OCCT7.7.2

### LINKED ISSUE #15599: [Regression] Boolean failures with OCC 7.7.2
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

You'll need this
[cone-common-bug.FCStd.delete.this.extension.zip](https://github.com/user-attachments/files/16365325/cone-common-bug.FCStd.delete.this.extension.zip)

In the screenshot below, I have the cone (50% transparent) and the pad from sketch shown. The common does not produce a shape, and shows the message:

`<Part> ViewProviderExt.cpp(1299): Cannot compute Inventor representation for the shape of cone_common_bug#Common001: Bnd_Box is void`

Screenshot_20240724_122959

Screenshot_20240724_122902

Changing any dimension of the cone by 0.001 mm, or changing the cone angle to anything other than 360 fixes the common. I tried to reproduce this with a cone and a wedge but was unsuccessful.

### Full version info

```shell
OS: Gentoo Linux (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38314 (Git) AppImage
Build type: Release
Branch: main
Hash: 3fa339e9eb71d34542e463b3f4581857a9e696fb
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Installed mods: 
  * parts_library
  * Curves 0.6.42
  * A2plus 0.4.65
  * DynamicData 2.62.0
  * Assembly4 0.50.15
  * Defeaturing 1.2.2
  * dodo 1.0.1
  * Alternate_OpenSCAD 1.0.0 (Disabled)
  * CurvedShapes 1.0.9
  * Design456 0.0.1
  * fasteners 0.5.24
  * SearchBar 1.0.2
  * DesignSPHysics 0.7.0(15-09-2023)
  * cadquery_module
  * ose-piping
  * Nodes 0.1.36
  * 3D_Printing_Tools
  * Pyramids-and-Polyhedrons
  * workfeature (Disabled)
  * MnesarcoUtils 0.2.5
  * OpenTheme 2024.7.3
  * Manipulator 1.5.7
  * Assembly3 0.12.2
  * lattice2 1.0.0
  * ThreadProfile 1.90.0
  * freecad.gears 1.2.0
  * Launcher
  * CommandPanel
  * CubeMenu
  * Reinforcement
  * PieMenu 1.7.5
  * MeshRemodel 1.9.23
```

### Subproject(s) affected?

Part

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by bgbsww**
Fix #15599.

The failure is actually in cone, and represents a bug in 7.7.2 but not 7.6.3 and not 7.8.x.  Angle values of 360.0 fail completely, 359.9999 and 359.999 partially, and 359.99 results in an ugly fix.

If it isn't clear, I hate this code, but it seems like the pragmatic best choice; the alternative is FreeCADs with 7.7.2 don't work with cones of 360 degrees.  I'm gonna take a bath now.

### CODE REVIEW

File: src/Mod/Part/App/PrimitiveFeature.cpp [hunk 1]
```diff
@@ -652,6 +652,13 @@ App::DocumentObjectExecReturn *Cone::execute()
         return new App::DocumentObjectExecReturn("Radius of cone too small");
     if (Height.getValue() < Precision::Confusion())
         return new App::DocumentObjectExecReturn("Height of cone too small");
+    double angle = Angle.getValue();
+#if OCC_VERSION_HEX == 0x070702
+    // OCCT 7.7.2 will not model a cone with an angle of exactly 360, so we cheat:
+    if ( angle == 360.0) {
+5        angle = 359.99;
```
Comment (oursland) [inline src/Mod/Part/App/PrimitiveFeature.cpp:659]: I think the '5' may be a typo.

Comment (bgbsww) [reply src/Mod/Part/App/PrimitiveFeature.cpp:659]: Yep.  I blame having fortran on my brain  ( bad punched card joke ).  Thanks!

File: src/Mod/Part/App/PrimitiveFeature.cpp [hunk 2]
```diff
@@ -665,7 +672,7 @@ App::DocumentObjectExecReturn *Cone::execute()
             BRepPrimAPI_MakeCone mkCone(Radius1.getValue(),
                                         Radius2.getValue(),
                                         Height.getValue(),
-                                        Angle.getValue()/180.0f*M_PI);
+                                        angle/180.0f*M_PI);
```
Comment (jbaehr) [inline src/Mod/Part/App/PrimitiveFeature.cpp:675]: nitpick: maybe use `Base::toRadians`, as elsewhere in this file?

Comment (bgbsww) [reply src/Mod/Part/App/PrimitiveFeature.cpp:675]: Absolutely a legitimate point, but M_PI / 180 appears about 68 times, and 180 / M_PI appears 10 times, and 180 * M_PI appears 9 times and 180.0f*M_PI appears 9 times (8 in this very file) ...  you get the point.  I think that should be somebody's separate PR to clean up all the angle/radian conversions, and not part of this extremely narrowly focused piece of nastiness, since there isn't a clear line on where to stop.  Just this one?  This one and the one in the clause above it?  All of them in this file?  All of them in App?

Comment (jbaehr) [reply src/Mod/Part/App/PrimitiveFeature.cpp:675]: I see your point and I agree that this very OCCT workaround should not be mixed with general cleanup.
However, if I touch a line of code anyway, I can "touch it for the better".  -- Your mileage may vary and I accept that.

Comment (chennes) [reply src/Mod/Part/App/PrimitiveFeature.cpp:675]: @jbaehr can you make an Issue for that? We can discuss in tomorrow's review meeting, but I'm inclined to merge this as-is and then promote a bigger-picture refactor to make the suggested change.

**Comment by wwmayer** [comment]
Such ugly workarounds should really be avoided because they don't fix anything but move problems from A to B. Only because a cone with an angle of 359.99 seems to work here doesn't mean that the cone feature (or the BRepPrimAPI_MakeCone algorithm, respectively) is to blame. After all it's still the boolean operation that causes the problem.

Now the first regressions of this workaround can be seen here:
* https://github.com/FreeCAD/FreeCAD/issues/17286
* https://forum.freecad.org/viewtopic.php?t=91426

**Comment by yorikvanhavre** [comment]
Do you feel we should revert this one, @wwmayer ?

**Comment by wwmayer** [comment]
Yes.

The problem reported in https://github.com/FreeCAD/FreeCAD/issues/15599. is not because of a bug in the cone creation but in the boolean operation. And when reading further this problem doesn't only occur with OCC 7.7.2 but also with 7.8.1. 

And as Syres916 correctly figured out it's a problem with co-planar faces. And this is a general problem with OCC we very frequently see with boolean operations.

Btw , a much better workaround than using an angle of 359.99 is to rotate the cone around its main axis. It suffices to rotate it a tiny bit but I recommend to rotate it by 90 deg because then the seam edge is not so visible. And the nice side-effect is that even the geometry checker doesn't find any defects in the shape any more while with this PR it still finds defects.

**Comment by wwmayer** [comment]
Here is an interesting reading about the failure of boolean operations: https://wiki.mcneel.com/rhino/booleanfaq
The problems are the same in OCC.

**Comment by FlachyJoe** [comment]
OCC can't merge coplanar face but can fill a hole between them (see fuzzy value) so we could create a hole.
Maybe we should hack all shapes to reduce their size and set the Fuzzy equal to the shrink, we can get the correct result size next by setting its Tolerance.

**Comment by wwmayer** [comment]
> Can you make a PR for that? Otherwise I can try too, but not sure where it should be done... Not at cone creation ,right?

This isn't something that should be coded but it must be done by the user. As explained in the Rhino FAQ the user must be aware of the problems with boolean operations and he has to help the kernel to do its job right.

**Comment by yorikvanhavre** [comment]
Ok I see... You mean if there are problems with coinciding faces/edges. the user should move something, change something or as in your example, rotate the cone slightly. But it's not us who should arbitrarily rotate a cone to hypothetically prevent a possible boolean problem. Indeed that makes sense to me too. In most other cases which don't involve booleans, the user will expect the topology to be correctly aligned by default.
