### PR TITLE
GUI: Fix Toggle Freeze Behavior

### LINKED ISSUE #18806: PartDesign: Strange behavior Toggle freeze elements of PD body
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Click **Toggle freeze** for body object.
The elements inside are also frozen.
It's not clear how to get everything back.

https://github.com/user-attachments/assets/f6258901-8fad-4edc-8d88-e168f66a5969

Another example.
I get some project with CAM.
Used **Toggle freeze** for body object.
Get frozen elements in project which not so easy to find.
Also can`t save project while some elements frozen

https://github.com/user-attachments/assets/20e8d0b2-6e2c-494e-b187-94792e549ed1

First time i found this problem and I unfreeze all elements inside tree one by one. But now feature **Toggle freeze** disappear for elements inside body.
The result is a dead end from which there is no way out.
The project cannot be saved and the action cannot be undone.

https://github.com/user-attachments/assets/9ba9cccd-ce46-4625-b9f4-23af488caf53

### Full version info

```shell
OS: Arch Linux (KDE/plasma/xcb)
Architecture: x86_64
Version: 1.1.0dev.39741 (Git) Conda AppImage
Build type: Release
Branch: main
Hash: 0d128517dedd154bbecfbabe67094ad56c8d46f5
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Dark/Fusion
Installed mods: lattice2 1.0.0; CurvedShapes 1.0.13; MeshRemodel 1.10.35; freecad.gears 1.3.0; fasteners 0.5.33; sheetmetal 0.6.12; Silk 0.1.5; Curves 0.6.52
```

### Subproject(s) affected?

None

### Anything else?

[VacuumTable.zip](https://github.com/user-attachments/files/18277705/VacuumTable.zip)
[VacuumTable_2024-12-30_19-15-55.zip](https://github.com/user-attachments/files/18277802/VacuumTable_2024-12-30_19-15-55.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by vletii**
Previously, the `StdCmdToggleFreeze` command only unfroze objects using `getInListRecursive()`, meaning that unfreezing an element would only affect itself or the elements that contained it.
This caused issues when using Toggle Freeze for a Body object, as it made it difficult to identify all frozen elements in a project, and the presence of frozen elements prevented the project from being saved.

Cause of the Bug
The unfreeze operation only considered outward dependencies, meaning that elements further down the hierarchy (inward dependencies) were not properly unfrozen.

Fix Implementation
Updated the `StdCmdToggleFreeze` command, so that objects are properly unfrozen when toggling freeze state.

Fix #18806

### CODE REVIEW

**Comment by chennes** [comment]
Thanks for the PR, @vletii -- we're waiting for a comment from @FlachyJoe on this one since he had an opinion about it in the issue. Sorry for the delay -- the code itself looks good, it's just figuring out the correct behavior here that looks a bit tricky.

**Review by FlachyJoe — APPROVED** [review]

File: src/Gui/CommandFeat.cpp [hunk 1]
```diff
@@ -185,6 +185,14 @@ void StdCmdToggleFreeze::activated(int iMsg)
             obj->unfreeze();
             for (auto child : obj->getInListRecursive())
                 child->unfreeze();
+            if (obj->isDerivedFrom(Base::Type::fromName("PartDesign::Body"))) {
+                for (auto child : obj->getOutListRecursive())
```
Comment (marioalexis84) [inline src/Gui/CommandFeat.cpp:189]: There should be no references to extension modules such as `PartDesign` in the core code (Base, App, Gui)

Comment (marioalexis84) [reply src/Gui/CommandFeat.cpp:189]: @chennes @hyarion

Comment (hyarion) [reply src/Gui/CommandFeat.cpp:189]: We should never include them, in this case it's a soft dependency which is less of a problem as you can still use it even if the type is not included (still not preferred though). Iirc, similar solutions has been done previously.

@marioalexis84 do you have any suggestion on how to eliminate this soft dependency?

Comment (marioalexis84) [reply src/Gui/CommandFeat.cpp:189]: I'm a bit busy working on FEM, but if no one fixes this anytime soon, I can look into the problem.

Comment (vletii) [reply src/Gui/CommandFeat.cpp:189]: I made the suggested changes (removed the soft dependency) and pushed them to my fork [here](https://github.com/vletii/FreeCAD/commit/a1739cf397511ff2f3dbf46b264575a7822ff8b7). Since the PR is already closed, it doesn’t show up here, but please do take a look.
For a bit of context: I initially added that check because I wasn’t totally sure what the expected behavior was. I’ve now removed it, and while the behavior changes slightly, it still seems like an improvement overall. With that being said, I’m still not completely sure this is the behavior we want, so I'm open to feedback.

Comment (FlachyJoe) [reply src/Gui/CommandFeat.cpp:189]: @vletii Feel free to open a draft PR with your changes and ping contributors of this one.

The _freeze_ behavior is not very clear. When I first introduce the feature it was intend to simply block recompute of an object without taking care of dependencies. But it wasn't considered satisfying and was changed to also block dependencies recompute.
Now I find it quite useless because you can't freeze a heavy-compute feature of a body without freezing the entire body.
E.g. consider this model
image
I'd like to change the Pad properties but I don't want to recompute the Helix until I'm sure of the values to set. I can't.

The freeze sate also block the document save because the model is **broken**. It's a transient state which force a recompute when it's switched off so we should be allowed to have outdated shapes.

Comment (vletii) [reply src/Gui/CommandFeat.cpp:189]: I see, that makes sense. I didn’t realize the original idea was to freeze just the object. Hopefully this change is still a small step in the right direction, even if the overall behavior needs a rethink. I’ll open a draft PR so we can continue the convo there.
