### PR TITLE
Sketcher: skip autoscale when dimension value yields invalid scale factor

### LINKED ISSUE #29089: Sketcher: autoscale fails if dimension value is zero
### Problem description

Autoscale fails if the dimension value is zero. The following warning is displayed:

> Exception performing autoscale: Invalid scale factor. Scale factor must be a positive number.

### Workbench affected?

Sketcher

### Steps to reproduce

1. Create a sketch.
2. Create 2 lines.
3. Start Sketcher_Dimension.
4. Select an endpoint of each line.
5. Click a point to position the dimension.
6. Enter 0 (zero) for the dimension value.
7. Result: warning.

### Expected behavior

No warning and no zoom.

### Actual behavior

n/a

### Development version About Info (in Safe Mode)

```shell
OS: Ubuntu 22.04.5 LTS (ubuntu:GNOME/ubuntu/wayland)
Architecture: x86_64
Version: 1.2.0dev.20260401 (Git shallow) AppImage
Build date: 2026/04/01 04:43:57
Build type: Release
Branch: (HEAD detached at 33dcd31f5)
Hash: 33dcd31f5e2175e7dcdfd3caf1d9d86440919bfc
Python 3.11.14, Qt 6.8.3, Coin 4.0.8, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.3.0, IfcOpenShell 0.8.2, OCC 7.8.1
Locale: Dutch/Netherlands (nl_NL)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/
Navigation Style/Orbit Style/Rotation Mode: CAD/Turntable/Object center
Logical DPI/Physical DPI/Pixel Ratio: 96/86.1283/1
Installed mods:
```

### Last known good version (optional)

```shell

```

### PR DESCRIPTION
**Pull request by Bojan9597**
Fixes #29089

Added an early return in `EditDatumDialog::performAutoScale` when the computed scale factor is zero or invalid, so entering `0` as a dimension value no longer triggers the warning.

### CODE REVIEW

File: src/Mod/Sketcher/Gui/EditDatumDialog.cpp [hunk 1]
```diff
@@ -489,7 +491,15 @@ void EditDatumDialog::performAutoScale(double newDatum)
             }
 
             double oldDatum = sketch->getDatum(ConstrNbr);
+            if (!std::isfinite(newDatum) || !std::isfinite(oldDatum)
+                || std::abs(oldDatum) <= Precision::Confusion()) {
+                return;
+            }
+
             double scaleFactor = newDatum / oldDatum;
+            if (!std::isfinite(scaleFactor) || scaleFactor <= Precision::Confusion()) {
```
Comment (theo-vt) [inline src/Mod/Sketcher/Gui/EditDatumDialog.cpp]: You could probably early exit also if scale is 1 so that we don't do a no op, but maybe not relevant

**Review by theo-vt — APPROVED** [review]

**Review by FEA-eng — APPROVED** [review]
Tested, fixes the issue

**Comment by FEA-eng** [comment]
@maxwxyz Can you add the Approved label?

**Comment by Bojan9597** [comment]
Can we merge it, if it is ok?

**Comment by chennes** [comment]
Can you address the comment from @theo-vt ?

**Review by theo-vt — APPROVED** [review]
