### PR TITLE
Fixes hole thread pitch

### LINKED ISSUE #20579: PartDesign: Thread pitch size not remembered
### Problem description

1. Create a hole of standard Metric - Fine, with thread pitch M12x1.5.
2. Ok. The thread in the preview, if you get it to work, is correct.
3. Double-click on Hole again. Now the panel shows M12x1.0. If you refresh the preview somehow, the thread in the preview goes down to M12x1.0. But I am unable to show this in this bug report because I get "removing splitter failed" in this extremely simple demo project, but not in my more sophisticated real project - I'm opening a separate issue for that.

If you have trouble "refreshing the preview", just save the file and reload it. If you decompress and analyze the saved file in a text editor, you can see it saved the wrong size index.

### Full version info

```shell
OS: Manjaro Linux (KDE/plasma/xcb)
Architecture: x86_64
Version: 1.1.0dev.41080 (Git)
Build date: 2025/03/31 13:17:51
Build type: Release
Branch: main
Hash: ee6f757c577b20b5bfe29ebee26a0651a7c7c921
Python 3.13.2, Qt 6.8.2, Coin 4.0.3, Vtk 9.4.1, OCC 7.8.1
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Dark/
Logical DPI/Physical DPI/Pixel Ratio: 96/108.888/1.5
Installed mods: 
  * OpenDark 2023.12.17
  * A2plus 0.4.68
  * fasteners 0.5.38
  * Woodworking 0.21.2.33771
  * CurvedShapes 1.0.13
  * Curves 0.6.60
```

[threadpitch.zip](https://github.com/user-attachments/files/19555918/threadpitch.zip)

Image

Image

Image

### PR DESCRIPTION
**Pull request by Beep6581**
When using a threaded hole, the code which finds the closest matching thread size would not take the thread pitch into account, leading to the user's selection being quietly changed and the model actually having a hole of the wrong pitch even though the preview and the Hole dialog pitch drop-down showed the correct value. Now the pitch is taken into account and preserved.

Closes #20579

### CODE REVIEW

**Comment by chennes** [comment]
Thanks for the PR, @Beep6581 -- I haven't looked, does FeatureHole have any tests? This seems like a regression that we should add some checks for.

**Comment by Beep6581** [comment]
Hello. I don't know, and I'm away from a computer for a few days, but would be nice if this was merged meanwhile so that threads work again on nightly builds.

File: src/Mod/PartDesign/App/FeatureHole.cpp [hunk 1]
```diff
@@ -1379,31 +1379,40 @@ double Hole::getThreadProfileAngle()
...
+        double pDiff = options[i].pitch - targetPitch;
+        double metric = std::hypot(dDiff, pDiff);
+        if (metric < bestMetric) {
+            bestMetric = metric;
+            bestIndex = i;
         }
     }
-    ThreadSize.setValue(closestSize);
+
+    ThreadSize.setValue(static_cast<int>(bestIndex));
```
Comment (hyarion) [inline src/Mod/PartDesign/App/FeatureHole.cpp:1415]: How about:
```cpp
auto bestIt = std::ranges::min_element(options, {}, [&](const auto& option) {
    double dDiff = option.diameter - diameter;
    double pDiff = option.pitch - targetPitch;
    return std::hypot(dDiff, pDiff);
});

size_t bestIndex = bestIt == options.end() ? 0 : std::distance(options.begin(), bestIt);
ThreadSize.setValue(static_cast<int>(bestIndex));
```

**Review by hyarion — COMMENTED** [review]
I haven't tried this but it looks like a good change.

I think the actual bug was to compare floating point values with `==` instead of adding an uncertainty, causing an off by one, but this should render better result.

Using `std::hypot` was an interesting choice, but measuring the euclidean distance (or cosine similarity) is common when trying to find the best fit with multidimensional data and it does take care of some edge case issues (keeping a similar thread size could be more important than an exact diameter.

**Comment by chennes** [comment]
@FreeCAD/cad-working-group is this how this feature should work?

**Comment by pierreporte** [comment]
If user input is ignored, it’s always bad. For threads, pitch is absolutely essential. This change is good.

**Comment by hyarion** [comment]
@pierreporte it needs fixing, no question about that, but what I wonder here is how we should prioritize diameter and threads sizes when there's no perfect match.

This change tries to find the lowest value for:`sqrt(diff_diameter^2 + diff_thread_pitch^2)`
which means that that if diameter and theads doesn't match up, it will weigh errors in tread pitch as much as error in diameter.

Another alternative would be to first look at the diameter to find the closest one there, then find the closest matching thread pitch.

example (extreme case):
lets say the user wants `M30x4`, but valid options are only `M30x1` and `M32x5`.
Then, what would be a better choice in this situation? `M30x1` or `M32x5`?


As this change tries to minimize overall change, it would choose `M32x5`. Both seem to be bad options, but which is better?

**Comment by pierreporte** [comment]
@hyarion I have read the issue, and I don’t understand why it is necessary to find the closest match. In the issue, the user selects an existing thread, and the 3D model changes more or less accordingly (because of the bug). The question is relevant for thread applied to existing holes though, and in this case I would lean towards diameter first.

File: src/Mod/PartDesign/App/FeatureHole.cpp (hunk 1 above)
Comment (hyarion) [reply src/Mod/PartDesign/App/FeatureHole.cpp:1415]: @pierreporte mentioned that it would be good to prioritize diameter first.

By returning a pair instead of the result from `hypot` would do that if `dDiff` is placed in the first slot.
It would look something like:
```c++
auto bestIt = std::ranges::min_element(options, {}, [&](const auto& option) {
    double dDiff = std::abs(option.diameter - diameter);
    double pDiff = std::abs(option.pitch - targetPitch);
    return std::make_pair(dDiff, pDiff);
});

size_t bestIndex = bestIt == options.end() ? 0 : std::distance(options.begin(), bestIt);
ThreadSize.setValue(static_cast<int>(bestIndex));
```

**Comment by hyarion** [comment]
> @hyarion I have read the issue, and I don’t understand why it is necessary to find the closest match. In the issue, the user selects an existing thread, and the 3D model changes more or less accordingly (because of the bug).
> The question is relevant for thread applied to existing holes though, and in this case I would lean towards diameter first.

Thanks

**Comment by Beep6581** [comment]
@pierreporte I think it's about finding the closest match if you switch e.g. from Metric Course to Metric Fine, so that it defaults to something similar in the newly selected standard.

Regardless how the exact match is performed or whether you decide to delete matching logic entirely, the current behavior is completely broken (assuming you did not select the first available pitch of a given diameter) so it would be nice if this was committed and improvements were made on top, so that there is at least some build of FreeCAD where threads work.

**Comment by pierreporte** [comment]
@Beep6581 Still, I don’t get why we discuss about matching because the geometry is changed to fit the selected standard when the threaded hole is created as a whole directly. The thread is not applied to an existing hole. The linked issue seems completely irrelevant to me.

**Comment by hyarion** [comment]
I'm merging this and creating an issue for the additional work.
