### PR TITLE
Sketcher: Fix Arrow Direction of Angle Arrows

### LINKED ISSUE #20098: Sketcher: Angle rendering broken for negative angles
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Problem description

Image

If you use the arc tool for example. If the angle shown in the OVP is negative, then the rendering of the soDatumLabel is wrong. It was good before : this is a regression of https://github.com/FreeCAD/FreeCAD/pull/17720.

### Full version info

```shell
1.1
```

### Subproject(s) affected?

Sketcher

### Anything else?

_No response_

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by matthiasdanner**
## Issues

fixes #20098
For negative angles the arrows on the end of the arc where rendered in the wrong direction. This PR fixes that. Positive Angles were correct before and were not changed
Also fixes the huge gap next to the angle box

## Before and After Images

Before:
* Screenshot 2025-05-29 231026
* Screenshot 2025-05-29 231724

After:
* Screenshot 2025-05-29 235836
* Screenshot 2025-05-29 235716

### CODE REVIEW

**Comment by luzpaz** [comment]
@AjinkyaDahale do you mind reviewing ?

File: src/Gui/SoDatumLabel.cpp [hunk 1]
```diff
@@ -1465,13 +1465,20 @@ void SoDatumLabel::drawAngle(const SbVec3f* points, float& angle, SbVec3f& textO
...
-    SbVec3f v2(cos(endangle),sin(endangle),0);
+    SbVec3f *v1, *v2;
+    if (range < 0) {
+        v2 = new SbVec3f(cos(startangle), sin(startangle), 0);
+        v1 = new SbVec3f(cos(endangle), sin(endangle), 0);
+    }
+    else {
+        v1 = new SbVec3f(cos(startangle), sin(startangle), 0);
+        v2 = new SbVec3f(cos(endangle), sin(endangle), 0);
+    }
```
Comment (hyarion) [inline src/Gui/SoDatumLabel.cpp:1476]: How about doing the old way and use [std::swap](https://en.cppreference.com/w/cpp/algorithm/swap.html) if range < 0 instead?

Comment (matthiasdanner) [reply src/Gui/SoDatumLabel.cpp]: thanks for calling that out, I changed it accordingly

**Comment by PaddleStroke** [comment]
Thanks for looking into this!
