### PR TITLE
Fix rotation expression errors in handleLegacyTangentPlaneOrientation()

### LINKED ISSUE #26056: Part: Rotation expression errors with unit mismatch and angle range in handleLegacyTangentPlaneOrientation()
### Workbench affected?

Part Design

### Problem description

The function handleLegacyTangentPlaneOrientation() was introduced in PR 
* #24529.

Later I found two problems related to rotation expressions.

Issue 1: Unit mismatch
- The added rotation angle unit may cause unit mismatch errors if it does not match the unit of the original expression
- The original expression unit is often an angle (degrees), but it can also be unitless numeric value
- Example file: [rotation_unit_mismatch.zip](https://github.com/user-attachments/files/24072880/rotation_unit_mismatch.zip)
- Error message: <Exception> Quantity::operator +(): Unit mismatch in plus operation in expression: 90 + 45 + 90 deg

Issue 2: Angle range exceeded
- Rotated angle expressions could produce values outside the accepted [-180, +180] range
- Example file: [rotation_out_of_range.zip](https://github.com/user-attachments/files/24072900/rotation_out_of_range.zip)
- Error message: <Exception> Yaw angle is out of range [-180, +180]

### Steps to reproduce

Issue 1: Unit mismatch
1. Open FreeCAD 1.0 or an earlier version.
2. Create an attachment in mmTangentPlane mode.
3. In the attachment's rotation property, set an expression using unitless numeric, e.g. 90 + 45.
4. Save the file and open the file in FreeCAD 1.1, then execute recompute.
5. Observe that a unit mismatch error occurs.

Issue 2: Angle range exceeded
1. Open FreeCAD 1.0 or an earlier version.
2. Create an attachment in mmTangentPlane mode.
3. In the attachment's rotation property, set an expression that evaluates to less than -90 degrees or greater than +90 degrees.
4. Save the file and open the file in FreeCAD 1.1, then execute recompute.
5. Observe that an out-of-range error occurs.

### Expected behavior

Issue 1: Unit mismatch
- The added rotation angle unit should be consistent with the original expression unit

Issue 2: Angle range exceeded
- Rotated angle expressions should always stay within [-180, +180]

### Actual behavior

Issue 1: Unit mismatch
- Error occurs: <Exception> Quantity::operator +/-(): Unit mismatch in plus/minus operation in expression: 

Issue 2: Angle range exceeded
- Error occurs: <Exception> Yaw angle is out of range [-180, +180]

### Development version About Info (in Safe Mode)

```shell
OS: Windows 11 build 26200
Architecture: x86_64
Version: 1.2.0dev.20251209 (Git shallow)
Build date: 2025/12/09 13:53:17
Build type: Release
Branch: grafted,grafted
Hash: 5ad6a1ba58c665c23f1d217c23e74379d8c1a5a4
Python 3.11.14, Qt 6.8.3, Coin 4.0.3, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.3.0, IfcOpenShell 0.8.2, OCC 7.8.1
Locale: Japanese/Japan (ja_JP)
Navigation Style/Orbit Style/Rotation Mode: CAD/Rounded Arcball/Window center
Stylesheet/Theme/QtStyle: FreeCAD.qss/FreeCAD Light/
Logical DPI/Physical DPI/Pixel Ratio: 96/93.1131/1.5
```

### Last known good version (optional)

```shell

```

### PR DESCRIPTION
**Pull request by marbocub**
This PR fixes Issue #26056 by adding unit handling and angle range validation in handleLegacyTangentPlaneOrientation().

## Issues
fixes #26056

### CODE REVIEW

**Comment by marbocub** [comment]
No changes to the code between commit 562d238 and commit c9c463c.
I rebased onto the latest main, but an unnecessary merge commit appeared, so I force-pushed to remove it.

File: src/Mod/Part/App/AttachExtension.cpp [hunk 1]
```diff
@@ -607,6 +607,31 @@ void AttachExtension::handleLegacyTangentPlaneOrientation()
...
+            std::string s = "(" + expr->toString() + ")";
+            if (angle >= 0) {
+                s += " + " + std::to_string(angle);
+            }
+            else {
+                s += " - " + std::to_string(-angle);
+            }
+
+            if (const App::Expression* simple = expr->eval()) {
+                if (auto ue = dynamic_cast<const App::UnitExpression*>(simple)) {
```
Comment (chennes) [inline src/Mod/Part/App/AttachExtension.cpp:625]: In cases where you're casting FreeCAD's types, use `freecad_cast` instead of `dynamic_cast`.

File: src/Mod/Part/App/AttachExtension.cpp [hunk 2]
```diff
@@ -607,6 +607,31 @@ void AttachExtension::handleLegacyTangentPlaneOrientation()
         }
 
         // convert placement and expressions according to the dominant axis
+        auto makeRotatedExpression =
+            [owner](const App::Expression* expr, double angle) -> App::Expression* {
+            if (!expr) {
+                return nullptr;
+            }
+
+            std::string s = "(" + expr->toString() + ")";
```
Comment (kadet1090) [inline src/Mod/Part/App/AttachExtension.cpp]: nitpick, but can we use longer and more descriptive variable names?

File: src/Mod/Part/App/AttachExtension.cpp (hunk 1 above)
Comment (marbocub) [reply src/Mod/Part/App/AttachExtension.cpp:625]: Thank you for the suggestion. Since both OperatorExpression and NumberExpression cannot be cast to UnitExpression using freecad_cast, I used dynamic_cast instead. Is there any mistake in this approach?

File: src/Mod/Part/App/AttachExtension.cpp (hunk 2 above)
Comment (marbocub) [reply src/Mod/Part/App/AttachExtension.cpp]: Thank you for the feedback, that makes sense. I've updated the code to use a more descriptive variable name.

**Comment by marbocub** [comment]
@chennes
I agree that `handleLegacyTangentPlaneOrientation` is getting a bit lengthy. I think this can be extended as part of the work in #24599, so I'd like to revisit refactoring at that time. Deciding how to split it naturally is not straightforward, but I’ll keep it in mind when working on that issue.

File: src/Mod/Part/App/AttachExtension.cpp (hunk 1 above)
Comment (chennes) [reply src/Mod/Part/App/AttachExtension.cpp:625]: Odd - is the type information wrong for them? They are derived from `Base::BaseClass`, so I think `freecad_cast` should work.
