### PR TITLE
[Measure] Revert one specific piece of code from PR19142

### LINKED ISSUE #22434: Std_Measure unable to calculate center of mass
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Problem description

Steps to reproduce:

- open new file
- create `Part_Box`
- select the box in the project tree
- start Std_Measure
- the center of mass should be calculated, but error shows up:

```
Unhandled Base::Exception caught in GUIApplication::notify.
The error message is: 'App::FeaturePythonT<FeatureT>' is not a document object type
```

I am able to reproduce the issue with other solids.
I am not able to reproduce with FC 1.0.1, it seems like a regression.

### Full version info

```shell
OS: Windows 10 build 19045
Architecture: x86_64
Version: 1.1.0dev.42523 (Git)
Build date: 2025/07/07 16:45:59
Build type: Release
Branch: main
Hash: d2a4f8994fba9e3e62098f1ff9a1af67e0ecf6e1
Python 3.11.13, Qt 6.8.3, Coin 4.0.3, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.2.5, IfcOpenShell 0.8.2, OCC 7.8.1
Locale: English/United States (en_US)
Navigation Style/Orbit Style/Rotation Mode: Revit/Turntable/Drag at cursor
Stylesheet/Theme/QtStyle: FreeCAD Light.qss/FreeCAD Light/
Logical DPI/Physical DPI/Pixel Ratio: 96/92.6073/1
Installed mods: 
  * Reporting
  * Telemetry 1.0.1
```

### Subproject(s) affected?

Core

### Anything else?

_No response_

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Syres916**
This PR has been created specifically at the request of @hyarion see https://github.com/FreeCAD/FreeCAD/issues/22434#issuecomment-3066718777

Fixes #22434

### CODE REVIEW

File: src/Mod/Measure/Gui/TaskMeasure.cpp [hunk 1]
```diff
@@ -223,7 +223,8 @@ Measure::MeasureBase* TaskMeasure::createObject(const App::MeasureType* measureT
         auto pyMeasureClass = measureType->pythonClass;
 
         // Create a MeasurePython instance
-        _mMeasureObject = doc->addObject<Measure::MeasurePython>(measureType->label.c_str());
+        auto featurePython = doc->addObject("Measure::MeasurePython", measureType->label.c_str());
+        _mMeasureObject = dynamic_cast<Measure::MeasureBase*>(featurePython);
```
Comment (hyarion) [inline src/Mod/Measure/Gui/TaskMeasure.cpp:228]:
```suggestion
        // Measure::MeasurePython is an alias so we need to use the string based addObject for now.
        auto featurePython = doc->addObject("Measure::MeasurePython", measureType->label.c_str());
        _mMeasureObject = dynamic_cast<Measure::MeasureBase*>(featurePython);
```
