### PR TITLE
Fix #27741: Prevent camel case splitting on numbers in Property Editor.

### LINKED ISSUE #27741: wrong display of property name in a varset
### Problem description

I have created a varset with a single property named **test3D**. In the property list of the varset it is displayed with a space **test3 D**, i.e. there is a space between the digit 3 and the letter D. The real name is correct, it is only a display problem.

### Workbench affected?

None

### Steps to reproduce

1. create a varset
2. add a property named test3D

### Expected behavior

The property name displayed should reflect the one inserted when creating the property

### Actual behavior

The property name is displayed with a space between 3 and D

### Development version About Info (in Safe Mode)

```shell
OS: Windows 10 build 19045
Architecture: x86_64
Version: 1.2.0dev.20260217 (Git shallow)
Build date: 2026/02/17 21:26:14
Build type: Release
Branch: (HEAD detached at 3bad5dabd)
Hash: 3bad5dabde38f1a901fa1475e30f5caee7f9846a
Python 3.11.14, Qt 6.8.3, Coin 4.0.3, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.3.0, IfcOpenShell 0.8.2, OCC 7.8.1
Locale: English/United Kingdom (en_GB)
Navigation Style/Orbit Style/Rotation Mode: CAD/Rounded Arcball/Window center
Stylesheet/Theme/QtStyle: FreeCAD.qss/FreeCAD Light/
Logical DPI/Physical DPI/Pixel Ratio: 96/141.951/1
Installed mods: 
  * Fasteners Workbench 0.5.44
```

### Last known good version (optional)

```shell

```

### PR DESCRIPTION
**Pull request by dhruvjamwal**
This PR fixes a display issue where property names like `test3D` are displayed with an unwanted space (`test3 D`) in the Property Editor.

I updated the string formatting loop in `PropertyItem::setPropertyName` to ensure that a space is only inserted if the previous character was explicitly a lowercase letter (`last.isLower()`), rather than triggering on any non-uppercase character like a number.

## Issues - 
Fixes #27741

## Before and After Images
*Before:* `test3D` displayed as `test3 D`
      *After:* `test3D` displayed correctly as `test3D`

### CODE REVIEW

File: src/Gui/propertyeditor/PropertyItem.cpp [hunk 1]
```diff
@@ -574,18 +574,14 @@ void PropertyItem::setPropertyName(const QString& name, const QString& realName)
     setObjectName(propName);
 
     QString display;
-    bool upper = false;
+    // Prevent camel case splitting on numbers in Property Editor
```
Comment (pieterhijma) [inline src/Gui/propertyeditor/PropertyItem.cpp]:
```suggestion
    // Camel case splitting
```

This comment has the scope of this PR in which you are trying to improve on splitting numbers. However, the code now does more than that, for example, it also prevents splitting on `_` (which is good). I suggest to make a comment that fits the scope of this specific code and that explains what the for loop tries to do.

File: tests/src/Gui/propertyeditor/PropertyItem.cpp [hunk 2]
```diff
@@ -0,0 +1,99 @@
...
+    {
+        item->setPropertyName(QLatin1String("MyView3D"));
+        QCOMPARE(item->propertyName(), QLatin1String("My View3D"));
+    }
+
+    void test_consecutiveUppercaseNotSplit()  // NOLINT
+    {
+        item->setPropertyName(QLatin1String("MyABC"));
+        QCOMPARE(item->propertyName(), QLatin1String("My ABC"));
+    }
```
Comment (pieterhijma) [inline tests/src/Gui/propertyeditor/PropertyItem.cpp:89]: Looks good, I would advise to add two more tests:

`MyABCLength` -> `My ABCLength`

This helps us to make clear that we didn't do anything smarter such as implementing logic to get `MyABCLength` -> `My ABC Length`

`Box_Length` -> `Box_Length`

This helps us to define that we now support proper "camel casing" with underscores. Before this PR, it would be `Box_ Length`

**Review by pieterhijma — CHANGES_REQUESTED** [review]
Besides adding these two test, I believe that my earlier suggestion should be applied too.
