### PR TITLE
[Gui] Fix Close without Saving button size

### LINKED ISSUE #19332: Light theme: chevron to select between multiple commands on the toolbar turns to white on white when being hovered over
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Problem description

As per the title. See demo:

https://github.com/user-attachments/assets/0708f706-ed08-47d1-b365-66d2b245c95e

### Full version info

```shell
OS: Ubuntu Core 22 (ubuntu:GNOME/ubuntu/xcb)
Architecture: x86_64
Version: 1.1.0dev.40038 (Git) Snap 1287
Build type: Release
Branch: main
Hash: 0d96954bcaa7a3de7d74d3804d52bde5292658ac
Python 3.10.12, Qt 5.15.10, Coin 4.0.0, Vtk 7.1.1, OCC 7.7.1
Stylesheet/Theme/QtStyle: FreeCAD Light.qss/FreeCAD Light/Fusion
Logical/physical DPI: 96/95.1083
Installed mods: 
  * OpenTheme 2024.9.1
  * fasteners 0.5.30
  * ezydxf
  * Assembly4 0.50.15
```

### Subproject(s) affected?

Other (specify in description)

### Anything else?

_No response_

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### LINKED ISSUE #19333: Light Theme: button text cut off when exiting without save
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Problem description

Steps to reproduce:

1. Open two documents with FreeCAD
2. Modify both, without saving them
3. Exit FreeCAD

See the text cut off in the <kbd>Close without Saving</kbd> button:

Image

With FreeCAD Classic the text is in full:

Image

### Full version info

```shell
OS: Ubuntu Core 22 (ubuntu:GNOME/ubuntu/xcb)
Architecture: x86_64
Version: 1.1.0dev.40038 (Git) Snap 1287
Build type: Release
Branch: main
Hash: 0d96954bcaa7a3de7d74d3804d52bde5292658ac
Python 3.10.12, Qt 5.15.10, Coin 4.0.0, Vtk 7.1.1, OCC 7.7.1
Stylesheet/Theme/QtStyle: FreeCAD Light.qss/FreeCAD Light/Fusion
Logical/physical DPI: 96/95.1083
Installed mods: 
  * OpenTheme 2024.9.1
  * fasteners 0.5.30
  * ezydxf
  * Assembly4 0.50.15
```

### Subproject(s) affected?

Other (specify in description)

### Anything else?

_No response_

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Syres916**
Fixes #19333 

After fix applied:

FreeCAD_Light_Fix

FreeCAD_Dark_Fix

Also fixed two typos in FreeCAD Light which also fixes #19332

### CODE REVIEW

**Comment by Syres916** [comment]
@MisterMakerNL for info

**Comment by MisterMakerNL** [comment]
Nice one!
Weird that I missed those!

File: src/Gui/MainWindow.cpp [hunk 1]
```diff
@@ -784,6 +784,7 @@ void MainWindow::closeActiveWindow ()
 
 int MainWindow::confirmSave(const char *docName, QWidget *parent, bool addCheckbox) {
     QMessageBox box(parent?parent:this);
+    box.setObjectName(QString::fromLatin1("confirmSave"));
```
Comment (xtemp09) [inline src/Gui/MainWindow.cpp:787]: In this case it is better to use `QStringLiteral`.[^1]


[^1]: https://doc.qt.io/qt-5/qlatin1string.html

Comment (Syres916) [reply src/Gui/MainWindow.cpp]: I've corrected this and the one that was merged last week with the same issue

**Review by hyarion — APPROVED** [review]
Looks good to me! 👍
