### PR TITLE
PD: hole fix cosmetic threads not working without sketches

### LINKED ISSUE #28455: PartDesign: Cosmetic threads are invisible when not using a sketch for the holes
### Problem description

The hole tool doesn’t necessarily require a sketch to create holes. Users can select circular faces or circular edges, including arcs. The texture that denotes a cosmetic threads doesn’t appear when the holes are not created using a sketch. The hole is there, with the correct size, there is no error, but there is no texture.

### Workbench affected?

Part Design

### Steps to reproduce

Open the example PD part

Select a circular face

Start hole tool and create a hole with cosmetic thread

### Expected behavior

Image

### Actual behavior

Note: the texture appears only after the feature has been created, so it is not visible when the task panel is opened. However it looks exactly the same and I captured the task panel to show you the parameters.

Image

### Development version About Info (in Safe Mode)

```shell
OS: Ubuntu 24.04.3 LTS (KDE/plasma/xcb)
Architecture: x86_64
Version: 1.2.0dev.20260318 (Git shallow) AppImage
Build date: 2026/03/18 17:37:38
Build type: Release
Branch: grafted,grafted
Hash: 12cced51f1931cb1bdb6d39fa0cb9dd8137679f7
Python 3.11.14, Qt 6.8.3, Coin 4.0.3, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.3.0, IfcOpenShell 0.8.2, OCC 7.8.1
Locale: French/France (fr_FR)
Navigation Style/Orbit Style/Rotation Mode: CAD/Rounded Arcball/Drag at cursor
Stylesheet/Theme/QtStyle: FreeCAD.qss/FreeCAD Light/
Logical DPI/Physical DPI/Pixel Ratio: 96/117.596/1
Installed mods: 
  * Cables Workbench 0.3.4
  * Fasteners Workbench 0.5.44
  * Curves workbench 0.6.71
  * Curved Shapes 1.0.14
  * SheetMetal Workbench 0.7.65
  * FusedFilamentDesign 0.25.510
  * FreeCAD-DFM-Workbench-main
```

### Last known good version (optional)

```shell
None
```

### PR DESCRIPTION
**Pull request by alfrix**
fixes #28455

### CODE REVIEW

File: src/Mod/PartDesign/Gui/ViewProviderHole.cpp [hunk 1]
```diff
@@ -333,15 +333,12 @@ std::optional<gp_Pnt> ViewProviderHole::getHoleOrigin(const PartDesign::Hole* pc
     if (!pcHole) {
         return std::nullopt;
     }
-
-    auto* sketch = freecad_cast<Part::Part2DObject*>(pcHole->Profile.getValue());
-
-    if (!sketch) {
-        return std::nullopt;
+    auto* profile = pcHole->Profile.getValue();
+    if (profile) {
```
Comment (kadet1090) [inline src/Mod/PartDesign/Gui/ViewProviderHole.cpp]:
```suggestion
    if (auto* profile = pcHole->Profile.getValue()) {
```

ensures that profile cannot be used unchecked
