### PR TITLE
Fix startup window placement to handle multiple monitors and nicer first-run

### LINKED ISSUE #14649: UX: If Main window is not Maximized, exiting FreeCAD and restarting, the Main window will not restore to the prior position
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

If you start FreeCAD, Restore Down the main Window, move it on the screen , then exit the program, upon restart the main window will not return to the position it was in when exiting occured.

It works correctly on 0.21.2

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37668 (Git)
Build type: Release
Branch: main
Hash: ea68c5e88cdc80044ede482f6ad908820f4c1c82
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Installed mods: 
  * A2plus 0.4.64a
  * freecad.gears 1.2.0
  * Manipulator 1.5.7
  * QuickMeasure 2022.10.28
```

### Subproject(s) affected?

None

### Anything else?

BeforeExitWindowsOrientation
AfterRestartWindowsShift

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by andershol**
Fixes #14649

On startup the main windows is moved so it overlaps with the available area of the primary monitor (at least 31px horizontally and 11px vertically). This makes sense for single monitor setups as it prevents the window from getting lost. But on multi monitor setups where the user has placed the window on a non-primary monitor, the window is still moved so it overlaps with the primary, which looks odd. The is changed so that if the window is inside the visible area of the monitors (with some padding to  allow the window chrome to be partly outside the monitor), it is just left there, and otherwise it is moved to be completely inside the closest monitor (easier than trying to fit it inside the possibly non-rectangular, holed area of all monitors).

The temporary fix for #25700 is also replaced. Prior to that fix the window, when no setting were available (e.g. first-run or safe-mode), would just be placed at the window managers default position and have its size reduced to fit on the size of the default monitor. After the fix, the window would then be moved to the upper left corner. This is changed so the window is centered on the primary monitor with a size of 1800x1000 (the default size seemed to small on a 2k monitor and maximizing the window seem to large on a 4k monitor) bounded to the size of the available on that monitor.

This change is only tested on Windows.

### CODE REVIEW

File: src/Gui/MainWindow.cpp [hunk 1]
```diff
@@ -1995,56 +1965,75 @@ void MainWindow::loadWindowSettings()
...
+        winGeometry = QRect(winPos, winSize + frameSizeDiff);
+        winPos.setX(qMax(qMin(winPos.x(), screen.right() - winGeometry.width()), screen.x()));
+        winPos.setY(qMax(qMin(winPos.y(), screen.bottom() - winGeometry.height()), screen.y()));
     }
-#endif
+
+    // Scale before move reducing, or vice versa, so a dpi change wont make window to be moved
+    resize(winSize.boundedTo(size()));
+    move(winPos);
+    resize(winSize);
```
Comment (chennes) [inline src/Gui/MainWindow.cpp:2036]: Can you explain this block to me? I'm having trouble understanding what's going on here.

Comment (andershol) [reply src/Gui/MainWindow.cpp:2036]: It wouldn't be uncommon to have multiple monitors with different resolution and screen scaling. E.g. a laptop with an external monitor, where the laptop screen might have high resolution, but low physical size, so the screen scaling might be 200% and the big external screen might have 100% scaling. And either might be the primary screen.

So if we need to move a window from the external monitor (because that is where the os placed the app by default) to the laptop screen (because that is where the prefs say the user had placed it), the window, that might be very large, is doubled in size (because of the screen scaling difference) and might not fit on the destination screen. And if the center of the window is outside the screen and is actually on another screen with different scaling the window might be reduced in size again (not sure what the origin of that scaling would be, so I guess the window could move). So in that case you want to scale before you move. But we might just as well be in the situation where we are moving the window the other way to a screen with more room, so we want to move before we scale.

So I considered something like `if (newSize < currentSize) { scale; move; } else { move; scale; }`, but it seems width and height should be handled independently. So doing `scale(min(newSize, currentSize)); move; scale(newSize)` was a simple way of doing the if-statement but handle width and height independently and in most cases one of the scale-calls should be a no-op. You could use `setGeometry` (if you handle the size of the frame), but it seems it will also send a move and a resize event. And it might just be me being paranoid, so didn't want to spend to many lines of code on it.

(a the comment should be fixed s/wont make/won't cause/ )

**Comment by freecad-ci-runner** [comment]
Successfully created backport PR for `releases/FreeCAD-1-1`:
- #29203
