### PR TITLE
[Spreadsheet] Replace override cursor with QGraphicsItem::setCursor

### LINKED ISSUE #22081: In the latest release, the cursor appearance is broken
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Problem description

When entering the Spreadsheet workbench, the cursor spontaneously changed its appearance and remained that way, even when changing the workbench (and even when editing the text)

Image

### Full version info

```shell
OS: Windows 10 build 19044
Architecture: x86_64
Version: 1.1.0dev.42180 (Git)
Build date: 2025/06/16 16:25:59
Build type: Release
Branch: main
Hash: fca41e4003f1680cf604b593a046ac2b1db6ba8a
Python 3.11.13, Qt 6.8.3, Coin 4.0.3, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.2.5, IfcOpenShell 0.8.2, OCC 7.8.1
Locale: Russian/Russia (ru_RU)
Navigation Style/Orbit Style/Rotation Mode: Blender/Rounded Arcball/Object center
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Dark/
Logical DPI/Physical DPI/Pixel Ratio: 96/102.299/1
```

### Subproject(s) affected?

None

### Anything else?

_No response_

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by xtemp09**
This method seems to be working. Closes #22081.

Tested on _KUbuntu 24.04.1 LTS (KDE/plasma/xcb)_, _Qt 5.15.13_.

### CODE REVIEW

File: src/Mod/Spreadsheet/Gui/ZoomableView.cpp [hunk 1]
```diff
@@ -122,6 +122,23 @@ ZoomableView::ZoomableView(Ui::Sheet* ui)
     });
 
     resetZoom();
+
+    auto hor_h = qobject_cast<SpreadsheetGui::SheetViewHeader*>(stv->horizontalHeader()),
+         ver_h = qobject_cast<SpreadsheetGui::SheetViewHeader*>(stv->verticalHeader());
```
Comment (kadet1090) [inline src/Mod/Spreadsheet/Gui/ZoomableView.cpp]: camelCase :)

File: src/Mod/Spreadsheet/Gui/ZoomableView.cpp [hunk 2]
```diff
@@ -122,6 +122,23 @@ ZoomableView::ZoomableView(Ui::Sheet* ui)
...
+                     [this](const QCursor newerCursor) {
+                         qpw->setCursor(newerCursor);
+                     });
+
+    QObject::connect(ver_h,
+                     &SpreadsheetGui::SheetViewHeader::cursorChanged,
+                     this,
+                     [this](const QCursor newerCursor) {
+                         qpw->setCursor(newerCursor);
+                     });
```
Comment (kadet1090) [inline src/Mod/Spreadsheet/Gui/ZoomableView.cpp]: that lambda could be extracted into variable and reaused

**Review by kadet1090 — APPROVED** [review]

File: src/Mod/Spreadsheet/Gui/ZoomableView.cpp (hunk 1 above)
Comment (xtemp09) [reply src/Mod/Spreadsheet/Gui/ZoomableView.cpp]: I simply followed the existing naming convention. In this file the underscore convention is used.

File: src/Mod/Spreadsheet/Gui/ZoomableView.cpp (hunk 2 above)
Comment (xtemp09) [reply src/Mod/Spreadsheet/Gui/ZoomableView.cpp]: I agree with this. But, if you take a look at this function, you'll notice a pattern of doubling lines. Both the horizontal and vertical scrollbars require the same connections and need to be handled in the same way.


Using a lambda in this situation keeps the exact same number of lines.

Comment (kadet1090) [reply src/Mod/Spreadsheet/Gui/ZoomableView.cpp]: Ah, I think that we did not understand each other - your solution is of course perfectly fine too. 

I thought about something like that:
```
const auto setCursorQpw = [this](const QCursor newerCursor) {
   qpw->setCursor(newerCursor);
};
                     
connect(horizontal, ..., setCursorQpw);
connect(vertical, ..., setCursorQpw);
```
