### PR TITLE
Fix SpaceBall button assignment and command dispatch

### LINKED ISSUE #10073: [Problem] 0.21 Stable switching camera view modes no longer works with Spaceball buttons
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.21 (Development)

### Full version info

```shell
[code]
OS: Ubuntu 22.04.2 LTS (MATE/mate)
Word size of FreeCAD: 64-bit
Version: 0.21.0.33675 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 0.21.0)
Hash: 41b058e2087de60dc8fef3d3e68c7d0129e13abf
Python 3.10.12, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.5, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * fasteners 0.4.59
  * 3D_Printing_Tools
  * A2plus 0.4.60n
  * Curves 0.6.13
  * freecad.gears 1.0.0
[/code]
```

### Subproject(s) affected?

None

### Problem description

Spaceball buttons can no longer switch the camera view modes in 0.21 (works in 0.20 and 0.19).
Other actions I've tested do seem to work properly (after reassignment, as all were lost during the upgrade).
(Note: I selected 0.21 Development as there is no option for 0.21 Stable in the Issue form)

I dug into the sources (disclaimer: I'm not a dev) and it appears that two functions (ViewPerspectiveCmd & ViewOrthographicCmd) were deleted from src/Gui/NaviCube.cpp from 0.20 to 0.21.
https://github.com/FreeCAD/FreeCAD/blob/fcad80494f8937a98be6b2d8fc45c54c930b7817/src/Gui/NaviCube.cpp#L1714
https://github.com/FreeCAD/FreeCAD/blob/fcad80494f8937a98be6b2d8fc45c54c930b7817/src/Gui/NaviCube.cpp#L1734
I couldn't find these in the 0.21 sources.

I'm only opening one report as I'm guessing the other problem is a side-effect of this removal: Spaceball button configs are cleared when going from 0.20 to 0.21 (repeatable). If this is not the case, I can open another issue (if needed).

Details:
I noticed that the Spaceball button configuration didn't carry over from 0.20 (I just upgraded to 0.21 today using the AppImage), so I proceeded to redefine the buttons. I found that while the buttons get programmed and issue commands, the two commands issued to change view modes to Perspective or Orthographic do not work.
I experimented in the Python Console and found that when I change the passed numeric parameter from a 0 to a 1 (and removed the hash), it changes modes properly.
Example of output when tapping the two buttons:
```
>>> # Gui.runCommand('Std_OrthographicCamera',0)
>>> # Gui.runCommand('Std_PerspectiveCamera',0)
```
If I manually enter either of the following, it does properly switch the view mode:
```
>>> Gui.runCommand('Std_PerspectiveCamera',1)
>>> Gui.runCommand('Std_OrthographicCamera',1)
```
I don't pretend to know what the numeric parameter is (help(Gui.runCommand) just shows it's the "index of the child command", not sure what that means), it's just the first thing I tried on a hunch.

After recovering my previous user.cfg and restarting 0.20, I captured a different set of commands in the Python Console (the view switching was working properly here):
```
>>> ### Begin command ViewPerspectiveCmd
>>> Gui.activeDocument().activeView().setCameraType("Perspective")
>>> ### End command ViewPerspectiveCmd
>>> Gui.runCommand('Std_OrthographicCamera',0)
>>> Gui.runCommand('Std_PerspectiveCamera',1)
>>> ### Begin command ViewOrthographicCmd
>>> Gui.activeDocument().activeView().setCameraType("Orthographic")
>>> ### End command ViewOrthographicCmd
>>> Gui.runCommand('Std_OrthographicCamera',1)
>>> Gui.runCommand('Std_PerspectiveCamera',0)
```

Upon switching back to 0.21, my config was again wiped (this is repeatable).
It appears the commands ViewOrthographicCmd & ViewPerspectiveCmd no longer exist, so are replaced with something that only does half of the intended actions when the Spaceball buttons are redefined in via the GUI.
```
>>> ViewOrthographicCmd
Traceback (most recent call last):
  File "<input>", line 1, in <module>
NameError: name 'ViewOrthographicCmd' is not defined
>>> ViewPerspectiveCmd
Traceback (most recent call last):
  File "<input>", line 1, in <module>
NameError: name 'ViewPerspectiveCmd' is not defined
```
Note that the long commands actually still work when entered into the console:
```
>>> Gui.activeDocument().activeView().setCameraType("Perspective")
>>> Gui.activeDocument().activeView().setCameraType("Orthographic")
```

I tried manually changing user.cfg as follows, but it did not work.
```
          <FCParamGroup Name="9">
            <FCText Name="Command">Gui.activeDocument().activeView().setCameraType("Perspective")</FCText>
            <FCText Name="Description"/>
          </FCParamGroup>
...
          <FCParamGroup Name="11">
            <FCText Name="Command">Gui.activeDocument().activeView().setCameraType("Orthographic")</FCText>
            <FCText Name="Description"/>
          </FCParamGroup>
```

Thank you very much for your time and attention, and for such an amazing piece of software. :)

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #17812: Navigation: Spaceball button configuration does not match dialog state after physical button press
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Steps to reproduce (requires spacenavd-compatible hardware):

1. Start FreeCAD and create a new document.
2. Right-click toolbar and select `Customize`
3. Open `Spaceball buttons` tab.
4. Click a physical button (other than Button 1) on the controller. This automatically selects the button in the list and correctly shows the currently assigned function. However `Button 1` also stays weirdly half-hilighted:

image

5. Switch the assigned function by clicking a new selection in the right side list
6. Close and reopen the dialog
7. Observe that the new function has been assigned to Button 1, while Button 3 function has not changed.

If you select the button in the left list using mouse instead of physical button, the configuration works correctly.

### Full version info

```shell
FreeCAD_weekly-builds-39175-conda-Linux-x86_64-py311.AppImage (also occurs with 1.0RC2)

OS: Ubuntu 22.04.5 LTS (ICEWM/icewm-session/xcb)
Architecture: x86_64
Version: 1.1.0dev.39175 (Git) Conda AppImage
Build type: Release
Branch: main
Hash: 46831f4c86a1679d48f63273b92cd755522e42f9
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
Installed mods: 
  * dxf_library
  * ThreadProfile 1.84.0
  * Assembly4 0.50.2
```

### Subproject(s) affected?

None

### Anything else?

Related part of code: [DlgCustomizeSpaceball::event](https://github.com/FreeCAD/FreeCAD/blob/45d3864942c6928cec7dc18f95b1f222485756e5/src/Gui/DlgCustomizeSpaceball.cpp#L807). I'm not sure why this occurs though and what this half-selected list state is about.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Maik-0000FF**
## Summary

Two bugs in the SpaceBall button system that affect all platforms and drivers:

1. **Button assignment goes to wrong button** — pressing a SpaceMouse button in the Spaceball Buttons dialog highlights the correct button visually, but assigning a command applies it to the previously selected button instead.

2. **Checkable commands do nothing via SpaceBall button** — commands like `Std_OrthographicCamera` and `Std_PerspectiveCamera` silently fail when triggered from a SpaceBall button, while working fine from the toolbar or keyboard shortcut.

### Commit 1: Fix button assignment (#17812)

**DlgCustomizeSpaceball.cpp** — `ButtonView::selectButton()` called `selectionModel()->select()` to update the visual highlight, but did not call `setCurrentIndex()`. When `goChangedCommand()` later read `currentIndex()` to determine which button row to assign the command to, it still pointed to the previous button.

Fix: store the `QModelIndex` once and call `setCurrentIndex(idx)` in addition to `select()`.

### Commit 2: Fix command dispatch (#10073)

**MainWindow.cpp** / **NavlibCmds.cpp** — The SpaceBall button handlers dispatched commands via `runCommandByName()` which calls `invoke(0)`. Checkable actions like `Std_OrthographicCamera` guard their execution with `if (iMsg == 1)` to prevent feedback loops from `isActive()` → `setChecked()` → `activated()`. Since `invoke(0)` never satisfies this guard, these commands silently did nothing.

Fix: use `invoke(1)` directly in the spnav and navlib SpaceBall button handlers instead of changing `runCommandByName()` globally, to avoid affecting its ~60 other call sites where `invoke(0)` is correct.

## Testing

Tested on Arch Linux (KDE Plasma Wayland) with SpaceNavigator (046d:c626) via spacenavd:

**Button assignment (#17812):**
- Open Tools → Customize → Spaceball Buttons
- Press SpaceMouse button 1 → assign "Fit All"
- Press SpaceMouse button 2 → assign "View Top"
- Verified: Button 1 shows "Fit All", Button 2 shows "View Top" (before fix: both on button 1)

**Command dispatch (#10073):**
- Assign `Std_OrthographicCamera` to button 1, `Std_PerspectiveCamera` to button 2
- Press buttons → camera switches correctly between orthographic and perspective
- Before fix: both buttons did nothing

**Regression:**
- Toolbar buttons for Orthographic/Perspective still work
- Keyboard shortcuts V,O and V,P still work
- ViewCube perspective toggle still works
- Other SpaceBall button assignments (Fit All, View Top, etc.) unaffected

## Fixes

Fixes #17812 (SpaceBall button assignment to wrong button)
Fixes #10073 (SpaceBall button does nothing for camera commands)

### CODE REVIEW

File: src/Gui/Command.cpp [hunk 1]
```diff
@@ -2139,7 +2139,7 @@ void CommandManager::runCommandByName(const char* sName) const
     Command* pCmd = getCommandByName(sName);
 
     if (pCmd) {
-        pCmd->invoke(0);
+        pCmd->invoke(1);
```
Comment (hyarion) [inline src/Gui/Command.cpp]: This fix is correct for the SpaceBall use-case, but changing `runCommandByName` globally feels a bit risky. It has ~60 call sites across the codebase, and some commands use `iMsg` as an action index rather than a boolean check/uncheck flag.
For example, `StdCmdFreezeViews::activated()` uses `iMsg` for saving/restoring/creating/clearing views.
If someone were to assign `Std_FreezeViews` to a SpaceBall button, it would now silently trigger "restore views" instead of "save views", it is an edge case and neither is the right default but the behavior change is a bit surprising.

Could this be scoped to just the SpaceBall handler instead? In `MainWindow.cpp` around line 1153, you could replace:
```cpp
Application::Instance->commandManager().runCommandByName(commandName.c_str());
```
with:
```cpp
Command* cmd = Application::Instance->commandManager().getCommandByName(commandName.c_str());
if (cmd) {
    cmd->invoke(1);
}
```

That way the fix targets exactly the code path that needs it, without changing semantics for the other ~60 callers (toolbar dispatchers, Start page actions, constraint selectors, etc.) which all work correctly with `invoke(0)` today.

The navlib SpaceBall handler at `NavlibCmds.cpp:171` also calls `runCommandByName` and would benefit from the same targeted fix.

I'd like to hear what you think.

Comment (Maik-0000FF) [reply src/Gui/Command.cpp]: You're absolutely right, changing `runCommandByName()` globally is too broad. Scoping the fix to just the SpaceBall handlers is the cleaner approach.

I've updated the commit to use `invoke(1)` directly in `MainWindow.cpp` (spnav handler) and `NavlibCmds.cpp` (navlib handler), leaving `runCommandByName()` unchanged.

Thanks for the review!
