### PR TITLE
Gui: fixes #12891: Random color not working for App::Part

### LINKED ISSUE #12891: App::Part: Random color not working
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Assigning a random color to App::Part containers does not work:
grafik

Ideally, all sub objects should get a random color.

### Full version info

```shell
OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.35758 (Git)
Build type: Release
Branch: sketcher-offset-external-geometry
Hash: 7e8265fb10269566c01bf11d8b1600a5dd81aaa2
Python 3.11.7, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.6, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * 3DfindIT 1.2.0
  * BIM 2021.12.0
  * CfdOF 1.25.2
  * CurvedShapes 1.0.5
  * Curves 0.6.24
  * Defeaturing 1.2.2
  * fasteners 0.5.13
  * FEMbyGEN 2.1.0
  * freecad.gears 1.2.0
  * freecad_metal_workbench 0.0.1
  * OpenDark 2023.12.17
  * sheetmetal 0.4.2
```

### Subproject(s) affected?

None

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by wwmayer**

### CODE REVIEW

File: src/Gui/CommandFeat.cpp [hunk 1]
```diff
@@ -86,29 +87,46 @@ void StdCmdRandomColor::activated(int iMsg)
...
+    std::vector<SelectionSingleton::SelObj> sel = Selection().getCompleteSelection();
+
+    Command::openCommand(QT_TRANSLATE_NOOP("Command", "Set Random Color"));
+    for (const auto & it : sel) {
+        ViewProvider* view = Application::Instance->getViewProvider(it.pObject);
+        setRandomColor(view);
+
+        Base::Type grpType = App::GroupExtension::getExtensionClassTypeId();
+        if (it.pObject->hasExtension(grpType)) {
+            auto *grp = static_cast<App::GroupExtension*>(it.pObject->getExtension(grpType));
```
Comment (PaddleStroke) [inline src/Gui/CommandFeat.cpp:124]: FIY there's a lint warning here:

> do not use static_cast to downcast from a base to a derived class; use dynamic_cast instead [cppcoreguidelines-pro-type-static-cast-downcast]

Comment (wwmayer) [reply src/Gui/CommandFeat.cpp:124]: This kind of linter warnings are annoying because in this context they are wrong. With the check that the object has an extension of type `GroupExtension` it's safe to downcast it with static_cast.

The recommended way by the cppcoreguidelines is to use dynamic_cast instead but then I do two type checks for the one and same thing. Furthermore, I have to also check the output of dynamic_cast as otherwise other code checkers will complain about that. All this makes the code to look unnecessarily complicated, then.

The only alternative I see ATM is to write (but not tested yet)
`if (auto grp = dynamic_cast<App::GroupExtension*>(it.pObject->getExtension(grpType, true, true)))`

But here we the problem of the so called _boolean blindness_ as for a code reviewer it's not obvious what the two true means. The reviewer has to check the API of `getExtension` to get an idea.

I think we need a template method of `getExtension` that allows to write elegant code. I will check this option.

Comment (wwmayer) [reply src/Gui/CommandFeat.cpp]: With 80d6d12ad1a I have added that template method. Now it can be used this way:
`if (auto grp = it.pObject->getExtension<App::GroupExtension>())`
