### PR TITLE
Gui: Improve object center rotation mode

### LINKED ISSUE #9911: [Problem] Axis cross affects the object center rotation mode
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.21 (Development)

### Full version info

```shell
[code]
OS: KDE neon 5.27 (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.21.0.33442 +3 (Git)
Build type: Release
Branch: rotationcenter
Hash: 1ae6a68ee0842d4e35b609556d5105bed3a6125f
Python 3.11.3, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.5, OCC 7.7.1
Locale: English/United States (en_US)
[/code]


The about page did not give me the right branch name and +n in version
```

### Subproject(s) affected?

None

### Problem description

Axis cross affects the "object center" rotation mode. Steps to reproduce (needs #9909 for visualization):
1. Ensure the axis cross is disabled.
2. Make a simple cube.
3. Set rotation mode to "Object center".
4. Start dragging. With the axis cross disabled, the center should be at the center of the object. This is expected.
5. Enable the axis cross.
6. Start dragging again. Now the rotation center is not shown at the center of the object but depending on the zoom level more towards the center of the axis cross. I would expect that the axis cross does not have an effect on the object center but apparently it does.

https://github.com/FreeCAD/FreeCAD/assets/14298143/8bad2e17-f622-487f-9f72-954dded24b01

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Rexbas**
- [x]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR
---
This is my attempt to fix #9911. I created a group in `pcViewProviderRoot` called `objectGroup` which contains basically everything that is allowed to affect the rotation center. Things that should not affect the rotation center are directly added as a child of `pcViewProviderRoot`. The axis cross is directly added to `pcViewProviderRoot` and should no longer affect the rotation center. I also excluded the measure distance tool from `objectGroup` because I think it could affect the rotation center too much in some cases.

I am not sure if this is the best way to fix the object center rotation mode but I think it is a step in the right direction. If there is a better way to fix this or if there are more things that should be excluded from the `objectGroup` please let me know.

This PR does not depend on #9909 but I recommend it for testing.

### CODE REVIEW

**Comment by 0penBrain** [comment]
> I am not sure if this is the best way to fix the object center rotation mode

The main problem is lack of genericity.
The good way IMO would be to mimic `canAddToSceneGraph`. Add another virtual function (something like `virtual bool excludeFromPhysicalObject() const { return false; }` to `ViewProvider.h` so then any VP that needs to be excluded can override this function to return `true`.

Then keep the separate SoGroup as you did but decide if VP goes in or out based on the `excludeFromPhysicalObject` return.

**Comment by Rexbas** [comment]
Sounds like a good idea. I will try to make that work.

File: src/Gui/View3DInventorViewer.cpp [hunk 1]
```diff
@@ -115,6 +115,7 @@
 #include "ViewProvider.h"
 #include "ViewProviderDocumentObject.h"
 #include "ViewProviderLink.h"
+#include "ViewProviderMeasureDistance.h"
```
Comment (0penBrain) [inline src/Gui/View3DInventorViewer.cpp:118]: This shouldn't be needed anymore.

File: src/Gui/ViewProvider.h [hunk 2]
```diff
@@ -142,6 +142,8 @@ class GuiExport ViewProvider : public App::TransactionalObject
     virtual SoSeparator* getBackRoot() const;
     ///Indicate whether to be added to scene graph or not
     virtual bool canAddToSceneGraph() const {return true;}
+    // Indicate whether to be added to scene graph root or object group root
```
Comment (0penBrain) [inline src/Gui/ViewProvider.h:145]: The comment isn't very clear. Especially because we expect toe find the `true` value first then the `false` one.
```suggestion
    // Indicate whether to be added object group (true) or only to scene graph (false)
```

File: src/Gui/View3DInventorViewer.h [hunk 3]
```diff
@@ -484,6 +484,7 @@ class GuiExport View3DInventorViewer : public Quarter::SoQTQuarterAdaptor, publi
     SoDirectionalLight* backlight;
 
     SoSeparator * pcViewProviderRoot;
+    SoGroup* objectGroup;
```
Comment (0penBrain) [inline src/Gui/View3DInventorViewer.h:487]: Adding a short comment to each line to get the purpose of each would be good.

**Review by 0penBrain — COMMENTED** [review]
LGTM except some remarks.

Just read the code, I didn't compile an test though.

**Comment by Rexbas** [comment]
Thanks for the feedback. I applied your suggestions and added more comments. :)

**Comment by 0penBrain** [comment]
Welcome. I won't go further now as I think we gonna wait after 0.21 release to merge (except if one decides otherwise).
When it's time to merge, I can give it a try if needed.

**Comment by yorikvanhavre** [comment]
Anything left here or is it good for merging?

**Comment by Rexbas** [comment]
I think it is good, unless @0penBrain wants to test it first.

**Comment by 0penBrain** [comment]
Didn't re-check but nothing wrong from my side

**Comment by luzpaz** [comment]
@yorikvanhavre :point_up_2:

**Comment by luzpaz** [comment]
@yorikvanhavre is AFK perhaps @chennes can merge?   
@Rexbas can you rebase ?

**Comment by chennes** [comment]
Sure, sounds like everyone is happy about it.

**Comment by adrianinsaval** [comment]
should we backport this?

**Comment by Rexbas** [comment]
I think backporting this would be a good idea.
