### PR TITLE
[TD]Headless view creation (fix #20024)

### LINKED ISSUE #20024: TechDraw: SIGSEGV on `TechDraw.viewPartAsSvg()` (triggered from CLI)
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Problem description

When I call TechDraw.viewPartAsSvg from FreeCADcmd i get a sementation fault.
Using the same model and code in the console within the GUI works fine.

Here is an example of it working fine in the GUI:

Image

But when I run the same code in console mode:
```bash
/opt/FreeCAD/usr/bin/freecad -c
[FreeCAD Console mode <Use Ctrl-D (i.e. EOF) to exit.>]
>>> FreeCAD.open("mechanical/simple.FCStd")
Importing project files......
Postprocessing......                            (100 %)
<Document object at 0x5640b13b5fa0>
>>> import TechDraw                             (100 %)
>>> TechDraw.viewPartAsSvg(FreeCAD.activeDocument().getObjectsByLabel("shell_view")[0])
Program received signal SIGSEGV, Segmentation fault.
#0  /lib/x86_64-linux-gnu/libc.so.6(+0x3c050) [0x7f6800e77050]
#1  /opt/FreeCAD/usr/lib/TechDraw.so(+0x12f6ec) [0x7f67f5cfe6ec]
#2  /opt/FreeCAD/usr/lib/TechDraw.so(+0x12fdc9) [0x7f67f5cfedc9]
#3  /opt/FreeCAD/usr/lib/TechDraw.so(+0x14c7c0) [0x7f67f5d1b7c0]
#4  /opt/FreeCAD/usr/bin/../lib/libFreeCADBase.so(method_varargs_call_handler+0x187) [0x7f68025fe317]
#5  /opt/FreeCAD/usr/bin/../lib/libpython3.11.so.1.0(+0x206068) [0x7f680301c068]
#6  /opt/FreeCAD/usr/bin/../lib/libpython3.11.so.1.0(_PyObject_MakeTpCall+0x26c) [0x7f6802ffbb5c]
#7  /opt/FreeCAD/usr/bin/../lib/libpython3.11.so.1.0(_PyEval_EvalFrameDefault+0x6f2) [0x7f6803007532]
#8  /opt/FreeCAD/usr/bin/../lib/libpython3.11.so.1.0(+0x2abd1d) [0x7f68030c1d1d]
#9  /opt/FreeCAD/usr/bin/../lib/libpython3.11.so.1.0(PyEval_EvalCode+0xa4) [0x7f68030c1794]
#10  /opt/FreeCAD/usr/bin/../lib/libpython3.11.so.1.0(+0x2cabf3) [0x7f68030e0bf3]
#11  /opt/FreeCAD/usr/bin/../lib/libpython3.11.so.1.0(+0x2c669a) [0x7f68030dc69a]
#12  /opt/FreeCAD/usr/bin/../lib/libpython3.11.so.1.0(+0x1c39fc) [0x7f6802fd99fc]
#13  /opt/FreeCAD/usr/bin/../lib/libpython3.11.so.1.0(_PyRun_InteractiveLoopObject+0xe7) [0x7f6802fd9ba3]
#14  /opt/FreeCAD/usr/bin/../lib/libpython3.11.so.1.0(PyRun_InteractiveLoopFlags+0x37) [0x7f6802fd9c59]
#15  0x7f680265553a in Base::InterpreterSingleton::runCommandLine(char const*) from /opt/FreeCAD/usr/bin/../lib/libFreeCADBase.so+0x1a
#16  /opt/FreeCAD/usr/bin/freecad(+0x786f) [0x56409ccf386f]
#17  /lib/x86_64-linux-gnu/libc.so.6(+0x2724a) [0x7f6800e6224a]
#18  /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x85) [0x7f6800e62305]
#19  /opt/FreeCAD/usr/bin/freecad(+0x7c2a) [0x56409ccf3c2a]
```

Any ideas?

Regards,
Toon

### Full version info

```shell
OS: Debian GNU/Linux 12 (bookworm) (xcb)
Architecture: x86_64
Version: 1.0.0.39109 (Git) Conda
Build type: Release
Branch: (HEAD detached at 1.0.0)
Hash: 2fcc5317fe3aee96ca73475986a577719fc78e20
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: C/Default (C)
Stylesheet/Theme/QtStyle: unset/unset/Qt default
```

### Subproject(s) affected?

None

### Anything else?

_No response_

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by WandererFan**
This PR implements a fix for issue #20024.  

In headless mode, the program will not receive a notification that the separate threads for long running OCCT methods, and processing will not continue after the completion of the thread.

This PR implements a check for the availability of the Gui (and its event loop) and does not start separate threads if the Gui is not available, but runs those methods in the main thread.

### CODE REVIEW

File: src/Mod/TechDraw/App/DrawUtil.cpp [hunk 1]
```diff
@@ -1887,6 +1887,14 @@ std::string DrawUtil::cleanFilespecBackslash(const std::string& filespec)
     return noBackslash;
 }
 
+//! returns true if the Gui module and its event loop are active.
+bool DrawUtil::isGuiUp()
+{
+    std::string pyCommand{"import FreeCAD\nguiState = FreeCAD.GuiUp"};
+    std::string result{Base::Interpreter().runStringWithKey(pyCommand.c_str(), "guiState", "None")};
+    return  (result == "1");
+}
```
Comment (hyarion) [inline src/Mod/TechDraw/App/DrawUtil.cpp:1896]: MergeDocument has a [c++ implementation](https://github.com/FreeCAD/FreeCAD/blob/main/src/App/MergeDocuments.cpp#L91-L94) of this, here it would look like:
```suggestion
bool DrawUtil::isGuiUp()
{
    auto* app = QCoreApplication::instance();
    return app && app->inherits("QApplication");
}
```
Maybe it fits your needs better than to go through the interpreter and back?

File: src/Mod/TechDraw/App/DrawViewSection.cpp [hunk 2]
```diff
@@ -459,6 +457,14 @@ void DrawViewSection::sectionExec(TopoDS_Shape& baseShape)
 
     m_cuttingTool = makeCuttingTool(m_shapeSize);
 
+    if (!DU::isGuiUp()) {
```
Comment (benj5378) [inline src/Mod/TechDraw/App/DrawViewSection.cpp:460]: I guess it fixes the issue, though the real issue is the DrawViewSection in the first place assumes/depends/expects that there is a GUI.

File: src/Mod/TechDraw/App/AppTechDrawPy.cpp [hunk 3]
```diff
@@ -43,6 +43,9 @@
 #include <Base/PyWrapParseTupleAndKeywords.h>
 #include <Base/Vector3D.h>
 #include <Base/VectorPy.h>
+
+#include <Gui/Application.h>
```
Comment (jbaehr) [inline src/Mod/TechDraw/App/AppTechDrawPy.cpp:47]: Including GUI in App looks strange

File: src/Mod/TechDraw/App/DrawViewSection.cpp (hunk 2 above)
Comment (WandererFan) [reply src/Mod/TechDraw/App/DrawViewSection.cpp:460]: All the DVP derived views that run OCCT operations in separate threads need the notification that the thread has ended, and that only arrives if the Gui's event loop is available.

File: src/Mod/TechDraw/App/AppTechDrawPy.cpp (hunk 3 above)
Comment (WandererFan) [reply src/Mod/TechDraw/App/AppTechDrawPy.cpp:47]: Yes,  it does.  Using the QApplication based test suggested by @hyarion would avoid that.
