### PR TITLE
part design: fix issue #25639 use c++ exception to prevent crash

### LINKED ISSUE #25639: Segfault on activating fillet tool
### Workbench affected?

None

### Problem description

Image

[workshop lamp pcb holder.FCStd.zip](https://github.com/user-attachments/files/23733808/workshop.lamp.pcb.holder.FCStd.zip)

### Steps to reproduce

1. Select Body.Pocket.Face7
2. Click Fillet tool. Segfault.

### Expected behavior

-

### Actual behavior

```
#0  0x00007fffa4aed027 in Geom2dAdaptor_Curve::D0(double, gp_Pnt2d&) const () from /usr/lib/libTKG2d.so.7.9
#1  0x00007fffa67934d5 in ChFi3d_FilBuilder::PerformTwoCorner(int) () from /usr/lib/libTKFillet.so.7.9
#2  0x00007fffa66dc6f5 in ChFi3d_Builder::PerformFilletOnVertex(int) () from /usr/lib/libTKFillet.so.7.9
#3  0x00007fffa66e143a in ChFi3d_Builder::Compute() () from /usr/lib/libTKFillet.so.7.9
#4  0x00007fffa685768b in BRepFilletAPI_MakeFillet::Build(Message_ProgressRange const&) () from /usr/lib/libTKFillet.so.7.9
#5  0x00007fffa45c526d in BRepBuilderAPI_MakeShape::Shape() () from /usr/lib/libTKTopAlgo.so.7.9
#6  0x00007fffa71b179c in Part::TopoShape::makeElementShape (this=this@entry=0x7fffffff99b0, mkShape=..., shapes=std::vector of length 1, capacity 1 = {...}, op=op@entry=0x7fffa724f94b "FLT")
    at /home/morgan/programs/code-freecad/src/Mod/Part/App/TopoShapeExpansion.cpp:4327
#7  0x00007fffa71b191d in Part::TopoShape::makeElementShape (this=this@entry=0x7fffffff99b0, mkShape=..., source=..., op=op@entry=0x7fffa724f94b "FLT") at /home/morgan/programs/code-freecad/src/Mod/Part/App/TopoShapeExpansion.cpp:4312
#8  0x00007fffa71b2f3d in Part::TopoShape::makeElementFillet (this=this@entry=0x7fffffff99b0, shape=..., edges=std::vector of length 8, capacity 8 = {...}, radius1=1, radius2=radius2@entry=1, op=0x7fffa724f94b "FLT", op@entry=0x0)
    at /home/morgan/programs/code-freecad/src/Mod/Part/App/TopoShapeExpansion.cpp:4107
#9  0x00007fff9f3b3123 in PartDesign::Fillet::execute (this=0x5555564e3f00) at /home/morgan/programs/code-freecad/src/Mod/PartDesign/App/FeatureFillet.cpp:108
#10 0x00007ffff4389ec2 in App::DocumentObject::recompute (this=0x5555564e3f00) at /home/morgan/programs/code-freecad/src/App/DocumentObject.cpp:165
#11 0x00007fffa6f23bee in Part::Feature::recompute (this=<optimized out>) at /home/morgan/programs/code-freecad/src/Mod/Part/App/PartFeature.cpp:107
#12 0x00007ffff433194c in App::Document::_recomputeFeature (this=this@entry=0x55555f09ab80, Feat=Feat@entry=0x5555564e3f00) at /home/morgan/programs/code-freecad/src/App/Document.cpp:3003
#13 0x00007ffff4337a16 in App::Document::recompute (this=this@entry=0x55555f09ab80, objs=std::vector of length 0, capacity 0, force=<optimized out>, hasError=hasError@entry=0x0, options=options@entry=0)
    at /home/morgan/programs/code-freecad/src/App/Document.cpp:2713
#14 0x00007ffff43fc253 in App::DocumentPy::recompute (this=this@entry=0x55555b49faf0, args=<optimized out>) at /home/morgan/programs/code-freecad/src/App/DocumentPyImp.cpp:723
#15 0x00007ffff43fc374 in App::DocumentPy::staticCallback_recompute (self=0x55555b49faf8, args=<optimized out>) at /home/morgan/programs/code-freecad/build/src/App/DocumentPy.cpp:2021
#16 0x00007ffff2b96213 in cfunction_call (func=0x7fffa77b09f0, args=0x7ffff2f03548 <_PyRuntime+88296>, kwargs=0x0) at Objects/methodobject.c:550
#17 0x00007ffff2b620cb in _PyObject_MakeTpCall (tstate=0x7ffff2f32df0 <_PyRuntime+283024>, callable=0x7fffa77b09f0, args=0x7ffff7f87078, nargs=<optimized out>, keywords=<optimized out>) at Objects/call.c:242
#18 0x00007ffff2b7697a in _PyEval_EvalFrameDefault (tstate=<optimized out>, frame=<optimized out>, throwflag=<optimized out>) at Python/generated_cases.c.h:813
#19 0x00007ffff2c4e2c9 in PyEval_EvalCode (co=0x7fffa0c54730, globals=<optimized out>, locals=0x7fffeb52bd80) at Python/ceval.c:604
#20 0x00007ffff2c8c88c in run_eval_code_obj (tstate=tstate@entry=0x7ffff2f32df0 <_PyRuntime+283024>, co=co@entry=0x7fffa0c54730, globals=globals@entry=0x7fffeb52bd80, locals=locals@entry=0x7fffeb52bd80) at Python/pythonrun.c:1381
#21 0x00007ffff2c8985d in run_mod (mod=mod@entry=0x55555908ad08, filename=filename@entry=0x7ffff2ef64d8 <_PyRuntime+34936>, globals=globals@entry=0x7fffeb52bd80, locals=locals@entry=0x7fffeb52bd80, flags=flags@entry=0x0, 
    arena=arena@entry=0x7fff9f6be310, interactive_src=0x0, generate_new_source=0) at Python/pythonrun.c:1466
#22 0x00007ffff2c84cde in _PyRun_StringFlagsWithName (str=<optimized out>, name=0x7ffff2ef64d8 <_PyRuntime+34936>, start=<optimized out>, globals=0x7fffeb52bd80, locals=0x7fffeb52bd80, flags=0x0, generate_new_source=0) at Python/pythonrun.c:1261
#23 0x00007ffff3de7ea8 in Base::InterpreterSingleton::runString[abi:cxx11](char const*) (this=<optimized out>, sCmd=sCmd@entry=0x55555fad3980 "App.ActiveDocument.recompute()") at /home/morgan/programs/code-freecad/src/Base/Interpreter.cpp:248
#24 0x00007ffff541645c in Gui::Command::_runCommand (file=file@entry=0x7ffff5b73bd0 "/home/morgan/programs/code-freecad/src/Gui/Command.cpp", line=line@entry=949, eType=eType@entry=Gui::Command::App, 
    sCmd=0x55555fad3980 "App.ActiveDocument.recompute()") at /home/morgan/programs/code-freecad/src/Gui/Command.cpp:784
#25 0x00007ffff54165ce in Gui::Command::_doCommand (file=file@entry=0x7ffff5b73bd0 "/home/morgan/programs/code-freecad/src/Gui/Command.cpp", line=line@entry=949, eType=eType@entry=Gui::Command::App, 
    sCmd=sCmd@entry=0x7ffff5b73bb0 "App.ActiveDocument.recompute()") at /home/morgan/programs/code-freecad/src/Gui/Command.cpp:729
#26 0x00007ffff5416790 in Gui::Command::updateActive () at /home/morgan/programs/code-freecad/src/Gui/Command.cpp:949
#27 0x00007fff9e9788b5 in finishFeature (feature=feature@entry=0x5555564e3f00, prevSolidFeature=prevSolidFeature@entry=0x55555ecc0450, hidePrevSolid=hidePrevSolid@entry=true, updateDocument=updateDocument@entry=true, cmd=0x555556622440)
    at /home/morgan/programs/code-freecad/src/Mod/PartDesign/Gui/Command.cpp:626
#28 0x00007fff9e979346 in finishDressupFeature (cmd=cmd@entry=0x555556622440, which="Fillet", base=base@entry=0x55555ecc0450, SubNames=std::vector of length 1, capacity 1 = {...}, useAllEdges=<optimized out>)
    at /home/morgan/programs/code-freecad/src/Mod/PartDesign/Gui/Command.cpp:1913
#29 0x00007fff9e988248 in makeChamferOrFillet (cmd=0x555556622440, which="Fillet") at /home/morgan/programs/code-freecad/src/Mod/PartDesign/Gui/Command.cpp:1947
#30 0x00007fff9e988415 in CmdPartDesignFillet::activated (this=<optimized out>, iMsg=<optimized out>) at /usr/include/c++/15.2.1/bits/basic_string.tcc:248
#31 0x00007ffff541c99d in Gui::Command::_invoke (this=this@entry=0x555556622440, id=<optimized out>, id@entry=0, disablelog=<optimized out>) at /home/morgan/programs/code-freecad/src/Gui/Command.cpp:479
#32 0x00007ffff541ce66 in Gui::Command::invoke (this=0x555556622440, i=0, trigger=<optimized out>) at /home/morgan/programs/code-freecad/src/Gui/Command.cpp:443
#33 0x00007ffff07d466f in ?? () from /usr/lib/libQt6Core.so.6
#34 0x00007ffff1407800 in QAction::activate(QAction::ActionEvent) () from /usr/lib/libQt6Gui.so.6
#35 0x00007ffff1a383e1 in ?? () from /usr/lib/libQt6Widgets.so.6
#36 0x00007ffff1a45cc1 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) () from /usr/lib/libQt6Widgets.so.6
#37 0x00007ffff1b85a41 in QToolButton::mouseReleaseEvent(QMouseEvent*) () from /usr/lib/libQt6Widgets.so.6
#38 0x00007ffff195c8a7 in QWidget::event(QEvent*) () from /usr/lib/libQt6Widgets.so.6
#39 0x00007ffff1901dd0 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt6Widgets.so.6
#40 0x00007ffff1905db7 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt6Widgets.so.6
#41 0x00007ffff53941a0 in Gui::GUIApplication::notify (this=0x7fffffffc8a0, receiver=0x55555884bcd0, event=0x7fffffffbc40) at /home/morgan/programs/code-freecad/src/Gui/GuiApplication.cpp:103
#42 0x00007ffff0768678 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/libQt6Core.so.6
#43 0x00007ffff18f7298 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () from /usr/lib/libQt6Widgets.so.6
#44 0x00007ffff1978321 in ?? () from /usr/lib/libQt6Widgets.so.6
#45 0x00007ffff1979568 in ?? () from /usr/lib/libQt6Widgets.so.6
#46 0x00007ffff1901dd0 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt6Widgets.so.6
#47 0x00007ffff53941a0 in Gui::GUIApplication::notify (this=0x7fffffffc8a0, receiver=0x555558574500, event=0x7fffffffc230) at /home/morgan/programs/code-freecad/src/Gui/GuiApplication.cpp:103
#48 0x00007ffff0768678 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/libQt6Core.so.6
#49 0x00007ffff0fa13cd in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /usr/lib/libQt6Gui.so.6
#50 0x00007ffff10249b4 in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt6Gui.so.6
#51 0x00007fffeaf19e87 in ?? () from /usr/lib/qt6/plugins/platforms/../../../libQt6XcbQpa.so.6
#52 0x00007fffecb08880 in ?? () from /usr/lib/libglib-2.0.so.0
#53 0x00007fffecb09cd7 in ?? () from /usr/lib/libglib-2.0.so.0
#54 0x00007fffecb09ee5 in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#55 0x00007ffff0a3ffe2 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt6Core.so.6
#56 0x00007ffff0774ca6 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt6Core.so.6
#57 0x00007ffff076cd21 in QCoreApplication::exec() () from /usr/lib/libQt6Core.so.6
#58 0x00007ffff529a668 in (anonymous namespace)::tryRunEventLoop (mainApp=...) at /home/morgan/programs/code-freecad/src/Gui/Application.cpp:2397
#59 (anonymous namespace)::runEventLoop (mainApp=...) at /home/morgan/programs/code-freecad/src/Gui/Application.cpp:2430
#60 Gui::Application::runApplication () at /home/morgan/programs/code-freecad/src/Gui/Application.cpp:2543
#61 0x000055555555b797 in main (argc=<optimized out>, argv=<optimized out>) at /home/morgan/programs/code-freecad/src/Main/MainGui.cpp:331
```

### Development version About Info (in Safe Mode)

```shell
OS: Manjaro Linux (KDE/plasma/xcb)
Architecture: x86_64
Version: 1.2.0dev.44437 (Git)
Build date: 2025/11/24 21:55:38
Build type: Release
Branch: main
Hash: d2f082c7bcf2157fa77c94a456945eea2317bf7d
Python 3.13.7, Qt 6.9.2, Coin 4.0.5, Vtk 9.5.2, boost 1_88, Eigen3 3.4.0, PySide 6.9.2
shiboken 6.9.2, SMESH 7.7.1.0, xerces-c 3.3.0, OCC 7.9.1
Locale: English/United States (en_US)
Navigation Style/Orbit Style/Rotation Mode: Blender/Trackball/Drag at cursor
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Dark/
Logical DPI/Physical DPI/Pixel Ratio: 96/163.331/1
Installed mods: 
  * OpenDark 2023.12.17
  * A2plus 0.4.68
  * fasteners 0.5.43
  * AddonManager 2025.10.16
  * CurvedShapes 1.0.14
  * woodworking 1.1.0.dev.1.1.1.2025.10.27
  * Curves 0.6.70
```

### Last known good version (optional)

```shell

```

### PR DESCRIPTION
**Pull request by ipatch**
this PR aims to resolve crash described in issue #25639

fixes #25639

though this does prevent the crash i believe the upstream opencascade code could be improved as the stacktrace / backtrace the error is caused by an internal occ algo.

The crash happens in Geom2dAdaptor_Curve::D0 which is called from ChFi3d_FilBuilder::PerformTwoCorner

## Before and After Images

image

image

### CODE REVIEW

File: src/Mod/PartDesign/App/FeatureFillet.cpp [hunk 1]
```diff
@@ -138,9 +147,20 @@ App::DocumentObjectExecReturn* Fillet::execute()
...
+    }
     catch (Standard_Failure& e) {
         return new App::DocumentObjectExecReturn(e.GetMessageString());
     }
+    catch (...) {
+        return new App::DocumentObjectExecReturn(QT_TRANSLATE_NOOP(
+            "Exception",
+            "Fillet operation failed. The selected edges may contain geometry that cannot be "
+            "filleted together. "
+            "Try filleting edges individually or with a smaller radius."
```
Comment (kadet1090) [inline src/Mod/PartDesign/App/FeatureFillet.cpp:161]: I love that this catch-all exception is probably way more useful than any of the more specific ones :sweat_smile:
