### PR TITLE
[Part][Sketcher] Fix some B-spline trimming issues

### LINKED ISSUE #12592: [Problem] Trimming periodic B-spline by knots results in deformed geometry
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Trimming a periodic B-spline by knots results in deformed geometry:

Open [spline-trim.FCStd.zip](https://github.com/FreeCAD/FreeCAD/files/14393737/spline-trim.FCStd.zip) (remove the zip extension).
Open the sketch.
Trim the right side of the periodic B-spline between the 2 lines.
Result: O-shape becomes a self-crossing Y-shape.

V0.21 does not have this issue.

spline-trim

### Full version info

```shell
OS: Windows 8 build 9600
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36117 (Git)
Build type: Release
Branch: main
Hash: 8a3407aee6dff8218282d9cdc3f4e32e7ad958d4
Python 3.10.13, Qt 5.15.8, Coin 4.0.2, Vtk 9.2.6, OCC 7.6.3
Locale: Dutch/Netherlands (nl_NL)
Installed mods:
```

### Subproject(s) affected?

Sketcher

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by AjinkyaDahale**
Fixes #12592.

~There is still a problem with the other (non-periodic) B-spline shown in that issue's example.~

If anyone wants to check it out, this issue was introduced in 728a880078f04e24bfe5ed215c95c4032f073683.

### CODE REVIEW

**Comment by AjinkyaDahale** [comment]
@bgbsww could you confirm whether or not it is important for a B-spline to have parameter range from 0 to 1, especially for topological naming concerns? The commit mentioned in OP is originally from RealThunder, and changes a generalization made later (the exact code I'm replacing it with).

It is a valid but not necessary restriction to keep these curves from 0 to 1. However, in that case, we should make it such that it is never possible to create them with any other range.

In any case, we should also somehow add tests to ensure whatever decision is taken should be enforced. When keeping a restriction, this would mean to try to create a B-spline that breaks it, and verify that this raises an exception or scales parameters. Otherwise, it would mean to ensure that every method that uses B-spline can use arbitrary parameters (something that could have failed 728a880078f04e24bfe5ed215c95c4032f073683).

**Comment by bgbsww** [comment]
I confirm that I don't see a TNP issue here.  TNP fix usually cares that you are using a TopoShape and not a TopoDS_Shape ( or TopoDS_Face or TopoDS_Edge or TopoDS_Vertex ...) because all the TNP avoidance code is based around that TopoShape, and the lower level OCCT TopoDS_XX objects don't know to look for it.  So you can change the logic all you want, as long as you don't restore the lower level object use.  

This looks like another of the cases where I have inadvertently brought along a logic change along with the upgrade to TopoShape.  In my defense, it's a handful against hundreds of cases, but still, poop.

**Comment by AjinkyaDahale** [comment]
> TNP fix usually cares that you are using a TopoShape and not a TopoDS_*... So you can change the logic all you want, as long as you don't restore the lower level object use.

Thanks. I'll keep it in mind.

> This looks like another of the cases where I have inadvertently brought along a logic change along with the upgrade to TopoShape. In my defense, it's a handful against hundreds of cases, but still, poop.

No need to defend. Still, I'm curious how this can be tested.

**Comment by bgbsww** [comment]
Is it sufficient just to test a sample case or two where the parameter range exceeds 1?  I think my original error was in assuming incorrectly that the range should be limited, and that isn't clear as you note.  That test should deter any future modifications that bring the limit in.

**Comment by AjinkyaDahale** [comment]
> Is it sufficient just to test a sample case or two where the parameter range exceeds 1? I think my original error was in assuming incorrectly that the range should be limited, and that isn't clear as you note. That test should deter any future modifications that bring the limit in.

That's what I was thinking. Just that this check should be applied everywhere its possible to make the 0-1 assumption.

**Comment by AjinkyaDahale** [comment]
Added some more trim-related changes
1. Now, point-on-object constraints will be applied to the resultant curve that the point actually lies on, rather than to the "start" curve.
2. Internal geometry of both resultant B-splines is displayed.
3. If the point lies outside the resultant B-splines, it is deleted. This causes shape change in B-splines, but can be kept for other curves.

File: src/Mod/Sketcher/App/SketchObject.cpp [hunk 1]
```diff
@@ -2989,6 +2991,56 @@ int SketchObject::trim(int GeoId, const Base::Vector3d& point)
         delConstraints(delete_list, false);
     };
 
+    // Pick the appropriate portion which should inherit the point-on-object constraint
+    // (or delete it altogether if it's not on any curve)
+    // Assume that GeoId1 is the pre-existing curve
+    // GeoId2 can be same as GeoId1 (for example for periodic B-spline)
+    auto chooseCurveForPointOnObject = [this](int GeoId1,
```
Comment (PaddleStroke) [inline src/Mod/Sketcher/App/SketchObject.cpp:2998]: Any reason why you are using a lambda rather than a normal function here? This Lambda is huge and so the function containing it even more so.

Comment (AjinkyaDahale) [reply src/Mod/Sketcher/App/SketchObject.cpp:2998]: I could define a normal function, but it would still have to be within this `trim` method, since it's use is limited and arguments are very dependent on `trim`'s internals. Admittedly not the best approach.

Comment (PaddleStroke) [reply src/Mod/Sketcher/App/SketchObject.cpp:2998]: Oh it's in trim(), I have to say I didn't look in which function it was.
Well then it sounds even less acceptable. Trim function is a huge beast of 700 lines. I'm not a huge advocate of refactoring, but even I can see that 700 is too long.
Perhaps trim should become a class then if you feel that the lambda cannot be taken out.

Comment (PaddleStroke) [reply src/Mod/Sketcher/App/SketchObject.cpp:2998]: Maybe refactoring trim is another PR though. I'm not against leaving this like that for this PR.

Comment (AjinkyaDahale) [reply src/Mod/Sketcher/App/SketchObject.cpp:2998]: Yes. I'll go with this option. This lambda and a lot of code from `trim` can be reused in, say, `split`. All that is best done with some tests added beforehand.

File: src/Mod/Sketcher/App/SketchObject.cpp [hunk 2]
```diff
@@ -260,25 +260,27 @@ void SketchObject::buildShape()
         ++i;
         if(GeometryFacade::getConstruction(geo))
             continue;
-        if (geo->isDerivedFrom(Part::GeomPoint::getClassTypeId())) {
 #ifdef FC_USE_TNP_FIX
+        if (geo->isDerivedFrom(Part::GeomPoint::getClassTypeId())) {
```
[the remark this answers is not in the document]
Comment (AjinkyaDahale) [reply src/Mod/Sketcher/App/SketchObject.cpp:264]: I only moved this line to keep spacemacs from highlighting all the subsequent braces for mismatch. maybe it can be kept as such for now.

**Comment by AjinkyaDahale** [comment]
Not sure why the tests are failing, but they don't appear to relate to these changes on surface.
