### PR TITLE
Fix legacy mmTangentPlane orientation in 1.1.0dev (resolves #24254)

### LINKED ISSUE #24254: SubtractivePipe: "Tool shape is not valid for boolean operation" error in 1.0, incorrect shape in 1.1.0dev
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Problem description

- FreeCAD 0.21.2 → works correctly (original design environment)
- FreeCAD 1.0.2 → recompute fails with error
- FreeCAD 1.1.0dev rev14555 (2025-09-24) → no compute error, but wrong shape calculated

[SubtractivePipe-issue.zip](https://github.com/user-attachments/files/22559368/SubtractivePipe-issue.zip)

1. The following model was designed with FreeCAD 0.21.2 using SubtractivePipe.
Image

2. When opening the same file in FreeCAD 1.0.2 and recomputing, the following error occurs:
Tool shape is not valid for boolean operation
Image

3. When opening the same file in FreeCAD 1.1.0dev rev14555 (2025-09-24), the error no longer occurs, but the calculated shape is incorrect.
Image

Result in 1.1.0dev rev14555:
Image

I found the following issue that shows a similar error in 1.0. It seems related to adaptive functions in 1.0, but in my case 1.1.0dev introduced another issue, where an incorrect shape is calculated:
https://github.com/FreeCAD/FreeCAD/issues/18236

I also found the following PR, which has already been merged. It would prevent the error that occurred in 1.0, but in 1.1.0dev rev14555 it exposes a new issue, where an incorrect shape is calculated:
https://github.com/FreeCAD/FreeCAD/pull/23102

### Full version info

```shell
OS: Windows 11 build 26100
Architecture: x86_64
Version: 1.0.2.39319 (Git) Conda
Build type: Release
Branch: (HEAD detached at 1.0.2)
Hash: 256fc7eff3379911ab5daf88e10182c509aa8052
Python 3.11.13, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: Japanese/Japan (ja_JP)
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Dark/Fusion
Installed mods: 
  * Assembly4 0.50.18
  * CfdOF 1.30.2
  * CfdOF_fork 1.30.4
  * fasteners 0.5.38

OS: Windows 11 build 26100
Architecture: x86_64
Version: 1.1.0dev.14555 (Git shallow)
Build date: 2025/09/23 18:47:15
Build type: Release
Branch: main
Hash: e9ce06155d8d47aad7d6c079bfa8ba54df2b6081
Python 3.11.13, Qt 6.8.3, Coin 4.0.3, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.3.0, IfcOpenShell 0.8.2, OCC 7.8.1
Locale: Japanese/Japan (ja_JP)
Navigation Style/Orbit Style/Rotation Mode: TinkerCAD/Trackball/Object center
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Dark/
Logical DPI/Physical DPI/Pixel Ratio: 96/93.1131/1.5
Installed mods: 
  * Assembly4 0.50.18
  * CfdOF 1.30.2
  * CfdOF_fork 1.30.4
  * fasteners 0.5.38
```

### Subproject(s) affected?

PartDesign

### Anything else?

_No response_

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by marbocub**
## Summary

This draft pull request fixes issue #24254 by restoring the pre-1.1.0dev handling code and adding a simple branching mechanism. This allows both legacy and new Datum objects to be handled correctly in 1.1.0dev.

I’m submitting it as a draft to present this straightforward solution and to get feedback, as there may be alternative approaches.
I’m still getting familiar with the codebase, so any guidance would be greatly appreciated.

## Issues
#24254

## Details

This change reintroduces the pre-1.1.0dev handling code for legacy Datum objects in `AttachEngine::readLinks()`.
It checks each object’s `getInList()` to decide whether to apply the restored pre-1.1.0dev behavior for legacy `DatumPlane`/`DatumLine` or to follow the current 1.1.0dev code path.

As a result, both legacy and new Datum objects can coexist and be handled correctly.

## Considerations

For now, I use each object’s `getInList()` to check whether it is related to a legacy Datum, since I don’t know of a way to determine the target object type from the provided arguments. There might be a cleaner solution.

It might be better to implement a conversion layer at a higher level, converting all legacy Datum to new Datum objects and adjusting their rotations, rather than this approach.

## Status

The changes work in my tests. Feedback or suggestions are welcome.

### CODE REVIEW

**Comment by marbocub** [comment]
Update:

The previous fix has been reverted.

A new function, `AttachEngine::adjustLegacyTangentModeRotation()`, has been added and is called from `AttachExtension::positionBySupport()`.
It ensures that objects attached in mmTangentPlane mode behave as follows:

* For Core DatumPlanes (Part::DatumPlane), the behavior remains unchanged.

* For other objects, the rotation is adjusted to match the legacy behavior.

This function determines the plane orientation based on OCCT’s `gp_Pln()`, similar to what the previous `readLinks()` did.

I’m not sure if this approach is ideal, but it correctly handles data created with both 0.21 / 1.0 and 1.1.0dev.

**Comment by marbocub** [comment]
Update:

I’ve reverted the previous changes.

After expanding the verification scope, I found that the issue described in #24254 affects a much broader range of cases — not only the legacy PartDesign DatumPlane but also other objects attached in mmTangentPlane mode.

To address this, I added an emulation of the legacy `gp_Pln()`-based orientation logic inside `AttachEngine3D::_calculateAttachedPlacement()`.
This emulation preserves the original orientation behavior, even if OCCT’s internal behavior changes in the future.

This fix restores compatibility with models created in 1.0 and earlier. However, it breaks compatibility with models created in 1.1.0dev when attached in mmTangentPlane mode — meaning that the Core Datum behavior in this mode may be affected.

This fix mainly focuses on resolving the compatibility issue reported in #24254, while the Core Datum behavior in mmTangentPlane mode will likely need further discussion and refinement, including #24599.

Thank you very much for your time and consideration.

**Comment by chennes** [comment]
@PaddleStroke what are your thoughts on this approach?

**Comment by PaddleStroke** [comment]
checking this now

**Comment by PaddleStroke** [comment]
Ok so this PR is basically restores the old, flawed orientation logic to any App::Plane that is used as a reference in mmTangentPlane mode.

This fixes the problem for old models (like the one in #24254)

However, as @marbocub  noted, this breaks compatibility for models created in the development versions of 1.1 (between PR #18332 and this fix). Any user who created a model using mmTangentPlane with a new App::Plane was relying on the new, correct orientation logic. This fix will now change the orientation of their attachment, breaking their models.

I do not know what is the best course of action here. If we do nothing, some files are getting bad. If we merge this, other files will get bad. And merging this restore a wrong behavior that is a weakness in the software.

Restoring this bad behavior is an open door for more issues in the future, more potential bug, more complexity.
Not restoring means some 1.0 files gets corrupted. Restoring means some 1.1 files gets corrupted. But 1.1 is development version so it can be argued that it should not have been used in production. But a lot of people use dev because our dev cycles are so long...

Besides the regression is apparantly not so widespread as it is quite specific, it needs attachment to a App::Plane with a rotation offset. This is the first report since 18332 merged.

And the attachements can be fixed by editing the offset.

So considering all of this, I would rather not restore the old bad behavior, and add a release note about this. But I am not sure it's the correct solution.

**Comment by chennes** [comment]
If we want to take a migration approach instead of a "stick to the old way" approach, if I have access to the placement of a plane and know that it was created in an old version of FreeCAD, what needs to happen to it? That is, I have the XML element
```
                <Property name="Placement" type="App::PropertyPlacement" status="8388616">
                    <PropertyPlacement Px="0.0000000000000000" Py="0.0000000000000000" Pz="0.0000000000000000" Q0="0.5000000000000000" Q1="0.5000000000000000" Q2="0.5000000000000000" Q3="0.5000000000000001" A="2.0943951023931953" Ox="1.0000000000000000" Oy="1.0000000000000000" Oz="1.0000000000000000"/>
                </Property>
```

**Comment by PaddleStroke** [comment]
Is it possible to know if a file was made before 18332 merged?

The problem is that even if you know, I am not sure you can migrate. Because the old bad behavior was transforming only the Z axis, then it relied on the gp_pln constructor to define X axis. So my understanding is that doing a migration that would work in this particular fix is not guaranteed to work in another file.

**Comment by PaddleStroke** [comment]
However, because App::Plane were only available in App::Origin before, then this bug could happen only when selecting the XY or YZ planes. So perhaps what I just said is not a problem in this case because we have only 2 cases.

**Comment by PaddleStroke** [comment]
To fix the file in the issue, you can just change the attachment offset : https://github.com/FreeCAD/FreeCAD/issues/24254#issuecomment-3359871137
turn around -26deg Y axis offset into +26 X axis offset.

I tried to recreate locally another example and found a different result : 

1.0 : 
image


1.1 : 
image

So in this example we only need to change the sign of X axis and Y axis offset without swapping them.
On top of that in the 1.0 example the plane is not even passing through vertex8 as it should... Which may be another issue. But in 1.1 it works as expected.

This test seems to say that it cannot be migrated

**Comment by chennes** [comment]
I am working on a proof-of-concept for a migration addon that would allow you to go back and forth between versions, and was trying to see if this was approachable with that method, by applying a reversible mathematical operation to the plane.

**Comment by chennes** [comment]
What about a compromise solution where we include a (possibly-hidden) parameter that controls which plane calculation algorithm is used? If the parameter is unset, or explicitly set to the pre-1.1 value, we use the old algorithm, and if it's set to 1.1, we use the new one? [Something like this](https://github.com/chennes/FreeCAD/commit/fa6d8fc9c539e3e54f0e7e2203f0bb9bdde5f77c) (note that's probably not a complete implementation, I only tested it briefly, and didn't add any unit tests for it).

**Comment by PaddleStroke** [comment]
It can be done. But I'm not sure of the value of it because this parameter would be disabled by default. So user with a broken file will not know until he understand this particular attachment is broken. So by the time he learns about this preference, he will know what is wrong. And so it will be as easy for him to just redo the attachment than to set this parameter. Especially since this parameter is going to be a pita for later. Because if user set this parameter to true, then all the files he now creates are going to be 'legacy'. If he share this file with someone else it's going to be a mess.

What about printing a warning message when we detect such a bad legacy attachment ? If we can detect files created before 18832, then we can check the file on restore for attachment mmTangent to ZY_plane that has X/Y axis offset. And then print the warning explaining what is going on and what they need to do.

**Comment by chennes** [comment]
Sorry, I made a bad word choice -- I don't mean a "parameter" (in the sense of a user-configuration option), I mean a property. I have a [working prototype here](https://github.com/chennes/FreeCAD/commit/fa6d8fc9c539e3e54f0e7e2203f0bb9bdde5f77c). The idea is that if the file *does not* have this property, then "TangentPlaneAlgorithm" is considered unset, and uses the old algorithm. If the file has the property, then it's an explicit flag about whether to use the old or the new algorithm. As coded above it's invisible, and the idea is that a migration macro could look at the exact revision of FreeCAD and decide which algorithm to set when run on that narrow band of affected files created during the 1.1 development cycle.

**Comment by marbocub** [comment]
I’ve implemented [an alternative approach as a simple compatibility layer](https://github.com/marbocub/FreeCAD/commit/565fda580269f12e4d2e6a92e95d74c4d96a3214) to handle this issue, designed to have minimal impact on existing FreeCAD functionality.
It’s working fine in my local tests, and I’m considering submitting it — either as a replacement for this pull request by reverting it and adding a commit, or as a new one — to further the discussion.

The logic applies only when the ProgramVersion of the stored data is earlier than 1.1, and the object is attached in mmTangentPlane mode to an App::Plane (with an associated vertex).
In such cases, it adjusts the plane orientation by ±90° rotation around the Z axis of the AttachmentOffset and swaps the X/Y placement values — with the sign of one axis inverted as determined by the dominant axis of the plane normal — during document restoration, ensuring that the orientation of legacy data is converted to match the behavior of 1.1.0dev.
When the ProgramVersion of the stored data is 1.1 or later, no conversion is performed — once the data has been converted and saved, it will not be converted again.

The compatibility layer is currently implemented in AttachExtension::handleLegacyTangentPlaneOrientation() and invoked from AttachExtension::onExtendedDocumentRestored().
While this location ensures data integrity, a different location might be more suitable in terms of responsibility separation.

With this logic, my legacy data and data newly saved in 1.1 have been successfully handled and behave correctly in 1.1.0dev.
While there might still be some cases that this logic doesn’t fully cover, I believe it should allow most legacy data to migrate correctly.

I’m currently doing a final build verification. If this approach seems reasonable, I’d like to proceed with submitting it as a pull request accordingly.
Any feedback would be greatly appreciated.

**Comment by chennes** [comment]
This is a fine approach for me. Note that you don't need to add commits for reversion, etc. Just do an "interactive rebase" to drop the original commits, and add your new one. If you continue doing that on this branch, the PR will update automatically.

**Comment by marbocub** [comment]
Thank you very much for your feedback and support.

I've added a new commit, performed an interactive rebase, and pushed the updated branch using `--force-with-lease`. I've also revised the PR title to better reflect the current focus on legacy `mmTangentPlane` orientation handling.

I would greatly appreciate any reviews or suggestions you may have.

Thanks again for your time and guidance!

**Review by pieterhijma — COMMENTED** [review]
The code looks good to me. Nice that you are taking into account expressions as well.

I tested the code and your original model looks as expected with this PR.

I'm wondering why the placement is a bit off and I don't understand the attachment offsset compared to what I read in the code:

pre card4, DatumPlane024
- placement: (0, 1, 0); 64; (18.8, 2.54, 6.5)
- attachment offset: (0, -1, 0); 26; (0, 0, 0)

in your pr, DatumPlane024:
- placement: (0, -1, 0); 296; (18.8, 2.54, 6.5)
- attachment offset: (0.22, -0.22, 0.95); 92.90; (0, 0, 0)

The two models from [this comment](https://github.com/FreeCAD/FreeCAD/issues/24254#issuecomment-3404721651) also work as expected in your PR. 

I'm essentially ok, but @marbocub, I would appreciate if you could explain the above.

**Comment by marbocub** [comment]
@pieterhijma

Thank you for the review.

**Placement:**  
The value of `Placement.Base = (18.8, 2.54, 6.5)` is identical between the old and new versions.  
As for `Placement.Rotation.Axis` and `Placement.Rotation.Angle`, the angles 64° and -296° represent the same rotation (since 64 = 360 - 296). The axis direction is reversed due to quaternion-to-axis-angle conversion, so I believe the rotation is effectively unchanged.

**AttachmentOffset:**  
Regarding `AttachmentOffset.Rotation.Axis = (0.22, -0.22, 0.95)` and `AttachmentOffset.Rotation.Angle = 92.90°`, these correspond to the axis-angle representation of Euler angles (90.0°, -26.0°, 0.0°).  
image
Compared to the previous rotation of (0.0°, -26.0°, 0.0°), this indicates a 90° yaw rotation, which matches the intended transformation logic in the code.

I believe the data is being converted as expected.  

If my understanding is incorrect, I’d appreciate any clarification.

File: src/Mod/Part/App/AttachExtension.cpp [hunk 1]
```diff
@@ -477,6 +482,164 @@ bool AttachExtension::extensionHandleChangedPropertyName(Base::XMLReader& reader
...
+        return;
+    }
+    if (major > 1 || (major == 1 && minor > 0)) {
+        return;
+    }
+
+    // check for an App::Plane support object exists
+    App::GeoFeature* geof = nullptr;
+    for (auto obj : this->AttachmentSupport.linkedObjects()) {
+        if (obj->isDerivedFrom(Base::Type::fromName("App::Plane"))) {
```
Comment (marbocub) [inline src/Mod/Part/App/AttachExtension.cpp]: Would it be better to use `App::Plane::getClassTypeId()` instead of `Base::Type::fromName("App::Plane")`?

I recently discovered that `App::Plane::getClassTypeId()` becomes available via `#include <App/Datums.h>`.

**Comment by pieterhijma** [comment]
> If my understanding is incorrect, I’d appreciate any clarification.

Thanks, I don't know myself. I was more worried about users that see there inputs transformed in a way that they may not understand. I guess we can't really do something about that.

File: src/Mod/Part/App/AttachExtension.cpp (hunk 1 above)
Comment (pieterhijma) [reply src/Mod/Part/App/AttachExtension.cpp]: Good points. I will do another review in more detail looking at the code.

File: src/Mod/Part/App/AttachExtension.cpp [hunk 2]
```diff
@@ -24,6 +24,11 @@
 #include <Base/Console.h>
 #include <Base/Tools.h>
 
+#include <App/Document.h>
```
Comment (pieterhijma) [inline src/Mod/Part/App/AttachExtension.cpp:27]: Indeed, it is better to include Datums here to not rely on strings for types.

```suggestion
#include <App/Document.h>
#include <App/Datums.h>
```

File: src/Mod/Part/App/AttachExtension.cpp (hunk 1 above)
Comment (pieterhijma) [inline src/Mod/Part/App/AttachExtension.cpp]: I think this would be the most clear solution:

```suggestion
        if (obj->isDerivedFrom<App::Plane>()) {
```

File: src/Mod/Part/App/AttachExtension.cpp [hunk 3]
```diff
@@ -477,6 +482,164 @@ bool AttachExtension::extensionHandleChangedPropertyName(Base::XMLReader& reader
...
+    }
+    if (major > 1 || (major == 1 && minor > 0)) {
+        return;
+    }
+
+    // check for an App::Plane support object exists
+    App::GeoFeature* geof = nullptr;
+    for (auto obj : this->AttachmentSupport.linkedObjects()) {
+        if (obj->isDerivedFrom(Base::Type::fromName("App::Plane"))) {
+            geof = dynamic_cast<App::GeoFeature*>(obj);
```
Comment (pieterhijma) [inline src/Mod/Part/App/AttachExtension.cpp]: You can make use of the FreeCAD type system here:

```suggestion
            geof = freecad_cast<App::GeoFeature*>(obj);
```

File: src/Mod/Part/App/AttachExtension.cpp [hunk 4]
```diff
@@ -477,6 +482,164 @@ bool AttachExtension::extensionHandleChangedPropertyName(Base::XMLReader& reader
...
+    geof->Placement.getValue().getRotation().multVec(Base::Vector3d(0.0, 0.0, 1.0), norm);
+    gp_Dir normal(norm.x, norm.y, norm.z);
+
+    // determine the dominant global axis
+    std::array<double, 3> cosXYZ = {
+        fabs(normal.Dot(gp_Dir(1, 0, 0))),  // normal dot global X axis
+        fabs(normal.Dot(gp_Dir(0, 1, 0))),  // normal dot global Y axis
+        fabs(normal.Dot(gp_Dir(0, 0, 1)))   // normal dot global Z axis
+    };
+    int axis = std::max_element(cosXYZ.begin(), cosXYZ.end()) - cosXYZ.begin();
```
Comment (pieterhijma) [inline src/Mod/Part/App/AttachExtension.cpp]: Using ranges and preventing a conversion from long to int

```suggestion
    std::size axis = std::ranges::max_element(cosXYZ) - cosXYZ.begin();
```

File: src/Mod/Part/App/AttachExtension.cpp [hunk 5]
```diff
@@ -477,6 +482,164 @@ bool AttachExtension::extensionHandleChangedPropertyName(Base::XMLReader& reader
...
+
+    try {
+        // extract current attachment offset values
+        Base::Placement placement = this->AttachmentOffset.getValue();
+        Base::Vector3d position = placement.getPosition();
+        Base::Rotation rotation = placement.getRotation();
+        double yaw, pitch, roll;
+        rotation.getYawPitchRoll(yaw, pitch, roll);
+
+        // extract existing expressions
```
Comment (pieterhijma) [inline src/Mod/Part/App/AttachExtension.cpp:552]: I would prefer to have a small lambda here that constructs the object identifiers to remove the code duplication.

File: src/Mod/Part/App/AttachExtension.cpp [hunk 6]
```diff
@@ -477,6 +482,164 @@ bool AttachExtension::extensionHandleChangedPropertyName(Base::XMLReader& reader
...
+            // should not happen
+            return;
+        }
+
+        // store updated placement and expressions back to the document object
+
+        // expressions
+        owner->ExpressionEngine.setValue(oidX, std::move(App::ExpressionPtr(newExprX)));
+        owner->ExpressionEngine.setValue(oidY, std::move(App::ExpressionPtr(newExprY)));
+        owner->ExpressionEngine.setValue(oidYaw, std::move(App::ExpressionPtr(newExprYaw)));
```
Comment (pieterhijma) [inline src/Mod/Part/App/AttachExtension.cpp]: The expression pointer is already a temporary so using move semantics is unnecessary as the compiler will do it automatically.

```suggestion
        owner->ExpressionEngine.setValue(oidX, App::ExpressionPtr(newExprX));
        owner->ExpressionEngine.setValue(oidY, App::ExpressionPtr(newExprY));
        owner->ExpressionEngine.setValue(oidYaw, App::ExpressionPtr(newExprYaw));
```

File: src/Mod/Part/App/AttachExtension.cpp [hunk 7]
```diff
@@ -477,6 +482,164 @@ bool AttachExtension::extensionHandleChangedPropertyName(Base::XMLReader& reader
...
+
+        // values
+        placement.setPosition(position);
+        placement.setRotation(rotation);
+        this->AttachmentOffset.setValue(placement);
+
+    } catch (const Base::Exception& e) {
+        Base::Console().error("Error converting attachment offset of %s: %s\n",
```
Comment (pieterhijma) [inline src/Mod/Part/App/AttachExtension.cpp]: The error message could be a bit more explanatory:

```suggestion
        Base::Console().error("Error converting legacy attachment offset of %s: %s\n",
```

**Review by pieterhijma — DISMISSED** [review]
Looks good in general. I answered your question and made some minor suggestions to make the code more idiomatic.

Would be great if you could make the changes!

**Comment by marbocub** [comment]
@pieterhijma

Thank you — I understand what you mean:

> I was more worried about users that see their inputs transformed in a way that they may not understand.

Yes, not only can users end up seeing unexpected changes, but since this is a simple approach, it may not fully handle cases where expressions reference other geometry — both the source and the target may end up being transformed.

File: src/Mod/Part/App/AttachExtension.cpp (hunk 1 above)
Comment (marbocub) [reply src/Mod/Part/App/AttachExtension.cpp]: Oh, I see!

File: src/Mod/Part/App/AttachExtension.cpp (hunk 6 above)
Comment (marbocub) [reply src/Mod/Part/App/AttachExtension.cpp]: Thanks, that makes sense now.

File: src/Mod/Part/App/AttachExtension.cpp (hunk 4 above)
Comment (marbocub) [reply src/Mod/Part/App/AttachExtension.cpp]: Thanks — I updated it to use std::distance to compute the index:
```
std::size_t axis = std::distance(cosXYZ.begin(), std::ranges::max_element(cosXYZ));
```

File: src/Mod/Part/App/AttachExtension.cpp (hunk 5 above)
Comment (marbocub) [reply src/Mod/Part/App/AttachExtension.cpp:552]: Thanks for the suggestion. I’ve added a small lambda:
```
auto buildOID  = [owner](const std::vector<std::string>& path) {
    App::ObjectIdentifier oid(owner, true);
    for (const auto& name : path) {
        oid.addComponent(App::ObjectIdentifier::SimpleComponent(name));
    }
    return oid;
};
App::ObjectIdentifier oidX   = buildOID ({"AttachmentOffset", "Base", "x"});
App::ObjectIdentifier oidY   = buildOID ({"AttachmentOffset", "Base", "y"});
App::ObjectIdentifier oidYaw = buildOID ({"AttachmentOffset", "Rotation", "Yaw"});
```

File: src/Mod/Part/App/AttachExtension.cpp (hunk 3 above)
Comment (marbocub) [reply src/Mod/Part/App/AttachExtension.cpp]: I read through BaseClass — it's impressive how freecad_cast, combined with the type system and isDerivedFrom, enables a safe static_cast. Learned a lot from this, thank you!

**Comment by chennes** [comment]
OK, it seems everything is good to merge code-wise here. My last request is for a file (or several files) that we can turn into regression tests to ensure that this code works now, and stays working in the future. Can you construct a simpler test case than the one in the original issue?

**Comment by marbocub** [comment]
How about the following test file? It was created with version 0.21.  

[TestTangentMode3-0.21.FCStd.zip](https://github.com/user-attachments/files/23398489/TestTangentMode3-0.21.FCStd.zip)

image


Sketch001 is attached to Sketch:Vertex1 and the XY_Plane,  
Sketch002 is attached to Sketch:Vertex1 and the XZ_Plane,  
and Sketch003 is attached to Sketch:Vertex1 and the YZ_Plane.  
Each sketch contains the characters "001" to "003" corresponding to its name.

Each of the three planes has expressions or fixed values in AttachmentOffset, which define translation and rotation.
Moving Sketch:Vertex1 causes the entire model to move accordingly, which I think may represent one possible realistic use case.

* 1.0: opens correctly  
* current 1.1.0dev: the shape changes but no computation error occurs, so the shapes can still be validated using the Python script below  
* this PR: the file opens normally, transformations are applied correctly, and the original shape is preserved  

The Python script below can be used to verify whether the computed Placement, Normal, and Tangent X-Axis of the three planes (Sketch001, Sketch002, Sketch003) match the designer’s expectations.
Perhaps this approach of verifying against the vectors in expected_planes[] could also be useful in the test module.

```
import math

def check_plane(name, expected_pos, expected_normal, expected_xaxis):
    obj = App.ActiveDocument.getObject(name)
    if not obj:
        FreeCAD.Console.PrintError(f"{name}: object not found\n")
        return

    pos = obj.Placement.Base
    rot = obj.Placement.Rotation
    normal = rot.multVec(FreeCAD.Vector(0,0,1))
    xaxis  = rot.multVec(FreeCAD.Vector(1,0,0))

    # position
    if (pos - expected_pos).Length < 1e-6:
        FreeCAD.Console.PrintMessage(f"{name}: position matches\n")
    else:
        FreeCAD.Console.PrintError(f"{name}: position mismatch {pos}\n")

    # normal
    if normal.getAngle(expected_normal) < 1e-6:
        FreeCAD.Console.PrintMessage(f"{name}: normal direction matches\n")
    else:
        FreeCAD.Console.PrintError(f"{name}: normal direction mismatch {normal}\n")

    # tangent x-axis
    if xaxis.getAngle(expected_xaxis) < 1e-6:
        FreeCAD.Console.PrintMessage(f"{name}: X-axis direction matches\n")
    else:
        FreeCAD.Console.PrintError(f"{name}: X-axis direction mismatch {xaxis}\n")

r = 10.0
rad30 = math.radians(30)
cos30 = math.cos(rad30)
sin30 = math.sin(rad30)

expected_planes = [
    ("Sketch001",
     FreeCAD.Vector(-1 * r, 0, 0), # position
     FreeCAD.Vector(1, 0, 0),      # normal
     FreeCAD.Vector(0, -1, 0)),    # tangent x-axis
    ("Sketch002",
     FreeCAD.Vector(sin30 * r,
                    cos30 * cos30 * (-r),
                    cos30 * sin30 * r),
     FreeCAD.Vector(sin30,
                    cos30 * cos30 * (-1),
                    cos30 * sin30),
     FreeCAD.Vector(0, sin30, cos30)),
    ("Sketch003",
     FreeCAD.Vector(cos30 * cos30 * r,
                    sin30 * r,
                    cos30 * sin30 * r),
     FreeCAD.Vector(cos30 * cos30,
                    sin30,
                    cos30 * sin30),
     FreeCAD.Vector(sin30, 0, -cos30)),
]

for name, pos, normal, xaxis in expected_planes:
    check_plane(name, pos, normal, xaxis)
```

**Comment by chennes** [comment]
If you open your file with FreeCAD 1.1 and then re-save it, does it still open correctly?

**Comment by chennes** [comment]
Thanks for the test file and code: I've adapted it into our regression testing framework. It looks like it's not passing so presumably I messed something up in the translation. Do you see what it is?

**Comment by marbocub** [comment]
> If you open your file with FreeCAD 1.1 and then re-save it, does it still open correctly?

Yes, I have confirmed this.

If the file is opened and saved with this PR, then when reopening it later the shape remains as saved and there is no double conversion — the conversion only happens the first time.

On the other hand, if the file has already been opened and saved with the regular 1.1.0dev, it cannot be converted afterwards even with this PR, but I think that is unavoidable.

To confirm in a test case that no double conversion occurs, this TestTangentMode3-1.1.FCStd file could also be used in addition, and by verifying it with the expected_planes[] defined earlier, it may be possible to determine whether the model remains as intended (i.e. whether or not a double conversion has occurred).  
As an example, one possible usage would be to first verify with the TestTangentMode3-0.21.FCStd file and then with the TestTangentMode3-1.1.FCStd file, and if neither matches the expected_planes[], an assert could then be triggered.

[TestTangentMode3-1.1.FCStd.zip](https://github.com/user-attachments/files/23401435/TestTangentMode3-1.1.FCStd.zip)

> Thanks for the test file and code: I've adapted it into our regression testing framework. It looks like it's not passing so presumably I messed something up in the translation. Do you see what it is?

Here is the output in my environment.  
Sketch002 and Sketch003 were converted without any errors, so it looks like the test finished successfully.  
I will try again by merging with master and doing a full build.

```
$ bin/FreeCAD --run-test TestPartApp
FreeCAD 1.1.0, Libs: 1.1.0devR43915 (Git)
(C) 2001-2025 FreeCAD contributors
FreeCAD is free and open-source software licensed under the terms of LGPL2+ license.

<AnaFilletAlgo object>
<ChamferAPI object>
<FilletAlgo object>
<ShapeFix_Edge object>
<ShapeFix_Face object>
<ShapeFix_Root object>
<ShapeFix_Shape object>
<ShapeFix_Shell object>
<ShapeFix_Solid object>
<ShapeFix_Wire object>
Converting attachment offset of Sketch003
Converting attachment offset of Sketch002
TopoShapeListTest - setting up
TopoShapeListTest: setUp complete
running TopoShapeListTest
TopoShapeListTest finished

----------------------------------------------------------------------
Ran 127 tests in 21.9s

OK
System exit
```

**Comment by marbocub** [comment]
I did a `git pull --rebase upstream main`, rebuilt, and tested again,  
but in my environment (FreeCAD 1.1.0, Libs: 1.1.0devR44180 +5 (Git)) TestPartApp passed successfully.  

Sorry, I have no idea what might be happening.

**Comment by chennes** [comment]
Doesn't really matter, it's passing in the CI and does appear to be running, so whatever is broken is just my local build. I'll blow it away and retry.
