### PR TITLE
Gui: improve quantitySpinbox / Sketcher OVP

### LINKED ISSUE #25947: 1.1rc1   Dimensions overflow text box in Sketcher
### Workbench affected?

Sketcher

### Problem description

When in Sketcher Dimension tool
If a large number of decimals like 4 places, or when getting in to hundreds of millimetres
The units (mm) disappear out the right hand end of the box… At first I thought I had Sketched a model with Meter dimensions.

The box with dimension does not expand to fit the number of characters.

### Steps to reproduce

Draw a line
Dimension it over 99mm with 6 decimal places accuracy set 

### Expected behavior

Expect full dimension and units to be visible.

### Actual behavior

Already done above 

### Development version About Info (in Safe Mode)

```shell
Done
```

### Last known good version (optional)

```shell
No idea… new to FreeCAD
```

### PR DESCRIPTION
**Pull request by alfrix**
Summary
* fixes #25947 Sketcher OVP hiding the unit
* makes the OVP width dynamic
* both OVP and quantitySpinboxes will take into account if they have an icon or not when calculating it's space
* both OVP and quantitySpinboxes will take into account number of decimals configured when calculating it's space

### CODE REVIEW

**Comment by alfrix** [comment]
force-pushed to merge the pre-commit fixes (yes i forgot to run install, should be good now)

**Comment by chennes** [comment]
@pieterhijma will test

**Comment by pieterhijma** [comment]
I've tested it. I may not be entirely sure how this is supposed to work, but I believe that it doesn't work for my case. The units still get pushed out of the window:

screenshot_002

**Comment by alfrix** [comment]
> I've tested it. I may not be entirely sure how this is supposed to work, but I believe that it doesn't work for my case. The units still get pushed out of the window:
> screenshot_002

that is weird, if you have 6 decimals configured then there should be at least 12 chars of space and you have 9 (the point has a small width), the question is do you have 6 decimals configured or is there another thing affecting this? other than that maybe you need a clean build?

**Comment by pieterhijma** [comment]
Ah ok, I changed the value to 6 decimals but apparently I didn't press apply. When I got back to the preferences it was still 2 decimals.

Although I think this is a mitigation, I don't think it fixes the issue. In general I think there are better ways to fix this and "nr of decimals" is a bit unclear in the preferences, because with this PR it seems as if we define a tolerance here. I would find it very natural to have FreeCAD *display* 2 decimals, but I would expect to be able to use more decimals than that.

The OVP doesn't allow me to use more than the number of specified displays because it can drop the unit as [this comment](https://github.com/FreeCAD/FreeCAD/issues/25947#issuecomment-3619652543) also mentions.

So, I think the real issue of #25947 is:

Sketcher OVP drops units when using more decimals than specified. 

I think the answer cannot be: "You have to specify that you want to use more decimals" because that feels to me as if you are not allowed to input more decimals than was specified and it becomes more like specifying a tolerance.

**Comment by alfrix** [comment]
if users dont want horizontal scrolling then we need to impose a char limit, otherwise you will have to live with that quirk, i've made another commit to set the char limit if you want to test it

**Comment by maxwxyz** [comment]
It does not look right here:
grafik
With maximum decimals the text is not centered too in the box and still has space on the right:
grafik

It also looks weird on all other input boxes and seems to shrink other important info:
grafik


@FreeCAD/design-working-group any feedback?

**Comment by pieterhijma** [comment]
Sorry for the late reaction. I took another look at it as well. Indeed, I agree with Max that it could look better but this solution does solve the original issue.

**Comment by alfrix** [comment]
>  With maximum decimals the text is not centered too in the box and still has space on the right:

the text is always align left on main, if it's wanted i can add center alignment

**Comment by maxwxyz** [comment]
IMO alignment is not an issue but those huge input boxes and they somehow mess up the UI in dialogs or task panels. Is it possible to make the width dynamically based on the decimal point preference of the user?

**Comment by kadet1090** [comment]
> It does not look right here: grafik With maximum decimals the text is not centered too in the box and still has space on the right: grafik
> 
> It also looks weird on all other input boxes and seems to shrink other important info: grafik
> 
> @FreeCAD/design-working-group any feedback?

I do agree that this is major impact in terms of UI and UX. If possible form controls should be close in width to expected input size - in this case however we are leaving way too much space which won't be ever utilized which looks like a mistake. Merging the PR in this state will result in degraded user experience. We should implement more dynamic approach before merging.

**Comment by maxwxyz** [comment]
Moving to 1.2 for now - let me know otherwise.

**Comment by alfrix** [comment]
i've just added the centering to the sketcher ovp, it should make the unused space more natural

image

**Comment by kadet1090** [comment]
> i've just added the centering to the sketcher ovp, it should make the unused space more natural
> image

That's not what we were after. The problem is not with alignment but with size of the input

**Comment by alfrix** [comment]
i've been testing the behavior of the different version, here is the recap

**Notes for 1.0.2**
**Sketcher OVP behaviour**
allowed to enter 10 numbers in the ovp, regardless of decimals just 10 numbers
char limit is not enforced aka you can put unlimited dots and commas 
other misc siimbols {}[] are allowed and will break the input (not able to delete afterwards)
Unit will be hidden or partially hidden if too many chars are typed
Unit will be hidden if more than 15 decimals are configured

**Taskpanel QuantitySpinboxes:**
unlimited chars, they will get behind the icon
Unit will be hidden or partially hidden if too many chars are typed
Unit will be hidden if a lot of decimals are configured (depends on taskpanel width)

**Notes for 1.1rc1**
**Sketcher OVP behaviour**
unlimited chars
Unit will be hidden or partially hidden if too many chars are typed
Unit will be hidden if more than 7 decimals are configured

**Taskpanel QuantitySpinboxes:**
unlimited chars
Unit will be hidden or partially hidden if too many chars are typed
Unit will be hidden if a lot of decimals are configured (depends on taskpanel width)

**Notes for the PR**
**Both Sketcher OVP and Taskpanel QuantitySpinboxes:**
limited chars calculated to 5+.+decimals+space+unit
a number like "12345.67 mm" will be auto converted on accept to "12.34 m", generally up-to 9999 is accepted as input but 10000 will be elevated to the next unit, so allowing 5 or maybe 6 base digits should be ok
increasing the number of decimals in the config will increase the max chars allowed
unit is never cut, minimum size of the spinbox is enforced

**Comment by alfrix** [comment]
> > i've just added the centering to the sketcher ovp, it should make the unused space more natural
> > image
> 
> That's not what we were after. The problem is not with alignment but with size of the input

triggering sizeHint recalculation on user input may be costly in terms of performance and i'm not fully sure it's doable

**Comment by alfrix** [comment]
and dinamically rezing quantity spinboxes will mean that as the user is typing in more numbers the taskpanel will grow wider? are you sure that is good ux? maybe for the ovp up to a certain point it makes sense, but we are talking about an extra space of 4 chars, it's not a huge amount...

**Comment by kadet1090** [comment]
Let's consider what is expected input for such spin box. 

Right now the PR assumes that it should hint for size of 5 digits + configured decimals + space and comma + unit. I'd that the logic here is fine, but the number of digits chosen (5) seems to be really excessive - how many times do you actually use 5 digits before comma? For most cases it would trigger unit change. I'd say aiming for 3 or even 2 should be good enough - at least for metric. The length could also be dependent on the unit system chosen and derived from that - as for metric and imperial that could differ. 

Another thing to consider is to split minimum size hint from size hint - the minimum size hint really should hint for the minimum viable space required (which should be 2 digits) and then size hint could be bigger (3-4?). 

We also have two separate scenarios to consider: 

1. For inputs that are unconstrained in horizontal space (i.e. OVPs) it should always use the minimum possible space and expand with user input adjusting so it shows everything user needs. If users wants to see `20.00000 mm` - that is their choice and it should be respected and should not be cut off. We should not however force more typical scenarios that will have `20.00 mm` to have wasted space and inflated inputs for no reason.

2. For task panel we obviously don't want layout changing on typing but in that case the layout is constrained to the task panel size (it is filling all available horizontal space). The only thing that we need to worry about is having some sane (minimum) size hints that would allow the dialog to behave correctly. In general, for default settings, we should aim for the dialog to work at default size of 400px (ideally even 350px) and we cannot force it to be bigger if it's not absolutely necessary - which in this case it is not. Again - if user wants to see  `20.0000000 mm` - we can expand the minimum width and hence the dialog, but it should  affect only users who do want so much precision and they are willing to trade some space for it - which I presume won't be too many people (but they are still important, of course).

In current version for 400px the dialog small inputs can fit 10 digits safely - which should be absolutely fine for almost all usecases. After merging that PR the hole dialog becomes cut out with default settings without the need to do so - which should not happen.

image

Requiring so much precision like in the issue discussion is an edge case - important one but still an edge case. We cannot make default experience worse because of edge cases.

**Comment by alfrix** [comment]
@kadet1090 i think it's done, wasn't easy

**Comment by kadet1090** [comment]
@alfrix thanks looks good. I have few minor remarks about code - do you mind if I fix them myself and push it as commit to your PR? Mostly nitpicks like rearranging properties, addition of setters and compilation errors due to https://github.com/FreeCAD/FreeCAD/issues/26294

Here is the commit with changes: https://github.com/FreeCAD/FreeCAD/commit/2a7ee86ed23be2c63138d33bedf98bc9c54cb645

@maxwxyz can you test it too?

File: src/Gui/QuantitySpinBox.cpp [hunk 1]
```diff
@@ -910,44 +920,53 @@ QSize QuantitySpinBox::sizeForText(const QString& txt) const
...
-    return sizeHintCalculator(lineEdit()->sizeHint().height());
-}
-
-QSize QuantitySpinBox::minimumSizeHint() const
-{
-    return sizeHintCalculator(lineEdit()->minimumSizeHint().height());
+    if (auto le = lineEdit()) {
+        // limit number of typed characters to keep unit visible
+        le->setMaxLength(getMaxStrLength());
+    }
```
Comment (kadet1090) [inline src/Gui/QuantitySpinBox.cpp]: I don't think that adding arbitrary limitations for the input size is a good thing - not seeing the unit is better than not being able to input it.

Comment (alfrix) [reply src/Gui/QuantitySpinBox.cpp]: but this pr goal was to keep the unit visible and fix https://github.com/FreeCAD/FreeCAD/issues/25947

**Comment by alfrix** [comment]
> @alfrix thanks looks good. I have few minor remarks about code - do you mind if I fix them myself and push it as commit to your PR? Mostly nitpicks like rearranging properties, addition of setters and compilation errors due to #26294
> 
> Here is the commit with changes: [2a7ee86](https://github.com/FreeCAD/FreeCAD/commit/2a7ee86ed23be2c63138d33bedf98bc9c54cb645)
> 
> @maxwxyz can you test it too?

sure you can push changes, seems cleaner but if you remove setMaxLength then you will not be fixing the issue linked

File: src/Gui/QuantitySpinBox.cpp (hunk 1 above)
Comment (kadet1090) [reply src/Gui/QuantitySpinBox.cpp]: We cannot keep unit visible by limiting users from being able to input things.

Comment (kadet1090) [reply src/Gui/QuantitySpinBox.cpp]: I see it like that. For OVPs where user does not have direct control over input width the issue is fixed as the input size is dynamic. For other dialogs the input size is dependent on dialog width - if there is not enough space for given person they can simply resize the dialog and it will be working fine.

Comment (alfrix) [reply src/Gui/QuantitySpinBox.cpp]: in the last commits  i've implemented the max chars **only for the OVP** since the width adjust some limit needs to be implemented, i've set a relaxed 16 digits which should be plenty but it can be simply increased if needed
16 digits + separator + 2 to 16 decimals, + space + unit 
makes a range of aproximately 18 to 32 numbers depending on config

**Comment by maxwxyz** [comment]
Did something change with the last commits?

**Comment by alfrix** [comment]
> Did something change with the last commits?

i've added 2 commits since you last tested
one to address the issue of jumping behind the unit that you mentioned
another to allow more chars in the ovp (although with a limit) and removed the limit in the taskpanel qspinbox
the taskpanel still benefits on more accurate size calculation, and increased minimum size if the user augments the decimals by default.

**Comment by ElementW** [comment]
Unfortunately this broke OVPs outright.
* #29248
