### PR TITLE
Fix Polar Pattern task panel labels

### LINKED ISSUE #25467: PartDesign: Angle input fields in Polar Pattern task panel are labeled 'Length' or 'Spacing'
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Problem description

The angle input fields in Polar Pattern task panel are labeled 'Length' or 'Spacing'. This is probably because the task panel uses the same elements as the Linear Pattern feature task panel. The mode options ('Extent' and 'Spacing') are also awkward for angles IMO.

### Full version info

```shell
v1.1
```

### Subproject(s) affected?

PartDesign

### Anything else?

_No response_

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by rehan-ahmed-aix**
## Issues
Fixes #25467 

### Before:

screenshot-2026-04-01_16-51-28
screenshot-2026-04-01_16-52-10

### After:

screenshot-2026-04-01_16-33-41
screenshot-2026-04-01_16-32-46

### CODE REVIEW

**Review by PaddleStroke — APPROVED** [review]

File: src/Mod/Part/Gui/PatternParametersWidget.cpp [hunk 1]
```diff
@@ -67,6 +67,10 @@ void PatternParametersWidget::setupUiElements()
 
     if (type == PatternType::Polar) {
         setTitle(tr("Axis"));
+        ui->comboMode->setItemText(0, tr("Total Angle"));
+        ui->comboMode->setItemText(1, tr("Angular Spacing"));
+        ui->labelLength->setText(tr("Total Angle"));
+        ui->labelOffset->setText(tr("Angular Spacing"));
```
Comment (maxwxyz) [inline src/Mod/Part/Gui/PatternParametersWidget.cpp:73]:
```suggestion
        ui->labelLength->setText(tr("Total angle"));
        ui->labelOffset->setText(tr("Angular spacing"));
```

Field labels use sentence case (capitalize only the first word). The combo items above are selectable modes (analogous to menu items) and correctly use title case.

**Review by maxwxyz — APPROVED** [review]
Tested
