### PR TITLE
Start: fix thumbnail generation causing QPixmap::resize errors

### LINKED ISSUE #29397: Core: QPixmap is a null pixmap on windows11 and no example file preview  when opening FC
### Problem description

Image

### Workbench affected?

Core (App, Gui,...)

### Steps to reproduce

*

### Expected behavior

*

### Actual behavior

*

### Development version About Info (in Safe Mode)

```shell
OS: Windows 11 build 26200
Architecture: x86_64
Version: 1.2.0dev.20260415 (Git shallow)
Build date: 2026/04/15 00:45:21
Build type: Release
Branch: (HEAD detached at 36786d479)
Hash: 36786d47949a449b3a8585354ef8c75a1c67c03b
Python 3.11.15, Qt 6.8.3, Coin 4.0.8, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.3.0, IfcOpenShell 0.8.2, OCC 7.8.1
Locale: Turkish/Türkiye (tr_TR) [ OS: Turkish/Türkiye (tr_TR) ]
Stylesheet/Theme/QtStyle: FreeCAD.qss/FreeCAD Dark/
Navigation Style/Orbit Style/Rotation Mode: Blender/Rounded Arcball/Window center
Logical DPI/Physical DPI/Pixel Ratio: 96/81.5973/1
Installed mods:
  * Curves workbench 0.6.70
```

### Last known good version (optional)

```shell

```

### PR DESCRIPTION
**Pull request by ElementW**
* Fixes #29397

1. `DisplayedFilesModel::addFile()` had a logic error where 3D thumbnail generation would still try to run for FCStd files, although it would immediately fail.
2. Windows does what Windoes best and its `std::ostringstream` mangles `'\n'` bytes if not preceded by `'\r'` within `operator>>` which `App::ProjectFile` & zipios++ use. This caused QPixmap loading to fail as the PNG files were corrupted. Switch to `Base::StringOStreambuf` or `std::spanstream` if available to avoid that.
3. Always fall back to a placeholder/QImageReader/system thumbnail if the main thumbnail loading process failed.

### CODE REVIEW

**Comment by chennes** [comment]
I didn't even know about `std::spanstream` -- thanks for that. Alas, clang libc++ doesn't support it yet. https://libcxx.llvm.org/Status/Cxx23.html (it's [P0448R4](https://wg21.link/P0448R4) in that list).

**Comment by ElementW** [comment]
I went looking for a `std::spanbuf` equivalent in `<Base/Stream.h>` but didn't find any so I just decided to `#if` my way to the zero-copy instead, as subpar as that is. I'm also absolutely floored it took C++ some 30+ years to finally have a standard fixed memory buffer `streambuf`.

**Comment by FEA-eng** [comment]
CI failed.

I can confirm that it removes the warnings, but the thumbnails are not shown for me:

image

**Comment by ElementW** [comment]
@FEA-eng Go clear the corrupted thumbnails in `%LocalAppData%\cache\FreeCADStartThumbnails` and try again. If it still fails then I've done something wrong.

CI failure is not my fault, I haven't touched anything that would make `ccache` be not found.

**Comment by chennes** [comment]
Ci is failing project-wide right now, it appears that something in `apt install` is borked right now.

**Comment by FEA-eng** [comment]
> Go clear the corrupted thumbnails in `%LocalAppData%\cache\FreeCADStartThumbnails` and try again. If it still fails then I've done something wrong.

Now it works, thanks.

**Review by FEA-eng — APPROVED** [review]
@maxwxyz Tested, fixes the issue.

**Comment by ElementW** [comment]
I think I'll improve the logic a bit. The `QAbstractDataModel` that's built contains the bytes of the encoded thumbnail, and it's decoded every time it's drawn in `FileCardDelegate::paint()`, moving the decoding to the data model seems like a good idea. And in so doing if loading the image fails there I can just delete the cached file as it's guaranteed to not be useful, irrespective of the reason why it's corrupt.

EDIT: that'll be in another PR, to keep this one simple.

File: src/Mod/Start/App/FcstdInfoSource.cpp [hunk 1]
```diff
@@ -23,7 +23,11 @@
 
 #include "FcstdInfoSource.h"
 
-#include <sstream>
+#if __cplusplus >= 202302L
```
Comment (chennes) [inline src/Mod/Start/App/FcstdInfoSource.cpp:26]: I'd suggest that
```suggestion
#if __has_include(<spanstream>)
```
is the better approach here.

File: src/Base/Stream.h [hunk 2]
```diff
@@ -423,6 +425,100 @@ class BaseExport StringIStreambuf: public std::streambuf
     int _beg, _end, _cur;
 };
 
+/**
+ * Streambuf for reading/writing to a fixed memory buffer.
+ * Equivalent in functionality to C++23 std::spanbuf.
+ */
+class BaseExport
+#if __cplusplus >= 202302L
+    [[deprecated("Use std::spanbuf wrapped in a \"#if __cplusplus >= 202302L\" condition instead")]]
```
Comment (chennes) [inline src/Base/Stream.h:434]: Same as other suggestion

**Review by chennes — COMMENTED** [review]
One minor issue (below), and a suggestion: this is the sort of code that really should have a set of unit tests attached to it. I know it's nearly already obsolete code, but if you have time, consider adding a set of gtest-based unit tests that actually exercise all of the functionality in your streambuf replacement class.

File: src/Mod/Start/App/FcstdInfoSource.cpp (hunk 1 above)
Comment (ElementW) [reply src/Mod/Start/App/FcstdInfoSource.cpp]: Actually the correct approach is `#ifdef __cpp_lib_spanstream`, as `<spanstream>` may exist as a file (on modern GCC for instance) but compiling as C++20 makes it effectively pre-process to empty.

**Comment by ElementW** [comment]
Added tests. It's not exhaustive as I did not test `iostream` only `istream` and `ostream` but the likelihood of using the former on a `BufferStreambuf` is pretty low.

**Comment by ElementW** [comment]
clang-analyzer was being choosy about `NOLINTBEGIN` and `NOLINTEND`, where my impl follows what the C++ standard says and should be excluded from type cast and pointer arithmetic warnings. They should now be gone.

**Comment by FEA-eng** [comment]
There is some CI failure, but it might be global.
