### PR TITLE
Fix Linux SpaceMouse performance: event coalescing, camera batching, per-axis deadzone

### LINKED ISSUE #25926: Lag when moving a standard mouse and a SpaceMouse at the same time
### Problem description

I received this bug report from the team at 3Dconnexion:

"We found that navigation is lagged when 2D mouse is moved during navigation with SpaceMouse for complicated objects."

### Steps to reproduce

With the attached file open:

[Assembly test.FCStd.zip](https://github.com/user-attachments/files/23912870/Assembly.test.FCStd.zip)

1. Zoom a bit to the complicated object
2. Navigate around the rounded object with SM
3. Start moving CM at the same time.
4. Repeat steps 1/2 if the issue doesn't occur

### Expected behavior

No lag

### Actual behavior

Lag, as shown in the attached video.

https://github.com/user-attachments/assets/231f72d6-6e60-429d-bc8f-58f9dab34f0a

### Development version About Info (in Safe Mode)

```shell
OS: macOS 15.7.1
Architecture: arm64
Version: 1.2.0dev.44466 (Git)
Build date: 2025/12/01 20:52:48
Build type: Unknown
Branch: patch-369907
Hash: 41e072e548ce5423e1fbfd77890fa6ae34b1ee91
Python 3.11.13, Qt 6.8.3, Coin 4.0.3, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.3.0, IfcOpenShell 0.8.0, OCC 7.8.1
Locale: English/United States (en_US)
Navigation Style/Orbit Style/Rotation Mode: Gesture/Trackball/Drag at cursor
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Dark/
Logical DPI/Physical DPI/Pixel Ratio: 72/127.5/2
```

### PR DESCRIPTION
**Pull request by Maik-0000FF**
## Summary

Linux SpaceMouse (spnav) navigation is jerky and unresponsive, especially on complex models. This is caused by two performance issues in the event pipeline and a missing feature:

1. **No event coalescing** — `pollSpacenav()` posts every spnav motion event individually (125-250Hz from spacenavd), each triggering a full scene redraw
2. **Double redraws** — `camera->orientation` and `camera->position` each trigger separate Coin3D scene graph notifications
3. **No per-axis deadzone** — sensor noise causes unintended drift with no way to filter individual axes

On Windows/macOS, NavLib handles coalescing and deadzone internally. On Linux (where NavLib is unavailable), the raw spnav pipeline has none of this.

### Commit 1: Event coalescing + camera batching (performance fix)

**GuiNativeEventLinux.cpp** — The drain loop now keeps only the latest motion state and posts once after all pending events are consumed. SpaceMouse events are absolute deflection (current puck position), not deltas, so the latest event always contains the complete state.

**NavigationStyle.cpp** — Camera property changes are wrapped in `enableNotify(false/true)` + `touch()` so Coin3D fires a single redraw instead of two per event.

Together this reduces redraws from ~500/sec to ~60/sec.

### Commit 2: Per-axis deadzone filtering

**GuiNativeEventLinux.cpp** — Reads per-axis deadzone thresholds from `user.cfg` (`BaseApp/Spaceball/Motion/{Axis}Deadzone`) and zeros axis values below their threshold before posting. Each axis (PanLR, PanUD, Zoom, Tilt, Roll, Spin) can be configured independently. Values default to 0 (no filtering). This is the Linux equivalent of the deadzone handling that NavLib provides on Windows/macOS.

## Testing

Tested on Arch Linux (KDE Plasma Wayland) with:
- SpaceNavigator (046d:c626) via spacenavd 1.3.1 / libspnav 1.2
- FreeCAD 1.0.2 and current main
- Complex models (>50k faces) where the jerkiness was most noticeable

Before: jerky, laggy navigation with visible stuttering on puck release
After: smooth, responsive 60fps navigation, instant stop on puck release

### Per-axis deadzone configuration

The deadzone values can be configured via **Tools → Edit Parameters**, navigate to `BaseApp/Spaceball/Motion`:

| Parameter | Axis | Type | Range |
|-----------|------|------|-------|
| `PanLRDeadzone` | Pan Left/Right | Integer | 0–350 |
| `PanUDDeadzone` | Pan Up/Down | Integer | 0–350 |
| `ZoomDeadzone` | Zoom In/Out | Integer | 0–350 |
| `TiltDeadzone` | Tilt Forward/Back | Integer | 0–350 |
| `RollDeadzone` | Roll Left/Right | Integer | 0–350 |
| `SpinDeadzone` | Spin CW/CCW | Integer | 0–350 |

A value of **100–150** works well as a starting point — small unintentional movements are filtered out while normal navigation feels natural. Setting it to **0** (or omitting the parameter) disables the deadzone for that axis. Values update live via Observer — no restart needed.

## Fixes

Fixes #25926 (Lag when moving standard mouse and SpaceMouse simultaneously)
Relates to #17521 (Spacemouse speed problem)

### CODE REVIEW

File: src/Gui/3Dconnexion/GuiNativeEventLinux.cpp [hunk 1]
```diff
@@ -85,6 +87,28 @@ void Gui::GuiNativeEvent::pollSpacenav()
             }
         }
     }
+    if (hasMotion) {
+        // Per-axis deadzone: zero out axes below their individual threshold.
+        // Configured via user.cfg BaseApp/Spaceball/Motion/{Axis}Deadzone.
+        static const char* axisDeadzoneKeys[] = {
```
Comment (hyarion) [inline src/Gui/3Dconnexion/GuiNativeEventLinux.cpp]: If you use std::array instead, you can use size instead of hardcoding a magic number

File: src/Gui/3Dconnexion/GuiNativeEventLinux.cpp [hunk 2]
```diff
@@ -85,6 +88,28 @@ void Gui::GuiNativeEvent::pollSpacenav()
...
+            "TiltDeadzone",
+            "RollDeadzone",
+            "SpinDeadzone"
+        };
+        auto hGrp = App::GetApplication().GetParameterGroupByPath(
+            "User parameter:BaseApp/Spaceball/Motion"
+        );
+        for (size_t i = 0; i < axisDeadzoneKeys.size(); i++) {
+            int dz = static_cast<int>(hGrp->GetInt(axisDeadzoneKeys[i], 0));
+            if (dz > 0 && motionDataArray[i] > -dz && motionDataArray[i] < dz) {
```
Comment (hyarion) [inline src/Gui/3Dconnexion/GuiNativeEventLinux.cpp]: Nit: this could be simplified to `std::abs(motionDataArray[i]) < dz` for readability (with `#include <cstdlib>` or `<cmath>`).

File: src/Gui/3Dconnexion/GuiNativeEventLinux.cpp [hunk 3]
```diff
@@ -85,6 +88,28 @@ void Gui::GuiNativeEvent::pollSpacenav()
             }
         }
     }
+    if (hasMotion) {
+        // Per-axis deadzone: zero out axes below their individual threshold.
+        // Configured via user.cfg BaseApp/Spaceball/Motion/{Axis}Deadzone.
+        static const std::array<const char*, 6> axisDeadzoneKeys = {
```
Comment (hyarion) [inline src/Gui/3Dconnexion/GuiNativeEventLinux.cpp]: Since these are all compile-time constants.

```suggestion
        static constexpr std::array<const char*, 6> axisDeadzoneKeys = {
```

File: src/Gui/3Dconnexion/GuiNativeEventLinux.cpp [hunk 4]
```diff
@@ -85,6 +88,28 @@ void Gui::GuiNativeEvent::pollSpacenav()
...
+            "ZoomDeadzone",
+            "TiltDeadzone",
+            "RollDeadzone",
+            "SpinDeadzone"
+        };
+        auto hGrp = App::GetApplication().GetParameterGroupByPath(
+            "User parameter:BaseApp/Spaceball/Motion"
+        );
+        for (size_t i = 0; i < axisDeadzoneKeys.size(); i++) {
+            int dz = static_cast<int>(hGrp->GetInt(axisDeadzoneKeys[i], 0));
```
Comment (hyarion) [inline src/Gui/3Dconnexion/GuiNativeEventLinux.cpp]: Do we have to poll these values at 60Hz? Can't we cache them instead and/or use an observer?

File: src/Gui/3Dconnexion/GuiNativeEventLinux.cpp (hunk 3 above)
Comment (Maik-0000FF) [reply src/Gui/3Dconnexion/GuiNativeEventLinux.cpp]: Done, good catch.

File: src/Gui/3Dconnexion/GuiNativeEventLinux.cpp (hunk 4 above)
Comment (Maik-0000FF) [reply src/Gui/3Dconnexion/GuiNativeEventLinux.cpp]: Great suggestion. Replaced with a static DeadzoneCache that loads values once at first use and subscribes via ParameterGrp::ObserverType — OnChange updates only the affected axis when user.cfg is modified. No more per-event lookups.

File: src/Gui/3Dconnexion/GuiNativeEventLinux.cpp (hunk 2 above)
Comment (Maik-0000FF) [reply src/Gui/3Dconnexion/GuiNativeEventLinux.cpp]: Done, much cleaner — thanks.

File: src/Gui/3Dconnexion/GuiNativeEventLinux.cpp [hunk 5]
```diff
@@ -85,6 +144,20 @@ void Gui::GuiNativeEvent::pollSpacenav()
             }
         }
     }
+    if (hasMotion) {
+        // Per-axis deadzone: zero out axes below their individual threshold.
+        // Values cached and auto-updated via Observer when user.cfg changes.
+        static DeadzoneCache dzCache(
+            App::GetApplication().GetParameterGroupByPath("User parameter:BaseApp/Spaceball/Motion")
+        );
```
Comment (hyarion) [inline src/Gui/3Dconnexion/GuiNativeEventLinux.cpp]: It feels like a bit of a hack to have it stored in a static.
Wouldn't it be better to set up the observer in the constructor instead?

Comment (Maik-0000FF) [reply src/Gui/3Dconnexion/GuiNativeEventLinux.cpp]: Good point — done. Moved `DeadzoneCache` to a `std::unique_ptr` member of `GuiNativeEvent`, created in `initSpaceball()` after the spnav connection succeeds. Forward-declared in the header to keep includes minimal.

This also makes the lifetime explicit: the observer is only alive while the spacenav connection exists, and gets cleaned up automatically with the `GuiNativeEvent` instance.

**Review by hyarion — APPROVED** [review]

**Comment by hyarion** [comment]
@chennes IIRC you have a 3d-space-puck-thingy and linux, could you give this a spin?

**Comment by tchilov** [comment]
Thank you so much for your contribution, this is exactly what I needed and it's a joy to use it.

> ### Per-axis deadzone configuration
> The deadzone values can be configured via **Tools → Edit Parameters**, navigate to `BaseApp/Spaceball/Motion`:
> 
> Parameter	Axis	Type	Range
> `PanLRDeadzone`	Pan Left/Right	Integer	0–350
> `PanUDDeadzone`	Pan Up/Down	Integer	0–350
> `ZoomDeadzone`	Zoom In/Out	Integer	0–350
> `TiltDeadzone`	Tilt Forward/Back	Integer	0–350
> `RollDeadzone`	Roll Left/Right	Integer	0–350
> `SpinDeadzone`	Spin CW/CCW	Integer	0–350
> A value of **100–150** works well as a starting point — small unintentional movements are filtered out while normal navigation feels natural. Setting it to **0** (or omitting the parameter) disables the deadzone for that axis. Values update live via Observer — no restart needed.

YMMV of course, but on my SpaceNavigator USB, I've set all deadzone values to 20. 100 was too high and felt very snappy. Also, I had to enable Flip Y/Z to make it feel natural.
