### PR TITLE
Gui/App: Add error checking to config migration

### LINKED ISSUE #28627: Windows: Stable 1.1 crash on startup. Every time. Unusable. Windows 10
### Problem description

I just downloaded 1.1 stable from the official page.
When started it displays the usual FreeCAD splash (hardly that, it's always there far too long for that term to have any meaning) screen.
It then whites out the entire screen (this is normal) and displays a dialogue for about half a millisecond.
And then it's gone.

After several attempts with OBS Studio, I was able to record the dialogue, then screen print it. Here it is.

Image

### Workbench affected?

None

### Steps to reproduce

na

### Expected behavior

na

### Actual behavior

na

### Development version About Info (in Safe Mode)

```shell
na
```

### Last known good version (optional)

```shell

```

### PR DESCRIPTION
**Pull request by chennes**
Fixes #28627 (and backported for 1.1.1). The code that handles the migration of one config directory to a new one lacks error handling. If there are broken symlinks, permissions problems, etc. with files in `userAppDataDir` or `configDir`, unhandled exceptions could propagate out, go into Qt code, and crash FreeCAD during startup. This PR adds relatively aggressive error handling and logging to the migration code to prevent the crash, as well as tell the user exactly which files were causing problems. Includes tests for the non-GUI changes.

ETA: test builds of this PR are available here -- https://github.com/chennes/FreeCAD/releases/tag/test-for-issue-28627

### CODE REVIEW

File: src/App/ApplicationDirectories.h [hunk 1]
```diff
@@ -133,8 +133,8 @@ namespace App {
         /// If the old paths are themselves versioned, then the new paths will be placed at the same
         /// level in the directory structure (e.g., they will be siblings of each entry in paths).
         /// If paths are NOT versioned, the new (versioned) copies will be placed *inside* the
-        /// original paths.
-        void migrateAllPaths(const std::vector<std::filesystem::path> &paths) const;
```
Comment (kadet1090) [inline src/App/ApplicationDirectories.h:137]: Not a fan of that return result. People do not read documentation and if you see `std::vector<std::string> migrate(...)` the things that were NOT migrated are not what first comes to mind. Not that someone else would use that method anyway but...

I'd probably wrap it with some struct like `MigrationResult` and give it field with state (so success, partial, fail?) and errored paths. That way it would be way easier to understand.

Also, why not returning vector of std::filesystem::path?

Comment (chennes) [reply src/App/ApplicationDirectories.h:137]: I don't want to return the complete list of migrated files because it can be enormous, and won't be used for anything. I can make the struct but it will basically just a nicer name for the return type.

Regarding the string return: I was already doing the string conversion for the console printing and didn't want to duplicate the conversion calls. Not a hill I will die on though, I can change it if you want.

Comment (kadet1090) [reply src/App/ApplicationDirectories.h:137]: I don't think that returning the complete list of migrated files is reasonable either. As for struct being basically nice name - giving nice names for return types is great. It expresses intent (the first thing written in core guidelines), which in that context is not clear and relies only on the comment. 

I don't see a problem with std::string, asked mostly out of curiosity. 

That said - not a hill I'll die on either.
