### PR TITLE
App: Random fixes 2

### LINKED ISSUE #18044: Core: Recovery files ignored if project file modification date is newer, even if crash corrupted the project file
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

After hours of work on a pretty simple model with the 1.0 release on Linux, FC crashed with a SIGSEGV. That happened before and I thought I might have lost a couple of minutes since my last save. Restarting FC gave the following on the console:
```
FreeCAD 1.0.0, Libs: 1.0.0R39109 (Git)
(C) 2001-2024 FreeCAD contributors
FreeCAD is free and open-source software licensed under the terms of LGPL2+ license.

Ignore recovery file  "/home/axel/.cache/FreeCAD/Cache/FreeCAD_Doc_5b799e8d-5c96-4109-9b9d-7b1098506e98_9ed579_617729/fc_recovery_file.fcstd"  because it is older than the project file "/home/axel/Downloads/DieFr\xC3\xA4se.FCStd" 

Fatal Error at file /home/axel/Downloads/DieFräse.FCStd, line 155, char 27
Invalid Document.xml: unexpected end of input
Fatal Error at file GuiDocument.xml, line 1, char 1
Exception message is: 
invalid document structure
Reading failed from embedded file: GuiDocument.xml (0 bytes, 2 bytes compressed)
```
So I ended up with an empty project and by the time I noticed what happened, the `*.FCBak` file as well as the recovery file from the cache have been overridden with the empty file as well. So all my work was gone. This is **bad**.

Independent of the crash itself, which might have happened when I pressed save or something else, I don't remember, I would think that dismissing the recovery from a backup file only based on the timestamp is not good and the decision has to be deferred until after the file has been successfully loaded. And if that did not work, then doing a recovery is the only sensible approach.

To reproduce this issues, simply open any project, do some work until a recovery file is written to the cache. Then kill the FC process and manually corrupt the project file, e.g. truncate it. Start FC again, open the corrupted file and see what happens.

### Full version info

```shell
OS: Ubuntu 24.04.1 LTS (ubuntu:GNOME/ubuntu/xcb)
Architecture: x86_64
Version: 1.0.0.39109 (Git) Conda AppImage
Build type: Release
Branch: (HEAD detached at 1.0.0)
Hash: 2fcc5317fe3aee96ca73475986a577719fc78e20
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Dark/Fusion
Installed mods: 
  * Defeaturing 1.2.2
  * A2plus 0.4.68
```

### Subproject(s) affected?

None

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #18806: PartDesign: Strange behavior Toggle freeze elements of PD body
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Click **Toggle freeze** for body object.
The elements inside are also frozen.
It's not clear how to get everything back.

https://github.com/user-attachments/assets/f6258901-8fad-4edc-8d88-e168f66a5969

Another example.
I get some project with CAM.
Used **Toggle freeze** for body object.
Get frozen elements in project which not so easy to find.
Also can`t save project while some elements frozen

https://github.com/user-attachments/assets/20e8d0b2-6e2c-494e-b187-94792e549ed1

First time i found this problem and I unfreeze all elements inside tree one by one. But now feature **Toggle freeze** disappear for elements inside body.
The result is a dead end from which there is no way out.
The project cannot be saved and the action cannot be undone.

https://github.com/user-attachments/assets/9ba9cccd-ce46-4625-b9f4-23af488caf53

### Full version info

```shell
OS: Arch Linux (KDE/plasma/xcb)
Architecture: x86_64
Version: 1.1.0dev.39741 (Git) Conda AppImage
Build type: Release
Branch: main
Hash: 0d128517dedd154bbecfbabe67094ad56c8d46f5
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Dark/Fusion
Installed mods: lattice2 1.0.0; CurvedShapes 1.0.13; MeshRemodel 1.10.35; freecad.gears 1.3.0; fasteners 0.5.33; sheetmetal 0.6.12; Silk 0.1.5; Curves 0.6.52
```

### Subproject(s) affected?

None

### Anything else?

[VacuumTable.zip](https://github.com/user-attachments/files/18277705/VacuumTable.zip)
[VacuumTable_2024-12-30_19-15-55.zip](https://github.com/user-attachments/files/18277802/VacuumTable_2024-12-30_19-15-55.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by 3x380V**
A continuation of #27243, this time a bit harder to review. Includes fix for #18044, which is marked as closed by #24123, but that improves reading corrupted file, while fix included here improves writer side. Also includes fix for #18806, which is marked as fixed by #20442, but the fix here allows saving frozen object.

All patches courtesy of @wwmayer.

Cc: @chennes, @hyarion,

### CODE REVIEW

File: src/App/Document.cpp [hunk 1]
```diff
@@ -1251,98 +1250,123 @@ constexpr auto fcAttrDepObjName {"Name"};
...
     }
-
     writer.decInd();  // indentation for 'Object name'
-    writer.Stream() << writer.ind() << "</ObjectData>" << '\n';
+
+    writer.Stream() << writer.ind() << "</ObjectData>\n";
+}
+
+void Document::writeObjects(const std::vector<App::DocumentObject*>& obj,
+                            Base::Writer& writer) const
```
Comment (hyarion) [inline src/App/Document.cpp]: Looks good, but how about removing the unnecessary `App::` as we have `using namespace App;` at the top of the file?

File: src/App/DocumentObject.cpp [hunk 2]
```diff
@@ -1170,11 +1170,7 @@ DocumentObject* DocumentObject::getLinkedObject(bool recursive,
 
 void DocumentObject::Save(Base::Writer& writer) const
 {
-    if (this->isFreezed()) {
-        throw Base::AbortException("At least one object is frozen, unable to save.");
-    }
```
Comment (hyarion) [inline src/App/DocumentObject.cpp:1175]: @FlachyJoe any thoughts on this commit? https://github.com/FreeCAD/FreeCAD/pull/27355/changes/6c9ad95a70bf60242826739c84579c62025d4a24 (git shows that you introduced this about a year ago)

File: src/Base/Writer.h [hunk 3]
```diff
@@ -136,7 +136,22 @@ class BaseExport Writer
...
+    /// Set error state flags
+    void clear();
+    /// Check whether state of stream is good
+    bool good() const;
+    /// Check whether either failbit or badbit is set
+    bool fail() const;
+    /// Check whether badbit is set
+    bool bad() const;
+    /// Check whether eofbit is set
+    bool eof() const;
```
Comment (hyarion) [inline src/Base/Writer.h]: The name doesn't seem to follow our own naming convention, instead it follows the one for c++.
As only `fail` is used of these flags, how about just exposing that and naming it `hasFailed()`?

**Review by hyarion — COMMENTED** [review]
Nothing too controversial, I added some thoughts in the code.
I'd like to get @FlachyJoe's input on the freeze change.

We might also want to backport some of these changes.

File: src/App/Document.cpp (hunk 1 above)
Comment (3x380V) [reply src/App/Document.cpp]: Thanks for spotting this. Leftover from conflicts resolution.

File: src/Base/Writer.h (hunk 3 above)
Comment (3x380V) [reply src/Base/Writer.h]: I tried to follow naming convention, but left unused methods there. I prefer not to diverge too much from original work.

File: src/App/DocumentObject.cpp (hunk 2 above)
Comment (FlachyJoe) [reply src/App/DocumentObject.cpp:1175]: I'm ok with this.

**Comment by freecad-ci-runner** [comment]
Backport failed for `releases/FreeCAD-1-1`, because it was unable to cherry-pick the commit(s).

Please cherry-pick the changes locally and resolve any conflicts.
```bash
git fetch origin releases/FreeCAD-1-1
git worktree add -d .worktree/backport-27355-to-releases/FreeCAD-1-1 origin/releases/FreeCAD-1-1
cd .worktree/backport-27355-to-releases/FreeCAD-1-1
git switch --create backport-27355-to-releases/FreeCAD-1-1
git cherry-pick -x 6c9ad95a70bf60242826739c84579c62025d4a24 2c2cdbfe7f94735a377c06f98389f507aed0d8c1 2c3d9e2bb702d35c8c0fe688f69682f614fb09f7 c97f6e5b3f29d9a4f698686ea63067596cf29236 4f116d8de36975ca220eaf4cd75e482062c139f6 cda2b8cbdbd9838335a9cef880d5f7fa8e81e99e
```

**Comment by chennes** [comment]
The backport here isn't going to work as-is because 4f116d8de36975ca220eaf4cd75e482062c139f6 depends on the new ApplicationPy API. If we want to backport it, that will have to be done manually.
