### PR TITLE
Gui: Property editor combobox fix not popping up if the user canceled

### LINKED ISSUE #21675: Strange behavior of the drop-down list element (in properties)
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Problem description

After combining #21567, there was a problem with the behavior of the drop-down lists inside the properties window - if you open the drop-down list and click outside it, you will not be able to open it again until you select another property item. 

In addition, two regressions have occurred:
- it is no longer possible to click on the list and, without releasing the mouse button, bring the pointer to the desired point (previously, when releasing, the point above which the pointer was at that moment was used), now the list will appear only when releasing the button
- lost the ability to scroll through the drop-down list with the mouse wheel, instead of opening it with a mouse click (but in this case, I think this is done intentionally so as not to make it difficult to scroll through properties when there are too many of them)

### Full version info

```shell
OS: Windows 10 build 19044
Architecture: x86_64
Version: 1.1.0dev.41905 (Git)
Build date: 2025/05/30 18:02:58
Build type: Release
Branch: main
Hash: 239a05b242b9162fd7a5ab13dcfa86b097c5ad55
Python 3.11.12, Qt 6.8.3, Coin 4.0.3, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.2.5, IfcOpenShell 0.8.2, OCC 7.8.1
Locale: Russian/Russia (ru_RU)
Navigation Style/Orbit Style/Rotation Mode: Blender/Rounded Arcball/Object center
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Dark/
Logical DPI/Physical DPI/Pixel Ratio: 96/102.299/1
```

### Subproject(s) affected?

None

### Anything else?

_No response_

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by alfrix**
fixes #21675 if the initial popup is canceled and the editor is left active, the combo will popup again-

regarding the regression before you needed a first click to activate the editor, then you can popup the list and hold the click
now the list will popup directly, the amount of clicks i'ts the same so there is no hold needed now, i don't consider this a regression

regarding the scroll on combo, it's incompatible with the approach of clicking an item on the list and directly applying the property directly, if wheel needs to be supported then we need to re-add the click outside to apply.

### CODE REVIEW

**Comment by belinski-roman** [comment]
OK, I'll check it out as soon as it gets into the weekly builds!

File: src/Gui/propertyeditor/PropertyItemDelegate.cpp [hunk 1]
```diff
@@ -129,6 +129,12 @@ bool PropertyItemDelegate::eventFilter(QObject *o, QEvent *ev)
 {
     if (ev->type() == QEvent::FocusOut) {
         auto parentEditor = qobject_cast<PropertyEditor*>(this->parent());
+        auto *comboBox = qobject_cast<QComboBox*>(o);
+        if (comboBox) {
```
Comment (kadet1090) [inline src/Gui/propertyeditor/PropertyItemDelegate.cpp]:
```suggestion
        if (auto* comboBox = qobject_cast<QComboBox*>(o)) {
```

That is slightly better way as the `comboBox` symbol is not visible outside of that if statement and cannot be used unchecked by mistake later.
