### PR TITLE
Core: raise exception when no space left on disk at document save

### LINKED ISSUE #19588: FreeCAD crashes when out of disk space
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Problem description

The place on the disk ended, Freecad restored the project when opening and I, out of habit, pressed Ctrl-S
The project file is now empty, Freecad does not start after such a Crash writes 

```
[big-vl@ho ~]$ freecad
FreeCAD 1.0.0, Libs: 1.0.0RC2R38806 (Git)
(C) 2001-2024 FreeCAD contributors
FreeCAD is free and open-source software licensed under the terms of LGPL2+ license.

Failed to compute left/right minimum bearings for "cursor.pcf"
Failed to compute left/right minimum bearings for "cursor.pcf"
Failed to compute left/right minimum bearings for "cursor.pcf"
Failed to compute left/right minimum bearings for "cursor.pcf"
/usr/include/c++/14.2.1/bits/stl_vector.h:1130: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](size_type) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>; reference = unsigned char&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.
Aborted (core dumped)
```

Logov is not appropriately, I managed to find a file cache, but not for today, it's good that I had a habit of making backups for previous dates, but 3 months of work at 0.

### Full version info

```shell
FreeCAD 1.0.0, Libs: 1.0.0RC2R38806 (Git)
```

### Subproject(s) affected?

None

### Anything else?

_No response_

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by FlachyJoe**
Fix #19588

### CODE REVIEW

File: src/App/Document.cpp [hunk 1]
```diff
@@ -2209,6 +2210,10 @@ bool Document::saveToFile(const char* filename) const
             throw Base::FileException("Failed to write all data to file", tmp);
         }
 
+        if ( errno == ENOSPC){
+            throw Base::FileException("No space left on the disk");
```
Comment (xtemp09) [inline src/App/Document.cpp:2214]: disk → device

File: src/App/Document.cpp [hunk 2]
```diff
@@ -2204,9 +2205,15 @@ bool Document::saveToFile(const char* filename) const
 
         // write additional files
         writer.writeFiles();
-
         if (writer.hasErrors()) {
-            throw Base::FileException("Failed to write all data to file", tmp);
+            // retrieve Writer error strings
+            std::stringstream message;
+            message << "Failed to write all data to file";
```
[the remark this answers is not in the document]
Comment (FlachyJoe) [reply src/App/Document.cpp:2211]: It also mixes languages because `strerror` gives a located error message but FreeCAD exceptions are chosen not to be translated.

@tritao What do you propose instead of space? Even if I keep only `writer.getErrors().front()` it has to be concatenate.

File: src/Base/Writer.cpp [hunk 3]
```diff
@@ -226,8 +226,16 @@ void Writer::addError(const std::string& msg)
...
+bool Writer::hasErrors()
+{
+    switch (errno) {
+        case ENOSPC:  // No space left
+        case EROFS:   // Read only
+        case ENODEV:  // No such device
+        case EACCES:  // Access denied
+            addError(strerror(errno));
+    }
+
```
Comment (chennes) [inline src/Base/Writer.cpp:238]: This feels like an awkward place to put this code: not only do you have to make a very `const`-sounding method into a non-`const`, but it doesn't address the use-case where someone might call `getErrors()` instead of `hasErrors()`.

**Comment by maxwxyz** [comment]
@FlachyJoe ping for feedback

**Comment by FlachyJoe** [comment]
@maxwxyz Thank you for the ping. See you after march the 17th.

File: src/App/Document.cpp [hunk 4]
```diff
@@ -2211,9 +2212,12 @@ bool Document::saveToFile(const char* filename) const
...
         // write additional files
         writer.writeFiles();
-
         if (writer.hasErrors()) {
-            throw Base::FileException("Failed to write all data to file", tmp);
+            // retrieve Writer error strings
+            std::stringstream message;
+            message << "Failed to write all data to file ";
+            message << writer.getErrors().front();
+            throw Base::FileException(message.str().c_str(), tmp);
```
Comment (hyarion) [inline src/App/Document.cpp:2220]: Is this safe? Don’t we get a
