### PR TITLE
PartDesign/Part: prevent chamfer crash on OCC kernel failure

### LINKED ISSUE #27221: Changing VarSet value causes immediate application crash
### Problem description

Modifying existing model with new values causes immediate application crash.

### Workbench affected?

None

### Steps to reproduce

1. Open example project.
2. In VarSet (named Dim) change Handle Length from 80mm to 50mm

[example.FCStd.zip](https://github.com/user-attachments/files/24924436/example.FCStd.zip)

### Expected behavior

No crash

### Actual behavior

Crash

### Development version About Info (in Safe Mode)

```shell
I did try this in safe mode. The info is just not. I originally encountered this issue in 1.1rc2.

OS: Linux Mint 22.3 (X-Cinnamon/cinnamon/xcb)
Architecture: x86_64
Version: 1.2.0dev.20260120 (Git shallow) AppImage
Build date: 2026/01/20 21:54:07
Build type: Release
Branch: (HEAD detached at 9beca43)
Hash: 9beca4363ad327e453ee5a27f737537e31467901
Python 3.11.14, Qt 6.8.3, Coin 4.0.3, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.3.0, IfcOpenShell 0.8.2, OCC 7.8.1
Locale: English/United States (en_US)
Navigation Style/Orbit Style/Rotation Mode: TinkerCAD/Trackball/Drag at cursor
Stylesheet/Theme/QtStyle: FreeCAD.qss/FreeCAD Dark/
Logical DPI/Physical DPI/Pixel Ratio: 96/93.338/2
Installed mods: 
  * fasterners 0.5.38
```

### PR DESCRIPTION
**Pull request by Bojan9597**
Summary

FreeCAD crashes (SIGSEGV) when a VarSet parameter change triggers recomputation of a Chamfer feature with geometry that OCC's chamfer kernel can't handle.

This adds defensive checks before calling OCC and installs a signal handler to convert the hard crash into a handled error, so the chamfer feature is marked as failed with an error message instead of killing the app.

Issues

Fixes #27221

### CODE REVIEW

File: src/Mod/Part/App/FeatureChamfer.cpp [hunk 1]
```diff
@@ -103,6 +104,9 @@ App::DocumentObjectExecReturn* Chamfer::execute()
         }
         Edges.setValues(edges);
 
+#if defined(__GNUC__) && defined(FC_OS_LINUX)
+        Base::SignalException se;
```
Comment (3x380V) [inline src/Mod/Part/App/FeatureChamfer.cpp]: Is there any particular reason not use something similar as in 512cf349f9e620529dd7d05d64783e969b83db78?

**Comment by Bojan9597** [comment]
Thanks for the pointr, wasn't aware of Part::SignalException. Switched to it, which also drops the #if guard since it handles the platform check internally.
