### PR TITLE
Sketcher: Create supplementary angle expression using AST

### LINKED ISSUE #11305: Sketcher: internal sketcher angle calculation fails on units, for example: `atan(0.03)` (Regression(?) in PR #10743)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

This commit causes problems, because it does not honor units correctly leading to error-messages and strange behaviour. Example of error-message:
```
<class 'ArithmeticError'>: Quantity::operator -(): Unit mismatch in minus operation
in expression: 180 - atan(0.03)
in property binding 'Luer#Sketch.Constraints'
<Sketch> SketchObject.cpp(9395): Failed to recompute Luer#Sketch.ExpressionEngine: Quantity::operator -(): Unit mismatch
in minus operation
in expression: 180 - atan(0.03)
in property binding 'Luer#Sketch.Constraints
```
The PR https://github.com/FreeCAD/FreeCAD/pull/10743 determines if an expression has a proper unit by searching for ‘°’, ‘deg’ or ’rad’. This does not work in some cases. Example: `atan(0.03)` returns an angle with proper unit, even there is no ‘`°`’, ‘`rad`’ or ‘`deg`’.
also see: https://forum.freecad.org/viewtopic.php?t=82458 (german)

@howie-j 

### Full version info

```shell
OS: Debian GNU/Linux 12 (bookworm) (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.34878 +2 (Git)
Build type: Release
Branch: Meins
Hash: f0b36b0fcac6bf9b7318c14b006146effe97819b
Python 3.11.2, Qt 5.15.8, Coin 4.0.0, Vtk 9.1.0, OCC 7.7.2
Locale: German/Germany (de_DE)
Installed mods: 
  * Curves 0.6.14
  * Assembly4 0.50.4
  * Pyramids-and-Polyhedrons
  * sheetmetal 0.3.1
  * Silk 0.1.5
  * CurvedShapes 1.0.5
  * DynamicData 2.53.0
  * FreeCAD_assembly3 0.11.3
  * fcgear 1.0.0
  * ExplodedAssembly
  * A2plus 0.4.60n
  * fasteners 0.4.70
  * Render 2023.8.18
```

### Subproject(s) affected?

Sketcher

### Anything else?

_No response_

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by andershol**
Fixes #11305
Evaluates the expression to check if it is unit-less or has an angle unit, instead of doing string comparison. Uses the expressions AST to check for the "180-x" pattern instead of doing string comparison. Also, updates the value of the constraint, even when the constraint has an expression, so the arc of the angle constraint is drawn correctly while dragging the constraint.

### CODE REVIEW

File: src/Mod/Sketcher/App/SketchObjectConstraints.cpp [hunk 1]
```diff
@@ -516,19 +517,73 @@ int SketchObject::moveDatumsToEnd()
...
+            }
+        }
+
+        if (!newExpr)
+        {
+            // evaluate expression to check if value is dimensionless or has unit
+            auto result = std::unique_ptr(expr->eval());
+            auto* number = freecad_cast<App::NumberExpression*>(result.get());
+            auto value = number ? number->getQuantity() : Base::Quantity(NAN);
+            if (!value.isValid() || !value.isDimensionless() && value.getUnit() != Base::Unit::Angle) {
```
Comment (chennes) [inline src/Mod/Sketcher/App/SketchObjectConstraints.cpp]: The operator precedence here is a little tricky (`&&` is higher than `||` but TBH I had to look that up) -- I suggest adding parenthesis to clarify your intent.

File: src/Mod/Sketcher/App/SketchObjectConstraints.cpp [hunk 2]
```diff
@@ -516,19 +517,73 @@ int SketchObject::moveDatumsToEnd()
...
-        setConstraintExpression(constNum, std::move(reverseAngleConstraintExpression(expression)));
+    auto path = Constraints.createPath(constNum);
+    auto expr = getExpression(path).expression;
+    if (expr) {
+        std::shared_ptr<App::Expression> newExpr;
+
+        // if expression matches the pattern "180 - x" without or with a unit, extract "x"
+        auto op = freecad_cast<App::OperatorExpression*>(expr.get());
+        if (op && op->getOperator() == App::OperatorExpression::SUB)
+        {
```
Comment (chennes) [inline src/Mod/Sketcher/App/SketchObjectConstraints.cpp]: I'll just flag this one, but this comment applies throughout -- please use K&R-style braces.

File: src/Mod/Sketcher/App/SketchObjectConstraints.cpp [hunk 3]
```diff
@@ -516,19 +517,73 @@ int SketchObject::moveDatumsToEnd()
...
+            auto result = std::unique_ptr(expr->eval());
+            auto* number = freecad_cast<App::NumberExpression*>(result.get());
+            auto value = number ? number->getQuantity() : Base::Quantity(NAN);
+            if (!value.isValid() || !value.isDimensionless() && value.getUnit() != Base::Unit::Angle) {
+                return;
+            }
+
+            // prepend "180 - ..." to expression, with or without unit as required
+            App::Expression* valueExpr = new App::NumberExpression(expr->getOwner(), Base::Quantity(180));
+            if (!value.isDimensionless())
```
Comment (chennes) [inline src/Mod/Sketcher/App/SketchObjectConstraints.cpp]: Please add braces.

File: src/Mod/Sketcher/App/SketchObjectConstraints.cpp (hunk 2 above)
Comment (andershol) [reply src/Mod/Sketcher/App/SketchObjectConstraints.cpp]: Sorry about that. Not sure how I missed that. Thanks.

File: src/Mod/Sketcher/App/SketchObjectConstraints.cpp (hunk 1 above)
Comment (andershol) [reply src/Mod/Sketcher/App/SketchObjectConstraints.cpp]: Thanks a lot for the review. `a || (b && c)` looks kind of like `a + (b * c)` to my eye, i.e. kinda redundant. But I added the parenthesis and pulled out the negation to hopefully make it a bit easier to read. But it is an early return, so the logic is bound to look a bit backwards.

File: src/Mod/Sketcher/App/SketchObjectConstraints.cpp (hunk 3 above)
Comment (andershol) [reply src/Mod/Sketcher/App/SketchObjectConstraints.cpp]: Done
