### PR TITLE
[Measure] Fix seg fault in MeasurePosition::execute if subElements is empty

### LINKED ISSUE #20194: Measuring distance between circles centers make everything crash
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Problem description

When performing the meshurmant between the centers of two holes (via the selection of their relative perimeters) the program (FreeCAD 1.1.0dev) crashes.
 This behaviour is present also in the default configuration (Restart in Safe Mode). This behaviour is not present in the FreeCAD 1.0.0RC4 relase.

Example file: [BugN005.zip](https://github.com/user-attachments/files/19248001/BugN005.zip)

### Full version info

```shell
OS: Windows 11 build 26100
Architecture: x86_64
Version: 1.1.0dev.40504 (Git) Conda
Build type: Release
Branch: main
Hash: 855ad6c70904f911b2ce7114dd1a5bc24da98bd1
Python 3.11.11, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, IfcOpenShell 0.0.0, OCC 7.8.1
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
Logical/physical DPI: 96/113.561
Installed mods: 
  * AirPlaneDesign 0.4.1
  * Beltrami 1.1.0
  * CfdOF 1.29.8
  * CurvedShapes 1.0.13
  * Curves 0.6.59
  * Defeaturing 1.2.3
  * EM 2.1.1
  * ExplodedAssembly
  * fasteners 0.5.37
  * FoamCut 0.1.6
  * freecad.gears 1.3.0
  * GDT
  * kicadStepUpMod 11.5.5
  * LCInterlocking
  * Lithophane
  * OpticsWorkbench 1.1.2
  * osh-autodoc-workbench 0.2.3
  * Reinforcement
  * Rocket 4.1.1
  * sheetmetal.backup1730147766.3034592 0.5.3 (Disabled)
  * Ship 2024.11.26
  * STEMFIE 0.3.1
```

### Subproject(s) affected?

Measurement

### Anything else?

_No response_

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### LINKED ISSUE #20329: Measurment: Crash when measuring an object in 1.1dev (doesn't occur in v1.0)
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Problem description

The program crashes when measuring an object. It does not happen with released version 1.0 is.

### Full version info

```shell
OS: Windows 11 build 26100
Architecture: x86_64
Version: 1.1.0dev.40504 (Git) Conda
Build type: Release
Branch: main
Hash: 855ad6c70904f911b2ce7114dd1a5bc24da98bd1
Python 3.11.11, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, IfcOpenShell 0.0.0, OCC 7.8.1
Locale: Spanish/Spain (es_ES)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
Logical/physical DPI: 96/112.889
Installed mods: 
  * A2plus 0.4.68
  * Assembly4 0.12.6
  * Curves 0.6.8
  * dodo 1.0.0
  * fasteners 0.5.37
  * freecad.gears 1.3.0
  * Lithophane
  * sheetmetal 0.7.21
  * ThreadProfile 1.84.0
```

### Subproject(s) affected?

None

### Anything else?

_No response_

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Syres916**
This PR is to fix the seg fault reported on the [forum](https://forum.freecad.org/viewtopic.php?t=97756) only when Measurement is started before selection of vertices.
Regression tested pre-selection of vertices with PR successfully.

Fixes #20329 
Fixes #20194 

@hlorus FYI

### CODE REVIEW

**Comment by Syres916** [comment]
@adrianinsaval could this please be backported to releases/FreeCAD-1-0 , TIA.

File: src/Mod/Measure/App/MeasurePosition.cpp [hunk 1]
```diff
@@ -95,17 +95,19 @@ App::DocumentObjectExecReturn* MeasurePosition::execute()
...
-
-    App::SubObjectT subject {object, subElements.front().c_str()};
-    auto info = getMeasureInfo(subject);
-
-    if (!info || !info->valid) {
-        return new App::DocumentObjectExecReturn("Cannot calculate position");
+    if (subElements.empty()) {
+        return {};
+    }
+    else {
```
Comment (chennes) [inline src/Mod/Measure/App/MeasurePosition.cpp]: No need for the `else()` block, since you have an early-return.

File: src/Mod/Measure/App/MeasurePosition.cpp [hunk 2]
```diff
@@ -95,7 +95,9 @@ App::DocumentObjectExecReturn* MeasurePosition::execute()
 {
     const App::DocumentObject* object = Element.getValue();
     const std::vector<std::string>& subElements = Element.getSubValues();
-
+    if (subElements.empty()) {
+        return {};
```
Comment (chennes) [inline src/Mod/Measure/App/MeasurePosition.cpp:99]: Should it be `return DocumentObject::StdReturn;` if this doesn't represent an error condition? ETA: it doesn't make an actual difference, since StdReturn is `nullptr`, so feel free to ignore...

**Comment by maxwxyz** [comment]
@Syres916 ping for feedback
