### PR TITLE
part: fix mirror with App::Link ignoring placement and add 2 new unit tests

### LINKED ISSUE #28133: Part: Mirror of App::Link ignores placement
### Problem description

When mirroring an App::Link using Part::Mirror the placement of the link is ignored:

Image

[part_mirror_link_issue.zip](https://github.com/user-attachments/files/25781346/part_mirror_link_issue.zip)

Maybe some edge case was missed in #27370. @ipatch could you maybe have a look when you have time?

### Workbench affected?

Part

### Steps to reproduce

create a body
create a link to that body
change the placement of the link
mirror the link

### Expected behavior

translated/rotated link should be mirrored

### Actual behavior

placement of the link is ignored

### Development version About Info (in Safe Mode)

```shell
OS: Arch Linux (KDE/plasma/wayland)
Architecture: x86_64
Version: 1.2.0dev.45585 (Git)
Build date: 2026/03/04 19:57:30
Build type: Unknown
Branch: main
Hash: 2db12d8a662654ab855a4d904ba4b4b3c7bab905
Python 3.14.3, Qt 6.10.2, Coin 4.0.7, Vtk 9.5.2, boost 1_89, Eigen3 3.4.1, PySide 6.10.2
shiboken 6.10.2, SMESH 7.7.1.0, xerces-c 3.3.0, OCC 7.9.3
Locale: English/United States (en_US) [ OS: German/Germany (de_DE) ]
Navigation Style/Orbit Style/Rotation Mode: Blender/Rounded Arcball/Drag at cursor
Stylesheet/Theme/QtStyle: unset/FreeCAD Light/
Logical DPI/Physical DPI/Pixel Ratio: 96/91.7555/2
Installed mods: 
  * KicadStepUp Workbench 11.8.2
  * Gridfinity Workbench 0.11.9
  * Fasteners Workbench 0.5.39 (Disabled)
  * KicadStepUp Workbench 11.7.3 (Disabled)
  * Lattice2 Workbench 1.0.0 (Disabled)
  * SheetMetal Workbench 0.7.60
  * freecad.gears workbench 1.0.0
  * SheetMetal Workbench 0.7.24 (Disabled)
  * Curves workbench 0.6.65 (Disabled)
  * Fasteners Workbench 0.5.43
  * Assembly4 0.60.6
  * Curves workbench 0.6.70
  * Assembly4 0.60.2 (Disabled)
  * Lattice2 Workbench 1.1.0
  * FusedFilamentDesign 0.25.510
```

### Last known good version (optional)

```shell

```

### PR DESCRIPTION
**Pull request by ipatch**
this PR addresses the issue in the below linked github issue.

fixes #28133

also i removed the verbose 12 argument SetValues block with,

```cpp
TopoShape::convertTogpTrsf(placement.toMatrix(), trsf);
```

per the following comment, https://github.com/FreeCAD/FreeCAD/pull/27370#discussion_r2810103433

without the fix to `FeatureMirroring.cpp` the two added unit tests from this PR will fail.

<details>
<summary>failing tests output</summary>

```
FAILED: testMirroringWithAppLinkPlacement (parttests.TestPartMirror.TestPartMirroringRegression.testMirroringWithAppLinkPlacement)
Traceback (most recent call last):
  File "/home/capin/homebrew/Cellar/python@3.13/3.13.12_1/lib/python3.13/unittest/case.py", line 58, in testPartExecutor
    yield
  File "/home/capin/homebrew/Cellar/python@3.13/3.13.12_1/lib/python3.13/unittest/case.py", line 651, in run
    self._callTestMethod(testMethod)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/capin/homebrew/Cellar/python@3.13/3.13.12_1/lib/python3.13/unittest/case.py", line 606, in _callTestMethod
    if method() is not None:
       ~~~~~~^^
  File "/opt/code/git/github/forks/freecad-git/installs/issue.tshooting.qt6.py313/Mod/Part/parttests/TestPartMirror.py", line 159, in testMirroringWithAppLinkPlacement
    self.assertAlmostEqual(
    ~~~~~~~~~~~~~~~~~~~~~~^
        mirror_center_x,
        ^^^^^^^^^^^^^^^^
    ...<3 lines>...
        f"but is at X={mirror_center_x:.2f}",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
AssertionError: -5.0 != -25.0 within 2.0 delta (20.0 difference) : mirror should be centered at X=-25 (opposite of link at X=25), but is at X=-5.00

FAILED: testMirroringWithAppLinkRotation (parttests.TestPartMirror.TestPartMirroringRegression.testMirroringWithAppLinkRotation)
Traceback (most recent call last):
  File "/home/capin/homebrew/Cellar/python@3.13/3.13.12_1/lib/python3.13/unittest/case.py", line 58, in testPartExecutor
    yield
  File "/home/capin/homebrew/Cellar/python@3.13/3.13.12_1/lib/python3.13/unittest/case.py", line 651, in run
    self._callTestMethod(testMethod)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/capin/homebrew/Cellar/python@3.13/3.13.12_1/lib/python3.13/unittest/case.py", line 606, in _callTestMethod
    if method() is not None:
       ~~~~~~^^
  File "/opt/code/git/github/forks/freecad-git/installs/issue.tshooting.qt6.py313/Mod/Part/parttests/TestPartMirror.py", line 216, in testMirroringWithAppLinkRotation
    self.assertAlmostEqual(
    ~~~~~~~~~~~~~~~~~~~~~~^
        mirror_bbox.XMin,
        ^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        msg=f"mirror XMin should be -{link_bbox.XMax:.2f}, got {mirror_bbox.XMin:.2f}",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
AssertionError: -10.0 != -30.000000000000004 within 1.0 delta (20.000000000000004 difference) : mirror XMin should be -30.00, got -10.00

TopoShapeListTest - setting up
TopoShapeListTest: setUp complete
running TopoShapeListTest
TopoShapeListTest finished

----------------------------------------------------------------------
Ran 131 tests in 42.4s

FAILED (failures=2)
System exit
```

</details>

## Issues

- https://github.com/FreeCAD/FreeCAD/issues/28133

## Before and After Images

see linked issue for before image(s).

### CODE REVIEW

File: src/Mod/Part/App/FeatureMirroring.cpp [hunk 1]
```diff
@@ -216,8 +216,8 @@ App::DocumentObjectExecReturn* Mirroring::execute()
 
             // if there is only 1 face or 1 edge, then we don't need to force the user to select
             // that face or edge instead we can infer what was intended
-            int faceCount = Part::TopoShape(shape).countSubShapes(TopAbs_FACE);
-            int edgeCount = Part::TopoShape(shape).countSubShapes(TopAbs_EDGE);
+            auto faceCount = Part::TopoShape(shape).countSubShapes(TopAbs_FACE);
+            auto edgeCount = Part::TopoShape(shape).countSubShapes(TopAbs_EDGE);
```
Comment (kadet1090) [inline src/Mod/Part/App/FeatureMirroring.cpp:220]: why change to auto here?

File: src/Mod/Part/App/FeatureMirroring.cpp [hunk 2]
```diff
@@ -312,35 +312,25 @@ App::DocumentObjectExecReturn* Mirroring::execute()
...
-        // manually apply placement via setPlacement() before mirroring
-        if (link->isDerivedFrom(App::GeoFeature::getClassTypeId())) {
-            App::GeoFeature* geo = static_cast<App::GeoFeature*>(link);
-            Base::Placement placement = geo->Placement.getValue();
+        // check for placement property no matter the type hieararchy
+        // App:Link does not get its placement via GeoFeature inheritance
+        auto propPlacement = dynamic_cast<App::PropertyPlacement*>(
+            link->getPropertyByName("Placement")
+        );
+        if (propPlacement) {
```
Comment (kadet1090) [inline src/Mod/Part/App/FeatureMirroring.cpp]:
```suggestion
        if (auto propPlacement = link->getPropertyByName<App::PropertyPlacement*>("Placement")) {
```

1. You can use template variant of getPropertyByName
2. It's usually nice to put the variable in init-statement because then you cannot use it unchecked by mistake later in code.

File: src/Mod/Part/App/FeatureMirroring.cpp [hunk 3]
```diff
@@ -312,35 +312,25 @@ App::DocumentObjectExecReturn* Mirroring::execute()
...
-                    mat[1][0],
-                    mat[1][1],
-                    mat[1][2],
-                    mat[1][3],
-                    mat[2][0],
-                    mat[2][1],
-                    mat[2][2],
-                    mat[2][3]
-                );
+                TopoShape::convertTogpTrsf(placement.toMatrix(), trsf);
```
Comment (kadet1090) [inline src/Mod/Part/App/FeatureMirroring.cpp:322]: Wow. That function is so badly named. We really should have `Base::convertTo<gp_Trsf>(placement)`. That is however outside of scope for this PR.

File: src/Mod/Part/App/FeatureMirroring.cpp [hunk 4]
```diff
@@ -312,35 +312,25 @@ App::DocumentObjectExecReturn* Mirroring::execute()
...
 
-                // actually transform the geometry (copy=true to create new shape)
                 BRepBuilderAPI_Transform mkTrf(shape.getShape(), trsf, Standard_True);
                 shape = TopoShape(mkTrf.Shape());
             }
         }
+        else {
+        }
+
```
Comment (kadet1090) [inline src/Mod/Part/App/FeatureMirroring.cpp]: Does not seem needed.

**Review by kadet1090 — CHANGES_REQUESTED** [review]

File: src/Mod/Part/App/FeatureMirroring.cpp (hunk 1 above)
Comment (ipatch) [reply src/Mod/Part/App/FeatureMirroring.cpp:220]: it was a suggestion from my lsp.

File: src/Mod/Part/App/FeatureMirroring.cpp (hunk 4 above)
Comment (ipatch) [reply src/Mod/Part/App/FeatureMirroring.cpp]: > Does not seem needed.

absolutely correct, i believe i had a debug / print statement in there at some point.

PR has been updated.

File: src/Mod/Part/App/FeatureMirroring.cpp (hunk 2 above)
Comment (ipatch) [reply src/Mod/Part/App/FeatureMirroring.cpp]: updated with latest commit and rebase.

File: src/Mod/Part/App/FeatureMirroring.cpp (hunk 1 above)
Comment (ipatch) [reply src/Mod/Part/App/FeatureMirroring.cpp:220]: so with the original lines ie.

```cpp
int edgeCount = Part::TopoShape(shape).countSubShapes(TopAbs_EDGE);
```

my lsp ie. clang-tidy was / is giving me the below warning,

```
Narrowing conversion from 'unsigned long' to signed type 'int' is implementation-defined
```

when i changed `int` to `auto` these warnings went away.

**Comment by ipatch** [comment]
@kadet1090

**Review by kadet1090 — APPROVED** [review]
