### PR TITLE
Measurement: save 'Show Delta' state between commands #19204

### LINKED ISSUE #19204: Measurement: save 'Show Delta' state between commands
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Problem description

When users sets `Show Delta` option of `Std_Measure` tool to off, the setting is not preserved when the tool is invoked again.

Steps to reproduce:

- start Std_Measure tool
- `Show Delta` is turned on
- select distance to be measured
- disable `Show Delta` by unchecking the box
- close the tool
- start Std_Measure tool again
- `Show Delta` is turned on

Suggested behavior:
`Show Delta` state should be saved between repeated invoking of the Std_Measure command. It is expected, that if the user turns the option off, he/she does not need delta values information. It is also expected, that he/she would know, how to turn this option if the desire for delta information arises.
I think it would be ideal, if the state of `Show Delta` would be saved system wide for current user.

Image

### Full version info

```shell
OS: Windows 10 build 19045
Architecture: x86_64
Version: 1.1.0dev.39896 (Git) Conda
Build type: Release
Branch: main
Hash: a977fade2de741c94c9efa59b1c2c26df18eb631
Python 3.11.11, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: FreeCAD Light.qss/FreeCAD Light/Fusion
```

### Subproject(s) affected?

Core

### Anything else?

_No response_

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by GS-GOAT**
When users set Show Delta option to off in the Measure tool, the setting was not being preserved when the tool was invoked again. This was due to     using an uninitialized value as the default when loading the preference.  

Changes staged in: FreeCAD\src\Mod\Measure\Gui\TaskMeasure.cpp 

Fixed by:
- Using explicit 'true' as default value when loading Show Delta preference 
- Maintains existing save functionality
- Ensures consistent behavior on first use 
- Fixes #19204

### CODE REVIEW

**Comment by hlorus** [comment]
This was last changed in #17717 so i'm letting @Murmele have an eye on it.

**Comment by Murmele** [comment]
I will have a look into it

File: src/Mod/Measure/Gui/TaskMeasure.cpp [hunk 1]
```diff
@@ -72,7 +72,7 @@ TaskMeasure::TaskMeasure()
 
     QSettings settings;
     settings.beginGroup(QLatin1String(taskMeasureSettingsGroup));
-    delta = settings.value(QLatin1String(taskMeasureShowDeltaSettingsName), delta).toBool();
+    delta = settings.value(QLatin1String(taskMeasureShowDeltaSettingsName), true).toBool();
     mAutoSave = settings.value(QLatin1String(taskMeasureAutoSaveSettingsName), mAutoSave).toBool();
     if (settings.value(QLatin1String(taskMeasureGreedySelection), false).toBool()) {
```
Comment (Murmele) [inline src/Mod/Measure/Gui/TaskMeasure.cpp:77]: It seems that the reading of the config value does not work and therefore the default is used

**Comment by Murmele** [comment]
@GS-GOAT is it really solved with your last changes?

**Comment by GS-GOAT** [comment]
@Murmele It is saving state.

**Comment by Murmele** [comment]
> @Murmele It is saving state.

Thanks!

**Comment by GS-GOAT** [comment]
@hlorus please review the changes

**Review by hlorus — APPROVED** [review]

**Comment by GS-GOAT** [comment]
@chennes Changes approved .
