### PR TITLE
Resolve #11965 (B) no proper execute() for cross-property references

### LINKED ISSUE #11965: [Problem] no proper `PropertyExpressionEngine.execute()` for cross-property references
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Recently resolved issue #11825 with PR #11937 removed previously occurring spurious exceptions,
and exposed next-level problem:  

PROBLEM:
in a use case when one property has a simple expression referencing another property (see  #11825)
the `value` part of the source quantity is propagated as-is to the target,  without any regard to the `unit` information

specifically, as code tracing shows, that when  `PropertyExpressionEngine::execute()` gets to processes 
the expression constructed elsewhere by the `ExpressionParser::parse()`, 
https://github.com/FreeCAD/FreeCAD/blob/3ba0c3d7958dad891e125e065a41d95faac47c6e/src/App/PropertyExpressionEngine.cpp#L607

the type of the expression corresponding to the `source property`  here `std::shared_ptr<App::Expression>`:
https://github.com/FreeCAD/FreeCAD/blob/3ba0c3d7958dad891e125e065a41d95faac47c6e/src/App/PropertyExpressionEngine.cpp#L677

is actually `VariableExpression`
https://github.com/FreeCAD/FreeCAD/blob/3ba0c3d7958dad891e125e065a41d95faac47c6e/src/App/Expression.cpp#L2896

and not the `UnitExpression` as one would expect
https://github.com/FreeCAD/FreeCAD/blob/3ba0c3d7958dad891e125e065a41d95faac47c6e/src/App/Expression.cpp#L1222

which explains the lack of `value/unit` information conversion

Here is a proposed test case, which is currently failing:
https://github.com/FreeCAD/FreeCAD/compare/main...random-cadder:FreeCAD:issue_11825_A

SOLUTION:
it is not clear how to proceed:
* should this be resolved in `ExpressionParser::parse()` ?
* should this be handled in the `PropertyExpressionEngine::execute()`?
* is there perhaps an expression language syntax with meaning: `TreatMeAsUnitExpression(<<10 mm>>)` ?

@chennes  : please advise

### Full version info

```shell
OS: Arch Linux (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.35567 (Git)
Build type: None
Branch: makepkg
Hash: 6a54591bac6c8843f12c6971623437083d017ab3
Python 3.11.6, Qt 5.15.11, Coin 4.0.1, Vtk 9.3.0, OCC 7.7.2
Locale: English/United States (en_US)
```

### Subproject(s) affected?

None

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Andrei-Pozolotin**
Solution B: `parsequant()` expression language function

### CODE REVIEW

**Comment by pieterhijma** [comment]
@Andrei-Pozolotin, @chennes, sorry, it's on my todo list for a while. I will review today or tomorrow.

**Review by pieterhijma — CHANGES_REQUESTED** [review]
@Andrei-Pozolotin, Initially I thought you wanted a full-fledged parser for general expressions, but a parse function just for quantities makes much more sense. The test shows that it works with a variable expression which is great, but I would like to see a couple of more direct / reflexive tests as well.

I would suggest:
- `parsequant(<<(1 + 2) m>>)` hoping it evaluates to `3000 mm` 
- `parsequant(str(1 m + 2 mm))` hoping it evaluates to `1002 mm`

For the former I would expect it to create a string `"(1 + 2) mm"` that should be a valid quantity expression, so it should be picked up by the quantity parser. For the latter I would expect the expression `1m + 2mm` to evaluate to `1002 mm`. This is then converted to a string that should be parsed by `parsequant` evaluating to `1002 mm`.

If this works as I expect on the rebased main branch that has the former PR [reverted](https://github.com/FreeCAD/FreeCAD/pull/12360), then I see no barriers to merge this. Great work from my point of view.

@chennes, hope this helps to make a decision.

**Comment by Andrei-Pozolotin** [comment]
@pieterhijma : Pieter: thank you for the feedback.

Status:
* tests added
* branch rebased

Please review again.

File: tests/src/App/ExpressionParser.cpp [hunk 1]
```diff
@@ -0,0 +1,106 @@
...
+    void TearDown() override
+    {
+        App::GetApplication().closeDocument(_doc_name.c_str());
+    }
+
+    std::string doc_name() { return _doc_name; }
+    App::Document* this_doc() { return _this_doc; }
+    App::DocumentObject* this_obj() { return _this_obj; }
+
+    Base::Quantity parse_expra_as_quant(const char* expra_text) {
```
Comment (pieterhijma) [inline tests/src/App/ExpressionParser.cpp:39]: Just a very small comment: why not use `expr` instead of `expra` anywhere in this file. (I'm trying to figure out what an `expra` could mean. I probably simply miss it, but to me the `a` suffix currently doesn't mean anything, so it confuses me.)

**Review by pieterhijma — APPROVED** [review]
Looks great overall. Also nice that a couple of different units were tested. From my point of view, I approve.

**Comment by Andrei-Pozolotin** [comment]
@pieterhijma : naming patterns changed, please review.

**Review by pieterhijma — APPROVED** [review]
Looks good, thanks.

**Comment by Andrei-Pozolotin** [comment]
@chennes : @pieterhijma : works as intended, thank you.
