### PR TITLE
part: fixes #27365 mirror place copy at correct location

### LINKED ISSUE #27365: Part: Mirror places copy at the wrong location
### Problem description

Trying to mirror the right square with the y-axis (normal: 1, 0, 0)

[part_mirror_issue.zip](https://github.com/user-attachments/files/25109030/part_mirror_issue.zip)

Image

### Workbench affected?

Part

### Steps to reproduce

open file with FreeCAD_weekly-2026.02.04-Linux-x86_64-py311.AppImage
recompute

### Expected behavior

see left image

### Actual behavior

see right image

### Development version About Info (in Safe Mode)

```shell
OS: Arch Linux (KDE/plasma/wayland)
Architecture: x86_64
Version: 1.2.0dev.20260204 (Git shallow) AppImage
Build date: 2026/02/04 19:46:02
Build type: Release
Branch: (HEAD detached at 27587b9)
Hash: 27587b9cd2bc8d686187149feee7b123a65b8c77
Python 3.11.14, Qt 6.8.3, Coin 4.0.3, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.3.0, IfcOpenShell 0.8.2, OCC 7.8.1
Locale: English/United States (en_US) [ OS: German/Germany (de_DE) ]
Navigation Style/Orbit Style/Rotation Mode: Blender/Rounded Arcball/Drag at cursor
Stylesheet/Theme/QtStyle: unset/FreeCAD Light/
Logical DPI/Physical DPI/Pixel Ratio: 96/91.7555/1.5
Installed mods: 
  * KicadStepUp Workbench 11.8.2
  * Gridfinity Workbench 0.11.9
  * Fasteners Workbench 0.5.39 (Disabled)
  * KicadStepUp Workbench 11.7.3 (Disabled)
  * Lattice2 Workbench 1.0.0 (Disabled)
  * SheetMetal Workbench 0.7.60
  * freecad.gears workbench 1.0.0
  * SheetMetal Workbench 0.7.24 (Disabled)
  * Curves workbench 0.6.65 (Disabled)
  * Fasteners Workbench 0.5.43
  * Assembly4 0.60.6
  * Curves workbench 0.6.70
  * Assembly4 0.60.2 (Disabled)
  * Lattice2 Workbench 1.1.0
  * FusedFilamentDesign 0.25.510
```

### Last known good version (optional)

```shell
OS: Arch Linux (KDE/plasma/wayland)
Architecture: x86_64
Version: 1.2.0dev.20260127 (Git shallow) AppImage
Build date: 2026/01/27 15:33:30
Build type: Release
Branch: (HEAD detached at 7bcaa76)
Hash: 7bcaa766de101b10c03b4a6f4fd09292068d5ef6
Python 3.11.14, Qt 6.8.3, Coin 4.0.3, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.3.0, IfcOpenShell 0.8.2, OCC 7.8.1
Locale: English/United States (en_US) [ OS: German/Germany (de_DE) ]
Navigation Style/Orbit Style/Rotation Mode: Blender/Rounded Arcball/Drag at cursor
Stylesheet/Theme/QtStyle: unset/FreeCAD Light/
Logical DPI/Physical DPI/Pixel Ratio: 96/91.7555/1.5
Installed mods: 
  * kicadStepUpMod 11.8.2
  * Gridfinity 0.11.9
  * fasteners-backup-before-zip-migration 0.5.39 (Disabled)
  * kicadStepUpMod-backup-before-zip-migration 11.7.3 (Disabled)
  * lattice2-backup-before-zip-migration 1.0.0 (Disabled)
  * sheetmetal 0.7.60
  * fcgear 1.0.0
  * sheetmetal-backup-before-zip-migration 0.7.24 (Disabled)
  * Curves-backup-before-zip-migration 0.6.65 (Disabled)
  * fasteners 0.5.43
  * Assembly4 0.60.6
  * Curves 0.6.70
  * Assembly4-backup-before-zip-migration 0.60.2 (Disabled)
  * lattice2 1.1.0
  * FusedFilamentDesign 0.25.510
```

### PR DESCRIPTION
**Pull request by ipatch**
this pr fixes #27365 while also providing a unit test to hopefully pick up on issues like this in the future to prevent regression like this from happening again.

results from the current main branch without this fix, running the newly created unit test.

```
╰─λ /opt/code/fcgit/installs/issue.tshooting.qt6.py313/bin/FreeCAD -t TestPartApp
FreeCAD 1.2.0, Libs: 1.2.0devR45261 (Git)
(C) 2001-2026 FreeCAD contributors
FreeCAD is free and open-source software licensed under the terms of LGPL2+ license.

<AnaFilletAlgo object>
<ChamferAPI object>
<FilletAlgo object>
<ShapeFix_Edge object>
<ShapeFix_Face object>
<ShapeFix_Root object>
<ShapeFix_Shape object>
<ShapeFix_Shell object>
<ShapeFix_Solid object>
<ShapeFix_Wire object>
Converting attachment offset of Sketch003
Converting attachment offset of Sketch002
FAILED: testMirroringWithDraftCloneStability (parttests.TestPartMirror.TestPartMirroringRegression.testMirroringWithDraftCloneStability)
Traceback (most recent call last):
  File "/home/capin/homebrew/Cellar/python@3.13/3.13.11/lib/python3.13/unittest/case.py", line 58, in testPartExecutor
    yield
  File "/home/capin/homebrew/Cellar/python@3.13/3.13.11/lib/python3.13/unittest/case.py", line 651, in run
    self._callTestMethod(testMethod)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/capin/homebrew/Cellar/python@3.13/3.13.11/lib/python3.13/unittest/case.py", line 606, in _callTestMethod
    if method() is not None:
       ~~~~~~^^
  File "/opt/code/git/github/forks/freecad-git/installs/issue.tshooting.qt6.py313/Mod/Part/parttests/TestPartMirror.py", line 69, in testMirroringWithDraftCloneStability
    self.assertLess(initial_center_x, -20.0,
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
        msg=f"mirror should be at X≈-30 (opposite side of X=0 from clone at X≈30), "
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            f"but is at X={initial_center_x:.2f}")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: 4.999999999999988 not less than -20.0 : mirror should be at X≈-30 (opposite side of X=0 from clone at X≈30), but is at X=5.00

TopoShapeListTest - setting up
TopoShapeListTest: setUp complete
running TopoShapeListTest
TopoShapeListTest finished

----------------------------------------------------------------------
Ran 129 tests in 36.4s

FAILED (failures=1)
System exit

```

results after the fix is applied.

```
╰─λ /opt/code/fcgit/installs/issue.tshooting.qt6.py313/bin/FreeCAD -t TestPartApp
FreeCAD 1.2.0, Libs: 1.2.0devR45264 (Git)
(C) 2001-2026 FreeCAD contributors
FreeCAD is free and open-source software licensed under the terms of LGPL2+ license.

<AnaFilletAlgo object>
<ChamferAPI object>
<FilletAlgo object>
<ShapeFix_Edge object>
<ShapeFix_Face object>
<ShapeFix_Root object>
<ShapeFix_Shape object>
<ShapeFix_Shell object>
<ShapeFix_Solid object>
<ShapeFix_Wire object>
Converting attachment offset of Sketch003
Converting attachment offset of Sketch002
TopoShapeListTest - setting up
TopoShapeListTest: setUp complete
running TopoShapeListTest
TopoShapeListTest finished

----------------------------------------------------------------------
Ran 129 tests in 36.2s

OK
System exit

```

## Issues

- https://github.com/freecad/freecad/issues/27365

### CODE REVIEW

**Comment by chennes** [comment]
@theosib you want to take a look at this to make sure it matches your understanding of how the mirror should be implemented?

File: src/Mod/Part/App/FeatureMirroring.cpp [hunk 1]
```diff
@@ -309,12 +309,48 @@ App::DocumentObjectExecReturn* Mirroring::execute()
...
+        // manually apply placement via setPlacement() before mirroring
+        if (link->isDerivedFrom(App::GeoFeature::getClassTypeId())) {
+            App::GeoFeature* geo = static_cast<App::GeoFeature*>(link);
+            Base::Placement placement = geo->Placement.getValue();
+
+            if (!placement.isIdentity()) {
+                // Convert Placement to gp_Trsf
+                gp_Trsf trsf;
+                Base::Matrix4D mat = placement.toMatrix();
+                trsf.SetValues(
```
Comment (chennes) [inline src/Mod/Part/App/FeatureMirroring.cpp:324]: Can you use `TopoShape::convert` instead?

**Comment by 3x380V** [comment]
Just resolved conflict in 30706898c8f9a540fc2717bd8f2a659c224766c1 Does it fix the same issue? If it does so, then it seems to be less noisy... FYI, @ipatch, @theo-vt

**Comment by marioalexis84** [comment]
@ipatch Part module shouldn't use Draft module (Draft can use Part, but no viceversa)
related to #29311

**Comment by ipatch** [comment]
> @ipatch Part module shouldn't use Draft module (Draft can use Part, but no viceversa) related to #29311

are you saying the crash in #29311 with the bim/arch workbench is due to a circular dependency error?

and ideally the test file included with this PR would not use `import Draft` or any draft related code within its test file?

ie.

```python
clone = Draft.make_clone(sketch)
```

**Comment by marioalexis84** [comment]
> are you saying the crash in https://github.com/FreeCAD/FreeCAD/issues/29311 with the bim/arch workbench is due to a circular dependency error?

No. The crash is due to the PySide bug.
Part workbench should not depend on another workbench as Draft or PartDesign.
