### PR TITLE
[CAM] separate tolerance variable used for arc fitting from tolerance used for section height offsets

### LINKED ISSUE #26780: CAM: Post Processing Tool Path Goes Out of Bounds (Flies Off Board) During a Cut
### Problem description

A PCB Pocket Shape milling op (the first tool in a sequence) generated G-code goes off-limits in a damaging way.  There are two versions of the same PCB job attached: 

1) The 'board_back'  "Cutout" body has no Part Geometry Check errors.  When the tool path computed by the first Pocket Shape (1.0mm Endmill tool) is run through the new CAM Path Simulator the path conversion error to g-code is visible (see pic attached below, circled in red).  Also, the G2 command at line 629 in the attached 'board_back--1_0mm_Endmill001.nc' with a huge I coordinate is suspect.

2) the 'board_back_old' "Cut" body has been created from DXF LINEs as imported (same as above but without me cleaning the garbage DXF LINEs and reconnecting the good ones). The same tool path computed shows  a few more of the same "going off-limit" errors are visible in the Path Simulator.

I tried to eliminate G2s by using the "--split-arcs" option to the 'grbl' output processor but the going off-limits is still present in the Path Simulator, so it must be in the g-codes as well.

Image

[boards.zip](https://github.com/user-attachments/files/24509737/boards.zip)

DXF File:    [dxf.zip](https://github.com/user-attachments/files/24510050/dxf.zip)

OS: macOS 13.7.8
Architecture: x86_64
Version: 1.2.0dev.20260106 (Git shallow)
Build date: 2026/01/06 15:36:19
Build type: Release
Branch: (HEAD detached at 9b64da8)
Hash: 9b64da827a112d88a025be26316e3d023ff491dc
Python 3.11.14, Qt 6.8.3, Coin 4.0.3, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.3.0, IfcOpenShell 0.8.2, OCC 7.8.1
Locale: English/Canada (en_CA)
Navigation Style/Orbit Style/Rotation Mode: Gesture/Rounded Arcball/Window center
Stylesheet/Theme/QtStyle: FreeCAD.qss/FreeCAD Dark/
Logical DPI/Physical DPI/Pixel Ratio: 72/147.25/2

### Workbench affected?

None

### Steps to reproduce

see above

### Expected behavior

see above

### Actual behavior

see above

### Development version About Info (in Safe Mode)

```shell
see above
```

### Last known good version (optional)

```shell

```

### PR DESCRIPTION
**Pull request by davidgilkaufman**
Fixes #26780 (note that this was previously marked as fixed by PR #26860 but OP correctly claims the PR does not fix the issue)

Somewhat fixes regression #27007, which is caused by a PR intended to fix #26780. That PR should still be reverted, as discussed in #27007, and this should be merged instead as an improved fix and backported to 1.1 for the release.

Supersedes #26871, which is an attempt to fix the same issue further down stream from the original problem

@Connor9220 @sliptonic @tarman3 @zoltan-ky fyi

---

The actual diff of this fix is a bit opaque, unfortunately. The crux of the fix is what I outlined in #26871 [comments](https://github.com/FreeCAD/FreeCAD/pull/26871#issuecomment-3740919321):  when converting back from clipper we attempt to fit arcs to clipper's lines, and evidently this can result in big-radius nearly-straight arcs that are hard to compute on reliably.

I said in my comment that this function probably ought to have a check that the candidate circle's radius is not to big. It turns out it already has that check. However, that check is run with tolerance `Point::tolerance`. This variable is clearly defined in code as `0.001mm`, but in fact it is overwritten within CArea initialization macros with a value passed in from python, which is ~1e-7. I don't think this value passed in from python makes sense here, and it fully explains why the large arcs reported in the issue are generated (they are large, but not compared to 1e7).

As a fix, I split off the tolerance variable used in the radius check and one other check of FitArcs from the tolerance ("section tolerance") controlled by python, and set the value to the likely-intended 0.001mm, which seems reasonable to me. I considered splitting off a couple other uses of `Point::tolerance` as well but decided against it even though they didn't look like they should be controlled by the python "section tolerance" because I was insufficiently confident about what impact that would have and I don't want to rock any boats in a regression fix PR.

### CODE REVIEW

**Comment by maxwxyz** [comment]
@Connor9220 to be backported?

**Comment by Connor9220** [comment]
> @Connor9220 to be backported?

Yes

**Comment by tarman3** [comment]
Looks good
I recomputed example from issue and did not get any "crazy" commands

Do not know, is it important or not
But still have several arcs with curvature deflection much less than 0.01 mm and can be represented by simple lines

first number is curvature deflection
<details>
  <summary>gcode</summary>

0.00112   Command G2 [ F:0.83333 I:-0.13525 J:0.18861 K:0 X:42.674 Y:21.844 Z:-0.1 ]
0.00128   Command G2 [ F:0.83333 I:-0.11191 J:-0.2414 K:0 X:42.719 Y:21.818 Z:-0.1 ]
0.00112   Command G2 [ F:0.83333 I:0.13527 J:-0.18862 K:0 X:41.146 Y:29.464 Z:-0.1 ]
0.00128   Command G2 [ F:0.83333 I:0.11192 J:0.24141 K:0 X:41.101 Y:29.49 Z:-0.1 ]
0.00112   Command G2 [ F:0.83333 I:0.13527 J:-0.18862 K:0 X:41.146 Y:24.384 Z:-0.1 ]
0.00128   Command G2 [ F:0.83333 I:0.11192 J:0.24141 K:0 X:41.101 Y:24.41 Z:-0.1 ]
0.00112   Command G2 [ F:0.83333 I:0.13527 J:-0.18862 K:0 X:41.146 Y:21.844 Z:-0.1 ]
0.00128   Command G2 [ F:0.83333 I:0.11191 J:0.24141 K:0 X:41.101 Y:21.87 Z:-0.1 ]
0.00112   Command G2 [ F:0.83333 I:-0.13525 J:0.18861 K:0 X:42.674 Y:24.384 Z:-0.1 ]
0.00128   Command G2 [ F:0.83333 I:-0.11191 J:-0.2414 K:0 X:42.719 Y:24.358 Z:-0.1 ]
0.00112   Command G2 [ F:0.83333 I:0.13526 J:-0.18862 K:0 X:41.146 Y:26.924 Z:-0.1 ]
0.00128   Command G2 [ F:0.83333 I:0.11192 J:0.24142 K:0 X:41.101 Y:26.95 Z:-0.1 ]
0.00112   Command G2 [ F:0.83333 I:-0.13525 J:0.1886 K:0 X:42.674 Y:29.464 Z:-0.1 ]
0.00128   Command G2 [ F:0.83333 I:-0.11191 J:-0.2414 K:0 X:42.719 Y:29.438 Z:-0.1 ]
0.00112   Command G2 [ F:0.83333 I:-0.13525 J:0.18861 K:0 X:42.674 Y:26.924 Z:-0.1 ]
0.00128   Command G2 [ F:0.83333 I:-0.11191 J:-0.2414 K:0 X:42.719 Y:26.898 Z:-0.1 ]
0.00112   Command G2 [ F:0.83333 I:-0.13525 J:0.18861 K:0 X:90.492 Y:54.513 Z:-0.1 ]
0.00128   Command G2 [ F:0.83333 I:-0.11191 J:-0.2414 K:0 X:90.537 Y:54.486 Z:-0.1 ]
0.00112   Command G2 [ F:0.83333 I:0.13527 J:-0.18863 K:0 X:88.964 Y:54.513 Z:-0.1 ]
0.00128   Command G2 [ F:0.83333 I:0.11192 J:0.24141 K:0 X:88.919 Y:54.539 Z:-0.1 ]
0.00143   Command G2 [ F:0.83333 I:-0.00033913 J:-1.1832 K:0 X:72.425 Y:48.226 Z:-0.1 ]
0.00112   Command G2 [ F:0.83333 I:0.18863 J:0.13527 K:0 X:116.82 Y:31.621 Z:-0.1 ]
0.00128   Command G2 [ F:0.83333 I:-0.24141 J:0.11192 K:0 X:116.8 Y:31.576 Z:-0.1 ]
0.00128   Command G2 [ F:0.83333 I:0.24141 J:-0.11192 K:0 X:114.31 Y:33.194 Z:-0.1 ]
0.00112   Command G2 [ F:0.83333 I:-0.18861 J:-0.13525 K:0 X:119.36 Y:33.149 Z:-0.1 ]
0.00128   Command G2 [ F:0.83333 I:0.24141 J:-0.11191 K:0 X:119.39 Y:33.194 Z:-0.1 ]
0.00112   Command G2 [ F:0.83333 I:0.18863 J:0.13527 K:0 X:121.9 Y:31.621 Z:-0.1 ]
0.00128   Command G2 [ F:0.83333 I:-0.24141 J:0.11192 K:0 X:121.88 Y:31.576 Z:-0.1 ]
0.00112   Command G2 [ F:0.83333 I:-0.18861 J:-0.13525 K:0 X:121.9 Y:33.149 Z:-0.1 ]
0.00128   Command G2 [ F:0.83333 I:0.2414 J:-0.11191 K:0 X:121.93 Y:33.194 Z:-0.1 ]
0.00112   Command G2 [ F:0.83333 I:0.18863 J:0.13527 K:0 X:114.28 Y:31.621 Z:-0.1 ]
0.00128   Command G2 [ F:0.83333 I:-0.24141 J:0.11192 K:0 X:114.26 Y:31.576 Z:-0.1 ]
0.00112   Command G2 [ F:0.83333 I:0.18863 J:0.13527 K:0 X:119.36 Y:31.621 Z:-0.1 ]
0.00128   Command G2 [ F:0.83333 I:-0.24141 J:0.11191 K:0 X:119.34 Y:31.576 Z:-0.1 ]
</details>

In any case result awesome
Thank you

**Comment by tarman3** [comment]
https://github.com/FreeCAD/FreeCAD/blob/cdce2f0ffdd15aabd29b52430c8e1bd0142ae325/src/Mod/CAM/libarea/Curve.cpp#L17

Is there a reason do not use `curve accuracy` from CAM preferences?

Screenshot_20260126_192545_lossy

**Comment by zoltan-ky** [comment]
I have not been through this "libarea" code much, only a bit while struggling with these huge arcs - but on reviewing a bit the apparent call-tree:
```
CCurve::FitArcs
  AddArcOrLines
    CheckForArc
    ...
    if (arc_found)
       if (arc.AlmostALine())
          "undo/pushback"...
  ...
  CheckForArc
```
it would appear that CheckForArc is called at different levels and 'more' than AlmostALine which find-grep found only in one spot in FitArcs indicated above.

1) Since funnily enough CheckForArc and AlmostALine seem like should be prefect complements ie. a False from one would imply a True from the other and CheckForArc seems to be a little more used why aren't we fixing this in CheckForArc?

2) Hard coded arc_tolerance = 0.001   - Does this mean that any radius > 1m will be rejected without regard to the size of the entire design?   What is someone is trying to model something on the order of a m...?   Wouldn't a relative measure like  e.g. chord/radius be more logical?

3) That added mid-point test in AlmostALine() tests the maximum deflection of the arc, do I read that correctly?   What about my find in the G2/G3 PR discussion that a number of large radius arc were caused by arcs created from three points where the middle point was infinitesimally close to the start or end-points and could thus simply be replaced by a line between the start end end points?    

I don't know much about this codebase or its history but somehow it feels that CheckForArc might be a better place for this fix given that it appears complementary to AlmostALine...  Is AlmostALine may be checking an arc that was created/accepted before erroneously by CheckForArc?

**Comment by davidgilkaufman** [comment]
> In any case result awesome
> Thank you

:+1: :heart: 



> Do not know, is it important or not
> But still have several arcs with curvature deflection much less than 0.01 mm and can be represented by simple lines

> Is there a reason do not use `curve accuracy` from CAM preferences?

Updated, and correspondingly it now uses default value 0.01mm. I might have a mild preference for 0.001mm but I don't think it matters much. I do think it is better that this value is something the user can customize


> 1. why aren't we fixing this in CheckForArc?

As you noted, there is not a 1-1 correspondence between calls to one and calls to the other. Notably CheckForArc can return an arc successfully and that arc can just be ignored and replaced by the next result of CheckForArc, effectively extending the arc to more points. AlmostALine is only called at the end.

I don't particularly endorse this algorithm, and I had no idea of the intricacies of how it works prior to diving into this bug. I think it would be similarly ok to do this check in CheckForArc. But it seems clear to me that whoever wrote this algorithm intended for the check to be done where it is written, and likely for some time that did happen, with a default value of 0.001mm. On the off chance I don't fully understand everything I read in the past few days I'm inclined to leave the check where it is. It gives me a better chance of shipping a fix for the 1.1 backport instead of a replacement bug.

> 2\. Does this mean that any radius > 1m will be rejected without regard to the size of the entire design?

Yes, but I'm not overly concerned about it. We will still output line segments modeling the arc, at a precision much greater than required (particularly for a >1m scale machine). The critical feature here is that we need to avoid constructing arcs big enough that we don't compute cleanly on them.

> 3\. That added mid-point test in AlmostALine() tests the maximum deflection of the arc, do I read that correctly? ...

In short yes, my understanding matches yours, but I do not have a detailed answer of why those arcs were accepted. Off hand it seems very reasonable to me -- that big a circle is basically a line at the relevant scale, and I expect all points that went into the fit were very nearly on the line (although not within 1e-7, perhaps, since that's the size of our clipper grid, and it's hard to be much more on a line than that precision. Thus the the arc was allowed).



> but somehow it feels that CheckForArc might be a better place for this fix

tbh I am not very invested in the semantics of where these checks belong in this algorithm. My priorities for this ticket are to resolve the bug and to make a safe-looking change with a low chance of introducing new unexpected bugs for 1.1. I think the current location of the fix does a good job of both of those things. I like that the change is minimal, and that it is likely reenabling a code path that was once used and thus plausibly validated by that use.

I'm currently busy working on Adaptive, but after that I'm hoping to upgrade our geometry library. One of the goals of that upgrade will be to obsolete this code -- completely remove the concept of arc fitting via guess+check and just know where there should be arcs and have arcs there instead of lines. This patchwork guess and check algorithm has been mostly good enough for a long time now, and my hope and expectation is that with this patch it will remain good enough long enough for long enough to not need more attention before it is deleted.

**Comment by zoltan-ky** [comment]
Yes, I also don't like the way this code is working with going ahead along the path then reverting back and trying in a different direction when some criterion fails.   I was only looking from a 'surgical' point of view and if we are certain that there won't be any CheckForArc calls that are NOT followed by an AlmostALine, (which is not clear to me given my short involvement) then it should fix it.

I'm not sure if it's any help but I will now try use your changes on the board examples I had in the OP and verify that all large radii are gone and will report back.

**Comment by tarman3** [comment]
> Updated, and correspondingly it now uses default value 0.01mm. I might have a mild preference for 0.001mm but I don't think it matters much. I do think it is better that this value is something the user can customize

Checked
Working fine

Thank You

**Comment by davidgilkaufman** [comment]
> and if we are certain that there won't be any CheckForArc calls that are NOT followed by an AlmostALine,

Oh, I see what you're saying. This should be fine. The check in this location ensures that everything appended to new_vertices has an acceptably small radius. It would also be sufficient to ensure CheckForArc only returns arcs of sufficiently small radius; either approach should work.

**Comment by zoltan-ky** [comment]
Went through the diffs in the output GCode of this solution vs the CheckForArc experiment using the original 'board_back_old' model and this here solution produces a much nicer and shorter GCode with no large arcs so this PR will fix [#26780](https://github.com/FreeCAD/FreeCAD/issues/26780)

**Comment by zoltan-ky** [comment]
I think this will also fix [#23134](https://github.com/FreeCAD/FreeCAD/issues/23134) that's been sitting open for a while.  There's a huge arc as the root of the problem (see enclosed G-code there).

**Comment by maxwxyz** [comment]
So does this fully close https://github.com/FreeCAD/FreeCAD/issues/27007 ?

**Comment by tarman3** [comment]
No
Need to revert #26860

**Comment by tarman3** [comment]
I found a problem
Deflection of this arcs more than 40 mm, but with `Default curve accuracy` 0.01 mm get incorrect shape from `PathScripts.PathUtils.getEnvelope()`

[curve_accracy_test.zip](https://github.com/user-attachments/files/24954409/curve_accracy_test.zip)

Screenshot_20260130_064620_hor_lossy

Steps to reproduce:
- set `Default curve accuracy = 0.01 mm`
- open test file
- execute commands
```
import PathScripts.PathUtils as PathUtils
obj = FreeCAD.ActiveDocument.getObject("Shape002")
wire = obj.Shape
face = Part.Face(wire)
shapeEnv = PathUtils.getEnvelope(face)
Part.show(shapeEnv)
```

https://github.com/user-attachments/assets/0faf3e7e-40b6-4f91-a052-d1f565fa26a3

File: src/Mod/CAM/libarea/Arc.cpp [hunk 1]
```diff
@@ -50,11 +51,11 @@ double CArc::IncludedAngle() const
 bool CArc::AlmostALine() const
 {
     Point mid_point = MidParam(0.5);
-    if (Line(m_s, m_e - m_s).Dist(mid_point) <= Point::tolerance) {
+    if (Line(m_s, m_e - m_s).Dist(mid_point) <= CArea::get_accuracy()) {
         return true;
     }
 
-    const double max_arc_radius = 1.0 / Point::tolerance;
+    const double max_arc_radius = 1.0 / CArea::get_accuracy();
```
Comment (tarman3) [inline src/Mod/CAM/libarea/Arc.cpp]: If set curve accuracy 0.01 mm, do not produce arcs with radius `1.0 / 0.01 = 100`

Increase value accuracy - decrease max allowed radius
accuracy 0.001 - allow radius 1000
accuracy 0.01 - allow radius 100
accuracy 0.1 - allow radius 10
accuracy 1 - allow radius 1

This looks wrong

**Comment by zoltan-ky** [comment]
Isn't that only the maximum allowed ie. 1.0 / 0.01 = 100mm ?  Only a few arcs along my PCB traces were generated with radii of a couple of mm, max was 11mm.

**Comment by tarman3** [comment]
I work with machine 2000x1500
In my tasks radius can be few meters

If we increase value, we allow less radius
accuracy 0.001 - allow radius 1000
accuracy 0.01 - allow radius 100
accuracy 0.1 - allow radius 10

This expression totally wrong

**Comment by zoltan-ky** [comment]
Right.  That's why I'm not a fan of hard-coded absolute values. A Chord/radius check against a configurable max ratio of e.g. 0.01 (just by accident similar to curve accuracy)  - 1cm chord with a 1m radius, or a 1mm chord with 10cm radius, or ...  would be AlmostALine ;-).

**Comment by tarman3** [comment]
We really need a replacement of `Area` and `Offset` tools
This should be first on the roadmap list

File: src/Mod/CAM/libarea/Arc.cpp (hunk 1 above)
Comment (tarman3) [reply src/Mod/CAM/libarea/Arc.cpp]: For test replaced expression to
```max_arc_radius = 1'000'000 * CArea::get_accuracy()```
