### PR TITLE
Measure: Improve Angle creation, UX and Sector Support

### LINKED ISSUE #14673: Std_Measure: Error for angle between face and edge of that face
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

If you measure the angle between a face and an edge of that face there is a warning. I am not saying this angle makes sense. But this situation may occur accidentally.

Test:
Create a Part_Box.
Start Std_Measure.
Select a face and an edge belonging to that face.
Result: Warning:
`10:26:48  <Gui> Document.cpp(822): Cannot update representation for Unnamed#Angle`

### Full version info

```shell
OS: Windows 8 build 9600
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37709 (Git)
Build type: Release
Branch: main
Hash: dd816a635ccacc39f29b1761c6ccfed21a90b646
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: C/Default (C) [ OS: Dutch/Netherlands (nl_NL) ]
Installed mods:
```

### Subproject(s) affected?

Core

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #16694: Measurement: label location is not saved
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Steps to reproduce:

1. Create an object (e.g. Part > Cube)
2. Select an edge
3. Click the measure tool
4. Press Save
5. With the measurement created, drag its label to a new position
6. Save document and close it
7. Reopen document
8. The label's position is back to its original positil. Expected: label to be in the new position (step 5)

### Full version info

```shell
OS: Ubuntu Core 22 (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38794 (Git) Snap 1144
Build type: Release
Branch: main
Hash: a47800d9ccd7d7a7cdb1779d56de03d3c64cd76e
Python 3.10.12, Qt 5.15.10, Coin 4.0.0, Vtk 7.1.1, OCC 7.7.1
Stylesheet/Theme/QtStyle: OpenLight.qss/OpenLight/Qt default
Installed mods: 
  * OpenTheme 2024.9.1
  * ezydxf
```

### Subproject(s) affected?

None

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by YashSuthar983**
fixes #16694 
closes #27386 

***Before***

https://github.com/user-attachments/assets/a04bad31-eda8-4492-a3d7-b229682d5a32

***After***

https://github.com/user-attachments/assets/2142b9a6-399a-490a-ab34-ad802325045f

added preference for arrow hight and radius. Normal line for correctly able to visualise angle arc .
Fix restore issue as closing opening doc cause lable to origin.

### CODE REVIEW

**Comment by maxwxyz** [comment]
It looks like the arcs are rendered on top of the labels?
@FreeCAD/design-working-group FYI

**Comment by luisDias89** [comment]
I have a suggestion about this commit. Some people create models with just a few millimeters, such as rings, jewelry, etc. The measurement arrows should adapt to the viewing size.
As I noticed, when the arrows are too close to each other, they end up overlapping.

**Comment by pierreporte** [comment]
Marking the screen size constant should be enough. When parts are small the view is usually zoomed accordingly, else it is hard to read anyway. The arrows shouldn't be too big though, and I do think they could be smaller to what is shown in the video.

**Comment by YashSuthar983** [comment]
prevent arrow overlap ,here what i came up with .
(we can also set global arrow hight and radius in preference/Measure ).

https://github.com/user-attachments/assets/932ae89a-9f8a-47c2-9bbd-3f7317b74024

**Comment by YashSuthar983** [comment]
> I have a suggestion about this commit. Some people create models with just a few millimeters, such as rings, jewelry, etc. The measurement arrows should adapt to the viewing size....

i am thinking to do this as similar we have in sketcher (icons for constraints etc).

**Comment by pierreporte** [comment]
Maybe @captain0xff can help you keep arrowheads at constant screen size, since he implemented them for a different feature.

**Comment by captain0xff** [comment]
https://github.com/FreeCAD/FreeCAD/blob/2dcc35153225ea3bbccb9314b81c28c499c6af45/src/Gui/Inventor/Draggers/SoTransformDragger.cpp#L483
Take a look at this function and corresponding callback methods to see how to detect change in the zoom level and calculate the relative scale. Then you can just use an SoScale node with your geometry to scale them as necessary.

**Comment by YashSuthar983** [comment]
@captain0xff  can't we do as done in sketcher 
https://github.com/FreeCAD/FreeCAD/blob/af4a989dc1208ea88f2c59df16f096d50d128307/src/Mod/Sketcher/Gui/SoZoomTranslation.cpp#L67
made a new node class?

Edit:  i have tested this one not sure its good approach, but it works.
@captain0xff i look into what you have suggested there we are using camera sensor and at end also getWorldToScreenScale, as both approch do same at the end i test with using getWorldToScreenScale as new node and implemented in arrow node and some soCalulator stuff.

I’d appreciate some clarification on which approach is preferred before I push the commit.

https://github.com/user-attachments/assets/7d7c4fd9-4d39-4116-a201-22a1e6f78ef8

**Comment by captain0xff** [comment]
If your approach works then that's fine. I am personally familiar with the approach that I shared above and used that for the interative gizmos.

**Comment by pierreporte** [comment]
I tested this PR but it doesn’t quite look like the latest video because the arrows are quite short and get bigger when zoomed in. More importantly, the dashed lines are not perpendicular to the measured surfaces, and the actual result depends on the selection order:

image

image

image

image

Also I can drag the measurement on the opposite side, towards the red arrow in this picture:

image


I would recommend to make it look like this, with dashed lines that are in the planes rather than perpendicular, for extra clarity. Note that it is already like this for lines as shown above.

image

```
OS: Ubuntu 24.04.3 LTS (KDE/plasma/xcb)
Architecture: x86_64
Version: 1.2.0dev.45097 (Git)
Build date: 2026/01/30 11:39:34
Build type: Unknown
Branch: Measure
Hash: 1ff63d233e45564e41d454a989be9a49ab12c47f
Python 3.11.13, Qt 6.8.3, Coin 4.0.3, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.3.0, IfcOpenShell 0.8.2, OCC 7.8.1
Locale: French/France (fr_FR)
Navigation Style/Orbit Style/Rotation Mode: CAD/Rounded Arcball/Drag at cursor
Stylesheet/Theme/QtStyle: FreeCAD.qss/FreeCAD Light/
Logical DPI/Physical DPI/Pixel Ratio: 96/117.596/1
Installed mods: 
  * Cables 0.3.4
  * fasteners 0.5.43
  * Curves 0.6.70
  * CurvedShapes 1.0.14
  * sheetmetal 0.7.61
  * FusedFilamentDesign 0.25.510
```

**Comment by pierreporte** [comment]
Then there are two problems:

1) The sizes in the preferences are in pixels but the actual rendering in the 3D view is way bigger. it says 2 px radius but it’s at around 3 or 4 times more.

2) Changing the settings doesn’t update existing measurements.

I think that a good default would be a radius of 0.5 px and a height of 2 px (with the current implementation).

**Comment by YashSuthar983** [comment]
@pierreporte 
>The pixel sizes in the preferences are more usable but still not very realistic:

i dont understand this point what realistic means here?

**Comment by YashSuthar983** [comment]
@pierreporte  
height

diameter

i tested with diff scales ratio i get the same result. as radius =6 (diameter 12) and (height =18).

**Comment by FEA-eng** [comment]
This should fix #13711, right? It would be good to test with the cases shown there once the PR is ready for review.

File: src/Mod/Measure/App/MeasureAngle.cpp [hunk 1]
```diff
@@ -211,6 +224,214 @@ gp_Vec MeasureAngle::location2()
...
+    gp_Pnt p1_2 = BRep_Tool::Pnt(v1_2);
+    gp_Pnt p2_1 = BRep_Tool::Pnt(v2_1);
+    gp_Pnt p2_2 = BRep_Tool::Pnt(v2_2);
+
+    double tol = Precision::Confusion();
+    bool matchStartStart = p1_1.IsEqual(p2_1, tol) && p1_2.IsEqual(p2_2, tol);
+    bool matchStartEnd = p1_1.IsEqual(p2_2, tol) && p1_2.IsEqual(p2_1, tol);
+
+    return matchStartStart || matchStartEnd;
+}
```
Comment (hyarion) [inline src/Mod/Measure/App/MeasureAngle.cpp]: this just checks the end positions, what if one is a curve?
maybe this would be better?
```c++
  auto geom1 = Part::Geometry::fromShape(ed1, true);
  auto geom2 = Part::Geometry::fromShape(ed2, true);
  if (geom1 && geom2
      && geom1->isSame(*geom2, Precision::Confusion(), Precision::Angular())) {
  }
```

but then, do we need this function as it gets so small and is just used in one place?

File: src/Mod/Measure/App/MeasureAngle.cpp [hunk 2]
```diff
@@ -211,6 +224,214 @@ gp_Vec MeasureAngle::location2()
...
+
+bool MeasureAngle::setOrigin(TopoDS_Shape& s1, TopoDS_Shape& s2)
+{
+    if (s1.IsNull() || s2.IsNull()) {
+        return false;
+    }
+    if (mCase == FaceFace) {
```
Comment (hyarion) [inline src/Mod/Measure/App/MeasureAngle.cpp]: instead of this if-else chain, how about using a switch?

```c++
      switch (mCase) {
          case FaceFace:
              return setOriginFaceFace(s1, s2);
          case EdgeEdge:
              return setOriginEdgeEdge(s1, s2);
          case FaceEdge:
              return setOriginFaceEdge(s1, s2);
      }
```

File: src/Mod/Measure/App/MeasureAngle.cpp [hunk 3]
```diff
@@ -211,6 +224,214 @@ gp_Vec MeasureAngle::location2()
...
+                    // calculate outOrigin from the common edge
+                    TopoDS_Vertex v1, v2;
+                    TopExp::Vertices(ed1, v1, v2);
+                    outOrigin = gp_Pnt((BRep_Tool::Pnt(v1).XYZ() + BRep_Tool::Pnt(v2).XYZ()) / 2);
+                    return true;
+                }
+                exp2.Next();
+            }
+            exp1.Next();
+        }
```
Comment (hyarion) [inline src/Mod/Measure/App/MeasureAngle.cpp]: This solution gives a complexity of O(n*m), could we use something like [TopTools_IndexedMapOfShape](https://techoverflow.net/2019/06/14/how-to-iterate-toptools_indexedmapofshape/) so we could iterate over it on O(n+m)?

if combined with the content of isGeometricalSameEdge, we could write it something like:
```c++
      auto setOriginFromEdgeMidpoint = [this](const TopoDS_Edge& edge) -> bool
      {
          TopoDS_Vertex v1, v2;
          TopExp::Vertices(edge, v1, v2);

          outOrigin = gp_Pnt(
              (BRep_Tool::Pnt(v1).XYZ() + BRep_Tool::Pnt(v2).XYZ()) / 2
          );
          return true;
      };

      TopTools_IndexedMapOfShape edges1, edges2;
      TopExp::MapShapes(s1, TopAbs_EDGE, edges1);
      TopExp::MapShapes(s2, TopAbs_EDGE, edges2);

      for (int i = 1; i <= edges1.Extent(); i++) {
          const TopoDS_Edge& ed1 = TopoDS::Edge(edges1(i));
          for (int j = 1; j <= edges2.Extent(); j++) {
              const TopoDS_Edge& ed2 = TopoDS::Edge(edges2(j));

              if (ed1.IsSame(ed2)) {
                  return setOriginFromEdgeMidpoint(ed1);
              }

              auto geom1 = Part::Geometry::fromShape(ed1, true);
              auto geom2 = Part::Geometry::fromShape(ed2, true);
              if (geom1 && geom2
                  && geom1->isSame(*geom2, Precision::Confusion(), Precision::Angular())) {
                  return setOriginFromEdgeMidpoint(ed1);
              }
          }
      }
```

I made a lambda here to simplify the reply, but it could be a private method instead.

File: src/Mod/Measure/App/MeasureAngle.cpp [hunk 4]
```diff
@@ -211,6 +224,214 @@ gp_Vec MeasureAngle::location2()
...
+            Handle(Geom_Curve) curve = intersector.Line(1);
+
+            gp_Pnt refPnt = loc1.XYZ();
+
+            GeomAPI_ProjectPointOnCurve proj(refPnt, curve);
+            if (proj.NbPoints() > 0) {
+                outOrigin = proj.Point(1);
+                return true;
+            }
+        }
```
Comment (hyarion) [inline src/Mod/Measure/App/MeasureAngle.cpp]: could this be reduced to something like the following?

```c++
      gp_Pln pln1(gp_Pnt(location1().XYZ()), gp_Dir(vector1()));
      gp_Pln pln2(gp_Pnt(location2().XYZ()), gp_Dir(vector2()));

      gp_Lin intersectionLine;
      if (Part::intersect(pln1, pln2, intersectionLine)) {
          gp_Pnt refPnt(location1().XYZ());
          GeomAPI_ProjectPointOnCurve proj(refPnt, new Geom_Line(intersectionLine));
          if (proj.NbPoints() > 0) {
              outOrigin = proj.Point(1);
              return true;
          }
      }
```

File: src/Mod/Measure/App/MeasureAngle.cpp [hunk 5]
```diff
@@ -211,6 +224,214 @@ gp_Vec MeasureAngle::location2()
...
+        Handle(Geom_Line) line1 = new Geom_Line(loc1.XYZ(), vector1);
+        Handle(Geom_Line) line2 = new Geom_Line(loc2.XYZ(), vector2);
+
+        GeomAPI_ExtremaCurveCurve intersector(line1, line2);
+        if (intersector.NbExtrema() > 0) {
+            gp_Pnt p1, p2;
+            intersector.NearestPoints(p1, p2);
+            outOrigin = p1;
+            return true;
+        }
```
Comment (hyarion) [inline src/Mod/Measure/App/MeasureAngle.cpp]: I might be missing something but can't we use `Part::closestPointsOnLines()` for this?

```c++
      gp_Lin lin1(gp_Pnt(location1().XYZ()), gp_Dir(vector1()));
      gp_Lin lin2(gp_Pnt(location2().XYZ()), gp_Dir(vector2()));
      gp_Pnt p1, p2;
      Part::closestPointsOnLines(lin1, lin2, p1, p2);
      outOrigin = p1;
```

File: src/Mod/Measure/App/MeasureAngle.cpp [hunk 6]
```diff
@@ -211,6 +224,214 @@ gp_Vec MeasureAngle::location2()
...
+        Handle(Geom_Line) line1 = new Geom_Line(location1().XYZ(), vector1());
+        Handle(Geom_Line) line2 = new Geom_Line(location2().XYZ(), vector2());
+
+        GeomAPI_ExtremaCurveCurve intersector(line1, line2);
+        if (intersector.NbExtrema() > 0) {
+            gp_Pnt p1, p2;
+            intersector.NearestPoints(p1, p2);
+            outOrigin = p2;
+            return true;
+        }
```
Comment (hyarion) [inline src/Mod/Measure/App/MeasureAngle.cpp]: Can we use closestPointsOnLines too?
```c++
      gp_Lin lin1(gp_Pnt(location1().XYZ()), gp_Dir(vector1()));
      gp_Lin lin2(gp_Pnt(location2().XYZ()), gp_Dir(vector2()));
      gp_Pnt p1, p2;
      Part::closestPointsOnLines(lin1, lin2, p1, p2);
      outOrigin = p2;
```

File: src/Mod/Measure/App/MeasureAngle.cpp [hunk 7]
```diff
@@ -211,6 +224,214 @@ gp_Vec MeasureAngle::location2()
...
+        // here we take the face as deciding factor
+        gp_Vec faceNormal;
+        faceNormal = (s1.ShapeType() == TopAbs_FACE) ? vector1() : vector2();
+        if (direction1.Dot(faceNormal) < 0) {
+            direction1 = -direction1;
+        }
+        if (direction2.Dot(faceNormal) < 0) {
+            direction2 = -direction2;
+        }
+    }
```
Comment (hyarion) [inline src/Mod/Measure/App/MeasureAngle.cpp]: As discussed, this looks a bit odd as it measures the normal.

I'm not sure if the following is correct, but AI suggested this:

```c++
      bool s1IsFace = (s1.ShapeType() == TopAbs_FACE);
      gp_Vec faceNormal = s1IsFace ? vector1() : vector2();
      gp_Vec edgeDir    = s1IsFace ? vector2() : vector1();
      gp_Vec edgeLoc    = s1IsFace ? location2() : location1();

      // Orient edge direction away from the origin
      if (edgeDir.Dot(gp_Vec(outOrigin.XYZ()) - edgeLoc) > 0) {
          edgeDir = -edgeDir;
      }

      gp_Vec normalHat = faceNormal.Normalized();

      // Project edge onto the face plane — this is the "flat" leg
      gp_Vec edgeOnFace = edgeDir - normalHat * edgeDir.Dot(normalHat);
      if (edgeOnFace.Magnitude() < Precision::Confusion()) {
          // Edge is perpendicular to face — angle is 90°, pick any in-plane direction
          edgeOnFace = faceNormal.IsParallel(gp_Vec(1, 0, 0), Precision::Angular())
              ? gp_Vec(0, 1, 0)
              : gp_Vec(1, 0, 0).Crossed(normalHat).Normalized();
      }
      edgeOnFace.Normalize();

      // The measurement plane is spanned by N and edgeOnFace.
      // Project the full edge direction into this plane.
      gp_Vec planeNormal = normalHat.Crossed(edgeOnFace).Normalized();
      gp_Vec edgeInPlane = edgeDir - planeNormal * edgeDir.Dot(planeNormal);
      edgeInPlane.Normalize();

      // leg 1: along the face (the projection)
      // leg 2: the edge projected into the measurement plane
      direction1 = edgeOnFace;
      direction2 = edgeInPlane;
```

File: src/Mod/Measure/App/MeasureAngle.cpp [hunk 8]
```diff
@@ -211,6 +224,214 @@ gp_Vec MeasureAngle::location2()
...
+    gp_Pnt p2_2 = BRep_Tool::Pnt(v2_2);
+
+    double tol = Precision::Confusion();
+    bool matchStartStart = p1_1.IsEqual(p2_1, tol) && p1_2.IsEqual(p2_2, tol);
+    bool matchStartEnd = p1_1.IsEqual(p2_2, tol) && p1_2.IsEqual(p2_1, tol);
+
+    return matchStartStart || matchStartEnd;
+}
+
+bool MeasureAngle::setOrigin(TopoDS_Shape& s1, TopoDS_Shape& s2)
```
Comment (hyarion) [inline src/Mod/Measure/App/MeasureAngle.cpp:230]: I am wondering if `setOrigin` and `setDirections` naming is a bit misleading.

These methods compute geometric results and store them. Names like `computeOrigin` and `computeDirections` might better communicate their behavior. What do you think?

File: src/Mod/Measure/App/MeasureAngle.cpp [hunk 9]
```diff
@@ -211,6 +224,214 @@ gp_Vec MeasureAngle::location2()
...
+        // should not reach here
+        return false;
+    }
+
+    return true;
+}
+
+bool MeasureAngle::getDirections(gp_Vec& dir1, gp_Vec& dir2)
+{
+    if (direction1.Magnitude() == 0 || direction2.Magnitude() == 0) {
```
Comment (hyarion) [inline src/Mod/Measure/App/MeasureAngle.cpp]: float equality here, how about using `< Precision::Confusion()`?

File: src/Mod/Measure/Gui/SoScreenSpaceScale.cpp [hunk 10]
```diff
@@ -0,0 +1,111 @@
...
+    if (state->isElementEnabled(SoFocalDistanceElement::getClassStackIndex())) {
+        float focal = SoFocalDistanceElement::get(state);
+        referencePoint = vv.getSightPoint(focal);
+    }
+
+    float scale = vv.getWorldToScreenScale(referencePoint, 1.0f);
+    scale /= float(vp_size[0]);
+
+    float newScale = scale * referenceSize.getValue();
+    if (finalScale.getValue() != newScale) {
```
Comment (hyarion) [inline src/Mod/Measure/Gui/SoScreenSpaceScale.cpp:68]: float equality here. Should we use a tolerance?

File: src/Mod/Measure/App/MeasureAngle.cpp [hunk 11]
```diff
@@ -28,8 +28,21 @@
...
+#include <TopExp_Explorer.hxx>
+#include <TopoDS.hxx>
+#include <TopoDS_Shape.hxx>
+#include <TopoDS_Edge.hxx>
+#include <TopoDS_Vertex.hxx>
+#include <TopExp.hxx>
+#include <BRep_Tool.hxx>
 
 #include "MeasureAngle.h"
+#include "Mod/Part/App/PartFeature.h"
```
Comment (hyarion) [inline src/Mod/Measure/App/MeasureAngle.cpp]:
```suggestion
#include <Mod/Part/App/PartFeature.h>
```

File: src/Mod/Measure/App/MeasureAngle.cpp (hunk 8 above)
Comment (YashSuthar983) [reply src/Mod/Measure/App/MeasureAngle.cpp:230]: i think setorigin and set direction good as they are related to measure object.

File: src/Mod/Measure/App/MeasureAngle.cpp [hunk 12]
```diff
@@ -227,35 +464,42 @@ App::DocumentObjectExecReturn* MeasureAngle::execute()
...
 
-        // get oriented angle wrt normal axis
-        Base::Vector3d normalAxis = (vec1.Cross(vec2)).Normalize();
-        Angle.setValue(Base::toDegrees(vec1.GetAngleOriented(vec2, normalAxis)));
+
+    double angleRad = direction1.Angle(direction2);
+
+    // because of face normal are perpendicular to face
+    if (mCase == FaceFace) {
+        angleRad = M_PI - angleRad;
```
Comment (hyarion) [inline src/Mod/Measure/App/MeasureAngle.cpp]: We try to avoid the old math defines and use `std::numbers` from `#include <numbers>` instead
```suggestion
        angleRad = std::numbers::pi - angleRad;
```

File: src/Mod/Measure/Gui/ViewProviderMeasureAngle.cpp [hunk 13]
```diff
@@ -186,61 +202,87 @@ SbMatrix ViewProviderMeasureAngle::getMatrix()
...
+        gp_Vec xAxis = (loc1 - originVector).Normalized();
+        gp_Vec zAxis;
+        gp_Vec yAxis;
+
+        // need to review this but works
+        if (originFound) {
+            if (measurmentCase == MeasureAngle::EdgeEdge) {
+                xAxis = adjustedVector1.Normalized();
+            }
+            if (measurmentCase == MeasureAngle::FaceFace) {
```
Comment (hyarion) [inline src/Mod/Measure/Gui/ViewProviderMeasureAngle.cpp]:
```suggestion
            else if (measurmentCase == MeasureAngle::FaceFace) {
```

File: src/Mod/Measure/Gui/ViewProviderMeasureAngle.cpp [hunk 14]
```diff
@@ -186,61 +202,87 @@ SbMatrix ViewProviderMeasureAngle::getMatrix()
...
-        else {
-            // find halfway point in between extrema points for dimension origin.
-            gp_Vec vec1(extremaPoint1.XYZ());
-            gp_Vec vec2(extremaPoint2.XYZ());
-            gp_Vec connection(vec2 - vec1);
-            Standard_Real distance = connection.Magnitude();
-            connection.Normalize();
-            connection *= (distance / 2.0);
-            dimensionOriginPoint.SetXYZ((vec1 + connection).XYZ());
+        // need testing before removethis
```
Comment (hyarion) [inline src/Mod/Measure/Gui/ViewProviderMeasureAngle.cpp]: Wip comment left in code. Is this still a problem that we need to address before merging?

File: src/Mod/Measure/Gui/ViewProviderMeasureAngle.cpp [hunk 15]
```diff
@@ -186,61 +202,87 @@ SbMatrix ViewProviderMeasureAngle::getMatrix()
...
-            thirdPoint = extrema2Vector + projectionVector;
-            gp_Vec hyp(thirdPoint - originVector);
-            hyp.Normalize();
-            gp_Vec otherSide(loc1 - originVector);
-            otherSide.Normalize();
+        gp_Vec xAxis = (loc1 - originVector).Normalized();
+        gp_Vec zAxis;
+        gp_Vec yAxis;
+
+        // need to review this but works
```
Comment (hyarion) [inline src/Mod/Measure/Gui/ViewProviderMeasureAngle.cpp]: Same here, the comment should be removed or we need to act on it.

File: src/Mod/Measure/Gui/ViewProviderMeasureAngle.cpp [hunk 16]
```diff
@@ -326,28 +390,268 @@ ViewProviderMeasureAngle::ViewProviderMeasureAngle()
...
+    }
+    normalStartPoint1.setValue(0, 0, 0);
+    normalStartPoint2.setValue(0, 0, 0);
+
     // Set Label
     setLabelValue(static_cast<Measure::MeasureBase*>(pcObject)->getResultString());
+
+    bool flipped = IsFlipped.getValue();
+    isArcFlipped.setValue(flipped);
+    sectorArcRotation.setValue(flipped ? M_PI : 0.0f);
```
Comment (hyarion) [inline src/Mod/Measure/Gui/ViewProviderMeasureAngle.cpp]: Use `std::numbers::pi` from `<numbers>` instead of the old `M_PI`

File: src/Mod/Measure/Gui/ViewProviderMeasureAngle.cpp [hunk 17]
```diff
@@ -186,61 +202,87 @@ SbMatrix ViewProviderMeasureAngle::getMatrix()
...
+        gp_Pnt dimensionOriginPoint;
+        dimensionOriginPoint.SetCoord(0, 0, 0);
+        bool originFound = false;
+        gp_Vec thirdPoint;
+        gp_Vec adjustedVector1;
+        gp_Vec adjustedVector2;
+        measurement->getDirections(adjustedVector1, adjustedVector2);
 
-        GeomAPI_ExtremaCurveCurve extrema(heapLine1, heapLine2);
+        auto measurmentCase = measurement->measurementCase();
```
Comment (hyarion) [inline src/Mod/Measure/Gui/ViewProviderMeasureAngle.cpp]: You have a typo here: `measurmentCase` -> `measurementCase`.

File: src/Mod/Measure/Gui/TaskMeasure.cpp [hunk 18]
```diff
@@ -586,8 +586,8 @@ bool TaskMeasure::reject()
     removeObject();
     closeDialog();
 
-    // Abort transaction
-    App::GetApplication().closeActiveTransaction(true);
+    // Commit transaction
+    App::GetApplication().closeActiveTransaction();
```
Comment (hyarion) [inline src/Mod/Measure/Gui/TaskMeasure.cpp]: This changed from `closeActiveTransaction(true)` (abort) to `closeActiveTransaction()` (commit). Was this intentional?

The old behavior aborted the entire "Add Measurement" transaction when the user cancelled, cleanly undoing everything. The new behavior commits the transaction after `removeObject()`, which records both creation and deletion. Both work, but aborting is semantically cleaner for a cancel operation. If this change was needed to fix the restore/label-to-origin issue mentioned in the PR description, a comment explaining why would be helpful.

File: src/Mod/Measure/Gui/SoScreenSpaceScale.h [hunk 19]
```diff
@@ -0,0 +1,66 @@
...
+ ***************************************************************************/
+
+#ifndef MEASUREGUI_SOSCREENSPACESCALE_H
+#define MEASUREGUI_SOSCREENSPACESCALE_H
+
+#include <Inventor/nodes/SoTransformation.h>
+
+#include <Inventor/actions/SoGLRenderAction.h>
+
+#include <Inventor/actions/SoCallbackAction.h>
```
Comment (hyarion) [inline src/Mod/Measure/Gui/SoScreenSpaceScale.h]: These action headers (`SoCallbackAction.h`, `SoGetBoundingBoxAction.h`, `SoPickAction.h`, `SoGetPrimitiveCountAction.h`) are only needed in the .cpp file — the header only needs forward declarations (or nothing, since the method signatures use pointers). Moving them to the .cpp would reduce header coupling.

File: src/Mod/Measure/App/MeasureAngle.cpp [hunk 20]
```diff
@@ -211,6 +227,225 @@ gp_Vec MeasureAngle::location2()
...
+    _isImgOrigin = true;
+
+    bool faceIsS1 = (s1.ShapeType() == TopAbs_FACE);
+    gp_Vec faceNormal = ((faceIsS1) ? vector1() : vector2()).Normalized();
+    gp_Vec edgeDir = ((faceIsS1) ? vector2() : vector1()).Normalized();
+    gp_Pnt faceLoc = gp_Pnt(((faceIsS1) ? location1() : location2()).XYZ());
+    gp_Pnt edgeLoc = gp_Pnt(((faceIsS1) ? location2() : location1()).XYZ());
+
+    // projection direction from the edge onto the face
+    gp_Vec projection = edgeDir - (faceNormal * edgeDir.Dot(faceNormal));
```
Comment (hyarion) [inline src/Mod/Measure/App/MeasureAngle.cpp]: Suggestion: this projection (`edgeDir - faceNormal * edgeDir.Dot(faceNormal)`) is equivalent to `Base::Vector3d::ProjectToPlane(origin, normal)`. Using the existing utility might be clearer:

```cpp
Base::Vector3d edgeDirVec(edgeDir.X(), edgeDir.Y(), edgeDir.Z());
Base::Vector3d normalVec(faceNormal.X(), faceNormal.Y(), faceNormal.Z());
edgeDirVec.ProjectToPlane(Base::Vector3d(0,0,0), normalVec);
```

Same applies to the identical projection in `setDirections()` at line 412.

File: src/Mod/Measure/App/MeasureAngle.h [hunk 21]
```diff
@@ -47,6 +49,13 @@ class MeasureExport MeasureAngle: public Measure::MeasureBaseExtendable<Part::Me
     PROPERTY_HEADER_WITH_OVERRIDE(Measure::MeasureAngle);
 
 public:
+    enum MeasurementCase
```
Comment (hyarion) [inline src/Mod/Measure/App/MeasureAngle.h]: Consider using `enum class` as recommended here https://freecad.github.io/DevelopersHandbook/bestpractices/c++practices#enums:

```suggestion
    enum class MeasurementCase
```

This would require qualifying usages as `MeasurementCase::FaceFace` etc., but prevents implicit conversions and namespace pollution.

File: src/Mod/Measure/App/MeasureAngle.h [hunk 22]
```diff
@@ -90,8 +99,34 @@ class MeasureExport MeasureAngle: public Measure::MeasureBaseExtendable<Part::Me
...
+    bool getDirections(gp_Vec& vec1, gp_Vec& vec2);  // this is not the normals(its is adjusted for
+                                                     // arc visualization)
+
 private:
+    gp_Vec direction1;
+    gp_Vec direction2;
+    gp_Pnt outOrigin;
+    MeasurementCase mCase;
+    // if no common vertex/edge found, use imaginary origin by extending
+    bool _isImgOrigin;
```
Comment (hyarion) [inline src/Mod/Measure/App/MeasureAngle.h]: These members are not initialized at declaration. They get set in `execute()`, but if any code path reads them before `execute()` runs (e.g. the view provider constructor querying `getDirections()` or `isImgOrigin()`), it's undefined behavior. At minimum, initialize at declaration:

```suggestion
    MeasurementCase mCase{MeasurementCase::FaceFace};
    bool _isImgOrigin{false};
```

File: src/Mod/Measure/Gui/SoScreenSpaceScale.cpp
Comment (hyarion) [inline src/Mod/Measure/Gui/SoScreenSpaceScale.cpp:1]: There's an existing `Gui::SoAutoZoomTranslation` in `src/Gui/Inventor/SoAutoZoomTranslation.h` that does nearly the same thing:
* same base class (`SoTransformation`)
* same overrides
* same `getWorldToScreenScale` approach.

The key difference is that this node exposes `finalScale` as a connectable field for SoCalculator, which `SoAutoZoomTranslation` doesn't have.

Consider either adding the `finalScale` field to `SoAutoZoomTranslation` (since it's in `Gui::` and available to all modules) or at minimum adding a comment here explaining why a separate node was needed. This avoids the impression of duplicated code.

File: src/Mod/Measure/Gui/ViewProviderMeasureAngle.cpp [hunk 23]
```diff
@@ -186,61 +202,87 @@ SbMatrix ViewProviderMeasureAngle::getMatrix()
...
+            if (measurmentCase == MeasureAngle::EdgeEdge) {
+                xAxis = adjustedVector1.Normalized();
+            }
+            if (measurmentCase == MeasureAngle::FaceFace) {
+                zAxis = adjustedVector1.Crossed(adjustedVector2);
+            }
+            else {
+                zAxis = adjustedVector2.Crossed(adjustedVector1);
+            }
+            zAxis.Normalize();
```
Comment (hyarion) [inline src/Mod/Measure/Gui/ViewProviderMeasureAngle.cpp]: The manual axis orthogonalization here (cross products + normalize to build a coordinate system) could be simplified with `Base::Rotation::makeRotationByAxes(xdir, ydir, zdir, "ZXY")` which handles orthogonalization automatically and ensures a proper right-handed frame. Then convert to `SbMatrix` via `Base::Matrix4D`.

**Review by hyarion — COMMENTED** [review]
One architectural suggestion; the new `setOrigin`/`computeOrigin`/`setDirections` methods (~200 lines) do a fair amount of raw OCCT work that existing helpers already cover:
* `Part::VectorAdapter` (`src/Mod/Part/App/VectorAdapter.h`): extracts normals from faces and directions from edges, handling surface types and orientation
* `getEdgeMidPointProps()` (`src/Mod/Part/App/GizmoHelper.h`): computes edge midpoints with proper curve evaluation, replacing the manual `TopExp::Vertices` + averaging.

The new logic here (origin computation, direction adjustment for arc visualization) is the valuable part, but it's buried in OCCT plumbing these utilities already handle.

Factoring that out would make the core logic shorter and more consistent with the rest of the codebase. What do you think?

I've also made some inline review comments:

File: src/Mod/Measure/Gui/ViewProviderMeasureAngle.cpp (hunk 13 above)
Comment (YashSuthar983) [reply src/Mod/Measure/Gui/ViewProviderMeasureAngle.cpp]: it will break orientation

File: src/Mod/Measure/Gui/TaskMeasure.cpp (hunk 18 above)
Comment (YashSuthar983) [reply src/Mod/Measure/Gui/TaskMeasure.cpp]: ya it is to apply the label drag and sector change logic only

File: src/Mod/Measure/Gui/SoScreenSpaceScale.cpp
Comment (YashSuthar983) [reply src/Mod/Measure/Gui/SoScreenSpaceScale.cpp:1]: added comment explaining why we need this.

File: src/Mod/Measure/Gui/ViewProviderMeasureAngle.cpp (hunk 23 above)
Comment (YashSuthar983) [reply src/Mod/Measure/Gui/ViewProviderMeasureAngle.cpp]: i will prefer not to refactor it right now.

File: src/Mod/Measure/Gui/ViewProviderMeasureAngle.cpp [hunk 24]
```diff
@@ -364,6 +632,85 @@ Measure::MeasureAngle* ViewProviderMeasureAngle::getMeasureAngle()
...
+    angle += sectorArcRotation.getValue();
+
+    if (obj->isImgOrigin()) {
+        gp_Vec loc1 = obj->location1();
+        gp_Vec loc2 = obj->location2();
+        if (loc1.Magnitude() < Precision::Confusion() || loc2.Magnitude() < Precision::Confusion()) {
+            return;
+        }
+
+        SbMatrix invMatrix = getMatrix().inverse();
```
Comment (hyarion) [inline src/Mod/Measure/Gui/ViewProviderMeasureAngle.cpp]: In `redrawAnnotation` we're wrapping getMatrix() in a try-catch since it can throw `Base::RuntimeError`, but here it is called without protection. If it throws, the exception will propagate unhandled.

File: src/Mod/Measure/App/MeasureAngle.cpp [hunk 25]
```diff
@@ -211,6 +227,243 @@ gp_Vec MeasureAngle::location2()
...
+    // cant reach here
+    return false;
+}
+
+bool MeasureAngle::computeOriginFaceFace(TopoDS_Shape& s1, TopoDS_Shape& s2)
+{
+    auto setOriginFromEdgeMidpoint = [this](const TopoDS_Edge& edge) -> bool {
+        TopoDS_Vertex v1, v2;
+        TopExp::Vertices(edge, v1, v2);
+        outOrigin = gp_Pnt((BRep_Tool::Pnt(v1).XYZ() + BRep_Tool::Pnt(v2).XYZ()) / 2);
```
Comment (hyarion) [inline src/Mod/Measure/App/MeasureAngle.cpp:254]: Calculating the mean value of the points gives the midpoint for a straight line, but what if the edge is a curve, like an arc or spline?

File: src/Mod/Measure/App/MeasureAngle.cpp [hunk 26]
```diff
@@ -211,6 +227,243 @@ gp_Vec MeasureAngle::location2()
...
+    TopoDS_Edge e1 = TopoDS::Edge(s1);
+    TopoDS_Edge e2 = TopoDS::Edge(s2);
+    TopoDS_Vertex common;
+
+    if (TopExp::CommonVertex(e1, e2, common)) {
+        outOrigin = BRep_Tool::Pnt(common);
+        return true;
+    }
+
+    // get geometricall same vertex
```
Comment (hyarion) [inline src/Mod/Measure/App/MeasureAngle.cpp]:
```suggestion
    // get geometrically same vertex
```

File: src/Mod/Measure/Gui/ViewProviderMeasureBase.cpp [hunk 27]
```diff
@@ -269,16 +301,32 @@ void ViewProviderMeasureBase::onChanged(const App::Property* prop)
...
+    }
 
     ViewProviderDocumentObject::onChanged(prop);
 }
 
 void ViewProviderMeasureBase::draggerChangedCallback(void* data, SoDragger*)
 {
     auto me = static_cast<ViewProviderMeasureBase*>(data);
+    SbVec3f pos = me->pDragger->translation.getValue();
+    me->LabelPosition.setValue(Base::Vector3d(pos[0], pos[1], pos[2]));
```
Comment (hyarion) [inline src/Mod/Measure/Gui/ViewProviderMeasureBase.cpp]: I think `draggerChangedCallback` fires on every mouse move during a drag, so this updates `LabelPosition` (and triggers `onChanged` cascades) on every frame. Since `draggerFinishedCallback` exists and calls `onLabelMoveEnd`, should we moving the `LabelPosition` property update there instead? (I don't think the intermediate positions during dragging needs to be persistant)

File: src/Mod/Measure/Gui/ViewProviderMeasureAngle.cpp [hunk 28]
```diff
@@ -186,73 +202,63 @@ SbMatrix ViewProviderMeasureAngle::getMatrix()
...
-            projectionVector *= legTwo;
-            thirdPoint = extrema2Vector + projectionVector;
-            gp_Vec hyp(thirdPoint - originVector);
-            hyp.Normalize();
-            gp_Vec otherSide(loc1 - originVector);
-            otherSide.Normalize();
+        if (measurementCase == MeasureAngle::MeasurementCase::EdgeEdge) {
+            xAxis = adjustedVector1.Normalized();
+        }
+        if (measurementCase == MeasureAngle::MeasurementCase::FaceFace) {
```
Comment (hyarion) [inline src/Mod/Measure/Gui/ViewProviderMeasureAngle.cpp]: This should be `else if` right?

```suggestion
        else if (measurementCase == MeasureAngle::MeasurementCase::FaceFace) {
```

File: src/Mod/Measure/App/MeasureAngle.cpp (hunk 25 above)
Comment (YashSuthar983) [reply src/Mod/Measure/App/MeasureAngle.cpp:254]: we tipically dont measure angle for curve, arc or spline.
> if (!(type == App::MeasureElementType::LINE || type == App::MeasureElementType::PLANE
              || type == App::MeasureElementType::LINESEGMENT)) {
            return false;
        }

**Review by pierreporte — CHANGES_REQUESTED** [review]
It’s good overall but there is a new problem with the label that doesn’t stick to the measurement. When you rotate the view it moves, and there is an extension arc appearing sometimes. Here is the video:

https://github.com/user-attachments/assets/3d3fee8b-8e04-49ba-ad2f-3df2d1ff64e9

**Comment by pierreporte** [comment]
Can you rebase on #29228 once that PR is merged? I’ll give it a final try to approve it.

**Comment by YashSuthar983** [comment]
@pierreporte  i rebased this branch ,ready for review.

**Review by pierreporte — APPROVED** [review]
Let’s merge this!

**Comment by FEA-eng** [comment]
Lint CI failed, but I guess it's not a fault of the PR
