### PR TITLE
ipatch: attempt to resolve #24188

### LINKED ISSUE #24188: PartDesign: Generic error pop-up on failed operation
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Problem description

When PD operation fails, there's now this generic error pop-up with cropped title:

Image

To see it, just add Additive Box, select its edge and enable fillet. Increase its size until the preview becomes red or just enter 10 mm for the radius. Click OK and this pop-up will appear. There are no other errors messages even in the report view so it's really confusing for users. Maybe it's not specific to Part Design, but I think I've only seen it there.

It has been mentioned in some other issues but I think that it deserves its own report. At least partially, it might be related to stylesheets, but I'm not sure if that's the case.

### Full version info

```shell
OS: Windows 10 build 19045
Architecture: x86_64
Version: 1.1.0dev.14555 (Git shallow)
Build date: 2025/09/23 18:47:15
Build type: Release
Branch: main
Hash: e9ce06155d8d47aad7d6c079bfa8ba54df2b6081
Python 3.11.13, Qt 6.8.3, Coin 4.0.3, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.3.0, IfcOpenShell 0.8.2, OCC 7.8.1
Locale: Polish/Poland (pl_PL)
Navigation Style/Orbit Style/Rotation Mode: CAD/Rounded Arcball/Window center
Stylesheet/Theme/QtStyle: FreeCAD.qss/FreeCAD Light/
Logical DPI/Physical DPI/Pixel Ratio: 96/90.0633/1
```

### Subproject(s) affected?

PartDesign

### Anything else?

_No response_

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by ipatch**
this PR attempts to resolve the issue in the below link,

https://github.com/FreeCAD/FreeCAD/issues/24188

### CODE REVIEW

**Comment by FEA-eng** [comment]
I'm not sure if it's due to this PR, but I get this error right after starting FreeCAD:

```
17:02:07  During initialization the error "cannot import name 'StrEnum' from 'enum' (/usr/lib/python3.10/enum.py)" occurred in /home/ubuntu/Documents/freecad_pop_ups/freecad-source/build/Mod/AddonManager/./InitGui.py
17:02:07  Look into the log file for further information
```

It seems that it does fix the issue, though, at least with my test case (I'll look for more examples later):

image

**Comment by furgo16** [comment]
The StrEnum message was due to the Add-on Manager. The fix was committed yesterday.

File: src/Mod/PartDesign/Gui/TaskFeatureParameters.cpp [hunk 1]
```diff
@@ -164,6 +164,11 @@ bool TaskDlgFeatureParameters::accept()
             // object was already computed, nothing more to do with it...
             Gui::cmdAppDocument(feature, "purgeTouched()");
 
+            // NOTE: @ipatch, below if block should resolve https://github.com/FreeCAD/FreeCAD/issues/24188
```
Comment (chennes) [inline src/Mod/PartDesign/Gui/TaskFeatureParameters.cpp]: Thanks for the fix. As a general rule we only add comments about closing specific bugs in particularly strange cases, where the code itself looks sketchy so need additional explanation. I'm not sure it's really needed here.
```suggestion
```

File: src/Mod/PartDesign/Gui/TaskFeatureParameters.cpp [hunk 2]
```diff
@@ -191,12 +196,23 @@ bool TaskDlgFeatureParameters::accept()
...
+      QString statusText = QString::fromUtf8(getObject()->getStatusString());
+
+      // generic, fallback error message
+      if (errorText == "Error" || errorText.isEmpty()) {
+        if (!statusText.isEmpty() && statusText != "Error") {
+          errorText = statusText;
+        } else {
+          errorText = tr("The feature could not be created with the given parameters.\n"
+              "The geometry may be invalid or the parameters may be incompatible.\n"
+              "Please adjust the parameters and try again.");
```
Comment (chennes) [inline src/Mod/PartDesign/Gui/TaskFeatureParameters.cpp:209]: @kaktusus heads-up to translators that the nature of this bug effectively requires a string addition to resolve it, so I plan on merging despite the current string freeze.

**Comment by kaktusus** [comment]
That is excellent.
One less error to fix.
