### PR TITLE
fix build with Qt < 6.0 by using associatedWidgets()

### LINKED ISSUE #28855: Commit b885dcb breaks building on Ubuntu
### Problem description

Trying to compile the latest commit I encountered a make error. I have gone back through the commits and found that this happened with commit [b885dcb](https://github.com/FreeCAD/FreeCAD/commit/b885dcb1c28bdf7affe4815133d17fb327e9c68b) "Gui: Fix crash in ActionGroup::onHovered during widget destruction" The previous commit works (bd3ab8d), this one does not.
The last time a similar problem happened it was because another dependency (python3-lark) had been added, is another package now required? cmake runs without error.

### Workbench affected?

None

### Steps to reproduce

Building according to official instructions on Ubuntu Linux 24.04, amd64. 

### Expected behavior

Should build

### Actual behavior

Fails with the errors shown in the attached log. 
[make.log](https://github.com/user-attachments/files/26347928/make.log)
cmake runs without errors, the output from this is shown here:
[cmake-output.txt](https://github.com/user-attachments/files/26348153/cmake-output.txt)

### Development version About Info (in Safe Mode)

```shell
N/A
```

### Last known good version (optional)

```shell
Commit bd3ab8d works
```

### PR DESCRIPTION
**Pull request by rehan-ahmed-aix**
Fixes build error on Qt 5.15 (and older Qt 6 versions) by using associatedWidgets() as a fallback instead of associatedObjects() for Qt < 6.0

## Issues
Fixes #28855

We basically add a version check so we use associatedWidgets() for older Qt versions and associatedObjects() for Qt 6.0+.

### CODE REVIEW

File: src/Gui/Action.cpp [hunk 1]
```diff
@@ -608,8 +608,16 @@ void ActionGroup::onHovered(QAction* act)
     // crash if called during widget destruction when synthetic enter/leave
     // events are processed.
     QMenu* foundMenu = nullptr;
+
+#if QT_VERSION >= QT_VERSION_CHECK(6, 4, 0)
+    // Use associatedObjects() which includes non-widget associated objects.
     const auto associatedObjects = act->associatedObjects();
     for (QObject* obj : associatedObjects) {
+#else
+    // Use associatedWidgets() for Qt < 6.4 (associatedObjects() requires Qt 6.4+).
```
Comment (Lgt2x) [inline src/Gui/Action.cpp]: No it does not require 6.4+, don't trust your LLM blindly https://doc.qt.io/qt-6/qaction.html#associatedObjects

Please fix your version check to include Qt >= 6.0

File: src/Gui/Action.cpp [hunk 2]
```diff
@@ -608,8 +608,16 @@ void ActionGroup::onHovered(QAction* act)
...
+
+#if QT_VERSION >= QT_VERSION_CHECK(6, 4, 0)
+    // Use associatedObjects() which includes non-widget associated objects.
     const auto associatedObjects = act->associatedObjects();
     for (QObject* obj : associatedObjects) {
+#else
+    // Use associatedWidgets() for Qt < 6.4 (associatedObjects() requires Qt 6.4+).
+    const auto associatedWidgets = act->associatedWidgets();
+    for (QWidget* obj : associatedWidgets) {
+#endif
```
Comment (kadet1090) [inline src/Gui/Action.cpp]:
```suggestion
    const auto associatedWidgets = act->associatedWidgets();
    for (QWidget* obj : associatedWidgets) {
```

Since the only action is for QMenu's the `associatedWidgets` seems like a better pick anyway - we don't need to traverse all QObjects since we know that QMenu is QWidget anyway. @Lgt2x is it right?

Comment (Lgt2x) [reply src/Gui/Action.cpp]: It's deprecated https://doc.qt.io/qt-6/qaction-obsolete.html#associatedWidgets

The code is right, but it does not test for the right qt version

File: src/Gui/Action.cpp (hunk 1 above)
Comment (rehan-ahmed-aix) [reply src/Gui/Action.cpp]: My bad. I've made the necessary changes. I'll make sure to verify against the official docs next time. Thank you for catching that.

**Review by Lgt2x — APPROVED** [review]

**Review by furgo16 — APPROVED** [review]
I can attest that it works, as I carry a patch that does exactly that to compile locally on Qt 5.
