### PR TITLE
Part/Toponaming: Tests for flushElementMap and resetElementMap

### LINKED ISSUE #12594: [Problem] Possible design flaw about overloaded method
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

In ComplexGeoData there is this virtual method declared:
```
    virtual ElementMapPtr resetElementMap(ElementMapPtr elementMap = ElementMapPtr(),
                                          ElementMapResetPolicy forceEmpty = ForceEmptyMap);
```
In the sub-class TopoShape a method with the same name but different number of arguments is re-defined
```
    virtual Data::ElementMapPtr resetElementMap(
        Data::ElementMapPtr elementMap=Data::ElementMapPtr());
```
Because the method has a different signature it overloads the method of the base class instead of overriding it. This leads to the compiler warning: `'Part::TopoShape::resetElementMap' hides overloaded virtual function [-Woverloaded-virtual]
`
Because TopoShape is a central class that is used by a lot of classes directly or indirectly a full rebuild prints this warning a several thousand times.

Usually, in such cases one could add this line to the class declaration of TopoShape:
`using ComplexGeoData::resetElementMap;`
but because in both versions all argument are optional this leads of course to an error that `resetElementMap` is ambiguous.

So, this is a strong indication that there is a design flaw which may result into unexpected behaviour.

### Full version info

```shell
Not relevant here
```

### Subproject(s) affected?

Part

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by CalligaroV**
Importing methods `flushElementMap()` and `resetElementMap()` that override the same methods (if present) in `ComplexGeoData`

fixes #12594

### CODE REVIEW

**Comment by CalligaroV** [comment]
In draft status until the tests for these new methods are added

File: src/Mod/Part/App/TopoShape.h [hunk 1]
```diff
@@ -925,6 +925,9 @@ class PartExport TopoShape: public Data::ComplexGeoData
     void mapSubElement(const TopoShape &other,const char *op=nullptr, bool forceHasher=false);
     void mapSubElement(const std::vector<TopoShape> &shapes, const char *op=nullptr);
     void mapSubElementsTo(std::vector<TopoShape>& shapes, const char* op = nullptr) const;
+    void flushElementMap() const;
```
Comment (bgbsww) [inline src/Mod/Part/App/TopoShape.h:928]: I think the lint errors above this point can be ignored, although that last one points at an error I must have made and will correct.   Those errors are waiting for an overall cleanup pass on this file.

File: src/Mod/Part/App/TopoShape.h [hunk 2]
```diff
@@ -925,6 +925,9 @@ class PartExport TopoShape: public Data::ComplexGeoData
     void mapSubElement(const TopoShape &other,const char *op=nullptr, bool forceHasher=false);
     void mapSubElement(const std::vector<TopoShape> &shapes, const char *op=nullptr);
     void mapSubElementsTo(std::vector<TopoShape>& shapes, const char* op = nullptr) const;
+    void flushElementMap() const;
+    virtual Data::ElementMapPtr resetElementMap(
+            Data::ElementMapPtr elementMap=Data::ElementMapPtr());
```
Comment (bgbsww) [inline src/Mod/Part/App/TopoShape.h:930]: Switching from virtual to override on these seems appropriate.   The 'overridden' spellcheck below also makes sense

File: src/Mod/Part/App/TopoShape.h (hunk 1 above)
Comment (CalligaroV) [reply src/Mod/Part/App/TopoShape.h:928]: Ok, I'll leave this as is for now.

File: src/Mod/Part/App/TopoShape.h (hunk 2 above)
Comment (CalligaroV) [reply src/Mod/Part/App/TopoShape.h:930]: Fine, I'll change this method from virtual to override and update the comment below.

File: tests/src/Mod/Part/App/TopoShapeExpansion.cpp [hunk 3]
```diff
@@ -385,6 +385,120 @@ TEST_F(TopoShapeExpansionTest, MapperHistoryGenerated)
...
+    shapeWithMapAfterReset.resetElementMap(newElementMapPtr);
+    shapeWithMapAfterEmptyReset.resetElementMap(nullptr);
+
+    // Assert
+    // Check that the original maps haven't been modified
+    EXPECT_EQ(shapeWithoutMap.getElementMapSize(false), 0);
+    EXPECT_EQ(shapeWithMap.getElementMapSize(false), 3);
+
+    // Check that the two shapes have the same map
+    EXPECT_EQ(shapeWithoutMapAfterReset.getElementMap(), shapeWithoutMapAfterReset.getElementMap());
```
Comment (bgbsww) [inline tests/src/Mod/Part/App/TopoShapeExpansion.cpp:440]: Should both sides have the same clause here?

File: tests/src/Mod/Part/App/TopoShapeExpansion.cpp [hunk 4]
```diff
@@ -385,6 +385,120 @@ TEST_F(TopoShapeExpansionTest, MapperHistoryGenerated)
...
+}
+
+TEST_F(TopoShapeExpansionTest, flushElementMapTest)
+{
+    // Arrange
+    // Creating various TopoShapes to check different conditions
+
+    // A TopoShape with a map that won't be flushed
+    auto shapeWithtMapNotFlushed {
+        TopoShape(BRepBuilderAPI_MakeEdge(gp_Pnt(-1.0, 0.0, 0.0), gp_Pnt(1.0, 0.0, 0.0)).Edge(),
```
Comment (bgbsww) [inline tests/src/Mod/Part/App/TopoShapeExpansion.cpp:458]: Witht -> With ?

File: src/App/ComplexGeoData.h [hunk 5]
```diff
@@ -270,12 +270,12 @@ class AppExport ComplexGeoData: public Base::Persistence, public Base::Handled
...
-                                          ElementMapResetPolicy forceEmpty = ForceEmptyMap)
+    virtual ElementMapPtr resetElementMap(ElementMapPtr elementMap = ElementMapPtr()/* ,
+                                          ElementMapResetPolicy forceEmpty = ForceEmptyMap */)
     {
-        if (!elementMap && forceEmpty == ForceEmptyMap) {
-            elementMap = std::make_shared<Data::ElementMap>();
-        }
+        // if (!elementMap && forceEmpty == ForceEmptyMap) {
+        //     elementMap = std::make_shared<Data::ElementMap>();
+        // }
```
Comment (bgbsww) [inline src/App/ComplexGeoData.h:278]: Agree.  I think you can delete these, not just comment out.  Here, above and below.

**Review by bgbsww — COMMENTED** [review]
Looks good.  This addresses #12594 I think

**Comment by bgbsww** [comment]
The CI failures are mostly related to places where this code causes elementMaps to exist (correctly), and thus changes the test results which need to be modified to match these correct results.  Also, look out for a case or two where the OCCT versions between platforms result in the allElementsMatch not working and elementsMatch has to be used instead.

File: src/App/ElementMap.cpp [hunk 6]
```diff
@@ -562,6 +562,11 @@ MappedName ElementMap::setElementName(const IndexedName& element, const MappedNa
         }
     }
 
+    // Originally in ComplexGeoData::setElementName
+    // LinkStable/src/App/ComplexGeoData.cpp#L1631
+    // if(!_ElementMap)
+    //     resetElementMap(std::make_shared<ElementMap>());
+
```
[the remark this answers is not in the document]
Comment (CalligaroV) [reply src/App/ElementMap.cpp:569]: Exactly.

`_ElementMap` (now `_elementMap`) is an `ElementMapPtr` object.
In RT fork it was accessible because the class it belongs to was in `ComplexGeoData`, now it isn't anymore (the closest object to perform this check could be `this` but it doesn't make much sense and, above all, it cannot be modified while the method is running).

About the comment, sure, a couple of words added to better explain are always a good thing IMO.

File: src/Mod/Part/App/TopoShapeExpansion.cpp [hunk 7]
```diff
@@ -757,9 +757,13 @@ void TopoShape::mapSubElementTypeForShape(const TopoShape& other,
                 }
             }
             char elementType {shapeName(type)[0]};
+
+            // Originally in ComplexGeoData::setElementName
+            // LinkStable/src/App/ComplexGeoData.cpp#L1631
```
Comment (CalligaroV) [inline src/Mod/Part/App/TopoShapeExpansion.cpp:762]: Note to self: add the same comment of `ElementMap::setElementName`, here and on the modifications below

File: tests/src/Mod/Part/App/TopoShapeExpansion.cpp (hunk 3 above)
Comment (CalligaroV) [reply tests/src/Mod/Part/App/TopoShapeExpansion.cpp:440]: Looks I missed something along the way, originally I was checking `shapeWithoutMapAfterReset` and `shapeWithMapAfterReset` (I guess, trying to remember).

They should have the same map as both reset with `newElementMapPtr`.

Fixing it in the next commit

File: tests/src/Mod/Part/App/TopoShapeExpansion.cpp (hunk 4 above)
Comment (CalligaroV) [reply tests/src/Mod/Part/App/TopoShapeExpansion.cpp:458]: Yes of course, typo.

Fixing it in the next commit

**Comment by CalligaroV** [comment]
> The CI failures are mostly related to places where this code causes elementMaps to exist (correctly), and thus changes the test results which need to be modified to match these correct results. Also, look out for a case or two where the OCCT versions between platforms result in the allElementsMatch not working and elementsMatch has to be used instead.

Ok then I'll modify the expected test results, keeping in mind also the different outputs generated by different OCCT versions. Could you point out the tests that need this extra check?

Anyway, how can we say what are supposed to be the right values?
Personally I'd like to avoid changing the tests without knowing what's correct, rather I'll leave the tests (with the correct expected results) to tell us if we're doing the right things or if there's something strange happening, for example because of missing imports.
