### PR TITLE
Part Design: Enforce recompute after UI is fully-initialized

### LINKED ISSUE #25794: PartDesign: Sketches (based on Subshapebinder external references) not updating
### Workbench affected?

Part Design

### Problem description

if you have external references based on subshpaebinder and subshape binder your updated model will be broken.Should be regression 1.0.2 works as expected

https://forum.freecad.org/viewtopic.php?t=101486

```
16:52:33  <PropertyLinks> PropertyLinks.cpp(512): Unnamed#Sketch001.ExternalGeometry missing element reference Unnamed#Binder ;#12:5;:U;XTR;:H122b:7,V;:H122c,V.Vertex1
16:52:33  <PropertyLinks> PropertyLinks.cpp(512): Unnamed#Sketch001.ExternalGeometry missing element reference Unnamed#Binder ;#14:7;:U;XTR;:H122b:7,V;:H122c,V.Vertex3
16:52:33  <Sketch> SketchObject.cpp(9101): Failed to project external geometry in Unnamed#Sketch001: Binder.;#12:5;:U;XTR;:H122b:7,V;:H122c,V
Invalid shape name ?Vertex1
16:52:33  <Sketch> SketchObject.cpp(9101): Failed to project external geometry in Unnamed#Sketch001: Binder.;#14:7;:U;XTR;:H122b:7,V;:H122c,V
Invalid shape name ?Vertex3
16:52:33  <Sketch> SketchObject.cpp(9186): External geometry Unnamed#Sketch001.e5 missing reference: Binder.;#12:5;:U;XTR;:H122b:7,V;:H122c,V
16:52:33  <Sketch> SketchObject.cpp(9186): External geometry Unnamed#Sketch001.e6 missing reference: Binder.;#14:7;:U;XTR;:H122b:7,V;:H122c,V
```

### Steps to reproduce

[binder_error(1).zip](https://github.com/user-attachments/files/23833213/binder_error.1.zip)

Steps to reproduce:
1.Create a sketch and  pad
2.Selec a face of pad and create a subshapebinder
3.Select subshapebinder and create a sketch  with external references from subshapebinder 
4.Create second pad
5.Go to first sketch and change the sketch
6.Subshapebinder will be updated as expected but not the sketch based on binder

### Expected behavior

When subshapebinder updates, sketch with external references based on binder should be updated too

### Actual behavior

https://github.com/user-attachments/assets/40b35cbd-a153-47c5-9e93-4815efb573f2

### Development version About Info (in Safe Mode)

```shell
OS: Windows 10 build 19045
Architecture: x86_64
Version: 1.2.0dev.20251126 (Git shallow)
Build date: 2025/11/26 00:30:17
Build type: Release
Branch: (HEAD detached at de230cf)
Hash: de230cfaa75433441366ad09a4d5fda828e7bfdb
Python 3.11.14, Qt 6.8.3, Coin 4.0.3, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.3.0, IfcOpenShell 0.8.2, OCC 7.8.1
Locale: Turkish/Türkiye (tr_TR)
Navigation Style/Orbit Style/Rotation Mode: Blender/Trackball/Drag at cursor
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/fusion
Logical DPI/Physical DPI/Pixel Ratio: 96/81.5973/1
Installed mods: 
  * CurvedShapes 1.0.13
  * Curves 0.6.61
```

### Last known good version (optional)

```shell
Version 1.0.2 works as expected without those error messages

OS: Windows 10 build 19045
Architecture: x86_64
Version: 1.0.2.39319 (Git) Conda
Build type: Release
Branch: (HEAD detached at 1.0.2)
Hash: 256fc7eff3379911ab5daf88e10182c509aa8052
Python 3.11.13, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: Turkish/Turkey (tr_TR)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Fusion
Installed mods: 
  * CurvedShapes 1.0.13
  * Curves 0.6.61
```

### PR DESCRIPTION
**Pull request by ipatch**
this PR aims at fixing the issue ie. fixes #25794 the issue mentions shapebinder, but the issue is still present ie. can be reproduced without a shapebinder as both I and connor confirmed. the commit that introduced this issue was 92e96839c9 which implemented some optimizations when recomputing objects, however with these optimizations this bug was introduced.

basically commit 92e968 reordered `setChecked()` to be called before `connectSlots()` in the `TaskExtrudeParameters.cpp` this prevented the `onAllFacesToggled()` signal handler from firing during the dialog setup, which basically means `tryRecomputeFeature()` was not being called.

> The Problem:
Without that recompute during Pad dialog setup, sketches with external geometry references to the Pad weren't getting their element references updated correctly. This caused the "missing element reference" errors and broken geometry updates.

i added a explicit `tryRecomputeFeature()` call at the end of the `setupDialog()` to ensure a recompute happens after the ui is fully initialized.

### CODE REVIEW

**Comment by ipatch** [comment]
@ErtugrulEge @drwho495 @Connor9220 

do y'all mind building and testing this locally to make sure nothing unusual happens? i reproduced the steps locally on my end with this fix and the problem was gone.

**Comment by ErtugrulEge** [comment]
Unfortunately, I don't know how to test fixes  locally. but when merged I can as soon as possible

**Comment by drwho495** [comment]
> @ErtugrulEge @drwho495 @Connor9220
> 
> do y'all mind building and testing this locally to make sure nothing unusual happens? i reproduced the steps locally on my end with this fix and the problem was gone.

You should trigger a build in the actions section of your gh repo. (the action should be called: "weekly-build", make sure to select the right branch)

The comment you put is not really correct; the issue is that the vertices on the extrusion are being hashed differently after a second mapping for some reason. It has something to do with the sketch element map or some other property (if you mess with the base sketch by reopening and closing, you can avoid this issue.)

If I can figure out how to make a review then I will fix it rq.

File: src/Mod/PartDesign/Gui/TaskExtrudeParameters.cpp [hunk 1]
```diff
@@ -116,6 +116,10 @@ void TaskExtrudeParameters::setupDialog()
     updateUI(Side::First);
 
     setupGizmos();
+
+    // trigger recompute to ensure external geometry references update correctly.
```
Comment (drwho495) [inline src/Mod/PartDesign/Gui/TaskExtrudeParameters.cpp:120]: You might want to change this to: "// recompute the support feature to fix bugs with the toponaming string hasher"

for better documentation for future developers, this is a bandaid fix right now, a more comprehensive one will need to be made later.

**Comment by Connor9220** [comment]
I tried this fix.  Looks like it works.  Reverted back to main, and still able to reproduce the bug. Can confirm, it  has nothing to do with the subshape binder.

**Comment by furgo16** [comment]
> You should trigger a build in the actions section of your gh repo. (the action should be called: "weekly-build", make sure to select the right branch)

The CI build scripts were reworked a few days ago, and there is no longre a "Weekly Build" workflow in FreeCAD main.

**Comment by eblanshey** [comment]
@ipatch, is it possible that this PR also fixes an issue I reported where expressions don't always get updated? https://github.com/FreeCAD/FreeCAD/issues/23959#issuecomment-3652179697 If you think it may, would you mind testing the same scenario in your build?

File: src/Mod/PartDesign/Gui/TaskExtrudeParameters.cpp (hunk 1 above)
Comment (kadet1090) [reply src/Mod/PartDesign/Gui/TaskExtrudeParameters.cpp:120]: @ipatch what we do with that comment? It is blocking merge right now as it is unresolved discussion.

Comment (ipatch) [reply src/Mod/PartDesign/Gui/TaskExtrudeParameters.cpp:120]: personally i think the original comment is good.

**Comment by maxwxyz** [comment]
@ipatch does this PR also fix https://github.com/FreeCAD/FreeCAD/issues/25720 or https://github.com/FreeCAD/FreeCAD/issues/25811 ?

**Comment by ErtugrulEge** [comment]
Thank you very much 

```
OS: Windows 10 build 19045
Architecture: x86_64
Version: 1.2.0dev.20251223 (Git shallow)
Build date: 2025/12/23 18:19:32
Build type: Release
Branch: (HEAD detached at 065fea4)
Hash: 065fea473f080691988bb11092759bf40f3c46fe
Python 3.11.14, Qt 6.8.3, Coin 4.0.3, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.3.0, IfcOpenShell 0.8.2, OCC 7.8.1
Locale: Turkish/Türkiye (tr_TR)
Navigation Style/Orbit Style/Rotation Mode: Blender/Trackball/Drag at cursor
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/
Logical DPI/Physical DPI/Pixel Ratio: 96/81.5973/1
Installed mods: 
  * CurvedShapes 1.0.13
  * Curves 0.6.61

```
