### PR TITLE
Core: Fix 'Expression' and 'Vector' editor outhanging the screen

### LINKED ISSUE #21782: [UI/UX] Can't see half of the expression editor when properties tab alignet to right
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Problem description

Greetings everyone!
I alignet properties panel to right and when I press expression editor button I can't see half of it

Image

### Full version info

```shell
OS: Windows 10 build 19045
Architecture: x86_64
Version: 1.1.0dev.42006 (Git)
Build date: 2025/06/02 16:32:08
Build type: Release
Branch: main
Hash: db1b5a877314f8d21514680421649fd9dc65acde
Python 3.11.12, Qt 6.8.3, Coin 4.0.3, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.2.5, IfcOpenShell 0.8.2, OCC 7.8.1
Locale: Turkish/Türkiye (tr_TR)
Navigation Style/Orbit Style/Rotation Mode: Blender/Trackball/Drag at cursor
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/fusion
Logical DPI/Physical DPI/Pixel Ratio: 96/81.5973/1
Installed mods: 
  * Curves 0.6.61
```

### Subproject(s) affected?

None

### Anything else?

_No response_

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by B0cho**
**Fix for the `Expression editor` and `Vector editor` outhanging screen when opened.**

### The Problem:
Previously, when these editors were opened from the _Model panel_ very close to the main window's edge, they could extend outside its boundaries, making user to move them inside.

Animation

### The Solution
 With this PR, the position of both editors will now automatically adjust if their initial opening position would cross the _main window's_ edge. This ensures they are always fully visible.

Animation2

If the _Model panel_ is undocked from the _main window_ (i.e., it's a free-floating window), the editors will continue to open above the triggering property, just as they did before.

Animation3
## Issues
fixes #21782 #18119
related #21031

### CODE REVIEW

**Comment by luzpaz** [comment]
Hi. thank you for submitting a fix. Question: why is so much unrelated code modified in this PR? Is it due to some linting process that snuck in somehow through the IDE you're using ?

**Comment by B0cho** [comment]
> Hi. thank you for submitting a fix. Question: why is so much unrelated code modified in this PR? Is it due to some linting process that snuck in somehow through the IDE you're using ?

I have no idea what has happend 😮 ... commit diffs looks OK, but branch diff shows like whole files were overwritten. I'm trying to fix it.

**Comment by B0cho** [comment]
Uff, now fixed 😅 Ready for review!

**Comment by hyarion** [comment]
There still seems to be some unrelated includes of MainWindow and lint. You could check https://github.com/FreeCAD/FreeCAD/pull/22426/files

File: src/Gui/Widgets.cpp [hunk 1]
```diff
@@ -1663,5 +1665,42 @@ bool ButtonGroup::exclusive() const
...
+    if (!dialog)
+        return;
+    const MainWindow* mw = getMainWindow();
+    if (!mw)
+        return;
+
+    dialog->adjustSize(); // needed for modal dialogs to ensure the size is correct
+    const QRect mainWindowRect = QRect(mw->mapToGlobal(QPoint(0, 0)), mw->size());
+    const QPoint initialDialogPos = dialog->mapToGlobal(QPoint(0, 0));
+    const QRect dialogRect = QRect(initialDialogPos, dialog->frameGeometry().size());
```
Comment (hyarion) [inline src/Gui/Widgets.cpp]: These can use auto to avoid redundant types

File: src/Gui/Dialogs/DlgExpressionInput.cpp [hunk 2]
```diff
@@ -46,6 +46,7 @@
 #include "ExpressionBinding.h"
 #include "BitmapFactory.h"
 #include "ViewProviderDocumentObject.h"
+#include "MainWindow.h"
```
Comment (hyarion) [inline src/Gui/Dialogs/DlgExpressionInput.cpp]: I think this can be removed

File: src/Gui/Widgets.cpp (hunk 1 above)
Comment (B0cho) [reply src/Gui/Widgets.cpp]: @hyarion resolved with https://github.com/FreeCAD/FreeCAD/commit/b5fdbbb773d9570ce490463fc141a109f4c7b0bd

File: src/Gui/Dialogs/DlgExpressionInput.cpp (hunk 2 above)
Comment (B0cho) [reply src/Gui/Dialogs/DlgExpressionInput.cpp]: @hyarion resolved with https://github.com/FreeCAD/FreeCAD/commit/f0f43f6cb056fdd6807e59d465e9c4b0761396f2

File: src/Gui/Widgets.cpp [hunk 3]
```diff
@@ -1663,5 +1665,42 @@ bool ButtonGroup::exclusive() const
...
 }
 
+namespace Gui {
+
+void adjustDialogPosition(QDialog* dialog) {
+    if (!dialog)
+        return;
+    const MainWindow* mw = getMainWindow();
+    if (!mw)
+        return;
```
Comment (hyarion) [inline src/Gui/Widgets.cpp]: There's some lint that can be removed with:

```suggestion
    if (!dialog) {
        return;
    }
    const MainWindow* mw = getMainWindow();
    if (!mw) {
        return;
    }
```

File: src/Gui/Widgets.cpp [hunk 4]
```diff
@@ -1663,5 +1665,42 @@ bool ButtonGroup::exclusive() const
...
+        }
+        if (dialogRect.left() < mainWindowRect.left()) {
+            adjustedDialogPos.setX(mainWindowRect.left() + margin);
+        }
+        if (dialogRect.top() < mainWindowRect.top()) {
+            adjustedDialogPos.setY(mainWindowRect.top() + margin);
+        }
+        if (dialogRect.bottom() > mainWindowRect.bottom()) {
+            adjustedDialogPos.setY(mainWindowRect.bottom() - dialogRect.height() - margin);
+        }
```
Comment (hyarion) [inline src/Gui/Widgets.cpp]: Could this be simplified with: https://doc.qt.io/qt-6/qsize.html#boundedTo
and: https://doc.qt.io/qt-6/qsize.html#expandedTo ?

Comment (hyarion) [reply src/Gui/Widgets.cpp]: The answer to that is no... but we could use std::clamp, right?

Maybe something like this:

```c++
void adjustDialogPosition(QDialog* dialog) {
    if (!dialog) {
        return;
    }

    const MainWindow* mw = getMainWindow();
    if (!mw) {
        return;
    }

    dialog->adjustSize(); // Ensure correct size

    QRect mainWindowRect{ mw->mapToGlobal(QPoint{0, 0}), mw->size() };
    QRect dialogRect = dialog->frameGeometry();

    const bool isFullyInside = mainWindowRect.contains(dialogRect);
    if (isFullyInside) {
        return;
    }

    const bool isCompletelyOutside = !mainWindowRect.intersects(dialogRect);
    if (isCompletelyOutside) {
        return;
    }

    const int margin = 5;
    QRect availableArea = mainWindowRect.adjusted(
        margin, margin, -margin, -margin
    );

    QPoint adjustedTopLeft = dialogRect.topLeft();

    adjustedTopLeft.setX(std::clamp(
        adjustedTopLeft.x(),
        availableArea.left(),
        availableArea.right() - dialogRect.width()
    ));

    adjustedTopLeft.setY(std::clamp(
        adjustedTopLeft.y(),
        availableArea.top(),
        availableArea.bottom() - dialogRect.height()
    ));

    dialog->move(adjustedTopLeft);
}
```

Note that this hasn't been tested.

**Comment by MisterMakerNL** [comment]
This is so nice, this was so annoying thanks for fixing!
