### PR TITLE
Part: bugfix #17468 recursively unpack compounds for boolean fuse

### LINKED ISSUE #17468: Part: Compounds/Fusion:  Can't fuse solids in recursively packed compounds.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When importing a .brep file, the imported shape is always a compound. It doesn't seem to matter if the shape is a single solid or multiple, it gets stuck in a compound.

This is a problem when making boolean fragments

Attempt the following:

1. Make "boolean fragments" with the imported shape and something else
2. "Explode" the boolean fragments - that should yield a compound filter to the original shape - but with new seams for the intersection (important for FEM)  make sure (Analysze Geometry) the fragment is 1 compound with multiple solids
3. Make a Part Fusion of this compound filter.

Expected Outcome:
Fusion treats the compound filter as a compound of solids and fuses them into a single solid.

Actual Outcome:
Fusion recognizes the compound, but then sees only a single shape in the compound and aborts with
```
<Exception> Not enough shape objects linked
Fusion: Not enough shape objects linked
```

This is because the compound holds another single compound, and only in this compound there are multiple shapes.

The code in here doesn't see that:

https://github.com/FreeCAD/FreeCAD/blob/3bae98c2e526394c79faae5847f7b22f3ed548c2/src/Mod/Part/App/FeaturePartFuse.cpp#L105-L114

it would have to recursively unpack the compound but this case isn't considered here (or elsewhere)

There is no feasible way to "unpack" the compound. A compound filter to the first entry, again packs the result into a compound, yielding the same issue.

### Full version info

```shell
current main 1.1dev 2d57e9f2afa1da442a20a3426719055fc4e906a9
```

### Subproject(s) affected?

Part

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by AIRCAP**
fix #17468  recursively unpack compounds for boolean fuse

OCCT can boolean fuse multiple shapes in a compound

even if that compound is in another compound
even if that compound is in another compound
even if that compound is in another compound
even if that compound is in another compound
even if that compound is in another compound
even if that compound is in another compound
even if that compound is in another compound
even if that compound is in another compound
even if that compound is in another compound
even if that compound is in another compound
even if that compound is in another compound
even if that compound is in another compound
...

but FreeCAD wouldn't let it because it only checks the topmost layer

sadly multi-recursive compounds can be created from brep export+import (there are scenarios that increase recursion depth by one)  and of course by hand

### CODE REVIEW

File: src/Mod/Part/Gui/Command.cpp [hunk 1]
```diff
@@ -374,12 +374,15 @@ void CmdPartCommon::activated(int iMsg)
         numShapes = 1; //to be updated later in code, if
         Gui::SelectionObject selobj = Sel[0];
         TopoDS_Shape sh = Part::Feature::getShape(selobj.getObject());
-        if (sh.ShapeType() == TopAbs_COMPOUND) {
+        while (numShapes==1 and sh.ShapeType() == TopAbs_COMPOUND) {
```
Comment (wwmayer) [inline src/Mod/Part/Gui/Command.cpp:377]: Don't use the keyword `and`! By default, this doesn't work with every compiler.

Comment (AIRCAP) [reply src/Mod/Part/Gui/Command.cpp]: ok fusion actually does fail with a single shape only.  common doesn't care (since it treats the compound of multiple shapes as a single shape anyway) there only is a warning

so I'm gonna remove the duplicated code from common and thus the code duplication

Comment (wwmayer) [reply src/Mod/Part/Gui/Command.cpp]: > I did not make a function for this, since I simply had no clue which class and folder to put it into.

E.g. a function can be added to TopoShape: `static int TopoShape::countShapes(const TopoDS_Compound&)`

> Also this is GUI code, I don't know how to put a test case for this.

It's used in the GUI but it's no GUI code.

> I now added tests for Part::MultiFuse with compounds and recursive compounds.

Actually, there is too much high-level code involved. Ideally, you only use the OCC API to construct a nested compound and pass this shape to `TopoShape::countShapes`.

**Comment by AIRCAP** [comment]
CI failed on mac . looks like an issue in the CI pipeline, the test itself succeeds but then runs into an error during cleanup sed: couldn't flush stdout: Broken pipe

**Comment by chennes** [comment]
> CI failed on mac . looks like an issue in the CI pipeline, the test itself succeeds but then runs into an error during cleanup sed: couldn't flush stdout: Broken pipe

Right - as you note, it's a false failure, the usual intermittent Mac Conda garbage. Ignoring it, but waiting for @wwmayer's final approval and/or merge of the PR.

File: src/Mod/Part/Gui/Command.cpp (hunk 1 above)
Comment (AIRCAP) [reply src/Mod/Part/Gui/Command.cpp]: yeah that could be done.

since it's currently only used in this one place, would you mind separating that from this issue/PR and making a separate issue/TODO for it? that way this bugfix doesn't have to wait until I get to implement that, kinda limited on time atm...

Comment (AIRCAP) [reply src/Mod/Part/Gui/Command.cpp]: I opened an issue for this so it doesnt get forgotten #17506 17506

**Comment by yorikvanhavre** [comment]
@wwmayer can you have a look if everything is OK here?

File: src/Mod/Part/App/FeaturePartFuse.cpp [hunk 2]
```diff
@@ -102,7 +102,8 @@ App::DocumentObjectExecReturn *MultiFuse::execute()
     TopoShape compoundOfArguments;
 
     // if only one source shape, and it is a compound - fuse children of the compound
-    while (shapes.size() == 1) {
+    int naucks_sanity_remaining=1000000; // hard abort after 1 million loops - will trigger "not enough shape objects linked" error below if ever reached
```
Comment (wwmayer) [inline src/Mod/Part/App/FeaturePartFuse.cpp:105]: Should be const to fix linter warning

File: src/Mod/Part/Gui/Command.cpp [hunk 3]
```diff
@@ -368,26 +368,7 @@ void CmdPartCommon::activated(int iMsg)
...
-                ++numShapes;
-                last = it.Value();
-            }
-            sh = last;
-        }
-    } else {
-        numShapes = Sel.size();
-    }
-    if (numShapes < 2) {
+    if (Sel.size() < 1) {
```
Comment (wwmayer) [inline src/Mod/Part/Gui/Command.cpp:371]: Weird expression!

The minimum value `size()` can return is 0. So, `Sel.size() < 1` is equal to `Sel.size() == 0` and this means the array is empty. So, write: `Sel.empty()`

**Review by wwmayer — COMMENTED** [review]
See comments in the code

**Comment by yorikvanhavre** [comment]
waiting for comments resolution

**Comment by maxwxyz** [comment]
@AIRCAP FYI

File: src/Mod/Part/App/FeaturePartFuse.cpp [hunk 4]
```diff
@@ -102,12 +102,15 @@ App::DocumentObjectExecReturn *MultiFuse::execute()
     TopoShape compoundOfArguments;
 
     // if only one source shape, and it is a compound - fuse children of the compound
-    if (shapes.size() == 1) {
+    int naucks_sanity_remaining=1000000; // hard abort after 1 million loops - will trigger "not enough shape objects linked" error below if ever reached
+    while (shapes.size() == 1 && naucks_sanity_remaining-- > 0) {
```
Comment (hyarion) [inline src/Mod/Part/App/FeaturePartFuse.cpp:106]: Though I like the tribute to my questionable sanity; we can clean up this code a bit to make it easier to read and follow.

```suggestion
    const int maxIterations = 1'000'000; // will trigger "not enough shape objects linked" error below if ever reached
    for (int i = 0; shapes.size() == 1 && i < maxIterations; ++i) {
```
* use c++14 digit separator for magic number. Makes the number easy to read and comment about the value unnecessary.
* rename variable so it represent the data. Side effect: making code dry, boring, and readable.
* using for loop that counts upwards to make. While counting downwards is a common optimization, the normal `for (int i = 0; ...)` encapsulates the intent better and makes it more easy to read. It also removes the need for an extra const for the magic number, see wwmayer's comment about the linter warning.

**Comment by yorikvanhavre** [comment]
backported
