### PR TITLE
Gui: fix Quantity spinbox margin without an icon

### LINKED ISSUE #20680: [UI/UX] Sketcher input units not showing properly
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Problem description

Sketcher input box are too narrow when showing units  and not responsive to the screen 

Image

### Full version info

```shell
OS: Windows 10 build 19045
Architecture: x86_64
Version: 1.1.0dev.41155 (Git) Conda
Build date: 2025/04/06 04:00:07
Build type: Release
Branch: main
Hash: e537278f1296211edb90bf1c938dfaebd2626f0d
Python 3.11.11, Qt 6.7.3, Coin 4.0.3, Vtk 9.3.1, IfcOpenShell 0.8.1, OCC 7.8.1
Locale: Turkish/Türkiye (tr_TR)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/windowsvista
Logical DPI/Physical DPI/Pixel Ratio: 96/81.5973/1
```

### Subproject(s) affected?

None

### Anything else?

_No response_

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by alfrix**
margin refactoring aimed to fix #20680

margins are different depending on whether there is an icon or not

imagen

imagen

### CODE REVIEW

File: src/Gui/QuantitySpinBox_p.h [hunk 1]
```diff
@@ -39,6 +40,16 @@ class ExpressionLabel : public QLabel
             this->setToolTip(expressionEditorTooltipPrefix + text);
     }
 
+    void show() {
+        if (QLineEdit* parentLineEdit = qobject_cast<QLineEdit*>(parent())) {
+            // horizontal margin, so text will not be behind the icon
+            QMargins margins = parentLineEdit->contentsMargins();
+            margins.setRight(margins.right() * 2 + this->sizeHint().width());
```
Comment (3x380V) [inline src/Gui/QuantitySpinBox_p.h:47]: Here I needed a while... Outer world is normally using `2 * margins.right() + sizeHint().width()` (note `this` is redundant here)

Comment (alfrix) [reply src/Gui/QuantitySpinBox_p.h]: apart from the icon width, you need to take into account the space to the left of the icon that's why you need to duplicate the margin, so the text-margin takes into account both sides of the icon

**Review by 3x380V — APPROVED** [review]
Looks good now (assuming commits get squashed on merge)

**Comment by kadet1090** [comment]
> Looks good now (assuming commits get squashed on merge)

They absolutely will! Thanks for taking care of review here.
