### PR TITLE
TechDraw: Add properties for configurable section line font, font size, and arrow size

### LINKED ISSUE #27520: TechDraw: Section line font, font size, and arrow size are not configurable
### Problem description

The font, font size, and arrow size of section view cut lines are taken from the user preferences and not from instance properties of the section view. It would be nice if these values were configurable on a per-instance basis.

### Workbench affected?

TechDraw

### Steps to reproduce

Create a section view.

### Expected behavior

The font, font size, and arrow size for the section line are controlled by per-instance view properties.

### Actual behavior

The font, font size, and arrow size for the section line are controlled by user preferences.

### Development version About Info (in Safe Mode)

```shell
OS: Ubuntu 24.04.3 LTS (KDE/plasma/xcb)
Architecture: x86_64
Version: 1.0.2.39319 (Git) Conda AppImage
Build type: Release
Branch: (HEAD detached at 1.0.2)
Hash: 256fc7eff3379911ab5daf88e10182c509aa8052
Python 3.11.13, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
Installed mods: 
  * sheetmetal 0.5.5
  * lattice2 1.0.0
  * freecad.gears 1.3.0
```

### Last known good version (optional)

```shell

```

### PR DESCRIPTION
**Pull request by dkleszyk**
Closes #27520

I am not committed to the exact property names and groups, so that is still open for bikeshedding.

### CODE REVIEW

File: src/Mod/TechDraw/Gui/QGIViewPart.cpp [hunk 1]
```diff
@@ -774,7 +775,9 @@ void QGIViewPart::drawSectionLine(TechDraw::DrawViewSection* viewSection, bool b
         }
 
         double fontSize = Preferences::dimFontSizeMM();
+        double arrowSize = QGIArrow::getPrefArrowSize();
```
Comment (WandererFan) [inline src/Mod/TechDraw/Gui/QGIViewPart.cpp:778]: QGIArrow::getPrefArrowSize() returns PreferencesGui::dimArrowSize().  Don't we want to get this from a property somewhere?

edit: NVM.  I found it in a later commit.
