### PR TITLE
Assembly: Fixes bug for origins in Sub-`AssemblyLink`

### LINKED ISSUE #18114: "Can't find Origin" Message when inserting Assembly containing Sub-Assemblies.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I searched for this issue but did not find a post about it. Sorry if it already exists.

I wanted to create an assembly that uses another assembly multiple times. So, I did the following:

1. [TSLOT-1515S.FCStd] Created the parts.
2. [SubAssembly.FCStd] Created a new assembly and inserted those parts. 
3. [Multi-Subassembly.FCStd] Created a new assembly and inserted the assembly created in step 2 twice. 
4. [FullAssembly.FCStd] Finally, created another assembly and inserted the Multi-Subassembly into this Full Assembly.

The Multi-Subassembly was indeed inserted, however, Error messages appeared on screen and in Report View:

21:25:00  Can't find Origin for "FullAssembly#SubAssembly"
21:25:00  Can't find Origin for "FullAssembly#SubAssembly"
21:25:00  Can't find Origin for "FullAssembly#SubAssembly"
21:25:00  Can't find Origin for "FullAssembly#SubAssembly"
21:25:00  Can't find Origin for "FullAssembly#SubAssembly"
21:25:00  Can't find Origin for "FullAssembly#SubAssembly"
21:25:00  Can't find Origin for "FullAssembly#SubAssembly"
21:25:00  Can't find Origin for "FullAssembly#SubAssembly001"
21:25:00  Can't find Origin for "FullAssembly#SubAssembly001"
21:25:00  Can't find Origin for "FullAssembly#SubAssembly001"
21:25:00  Can't find Origin for "FullAssembly#SubAssembly001"
21:25:00  Can't find Origin for "FullAssembly#SubAssembly001"
21:25:00  Can't find Origin for "FullAssembly#SubAssembly001"
21:25:00  Can't find Origin for "FullAssembly#SubAssembly001"

Now I did notice the Origin would get renamed when inserting a previously made assembly (Origin would be renamed Origin001). I have worked on RC2 and I recall I was able to insert assemblies made of other assemblies with no issues. In that case, the Origin was not renamed to Origin001, Origin002, etc... but would maintain it original name of Origin. 

I attached screenshots and the FreeCAD files I used. To see the error, Open file FullAssembly.FCStd and insert "Multi-Subassembly.FCStd" into its assembly.

### Full version info

```shell
OS: Windows 11 build 22631
Architecture: x86_64
Version: 1.0.0.39109 (Git) Conda
Build type: Release
Branch: (HEAD detached at 1.0.0)
Hash: 2fcc5317fe3aee96ca73475986a577719fc78e20
Python 3.11.10, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Dark/Fusion
Installed mods: 
  * A2plus 0.4.65
```

### Subproject(s) affected?

Assembly

### Anything else?

[SubAssemblyIssue.zip](https://github.com/user-attachments/files/17896450/SubAssemblyIssue.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by OnesAndZer0s**
Fixes #18114, #20270

When creating an `AssemblyLink` object, simply links the origin, as it did not before.

### CODE REVIEW

**Comment by luzpaz** [comment]
@PaddleStroke any chance you can review this Assembly PR ?

File: src/QtWidgets.h [hunk 1]
```diff
@@ -0,0 +1,11 @@
+#ifndef FREECAD_QTWIDGETS_H
```
Comment (PaddleStroke) [inline src/QtWidgets.h]: This file should not be in this PR. Same for QtCore.h and backtrace.cpp

File: src/Mod/Assembly/App/AssemblyLink.cpp [hunk 2]
```diff
@@ -207,14 +215,18 @@ void AssemblyLink::synchronizeComponents()
...
             }
             else if (link2) {
                 linkedObj = link2->getLinkedObject(false);  // not recursive
             }
+            // else if (group) {
+            //     linkedObj = group->getLinkedObject(false);  // not recursive
+            // }
             else {
-                // We consider only Links and AssemblyLinks in the AssemblyLink.
+                // We consider only Links, AssemblyLinks, and in the AssemblyLink.
```
Comment (PaddleStroke) [inline src/Mod/Assembly/App/AssemblyLink.cpp]: This edits the comment but new version does not make sense. There is something missing after 'and' also you don't need a ',' before a 'and'

File: src/Mod/Assembly/App/AssemblyLink.cpp [hunk 3]
```diff
@@ -229,11 +241,23 @@ void AssemblyLink::synchronizeComponents()
...
                 doc->addObject(subAsmLink, obj->getNameInDocument());
+                subAsmLink->Origin.setValue(asmLink->Origin.getValue());
                 subAsmLink->LinkedObject.setValue(obj);
                 subAsmLink->Rigid.setValue(asmLink->Rigid.getValue());
                 subAsmLink->Label.setValue(obj->Label.getValue());
+
+                origin->Label.setValue("Origin");
+                auto* test = dynamic_cast<App::PropertyPlacement*>(
+                    subAsmLink->getPropertyByName("Placement"));
+                origin->Placement.setValue(test->getValue());
```
Comment (PaddleStroke) [inline src/Mod/Assembly/App/AssemblyLink.cpp]: Memory leak. You create a new App::Origin object but this object is never deleted. Nor is it added to the document at any point.

252 to 256 is going nothing because the origin object is lost. Besides those lines don't really make sense.

File: src/Mod/Assembly/App/AssemblyLink.cpp [hunk 4]
```diff
@@ -207,14 +215,18 @@ void AssemblyLink::synchronizeComponents()
...
+
             if (subAsmLink) {
                 linkedObj = subAsmLink->getLinkedObject2(false);  // not recursive
             }
             else if (link2) {
                 linkedObj = link2->getLinkedObject(false);  // not recursive
             }
+            // else if (group) {
+            //     linkedObj = group->getLinkedObject(false);  // not recursive
+            // }
```
Comment (PaddleStroke) [inline src/Mod/Assembly/App/AssemblyLink.cpp]: What is this commented text for?

File: src/Mod/Assembly/App/AssemblyLink.cpp [hunk 5]
```diff
@@ -191,10 +193,16 @@ void AssemblyLink::synchronizeComponents()
...
     // We check if a component needs to be added to the AssemblyLink
     for (auto* obj : assemblyGroup) {
         if (!obj->isDerivedFrom<App::Part>() && !obj->isDerivedFrom<PartApp::Feature>()
-            && !obj->isDerivedFrom<App::Link>()) {
+            && !obj->isDerivedFrom<App::Link>()
+            && !obj->isDerivedFrom<App::DocumentObjectGroup>()) {
+            continue;
+        }
+
+        if (obj->isDerivedFrom<JointGroup>() || obj->getGroup() != nullptr) {
```
Comment (PaddleStroke) [inline src/Mod/Assembly/App/AssemblyLink.cpp]: Why `obj->getGroup() != nullptr`

**Comment by PaddleStroke** [comment]
Besides as it is, it looks like you are making links to the group object itself instead of the group content. Which is a problem because then the sub-assembly cannot be flexible.

To support folder what needs to be done is to create a group object in the sub-assembly, then populate this group with links to the components.

File: src/Mod/Assembly/App/AssemblyLink.cpp (hunk 4 above)
Comment (OnesAndZer0s) [reply src/Mod/Assembly/App/AssemblyLink.cpp]: This was me testing a variable, and I forgot to remove it

File: src/Mod/Assembly/App/AssemblyLink.cpp (hunk 2 above)
Comment (OnesAndZer0s) [reply src/Mod/Assembly/App/AssemblyLink.cpp]: I agree. This was a byproduct of how I was trying to link them before, as I had a third `else if` statement. However, as I removed that, I forgot to edit the comment properly

File: src/Mod/Assembly/App/AssemblyLink.cpp (hunk 5 above)
Comment (OnesAndZer0s) [reply src/Mod/Assembly/App/AssemblyLink.cpp]: `obj->getGroup() != nullptr` checks if group of the object is within the top-most level of the object. With the comment left about how that method causes sub-assemblies to not be flexible, I'll refactor.

File: src/Mod/Assembly/App/AssemblyLink.cpp (hunk 3 above)
Comment (OnesAndZer0s) [reply src/Mod/Assembly/App/AssemblyLink.cpp]: i commented this part out, and it still works. Honestly, I am clueless

**Comment by OnesAndZer0s** [comment]
> Besides as it is, it looks like you are making links to the group object itself instead of the group content. Which is a problem because then the sub-assembly cannot be flexible.
> 
> To support folder what needs to be done is to create a group object in the sub-assembly, then populate this group with links to the components.

That makes sense. Implementing this method has caused me to come across a fairly big bug. Moving a sub-assembly into a folder, while the sub-assembly is flexible, the joint does not properly link, and an error throws.

To fix this bug, should I make a different PR to fix that, or put that in this PR?

**Comment by PaddleStroke** [comment]
I think it should be 2 separate PRs. Because the group thing is going to be quite a big PR since you need to make a recursive function checking each folder and creating folders before populating them with links.

Now regarding the origin bug, it looks like you are trying to replicate the python workaround that was suggested in the issue. But that is not a correct fix. The code doesn't make sense as it is.

File: src/Mod/Assembly/App/AssemblyLink.cpp [hunk 6]
```diff
@@ -229,11 +233,15 @@ void AssemblyLink::synchronizeComponents()
             if (obj->isDerivedFrom<AssemblyLink>()) {
                 auto* asmLink = static_cast<AssemblyLink*>(obj);
                 auto* subAsmLink = new AssemblyLink();
+
                 doc->addObject(subAsmLink, obj->getNameInDocument());
+                subAsmLink->Origin.setValue(asmLink->Origin.getValue());
```
Comment (PaddleStroke) [inline src/Mod/Assembly/App/AssemblyLink.cpp]: So this line fix the issue right?

Comment (PaddleStroke) [reply src/Mod/Assembly/App/AssemblyLink.cpp]: You correctly identified where the problem is but the fix is not the correct one.

The issue is that there we have :

```
auto* subAsmLink = new AssemblyLink();
doc->addObject(subAsmLink, obj->getNameInDocument());
```

which is not the correct way to create an object. Because this way of creating an object does not create necessary subobjects (origin).

The correct way is : 

```
            if (obj->isDerivedFrom<AssemblyLink>()) {
                auto* asmLink = static_cast<AssemblyLink*>(obj);

                App::DocumentObject* newObj = doc->addObject("Assembly::AssemblyLink", obj->getNameInDocument());
                auto* subAsmLink = static_cast<AssemblyLink*>(newObj);
                subAsmLink->LinkedObject.setValue(obj);
                subAsmLink->Rigid.setValue(asmLink->Rigid.getValue());
                subAsmLink->Label.setValue(obj->Label.getValue());
                addObject(subAsmLink);
                link = subAsmLink;
            }
```

This is the correct fix for this bug. Please update your PR to this and it will be good to go.

File: src/Mod/Assembly/App/AssemblyLink.cpp [hunk 7]
```diff
@@ -21,6 +21,8 @@
  *                                                                          *
  ***************************************************************************/
 
+#include "App/GroupExtension.h"
+#include "App/Origin.h"
```
Comment (PaddleStroke) [inline src/Mod/Assembly/App/AssemblyLink.cpp]: Those additional headers don't seem necessary please remove them

**Comment by PaddleStroke** [comment]
Please also add this mention to your issue so that that duplicate issue is also closed when that pr merge :
Fix https://github.com/FreeCAD/FreeCAD/issues/20270

**Comment by OnesAndZer0s** [comment]
I removed all of the code relating to adding folders to Assemblies, and linked the other issue. I am currently building to see if the code snippet works.

File: src/Mod/Assembly/App/AssemblyLink.cpp [hunk 8]
```diff
@@ -228,13 +230,26 @@ void AssemblyLink::synchronizeComponents()
...
+
+                // doc->addObject(subAsmLink, obj->getNameInDocument());
+                // subAsmLink->Origin.setValue(asmLink->Origin.getValue());
+                // subAsmLink->LinkedObject.setValue(obj);
+                // subAsmLink->Rigid.setValue(asmLink->Rigid.getValue());
+                // subAsmLink->Label.setValue(obj->Label.getValue());
+
+                // addObject(subAsmLink);
+
+                // link = subAsmLink;
```
Comment (PaddleStroke) [inline src/Mod/Assembly/App/AssemblyLink.cpp]: Please don't leave that commented out code.

File: src/Mod/Assembly/App/AssemblyLink.cpp [hunk 9]
```diff
@@ -177,6 +177,7 @@ void AssemblyLink::updateContents()
     purgeTouched();
 }
 
+
```
Comment (PaddleStroke) [inline src/Mod/Assembly/App/AssemblyLink.cpp]: No reason to add an empty space here. It breaks uniformity of the file. Please remove it.

**Comment by PaddleStroke** [comment]
@luzpaz Looks good to go now. The commits needs to be squashed

**Comment by luzpaz** [comment]
@PaddleStroke do you mind Approving the PR as a reviewer ? TIA!

**Comment by PaddleStroke** [comment]
@chennes it would be useful if I had merging right so that I can merge stuff like that.
