### PR TITLE
Gui: fix Inputfield valid/invalid icon placement and size

### LINKED ISSUE #19156: [Draft/BIM] The information icon in the fields has an extra state and is not aligned correctly.
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Problem description

The gif image shows that the information icon has three states.
1. Correct data (green checkbox)
2. Incorrect data (red prohibition sign).
3. No icon (if the field is empty).

Image

In addition, the alignment of icons along the right edge in some tools is not the same. For three signs, we have three different indents from the right edge.

Image

1. Correct.
2 + 3. Incorrect. Because an empty field can be considered an incorrect input.

The appearance of the icons can also be made more modern.

For example, this is how it looks in Bootstrap v.5.3.

Image

### Full version info

```shell
OS: Manjaro Linux (KDE/plasma/xcb)
Architecture: x86_64
Version: 1.1.0dev.39896 (Git) Conda AppImage
Build type: Release
Branch: main
Hash: a977fade2de741c94c9efa59b1c2c26df18eb631
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: Russian/Russia (ru_RU)
Stylesheet/Theme/QtStyle: OpenLight.qss/OpenLight/Fusion
Installed mods: 
  * FreeCAD_SketchArch
  * lattice2 1.0.0
  * PitchedRoof
  * Road 2025.1.16
  * addFC 1.1.0
  * freecad.gears 1.3.0
  * sheetmetal 0.7.3
  * OpenTheme 2024.9.1
```

### Subproject(s) affected?

Draft

### Anything else?

_No response_

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by alfrix**
fixes #19156

this is the difference between master and this PR:
output

here is an overlap of this PR comparing it to the fx icon in master:
overlapped

### CODE REVIEW

File: src/Gui/InputField.cpp [hunk 1]
```diff
@@ -86,22 +86,33 @@ InputField::InputField(QWidget * parent)
...
     connect(this, &QLineEdit::textChanged, this, &InputField::updateIconLabel);
-    int frameWidth = style()->pixelMetric(QStyle::PM_DefaultFrameWidth);
-    setStyleSheet(QStringLiteral("QLineEdit { padding-right: %1px } ").arg(iconLabel->sizeHint().width() + frameWidth + 1));
-    QSize msz = minimumSizeHint();
-    setMinimumSize(qMax(msz.width(), iconLabel->sizeHint().height() + frameWidth * 2 + 2),
-                   qMax(msz.height(), iconLabel->sizeHint().height() + frameWidth * 2 + 2));
+
+    // Set Margins
+    // vertical to avoid this: https://forum.freecad.org/viewtopic.php?f=8&t=50615
+    // horizontal to avoid going under the icon
```
Comment (benj5378) [inline src/Gui/InputField.cpp:98]: These comments make no sense. I have no idea how the forum thread is realted either.

File: src/Gui/InputField.cpp [hunk 2]
```diff
@@ -175,12 +186,10 @@ void InputField::updateText(const Base::Quantity& quant)
     setText(QString::fromStdString(txt));
 }
 
-void InputField::resizeEvent(QResizeEvent *)
+void InputField::resizeEvent(QResizeEvent * /*event*/)
```
Comment (benj5378) [inline src/Gui/InputField.cpp:189]: Unrelated? No benefit of this either

Comment (alfrix) [reply src/Gui/InputField.cpp:189]: common practice, is either that or using Q_UNUSED, it avoids the IDE screaming at you, not important

**Comment by benj5378** [comment]
This is an improvement. Though weren't there agreed on a new design for incorrect inputs?

**Comment by alfrix** [comment]
> This is an improvement. Though weren't there agreed on a new design for incorrect inputs?

we talked about it for a bit in the design group on discord, if i remember correctly the consensus was something like the valid icon makes no sense to be present and the forbidden icon could be changed to an something like ( ! )

i reckon that those changes should be separated since they are not fixes, but rather UI changes

**Comment by kaiwas** [comment]
> fixes #19156

Looks great!

I hope someday you'll get the idea to remove the "mm" dimension and the like outside the input field. It's incredibly annoying that there are letter values ​​in digital fields that can also be entered.
But that's a topic for another issue.

**Comment by alfrix** [comment]
> I hope someday you'll get the idea to remove the "mm" dimension and the like outside the input field. It's incredibly annoying that there are letter values ​​in digital fields that can also be entered. But that's a topic for another issue.

it can be done as a suffix, and that would mean that the unit wouldn't be editable, 
but without looking at the code i can already tell you that this behavior was intended, so you can input 3cm or 30mm or something like 1/2in and it will be understood.

**Comment by kaiwas** [comment]
> 3cm or 30mm

Yes. I understand why this is done. You can enter 10000 (mm), or 10m and it will be the same.

The problem is that you don't have to do this very often. At the same time, you have to constantly aim between numbers and letters, or make sure not to accidentally delete a symbol. It turns out that because of "0.001%" of cases (when it is really necessary), the main process suffers.

In general, the idea is good, but the implementation is simply disgusting.
I will analyze how this is implemented in other programs and try to make a proposal. I will draw up a separate issue. Thank you!

File: src/Gui/InputField.cpp (hunk 2 above)
Comment (kadet1090) [reply src/Gui/InputField.cpp:189]: I think that we should use `[[maybe_unused]]` in that case as it is the current standard and independent of Qt.

**Review by kadet1090 — APPROVED** [review]

**Comment by maxwxyz** [comment]
@FreeCAD/design-working-group FYI

File: src/Gui/InputField.cpp (hunk 1 above)
Comment (benj5378) [reply src/Gui/InputField.cpp:98]:
```suggestion
    // vertical margin, such that `,` won't clipped to a `.` and similar font descents. Relevant on some OSX versions
    // horizontal margin, such that text will not be behind `fx` icon
```

File: src/Gui/InputField.cpp [hunk 3]
```diff
@@ -175,12 +186,10 @@ void InputField::updateText(const Base::Quantity& quant)
...
 
-void InputField::resizeEvent(QResizeEvent *)
+void InputField::resizeEvent(QResizeEvent * /*event*/)
 {
-    QSize sz = iconLabel->sizeHint();
-    int frameWidth = style()->pixelMetric(QStyle::PM_DefaultFrameWidth);
-    iconLabel->move(rect().right() - frameWidth - sz.width(),
-                    rect().center().y() - sz.height() / 2);
+    QSize iconSize = iconLabel->sizeHint();
+    iconLabel->move(width() - (iconSize.width() + 2 * getMargin()), (height() - iconSize.height()) / 2);
```
Comment (benj5378) [inline src/Gui/InputField.cpp:192]: I keep wondering why this `2 * getMargin()`, but if you tested the code, then sure!

File: src/Gui/InputField.h [hunk 4]
```diff
@@ -201,6 +201,7 @@ protected Q_SLOTS:
     void wheelEvent(QWheelEvent * event) override;
     void contextMenuEvent(QContextMenuEvent * event) override;
     void resizeEvent(QResizeEvent*) override;
+    int getMargin();
```
Comment (benj5378) [inline src/Gui/InputField.h:204]:
```suggestion
    int getMargin() const;
```
(minor issue)

**Comment by benj5378** [comment]
Above some comments from me on minor issues. My only complaint is the code comment: https://github.com/FreeCAD/FreeCAD/pull/20466#discussion_r2012738635.

**Review by benj5378 — APPROVED** [review]

**Review by kadet1090 — APPROVED** [review]
