### PR TITLE
Import: Use progress bar for STEP, IGES and glTF import

### LINKED ISSUE #17050: STEP: "Show progress bar when importing" option doesn't work (Regression)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When importing a step file.

It shows this popup... then there is this `Show progress bar when importing` option...
I don't see any progress indication anywhere. 
Is this working?

image

The step files tested are big with multiple objects inside. So it takes time to import the step file. 

### Full version info

```shell
OS: Ubuntu 24.04.1 LTS (ubuntu:GNOME/ubuntu-xorg)
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38898 (Git) AppImage
Build type: Release
Branch: main
Hash: 32e09d9554db26414697ed19e0189ccab4ea9029
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: OpenDark.qss/OpenDark/Qt default
Installed mods: 
  * Assembly4 0.50.16-dev
  * sheetmetal 0.4.26
  * InventorLoader 1.4.0
  * diff-tools 0.1.0
  * ose-piping
  * OpenTheme 2024.9.1
  * fasteners 0.5.29
  * osh-autodoc-workbench 0.2.3
  * OpticsWorkbench 1.0.24
  * lattice2 1.0.0
  * kicadStepUpMod 11.3.9
```

### Subproject(s) affected?

Core

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by 3x380V**
Fixes: #17050

Implemented by @wwmayer.

Beware: This branch (_import_) is based on _progress_ branch which has already pending #27380. Gihub cannot open cascaded pull requests, so I decided to open it for your convenience and give opportunity for testing. It merely shows what #27380 is good for. Once later is merged, all the commits except the last one vanish.

### CODE REVIEW

File: src/Mod/Import/Gui/AppImportGuiPy.cpp [hunk 1]
```diff
@@ -361,10 +376,10 @@ class Module: public Py::ExtensionModule<Module>
 
             if (ret) {
                 App::GetApplication().setActiveDocument(pcDoc);
-                auto gdoc = Gui::Application::Instance->getDocument(pcDoc);
-                if (gdoc) {
-                    gdoc->setActiveView();
-                    Gui::Application::Instance->commandManager().runCommandByName("Std_ViewFitAll");
+                if (auto gdoc = Gui::Application::Instance->getDocument(pcDoc)) {
+                    if (auto view = freecad_cast<Gui::View3DInventor*>(gdoc->setActiveView())) {
```
Comment (tritao) [inline src/Mod/Import/Gui/AppImportGuiPy.cpp]: I think this changes the old auto-fit behavior a bit more than intended. Before this, we went through `Std_ViewFitAll`, so anything that handled the generic `"ViewFit"` message would still fit correctly, including split 3D views. With the cast to `Gui::View3DInventor`, that only happens for a plain 3D view. I would keep the generic fit path here.

File: src/Mod/Import/Gui/AppImportGuiPy.cpp [hunk 2]
```diff
@@ -324,8 +331,12 @@ class Module: public Py::ExtensionModule<Module>
             }
             else if (file.hasExtension({"igs", "iges"})) {
                 try {
+                    Handle(Message_ProgressIndicator) pi;
+                    if (ocaf.showProgress()) {
```
Comment (tritao) [inline src/Mod/Import/Gui/AppImportGuiPy.cpp:337]: One small thing here: IGES now uses `ocaf.showProgress()` too, but `options["showProgress"]` is still only read in the STEP-specific block above. So if someone passes that option into `insert(...)`, it still will not affect IGES or glTF and just falls back to the global preference. Might be cleaner to read it once before branching on file type.

**Comment by tritao** [comment]
Looks good, just some minor issues.

I put together a small patch with one possible fix here:
https://gist.github.com/tritao/30e8b5289fdd0ab3202404956b615cbc

**Comment by 3x380V** [comment]
@tritao, thanks. Patch applied.

**Review by tritao — APPROVED** [review]
