### PR TITLE
Gui: Fix too small link icon on high dpi

### LINKED ISSUE #6765: UI: Overlay Icons for Std Link nearly invisible small
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Forums discussion

https://forum.freecadweb.org/viewtopic.php?f=3&t=68061&p=589456#p589444

### Version

0.20 (Development)

### Full version info

```shell
OS: macOS 10.16
Word size of FreeCAD: 64-bit
Version: 0.20.28717 (Git)
Build type: Release
Python 3.9.12, Qt 5.12.9, Coin 4.0.0, OCC 7.5.3
Locale: C/Default (C)
Installed mods: 
  * FC_SU
  * DynamicData 2.45.0
  * FeedsAndSpeeds 0.4.0
  * fcgear
  * A2plus 0.4.54b
  * fasteners
  * sheetmetal
  * ExplodedAssembly
  * Curves 0.3.0
```

### Subproject(s) affected?

_No response_

### Issue description

The overlay icons are on a high resolution near to invisible.
Other overlays e.g. indicating non attached or not fully constrained sketches have their normal size.

image

Edit: Overlay icons explained in the wiki: https://wiki.freecad.org/Tree_view#Overlay_icons

### Anything else?

Display resolution is 3072x1920 (Retina display)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by kadet1090**
Like #22345 it fixes issue with too small arrow on high DPI displays. The problem was that the code in ViewProviderLink used width that is already multiplied by DPR as size for icon that expects not premultiplied size, which was messing with proportions.

@maxwxyz can you test that it works as it should?

## Issues
Closes #22345
Fixes #6765

## Before and After Images

| Before | After |
|--------|--------|
| image |image  | 

Not sure why I get pixelated icons in that case, but I had it also before so probably some issue with my way of testing HighDPI stuff.

### CODE REVIEW

**Review by maxwxyz — APPROVED** [review]
I can confirm this fixes the issue. Closing my PR then.

File: src/Gui/ViewProviderLink.cpp [hunk 1]
```diff
@@ -673,8 +673,10 @@ class Gui::LinkInfo {
 
     QIcon getIcon(QPixmap px) {
         static int iconSize = -1;
-        if(iconSize < 0)
-            iconSize = QApplication::style()->standardPixmap(QStyle::SP_DirClosedIcon).width();
+        if (iconSize < 0) {
+            auto sampleIcon = QApplication::style()->standardPixmap(QStyle::SP_DirClosedIcon);
+            iconSize = sampleIcon.width() / sampleIcon.devicePixelRatio();
```
Comment (hyarion) [inline src/Gui/ViewProviderLink.cpp]: Suppress warning:
```suggestion
            double pixelRatio = sampleIcon.devicePixelRatio();
            iconSize = static_cast<int>(sampleIcon.width() / pixelRatio);
```
