### PR TITLE
core: fixes #29090 allow navigation ie. pan, orbit, track after using long LMB press

### LINKED ISSUE #29090: Clarify Selection: When selecting with a long press, moving and rotating stop working
### Problem description

When selecting with a long press, moving and rotating stop working; when deselecting, they start working again. If selecting through G, G everything works fine. In version 1.1 the behavior is the same

https://github.com/user-attachments/assets/3375498e-fbea-48dd-ad5d-eb40d1592fb7

### Workbench affected?

Other (specify in description)

### Steps to reproduce

-

### Expected behavior

-

### Actual behavior

-

### Development version About Info (in Safe Mode)

```shell
OS: Windows 11 build 26200
Architecture: x86_64
Version: 1.2.0dev.20260331 (Git shallow)
Build date: 2026/03/31 20:44:58
Build type: Release
Branch: (HEAD detached at 591c20176)
Hash: 591c201769da7bc9048562897da36c71fdddee9f
Python 3.11.15, Qt 6.8.3, Coin 4.0.8, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.3.0, IfcOpenShell 0.8.2, OCC 7.8.1
Locale: Russian/Russia (ru_RU)
Stylesheet/Theme/QtStyle: FreeCAD.qss/FreeCAD Dark/
Navigation Style/Orbit Style/Rotation Mode: Revit/Turntable/Drag at cursor
Logical DPI/Physical DPI/Pixel Ratio: 96/92.6073/1
Installed mods:
  * AddFC Workbench 3.5.7
  * Curved Shapes 1.0.14
  * Curves workbench 0.6.71
  * Fasteners Workbench 0.5.50
  * PieMenu 1.12.4
  * SheetMetal Workbench 0.8.10
  * StructureTools 0.0.1
  * SvgWorkbench 1.0.0.dev14
  * Telemetry 1.0.5
```

### Last known good version (optional)

```shell
-
```

### PR DESCRIPTION
**Pull request by ipatch**
this PR fixes the issue defined in #29090 add the below check to reset the navigation state for all three mouse buttons.

```cpp
// reset navigation state so button1down doesn't stay stuck ie. gh issue #29090
// (the blocking QMenu::exec in ClarifySelection steals the LMB release)
if (currentViewer) {
    if (auto* nav = currentViewer->navigationStyle()) {
        nav->resetButtonState();
    }
}
```

## Issues

- https://github.com/freecad/freecad/issues/29090

### CODE REVIEW

**Review by FEA-eng — APPROVED** [review]
@maxwxyz Tested, fixes the issue

File: src/Gui/Navigation/NavigationStyle.h [hunk 1]
```diff
@@ -211,6 +211,11 @@ class GuiExport NavigationStyle: public Base::BaseClass
         return ClarifySelectionMode::Default;
     }
 
+    void resetButtonState()
```
Comment (chennes) [inline src/Gui/Navigation/NavigationStyle.h:214]: Given this function's name, I'd expect it to restore *all* state to its defaults. Did you consider also adding resets for the rest of the state? (ETA: I think just a call to `setViewingMode(IDLE)` would do it). It seems like it would be harmless in this particular case, and might have some other future use. If you don't want to do that, maybe only call this `resetButtonDownState` instead.

Comment (ipatch) [reply src/Gui/Navigation/NavigationStyle.h]: updated.

**Comment by freecad-ci-runner** [comment]
Successfully created backport PR for `releases/FreeCAD-1-1`:
- #29541
