### PR TITLE
sketcher: fixes #27281 fix access out of bounds crash with "remove axes alignment"

### LINKED ISSUE #27281: Sketcher: crash when using "Remove Axes Alignment" on partially constrained sketch
### Problem description

When using the "Remove Axes Alignment" sketcher tool, FreeCAD crashes with this file:

[sketcher_remove_axis_alignment_crash.zip](https://github.com/user-attachments/files/24991800/sketcher_remove_axis_alignment_crash.zip)

https://github.com/user-attachments/assets/45b237b0-98c5-4cd3-84e0-dcdb29515ee6

Image

The crash might only be visible when compiled with `_GLIBCXX_ASSERTIONS`.

### Workbench affected?

Sketcher

### Steps to reproduce

open provided file
select right square
Sketch -> Sketcher Tools -> Remove Axes Alignment

### Development version About Info (in Safe Mode)

```shell
OS: Arch Linux (KDE/plasma/wayland)
Architecture: x86_64
Version: 1.2.0dev.45204 (Git)
Build date: 2026/02/01 10:48:44
Build type: Unknown
Branch: main
Hash: 0954760859ad22c3ea7c40c12edd82c066090a61
Python 3.14.2, Qt 6.10.2, Coin 4.0.7, Vtk 9.5.2, boost 1_89, Eigen3 3.4.1, PySide 6.10.1
shiboken 6.10.1, SMESH 7.7.1.0, xerces-c 3.3.0, OCC 8.0.0.rc3-c47d9c06b5
Locale: English/United States (en_US) [ OS: German/Germany (de_DE) ]
Navigation Style/Orbit Style/Rotation Mode: Blender/Rounded Arcball/Drag at cursor
Stylesheet/Theme/QtStyle: unset/FreeCAD Light/
Logical DPI/Physical DPI/Pixel Ratio: 96/91.7555/1.5
Installed mods: 
  * kicadStepUpMod 11.8.2
  * Gridfinity 0.11.9
  * fasteners-backup-before-zip-migration 0.5.39 (Disabled)
  * kicadStepUpMod-backup-before-zip-migration 11.7.3 (Disabled)
  * lattice2-backup-before-zip-migration 1.0.0 (Disabled)
  * sheetmetal 0.7.60
  * fcgear 1.0.0
  * sheetmetal-backup-before-zip-migration 0.7.24 (Disabled)
  * Curves-backup-before-zip-migration 0.6.65 (Disabled)
  * fasteners 0.5.43
  * Assembly4 0.60.6
  * Curves 0.6.70
  * Assembly4-backup-before-zip-migration 0.60.2 (Disabled)
  * lattice2 1.1.0
  * FusedFilamentDesign 0.25.510
```

### Last known good version (optional)

```shell

```

### PR DESCRIPTION
**Pull request by ipatch**
this pr fixes #27281, presently with the latest dev build a crash can occur if one builds freecad with the below cxx flag

```
-D_GLIBCXX_ASSERTIONS
```

for my local build i used the following cxx flags,

```
-DCMAKE_CXX_FLAGS="-I$bp/opt/mesa/include -I$bp/opt/pybind11_py312/include -I$bp/opt/mesa-glu/include -D_GLIBCXX_ASSERTIONS" \
```

## Issues

fixes issue #27281

- https://github.com/FreeCAD/FreeCAD/issues/27281

## Before and After Images

see above mentioned issue for images of crash.

see below attached video for demo with fix applied.

https://github.com/user-attachments/assets/2c80bc05-da1d-4423-99d6-21ca47186e49

### CODE REVIEW

File: src/Mod/Sketcher/App/SketchObject.cpp [hunk 1]
```diff
@@ -5666,9 +5667,10 @@ int SketchObject::removeAxesAlignment(const std::vector<int>& geoIdList)
         {{Sketcher::Horizontal, GeoEnum::GeoUndef},
          {Sketcher::Vertical, GeoEnum::GeoUndef}};
 
-    int cindex = 0;
+    size_t cindex = 0;
     for (size_t i = 0; i < constrvals.size(); i++) {
-        if (i != changeConstraintIndices[cindex].first) {
+        if (cindex >= changeConstraintIndices.size()
```
Comment (chennes) [inline src/Mod/Sketcher/App/SketchObject.cpp:5672]: Under what circumstances does this new condition trigger? How are these arrays getting out-of-sync?

Comment (PaddleStroke) [reply src/Mod/Sketcher/App/SketchObject.cpp:5672]: The fix is correct. 

If the last constraint to be modified is at an index less than the total number of constraints (e.g., you are modifying constraint #5 but there are 10 constraints in total), the loop for i will continue to 6, 7, 8... while cindex has already reached the end of the changeConstraintIndices vector.

Accessing changeConstraintIndices[cindex] when cindex >= size is Undefined Behavior. On systems with _GLIBCXX_ASSERTIONS enabled (like modern Fedora or debug builds), this triggers an immediate abort/crash.

Now the thing is that this logic structure of the whole function seems brittle and weird to me. The proof of that is that to understand the fix one has to look at the function for a long time to understand why it's ok. I mean why is the function running two passes and synchronise indexes in the first place? It's doesn't make sense

**Comment by PaddleStroke** [comment]
While the fix is correct, it feels like a band-aid on a broken leg. The function needs refactoring.

**Review by PaddleStroke — APPROVED** [review]
