### PR TITLE
Gui: Buggy Wayland custom cursors workaround

### LINKED ISSUE #10048: [Problem] QWaylandShmBuffer: mmap failed (Invalid argument)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.21 (Development)

### Full version info

```shell
[code]
OS: Arch Linux
Word size of FreeCAD: 64-bit
Version: 0.21.0.33675 (Git)
Build type: Release
Branch: makepkg
Hash: 41b058e2087de60dc8fef3d3e68c7d0129e13abf
Python 3.11.3, Qt 5.15.10, Coin 4.0.1, Vtk 9.2.6, OCC 7.6.3
Locale: C/Default (C)
Installed mods: 
  * dodo 1.0.0
  * FreeCAD_assembly3 0.12.0
  * FreeCAD_FastenersWB 0.4.58
  * FreeCAD_Assembly4 0.50.2
  * FreeCAD_SheetMetal 0.2.63
  * Lattice2 1.0.0
  * freecad.gears 1.0.0
  * CurvesWB 0.6.12
[/code]
```

### Subproject(s) affected?

None

### Problem description

I installed the freecad from arch linux repository. I use [sway](https://github.com/swaywm/sway) as the window compositor.

When I opened the 0.21 freecad, it shows this on the report view:
`(qt.qpa.wayland) Wayland does not support QWindow::requestActivate()`

Then I opened a file. I rotated the object view using mouse and report view shows this:
`QWaylandShmBuffer: mmap failed (Invalid argument)`

It interrupts the workflow because the report view pop up every time I rotate the object view.

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by 3x380V**
Fixes #10048

Until Qt 6.6 custom cursors are not shown at all on Wayland, so add a workaround. See also QTBUG-95434.
Workaround is limited to FreeCAD running on Wayland and Qt versions between 5.13 and 6.6. Versions prior implementing needed `QImage:: convertTo` are unlikely to be found running on Wayland.
As soon as the oldest supported Qt version becomes 6.6 on Linux, this workaround should be removed.

### CODE REVIEW

**Comment by 3x380V** [comment]
I hereby politely pinging _@adrianinsaval in https://github.com/FreeCAD/FreeCAD/issues/10048#issuecomment-1728673841_ to look at this and increase a chance fix would hit the next release.

File: src/Gui/View3DInventorViewer.cpp [hunk 1]
```diff
@@ -642,35 +642,46 @@ View3DInventorViewer::~View3DInventorViewer()
     delete glAction;
 }
 
-void View3DInventorViewer::createStandardCursors(double dpr)
+// QTBUG-95434
```
Comment (wwmayer) [inline src/Gui/View3DInventorViewer.cpp:645]: In terms of clean code this shouldn't be a macro but a proper function. Then then whole cursor handling code should be refactored and moved to its own class.

For future work:
There is also a class ToolHandler in the core system that partially handles the creation of cursor pixmaps. It would be good to refactor that as well to have all cursor related code in one class.

Comment (3x380V) [reply src/Gui/View3DInventorViewer.cpp:645]: I originally wrote that as a function and then moved back to the macro as it minimizes impact on other platforms. The logic is while we already need to preprocessor to deal with testing Qt versions, lets use it for all the stuff. Please note I'm able to test only on Linux and I didn't want to break anything else. I do not understand why `254ed951f924687e3dffb325288bbc0333980b9c` limited setting cursor pixel ratio to Windows only. Knowing all those details would help me to refactor code (yes, we are back to understandable commit messages).

I do not want to touch this that late in development cycle, so refactoring is out of scope now. Leaving for two weeks, so I will not be able to react to complains if I break anything I cannot test during refactor. That said, anyone is free to use this as a base for his own nice solution. If nothing happens until I return and people are okay with touching it more radical way and there is still time to give it more testing, I'm fine with that.

**Comment by chennes** [comment]
@kadet1090 is going to take a look at revising this.

File: src/Gui/View3DInventorViewer.cpp (hunk 1 above)
Comment (wwmayer) [reply src/Gui/View3DInventorViewer.cpp:645]: > I do not understand why 254ed951f924687e3dffb325288bbc0333980b9c limited setting cursor pixel ratio to Windows only.

This is because the Win32 API works differently compared to the APIs of other platforms.

Comment (kadet1090) [reply src/Gui/View3DInventorViewer.cpp:645]: This macro is called only once - there is no need to even declare it as function, simply inline it where it is used:

```
QPixmap View3DInventorViewer::fixupCursor(const QBitmap &bitmap, const QBitmap &mask, double dpr) const
{
#if defined(Q_OS_LINUX) && QT_VERSION < QT_VERSION_CHECK(6,6,0) && QT_VERSION >= QT_VERSION_CHECK(5,13,0)
    // QTBUG-95434
    QPixmap pixmap;
    if (qGuiApp->platformName() == QLatin1String("wayland")) {
        QImage img = bitmap.toImage();
        img.convertTo(QImage::Format_ARGB32);
        pixmap = QPixmap::fromImage(img);
    } else {
        pixmap = bitmap;
    }
#else
    QPixmap pixmap(bitmap);
#endif

    pixmap.setMask(mask);
#if defined(Q_OS_WIN32)
    pixmap.setDevicePixelRatio(dpr);
#else
    Q_UNUSED(dpr)
#endif
    return pixmap;
}
```

Comment (3x380V) [reply src/Gui/View3DInventorViewer.cpp:645]: > > I do not understand why [254ed95](https://github.com/FreeCAD/FreeCAD/commit/254ed951f924687e3dffb325288bbc0333980b9c) limited setting cursor pixel ratio to Windows only.
> 
> This is because the Win32 API works differently compared to the APIs of other platforms.

Yes, that is obvious from that `#if defined(Q_OS_WIN32)` in the code and there are gazilions of cursor related bugs in QT bug tracker, so some reference could be handy. I found similar solution referenced in [QTBUG-52211](https://bugreports.qt.io/browse/QTBUG-52211?focusedId=352267&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-352267) Nevermind, I won't touch this.

@kadet1090, indeed macro is used only once and it needs to `#include <QGuiApplication>` so this is just feasible way, how to do it using single ifdef. I'm aware that other workarounds adds includes unconditionally and I do not agree with that. It is implemented as a macro on purpose, to keep workaround code at single place, so it is self explaining and will be useful when removing it again.

**Comment by 3x380V** [comment]
@kadet1090, to speed things up, here is no macro version: c0ba72f74caf If you for whatever reason find my explanation above unsuitable, I'll force push it here.

**Comment by kadet1090** [comment]
@3x380V On merge meeting there were raised concerns about introducing such macro, I volunteered to see how it can be done without it. That said I do prefer version without macro, I also very like your approach with the `# define HAS_QTBUG_95434` and IMHO it is much cleaner way and it is very readable.

File: src/Gui/View3DInventorViewer.cpp [hunk 2]
```diff
@@ -642,35 +646,43 @@ View3DInventorViewer::~View3DInventorViewer()
     delete glAction;
 }
 
-void View3DInventorViewer::createStandardCursors(double dpr)
+QPixmap View3DInventorViewer::fixupCursor(const QBitmap &bitmap, const QBitmap &mask, double dpr) const
```
Comment (kadet1090) [inline src/Gui/View3DInventorViewer.cpp:649]: As this has no reference to the `this` object it probably could be a private function of this file and so it would not need to be defined in the `.h` file. I'm living this only as a sidenote however, this way is also fine by me.

**Review by kadet1090 — APPROVED** [review]

File: src/Gui/View3DInventorViewer.cpp (hunk 2 above)
Comment (3x380V) [reply src/Gui/View3DInventorViewer.cpp:649]: Indeed. I did it this way for consistency as I didn't find any other private function in that file, but I was obviously not looking hard enough. After test build finishes here, I'll push this change as well.

**Comment by chennes** [comment]
This PR breaks the rotation cursor on Windows 11 (Coin 4.0.2, Qt 6.8 -- so should not be subject to this bug at all). It does NOT break any of Sketcher's cursors, interestingly. The only one I noticed is that when rotating, I get a small black square instead of the arrows.

**Comment by 3x380V** [comment]
@chennes, could you retry? As a last resort I could try to pass parameters by a reference to make code exactly the same on windows.

**Comment by chennes** [comment]
No change -- the rotation cursor still shows as a single black square.

**Comment by 3x380V** [comment]
@chennes, can you run yet another test, please?

**Comment by chennes** [comment]
The cursor seems correct now.

**Comment by 3x380V** [comment]
@kadet1090, please look at this again. `fixupCursor` is now `createCursor` as it directly returns cursor instance. Creating cursor from pixmap didn't work on Windows, hence the change, so now it works the very same way for platform not affected by QTBUG-95434.
