### PR TITLE
Materials: Default units

### LINKED ISSUE #18272: Material: Ability to select incorrect unit
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Steps to reproduce

- creat new material
- add group of fluid properties
- type in '10 s' into density value
- the resulting value is with wrong unit

I am able to reproduce with other units, such as kg, etc.
units

### Full version info

```shell
OS: Windows 10 build 19045
Architecture: x86_64
Version: 1.0.0.39109 (Git) Conda
Build type: Release
Branch: (HEAD detached at 1.0.0)
Hash: 2fcc5317fe3aee96ca73475986a577719fc78e20
Python 3.11.10, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: FreeCAD Light.qss/FreeCAD Light/Fusion
```

### Subproject(s) affected?

Material

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #18870: Material: Density unit incorrect
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When defining a new material, the density units shown in the material editor are [kg/**m**<sup>3</sup>]. After applying the material parameters however, the body property in the tree view shows the same value with a different unit, [kg/**mm**<sup>3</sup>] - leading to a 10<sup>9</sup> error. I assume this is just a typo in the property description.
In my example, I used 1300kg/m<sup>3</sup> (equals 1.3g/cm<sup>3</sup>) and then end up with 1300t for a cube of 1cm length. The ratio of 130t/1.3g = 10<sup>9</sup> matches the scaling of m<sup>3</sup> to mm<sup>3</sup>.
I saw the solved issue [regarding](https://github.com/FreeCAD/FreeCAD/issues/18149) displaying small material values, but don't think this is related?
Density property description:
Screenshot from 2025-01-04 19-23-37

Set material density value:
Screenshot from 2025-01-04 19-37-27

Body properties in tree view (1cm cube):
Screenshot from 2025-01-04 19-38-01

### Full version info

```shell
OS: Ubuntu 24.04.1 LTS (ubuntu:GNOME/ubuntu/wayland)
Architecture: x86_64
Version: 1.1.0dev.39745 (Git)
Build type: Release
Branch: main
Hash: 6bb424b5d16adffb1896187a0725945f9635d144
Python 3.12.3, Qt 5.15.13, Coin 4.0.2, Vtk 9.1.0, OCC 7.8.1
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: FreeCAD Light.qss/FreeCAD Light/Fusion
Installed mods: 
  * FreeCAD-themes 2024.7.24
```

### Subproject(s) affected?

None

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by davesrocketshop**
Improves handling and assignment of default units

When creating a material without specifying units, no units are currently assigned. This PR will assign the default units when none are given, or throw an error when incompatible units are given. In the latter case, the units are set to the property defaults.

This PR also incidentally fixed an issue  when saving the material that resulted in accessing an uninitialized pointer.

Fixes #18272 
Fixes #18870

### CODE REVIEW

**Comment by davesrocketshop** [comment]
When entering the wrong units in the material editor, you get this message box:

Screenshot 2025-04-21 204713

File: src/Mod/Material/App/Materials.cpp [hunk 1]
```diff
@@ -386,6 +399,20 @@ void MaterialProperty::setFloat(const QString& value)
 void MaterialProperty::setQuantity(const Base::Quantity& value)
 {
     auto quantity = value;
+    auto units = quantity.getUnit();
+    Base::Unit propertyUnit = Base::Unit(getUnits().toStdString());
+    if (units.isEmpty()) {
```
Comment (3x380V) [inline src/Mod/Material/App/Materials.cpp:404]: This will stop working. Unfortunately I cannot tell when as there is PR pending since Feb 15.
You are welcome to browse [desired state](https://github.com/3x380V/FreeCAD/tree/cleanup-afterwards) meanwhile...

Comment (3x380V) [reply src/Mod/Material/App/Materials.cpp:404]: Indeed and correct branch is chosen... Do you want me to be [more specific](https://github.com/3x380V/FreeCAD/commits/cleanup-afterwards/)?

Comment (davesrocketshop) [reply src/Mod/Material/App/Materials.cpp:404]: Equally important, why is it changing?

**Comment by 3x380V** [comment]
As it does not make sense in first place. Quantity is a value and unit. Constructing unit using string means creating quantity and returning its unit. We are trying to make units constexpr and this spaghetti is standing in the way.

File: src/Mod/Material/App/Materials.cpp (hunk 1 above)
Comment (3x380V) [reply src/Mod/Material/App/Materials.cpp:404]: As it does not make sense in first place. Quantity is a value and unit. Constructing unit using string means creating quantity and returning its unit. We are trying to make units constexpr and this spaghetti is standing in the way.

Comment (davesrocketshop) [reply src/Mod/Material/App/Materials.cpp:404]: As you can see it certainly makes sense here. Often quantities are specified without specifying the units, requiring the code to create the quantity with the value and default units as is done here. Checking to see if the units are set is a perfectly valid operation. I think the arguments presented for removing it are flimsy at best, especially since it breaks the API.

this could easily be implemented with the changes you've made. Removing it makes no sense.

Comment (davesrocketshop) [reply src/Mod/Material/App/Materials.cpp:404]: And I see I'm not the only one who has expressed this opinion.

Comment (3x380V) [reply src/Mod/Material/App/Materials.cpp:404]: Any pointers? Unit was never able to parse a string. Only Quantity has such ability. It is basically: `Quantity::parse(expr).getUnit();`
Of course you are welcome to join corresponding PRs.

Comment (3x380V) [reply src/Mod/Material/App/Materials.cpp:404]: If you want to check if a `Quantity` has a `Unit` just use `isDimensionless()`. The `isValid()` method of `Unit` is misleading at best as it never had anything common with unit validity. It merely returns `true` on all zero exponents; the case when unit equals to 1. A perfectly valid operation both mathematically and also in the real world.
So you probably wanted to express something like:
```
void MaterialProperty::setQuantity(const Base::Quantity& value)
{
    Base::Quantity quantity;
    if (value.isDimensionless()) {
        quantity = Base::Quantity::parse(value.getUserString() + getUnits().toStdString());
    }
    else {
        auto propertyUnit = Base::Quantity::parse(getUnits().toStdString()).getUnit();
        if (propertyUnit != value.getUnit()) {
            throw Base::ValueError("Incompatible material units");
        }
        quantity = value;
    }
    quantity.setFormat(MaterialValue::getQuantityFormat());
    _valuePtr->setValue(QVariant(QVariant::fromValue(quantity)));
}
```

**Comment by 3x380V** [comment]
Commit message of this pull request is mentioning a pull request. There are no pull requests on this level, so this is a bit misleading.

File: src/Mod/Material/App/Materials.cpp (hunk 1 above)
Comment (davesrocketshop) [reply src/Mod/Material/App/Materials.cpp]: Updated

**Comment by davesrocketshop** [comment]
> Commit message of this pull request is mentioning a pull request. There are no pull requests on this level, so this is a bit misleading.

?? The only PR it mentions is this one.

**Comment by 3x380V** [comment]
Indeed, it is perfectly fine to have this wording in the pull request description, but does not make sense the commit message itself. Anyone doing `git pull` will see it in the git history and there is no PR on this level.
What if a commit message would read:
```
Materials: Default units

Improves handling and assignment of default units

When creating a material without specifying units, no units are
currently assigned. Assign the default units when none are
given, or throw an error when incompatible units are given. In the
latter case, the units are set to the property defaults.

This also incidentally fixes an issue when saving the material that
resulted in accessing an uninitialized pointer.
```
That is really a nit I noticed while reading your patch, so put short note above. Nothing I would like to argue about much longer...
