### PR TITLE
Changed QuickMeasurement to be conservative

### LINKED ISSUE #16888: Measurement: Too many segfaults in QuickMeasure (here's one more)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Everything the user clicks on in the FreeCAD GUI - whether in the part tree, the 3d view, or in selection dialogues in widgets (for example Results of Part_CheckGeometry - but also 3rd party mods) usually makes a selection.

Every selection is passed through QuickMeasure - it gets called from more or less every single click, which exposes this module to a verly large exposure-manifold w.r.t. the stuff it can be called with and the combinations.

For this to be feasible, QuickMeasure has to be coded in a very robust way to deal with this large variety of unknown cases, also in a future proof manner.

This is not the case. As a result, the activation of QuickMeasure in 1.0 has triggered a multitude of regressions, typically ending in a segfault, such as:  
* #14076 
* #16794
* #16844 
* #16820
* #16744

etc ...
some of which have been fixed while others are hard to reproduce.

This report adds one more. The way Part_CheckGeometry exposes problematic surfaces they are reported not in their immediate partent but in the part they reside in. Clicking on those crashes, since QuickMeasure can only handle selections of things within their immediate parent:

**Steps to reproduce:**
1. Make a new document with at least one Part called "Part"
2. In Python console, enter `Gui.Selection.addSelection(App.ActiveDocument.Name,'Part','SegfaultPlease')`

**Expected Outcome:**
Throw an exception of some kind

**Actual Outcome:**
Segfault from Null pointer dereferencing in QuickMeasure.cpp

The issue is here:

QuickSelection.cpp 122++
```
auto shouldSkip = [](App::DocumentObject* obj) {
        std::string vpType = obj->getViewProviderName();
        auto* vp = Gui::Application::Instance->getViewProvider(obj);
        return (vpType == "SketcherGui::ViewProviderSketch" && vp->isEditing())
            || vpType.find("Gui::ViewProviderOrigin") != std::string::npos
            || vpType.find("Gui::ViewProviderPart") != std::string::npos
            || vpType.find("SpreadsheetGui") != std::string::npos
            || vpType.find("TechDrawGui") != std::string::npos;
    };

```

Aside from the obvious - causing a segfault of obj==NULL  - this is a list of "known bad cases" where quickmeasurement should stay away from- which is a good start but essentially the wrong thinking.  Any future modification and any Mod may add new ViewProviders - any number of which may add shapes that QuickMeasurement can't handle and may crash.

This is just the start. The whole module seems to be coded with blind trust in that the selected objects are all "nails" that can be hammered in - no check if they are pointy or might explode when hammered - as apparent from the previously fixed - and yet unfixed issues above.

I am suggesting treating this issue as a blocker until QuickMeasure has been hardened or deactivated (or deactivated until it has been hardened)

### Full version info

```shell
OS: Ubuntu 20.04.6 LTS (XFCE/xfce)
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38844 (Git)
Build type: Debug
Branch: main
Hash: 6e2cd4e73303f817e4bf5e908abe39030b7c5fb3
Python 3.8.10, Qt 5.12.8, Coin 4.0.0, Vtk 7.1.1, OCC 7.6.3
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
OS: Ubuntu 20.04.6 LTS (XFCE/xfce)
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38844 (Git)
Build type: Debug
Branch: main
Hash: 6e2cd4e73303f817e4bf5e908abe39030b7c5fb3
Python 3.8.10, Qt 5.12.8, Coin 4.0.0, Vtk 7.1.1, OCC 7.6.3
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
Installed mods: 
  * Curves 0.6.48
```

### Subproject(s) affected?

Core

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by AIRCAP**
fix #16888

QuickMeasurement should not measure while tool dialogs are open this includes but is not limited to editing sketches also changed several other sanity checks to be opt-in vs opt-out, as discussed.

### CODE REVIEW

File: src/Mod/Measure/Gui/QuickMeasure.cpp [hunk 1]
```diff
@@ -111,24 +111,30 @@ void QuickMeasure::tryMeasureSelection()
...
-    if (!obj || !obj->isDerivedFrom(Part::Feature::getClassTypeId())) {
-        return false;
+    // only measure shapes
+    if (obj && obj->isDerivedFrom(Part::Feature::getClassTypeId())) {
+        return true;
     }
 
-    std::string vpType = obj->getViewProviderName();
-    auto* vp = Gui::Application::Instance->getViewProvider(obj);
-    return !(vpType == "SketcherGui::ViewProviderSketch" && vp && vp->isEditing());
```
Comment (AIRCAP) [inline src/Mod/Measure/Gui/QuickMeasure.cpp:131]: the check for "not editing a sketch" is no longer needed, since editing *anything* will now disable QuickMeasure

**Comment by hyarion** [comment]
These changes reflects what was discussed during the developer meeting earlier today:
* summarized by here https://github.com/FreeCAD/FreeCAD/issues/16888#issuecomment-2395508637
* and here https://github.com/FreeCAD/FreeCAD-developer-meetings/blob/main/Minutes/minutes-2023-10-06.md as `reducing traffic to QM / opt-in vs opt-out ("else return true") seems to be a reasonable approach.`

I think this is a good approach as it:
* removes *false positives* that can lead to exceptions and crashes and
* trades that to *potential false negatives*, where the worst thing is that the user don't get a measure.

The outcome of a missing readout might be annoying, but a crash is really bad.

👍 

FYI @PaddleStroke any input on this PR?

**Comment by AIRCAP** [comment]
I changed the logic a bit again to be even safer. The issue that the test `shouldMeasure()` was done when the event was triggered - this makes sense as far as the event itself is concerned (is it actually the right type of event) but its dangerous to check the state of the document and Gui there only and then rely on it

because the actual measuring takes place when the timer fires and by then things might have changed.

So in the last commit I moved all tests w.r.t. the state ( particularly document and any Task dialogs open ) to when the timer actually fires. This is when it really matters, and it has the additional benefit that the status line is cleared and no stale measurements remain there while in a Task Dialog.

File: src/Mod/Measure/Gui/QuickMeasure.cpp (hunk 1 above)
Comment (PaddleStroke) [reply src/Mod/Measure/Gui/QuickMeasure.cpp:131]: Minor: In this case you can directly `return obj && obj->isDerivedFrom(Part::Feature::getClassTypeId())`

**Comment by PaddleStroke** [comment]
Looks good.

> The outcome of a missing readout might be annoying, but a crash is really bad.

+1.

File: src/Mod/Measure/Gui/QuickMeasure.cpp (hunk 1 above)
Comment (AIRCAP) [reply src/Mod/Measure/Gui/QuickMeasure.cpp:131]: IMHO the code is functionally easier to read as is - the compiler will further optimize that when generating machine code anyway

Comment (chennes) [reply src/Mod/Measure/Gui/QuickMeasure.cpp:131]: I'm fine with leaving it like this, as long as the linter doesn't complain about it -- pylint is much crankier about such constructions than our current C++ linters.

**Comment by chennes** [comment]
Backported to 1.0
