### PR TITLE
Material: Material editor enhancements

### LINKED ISSUE #11686: [Problem] FreeCAD crashes when activating `Materials_Edit` (segfault)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I wanted to try the latest changes to the Material worbench with the weekly AppImage version. Clicking on `Materials_Edits` crashes FreeCAD. The previous weekly (0.22.0dev.35249) doesn’t crash.

How to reproduce:

1. Start FreeCAD
2. Create a new file
3. Go to the Material workbench
4. Click on `Materials_Edit`

### Full version info

```shell
OS: Ubuntu 23.04 (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.35315 (Git) AppImage
Build type: Release
Branch: main
Hash: 09f67f2f6bff1c57ac8019a5ba2f4a2c41025ee6
Python 3.10.13, Qt 5.15.8, Coin 4.0.2, Vtk 9.2.6, OCC 7.6.3
Locale: French/France (fr_FR)
Installed mods: 
  * Render 2023.8.18
  * OpenDark 2023.12.1
```

### Subproject(s) affected?

Other (specify in description)

### Anything else?

```
FreeCAD 0.22.0, Libs: 0.22.0devR35315 (Git)
© Juergen Riegel, Werner Mayer, Yorik van Havre and others 2001-2023
FreeCAD is free and open-source software licensed under the terms of LGPL2+ license.
FreeCAD wouldn't be possible without FreeCAD community.
  #####                 ####  ###   ####  
  #                    #      # #   #   # 
  #     ##  #### ####  #     #   #  #   # 
  ####  # # #  # #  #  #     #####  #   # 
  #     #   #### ####  #    #     # #   # 
  #     #   #    #     #    #     # #   #  ##  ##  ##
  #     #   #### ####   ### #     # ####   ##  ##  ##

Loading Assembly workbench...
Program received signal SIGSEGV, Segmentation fault.
#0  /lib/x86_64-linux-gnu/libc.so.6(+0x3c460) [0x7f70c7a3c460]
#1  0x7f6fb89ae592 in Materials::MaterialProperty::setValue(QString const&) from /tmp/.mount_FreeCAmQVGm5/usr/lib/./Material.so+0x22
#2  /tmp/.mount_FreeCAmQVGm5/usr/lib/./Material.so(+0x7cc62) [0x7f6fb8979c62]
#3  0x7f6fb89843a6 in Materials::MaterialConfigLoader::addRenderWB(QMap<QString, QString>&, std::shared_ptr<Materials::Material> const&) from /tmp/.mount_FreeCAmQVGm5/usr/lib/./Material.so+0x156
#4  0x7f6fb89863c9 in Materials::MaterialConfigLoader::getMaterialFromPath(std::shared_ptr<Materials::MaterialLibrary> const&, QString const&) from /tmp/.mount_FreeCAmQVGm5/usr/lib/./Material.so+0x6b9
#5  0x7f6fb89a008c in Materials::MaterialLoader::getMaterialFromPath(std::shared_ptr<Materials::MaterialLibrary> const&, QString const&) const from /tmp/.mount_FreeCAmQVGm5/usr/lib/./Material.so+0x6c
#6  0x7f6fb89a0658 in Materials::MaterialLoader::loadLibrary(std::shared_ptr<Materials::MaterialLibrary> const&) from /tmp/.mount_FreeCAmQVGm5/usr/lib/./Material.so+0x158
#7  0x7f6fb89a0a8d in Materials::MaterialLoader::loadLibraries() from /tmp/.mount_FreeCAmQVGm5/usr/lib/./Material.so+0x4d
#8  0x7f6fb89a0b5d in Materials::MaterialLoader::MaterialLoader(std::shared_ptr<std::map<QString, std::shared_ptr<Materials::Material>, std::less<QString>, std::allocator<std::pair<QString const, std::shared_ptr<Materials::Material> > > > > const&, std::shared_ptr<std::__cxx11::list<std::shared_ptr<Materials::MaterialLibrary>, std::allocator<std::shared_ptr<Materials::MaterialLibrary> > > > const&) from /tmp/.mount_FreeCAmQVGm5/usr/lib/./Material.so+0x4d
#9  0x7f6fb89a1ece in Materials::MaterialManager::initLibraries() from /tmp/.mount_FreeCAmQVGm5/usr/lib/./Material.so+0x13e
#10  0x7f6fb89a2193 in Materials::MaterialManager::MaterialManager() from /tmp/.mount_FreeCAmQVGm5/usr/lib/./Material.so+0x23
#11  0x7f6fb8a6d6c9 in MatGui::MaterialsEditor::MaterialsEditor(QWidget*) from /tmp/.mount_FreeCAmQVGm5/usr/lib/MatGui.so+0x69
#12  0x7f6fb8a4dd08 in CmdMaterialsEdit::activated(int) from /tmp/.mount_FreeCAmQVGm5/usr/lib/MatGui.so+0x188
#13  0x7f70ca974d88 in Gui::Command::_invoke(int, bool) from /tmp/.mount_FreeCAmQVGm5/usr/bin/../lib/libFreeCADGui.so+0x2a8
#14  0x7f70ca975144 in Gui::Command::invoke(int, Gui::Command::TriggerSource) from /tmp/.mount_FreeCAmQVGm5/usr/bin/../lib/libFreeCADGui.so+0x134
#15  /tmp/.mount_FreeCAmQVGm5/usr/bin/../lib/libQt5Core.so.5(+0x2e9214) [0x7f70c80e9214]
#16  0x7f70c8f6a422 in QAction::triggered(bool) from /tmp/.mount_FreeCAmQVGm5/usr/bin/../lib/libQt5Widgets.so.5+0x32
#17  0x7f70c8f6cdeb in QAction::activate(QAction::ActionEvent) from /tmp/.mount_FreeCAmQVGm5/usr/bin/../lib/libQt5Widgets.so.5+0xab
#18  /tmp/.mount_FreeCAmQVGm5/usr/bin/../lib/libQt5Widgets.so.5(+0x25cb9a) [0x7f70c905cb9a]
#19  0x7f70c905ccd7 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) from /tmp/.mount_FreeCAmQVGm5/usr/bin/../lib/libQt5Widgets.so.5+0xe7
#20  0x7f70c9145a4a in QToolButton::mouseReleaseEvent(QMouseEvent*) from /tmp/.mount_FreeCAmQVGm5/usr/bin/../lib/libQt5Widgets.so.5+0xa
#21  0x7f70c8faebd8 in QWidget::event(QEvent*) from /tmp/.mount_FreeCAmQVGm5/usr/bin/../lib/libQt5Widgets.so.5+0x178
#22  0x7f70c8f7035e in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /tmp/.mount_FreeCAmQVGm5/usr/bin/../lib/libQt5Widgets.so.5+0x7e
#23  0x7f70c8f78222 in QApplication::notify(QObject*, QEvent*) from /tmp/.mount_FreeCAmQVGm5/usr/bin/../lib/libQt5Widgets.so.5+0x13a2
#24  0x7f70ca926e19 in Gui::GUIApplication::notify(QObject*, QEvent*) from /tmp/.mount_FreeCAmQVGm5/usr/bin/../lib/libFreeCADGui.so+0x99
#25  0x7f70c80b3fc8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /tmp/.mount_FreeCAmQVGm5/usr/bin/../lib/libQt5Core.so.5+0x108
#26  0x7f70c8f763ab in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) from /tmp/.mount_FreeCAmQVGm5/usr/bin/../lib/libQt5Widgets.so.5+0x1ab
#27  /tmp/.mount_FreeCAmQVGm5/usr/bin/../lib/libQt5Widgets.so.5(+0x1c6e39) [0x7f70c8fc6e39]
#28  /tmp/.mount_FreeCAmQVGm5/usr/bin/../lib/libQt5Widgets.so.5(+0x1c9f99) [0x7f70c8fc9f99]
#29  0x7f70c8f7035e in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /tmp/.mount_FreeCAmQVGm5/usr/bin/../lib/libQt5Widgets.so.5+0x7e
#30  0x7f70ca926e19 in Gui::GUIApplication::notify(QObject*, QEvent*) from /tmp/.mount_FreeCAmQVGm5/usr/bin/../lib/libFreeCADGui.so+0x99
#31  0x7f70c80b3fc8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /tmp/.mount_FreeCAmQVGm5/usr/bin/../lib/libQt5Core.so.5+0x108
#32  0x7f70c8734bec in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) from /tmp/.mount_FreeCAmQVGm5/usr/bin/../lib/libQt5Gui.so.5+0x84c
#33  0x7f70c870ad7c in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /tmp/.mount_FreeCAmQVGm5/usr/bin/../lib/libQt5Gui.so.5+0xac
#34  /tmp/.mount_FreeCAmQVGm5/usr/plugins/platforms/../../lib/libQt5XcbQpa.so.5(+0x6454a) [0x7f70c26c354a]
#35  /tmp/.mount_FreeCAmQVGm5/usr/bin/../lib/./libglib-2.0.so.0(+0x5a417) [0x7f70c6711417]
#36  /tmp/.mount_FreeCAmQVGm5/usr/bin/../lib/./libglib-2.0.so.0(+0x5d3c7) [0x7f70c67143c7]
#37  /tmp/.mount_FreeCAmQVGm5/usr/bin/../lib/./libglib-2.0.so.0(g_main_context_iteration+0x2e) [0x7f70c67149be]
#38  0x7f70c81083d6 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /tmp/.mount_FreeCAmQVGm5/usr/bin/../lib/libQt5Core.so.5+0x66
#39  0x7f70c80b2bbb in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) from /tmp/.mount_FreeCAmQVGm5/usr/bin/../lib/libQt5Core.so.5+0x11b
#40  0x7f70c80ba6a2 in QCoreApplication::exec() from /tmp/.mount_FreeCAmQVGm5/usr/bin/../lib/libQt5Core.so.5+0x82
#41  0x7f70ca88accd in Gui::Application::runApplication() from /tmp/.mount_FreeCAmQVGm5/usr/bin/../lib/libFreeCADGui.so+0x20ad
#42  /tmp/.mount_FreeCAmQVGm5/usr/bin/freecad(+0x7620) [0x557d2e0c7620]
#43  /lib/x86_64-linux-gnu/libc.so.6(+0x23a90) [0x7f70c7a23a90]
#44  /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x89) [0x7f70c7a23b49]
#45  /tmp/.mount_FreeCAmQVGm5/usr/bin/freecad(+0x7981) [0x557d2e0c7981]
QMutex: destroying locked mutex
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by davesrocketshop**
Continues the work of the material subsystem improvements.

Add support for embedded SVG files. These are not the same as image files so need to be handled differently.

Add the ability to filter materials in the editor when called from code. This allows programs to select objects supporting specific models, complete models, older models, etc.

Updated tests, and refactored code.

New models and materials supporting patterns such as used by the TechDraw workbench.

fixes #11686 - checks for the presense of a model property before assinging a value. This can happen when a required model definition is not available.

### CODE REVIEW

File: src/Mod/TechDraw/App/DrawProjectSplit.cpp [hunk 1]
```diff
@@ -45,6 +44,7 @@
 #include <TopoDS.hxx>
 #include <TopoDS_Shape.hxx>
 #endif
+#include <BOPAlgo_Builder.hxx>
```
Comment (chennes) [inline src/Mod/TechDraw/App/DrawProjectSplit.cpp:47]: This change should no longer be necessary, I've added that include to the PCH.

Comment (davesrocketshop) [reply src/Mod/TechDraw/App/DrawProjectSplit.cpp:47]: Good. I hate adding changes to other people's code. I'll remove it.

**Comment by adrianinsaval** [comment]
It's a strange intermittent issue with the conda env, I triggered a re run and it'll probably pass this time

File: src/Mod/Material/App/CMakeLists.txt [hunk 2]
```diff
@@ -103,7 +105,18 @@ endif(FREECAD_USE_PCH)
...
+if(WIN32)
+    INSTALL(TARGETS Material
+        RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}
+        LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
+    )
+else(WIN32)
+    INSTALL(TARGETS Material
+        LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
+    )
+endif(WIN32)
```
Comment (marioalexis84) [inline src/Mod/Material/App/CMakeLists.txt:122]: @davesrocketshop @chennes any reason to remove the Material library from Mod/Material directory?
This causes a bug if a old version of the file is still present in that directory since Mod/Material takes precedence over /lib in Python's search path. The library should stay in Mod/Material as it happens respectively with the others modules.

Comment (davesrocketshop) [reply src/Mod/Material/App/CMakeLists.txt:122]: This can cause issues when the src/Gui library references the Material library. The Material folder isn't in its search path and I was unable to find a way to force it. There may well be a better way to do it but I haven't found it.

Comment (marioalexis84) [reply src/Mod/Material/App/CMakeLists.txt:122]: The core system (src/Base, src/App, src/Gui) should not depend on application modules like Mod/Material https://forum.freecad.org/viewtopic.php?p=448980#p448980

Can you point out where this dependency occurs so we can think of another approach?

Comment (davesrocketshop) [reply src/Mod/Material/App/CMakeLists.txt:122]: App/Material.*
App/MaterialObject.*
App/MaterialPy.xml
App/MaterialPyImpl.cpp
Gui/DlgMaterialProperties.*

That's a start. I believe there are also some view providers and others that will also need to be addressed as well, and there may be more. Moving those out of App and Gui are possible but that would be significantly more disruptive.

Comment (marioalexis84) [reply src/Mod/Material/App/CMakeLists.txt:122]: I'm looking in those files and I can't find any dependency on /Mod/Material.
Can you show some line of code from src/Gui or src/App where Mod/Material is necessary?

Comment (marioalexis84) [reply src/Mod/Material/App/CMakeLists.txt:122]: I guess you are trying to extend the App::Material objects with the functionality provided by the Material application module.
If that is the goal, you can try creating  virtual functions in App::Material and then implement them in the Material module.
Note that the core system should not know anything about the implementations in the application modules or have a dependency on them.

Here some comments from wwmayer in a similar situation: https://forum.freecad.org/viewtopic.php?p=450724#p450724

Comment (marioalexis84) [reply src/Mod/Material/App/CMakeLists.txt:122]: @davesrocketshop I will create a pull request to revert the changes in CMakeLists.txt
