### PR TITLE
[Gui] fix the FPS text visibilty issues raised in #19371

### LINKED ISSUE #19371: [Gui] [3D Viewport] Multiple issues with visibility of the Frames Per Second / Response text display
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Problem description

I'm sure this has already been logged but couldn't find it. Here are examples of the visibility issues with the FPS/responsiveness text output in the 3D viewport:

Color doesn't change according to the background affecting light colored backgrounds
Image

Depending on the theme, when the overlay is enabled with the left dock in use the Property tabs obscure part of the text
Image

Image

### Full version info

```shell
OS: Linux Mint 22.1 (X-Cinnamon/cinnamon/xcb)
Architecture: x86_64
Version: 1.1.0dev.40041 (Git) Conda AppImage
Build type: Release
Branch: main
Hash: 64a4f6e3669279e5dbe9cb59d8e0123eaeb70833
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: English/United Kingdom (en_GB)
Stylesheet/Theme/QtStyle: Light-modern.qss/Light-modern/Fusion
Logical/physical DPI: 96/93.1131
Installed mods: 
  * FreeCAD-themes 2025.1.7
  * CfdOF 1.29.6
```

### Subproject(s) affected?

Core

### Anything else?

I'm working on a proposal and will publish shortly when I get all combinations of overlay and background colors determined.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Syres916**
Result of this fix can be seen in https://github.com/FreeCAD/FreeCAD/issues/19371#issuecomment-2629540185

Fixes #19371

### CODE REVIEW

**Comment by Syres916** [comment]
As the poor visibility applies to 1.0 could this please be backported.

File: src/Gui/View3DInventorViewer.cpp [hunk 1]
```diff
@@ -2444,7 +2444,32 @@ void View3DInventorViewer::renderScene()
...
+                         fColBlue);  // NOLINT
+        }
+        else {
+            draw2DString(stream.str().c_str(),
+                         SbVec2s(10, 10),
+                         SbVec2f(1.1F, 0.1F),
+                         fColRed,
+                         fColGreen,
+                         fColBlue);  // NOLINT
+        }
```
Comment (benj5378) [inline src/Gui/View3DInventorViewer.cpp:2472]:
```suggestion
        App::Color color(axisLetterColor);
        if (overlayLeftWidgets == "") {
            draw2DString(stream.str().c_str(),
                         SbVec2s(10, 10),
                         SbVec2f(0.1F, 0.1F),
                         color);  // NOLINT
        }
        else {
            draw2DString(stream.str().c_str(),
                         SbVec2s(10, 10),
                         SbVec2f(1.1F, 0.1F),
                         color);  // NOLINT
        }
```

**Review by benj5378 — CHANGES_REQUESTED** [review]
I think we can simplify the code greatly here :)

File: src/Gui/View3DInventorViewer.cpp (hunk 1 above)
Comment (xtemp09) [reply src/Gui/View3DInventorViewer.cpp:2472]: @benj5378, would it be better to condense the whole fragment into the following:


```ruby
draw2DString(stream.str().c_str(),
             SbVec2s(10, 10),
             SbVec2f( (overlayLeftWidgets == "" ? 0.1f : 1.1f), 0.1f),
             App::Color(axisLetterColor));  // NOLINT
```	 




?

Comment (benj5378) [reply src/Gui/View3DInventorViewer.cpp:2472]: @xtemp09 its surely shorter, though I don't find it more or less readable, I'm neutral.

**Comment by xtemp09** [comment]
@Syres916, sorry, I missed the second line. In my humble opinion comparing strings in the function argument is not the right way. Would be better to compare Booleans instead?


So, it will become like this:


```ruby
draw2DString(stream.str().c_str(),
             SbVec2s(10, 10),
             SbVec2f((overlayLeftWidgets ? 1.1f : 0.1f), 0.1f),
             App::Color(static_cast<uint32_t>(axisLetterColor)));  // NOLINT
```


At least, in this case a reader understands that presence or absence is considered, while comparing to "" can mean something else.

File: src/Gui/View3DInventorViewer.cpp (hunk 1 above)
Comment (benj5378) [reply src/Gui/View3DInventorViewer.cpp]: Then it should be

```cpp
double x = overlayLeftWidgets == "" ? 0.1f : 1.1f;
draw2DString(stream.str().c_str(),
             SbVec2s(10, 10),
             SbVec2f(x, 0.1f),
             App::Color(axisLetterColor));  // NOLINT
```

**Comment by benj5378** [comment]
Seems like we are just trolling now, but

```
double x = overlayLeftWidgets == "" ? 0.1f : 1.1f;
draw2DString(stream.str().c_str(),
             SbVec2s(10, 10),
             SbVec2f(x, 0.1f),
             App::Color(axisLetterColor));  // NOLINT
```

**Comment by maxwxyz** [comment]
@Syres916 ping for change requests

**Comment by Syres916** [comment]
@maxwxyz if a change doesn't compile on my system I'm not going to submit it, the PR works as designed and doesn't cause seg faults so I'm leaving as is.

**Comment by benj5378** [comment]
I haven't tested functionality, but code looks great from here.
