### PR TITLE
step exporting preserve body name when exporting to step file, fixes #24962

### LINKED ISSUE #24962: Core: Exporting to STEP does not preserve body names (Regression)
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Problem description

Exporting to step does not preserve body names. It appears that the name of the last operation in a body's model tree is replacing the body name in the step file.  I started noticing this with FC 20251022 and 20251031 but it may have happend earlier.

[STEP_EXPORT_PROBLEM-STEP_EPORT_PROBLEM.zip](https://github.com/user-attachments/files/23268486/STEP_EXPORT_PROBLEM-STEP_EPORT_PROBLEM.zip)

### Full version info

```shell
OS: Windows 11 build 22631
Architecture: x86_64
Version: 1.1.0dev.20251031 (Git shallow)
Build date: 2025/10/31 03:23:50
Build type: Release
Branch: main
Hash: c270a8ac666dff22a92baf2a3a4f5200197bb678
Python 3.11.14, Qt 6.8.3, Coin 4.0.3, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.3.0, IfcOpenShell 0.8.2, OCC 7.8.1
Locale: English/United States (en_US)
Navigation Style/Orbit Style/Rotation Mode: Gesture/Rounded Arcball/Window center
Stylesheet/Theme/QtStyle: FreeCAD.qss/FreeCAD Dark/
Logical DPI/Physical DPI/Pixel Ratio: 96/113.414/1.25
Installed mods: 
  * Cables 0.3.0
  * CurvedShapes 1.0.14
  * Curves 0.6.70
  * fasteners 0.5.43
  * lattice2 1.0.0
  * sheetmetal 0.7.58
```

### Subproject(s) affected?

None

### Anything else?

_No response_

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by ipatch**
this PR aims to fix the regression introduced when exporting a step file and preserving the colors of individual faces. unfortunately when that PR was merged the name of a body object was not, and when importing a step in freecad or another cad package / software that works with step files the body names were not preserved the object in question was named after the tip feature ie. **pad**. this PR aims to fix that issue.

### CODE REVIEW

**Comment by ipatch** [comment]
https://github.com/user-attachments/assets/bcc9bc49-0fcd-4b8b-9422-7faaf8640539

File: src/Mod/Import/App/ExportOCAF.cpp [hunk 1]
```diff
@@ -265,9 +271,9 @@ int ExportOCAF::saveShape(Part::Feature* part,
     TDF_Label shapeLabel = aShapeTool->NewShape();
     aShapeTool->SetShape(shapeLabel, baseShape);
 
+    const char* labelToUse = labelOverride ? labelOverride : part->Label.getValue();
```
Comment (chennes) [inline src/Mod/Import/App/ExportOCAF.cpp:279]: Presumably you meant to then use this variable in the next line, rather than using `part->Label.getValue()`?

**Review by chennes — CHANGES_REQUESTED** [review]

File: src/Mod/Import/App/ExportOCAF.cpp (hunk 1 above)
Comment (ipatch) [reply src/Mod/Import/App/ExportOCAF.cpp:279]: doh 🤦‍♂️

yup that's exactly what i was meaning to do. i just updated this PR and rebased it as well.

**Comment by chennes** [comment]
@ipatch the CI failure is just a typo... can you address?

**Comment by ipatch** [comment]
> @ipatch the CI failure is just a typo... can you address?

lulz yeah i see i put `lable` instead of `label` 🤦‍♂️ funny enough i'm in the middle of a bisect right now trying to track down another regression related issue. i'll be sure to fix this typo in a bit. maybe like an hour or two.

for future me,

```
Error: /home/runner/work/FreeCAD/FreeCAD/src/Mod/Import/App/ExportOCAF.cpp:275:63: error: use of undeclared identifier 'lableToUse'; did you mean 'labelToUse'?
  275 |     TDataStd_Name::Set(shapeLabel, TCollection_ExtendedString(lableToUse, true));
      |                                                               ^~~~~~~~~~
      |                                                               labelToUse
/home/runner/work/FreeCAD/FreeCAD/src/Mod/Import/App/ExportOCAF.cpp:274:17: note: 'labelToUse' declared here
  274 |     const char* labelToUse = labelOverride ? labelOverride : part->Label.getValue();
      |                 ^
1 error generated.
```

**Comment by kadet1090** [comment]
Hi! This PR has seemingly a lot of conflicts due to recent update to the code style. Unfortunately in case of that PR formatting changes are not the only conflicts so I couldn't update it automatically. Instruction on how to best deal with such massive automatic changes to the codebase is here: https://github.com/FreeCAD/FreeCAD/discussions/25217. 

While it would be awesome for you to do all the steps necessary, if you resolve only conflicts before changes that is fine too - I can take care of formatting changes. In case of any troubles, feel free to ping me here (or on any other platform) and I'll try to help.

**Comment by ipatch** [comment]
okay can't do this right now, as i just got home, and am about leave again. i'll try and update the formatting in the next day or two. 🤞 maybe tomorrow, before i go to work if i'm lucky.

**Comment by maxwxyz** [comment]
friendly reminder :)

**Comment by ipatch** [comment]
> friendly reminder :)

this PR should be good to go. i made those changes @kadet1090 mentioned the other day

**Comment by leoheck** [comment]
> recent update to the code style.

@kadet1090, which code style is FC using?
Is there any tool that does that automatically?

**Comment by chennes** [comment]
> which code style is FC using? Is there any tool that does that automatically?

Black (--line-length=100) for Python, and clang-format for C++ (see the .clang-format file at the top of the tree for details). Most developers should be using `pre-commit` [as described here](https://freecad.github.io/DevelopersHandbook/gettingstarted/#setting-up-for-development) to ensure their code is well-formatted prior to submission.

Regarding this PR -- I think it's good to go but I want to give it a quick run locally with ASAN on to ensure there are no strange lifetime issues with the pointers we're pushing around.

**Comment by axxel** [comment]
Question: would something similar also work for the 3mf export? All bodies end up being called "Object_1" in Bambu Studio.
