### PR TITLE
Toponaming: fix bug with points in sketches

### LINKED ISSUE #14234: When a Point object is in a sketch all Part Design feature tools fail, but Part workbench is fine.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

In the latest builds when a point is added to a sketch it is added, by default, as geometry not construction. In the past when a geometry point was in a sketch it was ignored and Pad/Pocket/etc would work. 
Now it produces the error: ` Pad: Shape must be a wire, edge or compound. Something else was supplied.`
Is is ignored in Part workbench. In both Part and Part Design it works as expected when a single point is in the sketch and used a one profile in a loft.
Screenshot_20240523_082512

[PointTests.FCStd.zip](https://github.com/FreeCAD/FreeCAD/files/15416797/PointTests.FCStd.zip)

### Full version info

```shell
OS: Debian GNU/Linux 12 (bookworm) (XFCE/xfce)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37462 (Git)
Build type: Release
Branch: main
Hash: d12635246f86947031776a42714028b236bd05ed
Python 3.11.2, Qt 5.15.8, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * MnesarcoUtils 0.2.5
  * lattice2 1.0.0
  * Curves 0.6.37
  * ArchTextures
  * Nodes 0.1.36
  * OpenTheme 2024.5.16
  * Help 1.0.3
  * QuickMeasure 2022.10.28
  * Manipulator 1.5.7
  * freecad.gears 1.2.0
  * sheetmetal 0.4.14
  * Silk 0.1.5
  * kicadStepUpMod 11.1.5
  * DynamicData 2.62.0
  * workfeature-macro
  * fasteners 0.5.21
  * Defeaturing 1.2.2
  * CurvedShapes 1.0.9
```

### Subproject(s) affected?

None

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by bgbsww**
Should fix #14234

### CODE REVIEW

**Comment by Syres916** [comment]
I tested the PR and it resolves another test file I have for Revolution with a redundant point.

File: src/Mod/PartDesign/Gui/Command.cpp [hunk 1]
```diff
@@ -664,6 +664,115 @@ unsigned validateSketches(std::vector<App::DocumentObject*>& sketches,
...
+ *  subobject when appropriate, we allow those sketches to be used as profiles without error.
+ *
+ * @param prop  The property ( generally a Profile link )
+ * @param _sobjs    Subobjects to use
+ * @param report    True if we should raise a dialog, otherwise raise and exception
+ * @return  True if elements were found
+ */
+bool importExternalElements(App::PropertyLinkSub& prop,
+                             std::vector<App::SubObjectT> _sobjs,
+                             bool report)
```
Comment (chennes) [inline src/Mod/PartDesign/Gui/Command.cpp:679]: Do we really need that "report" boolean? I'd just strip out the entire try block and let the exception propagate.

Comment (bgbsww) [reply src/Mod/PartDesign/Gui/Command.cpp:679]: Totally agree.  I stripped a lot, but wasn't positive on this one.  It'll be gone shortly.
