### PR TITLE
Gui: New transform dialog

### LINKED ISSUE #12451: [Problem] Transform tool is at object origin.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

This problem came a few time. When you transform an object, the handles are drawn at the origin of the object. This can be annoying in cases where the origin is far away from the solid itself. This often happen with imported step files.
The result looks like this (and can sometimes be much worse): 
image
One solution would be to draw the handles at the solid center of gravity.
But I was wondering if there was usecases where we actually want the handles to be drawn at the origin.

One thing that comes to mind is that if the handles are not at origin, then rotating does not correspond to changing the object rotation. But I don't know if there're actual usecases.

Another possible solution is to be able to reposition the origin of solids. This way if you have a solid coming from a step file with a ridiculous placement, you could reset it to something that makes sense.
Thoughts?

### Full version info

```shell
0.22
```

### Subproject(s) affected?

Core

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #13854: Transform: Ability to align dragger
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

As possible with the exploded assembly task it would be great to align / move the Std_Transform dragger to:
- origin of selected part(s) --> current default behavior
- part(s) center
- Align to... select features in the document (not limited to the current part selection)

Demo of alignment in assembly:

https://github.com/FreeCAD/FreeCAD/assets/6246609/7f8f1de2-ec76-4a81-aa58-8bb00f2cd452

Mockup of Std_Transform:
- Renamed "Increments" to transform
- Changed icon to Std_TransformManip
- Added Align to... button as in the assembly feature
image

@PaddleStroke 

### Full version info

```shell
OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37213 (Git)
Build type: Release
Branch: main
Hash: 20e7deb86a8c6c2cd2378f09f8313760933f3a5c
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: German/Germany (de_DE)
Installed mods: 
  * BIM 2021.12.0
  * CfdOF 1.25.11
  * Curves 0.6.36
  * dodo 1.0.1
  * fasteners 0.5.20
  * freecad.gears 1.2.0
  * OpenTheme 2024.5.3
  * OpticsWorkbench 1.0.17
  * sheetmetal 0.4.13
```

### Subproject(s) affected?

Core

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #18024: Model disappears on transform -> position becomes NaN -> seems related to python?
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I translate a simple group and it typically will work once, but if you stop and then attempt to translate in a second direction it will almost always cause the model to disappear. If you rotate the view every other model will also disappear. The position of the translated group becomes "nan m". The position cannot be manually changed due to a problem that seems to be related to python. Clicking fit-to-screen doesn't help, Undoing will typically make it reappear in recent versions. This has been present in every version of FreeCAD I've used, but it has gotten better in more recent versions, but clearly it's still happening.

After attempting to change the position the following error displays in the message area. This is the only error that is ever displayed:

pyException: Traceback (most recent call last):
  File "<"string">", line 1, in <"module">
<class 'NameError'>: name 'nan' is not defined
*I had to add some extra "s here to make the string and module part show up. Looks like BBCode or LaTeX or something is removing it from the html.

The attached video files: The first shows the model disappearing, then towards the end the program hangs. I stopped the video recording. Then later it began responding again so I started another recording and show the "nan m" positions and the error message and finally undoing to get the models back.

(I recoded the videos and they worked for a while, now they've been removed for some reason. I'll resend the videos in a comment below. If that comment disappears, I'll take the hint and not reupload them.)

This is a work file, so I can upload privately, but do not want to post it publicly. Any sufficiently complex parts added to a simple group should show the same behavior I would assume.

### Full version info

```shell
OS: Windows 10 build 19045
Architecture: x86_64
Version: 1.0.0.39109 (Git) Conda
Build type: Release
Branch: (HEAD detached at 1.0.0)
Hash: 2fcc5317fe3aee96ca73475986a577719fc78e20
Python 3.11.10, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: English/United States (en_US) [ OS: Japanese/Japan (ja_JP) ]
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Classic/Qt default
Installed mods: 
  * Curves 0.6.47
  * fasteners 0.5.28
```

### Subproject(s) affected?

PartDesign

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #18421: Transform selection in 3D view does not actually transform the body/part
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When working in PartDesign, selecting an element in the 3D view always selects the last feature of a body (relates issues: https://github.com/FreeCAD/FreeCAD/issues/11132, https://github.com/FreeCAD/FreeCAD/issues/16164).

The transform tool (Std_TransformManip) is greyed out in the context menu of the tree view when a feature is selected (only visible when the body is selected) but is still available from the 3D view and the menu.

So usually a user selects an element in the 3D view, right clicks and chooses transform. The transform dialog is opened and the user can perform the transform which is also shown to the user in the 3D view. When clicking OK, the transform is not applied.

Demo (the origin of the body is not moving):

https://github.com/user-attachments/assets/b623e16b-359b-4949-a033-0b78a1ddc0fb

Ideally, when the transform tool is active, it should affect the first parent object which can be transformed (as if I had selected the body), but not the object at root level (as this would be wrong for nested parts).

@kadet1090 FYI

### Full version info

```shell
OS: macOS 13.7.1
Architecture: x86_64
Version: 1.1.0dev.38388 +1145 (Git) Conda
Build type: Release
Branch: pr/kadet1090/17564
Hash: 6253f6c8b8d8ef0bab9f136768fde7a1d09493a4
Python 3.11.8, Qt 5.15.8, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Dark/Fusion
Installed mods: 
  * freecad.gears 1.2.0
  * OpenTheme 2024.8.17
  * CfdOF 1.27.5
  * Defeaturing 1.2.2
  * Manipulator 1.5.7
  * fasteners 0.5.27
  * CurvedShapes 1.0.9
  * sheetmetal 0.4.24
  * Curves 0.6.45
```

### Subproject(s) affected?

Core

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by kadet1090**
This refactors `ViewProviderDragger` and `TaskCSysDragger` to be more modern and to support selecting Transform Origin. It adds ability to snap transform origin, enter exact coordinates, snap one object to another

> [!CAUTION] 
> **Breaking Changes** 
>
> This removes support for `UseCenterballDragger` from Link view provider. this was obscure feature that was in core basically only because Assembly 3 used it. Keeping it would drastically complicate code and provide yet another place in code where something behaves differently.
>
> As far as I understand, it can be reimplemented inside assembly 3 as addons can create custom nodes and affect the placement from Python. 

**Further work**
- Add preview of moved object - will be done as part of https://github.com/FreeCAD/FPA-grant-proposals/issues/22
- Add preview of transformation path - same as above
- Add more coordinate systems (like Part, Assembly etc)
- Add ability to move multiple objects (requires changes to edit modes)

image

https://github.com/user-attachments/assets/c79ca028-616e-4c50-a8a1-c32d57e9c2d7

Fixes #18421
Fixes #13854 
Fixes #12451
Probably fixes #18024

### CODE REVIEW

**Comment by maxwxyz** [comment]
@PaddleStroke @FreeCAD/design-working-group @FreeCAD/cad-advisory-group

**Comment by pierreporte** [comment]
It’s starting great.

For local nudge, I think that there should be a button for each line because applying the whole vector may be unwanted. Users sometimes set increments in the 3 directions but apply them along only one. It could also be a pair of buttons for positive and negative directions.

Don’t know if it’s a detail but I think U/V/W could be displayed in the 3D view or with some sort of color code to indicate what they are because it’s not necessary obvious. We all know it because we’ve discussed about it on Discord, but users who will discover the feature may need some time to figure it out.

**Comment by kadet1090** [comment]
> Don’t know if it’s a detail but I think U/V/W could be displayed in the 3D view or with some sort of color code to indicate what they are because it’s not necessary obvious. We all know it because we’ve discussed about it on Discord, but users who will discover the feature may need some time to figure it out.

Good idea, I also plan to display labels on 3D view, as without it it is pretty hard to understand what UVW coordinate space is

**Comment by pierreporte** [comment]
In the video, when you switch translate to global placement, the selected origin stays in place. It can make sense because rotation is still in the selected origin, but now the user is unable to drag the part along global axis. It can even mislead users that the global origin is the selected origin. It doesn’t help that there are no labels. I can think of a two solutions:

1. Move the combo box in the first section, allowing to select an origin only if global placement is not selected (btw let’s rename “nudge” to “selected coordinate system”). The origin then moves to the selection or to the global origin
2. Always display the manipulator at the global origin so that users can drag both (but they would need to use the combo box for precise movements).

My favorite is the first one.

**Comment by maxwxyz** [comment]
So great!
Cannot built on Windows as discussed earlier today. So based on the concept will the PR also implement the following or should I create new issues for each:
- [ ] Align dragger to object (selection) origin (= reset dragger position)
- [ ] Align dragger to global origin (maybe when switching to global placement mode)
- [ ] Align dragger to other objects in the document / snap to other object's elements (face, edge, point) or LCS
- [ ] Align/snap to edges, points, midpoints like the exploded view tool in assembly
- [ ] Align dragger to center of mass of selection

"Local nudge" should be "Transform origin" or "Local coordinates".
Global placement should display the dragger at the object's origin (placement value) as only then it would make sense to drag it around in the right coordinate system as the tool works today incl. the snapping increments.
As @pierreporte mentioned you can end up with translate in global and rotate in local coordinate system, which would conflict the dragger position. Could we either have a global dropdown under the align dragger menu or maybe have two different draggers, one for rotation commands only, one for translation (although UX would be not intuitive). Adding axis names would be beneficial (x,y,z or u,v,w depending on local/global selection, maybe another point for setting it for the entire dialog not independent for translate/rotate).
For the align button it could also be done with a dropdown as the exploded view tool in Assembly, choosing COM, origin, or the interactive snap mode. A preview like in the exploded view tool where the dragger would end up before you left click would be great.

Will test and report when building this PR with Conda on Windows is possible.

**Comment by WandererFan** [comment]
Might want to check your branch's starting point.  The are template changes that don't seem to have anything to do with transform.

**Comment by kadet1090** [comment]
> Might want to check your branch's starting point. The are template changes that don't seem to have anything to do with transform.

Starting point is ok. I cherrypicked first commit from https://github.com/FreeCAD/FreeCAD/pull/17528 because I depend on it. Once it is merged this commit will be gone, and if it is not merged I'll rework it to not depend.

**Comment by maxwxyz** [comment]
Nice. I don't understand the last point: If you want to position it in the global coordinates, why is it not easier to have the dragger aligned to the global coordinates but instead have it at an arbitrary rotation? You could manually snap it to the objects origin, but there is absolutely no way to snap to the global origin, maybe something like this is needed?

**Comment by kadet1090** [comment]
@wwmayer can you take a look at https://github.com/FreeCAD/FreeCAD/pull/17564/commits/d19b84d7c710116c686acb3902b3bc991261eb37? I had to change Attacher to use `TopoShape` instead of `TopoDS_Shape`, it works, passes tests etc but this is not a part that I am familiar with so would be nice for someone more knowledgeable to check.

**Comment by PaddleStroke** [comment]
As a note, my current core datum PR is touching attacher quite a lot.
If perhaps you could base your pr on top of my pr we could avoid conflicts :)

**Comment by kadet1090** [comment]
As far as I see we don't have much conflicting code. I prefer to keep the base as close to main as possible so I could quickly rebase on top of it without having to deal with not my commits or wait for you to rebase your branch. I however don't mind solving conflicts once your PR is merged - Attacher changes are separated into commits so it should be non-issue.

**Comment by PaddleStroke** [comment]
Great!

File: src/App/ComplexGeoData.cpp [hunk 1]
```diff
@@ -184,6 +184,17 @@ bool ComplexGeoData::getCenterOfGravity(Base::Vector3d& unused) const
     return false;
 }
 
+std::optional<Base::Vector3d> ComplexGeoData::centerOfGravity() const
```
Comment (wwmayer) [inline src/App/ComplexGeoData.cpp:187]: Why adding another method to get the COG? Then just change the existing one to use std::optional.

File: src/Gui/CMakeLists.txt [hunk 2]
```diff
@@ -52,10 +52,12 @@ include_directories(
     ${EIGEN3_INCLUDE_DIR}
     ${COIN3D_INCLUDE_DIRS}
     ${PYTHON_INCLUDE_DIRS}
+    ${OCC_INCLUDE_DIR}
```
Comment (wwmayer) [inline src/Gui/CMakeLists.txt:55]: Please DO NOT any OCC stuff to the core system!

File: src/Gui/CMakeLists.txt [hunk 3]
```diff
@@ -66,6 +68,7 @@ endif(MSVC)
 if(MSVC)
     set(FreeCADGui_LIBS
          FreeCADApp
+         Part
```
Comment (wwmayer) [inline src/Gui/CMakeLists.txt:71]: Adding extension modules to the core system is a no go. This breaks the architecture!

File: src/Gui/SelectionObject.h [hunk 4]
```diff
@@ -72,8 +72,10 @@ class GuiExport SelectionObject : public Base::BaseClass
 
     /// returns the selected DocumentObject or NULL if the object is already deleted
     const App::DocumentObject *getObject() const;
-    /// returns the selected DocumentObject or NULL if the object is already deleted
+    /// returns the selected DocumentObject as specified type or NULL if the object is already deleted
     App::DocumentObject *getObject();
+    template <class T>
+    T* getObject() { return Base::freecad_dynamic_cast<T>(getObject()); }
```
Comment (wwmayer) [inline src/Gui/SelectionObject.h:78]: For the sake of consistency there should also be a:
`template <class T> const T* getObject() const { return Base::freecad_dynamic_cast<T>(getObject()); }`

File: src/Gui/CMakeLists.txt (hunk 3 above)
Comment (PaddleStroke) [reply src/Gui/CMakeLists.txt:71]: He mentioned in the description that this is temporary.

File: src/Gui/Utilities.h [hunk 5]
```diff
@@ -104,6 +104,17 @@ struct vec_traits<App::Color> {
 private:
     const vec_type& v;
 };
+
+template <>
+inline SbMatrix convertTo<SbMatrix, Base::Matrix4D>(const Base::Matrix4D& vec2)
```
Comment (wwmayer) [inline src/Gui/Utilities.h:109]: A bit nit-picking but a matrix shouldn't be called vec2.
And for consistency reasons a converter from SbMatrix to Base::Matrix4D should be available, too.

Comment (kadet1090) [reply src/Gui/Utilities.h:109]: Yeah, I don't like the `vec2` too but linter complains if the template specialization uses different name :/ I'll provide other side of conversion.

File: src/Gui/CMakeLists.txt (hunk 2 above)
Comment (kadet1090) [reply src/Gui/CMakeLists.txt:55]: It is semi mentioned in the PR description:
> For now it adds dependency on Part to the Gui module but it will be removed later when I figure out how to do it properly.

If you have any suggestion on how to skip that dependency it would be nice. I don't see any good way of providing the ability to support choosing the transform origin without relying on Part. My current plan is to simply utilize newly created `getTransformDialog` method and override it when Part is available, but maybe there is a better way.

File: src/Gui/SelectionObject.h (hunk 4 above)
Comment (kadet1090) [reply src/Gui/SelectionObject.h:78]: I'll do that in https://github.com/FreeCAD/FreeCAD/pull/17528

File: src/Gui/ViewProviderLink.cpp [hunk 6]
```diff
@@ -2893,7 +2893,7 @@ void ViewProviderLink::setEditViewer(Gui::View3DInventorViewer* viewer, int ModN
             dragger->setUpAutoScale(viewer->getSoRenderManager()->getCamera());
             viewer->setupEditingRoot(pcDragger,&dragCtx->preTransform);
 
-            auto task = new TaskCSysDragger(this, dragger);
+            auto task = new TaskCSysDragger(nullptr, dragger);
```
Comment (wwmayer) [inline src/Gui/ViewProviderLink.cpp:2896]: This will cause a segmentation fault. The constructor of TaskCSysDragger forwards its first argument to TaskTransform and this constructor will access it without checking for null.

Comment (kadet1090) [reply src/Gui/ViewProviderLink.cpp:2896]: Yes, this is temporary until I refactor `ViewProviderLink`.

File: src/Gui/CMakeLists.txt (hunk 2 above)
Comment (wwmayer) [reply src/Gui/CMakeLists.txt:55]: It's a virtual method in ViewProviderDragger and you can override it for the view providers from PartGui.

File: src/Gui/Utilities.h (hunk 5 above)
Comment (wwmayer) [reply src/Gui/Utilities.h:109]: Oh, OK. Then leave it.

**Comment by wwmayer** [comment]
> can you take a look at https://github.com/FreeCAD/FreeCAD/commit/d19b84d7c710116c686acb3902b3bc991261eb37? I had to change Attacher to use TopoShape instead of TopoDS_Shape, it works, passes tests etc but this is not a part that I am familiar with so would be nice for someone more knowledgeable to check.

Where exactly did you need it in the code to have a TopoShape instead of TopoDS_Shape? I must have missed the exact location.

Nevertheless, using a TopoShape is fine because it doesn't make a deep copy of any geometry but only adds a little cost in incrementing and decrementing the ref. counter of the underlying TopoDS_TShape.

File: src/Gui/CMakeLists.txt (hunk 3 above)
Comment (wwmayer) [reply src/Gui/CMakeLists.txt:71]: Yeah, I have seen it now, too.

**Comment by kadet1090** [comment]
> Where exactly did you need it in the code to have a TopoShape instead of TopoDS_Shape? I must have missed the exact location

It is hard to spot indeed. Basically I need center of gravity which is defined only in TopoShape and I use it here: https://github.com/FreeCAD/FreeCAD/pull/17564/files#diff-39390d1d67bdf8c90422df5552474c42d127d8747cda9343a457c1a73bb30d4aR1972 I could probably extract it in some other way but using TopoShape seemed like a good refactor anyway.

**Comment by PaddleStroke** [comment]
@kadet1090 will this PR remove the need of edit mode of the transform tool?

**Comment by kadet1090** [comment]
> will this PR remove the need of edit mode of the transform tool?

No, too big of change for this PR. I'd like however to lay some ground for this. 

I have idea of `Editor` concept that could be used in there. Basically `Editor`s should be used to encapsulate all UI related stuff and connect Qt, Coin and Features together. Basically extract the editing responsibility from VP. 

I imagine that `Editor` would consist of at least one `SoSeparator` that would contain all Coin nodes necessary for the editor, reference to the dialog and edited thing(s). That would allow us to move editing related things from ViewProviders into dedicated classes so they are not polluted with draggers and other edit only stuff. This should also allow us to make editors more independent - there is no reason to tie placement modification into any particular VP. As long as we have something that can accept the coin separator of editor so it can be displayed and provide it with all necessary stuff (like references to edited properties) we should be fine. We should be able to even attach editors directly to the VP of document if no better choice.

Not yet fully ready to push that further, but if you want some brainstorming we can do that via discord. I'll draw some initial PoC for this once this is ready enough:tm:.

**Comment by kadet1090** [comment]
A bit of update on the feature. It is almost fully feature complete. Missing bits are:

- [ ] Ability to align to other features
- [ ] Ability to bind expressions if transform is at origin
- [ ] Removing the part dependency in the core

Of course it still needs few rounds of polish and refinement but it quite close to finish.

https://github.com/user-attachments/assets/9dbd9b3b-c348-425f-aadf-2014b701348f


https://github.com/user-attachments/assets/21789329-6a56-4e01-bd5a-4a4621a4f8be

**Comment by pierreporte** [comment]
The only two things I would change are:

* Snapping deltas on each line instead of at the top, or at the very least the translation one above the 3 translation fields, and the rotation ones above the 3 rotation fields. We can imagine a checkbox so that they all keep the same value.
* I would make placement drop-down list as two buttons or a set of radio-buttons.

The first point is the most important IMO. Maybe the @FreeCAD/design-working-group can propose something.

**Comment by kadet1090** [comment]
> Snapping deltas on each line instead of at the top, or at the very least the translation one above the 3 translation fields, and the rotation ones above the 3 rotation fields. We can imagine a checkbox so that they all keep the same value.

Snapping affects only dragger, not the inputs below that is why it was moved to the dragger section. I'm open to change that but personally I feel that current solution is more intuitive. 

> * I would make placement drop-down list as two buttons or a set of radio-buttons.

I'm not keen on radio-buttons there as in current state it can have arbitrary number of entries. I'll however reduce the history to potentially only one, but even there it has potential to grow (we may list here LCSes for example) - radio buttons are not great for this usecase IMO. 

Playing with it I think that best solution would be here to have combo box with 3 entries: `Origin`, `Center of mass / centroid`, `Custom (<feature name>)` which will be available after first feature is selected. I'm also not happy with "Pick another one..." option, standalone "Pick feature" button directly under the combo box seems better.

**Comment by pierreporte** [comment]
> > Snapping deltas on each line instead of at the top, or at the very least the translation one above the 3 translation fields, and the rotation ones above the 3 rotation fields. We can imagine a checkbox so that they all keep the same value.
>
> Snapping affects only dragger, not the inputs below that is why it was moved to the dragger section. I'm open to change that but personally I feel that current solution is more intuitive.

I didn’t know that. I was expecting something like Catia where the dragger follows the steps defined near the spinboxes.

**Comment by kaiwas** [comment]
All this looks great. But sometimes it is completely unclear by what amount the movement/rotation was performed.
At least it is unclear in local mode.

**Comment by pierreporte** [comment]
@kaiwas It is true. Catia displays the information in the 3D view by drawing a line from the starting point to the current position of the manipulator and displaying the value on it. This solution would need to solve #13116 first.

**Comment by kadet1090** [comment]
@kaiwas @pierreporte is this better in your opinion?


https://github.com/user-attachments/assets/80f2abaa-ffe2-4db5-8aa6-0e794dc77536

https://github.com/user-attachments/assets/dd161ff3-3859-423d-9c66-4ce9e7cb0682

**Comment by pierreporte** [comment]
Looks good. You really have to use it to evaluate UX though.

Is it possible to display axis names on the dragger, or use colors in the panels for better understanding?

**Comment by kadet1090** [comment]
> Is it possible to display axis names on the dragger, or use colors in the panels for better understanding?

Yes I plan to add labels as next step. Not sure about colors as I don't know how to achieve that with Qt. This was my plan how that could look like:
image-4

**Comment by kaiwas** [comment]
> is this better in your opinion?

in my opinion YES

**Comment by kadet1090** [comment]
> You can simply color the axis titles and values ​​in the desired color (not the underline).

That will cause problems with readability and contrast - I'd love to avoid that.

**Comment by kaiwas** [comment]
> That will cause problems with readability and contrast - I'd love to avoid that.

Yes, I agree.
Maybe some colored frame around the axis designation letter. Or maybe underlining the letter.

But underlining the whole field looks a bit strange.

**Comment by tarman3** [comment]
Maybe bold color letters X Y Z

**Comment by kadet1090** [comment]
At this stage I consider this PR mostly complete - it still has some minor issues that I am aware of and needs a bit of code cleanup but is mostly ready to test and review.


https://github.com/user-attachments/assets/c1605699-98dc-4400-9ef2-84bdc4f5016a

File: src/Base/Rotation.h [hunk 7]
```diff
@@ -112,6 +92,33 @@ class BaseExport Rotation
 
         EulerSequenceLast,
     };
+
+    /// Utility function to create Rotation based on direction / normal vector
+    static Rotation fromNormalVector(const Vector3d& normal);
```
Comment (hyarion) [inline src/Base/Rotation.h:97]: This function defines the normal vector to be Z globally. I would prefer if Rotation doesn’t do assumptions like this.

Would it be an option to create a const normalVector{0, 0, 0} in Attacher.cpp, that can be used in the two places instead of the new function?

File: src/Gui/TaskCSysDragger.cpp [hunk 8]
```diff
@@ -39,139 +47,586 @@
...
+
+void TaskTransform::updateTransformOrigin()
+{
+    auto getTransformOrigin = [this](const PlacementMode& mode) -> Base::Placement {
+        switch (mode) {
+            case PlacementMode::ObjectOrigin:
+                return {};
+            case PlacementMode::Centroid:
+                if (const auto com = centerOfMassProvider->ofDocumentObject(vp->getObject())) {
+                    return Base::Placement { *com, {} };
```
Comment (hyarion) [inline src/Gui/TaskCSysDragger.cpp:506]: I don’t think you need to write `Base::Placement` here as you already defined the return type of the lambda
```suggestion
                    return { *com, {} };
```

File: src/Base/Rotation.h (hunk 7 above)
Comment (kadet1090) [reply src/Base/Rotation.h:97]: I'd argue that this is assumption that should be made globally. If we are dealing with normal vectors they should be always represented by one axis vector in the whole application. I don't see a good reason why it should not be global and I see problems that can happen when one part of application assumes Z to be the normal vector and another assumes let's say Y.

**Comment by PaddleStroke** [comment]
I've not checked it yet, just a small question : this PR looks like it is using the same LCS positioning based on mouse position on the object? Did you took the code out of assembly for this or did you reimplement it in cpp?

**Comment by kadet1090** [comment]
> I've not checked it yet, just a small question : this PR looks like it is using the same LCS positioning based on mouse position on the object? Did you took the code out of assembly for this or did you reimplement it in cpp?

Yeah it is your code rewritten as attachment mode - I've skipped some parts that were not needed and which I didn't really understand. If you have time to explain to me some stuff over discord I'll make PR to assembly to use C++ solution so that code is not duplicated.

**Comment by maxwxyz** [comment]
I'm posting each finding as separate comment so we can mark (hide) them as resolved.
Here is the file I've used for testing: 
[transform.FCStd.zip](https://github.com/user-attachments/files/18084487/transform.FCStd.zip)

**Comment by maxwxyz** [comment]
It is currently not possible to select the origin or LCS as dragger location.
I can only select axes and if I do so, the direction is flipped (+Z axis is -Z on the dragger)
grafik

**Comment by maxwxyz** [comment]
Dragger attachment and move to target object is not working correctly for nested parts. It works for one level of nesting but everything more breaks it. 
The attachment needs to consider all/infinite levels of nesting (so up to root / where it is displayed)

https://github.com/user-attachments/assets/9eb36d2a-e4fe-4d8b-b886-0c667dd2587f

**Comment by maxwxyz** [comment]
Not from this PR but general UI issue: Sometimes it looks like the transform is cancelled when clicking OK.
That is the case when trying to transform the part design feature instead of the body.
Steps to reproduce:

1. select a PD feature in the tree (e.g. latest).
2. If you right click in the tree, there is no transform command
3. if you right click in the 3D view you can choose transform.
4. you see the movement of the part (actually last feature), the origin of that part does not move

(the new visuals for the LCS makes it easy to spot)

https://github.com/user-attachments/assets/38b58ee6-1610-42d0-8a73-b56f57452fcb

**Comment by maxwxyz** [comment]
So about the display of the input values for translation and transform I'd like feedback from @FreeCAD/design-working-group // @FreeCAD/cad-advisory-group as also Kacper mentioned in the PR

> For local mode rotation always reads 0 as rotation of dragger which define UVW is always 0, it can be however applied via UI.
For the same reason when rotating object UVW space changes base vectors and so UVW coordinates change.


Originally, the inputs were not "live" in that regard that you see the feedback when dragging in the 3D view or when scrolling in the spinbox. You've had to hit "apply" first to apply the movement or rotation in the orientation of the **current** dragger in the 3D view. So the current dragger was always 0,0,0 when in local mode and the values were the delta to that. We've called this mode 'local nudge'.

@kaiwas mentioned [here](https://github.com/FreeCAD/FreeCAD/pull/17564#issuecomment-2499001979) that this behavior is unintuitive as it might be unclear what transformation was done.

Implementation was changed so the translate values in local mode now show the delta of the first dragger position to the current dragger location. Rotation works still in the other mode, where dragging  the dragger always sets the rotational values to 0.
The problem is now UI wise, when I move my part and then rotate it, all the rotation values stay 0 and all the translation values change, which I find more confusing.  
You can see a demo in the following video where rotating it by dragging, it does not change the values in the task dialog. When I move it and then rotate it, all translate values change but no rotation:

https://github.com/user-attachments/assets/b3119c4a-293f-4c4d-8640-43d01675b72e

You can see the behavior again in the following video, where I attach the dragger to the shaft, move the shaft to the circle and then rotate it around the circle axis. The values for translation of the part change but not rotation. When I input rotation values and then drag it in the 3D view, the inputs are zero again. So it is a mixed UX behavior between rotation and translation. 
A user can workaround this but I am not sure if this is the ideal behavior. 
I propose these changes:
1. reset translation and rotation values in the task dialog each time the dragger is (re)attached or the part is moved with the 'Move to other object command'
2. add a checkbox or button to toggle between the "live" behavior (=delta transform to the first transform origin) and the "local nudge" (=dragger position is always transform origin (0,0,0)) which need the old apply button. Then have both, translation and rotation, behave the same according to the mode (delta to first dragger position - as translate is now; and delta to current dragger - as rotation is now.

As seen here, CATIA displays both modes at the same time and does not mix them between translation and rotation: https://github.com/FreeCAD/FreeCAD/pull/17564#issuecomment-2499705181

https://github.com/user-attachments/assets/2cc3195f-aaa1-4dbe-970c-40c971c7285e

@kadet1090 at the end and in the middle you can spot a bug: Move the part; input rotational values in the task dialog, then input/change translation values above ==> the part jumps to a different location

@obelisk79 @pierreporte @PaddleStroke @FEA-eng what is your opinion? If you can build it please also test it and play around with nested and weirdly oriented parts. The new datums make it easy to see the orientation :)

**Comment by maxwxyz** [comment]
Here is the bug where changing (in the task dialog spin boxes) the rotation values of a transformed part and then changing the translation the part jumps to a new location. Entering the same value as before in the translate spinbox still leaves the part at a different location:

https://github.com/user-attachments/assets/45607307-b379-4daf-979f-6d93c9a89ffa

**Comment by maxwxyz** [comment]
I cannot enter a unit in the snapping increments spinboxes.
It does not let me type the characters `m` or `t`right after the number or after a space. I can type these characters after entering other characters, like `u`
Bildschirmfoto 2024-12-10 um 21 01 13

**Comment by maxwxyz** [comment]
In global mode (=object placement values), the rotation is reset when checking `align dragger rotation with selected coordinate system`.
Expected behavior: the absolute rotational values are shown in the dialog (as with the translation values):

https://github.com/user-attachments/assets/4e46b0ab-b610-4d0a-86ca-0d2b1b931247

**Comment by kadet1090** [comment]
>Dragger attachment and move to target object is not working correctly for nested parts. It works for one level of nesting but everything more breaks it.

Fixed for non-links.

> I cannot enter a unit in the snapping increments spinboxes.

Fixed.

> Here is the bug where changing (in the task dialog spin boxes) the rotation values of a transformed part and then changing the translation the part jumps to a new location. Entering the same value as before in the translate spinbox still leaves the part at a different location:

This is highly related to the problem with changing rotation of coordinate system. The rotation in local mode does not work generally to well. Honestly I'm currently inclined to change rotation in local mode to be more nudge like. While there is a logical readout for the position, which is quite useful (it gives feedback, shows how much object moved in total etc) for rotation it only causes problems.

IMHO the best solution would be to change rotation in local mode to look like it currently looks, but every spinbox should zero out when the axis changes (so for example, if you rotate around Z axis, X and Y will change so they should 0 out, if you move object - all should zero out). When you rotate around X axis it would correctly display how much you rotated.

Similar behavior can be implemented for translation, but I'd zero out the coordinates when rotation changes at all. I'm not sure here however as this number is valid, simply coordinate system changes so it looks strange.

**Comment by PaddleStroke** [comment]
Note that the core datums card4 PR is doing the migration changing the base placement of the Axis. The planes should stay unchanged.

**Comment by maxwxyz** [comment]
@kadet1090 not sure if possible but would be great if you can snap the dragger to Draft Working Planes. I could imagine this to be helpful to position and slide along a working plane, maybe for furniture in BIM? There are special transform and snapping tools in Draft/BIM though.

Selecting an arc as reference seems to align the dragger at the center of the edge but in an interesting orientation:
Bildschirmfoto 2024-12-13 um 13 07 38
Not sure if snapping to center (like on full circles) would be better  though.

**Comment by pierreporte** [comment]
It’s hard to fully grasp how the feature works and feels without building. Hopefully it will be easier in the future.

@maxwxyz 

> 1. reset translation and rotation values in the task dialog each time the dragger is (re)attached or the part is moved with the 'Move to other object command'
> 2. add a checkbox or button to toggle between the "live" behavior (=delta transform to the first transform origin) and the "local nudge" (=dragger position is always transform origin (0,0,0)) which need the old apply button. Then have both, translation and rotation, behave the same according to the mode (delta to first dragger position - as translate is now; and delta to current dragger - as rotation is now.

Seems sensible to me. My perception have been influenced by Catia so I would expect that UVW values are the delta from when the dragger was attached. A reset button could be useful as well, when you move things around, then at some point you want to use that position as reference for the next step. Not quite the same as nudge. I was always a proponent to having separate steps and apply buttons.

@kadet1090 It seems that the movements are always stepped. Is there a way to move objects without this restrictions? If it needs setting the step to zero, then I think it would be better to provide a modifier key or a button to bypass that so that the initial step value isn’t lost.

**Comment by FEA-eng** [comment]
Tested, works well. It’s a really large improvement for this important tool. I’m just not sure if increments should be renamed to snapping but it’s just a minor detail.

**Comment by maxwxyz** [comment]
@kadet1090 heads up for conflicts.
Do you plan on changing the UX behavior or is there already a change in a recent push?
Shall I create new issues for the bits which could be added later (full port from assembly edge line end/start points; snap dragger to Draft WP,...).
@obelisk79 you've mentioned that you wanted to give this PR a look too, any feedback?

**Comment by kadet1090** [comment]
> Do you plan on changing the UX behavior or is there already a change in a recent push?
I'll update it probably today.

> Shall I create new issues for the bits which could be added later (full port from assembly edge line end/start points; snap dragger to Draft WP,...).
Let's wait with that for the PR that is 100% done i.e. with changes to UX.

**Comment by kadet1090** [comment]
Ok, so I updated the behavior to something that should be a bit more logical:

https://github.com/user-attachments/assets/0a3414f4-088e-4dea-b836-a9e0dfbed0e0

**Comment by pierreporte** [comment]
Looks good to me. I just think that, when you select a custom origin, the values are reset to zero automatically and not when you start moving. Also, can you do something about the minus sign randomly appearing?

**Comment by kadet1090** [comment]
> I just think that, when you select a custom origin, the values are reset to zero automatically and not when you start moving.

Nice catch! Fixed.

> Also, can you do something about the minus sign randomly appearing?

Also fixed.


https://github.com/user-attachments/assets/8ba4a2f9-202c-4dec-a6f8-415df62bc42f

**Comment by pierreporte** [comment]
Perfect! It’s a solid foundation now.

There was this comment I made:

> It seems that the movements are always stepped. Is there a way to move objects without this restrictions? If it needs setting the step to zero, then I think it would be better to provide a modifier key or a button to bypass that so that the initial step value isn’t lost.

In Microsoft Office you need to press <kbd>Alt</kbd> key to bypass the steps. Is there a similar mechanism with your feature? If not I’ll wait for this PR to be merged to open an issue.

**Comment by kadet1090** [comment]
For now it would not be possible in order to achieve accuracy movement is calculated by multiplying integer steps by the increment. It is not possible to change while dragging. Probably can be reworked a bit to achieve it but I don't want to fight with this right now - so yes, that would be a good issue to open.

**Comment by maxwxyz** [comment]
@kadet1090 looks good. Will it reset values now on each re-attachment of the dragger (translation & rotation U,V,W in local mode only) and when using the move to target tool?
I will build and test tomorrow.

**Comment by maxwxyz** [comment]
new behavior of the task dialog is good.
There is an new issue with the dragger location when using the `Move to other object` command and cancelling this command is also not possible. Clicking on cancel does not do anything.

https://github.com/user-attachments/assets/b8e49fb9-3583-4c79-ba75-179472a07e1f

**Comment by maxwxyz** [comment]
Another new issues: in absolute (global) mode, it does not use document absolute values but the ones of the selected object's origin. Use case: center part at dragger location to global 0,0,0
Bildschirmfoto 2024-12-16 um 12 45 11

**Comment by maxwxyz** [comment]
Attaching the dragger on the Schenkel.stp example file results in some weird placements:

https://github.com/user-attachments/assets/7e867933-9226-422a-a4f2-c312d4eed3b0

**Comment by maxwxyz** [comment]
Crash on macOS:
1. Attach the dragger to custom location
2. Cancel the tool
3. Crash without warning

https://github.com/user-attachments/assets/ede254f4-45bb-472e-ade0-d7e3be07b25b

<details><summary>About info</summary>
<p>

```
OS: macOS Ventura (13.7)
Architecture: x86_64
Version: 1.1.0dev.39586 +77 (Git) Conda
Build type: Release
Branch: pr/kadet1090/17564
Hash: e6b3f7de9609d60ad2b6b4af8fdc50d1f794d99d
Python 3.12.0, Qt 6.7.3, Coin 4.0.3, Vtk 9.3.1, OCC 7.8.1
Locale: German/Germany (de_DE)
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Dark/
Installed mods: 
  * freecad.gears 1.2.0
  * OpenTheme 2024.8.17
  * CfdOF 1.27.5
  * Defeaturing 1.2.2
  * Manipulator 1.5.7
  * fasteners 0.5.27
  * CurvedShapes 1.0.9
  * sheetmetal 0.4.24
  * Curves 0.6.45

``` 


</p>
</details>

**Comment by maxwxyz** [comment]
Crash on Windows and error when launching the transform tool:
1. Launch transform tool: Error
grafik
2. Launch transform tool again: Crash
```
07:25:57  Illegal storage access...
07:25:57  <Gui> Document.cpp(574): Illegal storage access! Please save your work under a new file name and restart the application!
``` 


<details><summary>About info</summary>
<p>

```
OS: Windows 11 build 26100
Architecture: x86_64
Version: 1.1.0dev.39651 +12 (Git) Conda
Build type: Release
Branch: pr/kadet1090/17564
Hash: e6b3f7de9609d60ad2b6b4af8fdc50d1f794d99d
Python 3.12.0, Qt 6.7.3, Coin 4.0.3, Vtk 9.3.1, OCC 7.8.1
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Dark/
Installed mods: 
  * CfdOF 1.29.3
  * CurvedShapes 1.0.13
  * Curves 0.6.51
  * dodo 1.0.1
  * fasteners 0.5.33
  * freecad.gears 1.3.0
  * Manipulator 1.5.7
  * OpenTheme 2024.9.1
  * OpticsWorkbench 1.0.26
  * Rocket 4.0.1
  * sheetmetal 0.6.1
  * Ship 2024.11.26
  * Silk 0.1.5
``` 

</p>
</details>

**Comment by maxwxyz** [comment]
here are the backtraces kindly provided by @hyarion

1. Crash in AssemblyExample.FCStd
  when using the AssemblyExample file: click on a part in the CAD folder and right click>transform. When Clicking OK or Cancel in the task dialog it crashes instantly.  
<details><summary>Backtrace AssemblyExample.FCStd</summary>
<p>

```
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
  * frame #0: 0x0000000102dae8f8 libFreeCADGui.dylib`Gui::TaskTransform::loadPlacementModeItems(this=0x0000000157eec190) const at TaskCSysDragger.cpp:157:31 [opt]
    frame #1: 0x0000000102dad71c libFreeCADGui.dylib`Gui::TaskTransform::setupGui(this=0x0000000157eec190) at TaskCSysDragger.cpp:180:5 [opt]
    frame #2: 0x0000000102dad434 libFreeCADGui.dylib`Gui::TaskTransform::TaskTransform(this=0x0000000157eec190, vp=0x000000017765a600, dragger=0x0000000150bac400, parent=0x0000000000000000, subObjectPlacemenProvider=0x0000000000000000, centerOfMassProvider=<unavailable>) at TaskCSysDragger.cpp:106:5 [opt]
    frame #3: 0x0000000102db2530 libFreeCADGui.dylib`Gui::TaskCSysDragger::TaskCSysDragger(Gui::ViewProviderDragger*, Gui::SoFCCSysDragger*) [inlined] Gui::TaskTransform::TaskTransform(this=0x0000000157eec190, vp=0x000000017765a600, dragger=0x0000000150bac400, parent=0x0000000000000000, subObjectPlacemenProvider=0x0000000000000000, centerOfMassProvider=<unavailable>) at TaskCSysDragger.cpp:96:1 [opt]
    frame #4: 0x0000000102db2518 libFreeCADGui.dylib`Gui::TaskCSysDragger::TaskCSysDragger(this=0x00006000034b3b80, vp=0x000000017765a600, dragger=0x0000000150bac400) at TaskCSysDragger.cpp:677:21 [opt]
    frame #5: 0x000000010308d5fc libFreeCADGui.dylib`Gui::ViewProviderDragger::getTransformDialog(this=0x000000017765a600) at ViewProviderDragger.cpp:106:16 [opt]
    frame #6: 0x000000010308dad8 libFreeCADGui.dylib`Gui::ViewProviderDragger::setEdit(this=0x000000017765a600, ModNum=<unavailable>) at ViewProviderDragger.cpp:188:31 [opt]
    frame #7: 0x0000000103074944 libFreeCADGui.dylib`Gui::ViewProvider::startEditing(this=0x000000017765a600, ModNum=1) at ViewProvider.cpp:137:8 [opt]
    frame #8: 0x000000010308d860 libFreeCADGui.dylib`Gui::ViewProviderDragger::startEditing(this=0x000000017765a600, mode=<unavailable>) at ViewProviderDragger.cpp:127:44 [opt]
    frame #9: 0x0000000102c59f74 libFreeCADGui.dylib`Gui::DocumentP::tryStartEditing(this=0x00000001183a7630, svp=<unavailable>, sobj=0x0000000177652600, ModNum=<unavailable>) at Document.cpp:282:34 [opt]
    frame #10: 0x0000000102c4e01c libFreeCADGui.dylib`Gui::DocumentP::tryStartEditing(this=<unavailable>, vp=<unavailable>, obj=<unavailable>, subname=<unavailable>, ModNum=<unavailable>) at Document.cpp:275:16 [opt] [artificial]
    frame #11: 0x0000000102c4d2e8 libFreeCADGui.dylib`Gui::Document::trySetEdit(this=0x000000013ef73980, p=<unavailable>, ModNum=1, subname=<unavailable>) at Document.cpp:638:13 [opt]
    frame #12: 0x0000000102c4ce9c libFreeCADGui.dylib`Gui::Document::setEdit(this=<unavailable>, p=<unavailable>, ModNum=<unavailable>, subname=<unavailable>) at Document.cpp:571:16 [opt]
    frame #13: 0x0000000102ec66b4 libFreeCADGui.dylib`Gui::TreeWidget::onStartEditing(this=0x000000011ee45c10) at Tree.cpp:1248:23 [opt]
    frame #14: 0x0000000102373ca4 libQt6Core.6.dylib`void doActivate<false>(QObject*, int, void**) + 1452
    frame #15: 0x0000000105b0708c libQt6Gui.6.dylib`QAction::activate(QAction::ActionEvent) + 284
    frame #16: 0x0000000105533bb8 libQt6Widgets.6.dylib`QMenuPrivate::activateCausedStack(QList<QPointer<QWidget>> const&, QAction*, QAction::ActionEvent, bool) + 116
    frame #17: 0x0000000105531690 libQt6Widgets.6.dylib`QMenuPrivate::activateAction(QAction*, QAction::ActionEvent, bool) + 600
    frame #18: 0x0000000105538354 libQt6Widgets.6.dylib`QMenu::mouseReleaseEvent(QMouseEvent*) + 484
    frame #19: 0x0000000105642288 libQt6Widgets.6.dylib`QWidget::event(QEvent*) + 132
    frame #20: 0x00000001055389d4 libQt6Widgets.6.dylib`QMenu::event(QEvent*) + 1160
    frame #21: 0x00000001056e70a0 libQt6Widgets.6.dylib`QApplicationPrivate::notify_helper(QObject*, QEvent*) + 272
    frame #22: 0x00000001056e9288 libQt6Widgets.6.dylib`QApplication::notify(QObject*, QEvent*) + 5248
    frame #23: 0x0000000102ca6ec4 libFreeCADGui.dylib`Gui::GUIApplication::notify(this=0x000000016fdfe798, receiver=0x000000016fdfbc40, event=0x000000016fdf9bf8) at GuiApplication.cpp:93:34 [opt]
    frame #24: 0x000000010241ed50 libQt6Core.6.dylib`QCoreApplication::notifyInternal2(QObject*, QEvent*) + 212
    frame #25: 0x00000001056e76c0 libQt6Widgets.6.dylib`QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) + 848
    frame #26: 0x000000010566caac libQt6Widgets.6.dylib`QWidgetWindow::handleMouseEvent(QMouseEvent*) + 2800
    frame #27: 0x000000010566b7ac libQt6Widgets.6.dylib`QWidgetWindow::event(QEvent*) + 168
    frame #28: 0x00000001056e70a0 libQt6Widgets.6.dylib`QApplicationPrivate::notify_helper(QObject*, QEvent*) + 272
    frame #29: 0x00000001056e8004 libQt6Widgets.6.dylib`QApplication::notify(QObject*, QEvent*) + 508
    frame #30: 0x0000000102ca6ec4 libFreeCADGui.dylib`Gui::GUIApplication::notify(this=0x000000016fdfe798, receiver=0x0000600003ea63a0, event=0x000000016fdfa190) at GuiApplication.cpp:93:34 [opt]
    frame #31: 0x000000010241ed50 libQt6Core.6.dylib`QCoreApplication::notifyInternal2(QObject*, QEvent*) + 212
    frame #32: 0x0000000105dd540c libQt6Gui.6.dylib`QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) + 1808
    frame #33: 0x0000000105d55f14 libQt6Gui.6.dylib`QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 408
    frame #34: 0x0000000107711b20 libqcocoa.dylib`QCocoaEventDispatcherPrivate::postedEventsSourceCallback(void*) + 436
    frame #35: 0x000000018a4ae4d8 CoreFoundation`__CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 28
    frame #36: 0x000000018a4ae46c CoreFoundation`__CFRunLoopDoSource0 + 176
    frame #37: 0x000000018a4ae1dc CoreFoundation`__CFRunLoopDoSources0 + 244
    frame #38: 0x000000018a4acdc8 CoreFoundation`__CFRunLoopRun + 828
    frame #39: 0x000000018a4ac434 CoreFoundation`CFRunLoopRunSpecific + 608
    frame #40: 0x0000000194c5019c HIToolbox`RunCurrentEventLoopInMode + 292
    frame #41: 0x0000000194c4fe2c HIToolbox`ReceiveNextEventCommon + 220
    frame #42: 0x0000000194c4fd30 HIToolbox`_BlockUntilNextEventMatchingListInModeWithFilter + 76
    frame #43: 0x000000018dd0bd68 AppKit`_DPSNextEvent + 660
    frame #44: 0x000000018e501808 AppKit`-[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 700
    frame #45: 0x000000018dcff09c AppKit`-[NSApplication run] + 476
    frame #46: 0x000000010770f70c libqcocoa.dylib`QCocoaEventDispatcher::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 2452
    frame #47: 0x000000010241fb48 libQt6Core.6.dylib`QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 576
    frame #48: 0x0000000105536fc4 libQt6Widgets.6.dylib`QMenuPrivate::exec(QPoint const&, QAction*, std::__1::function<QPoint (QSize const&)>) + 260
    frame #49: 0x000000010551a500 libQt6Widgets.6.dylib`QMenu::exec(QPoint const&, QAction*) + 52
    frame #50: 0x0000000102ec5a80 libFreeCADGui.dylib`Gui::TreeWidget::contextMenuEvent(this=0x000000011ee45c10, e=<unavailable>) at Tree.cpp:1175:25 [opt]
    frame #51: 0x0000000105642288 libQt6Widgets.6.dylib`QWidget::event(QEvent*) + 132
    frame #52: 0x000000010559a904 libQt6Widgets.6.dylib`QAbstractScrollArea::viewportEvent(QEvent*) + 96
    frame #53: 0x00000001054a8ff4 libQt6Widgets.6.dylib`QAbstractItemView::viewportEvent(QEvent*) + 1088
    frame #54: 0x000000010536acf8 libQt6Widgets.6.dylib`QTreeView::viewportEvent(QEvent*) + 300
    frame #55: 0x000000010241f118 libQt6Core.6.dylib`QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) + 288
    frame #56: 0x00000001056e7080 libQt6Widgets.6.dylib`QApplicationPrivate::notify_helper(QObject*, QEvent*) + 240
    frame #57: 0x00000001056e8a9c libQt6Widgets.6.dylib`QApplication::notify(QObject*, QEvent*) + 3220
    frame #58: 0x0000000102ca6ec4 libFreeCADGui.dylib`Gui::GUIApplication::notify(this=0x000000016fdfe798, receiver=0x0000600001591c80, event=0x000000016fdfc648) at GuiApplication.cpp:93:34 [opt]
    frame #59: 0x000000010241ed50 libQt6Core.6.dylib`QCoreApplication::notifyInternal2(QObject*, QEvent*) + 212
    frame #60: 0x000000010566c668 libQt6Widgets.6.dylib`QWidgetWindow::handleMouseEvent(QMouseEvent*) + 1708
    frame #61: 0x000000010566b7ac libQt6Widgets.6.dylib`QWidgetWindow::event(QEvent*) + 168
    frame #62: 0x00000001056e70a0 libQt6Widgets.6.dylib`QApplicationPrivate::notify_helper(QObject*, QEvent*) + 272
    frame #63: 0x00000001056e8004 libQt6Widgets.6.dylib`QApplication::notify(QObject*, QEvent*) + 508
    frame #64: 0x0000000102ca6ec4 libFreeCADGui.dylib`Gui::GUIApplication::notify(this=0x000000016fdfe798, receiver=0x0000600003f77d80, event=0x000000016fdfcbe0) at GuiApplication.cpp:93:34 [opt]
    frame #65: 0x000000010241ed50 libQt6Core.6.dylib`QCoreApplication::notifyInternal2(QObject*, QEvent*) + 212
    frame #66: 0x0000000105dd540c libQt6Gui.6.dylib`QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) + 1808
    frame #67: 0x0000000105d55f14 libQt6Gui.6.dylib`QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 408
    frame #68: 0x0000000107711b20 libqcocoa.dylib`QCocoaEventDispatcherPrivate::postedEventsSourceCallback(void*) + 436
    frame #69: 0x000000018a4ae4d8 CoreFoundation`__CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 28
    frame #70: 0x000000018a4ae46c CoreFoundation`__CFRunLoopDoSource0 + 176
    frame #71: 0x000000018a4ae1dc CoreFoundation`__CFRunLoopDoSources0 + 244
    frame #72: 0x000000018a4acdc8 CoreFoundation`__CFRunLoopRun + 828
    frame #73: 0x000000018a4ac434 CoreFoundation`CFRunLoopRunSpecific + 608
    frame #74: 0x0000000194c5019c HIToolbox`RunCurrentEventLoopInMode + 292
    frame #75: 0x0000000194c4fe2c HIToolbox`ReceiveNextEventCommon + 220
    frame #76: 0x0000000194c4fd30 HIToolbox`_BlockUntilNextEventMatchingListInModeWithFilter + 76
    frame #77: 0x000000018dd0bd68 AppKit`_DPSNextEvent + 660
    frame #78: 0x000000018e501808 AppKit`-[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 700
    frame #79: 0x000000018dcff09c AppKit`-[NSApplication run] + 476
    frame #80: 0x000000010770f70c libqcocoa.dylib`QCocoaEventDispatcher::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 2452
    frame #81: 0x000000010241fb48 libQt6Core.6.dylib`QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 576
    frame #82: 0x000000010241f78c libQt6Core.6.dylib`QCoreApplication::exec() + 128
    frame #83: 0x0000000102bd7268 libFreeCADGui.dylib`Gui::Application::runApplication() at Application.cpp:2205:13 [opt]
    frame #84: 0x0000000102bd7084 libFreeCADGui.dylib`Gui::Application::runApplication() [inlined] (anonymous namespace)::runEventLoop(mainApp=0x000000016fdfe798) at Application.cpp:2234:9 [opt]
    frame #85: 0x0000000102bd7084 libFreeCADGui.dylib`Gui::Application::runApplication() at Application.cpp:2310:5 [opt]
    frame #86: 0x00000001000078d4 FreeCAD`main(argc=<unavailable>, argv=<unavailable>) at MainGui.cpp:295:13 [opt]
    frame #87: 0x000000018a0460e0 dyld`start + 2360
(lldb) 
``` 

</p>
</details> 

2. Crash in ArchDetail.FCStd
  when using the ArchDetail example file: Clicking on any solid item and then right click>transform and it instantly crashes.  
<details><summary>Backtrace ArchDetail.FCStd
</summary>
<p>

```
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
  * frame #0: 0x000000018a396a60 libsystem_kernel.dylib`__pthread_kill + 8
    frame #1: 0x000000018a3cec20 libsystem_pthread.dylib`pthread_kill + 288
    frame #2: 0x000000018a2dba30 libsystem_c.dylib`abort + 180
    frame #3: 0x0000000102bd641c libFreeCADGui.dylib`messageHandler(type=QtFatalMsg, context=<unavailable>, msg=0x000000016fdfa6f0) at Application.cpp:1967:13 [opt]
    frame #4: 0x0000000102484390 libQt6Core.6.dylib`qt_message_print(QtMsgType, QMessageLogContext const&, QString const&) + 296
    frame #5: 0x00000001024805f8 libQt6Core.6.dylib`qt_message(QtMsgType, QMessageLogContext const&, char const*, char*) + 72
    frame #6: 0x00000001024ed568 libQt6Core.6.dylib`QMessageLogger::fatal(char const*, ...) const + 40
    frame #7: 0x00000001024ece04 libQt6Core.6.dylib`qt_assert(char const*, char const*, int) + 60
    frame #8: 0x0000000103127af8 libFreeCADGui.dylib`Gui::QuantitySpinBox::updateEdit(QString const&) [inlined] QTypeTraits::detail::Promoted<int, long long, std::__1::enable_if<std::is_arithmetic_v<int> && std::is_arithmetic_v<long long> && std::is_floating_point_v<int> == std::is_floating_point_v<long long> && std::is_signed_v<int> == std::is_signed_v<long long> && !std::is_same_v<int, bool> && !std::is_same_v<long long, bool> && !std::is_same_v<int, char> && !std::is_same_v<long long, char>, void>::type>::type qBound<int, long long>(min=<unavailable>, val=<unavailable>, max=<unavailable>) at qminmax.h:75:5 [opt]
    frame #9: 0x0000000103127ae0 libFreeCADGui.dylib`Gui::QuantitySpinBox::updateEdit(this=0x0000000354fc0c40, text=0x000000016fdfa808) at QuantitySpinBox.cpp:452:14 [opt]
    frame #10: 0x00000001031281c8 libFreeCADGui.dylib`Gui::QuantitySpinBox::updateText(this=0x0000000354fc0c40, quant=0x0000600003f37868) at QuantitySpinBox.cpp:436:5 [opt]
    frame #11: 0x000000010312a5dc libFreeCADGui.dylib`Gui::QuantitySpinBox::setUnitText(QString const&) [inlined] Gui::QuantitySpinBox::setUnit(this=0x0000000354fc0c40, unit=<unavailable>) at QuantitySpinBox.cpp:631:5 [opt]
    frame #12: 0x000000010312a5c0 libFreeCADGui.dylib`Gui::QuantitySpinBox::setUnitText(this=0x0000000354fc0c40, str=<unavailable>) at QuantitySpinBox.cpp:638:9 [opt]
    frame #13: 0x000000010312c268 libFreeCADGui.dylib`Gui::QuantitySpinBox::qt_metacall(this=0x0000000354fc0c40, _c=WriteProperty, _id=0, _a=0x000000016fdfa940) at moc_QuantitySpinBox.cpp:307:9 [opt]
    frame #14: 0x000000010242ebf8 libQt6Core.6.dylib`QMetaProperty::write(QObject*, QVariant&&) const + 1068
    frame #15: 0x00000001023740e4 libQt6Core.6.dylib`QObject::doSetProperty(char const*, QVariant const*, QVariant*) + 144
    frame #16: 0x0000000102db2e10 libFreeCADGui.dylib`Gui::Ui_TaskCSysDragger::retranslateUi(QWidget*) [inlined] QObject::setProperty(this=0x0000000354fc0c40, name=<unavailable>, value=0x000000016fdfaab8) at qobject.h:408:12 [opt]
    frame #17: 0x0000000102db2df8 libFreeCADGui.dylib`Gui::Ui_TaskCSysDragger::retranslateUi(this=0x0000000354fb94a0, Gui__TaskCSysDragger=<unavailable>) at ui_TaskCSysDragger.h:412:27 [opt]
    frame #18: 0x0000000102db0150 libFreeCADGui.dylib`Gui::Ui_TaskCSysDragger::setupUi(this=0x0000000354fb94a0, Gui__TaskCSysDragger=0x00006000046c4750) at ui_TaskCSysDragger.h:398:9 [opt]
    frame #19: 0x0000000102dad6fc libFreeCADGui.dylib`Gui::TaskTransform::setupGui(this=0x0000000354fb62e0) at TaskCSysDragger.cpp:177:9 [opt]
    frame #20: 0x0000000102dad434 libFreeCADGui.dylib`Gui::TaskTransform::TaskTransform(this=0x0000000354fb62e0, vp=0x00000001226f3800, dragger=0x0000000358aca800, parent=0x0000000000000000, subObjectPlacemenProvider=0x0000000000000000, centerOfMassProvider=<unavailable>) at TaskCSysDragger.cpp:106:5 [opt]
    frame #21: 0x0000000102db2530 libFreeCADGui.dylib`Gui::TaskCSysDragger::TaskCSysDragger(Gui::ViewProviderDragger*, Gui::SoFCCSysDragger*) [inlined] Gui::TaskTransform::TaskTransform(this=0x0000000354fb62e0, vp=0x00000001226f3800, dragger=0x0000000358aca800, parent=0x0000000000000000, subObjectPlacemenProvider=0x0000000000000000, centerOfMassProvider=<unavailable>) at TaskCSysDragger.cpp:96:1 [opt]
    frame #22: 0x0000000102db2518 libFreeCADGui.dylib`Gui::TaskCSysDragger::TaskCSysDragger(this=0x000060000660e800, vp=0x00000001226f3800, dragger=0x0000000358aca800) at TaskCSysDragger.cpp:677:21 [opt]
    frame #23: 0x000000010308d5fc libFreeCADGui.dylib`Gui::ViewProviderDragger::getTransformDialog(this=0x00000001226f3800) at ViewProviderDragger.cpp:106:16 [opt]
    frame #24: 0x000000010308dad8 libFreeCADGui.dylib`Gui::ViewProviderDragger::setEdit(this=0x00000001226f3800, ModNum=<unavailable>) at ViewProviderDragger.cpp:188:31 [opt]
    frame #25: 0x0000000103074944 libFreeCADGui.dylib`Gui::ViewProvider::startEditing(this=0x00000001226f3800, ModNum=1) at ViewProvider.cpp:137:8 [opt]
    frame #26: 0x000000010308d860 libFreeCADGui.dylib`Gui::ViewProviderDragger::startEditing(this=0x00000001226f3800, mode=<unavailable>) at ViewProviderDragger.cpp:127:44 [opt]
    frame #27: 0x0000000102c59f74 libFreeCADGui.dylib`Gui::DocumentP::tryStartEditing(this=0x0000000177286860, svp=<unavailable>, sobj=0x00000001226f1c00, ModNum=<unavailable>) at Document.cpp:282:34 [opt]
    frame #28: 0x0000000102c4e01c libFreeCADGui.dylib`Gui::DocumentP::tryStartEditing(this=<unavailable>, vp=<unavailable>, obj=<unavailable>, subname=<unavailable>, ModNum=<unavailable>) at Document.cpp:275:16 [opt] [artificial]
    frame #29: 0x0000000102c4d2e8 libFreeCADGui.dylib`Gui::Document::trySetEdit(this=0x0000000301af23f0, p=<unavailable>, ModNum=1, subname=<unavailable>) at Document.cpp:638:13 [opt]
    frame #30: 0x0000000102c4ce9c libFreeCADGui.dylib`Gui::Document::setEdit(this=<unavailable>, p=<unavailable>, ModNum=<unavailable>, subname=<unavailable>) at Document.cpp:571:16 [opt]
    frame #31: 0x0000000102d04ee4 libFreeCADGui.dylib`StdCmdTransformManip::activated(this=0x00006000038da9a0, iMsg=<unavailable>) at CommandDoc.cpp:1610:33 [opt]
    frame #32: 0x0000000102cec6f4 libFreeCADGui.dylib`Gui::Command::_invoke(this=0x00006000038da9a0, id=0, disablelog=<unavailable>) at Command.cpp:444:17 [opt]
    frame #33: 0x0000000102cec4b0 libFreeCADGui.dylib`Gui::Command::invoke(this=0x00006000038da9a0, i=0, trigger=<unavailable>) at Command.cpp:408:5 [opt]
    frame #34: 0x0000000102373c58 libQt6Core.6.dylib`void doActivate<false>(QObject*, int, void**) + 1376
    frame #35: 0x0000000105b0708c libQt6Gui.6.dylib`QAction::activate(QAction::ActionEvent) + 284
    frame #36: 0x0000000105533bb8 libQt6Widgets.6.dylib`QMenuPrivate::activateCausedStack(QList<QPointer<QWidget>> const&, QAction*, QAction::ActionEvent, bool) + 116
    frame #37: 0x0000000105531690 libQt6Widgets.6.dylib`QMenuPrivate::activateAction(QAction*, QAction::ActionEvent, bool) + 600
    frame #38: 0x0000000105538354 libQt6Widgets.6.dylib`QMenu::mouseReleaseEvent(QMouseEvent*) + 484
    frame #39: 0x0000000105642288 libQt6Widgets.6.dylib`QWidget::event(QEvent*) + 132
    frame #40: 0x00000001055389d4 libQt6Widgets.6.dylib`QMenu::event(QEvent*) + 1160
    frame #41: 0x00000001056e70a0 libQt6Widgets.6.dylib`QApplicationPrivate::notify_helper(QObject*, QEvent*) + 272
    frame #42: 0x00000001056e9288 libQt6Widgets.6.dylib`QApplication::notify(QObject*, QEvent*) + 5248
    frame #43: 0x0000000102ca6ec4 libFreeCADGui.dylib`Gui::GUIApplication::notify(this=0x000000016fdfe798, receiver=0x0000600000516700, event=0x000000016fdfbd78) at GuiApplication.cpp:93:34 [opt]
    frame #44: 0x000000010241ed50 libQt6Core.6.dylib`QCoreApplication::notifyInternal2(QObject*, QEvent*) + 212
    frame #45: 0x0000000105533a74 libQt6Widgets.6.dylib`QMenuPrivate::mouseEventTaken(QMouseEvent*) + 1784
    frame #46: 0x00000001055381b0 libQt6Widgets.6.dylib`QMenu::mouseReleaseEvent(QMouseEvent*) + 64
    frame #47: 0x0000000105642288 libQt6Widgets.6.dylib`QWidget::event(QEvent*) + 132
    frame #48: 0x00000001055389d4 libQt6Widgets.6.dylib`QMenu::event(QEvent*) + 1160
    frame #49: 0x00000001056e70a0 libQt6Widgets.6.dylib`QApplicationPrivate::notify_helper(QObject*, QEvent*) + 272
    frame #50: 0x00000001056e9288 libQt6Widgets.6.dylib`QApplication::notify(QObject*, QEvent*) + 5248
    frame #51: 0x0000000102ca6ec4 libFreeCADGui.dylib`Gui::GUIApplication::notify(this=0x000000016fdfe798, receiver=0x00006000046f6460, event=0x000000016fdfc648) at GuiApplication.cpp:93:34 [opt]
    frame #52: 0x000000010241ed50 libQt6Core.6.dylib`QCoreApplication::notifyInternal2(QObject*, QEvent*) + 212
    frame #53: 0x00000001056e76c0 libQt6Widgets.6.dylib`QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) + 848
    frame #54: 0x000000010566caac libQt6Widgets.6.dylib`QWidgetWindow::handleMouseEvent(QMouseEvent*) + 2800
    frame #55: 0x000000010566b7ac libQt6Widgets.6.dylib`QWidgetWindow::event(QEvent*) + 168
    frame #56: 0x00000001056e70a0 libQt6Widgets.6.dylib`QApplicationPrivate::notify_helper(QObject*, QEvent*) + 272
    frame #57: 0x00000001056e8004 libQt6Widgets.6.dylib`QApplication::notify(QObject*, QEvent*) + 508
    frame #58: 0x0000000102ca6ec4 libFreeCADGui.dylib`Gui::GUIApplication::notify(this=0x000000016fdfe798, receiver=0x0000600006032100, event=0x000000016fdfcbe0) at GuiApplication.cpp:93:34 [opt]
    frame #59: 0x000000010241ed50 libQt6Core.6.dylib`QCoreApplication::notifyInternal2(QObject*, QEvent*) + 212
    frame #60: 0x0000000105dd540c libQt6Gui.6.dylib`QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) + 1808
    frame #61: 0x0000000105d55f14 libQt6Gui.6.dylib`QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 408
    frame #62: 0x0000000107db5b20 libqcocoa.dylib`QCocoaEventDispatcherPrivate::postedEventsSourceCallback(void*) + 436
    frame #63: 0x000000018a4ae4d8 CoreFoundation`__CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 28
    frame #64: 0x000000018a4ae46c CoreFoundation`__CFRunLoopDoSource0 + 176
    frame #65: 0x000000018a4ae1dc CoreFoundation`__CFRunLoopDoSources0 + 244
    frame #66: 0x000000018a4acdc8 CoreFoundation`__CFRunLoopRun + 828
    frame #67: 0x000000018a4ac434 CoreFoundation`CFRunLoopRunSpecific + 608
    frame #68: 0x0000000194c5019c HIToolbox`RunCurrentEventLoopInMode + 292
    frame #69: 0x0000000194c4fe2c HIToolbox`ReceiveNextEventCommon + 220
    frame #70: 0x0000000194c4fd30 HIToolbox`_BlockUntilNextEventMatchingListInModeWithFilter + 76
    frame #71: 0x000000018dd0bd68 AppKit`_DPSNextEvent + 660
    frame #72: 0x000000018e501808 AppKit`-[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 700
    frame #73: 0x000000018dcff09c AppKit`-[NSApplication run] + 476
    frame #74: 0x0000000107db370c libqcocoa.dylib`QCocoaEventDispatcher::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 2452
    frame #75: 0x000000010241fb48 libQt6Core.6.dylib`QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 576
    frame #76: 0x000000010241f78c libQt6Core.6.dylib`QCoreApplication::exec() + 128
    frame #77: 0x0000000102bd7268 libFreeCADGui.dylib`Gui::Application::runApplication() at Application.cpp:2205:13 [opt]
    frame #78: 0x0000000102bd7084 libFreeCADGui.dylib`Gui::Application::runApplication() [inlined] (anonymous namespace)::runEventLoop(mainApp=0x000000016fdfe798) at Application.cpp:2234:9 [opt]
    frame #79: 0x0000000102bd7084 libFreeCADGui.dylib`Gui::Application::runApplication() at Application.cpp:2310:5 [opt]
    frame #80: 0x00000001000078d4 FreeCAD`main(argc=<unavailable>, argv=<unavailable>) at MainGui.cpp:295:13 [opt]
    frame #81: 0x000000018a0460e0 dyld`start + 2360
(lldb) 
``` 

</p>
</details>

**Comment by maxwxyz** [comment]
@kadet1090 to add to that: It only happens with this PR, not on a weekly build.

Opening the **AssemblyExample.FCStd** and just marking the file for recompute will freeze FreeCAD:
```
Process 36024 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = hit program assert
    frame #4: 0x000000018e29aec3 libOndselSolver.1.0.1.dylib`MbD::LimitIJ::fillqsudot(this=<unavailable>, col=<unavailable>) at LimitIJ.cpp:112:2 [opt]
   109  void MbD::LimitIJ::fillqsudot(FColDsptr col)
   110  {
   111      (void) col;
-> 112          assert(false);
   113  }
   114 
   115  void MbD::LimitIJ::fillqsudotWeights(DiagMatDsptr diagMat)
Target 0: (FreeCAD) stopped.
warning: libOndselSolver.1.0.1.dylib was compiled with optimization - stepping may behave oddly; variables may not be available.
```
@PaddleStroke @aiksiongkoh FYI, seems related to OndselSolver.
<details><summary>Backtrace</summary>
<p>

```
* thread #1, queue = 'com.apple.main-thread', stop reason = hit program assert
    frame #0: 0x00007ff8118ae196 libsystem_kernel.dylib`__pthread_kill + 10
    frame #1: 0x00007ff8118e5ee6 libsystem_pthread.dylib`pthread_kill + 263
    frame #2: 0x00007ff81180cb45 libsystem_c.dylib`abort + 123
    frame #3: 0x00007ff81180be5e libsystem_c.dylib`__assert_rtn + 314
  * frame #4: 0x000000018e29aec3 libOndselSolver.1.0.1.dylib`MbD::LimitIJ::fillqsudot(this=<unavailable>, col=<unavailable>) at LimitIJ.cpp:112:2 [opt]
    frame #5: 0x000000018e306825 libOndselSolver.1.0.1.dylib`std::__1::__function::__func<MbD::VelICSolver::runBasic()::$_2, std::__1::allocator<MbD::VelICSolver::runBasic()::$_2>, void (std::__1::shared_ptr<MbD::Item>)>::operator()(std::__1::shared_ptr<MbD::Item>&&) [inlined] MbD::VelICSolver::runBasic()::$_2::operator()(this=<unavailable>, item=<unavailable>) const at VelICSolver.cpp:65:78 [opt]
    frame #6: 0x000000018e3067fb libOndselSolver.1.0.1.dylib`std::__1::__function::__func<MbD::VelICSolver::runBasic()::$_2, std::__1::allocator<MbD::VelICSolver::runBasic()::$_2>, void (std::__1::shared_ptr<MbD::Item>)>::operator()(std::__1::shared_ptr<MbD::Item>&&) [inlined] decltype(std::declval<MbD::VelICSolver::runBasic()::$_2&>()(std::declval<std::__1::shared_ptr<MbD::Item>>())) std::__1::__invoke[abi:ue170006]<MbD::VelICSolver::runBasic()::$_2&, std::__1::shared_ptr<MbD::Item>>(__f=<unavailable>, __args=<unavailable>) at invoke.h:340:25 [opt]
    frame #7: 0x000000018e3067ee libOndselSolver.1.0.1.dylib`std::__1::__function::__func<MbD::VelICSolver::runBasic()::$_2, std::__1::allocator<MbD::VelICSolver::runBasic()::$_2>, void (std::__1::shared_ptr<MbD::Item>)>::operator()(std::__1::shared_ptr<MbD::Item>&&) [inlined] void std::__1::__invoke_void_return_wrapper<void, true>::__call[abi:ue170006]<MbD::VelICSolver::runBasic()::$_2&, std::__1::shared_ptr<MbD::Item>>(__args=<unavailable>, __args=<unavailable>) at invoke.h:415:5 [opt]
    frame #8: 0x000000018e3067ee libOndselSolver.1.0.1.dylib`std::__1::__function::__func<MbD::VelICSolver::runBasic()::$_2, std::__1::allocator<MbD::VelICSolver::runBasic()::$_2>, void (std::__1::shared_ptr<MbD::Item>)>::operator()(std::__1::shared_ptr<MbD::Item>&&) [inlined] std::__1::__function::__alloc_func<MbD::VelICSolver::runBasic()::$_2, std::__1::allocator<MbD::VelICSolver::runBasic()::$_2>, void (std::__1::shared_ptr<MbD::Item>)>::operator()[abi:ue170006](this=<unavailable>, __arg=<unavailable>) at function.h:192:16 [opt]
    frame #9: 0x000000018e3067ee libOndselSolver.1.0.1.dylib`std::__1::__function::__func<MbD::VelICSolver::runBasic()::$_2, std::__1::allocator<MbD::VelICSolver::runBasic()::$_2>, void (std::__1::shared_ptr<MbD::Item>)>::operator()(this=<unavailable>, __arg=<unavailable>) at function.h:363:12 [opt]
    frame #10: 0x000000018e2f5811 libOndselSolver.1.0.1.dylib`MbD::System::partsJointsMotionsLimitsDo(std::__1::function<void (std::__1::shared_ptr<MbD::Item>)> const&) [inlined] std::__1::__function::__value_func<void (std::__1::shared_ptr<MbD::Item>)>::operator()[abi:ue170006](this=0x00007ff7bfefacf0, __args=nullptr) const at function.h:517:16 [opt]
    frame #11: 0x000000018e2f57f8 libOndselSolver.1.0.1.dylib`MbD::System::partsJointsMotionsLimitsDo(std::__1::function<void (std::__1::shared_ptr<MbD::Item>)> const&) [inlined] std::__1::function<void (std::__1::shared_ptr<MbD::Item>)>::operator()(this=0x00007ff7bfefacf0, __arg=nullptr) const at function.h:1168:12 [opt]
    frame #12: 0x000000018e2f57f8 libOndselSolver.1.0.1.dylib`MbD::System::partsJointsMotionsLimitsDo(std::__1::function<void (std::__1::shared_ptr<MbD::Item>)> const&) [inlined] std::__1::function<void (std::__1::shared_ptr<MbD::Item>)> std::__1::for_each[abi:ue170006]<std::__1::__wrap_iter<std::__1::shared_ptr<MbD::LimitIJ>*>, std::__1::function<void (std::__1::shared_ptr<MbD::Item>)>>(__first=__wrap_iter<std::__1::shared_ptr<MbD::LimitIJ> *> @ scalar, __last=__wrap_iter<std::__1::shared_ptr<MbD::LimitIJ> *> @ scalar, __f=function<void (std::__1::shared_ptr<MbD::Item>)> @ 0x00007ff7bfefacf0) at for_each.h:26:5 [opt]
    frame #13: 0x000000018e2f57b8 libOndselSolver.1.0.1.dylib`MbD::System::partsJointsMotionsLimitsDo(this=0x000000018e6c9a18, f=<unavailable>) at System.cpp:163:2 [opt]
    frame #14: 0x000000018e305af1 libOndselSolver.1.0.1.dylib`MbD::VelICSolver::runBasic(this=0x000000018f4ac1d8) at VelICSolver.cpp:65:11 [opt]
    frame #15: 0x000000018e3058b2 libOndselSolver.1.0.1.dylib`MbD::VelICSolver::run(this=0x000000018f4ac1d8) at VelICSolver.cpp:52:8 [opt]
    frame #16: 0x000000018e2f937c libOndselSolver.1.0.1.dylib`MbD::SystemSolver::runAllIC(this=0x000000018e6c9b38) at SystemSolver.cpp:71:3 [opt]
    frame #17: 0x000000018e2f389b libOndselSolver.1.0.1.dylib`MbD::System::runKINEMATIC(this=0x000000018e6c9a18, self=<unavailable>) at System.cpp:86:16 [opt]
    frame #18: 0x000000018e1a514d libOndselSolver.1.0.1.dylib`MbD::ASMTAssembly::runKINEMATIC(this=0x000000010c6ca418) at ASMTAssembly.cpp:1447:20 [opt]
    frame #19: 0x000000018d9a3cb2 AssemblyApp.so`Assembly::AssemblyObject::solve(this=0x0000000185043000, enableRedo=false, updateJCS=<unavailable>) at AssemblyObject.cpp:162:22 [opt]
    frame #20: 0x000000018d9a38d6 AssemblyApp.so`Assembly::AssemblyObject::execute(this=0x0000000185043000) at AssemblyObject.cpp:131:9 [opt]
    frame #21: 0x000000010097815d libFreeCADApp.dylib`App::DocumentObject::recompute(this=0x0000000185043000) at DocumentObject.cpp:167:22 [opt]
    frame #22: 0x00000001008f1ad2 libFreeCADApp.dylib`App::Document::_recomputeFeature(this=0x000000010b11f400, Feat=0x0000000185043000) at Document.cpp:3469:32 [opt]
    frame #23: 0x00000001008efb33 libFreeCADApp.dylib`App::Document::recompute(this=0x000000010b11f400, objs=<unavailable>, force=<unavailable>, hasError=0x0000000000000000, options=<unavailable>) at Document.cpp:3177:31 [opt]
    frame #24: 0x00000001009ec0c3 libFreeCADApp.dylib`App::DocumentPy::recompute(this=0x000000017e77f8c0, args=<unavailable>) at DocumentPyImp.cpp:690:31 [opt]
    frame #25: 0x00000001009e4e50 libFreeCADApp.dylib`App::DocumentPy::staticCallback_recompute(self=<unavailable>, args=<unavailable>) at DocumentPy.cpp:2025:57 [opt]
    frame #26: 0x0000000101b0e23e libpython3.12.dylib`cfunction_call + 222
    frame #27: 0x0000000101a8afba libpython3.12.dylib`_PyObject_MakeTpCall + 522
    frame #28: 0x0000000101c4a57a libpython3.12.dylib`_PyEval_EvalFrameDefault + 110074
    frame #29: 0x0000000101c2e062 libpython3.12.dylib`PyEval_EvalCode + 178
    frame #30: 0x0000000101ce8056 libpython3.12.dylib`run_eval_code_obj + 86
    frame #31: 0x0000000101ce8369 libpython3.12.dylib`run_mod + 121
    frame #32: 0x0000000101cedb2c libpython3.12.dylib`PyRun_StringFlags + 156
    frame #33: 0x00000001003e5caf libFreeCADBase.dylib`Base::InterpreterSingleton::runString(this=<unavailable>, sCmd="App.activeDocument().recompute(None,True,True)") at Interpreter.cpp:249:15 [opt]
    frame #34: 0x00000001029173c6 libFreeCADGui.dylib`Gui::Command::_runCommand(file="/Users/maxwilfinger/dev/FreeCAD/src/Gui/CommandDoc.cpp", line=1537, eType=Doc, sCmd="App.activeDocument().recompute(None,True,True)") at Command.cpp:725:29 [opt]
    frame #35: 0x0000000102917230 libFreeCADGui.dylib`Gui::Command::_doCommand(file="/Users/maxwilfinger/dev/FreeCAD/src/Gui/CommandDoc.cpp", line=1537, eType=Doc, sCmd=<unavailable>) at Command.cpp:677:5 [opt]
    frame #36: 0x00000001029303fc libFreeCADGui.dylib`StdCmdRefresh::activated(this=0x0000000107788460, iMsg=<unavailable>) at CommandDoc.cpp:1537:13 [opt]
    frame #37: 0x0000000102916179 libFreeCADGui.dylib`Gui::Command::_invoke(this=0x0000000107788460, id=0, disablelog=<unavailable>) at Command.cpp:433:17 [opt]
    frame #38: 0x0000000102915df5 libFreeCADGui.dylib`Gui::Command::invoke(this=0x0000000107788460, i=0, trigger=<unavailable>) at Command.cpp:408:5 [opt]
    frame #39: 0x00000001058ab433 libQt6Core.6.dylib`void doActivate<false>(QObject*, int, void**) + 1539
    frame #40: 0x00000001060b6c87 libQt6Gui.6.dylib`QAction::activate(QAction::ActionEvent) + 311
    frame #41: 0x0000000105266a29 libQt6Widgets.6.dylib`QAbstractButtonPrivate::click() + 89
    frame #42: 0x000000010526860d libQt6Widgets.6.dylib`QAbstractButton::mouseReleaseEvent(QMouseEvent*) + 205
    frame #43: 0x00000001050bfe58 libQt6Widgets.6.dylib`QToolButton::mouseReleaseEvent(QMouseEvent*) + 40
    frame #44: 0x00000001052e7d75 libQt6Widgets.6.dylib`QWidget::event(QEvent*) + 469
    frame #45: 0x00000001050be2ca libQt6Widgets.6.dylib`QToolButton::event(QEvent*) + 234
    frame #46: 0x00000001053a1801 libQt6Widgets.6.dylib`QApplicationPrivate::notify_helper(QObject*, QEvent*) + 241
    frame #47: 0x00000001053a3e99 libQt6Widgets.6.dylib`QApplication::notify(QObject*, QEvent*) + 6537
    frame #48: 0x00000001028ce1c7 libFreeCADGui.dylib`Gui::GUIApplication::notify(this=0x00007ff7bfefeaf8, receiver=0x0000000136cfa190, event=0x00007ff7bfefc950) at GuiApplication.cpp:93:34 [opt]
    frame #49: 0x000000010595ed67 libQt6Core.6.dylib`QCoreApplication::notifyInternal2(QObject*, QEvent*) + 167
    frame #50: 0x00000001053a1e17 libQt6Widgets.6.dylib`QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) + 919
    frame #51: 0x0000000105315987 libQt6Widgets.6.dylib`QWidgetWindow::handleMouseEvent(QMouseEvent*) + 1847
    frame #52: 0x00000001053146e6 libQt6Widgets.6.dylib`QWidgetWindow::event(QEvent*) + 118
    frame #53: 0x00000001053a1801 libQt6Widgets.6.dylib`QApplicationPrivate::notify_helper(QObject*, QEvent*) + 241
    frame #54: 0x00000001053a2705 libQt6Widgets.6.dylib`QApplication::notify(QObject*, QEvent*) + 501
    frame #55: 0x00000001028ce1c7 libFreeCADGui.dylib`Gui::GUIApplication::notify(this=0x00007ff7bfefeaf8, receiver=0x0000000137a1f550, event=0x00007ff7bfefce90) at GuiApplication.cpp:93:34 [opt]
    frame #56: 0x000000010595ed67 libQt6Core.6.dylib`QCoreApplication::notifyInternal2(QObject*, QEvent*) + 167
    frame #57: 0x00000001063e9583 libQt6Gui.6.dylib`QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) + 2259
    frame #58: 0x000000010634e87b libQt6Gui.6.dylib`QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 443
    frame #59: 0x0000000108b18d8e libqcocoa.dylib`QCocoaEventDispatcherPrivate::postedEventsSourceCallback(void*) + 414
    frame #60: 0x00007ff8119c1e9a CoreFoundation`__CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
    frame #61: 0x00007ff8119c1e3c CoreFoundation`__CFRunLoopDoSource0 + 157
    frame #62: 0x00007ff8119c1c15 CoreFoundation`__CFRunLoopDoSources0 + 217
    frame #63: 0x00007ff8119c089f CoreFoundation`__CFRunLoopRun + 916
    frame #64: 0x00007ff8119bfea1 CoreFoundation`CFRunLoopRunSpecific + 560
    frame #65: 0x00007ff81b44bf3d HIToolbox`RunCurrentEventLoopInMode + 292
    frame #66: 0x00007ff81b44bb84 HIToolbox`ReceiveNextEventCommon + 199
    frame #67: 0x00007ff81b44baa8 HIToolbox`_BlockUntilNextEventMatchingListInModeWithFilter + 64
    frame #68: 0x00007ff814a5dd08 AppKit`_DPSNextEvent + 858
    frame #69: 0x00007ff814a5cbb2 AppKit`-[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1214
    frame #70: 0x00007ff814a4f227 AppKit`-[NSApplication run] + 586
    frame #71: 0x0000000108b16aad libqcocoa.dylib`QCocoaEventDispatcher::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 2701
    frame #72: 0x000000010595f9b6 libQt6Core.6.dylib`QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 518
    frame #73: 0x000000010595f626 libQt6Core.6.dylib`QCoreApplication::exec() + 134
    frame #74: 0x000000010280ede5 libFreeCADGui.dylib`Gui::Application::runApplication() at Application.cpp:2205:13 [opt]
    frame #75: 0x000000010280eb58 libFreeCADGui.dylib`Gui::Application::runApplication() [inlined] (anonymous namespace)::runEventLoop(mainApp=0x00007ff7bfefeaf8) at Application.cpp:2234:9 [opt]
    frame #76: 0x000000010280eb58 libFreeCADGui.dylib`Gui::Application::runApplication() at Application.cpp:2310:5 [opt]
    frame #77: 0x0000000100004f16 FreeCAD`main(argc=<unavailable>, argv=<unavailable>) at MainGui.cpp:295:13 [opt]
    frame #78: 0x00007ff81158b418 dyld`start + 1896
``` 

</p>
</details> 

The other crash in with the **ArchDetail.FCStd**:
```
ASSERT: "!(P(max) < P(min))" in file /Users/maxwilfinger/dev/FreeCAD/.pixi/envs/default/include/qt6/QtCore/qminmax.h, line 75
Process 36747 stopped
Process 36747 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
    frame #0: 0x00007ff8118ae196 libsystem_kernel.dylib`__pthread_kill + 10
libsystem_kernel.dylib`:
->  0x7ff8118ae196 <+10>: jae    0x7ff8118ae1a0            ; <+20>
    0x7ff8118ae198 <+12>: movq   %rax, %rdi
    0x7ff8118ae19b <+15>: jmp    0x7ff8118a7c7b            ; cerror_nocancel
    0x7ff8118ae1a0 <+20>: retq   
Target 0: (FreeCAD) stopped.
```
@yorikvanhavre FYI.
<details><summary>Backtrace</summary>
<p>

```
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
  * frame #0: 0x00007ff8118ae196 libsystem_kernel.dylib`__pthread_kill + 10
    frame #1: 0x00007ff8118e5ee6 libsystem_pthread.dylib`pthread_kill + 263
    frame #2: 0x00007ff81180cb45 libsystem_c.dylib`abort + 123
    frame #3: 0x000000010280dda2 libFreeCADGui.dylib`messageHandler(type=QtFatalMsg, context=<unavailable>, msg=0x00007ff7bfefb1c8) at Application.cpp:1967:13 [opt]
    frame #4: 0x00000001059c5edb libQt6Core.6.dylib`qt_message_print(QtMsgType, QMessageLogContext const&, QString const&) + 251
    frame #5: 0x00000001059c18ef libQt6Core.6.dylib`qt_message(QtMsgType, QMessageLogContext const&, char const*, __va_list_tag*) + 63
    frame #6: 0x0000000105a3f1f6 libQt6Core.6.dylib`QMessageLogger::fatal(char const*, ...) const + 124
    frame #7: 0x0000000105a3e6b0 libQt6Core.6.dylib`qt_assert(char const*, char const*, int) + 68
    frame #8: 0x0000000102d9b27f libFreeCADGui.dylib`Gui::QuantitySpinBox::updateEdit(QString const&) [inlined] QTypeTraits::detail::Promoted<int, long long, std::__1::enable_if<std::is_arithmetic_v<int> && std::is_arithmetic_v<long long> && std::is_floating_point_v<int> == std::is_floating_point_v<long long> && std::is_signed_v<int> == std::is_signed_v<long long> && !std::is_same_v<int, bool> && !std::is_same_v<long long, bool> && !std::is_same_v<int, char> && !std::is_same_v<long long, char>, void>::type>::type qBound<int, long long>(min=<unavailable>, val=<unavailable>, max=<unavailable>) at qminmax.h:75:5 [opt]
    frame #9: 0x0000000102d9b267 libFreeCADGui.dylib`Gui::QuantitySpinBox::updateEdit(this=0x0000000188e80d40, text=0x00007ff7bfefb380) at QuantitySpinBox.cpp:452:14 [opt]
    frame #10: 0x0000000102d9b915 libFreeCADGui.dylib`Gui::QuantitySpinBox::updateText(this=0x0000000188e80d40, quant=0x0000000188e87a28) at QuantitySpinBox.cpp:436:5 [opt]
    frame #11: 0x0000000102d9e36f libFreeCADGui.dylib`Gui::QuantitySpinBox::setUnitText(QString const&) [inlined] Gui::QuantitySpinBox::setUnit(this=0x0000000188e80d40, unit=<unavailable>) at QuantitySpinBox.cpp:631:5 [opt]
    frame #12: 0x0000000102d9e353 libFreeCADGui.dylib`Gui::QuantitySpinBox::setUnitText(this=0x0000000188e80d40, str=<unavailable>) at QuantitySpinBox.cpp:638:9 [opt]
    frame #13: 0x0000000102da01b0 libFreeCADGui.dylib`Gui::QuantitySpinBox::qt_metacall(this=0x0000000188e80d40, _c=WriteProperty, _id=0, _a=0x00007ff7bfefb4a0) at moc_QuantitySpinBox.cpp:307:9 [opt]
    frame #14: 0x000000010596f46d libQt6Core.6.dylib`QMetaProperty::write(QObject*, QVariant&&) const + 1133
    frame #15: 0x00000001058ab824 libQt6Core.6.dylib`QObject::doSetProperty(char const*, QVariant const*, QVariant*) + 132
    frame #16: 0x00000001029e9b4e libFreeCADGui.dylib`Gui::Ui_TaskCSysDragger::retranslateUi(QWidget*) [inlined] QObject::setProperty(this=0x0000000188e80d40, name=<unavailable>, value=0x00007ff7bfefb5c8) at qobject.h:408:12 [opt]
    frame #17: 0x00000001029e9b39 libFreeCADGui.dylib`Gui::Ui_TaskCSysDragger::retranslateUi(this=0x000000019525f0a0, Gui__TaskCSysDragger=0x000000018ad65b00) at ui_TaskCSysDragger.h:412:27 [opt]
    frame #18: 0x00000001029e68a0 libFreeCADGui.dylib`Gui::Ui_TaskCSysDragger::setupUi(this=0x000000019525f0a0, Gui__TaskCSysDragger=0x000000018ad65b00) at ui_TaskCSysDragger.h:398:9 [opt]
    frame #19: 0x00000001029e347e libFreeCADGui.dylib`Gui::TaskTransform::setupGui(this=0x000000018ad658b0) at TaskCSysDragger.cpp:177:9 [opt]
    frame #20: 0x00000001029e3187 libFreeCADGui.dylib`Gui::TaskTransform::TaskTransform(this=0x000000018ad658b0, vp=0x000000018d911800, dragger=0x0000000187868000, parent=0x0000000000000000, subObjectPlacemenProvider=0x00000001299169e0, centerOfMassProvider=0x0000000129917b80) at TaskCSysDragger.cpp:106:5 [opt]
    frame #21: 0x00000001029e921d libFreeCADGui.dylib`Gui::TaskCSysDragger::TaskCSysDragger(Gui::ViewProviderDragger*, Gui::SoFCCSysDragger*) [inlined] Gui::TaskTransform::TaskTransform(this=0x000000018ad658b0, vp=0x000000018d911800, dragger=0x0000000187868000, parent=0x0000000000000000, subObjectPlacemenProvider=0x00000001299169e0, centerOfMassProvider=<unavailable>) at TaskCSysDragger.cpp:96:1 [opt]
    frame #22: 0x00000001029e9207 libFreeCADGui.dylib`Gui::TaskCSysDragger::TaskCSysDragger(this=0x000000018ad657b0, vp=0x000000018d911800, dragger=0x0000000187868000) at TaskCSysDragger.cpp:677:21 [opt]
    frame #23: 0x0000000102cf6b59 libFreeCADGui.dylib`Gui::ViewProviderDragger::getTransformDialog(this=0x000000018d911800) at ViewProviderDragger.cpp:106:16 [opt]
    frame #24: 0x0000000102cf700c libFreeCADGui.dylib`Gui::ViewProviderDragger::setEdit(this=0x000000018d911800, ModNum=<unavailable>) at ViewProviderDragger.cpp:188:31 [opt]
    frame #25: 0x0000000102cdcf56 libFreeCADGui.dylib`Gui::ViewProvider::startEditing(this=<unavailable>, ModNum=<unavailable>) at ViewProvider.cpp:137:8 [opt]
    frame #26: 0x0000000102cf6d99 libFreeCADGui.dylib`Gui::ViewProviderDragger::startEditing(this=<unavailable>, mode=<unavailable>) at ViewProviderDragger.cpp:127:44 [opt]
    frame #27: 0x0000000102883c4d libFreeCADGui.dylib`Gui::DocumentP::tryStartEditing(this=0x000000017eb43190, svp=<unavailable>, sobj=<unavailable>, ModNum=<unavailable>) at Document.cpp:282:34 [opt]
    frame #28: 0x0000000102876d12 libFreeCADGui.dylib`Gui::DocumentP::tryStartEditing(this=<unavailable>, vp=<unavailable>, obj=<unavailable>, subname=<unavailable>, ModNum=<unavailable>) at Document.cpp:275:16 [opt] [artificial]
    frame #29: 0x0000000102875f98 libFreeCADGui.dylib`Gui::Document::trySetEdit(this=0x0000000137d5cee0, p=<unavailable>, ModNum=1, subname=<unavailable>) at Document.cpp:638:13 [opt]
    frame #30: 0x0000000102875ad1 libFreeCADGui.dylib`Gui::Document::setEdit(this=<unavailable>, p=<unavailable>, ModNum=<unavailable>, subname=<unavailable>) at Document.cpp:571:16 [opt]
    frame #31: 0x0000000102930e47 libFreeCADGui.dylib`StdCmdTransformManip::activated(this=0x00000001081939d0, iMsg=<unavailable>) at CommandDoc.cpp:1656:33 [opt]
    frame #32: 0x000000010291609c libFreeCADGui.dylib`Gui::Command::_invoke(this=0x00000001081939d0, id=0, disablelog=<unavailable>) at Command.cpp:444:17 [opt]
    frame #33: 0x0000000102915df5 libFreeCADGui.dylib`Gui::Command::invoke(this=0x00000001081939d0, i=0, trigger=<unavailable>) at Command.cpp:408:5 [opt]
    frame #34: 0x00000001058ab433 libQt6Core.6.dylib`void doActivate<false>(QObject*, int, void**) + 1539
    frame #35: 0x00000001060b6c87 libQt6Gui.6.dylib`QAction::activate(QAction::ActionEvent) + 311
    frame #36: 0x00000001051bfcf8 libQt6Widgets.6.dylib`QMenuPrivate::activateCausedStack(QList<QPointer<QWidget>> const&, QAction*, QAction::ActionEvent, bool) + 104
    frame #37: 0x00000001051bd50d libQt6Widgets.6.dylib`QMenuPrivate::activateAction(QAction*, QAction::ActionEvent, bool) + 557
    frame #38: 0x00000001051c4f91 libQt6Widgets.6.dylib`QMenu::mouseReleaseEvent(QMouseEvent*) + 513
    frame #39: 0x00000001052e7d75 libQt6Widgets.6.dylib`QWidget::event(QEvent*) + 469
    frame #40: 0x00000001051c56be libQt6Widgets.6.dylib`QMenu::event(QEvent*) + 1278
    frame #41: 0x00000001053a1801 libQt6Widgets.6.dylib`QApplicationPrivate::notify_helper(QObject*, QEvent*) + 241
    frame #42: 0x00000001053a3e99 libQt6Widgets.6.dylib`QApplication::notify(QObject*, QEvent*) + 6537
    frame #43: 0x00000001028ce1c7 libFreeCADGui.dylib`Gui::GUIApplication::notify(this=0x00007ff7bfefeaf8, receiver=0x000000017e3f49d0, event=0x00007ff7bfefc950) at GuiApplication.cpp:93:34 [opt]
    frame #44: 0x000000010595ed67 libQt6Core.6.dylib`QCoreApplication::notifyInternal2(QObject*, QEvent*) + 167
    frame #45: 0x00000001053a1e17 libQt6Widgets.6.dylib`QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) + 919
    frame #46: 0x000000010531608a libQt6Widgets.6.dylib`QWidgetWindow::handleMouseEvent(QMouseEvent*) + 3642
    frame #47: 0x00000001053146e6 libQt6Widgets.6.dylib`QWidgetWindow::event(QEvent*) + 118
    frame #48: 0x00000001053a1801 libQt6Widgets.6.dylib`QApplicationPrivate::notify_helper(QObject*, QEvent*) + 241
    frame #49: 0x00000001053a2705 libQt6Widgets.6.dylib`QApplication::notify(QObject*, QEvent*) + 501
    frame #50: 0x00000001028ce1c7 libFreeCADGui.dylib`Gui::GUIApplication::notify(this=0x00007ff7bfefeaf8, receiver=0x00000001972b4da0, event=0x00007ff7bfefce90) at GuiApplication.cpp:93:34 [opt]
    frame #51: 0x000000010595ed67 libQt6Core.6.dylib`QCoreApplication::notifyInternal2(QObject*, QEvent*) + 167
    frame #52: 0x00000001063e9583 libQt6Gui.6.dylib`QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) + 2259
    frame #53: 0x000000010634e87b libQt6Gui.6.dylib`QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 443
    frame #54: 0x0000000108b18d8e libqcocoa.dylib`QCocoaEventDispatcherPrivate::postedEventsSourceCallback(void*) + 414
    frame #55: 0x00007ff8119c1e9a CoreFoundation`__CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
    frame #56: 0x00007ff8119c1e3c CoreFoundation`__CFRunLoopDoSource0 + 157
    frame #57: 0x00007ff8119c1c15 CoreFoundation`__CFRunLoopDoSources0 + 217
    frame #58: 0x00007ff8119c089f CoreFoundation`__CFRunLoopRun + 916
    frame #59: 0x00007ff8119bfea1 CoreFoundation`CFRunLoopRunSpecific + 560
    frame #60: 0x00007ff81b44bf3d HIToolbox`RunCurrentEventLoopInMode + 292
    frame #61: 0x00007ff81b44bb84 HIToolbox`ReceiveNextEventCommon + 199
    frame #62: 0x00007ff81b44baa8 HIToolbox`_BlockUntilNextEventMatchingListInModeWithFilter + 64
    frame #63: 0x00007ff814a5dd08 AppKit`_DPSNextEvent + 858
    frame #64: 0x00007ff814a5cbb2 AppKit`-[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1214
    frame #65: 0x00007ff814a4f227 AppKit`-[NSApplication run] + 586
    frame #66: 0x0000000108b16aad libqcocoa.dylib`QCocoaEventDispatcher::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 2701
    frame #67: 0x000000010595f9b6 libQt6Core.6.dylib`QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 518
    frame #68: 0x000000010595f626 libQt6Core.6.dylib`QCoreApplication::exec() + 134
    frame #69: 0x000000010280ede5 libFreeCADGui.dylib`Gui::Application::runApplication() at Application.cpp:2205:13 [opt]
    frame #70: 0x000000010280eb58 libFreeCADGui.dylib`Gui::Application::runApplication() [inlined] (anonymous namespace)::runEventLoop(mainApp=0x00007ff7bfefeaf8) at Application.cpp:2234:9 [opt]
    frame #71: 0x000000010280eb58 libFreeCADGui.dylib`Gui::Application::runApplication() at Application.cpp:2310:5 [opt]
    frame #72: 0x0000000100004f16 FreeCAD`main(argc=<unavailable>, argv=<unavailable>) at MainGui.cpp:295:13 [opt]
    frame #73: 0x00007ff81158b418 dyld`start + 1896
``` 

</p>
</details> 


I can only produce crashes with these two files for now.

**Comment by maxwxyz** [comment]
@kadet1090 another issue when working with links and assembly/part container:

1. Transforming a link does transform the base object, but only when I select an element in the 3D view of the link and then start the transform tool command.
2. It is in this scenario, when the dragger placement is also way off.

Screencast:

https://github.com/user-attachments/assets/b5dc9247-7cc8-494a-927d-18e6f1f20255



Demo file:
[asm-test.FCStd.zip](https://github.com/user-attachments/files/18186028/asm-test.FCStd.zip)

**Comment by maxwxyz** [comment]
Narrowing it down it seems to be related to units. 
If I create a new file with a cube and just change the units in the document information, this is the result:
- Standard --> OK
- MKS --> OK
- US customary --> OK
- Imperial decimal --> OK
- Building Euro --> OK
- **Building US --> Crash**
- Metric small part --> OK
- **Imperial for civil eng. --> Crash**
- FEM --> OK
- Meter decimal --> OK

**Comment by kadet1090** [comment]
> Transforming a link does transform the base object, but only when I select an element in the 3D view of the link and then start the transform tool command.
Should be fixed now?

> Crash in AssemblyExample.FCStd
> when using the AssemblyExample file: click on a part in the CAD folder and right click>transform. When Clicking OK or Cancel in the task dialog it crashes instantly.

This file randomly crashes with this assert, not something for this PR. Maybe it makes it worse as it applies the transform in a different manner but it is not for this PR.

> Narrowing it down it seems to be related to units.
Fixed.

**Comment by maxwxyz** [comment]
I can confirm it fixes the issue.
Three more:
1. link transform does work now, but not in that case: when selecting an element in the 3d view, the last feature is selected if it is a link of a PD body. Transform then falls back to the original body.
grafik

2. When you hit Move to other object you cannot cancel that. The button displays cancel and it does nothing
3. You also get weird behavior when running move to other object or pick a custom dragger location and just hover but don't click and then adjust the spinboxes. But that is an edge case I think. Workaround would be to disable inputs when dragger or target is chosen.

**Comment by maxwxyz** [comment]
waiting for fixes (to put it back in the queue for the merge meeting)

**Comment by maxwxyz** [comment]
Now as soon as you open the dialog, there is already rotation values in the spinboxes, even in local mode. Should be 0,0,0 when starting the dialog:
Bildschirmfoto 2024-12-25 um 14 14 16

**Comment by maxwxyz** [comment]
@kadet1090 Global rotation is fixed but one new issue:
When dragger is not aligned, rotation around W is the value around Z, even if the axes are not aligned. It should be the global XYZ rotation, same as it is for position. It works when align dragger to CS is checked:


https://github.com/user-attachments/assets/ace15faa-af18-4e9e-8582-0f3c7e0f6f22

**Comment by maxwxyz** [comment]
Rotation values in the spinboxes reset as soon as I start dragging in the 3D view, even when rotating around the same axis.

https://github.com/user-attachments/assets/25d77dbe-a24b-4846-bff9-4484c2fb331f

**Comment by kadet1090** [comment]
> When dragger is not aligned, rotation around W is the value around Z, even if the axes are not aligned. It should be the global XYZ rotation, same as it is for position. It works when align dragger to CS is checked:

Fixed, I now use extrinsic angles instead of intrinsic for absolute mode.

> Rotation values in the spinboxes reset as soon as I start dragging in the 3D view, even when rotating around the same axis.

Should be fixed also.

> Now as soon as you open the dialog, there is already rotation values in the spinboxes, even in local mode. Should be 0,0,0 when starting the dialog:

Fixed? Probably, I could not reproduce.

**Comment by maxwxyz** [comment]
@kadet1090 yes, great, all fixed.
One last one: This now only happens when rotating around V axis: at some point U and W switch to -180°, so dragging further or increasing the value in the spinbox also resets their values all to 0:

https://github.com/user-attachments/assets/488a0ed0-e907-4149-affa-11f29492c777

**Review by maxwxyz — APPROVED** [review]

**Comment by maxwxyz** [comment]
@pieterhijma is it good from your side too?

File: src/Base/Rotation.h (hunk 7 above)
Comment (hyarion) [reply src/Base/Rotation.h:97]: In that case, I think it should be explicitly defined somewhere rather than having it only as an assumption in this function.

**Comment by hyarion** [comment]
> here are the backtraces kindly provided by @hyarion
> 
> 1. Crash in AssemblyExample.FCStd
>    when using the AssemblyExample file: click on a part in the CAD folder and right click>transform. When Clicking OK or Cancel in the task dialog it crashes instantly.
> 
> Backtrace AssemblyExample.FCStd
> 2. Crash in ArchDetail.FCStd
>    when using the ArchDetail example file: Clicking on any solid item and then right click>transform and it instantly crashes.
> 
> Backtrace ArchDetail.FCStd

I've now verified that both these where fixed by [Base: Use std::string as key for services map](https://github.com/FreeCAD/FreeCAD/pull/17564/commits/a58a0bdd5da035c98e1cebc815e70b841e4a8c70) 👍

File: src/Base/Rotation.h (hunk 7 above)
Comment (kadet1090) [reply src/Base/Rotation.h:97]: I can update the doc comment, it seems like reasonable place for such information. 

In general I feel that in 3D space it is assumed that Z axis defines the normal vector for surfaces. It is quite natural because surfaces are 2D objects and so have only XY (or UV to differentiate surface coordinates from 3D space) space to work with and so the normal vector, which is perpendicular to both must be Z. Given that reasoning I could update the name to `fromSurfaceNormalVector` which should be more clear.

Assembly uses the same assumption and I bet that we would find more such assumptions across the codebase

**Review by pieterhijma — CHANGES_REQUESTED** [review]
Looks very good to me in general, but I have a couple of small comments.

Since others have tested extensively, I was focused mainly on the code, but I did notice a couple of things in terms of functionality as well:
- Center of mass mode is not possible on links. Would this require a service that needs to be a added? How would that work?
- The labels on the dragger do not consistently change between UWV and XYZ when switching from local to global (simply try on a Part Cube, for example). 
- Often there are more coordinate systems than only local and global, for example in an assembly. I would find it useful to be able to pick all possible coordinate systems in the hierarchy. Could be a separate issue/PR of course.
- The dragger appears in a surprising location on subshapebinders, for example create a subshapebinder from a Part Cube that has been transformed and transform this subshapebinder.

File: src/Gui/ViewProviderLink.h [hunk 9]
```diff
@@ -184,10 +184,10 @@ class GuiExport LinkView : public Base::BaseClass, public LinkOwner {
     Py::Object PythonObject;
 };
 
-class GuiExport ViewProviderLink : public ViewProviderDocumentObject
+class GuiExport ViewProviderLink : public ViewProviderDragger
```
[the remark this answers is not in the document]
Comment (kadet1090) [reply src/Gui/ViewProviderLink.h:187]: That is a question to @realthunder, I was not able to deduce any good reason for not inheriting from that class and found many problems caused by it.

File: src/Gui/ViewProviderDragger.cpp [hunk 10]
```diff
@@ -81,249 +115,228 @@ bool ViewProviderDragger::doubleClicked()
...
+void ViewProviderDragger::dragStartCallback(void* data, [[maybe_unused]] SoDragger* d)
 {
-    auto selection = static_cast<SoGroup*>(viewer->getSceneGraph());
-    SoNode *child = selection->getChild(0);
-    if (child && child->isOfType(SoPickStyle::getClassTypeId())) {
-        selection->removeChild(child);
-        viewer->setSelectionEnabled(true);
-    }
+    // This is called when a manipulator has done manipulating
+    auto sudoThis = static_cast<ViewProviderDragger*>(data);
```
[the remark this answers is not in the document]
Comment (kadet1090) [reply src/Gui/ViewProviderDragger.cpp:226]: So, coin3D is from the time when C++ did not have lambdas so to implement closures context is passed via `void*` data argument that can contain arbitrary stuff and is defined when adding callback. 

In case of this callback `this` is passed as the data and later is extracted in context of the static function. So in reality this is just a `this` pointer passed explicitly to a function via argument. Some files uses `self` as name, in context of this file it was `sudoThis` - frankly I don't know why it was called like this, I assumed that it is convention that is used more across the codebase but it is not. 

So, any suggestions for the name? maybe `callerViewProvider`?

File: src/App/Application.cpp [hunk 11]
```diff
@@ -2217,6 +2219,8 @@ void Application::initTypes()
     new Base::ExceptionProducer<Base::CADKernelError>;
     new Base::ExceptionProducer<Base::RestoreError>;
     new Base::ExceptionProducer<Base::PropertyError>;
+
+    ServiceProvider::get().implement<CenterOfMassProvider>(new NullCenterOfMass);
```
[the remark this answers is not in the document]
Comment (kadet1090) [reply src/App/Application.cpp:2223]: ServiceProvider is not really singleton - you can instantiate multiple instances of it if it is needed for any reason (for example to provide scoped provider for typical service locator use). There is however one global service provider implemented as singleton that should be used to acquire global services. Ideally it should probably be part of `Application` class.

I also don't think think that namespace here is necessary - I consider ServiceProvider to be implementation detail. The goal of this function is to obtain instance of service implementing given interface - Service Provider class is only means to do so. If anything, I'd call the namespace simply `Service`. However, given that the name is already quite lengthy I would not want to make it any longer - ideally it should fit in one line.

As for the names:
 - I'll surely rename `Base::implementContract` into `Base::implementService` or something like thatas I fortgot to rename that method originally. I don't like `addService` as it does not add service, only an implementation of service - service is defined by the abstract interface class.
 - `Base::provideImplementation()` - I am open to change that name, `provide` seems like good word, but `acquireService` also seems nice and is a bit shorter.
 - I don't like `acquireAllServices` on the same reasoning as first point. This PR introduces 2 services: `CenterOfMassProvider` and `SubObjectPlacementProvider` with 2 and 1 implementation respectively. For method named `acquireAllServices` I'd assume to obtain both `CenterOfMassProvider` and `SubObjectPlacementProvider` not all implementations of lets say `CenterOfMassProvider`

**Comment by kadet1090** [comment]
> Center of mass mode is not possible on links. Would this require a service that needs to be a added? How would that work?

Additional implementation of `CenterOfMassProvider` would be required here, something like `LinkCenterOfMass`. Then `CenterOfMassProvider` would have two implementations, one for `Part` and one for `Link`. We should then iterate over all possible implementations until any is able to provide the center of mass. This logic however should be encapsulated into some aggregate service that provides a good abstraction over this iteration. I will implement that, however I don't want to do this as part of this PR.  



> The labels on the dragger do not consistently change between UWV and XYZ when switching from local to global (simply try on a Part Cube, for example).

You should need to check "Align dragger with selected coordinate system" for it to change labels to XYZ. Even if you are in absolute mode the arrows of dragger are still aligned with UVW coordinate system, not XYZ.


> Often there are more coordinate systems than only local and global, for example in an assembly. I would find it useful to be able to pick all possible coordinate systems in the hierarchy. Could be a separate issue/PR of course.

Yup, that is separate issue - code is written in a way that implementing this feature would be easy.

> The dragger appears in a surprising location on subshapebinders, for example create a subshapebinder from a Part Cube that has been transformed and transform this subshapebinder.

Will need to check that, thx!

File: src/App/Application.cpp (hunk 11 above)
[the remark this answers is not in the document]
Comment (pieterhijma) [reply src/App/Application.cpp:2223]: Ok, I can see that the service provider is not really a singleton. Indeed you can construct one yourself. However, by providing a static get function, you really communicate to readers of the code that the class is meant to be a singleton. The public constructor communicates the opposite, so for me it feels like mixed signals here and clearly I overlooked the public constructor and assumed it was a singleton based on the static `get()`. If there is one service provider meant to be global, but you can also construct service providers for limited scope, I would prefer to simply have a global instance available. I don't mind global variables for things that are meant to be global.

I guess I wasn't clear on that but you don't address why there are two ways of accessing the global instance. One way is what you do above:
- `ServiceProvider::get().implement<CenterOfMassProvider>(new NullCenterOfMass);`
- `Base::implementContract<CenterOfMassProvider>(new NullCenterOfMass);`

I find the second one more logical for this case (it is accessing the global one). 

About the namespace, I don't find it necessary if the ServiceProvider keeps on being a class.

Regarding naming. I can see your point, but `Base::implementService` sounds to me as if this function is going to create an implementation for a service which is not the case. I can see the difference between a service and an implementation of the service, but from the viewpoint of the user of the function, you created an implementation of a service and you're adding it to the service provider. At the moment you created the implementation of the service, the implementation will act as a service, so when the service switches from being an implementation to when it becomes a service (in any case before calling `acquireService()`) is splitting hairs a bit. Perhaps the most accurate would be `addServiceImplementation()`, but that is a bit long. I would simply call it `addService()`, but it is not critical to me.

Regarding your comment on `acquireAllServices()`: I don't think that is the case, because we still have the template parameter that communicates your acquiring all services of `CenterOfMassProvider` or `SubObjectPlacementProvider`.

File: src/Gui/ViewProviderLink.h (hunk 9 above)
[the remark this answers is not in the document]
Comment (pieterhijma) [reply src/Gui/ViewProviderLink.h:187]: Ok, good, makes sense to me to have it like this.

**Comment by pieterhijma** [comment]
> > Center of mass mode is not possible on links. Would this require a service that needs to be a added? How would that work?
> 
> Additional implementation of `CenterOfMassProvider` would be required here, something like `LinkCenterOfMass`. Then `CenterOfMassProvider` would have two implementations, one for `Part` and one for `Link`. We should then iterate over all possible implementations until any is able to provide the center of mass. This logic however should be encapsulated into some aggregate service that provides a good abstraction over this iteration. I will implement that, however I don't want to do this as part of this PR.

Ok, totally fine not to have it as part of this PR. Can we make an issue for this one then? The link case allows us already to understand some of the requirements.

> > The labels on the dragger do not consistently change between UWV and XYZ when switching from local to global (simply try on a Part Cube, for example).
> 
> You should need to check "Align dragger with selected coordinate system" for it to change labels to XYZ. Even if you are in absolute mode the arrows of dragger are still aligned with UVW coordinate system, not XYZ.

Right, that's a tricky little checkbox that suddenly appears! In hindsight, I realize I had actually seen it, but I wondered for what it was and because it is not visible all the time, I forgot about it. I think this checkbox lacks a bit in usability. For me it would help if the checkbox is always on be default when you switch to global and you can switch it off if you want to. I don't know if that makes sense in terms of CAD workflow though.
 
> > Often there are more coordinate systems than only local and global, for example in an assembly. I would find it useful to be able to pick all possible coordinate systems in the hierarchy. Could be a separate issue/PR of course.
> 
> Yup, that is separate issue - code is written in a way that implementing this feature would be easy.

Great. Let's make an issue about that then.

> > The dragger appears in a surprising location on subshapebinders, for example create a subshapebinder from a Part Cube that has been transformed and transform this subshapebinder.
> 
> Will need to check that, thx!

Great.

**Comment by maxwxyz** [comment]
@pieterhijma I'll create the new feature requests as soon as this is merged. Transforming subshapebinders was not possible before.

File: src/App/Application.cpp (hunk 11 above)
[the remark this answers is not in the document]
Comment (kadet1090) [reply src/App/Application.cpp:2223]: This singleton is misleading, indeed. I thought I changed all `ServiceProvider::get` occurrences into functions from  `Base` but I did not. I also did remove singleton and replaced it with global variable as I agree with your point here. 

As for the names, I reworked it a bit so now it is:

```
provideImplementation<T> -> provideService<T>
provideAllImplementation<T> -> provideServiceImplementations<T>
implementContract<T> -> registerServiceImplementation<T>
```

`registerServiceImplementation` is quite long, but it is not used in assignments so it should be quite fine. I have quite strong opinion about mixing `service implementation` with `service` concept and I'm really not keen on using plural services unless it actually supplies different services (so, something like you can say fishes only when you are talking about multiple species of fish)

File: src/Base/Rotation.h (hunk 7 above)
Comment (kadet1090) [reply src/Base/Rotation.h:98]: I've added information to the doc comment of the method, but it probably should end up within class comment when it is fully documented.

File: src/App/Application.cpp (hunk 11 above)
[the remark this answers is not in the document]
Comment (pieterhijma) [reply src/App/Application.cpp]: Good that we agree on the global variable. I think this is much better.

Regarding the naming, I think I can follow your logic and if there is a logic to it, then I'm fine. I think this is your logic:

- dealing with implementations follows the convention to have "implementation" in the name, so for example: `Base::registerServiceImplementation<CenterOfMassProvider>(new NullCenterOfMass);` registers an implementation of service `CenterOfMassProvider`, so "implementation" is in the name.
- dealing with only a service (without really caring about which implementation), so for example: `    App::SubObjectPlacementProvider* subObjectPlacementProvider = Base::provideService<App::SubObjectPlacementProvider>();`, then there is no "implementation" in the name.

I'm fine with this, but I want to point out that to me personally, "implementation" in the names is a bit pleonastic because the context already makes clear that it provides an implementation of an interface, so `Base::registerService<CenterOfMassProvider>(new NullCenterOfMass)` would be sufficient for me to understand that `CenterOfMassProvider` is the interface and `NullCenterOfMass` the implementation. On the other hand, if you're new to this API, then it may be useful that the name with "implementation" in it already suggests that you have to provide an implementation to an interface. I have a slight preference of making use of the context, so leaving out "implementation", but again since I can recognize a clear logic, I'm totally ok.

**Comment by pieterhijma** [comment]
> @pieterhijma I'll create the new feature requests as soon as this is merged. Transforming subshapebinders was not possible before.

Thanks. Good point. I didn't realize that never worked, but now that you mention it, I remember.

**Review by pieterhijma — APPROVED** [review]
Really great work! Looks very good to me.

I still think the little checkbox to align to global coordinates should be checked by default, but this is not fundamental and can be a separate issue for the DWG perhaps.

Another point that gives a bit unexpected behavior is that when you transform something let's say with a delta of 10 mm in the X direction and then you switch to the global coordinates to verify what this means in terms of that coordinate system, and then you switch back to the local coordinate system, the delta values are reset. Again, probably not fundamental, so I propose to simply merge and create an issue for it (or it is by design, but then not intuitive to me).

Just out of interest, I notice that subshapebinders now also work, great! However, I missed the changes in the code that accomplish this. Could you point me to the changes that affect subshapebinder transformation?

File: src/App/Application.cpp (hunk 11 above)
[the remark this answers is not in the document]
Comment (kadet1090) [reply src/App/Application.cpp]: You described the logic behind naming better than I ever could! Yes, that was the intent. I think that giving a bit more context on caller side is always better than lacking a bit. I agree that it is not really needed but it does not make it much worse. If this will pose readability problems we can rename it later.

**Comment by kadet1090** [comment]
> Really great work! Looks very good to me.

Thanks!

> I still think the little checkbox to align to global coordinates should be checked by default, but this is not fundamental and can be a separate issue for the DWG perhaps.

I'm open for such change once more people request it. Current reasoning is that the fact that you want to see the position in global frame of reference does not mean that you want to change rotation of the dragger. But I am not married to that in any way.

> Another point that gives a bit unexpected behavior is that when you transform something let's say with a delta of 10 mm in the X direction and then you switch to the global coordinates to verify what this means in terms of that coordinate system, and then you switch back to the local coordinate system, the delta values are reset. Again, probably not fundamental, so I propose to simply merge and create an issue for it (or it is by design, but then not intuitive to me).

That should not happen. Local position should reset when:
1. Dragger changes position
2. Any axis of dragger changes rotation

It might be related to dragger align checkbox somehow.

> Just out of interest, I notice that subshapebinders now also work, great! However, I missed the changes in the code that accomplish this. Could you point me to the changes that affect subshapebinder transformation?

Have not touched it. I think that it will work only when binder is not attached to anything. I plan to extend this dialog so if it is attached it does not affect Placement property (which is calculated from attachment) but instead affects AttachmentOffset. Should not be too hard. But it is another issue to tackle!

**Comment by kaiwas** [comment]
Tested the new version. I really liked it!

But I noticed one oddity. Different changes reset previous transformations.
I understand that these are local transformations. But this behavior is typical that local coordinates are reset after actions (without pressing the OK button).

This is probably not very good. It would probably be more correct if all transformations were "summed up" and applied only by the "OK" button.
Demonstration on video.


https://github.com/user-attachments/assets/dffd651f-ec40-4ebc-880c-3cdb84b22cfb

**Comment by kaiwas** [comment]
if it is possible to integrate into this tool the creation of copies of an object and the repetition of the last changes? (maybe some checkboxes). This would allow the object to be replicated with a given step.

**Comment by belinski-roman** [comment]
An example is creating a copy when moving or rotating using a similar transformation function from the App Shapr3d. It would be possible to add a checkbox to create a copy (App::Link) or two buttons to apply the transformation after the fact — Apple and Apple for the copy[](url)

**Comment by maxwxyz** [comment]
@kaiwas the reset is necessary as as soon as you change transform or rotation the previous values in the other fields are not the same anymore and this would result in even more confusion. Think of rotating around U, moving in W and then rotating around V in one go. The axis at the end do not match with the coordinate system you had when you started the dialog. Sure you could do the math and keep values but the user could not work with them.
Second could be done but makes no sense IMO as soon as you have attached the dragger: where should the transformation be around (what is the origin). I could see the use of create a copy checkbox. But what should it create? An independent copy, a simple copy, a linked object (clone)... there are more options. You can create a new feature request for it.

**Comment by kaiwas** [comment]
> the reset is necessary as as soon as you change transform or rotation the previous values

Okay. I agree with this (although the sum of the movements BEFORE the controller change could be shown next to the current values). But the rotation falls out of this logic. For some reason it does not reset when moving. Probably everything should work the same in all fields.

**Comment by maxwxyz** [comment]
It works as expected. It resets when the axis changes. If you rotate around Z and move in X, Y, or Z the Z axis is still pointing in the same direction, that's why there is no need to reset the rotation around Z. If you rotate it around another axis, the Z axis is not pointing in the same direction as before, thus resetting the value. Same logic for movements: As long as the dragger is not rotated they are kept, as the axes point in the same direction. If you rotate them, they are not aligned as they were before, thus resetting the translation values.

**Comment by kaiwas** [comment]
Снимок экрана_20250115_155039

**Comment by maxwxyz** [comment]
exactly that's why it is resetted and not displayed: 620 is wrong, because  U changed it's orientation.

**Comment by kaiwas** [comment]
> It works as expected

Thank you. It became clearer. Movements have no history. With multiple transformations, you will have to write them down on a piece of paper)

**Comment by kadet1090** [comment]
Summing up the movements was the initial implementation, but it was causing strange readouts. With rotating frame of reference that changes definition of the coordinate system it is not possible to satisfy all scenarios, unfortunately.

**Comment by belinski-roman** [comment]
@kadet1090 Have you planned to add a copy transformation instead of the original? As an option

**Comment by kadet1090** [comment]
No, this is something that should be discussed on different issue, there will be problems with implementing something like that however

**Comment by PaddleStroke** [comment]
This PR breaks entering any negative value into any quantityspinbox accross the application. See https://github.com/FreeCAD/FreeCAD/issues/19124

**Comment by PaddleStroke** [comment]
Also generates https://github.com/FreeCAD/FreeCAD/issues/19989
