### PR TITLE
Assembly: Fix sketcher external edit

### LINKED ISSUE #28989: Assembly: Segfault when opening a sketch created with "Assembly_InsertNewPart"
### Problem description

FC crashes when trying to open the initial sketch created by `Assembly_InsertNewPart` command .
Also , the part is created at the origin of the document even tho the user chooses other geometry as the origin (should this be a different bug report?)

https://github.com/user-attachments/assets/deaac09b-90f4-4456-87fb-9f8b7a0c6927

### Workbench affected?

Assembly

### Steps to reproduce

1-Create Assembly
2-Insert new part using Assembly_InsertNewPart
3-Open the newly created sketch
4-SegFault

### Expected behavior

.

### Actual behavior

FC crashes with 

```
Program received signal SIGSEGV, Segmentation fault.
#0  /lib/x86_64-linux-gnu/libc.so.6(+0x45330) [0x733755445330]
#1  0x733757a896c8 in SoBase::unref() const from /tmp/.mount_FreeCApmenoC/usr/bin/../lib/libCoin.so.80+0x18
#2  0x7336837dea17 in AssemblyGui::ViewProviderAssembly::unsetEdit(int) from /tmp/.mount_FreeCApmenoC/usr/lib/AssemblyGui.so+0xa7
#3  0x73375bf77983 in Gui::ViewProvider::finishEditing() from /tmp/.mount_FreeCApmenoC/usr/bin/../lib/libFreeCADGui.so+0x13
#4  0x73375baa2d6c in Gui::Document::_resetEdit() from /tmp/.mount_FreeCApmenoC/usr/bin/../lib/libFreeCADGui.so+0xac
#5  0x73375baa2961 in Gui::Document::trySetEdit(Gui::ViewProvider*, int, char const*) from /tmp/.mount_FreeCApmenoC/usr/bin/../lib/libFreeCADGui.so+0x2d1
#6  0x73375baa2491 in Gui::Document::setEdit(Gui::ViewProvider*, int, char const*) from /tmp/.mount_FreeCApmenoC/usr/bin/../lib/libFreeCADGui.so+0x21
#7  0x73367b89b834 in SketcherGui::ViewProviderSketch::doubleClicked() from /tmp/.mount_FreeCApmenoC/usr/lib/SketcherGui.so+0x24
#8  0x73375bd7c999 in Gui::TreeWidget::mouseDoubleClickEvent(QMouseEvent*) from /tmp/.mount_FreeCApmenoC/usr/bin/../lib/libFreeCADGui.so+0x279
#9  0x7337573c3d8d in QWidget::event(QEvent*) from /tmp/.mount_FreeCApmenoC/usr/bin/../lib/libQt6Widgets.so.6+0xf8d
#10  0x73375726f2c7 in QFrame::event(QEvent*) from /tmp/.mount_FreeCApmenoC/usr/bin/../lib/libQt6Widgets.so.6+0x37
#11  0x733755f5f8de in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) from /tmp/.mount_FreeCApmenoC/usr/bin/../lib/libQt6Core.so.6+0x7e
#12  0x7337573b3e38 in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /tmp/.mount_FreeCApmenoC/usr/bin/../lib/libQt6Widgets.so.6+0x78
#13  0x7337573b4cbd in QApplication::notify(QObject*, QEvent*) from /tmp/.mount_FreeCApmenoC/usr/bin/../lib/libQt6Widgets.so.6+0xdad
#14  0x73375bae3218 in Gui::GUIApplication::notify(QObject*, QEvent*) from /tmp/.mount_FreeCApmenoC/usr/bin/../lib/libFreeCADGui.so+0x78
#15  0x733755f5fb8a in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /tmp/.mount_FreeCApmenoC/usr/bin/../lib/libQt6Core.so.6+0x17a
#16  0x7337573bbe7c in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) from /tmp/.mount_FreeCApmenoC/usr/bin/../lib/libQt6Widgets.so.6+0x1ec
#17  /tmp/.mount_FreeCApmenoC/usr/bin/../lib/libQt6Widgets.so.6(+0x5be8c7) [0x7337573be8c7]
#18  /tmp/.mount_FreeCApmenoC/usr/bin/../lib/libQt6Widgets.so.6(+0x5c5440) [0x7337573c5440]
#19  0x7337573b3e48 in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /tmp/.mount_FreeCApmenoC/usr/bin/../lib/libQt6Widgets.so.6+0x88
#20  0x73375bae3218 in Gui::GUIApplication::notify(QObject*, QEvent*) from /tmp/.mount_FreeCApmenoC/usr/bin/../lib/libFreeCADGui.so+0x78
#21  0x733755f5fb8a in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /tmp/.mount_FreeCApmenoC/usr/bin/../lib/libQt6Core.so.6+0x17a
#22  0x7337565d1882 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) from /tmp/.mount_FreeCApmenoC/usr/bin/../lib/libQt6Gui.so.6+0x722
#23  0x733756631e14 in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /tmp/.mount_FreeCApmenoC/usr/bin/../lib/libQt6Gui.so.6+0xb4
#24  /tmp/.mount_FreeCApmenoC/usr/lib/qt6/plugins/platforms/../../../libQt6XcbQpa.so.6(+0x58f90) [0x733751d29f90]
#25  /tmp/.mount_FreeCApmenoC/usr/bin/../lib/./libglib-2.0.so.0(+0x5bde6) [0x733753506de6]
#26  /tmp/.mount_FreeCApmenoC/usr/bin/../lib/./libglib-2.0.so.0(+0x5f0a7) [0x73375350a0a7]
#27  /tmp/.mount_FreeCApmenoC/usr/bin/../lib/./libglib-2.0.so.0(g_main_context_iteration+0x2e) [0x73375350a81e]
#28  0x733755cf6b12 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /tmp/.mount_FreeCApmenoC/usr/bin/../lib/libQt6Core.so.6+0x72
#29  0x733755f9747c in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) from /tmp/.mount_FreeCApmenoC/usr/bin/../lib/libQt6Core.so.6+0x25c
#30  0x733755f977da in QCoreApplication::exec() from /tmp/.mount_FreeCApmenoC/usr/bin/../lib/libQt6Core.so.6+0x9a
#31  0x73375ba532dc in Gui::Application::runApplication() from /tmp/.mount_FreeCApmenoC/usr/bin/../lib/libFreeCADGui.so+0xc4c
#32  /tmp/.mount_FreeCApmenoC/usr/bin/freecad(+0x9f65) [0x55cfd0c58f65]
#33  /lib/x86_64-linux-gnu/libc.so.6(+0x2a1ca) [0x73375542a1ca]
#34  /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x8b) [0x73375542a28b]
#35  /tmp/.mount_FreeCApmenoC/usr/bin/freecad(+0x9059) [0x55cfd0c58059]
```

### Development version About Info (in Safe Mode)

```shell
OS: KDE neon User Edition (KDE/plasma/wayland)
Architecture: x86_64
Version: 1.2.0dev.20260401 (Git shallow) AppImage
Build date: 2026/04/01 04:43:57
Build type: Release
Branch: (HEAD detached at 33dcd31f5)
Hash: 33dcd31f5e2175e7dcdfd3caf1d9d86440919bfc
Python 3.11.14, Qt 6.8.3, Coin 4.0.8, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.3.0, IfcOpenShell 0.8.2, OCC 7.8.1
Locale: Italian/Italy (it_IT)
Stylesheet/Theme/QtStyle: OpenLight.qss/OpenLight/
Navigation Style/Orbit Style/Rotation Mode: Touchpad/Free Turntable/Object center
Logical DPI/Physical DPI/Pixel Ratio: 96/141.951/1
Installed mods:
  * Curves workbench 0.6.63 (Disabled)
  * Fasteners Workbench 0.5.43
  * Fasteners Workbench 0.5.38 (Disabled)
  * PieMenu 1.12.1
  * OpenTheme 2025.5.20
  * Display Tools 1.0.0
  * freecad.gears workbench 1.3.0 (Disabled)
  * SheetMetal Workbench 0.7.22 (Disabled)
  * freecad.gears workbench 1.3.0
  * SheetMetal Workbench 0.7.55
  * Assembly4 0.50.18 (Disabled)
  * Curves workbench 0.6.70
  * Assembly3 0.12.2
  * Gridfinity Workbench 0.11.9
  * PieMenu 1.12.0 (Disabled)
  * Assembly4 0.60.2
  * Curved Shapes 1.0.13
```

### Last known good version (optional)

```shell

```

### LINKED ISSUE #29148: Sketcher: Cannot edit sketch from external file (Regression)
### Problem description

Regression, it's not longer possible to edit a sketch from an external file. Most likely caused by the per document undo stack (https://github.com/FreeCAD/FreeCAD/pull/21978).

Probably causing https://github.com/FreeCAD/FreeCAD/issues/28989

https://github.com/user-attachments/assets/29c14f86-f83c-409c-a35a-7593f6ab6352

File:
https://github.com/user-attachments/assets/ba50cb6f-bcc8-40e8-883c-347d248e7223

### Workbench affected?

Sketcher

### Steps to reproduce

Open Asy Test.fcstd
Double click the sketch in the link.
Try to exit edit mode.

### Expected behavior

.

### Actual behavior

.

### Development version About Info (in Safe Mode)

```shell
.
```

### Last known good version (optional)

```shell

```

### PR DESCRIPTION
**Pull request by theo-vt**
The sketcher's TaskDialog would get it's associated view from the sketch object in the sketch's source document, which made the sketcher's source document the active document for a fraction of a second, just in time to get bound to the sketcher' taskview

The assembly deactivation pattern was wrongly refactored and would do a use after free in that situation

## Issues

Fix #28989 
Fix #29148

### CODE REVIEW

**Comment by theo-vt** [comment]
@FEA-eng hi! could you test this if you have time?

**Comment by FEA-eng** [comment]
> @FEA-eng hi! could you test this if you have time?

Actually, I wanted to test it yesterday, but I couldn't reproduce the issue - I've noticed different behavior that I've mentioned [here](https://github.com/FreeCAD/FreeCAD/issues/29148#issuecomment-4229309180).

**Comment by theo-vt** [comment]
This should be fixed as well!

**Comment by FEA-eng** [comment]
Regarding the first issue (#28989), I don't get Access Violation with this PR, but I got this:

```
21:28:58  Illegal storage access...
21:28:58  pyException: Traceback (most recent call last):
  File "<string>", line 5, in <module>
  File "D:\FreeCAD_dev\FreeCAD-src\.pixi\envs\default\Library\Mod\Show\mTempoVis.py", line 507, in activateWorkbench
    self.modify(Workbench(wb_name))
  File "D:\FreeCAD_dev\FreeCAD-src\.pixi\envs\default\Library\Mod\Show\mTempoVis.py", line 172, in modify
    detail.apply_data(detail.data)
  File "D:\FreeCAD_dev\FreeCAD-src\.pixi\envs\default\Library\Mod\Show\SceneDetails\Workbench.py", line 46, in apply_data
    FreeCADGui.activateWorkbench(val)
<class 'OSError'>: SketcherWorkbench: Illegal storage access! Please save your work under a new file name and restart the application!
```

image

**Comment by FEA-eng** [comment]
I can't reliably reproduce the error reported above (may depend on the exact sequence of steps). Other problems I've noticed are disappearing Sketcher toolbars when editing that sketch and a crash when closing the file, but I think those are the other existing regressions from the multidocument feature.

**Comment by theo-vt** [comment]
I can't seem to reproduce any of those issues arg

it crashes when closing the 3442 file or the 34 file? And while in sketch edit?

**Comment by FEA-eng** [comment]
> it crashes when closing the 3442 file or the 34 file? And while in sketch edit?

The crash seems to be this known issue: #28506

So it can happen with pretty much any assembly file and I guess we can treat it as unrelated to this PR.

**Comment by FEA-eng** [comment]
The `Illegal storage access` happened one time, might be unrelated too.

To sum up, this PR seems to be fixing the first issue and I just can’t reproduce the second one.

File: src/Mod/Assembly/Gui/ViewProviderAssembly.h [hunk 1]
```diff
@@ -127,10 +127,6 @@ class AssemblyGuiExport ViewProviderAssembly: public Gui::ViewProviderPart,
     void setEditViewer(Gui::View3DInventorViewer*, int ModNum) override;
     bool isInEditMode() const;
 
-    void setActive(bool active) override;
```
Comment (PaddleStroke) [inline src/Mod/Assembly/Gui/ViewProviderAssembly.h:130]: why are you removing this override? I have not tested but this is most likely breaking stuff

Comment (PaddleStroke) [reply src/Mod/Assembly/Gui/ViewProviderAssembly.h:130]: Erratum I just checked and found you are just reverting changes you made earlier. So it's fine :)

**Comment by PaddleStroke** [comment]
@theo-vt do you think this PR is also fixing https://github.com/FreeCAD/FreeCAD/issues/28506 ?

**Comment by theo-vt** [comment]
I was not able to reproduce that issue so I couldn't check :/

**Comment by PaddleStroke** [comment]
Ok, let's merge this PR and i'll check the other bug if it can still be replicated
