### PR TITLE
Gui: fix file dialog type filters being too long (fixes #23139)

### LINKED ISSUE #23139: UI/UX: Open document dialog box default supported format is very crowded with other file types
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Problem description

Greetings everyone! 

When you press File->Open the open document dialog box opens which has a default with ` supported formats ` includes even jpg files so if you have lots of files such as jpg or other file types you have to look for .FCstd files in a crowd or you have to switch to  Freecad Document.

My proposal is default file type  should be  `Freecad  Document`  (the file type most likely to be opened) also maybe we can remove  `Supported formats` option because it is a duplicate of the list. 

Image

### Full version info

```shell
OS: Windows 10 build 19045
Architecture: x86_64
Version: 1.1.0dev.14555 (Git shallow)
Build date: 2025/08/12 22:08:35
Build type: Release
Branch: main
Hash: 4195f7fee28e65b289b9390ff7a0deab49e81040
Python 3.11.13, Qt 6.8.3, Coin 4.0.3, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.3.0, IfcOpenShell 0.8.0, OCC 7.8.1
Locale: Turkish/Türkiye (tr_TR)
Navigation Style/Orbit Style/Rotation Mode: Blender/Trackball/Drag at cursor
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/fusion
Logical DPI/Physical DPI/Pixel Ratio: 96/81.5973/1
Installed mods: 
  * CurvedShapes 1.0.13
  * Curves 0.6.61
```

### Subproject(s) affected?

Core

### Anything else?

_No response_

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by ElementW**
#23139 shines the light on open/import/save/export dialog file type filters being too long, especially the wildcard `Supported formats` entry.

This PR rectifies this at the `FileDialog::get{Open,Save}FileName{,s}()` level to handle most cases, although parts of FC's code do not call this and use `QFileDialog` directly.

Uses the `QFileDialog::HideNameFilterDetails` flag to hide the actual extension filter lists, and runs all filters through a `formatFilter()` function to:
1. still show the extension list if it is deemed short enough (currently <= 128 chars in its original form, feedback welcome on that threshold)
2. deduplicate the extensions, as many have both lowercase and uppercase variants (only relevant on case-sensitive platforms)
   * this dedup is not flawless as it (as of right now anyway) does linear iteration over the extension filters and expects differing cases of the same ext to be contiguous, but most filter strings comply with this requirement anyway

The `FileDialog` functions used to force-unset the `HideNameFilterDetails` flag, I'm not quite sure why as AFAIU this flag is never set by default, nor used in FC. Setting it smoothes out platform differences [as outlined in a previous comment of mine](https://github.com/FreeCAD/FreeCAD/pull/23183#issuecomment-3199927048), and allows for this PR's behaviour.

## Issues
* #23139

This PR conflicts with #23183 on the account of solving the same issue.

## Before and After Images

image

image

### CODE REVIEW

**Comment by MisterMakerNL** [comment]
Looks nice!

**Comment by ElementW** [comment]
Argh, Qt 5 doesn't have `QStringView::slice()`, fixed that.

**Comment by xtemp09** [comment]
Today I saw twice something I haven't seen before in my life. I'm talking about usage of `QSet<QByteArray>` and `std::unique_ptr<QString>` instead of just `QString`. 




What is the purpose of `std::unique_ptr<QString>`?

**Comment by ElementW** [comment]
@xtemp09 Only conditionally creating the `QString` if the `selectedFilter` is passed. To be honest I kind of just winged it and should've relied on the default QString constructor and use `formattedSelectedFilter.isEmpty() ? nullptr : &formattedSelectedFilter`, as the constructor is actually empty and inlined, which I didn't know when writing this; I'm used to string types being direly inefficient even when empty.
I'll yeet that, the heap alloc overhead is greater than just the default init.

Edit: neeeevermind there's [actually no semantic difference between passing a null and an empty](https://github.com/qt/qtbase/blob/c28a574b6cda65c99c6ac8551b7976113d391cda/src/widgets/dialogs/qfiledialog.cpp#L2488), so `&formattedSelectedFilter` will do. So much for Qt's API surface making sense, why is that even a pointer, this should be a const reference with default init.

**TLDR:** brain fart + pointers bad.

**Comment by ElementW** [comment]
* Update to use `QStringLiteral` where relevant.
* Since this commit series adds `FileDialog::get{Open,Save}FileName{,s}()` variants with a `QStringList` filter list, add a commit to deprecate the flat list version, and fixup call sites using this older variant.

An argument could be made that a popular subset of extensions for long entries like `Image formats` should be shown. Should I try adding this? This might require some additional non-trivial refactoring to allow for that in a clean way.

**Comment by xtemp09** [comment]
> * Update to use `QStringLiteral` where relevant.


You rewrote some fragments, you left some unchanged. Is there a system?


```cpp
QStringList filterList;
filterList << QString::fromUtf8(QT_TR_NOOP("Image files (*.jpg *.jpeg *.png *.bmp)"));
filterList << QString::fromUtf8(QT_TR_NOOP("All files (*)"));
```


```cpp
QStringList(QString::fromUtf8(QT_TR_NOOP("Template (*.svg)"))));
```



Do these places not require update?



----





Why did you mark the functions as deprecated? Are you planning on removing them?

**Comment by ElementW** [comment]
> You rewrote some fragments, you left some unchanged. Is there a system?

I only updated parts of code I touched (specifically, those where QLatin1String was involved), this is not a general refactor/code cleanup.

> Do these places not require update?

Please do your due diligence and read the commit message associated with those changes. Fixing i18n and other code idiosyncrasies at the call sites is not within the scope of this PR.

~~_At least yet._ I have pending changes to enable showing a select list of extension filters which changes the `QStringList` into a list of structs, but am unsure if I should include these in this PR.~~
These changes are turning out to be a larger refactor of file format handling and I'll probably merge them with my initial work on fixing #16431, #23123 and #23124.

> Why did you mark the functions as deprecated? Are you planning on removing them?

The call to remove them is not mine to make, I do not know FC nearly enough to confidently remove functions in a `GuiExport` class.

**Comment by Connor9220** [comment]
Need to add support for *.fctb files.  These are FreeCAD Toolbit Files that are used in the CAM workbench.  (They're the same as FCStd but with a different extension to make it easier to distinguish they're use.)

**Comment by ElementW** [comment]
@Connor9220  Adding format associations is not within the scope of this PR (at most only touches existing import/export strings to fix inconsistencies). If you want to add that to the general open/import/save/export dialogs, `FreeCAD.addImportType()` should be added in the scripts.

Plus, [the CAM WB uses QFileDialog directly](https://github.com/FreeCAD/FreeCAD/blob/e2346dabd6080aafe0622a80524067eafa67f8f1/src/Mod/CAM/Path/Tool/assets/ui/filedialog.py#L85) so that's outside of my control anyway. I'm already working on a follow-up PR to improve on the same file dialogs as here, and once done I may look into unifying the APIs the WBs uses, but not now.

**Comment by Connor9220** [comment]
> @Connor9220 Adding format associations is not within the scope of this PR (at most only touches existing import/export strings to fix inconsistencies). If you want to add that to the general open/import/save/export dialogs, `FreeCAD.addImportType()` should be added in the scripts.
> 
> Plus, [the CAM WB uses QFileDialog directly](https://github.com/FreeCAD/FreeCAD/blob/e2346dabd6080aafe0622a80524067eafa67f8f1/src/Mod/CAM/Path/Tool/assets/ui/filedialog.py#L85) so that's outside of my control anyway. I'm already working on a follow-up PR to improve on the same file dialogs as here, and once done I may look into unifying the APIs the WBs uses, but not now.

It use to do this though. I'm saying that this extension was removed.  We only open these up through Part Design WB.  It's just has a different extension. 

Okay, I'm mistaken, I though older versions did this.

**Comment by ElementW** [comment]
Rebased on latest `main`.

**Comment by MisterMakerNL** [comment]
Just a question, about the image formats, have you split off the vector files? 
Because otherwise I think it could be confusing since some vector files format are not images, like DXF.

**Comment by ElementW** [comment]
@MisterMakerNL Nope, the format list building is still untouched, i.e. a simple iteration over
https://github.com/FreeCAD/FreeCAD/blob/5c73859134e3dfb00034eafc943c529fe971a2af/src/Gui/StartupProcess.cpp#L401
You make a fair point, but it kind of falls flat in these file dialogs' case: every format that's handled *if you select "Image formats"* will invoke Qt's image reader which produces, well, *images*. Raster ones. Even if the format is not really an image per se. Vector imports as geometry/drawings are handled by their own filter selector (e.g. "SVG as geometry") instead, and if you drag&drop one such file onto FC you're explicitly given the choice to resolve the ambiguity.

(And unfortunately even using `QImageReader::supportedMimeTypes()` with `QMimeType` we can't figure out whether a supported import format is vector or not, so our only option would be having a built-in list of vector formats like you did in your PR, which if I'm honest I'm not too fond of)

**Comment by MisterMakerNL** [comment]
> @MisterMakerNL Nope, the format list building is still untouched, i.e. a simple iteration over
> 
> https://github.com/FreeCAD/FreeCAD/blob/5c73859134e3dfb00034eafc943c529fe971a2af/src/Gui/StartupProcess.cpp#L401
> 
> You make a fair point, but it kind of falls flat in these file dialogs' case: every format that's handled _if you select "Image formats"_ will invoke Qt's image reader which produces, well, _images_. Raster ones. Even if the format is not really an image per se. Vector imports as geometry/drawings are handled by their own filter selector (e.g. "SVG as geometry") instead, and if you drag&drop one such file onto FC you're explicitly given the choice to resolve the ambiguity.
> 
> (And unfortunately even using `QImageReader::supportedMimeTypes()` with `QMimeType` we can't figure out whether a supported import format is vector or not, so our only option would be having a built-in list of vector formats like you did in your PR, which if I'm honest I'm not too fond of)

A real dirty fix would be too call it  "image/vector file formats"

**Comment by chennes** [comment]
Running this on Windows 11, I get the following error in the Report View
```
QWindowsNativeFileDialogBase::selectNameFilter: Invalid parameter 'Supported formats ( *.3DS *.3MF *.3ds *.3mf *.ASC *.ASMT *.AST *.BDF *.BMP *.BMS *.BREP *.BRP *.CNC *.CSG *.CSV *.CUR *.DAE *.DAT *.DWG *.DXF *.E57 *.EMN *.FCMacro *.FCMat *.FCScript *.FRD *.GC *.GCAD *.GCODE *.GIF *.GLB *.GLTF *.ICNS *.ICO *.IGES *.IGS *.INP *.IV *.JFIF *.JPEG *.JPG *.JSON *.MED *.MESHJSON *.MESHYAML *.NC *.NCC *.NGC *.OBJ *.OCA *.OFF *.PBM *.PCD *.PGM *.PLMXML *.PLY *.PNG *.PPM *.PVTU *.SHP *.SMF *.STEP *.STL *.STP *.STPZ *.SVG *.SVGZ *.TAP *.TGA *.TIF *.TIFF *.TXT *.UNV *.VRML *.VTK *.VTU *.WBMP *.WEBP *.WRL *.WRL.GZ *.WRZ *.XBM *.XDMF *.XLSX *.XML *.XPM *.YAML *.Z88 *.asc *.asmt *.ast *.bdf *.bmp *.bms *.brep *.brp *.cnc *.csg *.csv *.cur *.dae *.dat *.dwg *.dxf *.e57 *.emn *.fcmacro *.fcscript *.frd *.gc *.gcad *.gcode *.gif *.glb *.gltf *.icns *.ico *.ifc *.iges *.igs *.inp *.iv *.jfif *.jpeg *.jpg *.json *.med *.meshjson *.meshyaml *.nc *.ncc *.ngc *.obj *.oca *.off *.pbm *.pcd *.pgm *.plmxml *.ply *.png *.ppm *.pvtu *.py *.sh3d *.shp *.smf *.step *.stl *.stp *.stpZ *.stpz *.svg *.svgz *.tap *.tga *.tif *.tiff *.txt *.unv *.vrml *.vtk *.vtm *.vtu *.wbmp *.webp *.wrl *.wrl.gz *.wrz *.xbm *.xdmf *.xlsx *.xml *.xpm *.yaml *.z88)' not found in 'Supported formats ( *.3DS *.3MF *.3ds *.3mf *.ASC *.ASMT *.AST *.BDF *.BMP *.BMS *.BREP *.BRP *.CNC *.CSG *.CSV *.CUR *.DAE *.DAT *.DWG *.DXF *.E57 *.EMN *.FCMacro *.FCMat *.FCScript *.FRD *.GC *.GCAD *.GCODE *.GIF *.GLB *.GLTF *.ICNS *.ICO *.IGES *.IGS *.INP *.IV *.JFIF *.JPEG *.JPG *.JSON *.MED *.MESHJSON *.MESHYAML *.NC *.NCC *.NGC *.OBJ *.OCA *.OFF *.PBM *.PCD *.PGM *.PLMXML *.PLY *.PNG *.PPM *.PVTU *.SHP *.SMF *.STEP *.STL *.STP *.STPZ *.SVG *.SVGZ *.TAP *.TGA *.TIF *.TIFF *.TXT *.UNV *.VRML *.VTK *.VTM *.VTU *.WBMP *.WEBP *.WRL *.WRL.GZ *.WRZ *.XBM *.XDMF *.XLSX *.XML *.XPM *.YAML *.Z88 *.asc *.asmt *.ast *.bdf *.bmp *.bms *.brep *.brp *.cnc *.csg *.csv *.cur *.dae *.dat *.dwg *.dxf *.e57 *.emn *.fcmacro *.fcscript *.frd *.gc *.gcad *.gcode *.gif *.glb *.gltf *.icns *.ico *.ifc *.iges *.igs *.inp *.iv *.jfif *.jpeg *.jpg *.json *.med *.meshjson *.meshyaml *.nc *.ncc *.ngc *.obj *.oca *.off *.pbm *.pcd *.pgm *.plmxml *.ply *.png *.ppm *.pvtu *.py *.sh3d *.shp *.smf *.step *.stl *.stp *.stpZ *.stpz *.svg *.svgz *.tap *.tga *.tif *.tiff *.txt *.unv *.vrml *.vtk *.vtm *.vtu *.wbmp *.webp *.wrl *.wrl.gz *.wrz *.xbm *.xdmf *.xlsx *.xml *.xpm *.yaml *.z88), 3D Manufacturing Format (*.3mf) (*.3mf *.3MF), 3D Studio mesh (*.3ds) (*.3ds *.3DS), Alias Mesh (*.obj) (*.obj *.OBJ), Assembly Format (*.asmt) (*.asmt *.ASMT), Autodesk DWG 2D (*.dwg) (*.dwg *.DWG), Autodesk DXF 2D (*.dxf) (*.dxf *.DXF), BREP format (*.brep *.brp) (*.brep *.BREP *.brp *.BRP), Binary Mesh (*.bms) (*.bms *.BMS), Collada (*.dae) (*.dae *.DAE), Common airfoil data (*.dat) (*.dat *.DAT), Excel spreadsheet (*.xlsx) (*.xlsx *.XLSX), FEM mesh Fenics (*.xml *.xdmf) (*.xml *.XML *.xdmf *.XDMF), FEM mesh YAML/JSON (*.meshyaml *.meshjson *.yaml *.json) (*.meshyaml *.MESHYAML *.meshjson *.MESHJSON *.yaml *.YAML *.json *.JSON), FEM mesh Z88 (*.txt) (*.txt *.TXT), FEM mesh formats (*.bdf *.dat *.inp *.med *.unv *.vtk *.vtu *.pvtu *.z88) (*.bdf *.BDF *.dat *.DAT *.inp *.INP *.med *.MED *.unv *.UNV *.vtk *.VTK *.vtu *.VTU *.pvtu *.PVTU *.z88 *.Z88), FEM result CalculiX (*.frd) (*.frd *.FRD), FEM result VTK (*.vtk *.vtu *.pvtu *.vtm) (*.vtk *.VTK *.vtu *.VTU *.pvtu *.PVTU *.vtm *.VTM), FEM result Z88 displacements (*.txt) (*.txt *.TXT), FreeCAD Material Card (*.FCMat) (*.FCMat), GCode (*.nc *.gc *.ncc *.ngc *.cnc *.tap *.gcode) (*.nc *.NC *.gc *.GC *.ncc *.NCC *.ngc *.NGC *.cnc *.CNC *.tap *.TAP *.gcode *.GCODE), IDF emn file File Type (*.emn) (*.emn *.EMN), IGES format (*.iges *.igs) (*.iges *.IGES *.igs *.IGS), Image formats (*.bmp *.BMP *.cur *.CUR *.gif *.GIF *.icns *.ICNS *.ico *.ICO *.jfif *.JFIF *.jpeg *.JPEG *.jpg *.JPG *.pbm *.PBM *.pgm *.PGM *.png *.PNG *.ppm *.PPM *.svg *.SVG *.svgz *.SVGZ *.tga *.TGA *.tif *.TIF *.tiff *.TIFF *.wbmp *.WBMP *.webp *.WEBP *.xbm *.XBM *.xpm *.XPM ), Industry Foundation Classes (*.ifc) (*.ifc), Inventor V2.1 (*.iv) (*.iv *.IV), Object File Format Mesh (*.off) (*.off *.OFF), Open CAD Format (*.oca *.gcad) (*.oca *.OCA *.gcad *.GCAD), OpenSCAD CSG Format (*.csg) (*.csg *.CSG), PLMXML files (*.plmxml) (*.plmxml *.PLMXML), Point formats (*.asc *.pcd *.ply *.e57) (*.asc *.ASC *.pcd *.PCD *.ply *.PLY *.e57 *.E57), Python (*.py *.FCMacro *.FCScript) (*.py *.FCMacro *.fcmacro *.FCScript *.fcscript), STEP with colors (*.step *.stp) (*.step *.STEP *.stp *.STP), STEPZ Zip File Type (*.stpZ) (*.stpZ *.stpz *.STPZ), STL Mesh (*.stl *.ast) (*.stl *.STL *.ast *.AST), SVG as geometry (*.svg) (*.svg *.SVG), Shapefile (*.shp) (*.shp *.SHP), Simple Model Format (*.smf) (*.smf *.SMF), Spreadsheet formats (*.csv) (*.csv *.CSV), Stanford Triangle Mesh (*.ply) (*.ply *.PLY), SweetHome3D (*.sh3d) (*.sh3d), VRML V2.0 (*.wrl *.vrml *.wrz *.wrl.gz) (*.wrl *.WRL *.vrml *.VRML *.wrz *.WRZ *.wrl.gz *.WRL.GZ), Wavefront OBJ - Arch module (*.obj) (*.obj *.OBJ), glTF (*.gltf *.glb) (*.gltf *.GLTF *.glb *.GLB), All files (*.*) (*.*)'.
```
And that entire string gets displayed as the first entry in the "Import" or "Open" dialog (obviously totally bonkers, presumably a bug).

**Comment by ElementW** [comment]
@chennes Argh, I do not have a Windows machine to test on right now, I'll spin up a VM and have a look. Hopefully the error is due to some actually invalid string from my end and not Qt's inability to parse filter strings with multiple `(...)` per entry. Failing that, falling back to Qt built-in dialogs is still an option, although subpar.
(inbefore I start rewriting the entire native dialog handling...)

**Comment by chennes** [comment]
Before you start anything drastic, drop me a line and we can try to do some team debugging. Are you on Discord, Telegram, Matrix, etc.?

**Comment by ElementW** [comment]
I won't start drastic things if I dont need to. I'm mostly on Telegram but also occasionally on Discord.

**Comment by chennes** [comment]
The FreeCAD Discord is pretty active and a good place to go for help - I'm @chennes there too. @chris_hennes on Telegram, though it's been awfully spammy lately so I block new contacts by default.

**Comment by kadet1090** [comment]
Hi! This PR has seemingly a lot of conflicts due to recent update to the code style. Unfortunately in case of that PR formatting changes are not the only conflicts so I couldn't update it automatically. Instruction on how to best deal with such massive automatic changes to the codebase is here: https://github.com/FreeCAD/FreeCAD/discussions/25217. 

While it would be awesome for you to do all the steps necessary, if you resolve only conflicts before changes that is fine too - I can take care of formatting changes. In case of any troubles, feel free to ping me here (or on any other platform) and I'll try to help.

**Comment by maxwxyz** [comment]
@ElementW ping for conflicts (resolution provided above)

**Comment by ElementW** [comment]
`pre-commit` fixing a file I did not touch, great. So much for having it as merge policy onto `main`.

**Comment by ElementW** [comment]
@chennes Looks like the error you have comes from FC remembering the last filter set you used, and said set came from a previous version where `*.VTM` was missing from the *Supported formats* entry. I believe this happens even before my changes, and is a problem that will persist until text-based filtering is phased out (which is what I set out to do a few months ago but, thanks ADHD, ended up leaving on the side).

**Comment by chennes** [comment]
Here's what it looks like for me (safe mode):
Screenshot 2026-03-21 204437

So neither the "All supported formats" nor "Image files" is getting trimmed (I think those are the only two we'd expect to be here).

```
OS: Windows 11 build 26200
Architecture: x86_64
Version: 1.2.0dev.45858 (Git)
Build date: 2026/03/21 22:25:34
Build type: RelWithDebInfo
Branch: fix/file-dialog-long-filters
Hash: 09f809d3355366b18ef7d4dd556775cd64778e49
Python 3.14.2, Qt 6.10.1, Coin 4.0.6, Vtk 9.5.2, boost 1_90, Eigen3 5.0.1, PySide 6.10.1
shiboken 6.10.1, SMESH 7.7.1.0, xerces-c 3.2.5, IfcOpenShell 0.0.0, OCC 7.9.3
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: FreeCAD.qss/FreeCAD Light/
Navigation Style/Orbit Style/Rotation Mode: CAD/Rounded Arcball/Window center
Logical DPI/Physical DPI/Pixel Ratio: 96/107.975/1.5
```

File: src/Gui/FileDialog.cpp [hunk 1]
```diff
@@ -410,6 +735,24 @@ QString FileDialog::getOpenFileName(
...
+QString FileDialog::getOpenFileName(
+    QWidget* parent,
+    const QString& caption,
+    const QString& dir,
+    const QStringList& filters,
+    QString* selectedFilter,
+    Options options
+)
+{
+    qWarning() << "openfilename filters" << filters;
```
Comment (ElementW) [inline src/Gui/FileDialog.cpp]: Reminder to self: remove this when rebasing.

**Review by maxwxyz — APPROVED** [review]
Works.

Before:

Image

After:

Image

**Comment by kadet1090** [comment]
Tested on linux too! Thank you so much for your effort and amazing blog posts about it!
