### PR TITLE
App: fix removing object while recomputing

### LINKED ISSUE #9912: [Problem] Regression: When expanding a Draft Link Array after previously shrinking, object instances are missing
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.21 (Development)

### Full version info

```shell
[code]
OS: Linux Mint 20.3 (X-Cinnamon/cinnamon)
Word size of FreeCAD: 64-bit
Version: 0.21.0.33510 (Git)
Build type: Release
Branch: master
Hash: 7fb1ca55eb6fe5260e4393eba4eba3b6426e84e3
Python 3.8.10, Qt 5.12.8, Coin 4.0.0, Vtk 7.1.1, OCC 7.7.1
Locale: English/United Kingdom (en_GB)
Installed mods: 
  * Silk 0.1.3
  * A2plus
  * Defeaturing 1.2.0
  * CurvedShapes 1.0.4
  * MakerWorkbench 1.0.1
  * freecad.gears 1.0.0
  * Curves 0.6.8
  * toSketch 1.0.1
  * AirPlaneDesign 0.4.0
  * fasteners 0.4.56
  * sheetmetal 0.2.63
[/code]
```

### Subproject(s) affected?

Draft

### Problem description

Open the attached project file and run the following in the Python Console:

```
FreeCAD.getDocument('expanded_array_count_issue').getObject('Array').NumberX = 6
FreeCAD.activeDocument().recompute(None,True,True)
FreeCAD.getDocument('expanded_array_count_issue').getObject('Array').NumberX = 24
FreeCAD.activeDocument().recompute(None,True,True)
```

This is the equivalent to a user shrinking then expanding the Link Array. This results in mssing Link objects and the following output in the Report View:
```

11:04:06  7.8e-08 Tree.cpp(304): [ComboView] duplicate child item expanded_array_count_issue#Array.Array_i18
11:04:06  5.4159e-05 Tree.cpp(304): [ComboView] duplicate child item expanded_array_count_issue#Array.Array_i19
11:04:06  6.2731e-05 Tree.cpp(304): [ComboView] duplicate child item expanded_array_count_issue#Array.Array_i20
11:04:06  6.9538e-05 Tree.cpp(304): [ComboView] duplicate child item expanded_array_count_issue#Array.Array_i21
11:04:06  7.6149e-05 Tree.cpp(304): [ComboView] duplicate child item expanded_array_count_issue#Array.Array_i22
11:04:06  8.268e-05 Tree.cpp(304): [ComboView] duplicate child item expanded_array_count_issue#Array.Array_i23
```
[expanded_array_count_issue.FCStd.zip](https://github.com/FreeCAD/FreeCAD/files/12026720/expanded_array_count_issue.FCStd.zip)

### Anything else?

See forum discussion: https://forum.freecad.org/viewtopic.php?t=79566

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by realthunder**
Fixes #9912

### CODE REVIEW

File: src/App/Document.cpp [hunk 1]
```diff
@@ -2826,18 +2826,24 @@ int Document::recompute(const std::vector<App::DocumentObject*> &objs, bool forc
...
+    for (auto doc : GetApplication().getDocuments()) {
+        decltype(doc->d->pendingRemove) objs;
+        objs.swap(doc->d->pendingRemove);
+        for(auto &o : objs) {
+            try {
+                if (auto obj = o.getObject()) {
+                    obj->getDocument()->removeObject(obj->getNameInDocument());
+                }
+            } catch (Base::Exception & e) {
+                e.ReportException()
```
Comment (Syres916) [inline src/App/Document.cpp:2842]: Thanks @realthunder , I had to add the semi colon at the end of this line in order to compile:
`                e.ReportException();`

Comment (realthunder) [reply src/App/Document.cpp:2842]: Oops

**Review by Syres916 — APPROVED** [review]
