### PR TITLE
Sketcher: make line type settings visible on dark theme, fix #29305

### LINKED ISSUE #29305: Sketcher: Line Type previews are not visible in Preferences > Appearance when using dark theme
### Problem description

Image

In **Sketcher > Preferences > Appearance**, the **Line Type** previews are not visible / barely visible when using a **dark theme**.

The dropdown/list opens, but the line style samples cannot be seen properly, which makes it impossible to distinguish the available line types from the preview.

This appears to be a UI visibility / contrast issue related to dark theme styling.

### Workbench affected?

Sketcher

### Steps to reproduce

Steps to reproduce
Start FreeCAD with a dark theme enabled
Open Edit > Preferences
Go to Sketcher > Appearance
Open the Line Type selector
Observe that the preview samples are not visible or are too dark to distinguish

### Expected behavior

The line type preview samples should be clearly visible in the selector, regardless of whether FreeCAD is using a light or dark theme.

### Actual behavior

The selector opens, but the preview area looks empty or nearly empty because the line samples do not have enough contrast against the dark background.

### Development version About Info (in Safe Mode)

```shell
OS: Windows 11 build 26100
Architecture: x86_64
Version: 1.2.0dev.20260324 (Git shallow)
Build date: 2026/03/24 17:14:33
Build type: Release
Branch: (HEAD detached at 1bc5980a7)
Hash: 1bc5980a7ff302a55c617181e774cd5cd2a9443a
Python 3.11.15, Qt 6.8.3, Coin 4.0.8, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.3.0, IfcOpenShell 0.8.2, OCC 7.8.1
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: FreeCAD.qss/FreeCAD Dark/
Navigation Style/Orbit Style/Rotation Mode: SiemensNX/Rounded Arcball/Window center
Logical DPI/Physical DPI/Pixel Ratio: 96/141.951/1
```

### Last known good version (optional)

```shell

```

### PR DESCRIPTION
**Pull request by ElementW**
* Fixes #29305

Had to use a QStyledItemDelegate to make the lines render properly in the dropdown, at least on Linux.

### Before

image

Windows image courtesy of @Reqrefusion:
Image

### After

image

### CODE REVIEW

**Comment by FEA-eng** [comment]
I don't see the difference on Windows:

image

Also, should it affect these too?

image

**Comment by ElementW** [comment]
@FEA-eng Oh, weird. Maybe the theme palette isn't populated the same on Windows (I ask for `QPalette::WindowText` to match the color of the text that would normally be there)?

And yes, the grid lines dropdowns should also be affected.

**Comment by ElementW** [comment]
Even weirder, in my local build (pixi-based) it works on Windows:
image

**Comment by chennes** [comment]
Maybe @kadet1090 can lend a hand?

**Comment by Syres916** [comment]
In TechDraw which we know works across all platforms, masking of the black pixels is used:

```
QIcon DrawGuiUtil::maskBlackPixels(QIcon itemIcon, QSize iconSize, QColor textColor)
{
    QPixmap originalPix = itemIcon.pixmap(iconSize, QIcon::Mode::Normal, QIcon::State::On);
    QPixmap filler(iconSize);
    filler.fill(QColor(textColor));
    filler.setMask(originalPix.createMaskFromColor(Qt::black, Qt::MaskOutColor));
    return filler;
}
```

**Comment by ElementW** [comment]
@FEA-eng Through trials and tribulations I have compiled FreeCAD with the LibPack instead of Pixi, and still cannot reproduce. Are you running a Qt5 build?
**EDIT:** built with Qt 5 on Linux, couldn't reproduce either.

@Syres916 The masking thing is smart but does not help here, the transparency & palette replacement isn't the issue, the base color is. As a matter of fact, TechDraw's theming logic is so hilariously bad that it fails to understand I'm on *the default dark theme*, and so the `isStyleSheetDark()` if prongs aren't even taken, resulting in black graphics:
image
Plus this is one such case where having to switch on the theme being dark or not is a major code smell to me: we have theme/color palettes for a reason and those graphics should be of the same color as the text, no custom logic required.

**Comment by ElementW** [comment]
Ok I figured it out. On both Windows and Linux the palette you get on construction depends on system theme (incl. text color), not FreeCAD theme. You only get the actual palette when the styles are applied, i.e. after the `QWidget` or its style specifically has been polished, which is a concept I didn't know about.

**Comment by ElementW** [comment]
@FEA-eng I think I fixed the colors for good. Can you retest?

**Comment by FEA-eng** [comment]
> @FEA-eng I think I fixed the colors for good. Can you retest?

Now it's ok, thanks.

image
image

**Review by FEA-eng — APPROVED** [review]
@maxwxyz Tested, fixes the issue.

**Comment by Reqrefusion** [comment]
Image

The issue appears to be resolved in Windows 11.

File: src/Mod/Sketcher/Gui/SketcherSettings.cpp [hunk 1]
```diff
@@ -43,48 +44,72 @@ using namespace SketcherGui;
...
+        painter.drawLine(0, mid, size.width(), mid);
+        painter.end();
+
+        return px;
     }
+};
 
-    return dashPattern;
-}
+static constexpr std::array<PenStyle, 7> PenStyles {{
```
Comment (kadet1090) [inline src/Mod/Sketcher/Gui/SketcherSettings.cpp]: can we use `auto` and `std::to_array` here? Now you need to update the count manually if pattern is added or removed.

**Review by kadet1090 — APPROVED** [review]

File: src/Mod/Sketcher/Gui/SketcherSettings.cpp (hunk 1 above)
Comment (ElementW) [reply src/Mod/Sketcher/Gui/SketcherSettings.cpp]: I always forgor `to_array` is a thing :skull:

**Comment by ElementW** [comment]
Rebased on main and switched `PenStyles` to being built with `std::to_array`.
