### PR TITLE
[TD]fix view loses dimensions (fix #19968)

### LINKED ISSUE #19968: [TD]Dimensions lose connection to View when adding additional views
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Problem description

When a projection group is reverted to a single view by removing the secondary views, any dimensions attached to the "front" view will lose their connection to the parent view and appear in the bottom left corner of the page.

Closing the Page tab and reopening the Page will restore the connection.   There is a missing call to fixSceneDependencies somewhere.

Original report is here: https://forum.freecad.org/viewtopic.php?t=95281

### Full version info

```shell
OS: Linux Mint 21.2 (X-Cinnamon/cinnamon/xcb)
Architecture: x86_64
Version: 1.1.0dev.40456 (Git)
Build type: debug
Branch: BlackWindowFlash
Hash: 0c65673a6fd2421be8fbe613116077120adea068
Python 3.10.12, Qt 5.15.2, Coin 4.0.0, Vtk 7.1.1, OCC 7.8.0
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
Logical/physical DPI: 115/141.585
Installed mods: 
  * fasteners 0.5.21
```

### Subproject(s) affected?

None

### Anything else?

_No response_

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by WandererFan**
This PR implements a fix for issue #19968.

### CODE REVIEW

File: src/Mod/TechDraw/Gui/TaskProjGroup.cpp [hunk 1]
```diff
@@ -379,6 +379,11 @@ void TaskProjGroup::turnProjGroupToView()
     view = viewPart;
     multiView = nullptr;
 
+    auto* vpView = static_cast<ViewProviderViewPart*>(activeGui->getViewProvider(viewPart));
+    if (vpView) {
+        vpView->fixSceneDependencies();
+    }
+
```
Comment (benj5378) [inline src/Mod/TechDraw/Gui/TaskProjGroup.cpp:386]: https://github.com/FreeCAD/FreeCAD/blob/9aa27d7dc3d80aa86daf361d44a43e50e4617ebc/src/Mod/TechDraw/Gui/TaskProjGroup.cpp#L373-L385

No need to cast twice, suggestion:

```cpp
    viewPart->recomputeFeature();
    auto* vp = static_cast<ViewProviderProjGroupItem*>(activeGui->getViewProvider(viewPart));
    if (vp) {
        vp->updateIcon();
        vp->fixSceneDependencies();
    }
    view = viewPart;
    multiView = nullptr;
```

**Review by benj5378 — APPROVED** [review]
