### PR TITLE
Fem: Handle single value field - fixes #14022

### LINKED ISSUE #14022: FEM: Results pipeline can't handle cases when output has a single value in the whole model
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Sometimes (usually in fundamental tests), the simulation result is uniform in the whole model. For example, in the case of a cube supported on 3 orthogonal faces (with their normal displacements fixed) and pulled on another side. Then there's a single value of stress everywhere. The results pipeline can't handle such cases. It throws an error:

`<Exception> Maximum must be higher than minimum`

and doesn't display this single value on the legend. It should look like this:

mises uniform

@marioalexis84 FYI

### Full version info

```shell
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37302 (Git)
Build type: Release
Branch: main
Hash: 0e24e121eb3e5708c380596e0a9fd583befac977
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: Polish/Poland (pl_PL)
```

### Subproject(s) affected?

FEM

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by marioalexis84**
Fixes #14022

@FEA-eng

### CODE REVIEW

**Comment by FEA-eng** [comment]
Nice, it works as expected.

**Review by FEA-eng — APPROVED** [review]

File: src/Mod/Fem/Gui/ViewProviderFemPostObject.cpp [hunk 1]
```diff
@@ -618,12 +618,24 @@ void ViewProviderFemPostObject::WritePointData(vtkPoints* points,
...
 }
 
-void ViewProviderFemPostObject::setRangeOfColorBar(double min, double max)
+void ViewProviderFemPostObject::setRangeOfColorBar(float min, float max)
 {
     try {
         if (min >= max) {
-            min = max - 10 * std::numeric_limits<double>::epsilon();
-            max = max + 10 * std::numeric_limits<double>::epsilon();
+            float eps = std::numeric_limits<float>::epsilon();
```
Comment (chennes) [inline src/Mod/Fem/Gui/ViewProviderFemPostObject.cpp:625]: Can you add a comment explaining what this code is trying to accomplish? It seems like a lot of complexity for what (in the code) looks like an input error.

Comment (marioalexis84) [reply src/Mod/Fem/Gui/ViewProviderFemPostObject.cpp]: Comment added.
Basically, the code handles the case of min value equal to max value, and also the case where min is expected to be equal to max but turns out to be greater due to floating point error.
