### PR TITLE
[TechDraw]Detail highlight drag (fix #21828)

### LINKED ISSUE #21828: TechDraw: Detail Highlight Drag
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Problem description

Problem originally reported here: https://forum.freecad.org/viewtopic.php?t=96310

Dragging the highlight circle on the base view of a detail without going through the "Drag Highlight" fails to update the DrawViewDetail feature properly.

### Full version info

```shell
v1.1.0dev
```

### Subproject(s) affected?

TechDraw

### Anything else?

_No response_

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by WandererFan**
This PR implements a fix for issue #21828.  Specifically, it:

- eliminates the conflict between the dragable highlight on base views and the update process in TaskDetail
- uses DrawView::isProjGroupItem() instead of dynamic_cast or isDerivedFrom<>() to determine if a views belongs to a projection group.  This eliminates the spurious "ProjectionGroup is confused" message.
- implements snapping of highlights to the closest vertex in the TaskDialog drag highlight process.

### CODE REVIEW

**Comment by WandererFan** [comment]
2 new preferences for highlight snapping:

SnapHighlightPrefs

File: src/Mod/TechDraw/Gui/TaskDetail.cpp [hunk 1]
```diff
@@ -271,27 +264,35 @@ void TaskDetail::setUiFromFeat()
     ui->qsbRadius->setValue(radius);
     ui->qsbScale->setDecimals(decimals);
     ui->cbScaleType->setCurrentIndex(ScaleType);
-    if (ui->cbScaleType->currentIndex() == 2) // only if custom scale
+    if (ui->cbScaleType->currentIndex() == 2) { // only if custom scale
         ui->qsbScale->setEnabled(true);
-    else
+    } else {
```
Comment (benj5378) [inline src/Mod/TechDraw/Gui/TaskDetail.cpp]:
```suggestion
    }
    else {
```
I think linter is configured this way

Comment (WandererFan) [reply src/Mod/TechDraw/Gui/TaskDetail.cpp]: Yeah, I'm having arguments with Qt Creator about formatting.
