### PR TITLE
PartDesign: fix the range of the custom clearance of threads

### LINKED ISSUE #11912: [Problem] PartDesign/Hole feature threading clearance accepts only positive values
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

When trying to model a threaded rod it seems to be the easiest solution to create a threaded hole object and make a Boolean Cut with it on a proper sized cylinder. I we want to match the size of the threaded socket (or nut) and the rod, proper clearance is required.
The PartDesign/Hole feature has the clearance, but it accepts **only positive values** (which grows the hole size). I can type in negative value on the "Hole parameters" panel, and the view update shows the perfect (shrinked) result, but upon clicking the OK button the clearance sets back to 0,00.
This is a huge problem, because the shinked size threaded hole object could be used as a perfect cutting die for modelling the threaded rod.

### Full version info

```shell
[code]
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.21.1.33668 +26 (Git)
Build type: Release
Branch: (HEAD detached at 0.21.1)
Hash: f6708547a9bb3f71a4aaade12109f511a72c207c
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: Hungarian/Hungary (hu_HU)
Installed mods: 
  * A2plus
  * ExplodedAssembly
  * fasteners
  * fcgear
  * Manipulator
[/code]
```

### Subproject(s) affected?

None

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by alfrix**
fixes #11912 allowing a reasonable range around the target.

Notes:
* lowering the value further than 0.5mm will cause issues at the smaller threads, so it has been chosen as min
* typical 3D printing / FDM values are around +0.5mm so this should cover the case with margin to spare on the positive side (1mm).
* the taskpanel is now clamped to the chosen min/max values, so there is no more confusion of being allowed to enter a value that then gets rejected on accept.

### CODE REVIEW

**Comment by chennes** [comment]
@FreeCAD/cad-working-group can you please weigh in on these values?

**Comment by pierreporte** [comment]
The original issue was the inability to set a negative clearance for modeled threads. Does this issue implements that (but limits to -0.5 mm), or does it limit the positive clearance?

I understand that the min and max clearance values depend on the thread size, so maybe FreeCAD should compute these values and make the UI work with them?

**Comment by kadet1090** [comment]
@alfrix ^ bump

**Comment by alfrix** [comment]
> The original issue was the inability to set a negative clearance for modeled threads. Does this issue implements that (but limits to -0.5 mm), or does it limit the positive clearance?
> 
> I understand that the min and max clearance values depend on the thread size, so maybe FreeCAD should compute these values and make the UI work with them?

nothing really to implement, the ui set positive limits only, but that is just because it defaulted to that, the current limit is 0 to infinity, this PR limits it to 0.5mm to 1mm which seems reasonable, there is no practical reason to limit the positive side, we could let it be infinity if preferred.
regarding standards, this is totally out of the standards and it's usually used to account for material shrinkage on 3d printers, the usual values are 0.5mm or 0.6mm, but depends on the nozzle and material

**Comment by kadet1090** [comment]
So if I understand, this is pretty arbitrary limitation? I don't see a reason to put any limits on that unless we know that something above 0.5mm does not make sense and simply cannot be computed.

**Comment by alfrix** [comment]
> So if I understand, this is pretty arbitrary limitation? I don't see a reason to put any limits on that unless we know that something above 0.5mm does not make sense and simply cannot be computed.

we could just set numeric_limits lowest() and max() and let freecad do whatever...

i just chose reasonable values, since it seemed a bit silly to me that you could select M20 and a negative offset of -10 and you essentially had an M10 modeled, a mean you can input bigger negative numbers than the diameter and produce funky stuff, but it sometimes fails.
image

**Comment by kadet1090** [comment]
> i just chose reasonable values, since it seemed a bit silly to me that you could select M20 and a negative offset of -10 and you essentially had an M10 modeled, a mean you can input bigger negative numbers than the diameter and produce funky stuff, but it sometimes fails.

We should left to the users to choose what is reasonable and what is not - limiting what is possible without a strict need to do so almost always impacts some kind of edge (and usually not so edge) case where it would be useful. If we had some way of adding a soft-limit (that for example would trigger warning for that field displaying additional information that the value is outside of recommended values) then such limit would be fine. 

If there is a way to set the limits dynamically based on size or something like that and limit it to what can be computed then we should go with such limit, otherwise we should left it more open ended.

**Comment by alfrix** [comment]
> > i just chose reasonable values, since it seemed a bit silly to me that you could select M20 and a negative offset of -10 and you essentially had an M10 modeled, a mean you can input bigger negative numbers than the diameter and produce funky stuff, but it sometimes fails.
> 
> We should left to the users to choose what is reasonable and what is not - limiting what is possible without a strict need to do so almost always impacts some kind of edge (and usually not so edge) case where it would be useful. If we had some way of adding a soft-limit (that for example would trigger warning for that field displaying additional information that the value is outside of recommended values) then such limit would be fine.
> 
> If there is a way to set the limits dynamically based on size or something like that and limit it to what can be computed then we should go with such limit, otherwise we should left it more open ended.

it would be cool to have a system to change the color of the text in the spinbox to yellow as a warning, but at the moment there is no mechanism to do that.
so lowest to max it is

**Comment by pierreporte** [comment]
What about computing the min and max values for the given thread and use them for limiting the offset value dynamically?

**Comment by alfrix** [comment]
> What about computing the min and max values for the given thread and use them for limiting the offset value dynamically?

since this is a `Custom` property which means is up to the user, i'll have to agree with Kadet: _We should let the users choose what is reasonable and what is not_

**Comment by pierreporte** [comment]
The problem is to distinguish what is impossible from what is reasonable. There are definitely impossible values so my proposal is to remove them by computing the limits, so that the user is free to define any physically possible values for, regardless of manufacturability.

**Comment by alfrix** [comment]
> The problem is to distinguish what is impossible from what is reasonable. There are definitely impossible values so my proposal is to remove them by computing the limits, so that the user is free to define any physically possible values for, regardless of manufacturability.

impossible would be **near** 0 diameters, freecad cannot make holes of less than 170nm in my testing, Also we can validate the diameter to be positive and that would be reasonable because it will not flip weirdly.

File: src/Mod/PartDesign/App/FeatureHole.cpp [hunk 1]
```diff
@@ -541,8 +541,13 @@ const App::PropertyAngle::Constraints Hole::floatAngle = {
     1.0
 };
 // OCC can only create holes with a min diameter of 10 times the Precision::Confusion()
+// In practice less than 170nm will result in failure
 const App::PropertyQuantityConstraint::Constraints diameterRange
-    = {10 * Precision::Confusion(), std::numeric_limits<float>::max(), 1.0};
+    = {1700 * Precision::Confusion(), std::numeric_limits<float>::max(), 1.0};
```
Comment (kadet1090) [inline src/Mod/PartDesign/App/FeatureHole.cpp]: "In Practice" is not good enough measure for limits like that - it is still arbitrary. It can change over time so it's best to drop that change. It's not like "negative diameter" which simply does not exist and thus is not possible, or corner radii bigger than the side length. This simply captures current limit of CAD kernel that can be changed in later versions - it can improve, or be even more fragile and fail with different values. 

I don't see a good value from change like this, so it's better to drop it and only keep the later part.

```suggestion
const App::PropertyQuantityConstraint::Constraints diameterRange
    = {10 * Precision::Confusion(), std::numeric_limits<float>::max(), 1.0};;
```

**Review by kadet1090 — CHANGES_REQUESTED** [review]

File: src/Mod/PartDesign/App/FeatureHole.cpp (hunk 1 above)
Comment (alfrix) [reply src/Mod/PartDesign/App/FeatureHole.cpp]: understood, i'll drop the commit
