### PR TITLE
Toponaming: Missing getSubObject code in PartDesign::Body

### LINKED ISSUE #15145: FreeCADGui.Selection.getSelectionEx()[0].SubObjects broken for sketches
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

`FreeCADGui.Selection.getSelectionEx()[0].SubObjects` is broken for sketches, it always returns an empty tuple.

1. Create a sketch with some lines.
2. Close the sketch.
3. Select some of the edges from the sketch.
4. Paste `FreeCADGui.Selection.getSelectionEx()[0].SubObjects` in the Python console.

### Full version info

```shell
OS: Windows 8 build 9600
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38001 (Git)
Build type: Release
Branch: main
Hash: 1fc6da959b936a2999774a4fe5b4c4b12bf6ac8d
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: Dutch/Netherlands (nl_NL)
Installed mods:
```

### Subproject(s) affected?

Core

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by bgbsww**
Fix #15145.

### CODE REVIEW

File: src/Mod/Sketcher/App/SketchObject.cpp [hunk 1]
```diff
@@ -9734,10 +9737,60 @@ Part::TopoShape SketchObject::getEdge(const Part::Geometry *geo, const char *nam
     return shape;
 }
 
-Data::IndexedName SketchObject::checkSubName(const char *sub) const
-{
-    // FIXME: trivial implementation needs to be replaced with full logic
-    (void)sub;
+Data::IndexedName SketchObject::checkSubName(const char *sub) const{
```
Comment (chennes) [inline src/Mod/Sketcher/App/SketchObject.cpp:9740]: I don't love the variable names in this method (too many abbreviations and similar-sounding-but-not-the-same things). @Pesc0 you want to take a stab at renaming some of them while you're at it? My linter also yells about the pointer arithmetic, so I wouldn't be sad to see that eliminated (though we want to be careful about efficiency here, I bet).

**Comment by chennes** [comment]
@bgbsww or @Pesc0 can you look at these build errors?

**Comment by Pesc0** [comment]
Probably not in the next few days, currently busy with other stuff, sorry
