### PR TITLE
Fix Arc length look for angle > pi

### LINKED ISSUE #13954: Sketcher: arc length higher than half diameter looks bad
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

In a sketch, draw an arc then constrain its length making sure it is longer than half the perimeter of a circle having the same radius. It looks like this:

image

While the result is rather clear when you think about it, it’s not optimal, if only because the longer the arc, the shorter the dimension look. It could be improved by making the dimension go around the arc, like angle constraints, while keeping the two lines parallel. Here is a proposal:

image

### Full version info

```shell
OS: Ubuntu 23.10 (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.37249 (Git) AppImage
Build type: Release
Branch: main
Hash: 3acbc561f299b4cddea8215c387a52f3d5132cf6
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: French/France (fr_FR)
Installed mods: 
  * BillOfMaterials-WB 0.0.7
  * CosmeticThread3D
  * OpenTheme 2024.4.20
  * Curves 0.6.35
  * CurvedShapes 1.0.9
  * sheetmetal 0.4.13
```

### Subproject(s) affected?

Sketcher

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by FlachyJoe**
Fix  #13954

@pierreporte FYI

image

### CODE REVIEW

**Comment by pierreporte** [comment]
Looks good!

File: src/Gui/SoDatumLabel.cpp [hunk 1]
```diff
@@ -59,6 +59,63 @@ using namespace Gui;
 
 // ------------------------------------------------------
 
+
+namespace glVec3f{
```
Comment (wwmayer) [inline src/Gui/SoDatumLabel.cpp:63]: Why this weird namespace name? Since you anyway import it below you can use an anonymous namespace.

File: src/Gui/SoDatumLabel.cpp [hunk 2]
```diff
@@ -59,6 +59,63 @@ using namespace Gui;
...
+
+void glVertex(SbVec3f pt){
+    glVertex3f(pt[0], pt[1], pt[2]);
+}
+
+void glVertexes(std::vector<SbVec3f> pts){
```
Comment (wwmayer) [inline src/Gui/SoDatumLabel.cpp:69]: This should be a const reference to avoid copying the data for every function call.

File: src/Gui/SoDatumLabel.cpp [hunk 3]
```diff
@@ -59,6 +59,63 @@ using namespace Gui;
...
+    for (auto pt: pts){
```
Comment (wwmayer) [inline src/Gui/SoDatumLabel.cpp:70]: Make pt a const reference.

File: src/Gui/SoDatumLabel.cpp [hunk 4]
```diff
@@ -59,6 +59,63 @@ using namespace Gui;
...
+    for (int i=0; i < countSegments; i++) {
+        float theta = startAngle + segment*i;
+        SbVec3f v1 = center + radius * SbVec3f(cos(theta),sin(theta),0);
+        glVertex(v1);
+    }
+    glEnd();
+}
+
+void glDrawArrow(SbVec3f base, SbVec3f dir, double width, double length){
+        // Calculate arrowhead points
```
Comment (wwmayer) [inline src/Gui/SoDatumLabel.cpp:103]: Wrong indentation.

File: src/Gui/SoDatumLabel.cpp [hunk 5]
```diff
@@ -59,6 +59,63 @@ using namespace Gui;
...
+    glBegin(GL_LINE_STRIP);
+    for (int i=0; i < countSegments; i++) {
+        float theta = startAngle + segment*i;
+        SbVec3f v1 = center + radius * SbVec3f(cos(theta),sin(theta),0);
+        glVertex(v1);
+    }
+    glEnd();
+}
+
+void glDrawArrow(SbVec3f base, SbVec3f dir, double width, double length){
```
Comment (wwmayer) [inline src/Gui/SoDatumLabel.cpp:102]: Why do use a double for with and length while all other data types use floats?

File: src/Gui/SoDatumLabel.cpp [hunk 6]
```diff
@@ -483,10 +540,28 @@ class DatumLabelBox
 
         float length = label->param1.getValue();
 
+                // Angles calculations
```
Comment (wwmayer) [inline src/Gui/SoDatumLabel.cpp:543]: Indentation.

File: src/Gui/SoDatumLabel.cpp [hunk 7]
```diff
@@ -613,10 +688,27 @@ SbVec3f SoDatumLabel::getLabelTextCenterArcLength(const SbVec3f& ctr, const SbVe
 {
     float length = this->param1.getValue();
 
-            // Text location
+    // Angles calculations
+    SbVec3f vc1 = (p1 - ctr);
```
Comment (wwmayer) [inline src/Gui/SoDatumLabel.cpp:692]: Don't repeat yourself! The exact same code block is used above. Consider refactoring this code part.

File: src/Gui/SoDatumLabel.cpp [hunk 8]
```diff
@@ -613,10 +688,27 @@ SbVec3f SoDatumLabel::getLabelTextCenterArcLength(const SbVec3f& ctr, const SbVe
...
+    if (endangle < startangle) {
+        endangle += 2. * M_PI;
+    }
+
+    // Text location
     SbVec3f vm = (p1+p2)/2 - ctr;
     vm.normalize();
-    SbVec3f textCenter = ctr + vm * (length + this->imgHeight);
+
+    SbVec3f textCenter;
```
Comment (wwmayer) [inline src/Gui/SoDatumLabel.cpp:706]: Same as above.

File: src/Gui/SoDatumLabel.cpp (hunk 7 above)
Comment (FlachyJoe) [reply src/Gui/SoDatumLabel.cpp:692]: Above is on the `DatumLabelBox` class, here we are in `SoDatumLabel`.

Notice the whole file needs refactoring. Maybe out of scope of this PR even if I already start it.
We could create `InfoArcAngle`, `InfoArcLength` - and so ones - classes to give all the values required multiple times.

**Review by wwmayer — APPROVED** [review]

**Comment by PaddleStroke** [comment]
@FlachyJoe I'm pretty sure that this caused this regression : https://github.com/FreeCAD/FreeCAD/issues/20098

**Comment by pierreporte** [comment]
@FlachyJoe The fix appears to be broken. The label is on the opposite side of the center (only when the angle > 180°).

image

```
OS: Ubuntu 24.04.2 LTS (KDE/plasma/xcb)
Architecture: x86_64
Version: 1.1.0dev.14555 (Git shallow) AppImage
Build date: 2025/09/23 18:47:15
Build type: Release
Branch: main
Hash: e9ce06155d8d47aad7d6c079bfa8ba54df2b6081
Python 3.11.13, Qt 6.8.3, Coin 4.0.3, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.3.0, IfcOpenShell 0.8.2, OCC 7.8.1
Locale: French/France (fr_FR)
Navigation Style/Orbit Style/Rotation Mode: CAD/Rounded Arcball/Drag at cursor
Stylesheet/Theme/QtStyle: FreeCAD.qss/FreeCAD Light/
Logical DPI/Physical DPI/Pixel Ratio: 96/117.596/1
Installed mods: 
  * sheetmetal-backup-before-zip-migration 0.7.22 (Disabled)
  * Curves-backup-before-zip-migration 0.6.63 (Disabled)
  * FusedFilamentDesign-backup-before-zip-migration 0.25.220 (Disabled)
  * fasteners 0.5.41
  * Curves 0.6.70
  * CurvedShapes 1.0.13
  * sheetmetal 0.7.24
  * FusedFilamentDesign 0.25.250
```

**Comment by FlachyJoe** [comment]
Ping @tetektoza is this related to #21920 ?
