### PR TITLE
[Core] Fix for frozen status

### LINKED ISSUE #12829: [Problem] UI/UX: Freeze function issues
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

@FlachyJoe implemented a great feature to *freeze* the current state and exclude from recompute: https://github.com/FreeCAD/FreeCAD/pull/12580

As @FEA-eng mentioned in the PR https://github.com/FreeCAD/FreeCAD/pull/12580#issuecomment-1978531015 it is currently not available in the PartDesign WB.
I've played a bit with this feature and have some troubles which should be easy to fix:

1. Frozen state does not persist on save and opening a file. If I freeze an object, alter it and save it, the alteration is not displayed. When reopening, the modified object is visible and the object is not frozen anymore (recompute at opening). The last modification before closing is now irreversible and lost, although the object was frozen and shouln't be altered.
3. If a PartDesign body is frozen, all nested features can be changed and alter the frozen body.
4. A frozen body can be chamfered in the PartWB. After that it cannot be unfrozen again.
5. A frozen sketch can be activated but is displayed empty in the Sketcher WB
7. The visibility eye icon does not change its state when clicked but the visibillity in the 3D view is toggled (reproduced with a nested sketch in a PartDesign Pad feature) https://github.com/FreeCAD/FreeCAD/issues/12822
Also reproduceable with nested object which are frozen inside of a group (e.g. walls in an arch group)
8. Frozen command does not register with undo/redo
9. If you use a part of a frozen object to create a new feature it throws an error (tried to pad a face of the frozen feature: Index out of bound)
10. If you undo and redo and the body is frozen, all redone features are now outside of the body and cannot be moved inside of the body
11. You can edit frozen features (e.g. draft objects). They wont change but the edit is permanent. On unfreezing, the edit will be applied. 
12. Transform commands move the object, even when frozen. When using Draft WB move, they don't move
13. Placement command moves the frozen object.
14. Non-reversable operations could be applied to frozen objects (e.g. smooth a frozen mesh). If this is done by accident it is not noticed, as there is no feedback to the user. If the mesh is later unfrozen, the smoothed, decimated shape is visible.
15. The freeze icon is not optimal. It covers the entire icon of the feature, body or object. It is not clear if you want to unfreeze something if this is a body or part container, a spreadsheet or PartDesign features. Maybe it can also be combined with the eye icon as the appearance of the object is *frozen*
6. Could it be placed in the context menu section at the bottom, where "Mark to recompute" and "Recompute" is located, as I understand it's related to that?
7. Could it be renamed? I did not figure out what this is doing and had to look through the PRs. 
Proposals: Exclude from recompute, Lock current state, 
8. Could it have a checkbox like "Active body" (at the top of the context menu), like: [ x ] Locked to see the current state in the context menu

Maybe this is all just my personal preference, @obelisk79 maybe ask DWG about this.

grafik
grafik

### Full version info

```shell
OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.36277 (Git)
Build type: Release
Branch: main
Hash: 9e1903d46112b3660bf10c6a4537d728101d560b
Python 3.10.13, Qt 5.15.8, Coin 4.0.2, Vtk 9.2.6, OCC 7.6.3
Locale: German/Germany (de_DE)
Installed mods: 
  * 3DfindIT 1.2.0
  * BIM 2021.12.0
  * CfdOF 1.25.2
  * CurvedShapes 1.0.5
  * Curves 0.6.23
  * Defeaturing 1.2.2
  * fasteners 0.5.12
  * FEMbyGEN 2.1.0
  * freecad.gears 1.2.0
  * freecad_metal_workbench 0.0.1
  * OpenDark 2023.12.17
  * sheetmetal 0.4.2
```

### Subproject(s) affected?

Core

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by FlachyJoe**
Fix #12829 

Ping @maxwxyz 

- [x] Frozen state does not persist on save and opening a file. If I freeze an object, alter it and save it, the alteration is not displayed. When reopening, the modified object is visible and the object is not frozen anymore (recompute at opening). The last modification before closing is now irreversible and lost, although the object was frozen and shouln't be altered.
**a 'freezed' object now prevent the document to be saved.**
- [x] If a PartDesign body is frozen, all nested features can be changed and alter the frozen body.
**linked objects are 'freezed' / 'unfreezed' when the state changes**
- [x] A frozen body can be chamfered in the PartWB. After that it cannot be unfrozen again.
**Part_Chamfer create a new ('unfreezed') object, the nested Body is still 'freezed' and 'unfreezable'**
- [x] A frozen sketch can be activated but is displayed empty in the Sketcher WB
- [x] The visibility eye icon does not change its state when clicked but the visibillity in the 3D view is toggled (reproduced with a nested sketch in a PartDesign Pad feature)
Also reproduceable with nested object which are frozen inside of a group (e.g. walls in an arch group)
- [ ] Frozen command does not register with undo/redo
**It acts on the object state not on a property. The object is not modified. Not sure it's needed**
- [ ] If you use a part of a frozen object to create a new feature it throws an error (tried to pad a face of the frozen feature: Index out of bound)
**Can not reproduce**
- [ ] If you undo and redo and the body is frozen, all redone features are now outside of the body and cannot be moved inside of the body
- [ ] You can edit frozen features (e.g. draft objects). They wont change but the edit is permanent. On unfreezing, the edit will be applied.
- [x] Transform commands move the object, even when frozen. When using Draft WB move, they don't move
- [x] Placement command moves the frozen object.
- [ ] Non-reversable operations could be applied to frozen objects (e.g. smooth a frozen mesh). If this is done by accident it is not noticed, as there is no feedback to the user. If the mesh is later unfrozen, the smoothed, decimated shape is visible.
- [x] The freeze icon is not optimal. It covers the entire icon of the feature, body or object. It is not clear if you want to unfreeze something if this is a body or part container, a spreadsheet or PartDesign features. Maybe it can also be combined with the eye icon as the appearance of the object is frozen
**Fixed** 
image

- [ ] Could it be placed in the context menu section at the bottom, where "Mark to recompute" and "Recompute" is located, as I understand it's related to that?
- [ ] Could it be renamed? I did not figure out what this is doing and had to look through the PRs.
Proposals: Exclude from recompute, Lock current state,
- [ ] Could it have a checkbox like "Active body" (at the top of the context menu), like: [ x ] Locked to see the current state in the context menu

### CODE REVIEW

File: src/Gui/CommandFeat.cpp [hunk 1]
```diff
@@ -144,22 +144,27 @@ StdCmdToggleFreeze::StdCmdToggleFreeze()
 void StdCmdToggleFreeze::activated(int iMsg)
```
Comment (maxwxyz) [inline src/Gui/CommandFeat.cpp:144]: line 134 above has a typo:
+ QT_TR_NOOP("Toggles freeze **sate** of the selected objects. A freezed object is not recomputed when its parents change.")

should be **state**

**Review by maxwxyz — CHANGES_REQUESTED** [review]

**Comment by maxwxyz** [comment]
@FlachyJoe another approach which was brought up by @obelisk79 was to remove the additional snowflake icon and instead desaturate the original icon of the object and color it slightly blue/icy. Maybe the label text of the object could be greyed out as well.

**Comment by FlachyJoe** [comment]
@maxwxyz I've currently no idea how to do this but if no one is in a hurry, I'll learn.

**Comment by maxwxyz** [comment]
@FlachyJoe did you change something else with the context menu? It renders always on the top edge of the screen, not on mouse location. Only in PD (own context menu) its at the cursor location.

**Comment by maxwxyz** [comment]
@FlachyJoe also here the heads up for the upcoming feature freeze. As there are a lot of open points, are you considering this a post 1.0 PR?

**Comment by FlachyJoe** [comment]
@maxwxyz this is a bug fix not concerned by feature freeze but should be done before release, right?

**Comment by maxwxyz** [comment]
Yes

**Comment by FEA-eng** [comment]
@FlachyJoe Will some of those fixes make it 1.0? It would be good to have the Freeze option available in Part Design, for instance.

**Comment by FlachyJoe** [comment]
I'm not available to end this before release date. The current state with partial fix can be merged.

**Comment by FEA-eng** [comment]
> I'm not available to end this before release date. The current state with partial fix can be merged.

Sure, no need to fix all the issues at once. If this PR is good to go and fixes some of the issues, please undraft it so that it can be merged.

**Review by maxwxyz — APPROVED** [review]

File: src/Gui/CommandFeat.cpp [hunk 2]
```diff
@@ -165,22 +165,27 @@ StdCmdToggleFreeze::StdCmdToggleFreeze()
...
-        if (obj->isFreezed())
+        if (obj->isFreezed()){
             obj->unfreeze();
-        else
+            for (auto child: obj->getInListRecursive())
+                child->unfreeze();
+        } else {
             obj->freeze();
-    }
+            for (auto parent: obj->getOutListRecursive())
```
Comment (chennes) [inline src/Gui/CommandFeat.cpp:183]:
```suggestion
            for (auto parent : obj->getOutListRecursive())
```

File: src/App/DocumentObject.cpp [hunk 3]
```diff
@@ -1059,6 +1067,9 @@ DocumentObject *DocumentObject::getLinkedObject(
 
 void DocumentObject::Save (Base::Writer &writer) const
 {
+    if (this->isFreezed())
+        throw Base::AbortException("At least one object is frozen, unable to save.");
```
Comment (chennes) [inline src/App/DocumentObject.cpp:1071]:
```suggestion
    if (this->isFreezed()) {
        throw Base::AbortException("At least one object is frozen, unable to save.");
    }
```

File: src/App/DocumentObject.cpp [hunk 4]
```diff
@@ -773,7 +781,7 @@ void DocumentObject::onEarlyChange(const Property *prop)
 /// get called by the container when a Property was changed
 void DocumentObject::onChanged(const Property* prop)
 {
-    if (isFreezed())
+    if (isFreezed() && prop != &Visibility)
         return;
```
Comment (chennes) [inline src/App/DocumentObject.cpp:785]:
```suggestion
    if (isFreezed() && prop != &Visibility) {
        return;
    }
```

File: src/App/DocumentObject.cpp [hunk 5]
```diff
@@ -751,6 +756,9 @@ void DocumentObject::onBeforeChange(const Property* prop)
 
 void DocumentObject::onEarlyChange(const Property *prop)
 {
+    if (isFreezed() && prop != &Visibility)
+        return;
```
Comment (chennes) [inline src/App/DocumentObject.cpp:760]:
```suggestion
    if (isFreezed() && prop != &Visibility) {
        return;
    }
```

File: src/App/DocumentObject.cpp [hunk 6]
```diff
@@ -738,6 +740,9 @@ App::Property* DocumentObject::addDynamicProperty(
 
 void DocumentObject::onBeforeChange(const Property* prop)
 {
+    if (isFreezed() && prop != &Visibility)
+        return;
```
Comment (chennes) [inline src/App/DocumentObject.cpp:744]:
```suggestion
    if (isFreezed() && prop != &Visibility) {
        return;
    }
```

**Review by chennes — APPROVED** [review]
Linter cleanup (no need to manually make these changes, I will merge them into the PR).

**Comment by adrianinsaval** [comment]
@chennes this is good to merge now right?

**Comment by adrianinsaval** [comment]
ok to squash this?

**Comment by FlachyJoe** [comment]
Squashed and rebased

**Comment by luzpaz** [comment]
Screenshot_20241120_071813

Can the commit subject and body be re-edited. They are very generic, don't mention which ticket it addresses. This is important for folks writing the Release Notes and documentation. TIA

**Comment by maxwxyz** [comment]
@FlachyJoe unfortunately another conflict due to the large queue of PRs

**Comment by maxwxyz** [comment]
@FlachyJoe ping for conflict

**Comment by Roy-043** [comment]
This PR changes the behavior of the Std_Placement command. Before this PR multiple objects could be selected. Now only a single object can be selected. Reported on the forum (https://forum.freecad.org/viewtopic.php?t=99693).
