### PR TITLE
Core: Fix expression function simplify

### LINKED ISSUE #22766: Reproducible crash when adding expressions with square roots to VarSets via expression editor
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Problem description

I've found a reproducible crash, but I need to ask if this happens on other people's machines. 

I've narrowed down the crash to a short procedure: 
- Launch FreeCAD into safe mode, blank document. 
- New VarSet. No need to add a value (but works if there is one)
- Make something, anything. Part WB > Cube. 
- Open the expression editor for any property of it, with any method. I'm doing Property Table and Cube.length
- Input *anything* involving `sqrt()` and saving it to VarSet.
```
[X] Show variable sets
Value: sqrt(1)
Variable set: VarSet
Group: Base
New property: fubar
```
The instant I hit submit the app crashes to desktop. No warning. 
***Workaround: the crash does not happen if you add the expression to the VarSet directly, instead of by some other component's Expression Editor.***

### Full version info

```shell
OS: KDE Flatpak runtime (KDE/plasma/xcb)
Architecture: x86_64
Version: 1.0.1.39285 (Git) Flatpak
Build type: Release
Branch: (HEAD detached at 878f0b8)
Hash: 878f0b8c9c72c6f215833a99f2762bc3a3cf2abd
Python 3.12.10, Qt 6.9.0, Coin 4.0.3, Vtk 9.3.1, OCC 7.8.1
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Dark/

OS: Fedora 42
KDE Plasma version: 6.4.3
Graphics: Wayland
GPU: Nvidia GTX 1650 Super
```

### Subproject(s) affected?

None

### Anything else?

If I open FreeCAD in the terminal and do the crash bug, I get this log: 

```
fedora:~:% flatpak run org.freecad.FreeCAD --safe-mode
FreeCAD 1.0.1, Libs: 1.0.1R39285 (Git)
(C) 2001-2025 FreeCAD contributors
FreeCAD is free and open-source software licensed under the terms of LGPL2+ license.

FreeCAD is running in _SAFE_MODE_.
Safe mode temporarily disables your configurations and addons. Restart the application to exit safe mode.

Qt: Session management error: Could not open network socket
Migrating Start Workbench to Start command... done.
Program received signal SIGSEGV, Segmentation fault.
#0  /usr/lib/x86_64-linux-gnu/libc.so.6(+0x41140) [0x7fcb38042140]
#1  0x7fcb3afd1462 in App::Expression::getPyValue() const from /app/freecad/lib/libFreeCADApp.so+0x32
#2  0x7fcb3afd6940 in App::FunctionExpression::evaluate(App::Expression const*, int, std::vector<App::Expression*, std::allocator<App::Expression*> > const&) from /app/freecad/lib/libFreeCADApp.so+0x970
#3  0x7fcb3afda18f in App::FunctionExpression::_getPyValue() const from /app/freecad/lib/libFreeCADApp.so+0x2f
#4  0x7fcb3afd1468 in App::Expression::getPyValue() const from /app/freecad/lib/libFreeCADApp.so+0x38
#5  0x7fcb3afd1d18 in App::Expression::eval() const from /app/freecad/lib/libFreeCADApp.so+0x38
#6  0x7fcb3afd2214 in App::FunctionExpression::simplify() const from /app/freecad/lib/libFreeCADApp.so+0x2c4
#7  0x7fcb3bc90c73 in Gui::Dialog::DlgExpressionInput::acceptWithVarSet() from /app/freecad/lib/libFreeCADGui.so+0x203
#8  0x7fcb3bc91649 in Gui::Dialog::DlgExpressionInput::accept() from /app/freecad/lib/libFreeCADGui.so+0x29
#9  /usr/lib/x86_64-linux-gnu/libQt6Core.so.6(+0x20dfee) [0x7fcb3880dfee]
#10  0x7fcb39ae8434 in QAbstractButton::clicked(bool) from /usr/lib/x86_64-linux-gnu/libQt6Widgets.so.6+0x44
#11  /usr/lib/x86_64-linux-gnu/libQt6Widgets.so.6(+0x2e86bf) [0x7fcb39ae86bf]
#12  0x7fcb39aea216 in QAbstractButton::click() from /usr/lib/x86_64-linux-gnu/libQt6Widgets.so.6+0x96
#13  0x7fcb39c43b7c in QDialog::keyPressEvent(QKeyEvent*) from /usr/lib/x86_64-linux-gnu/libQt6Widgets.so.6+0x19c
#14  0x7fcb39a0a8df in QWidget::event(QEvent*) from /usr/lib/x86_64-linux-gnu/libQt6Widgets.so.6+0x118f
#15  0x7fcb399a167d in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /usr/lib/x86_64-linux-gnu/libQt6Widgets.so.6+0x8d
#16  0x7fcb399ac4ac in QApplication::notify(QObject*, QEvent*) from /usr/lib/x86_64-linux-gnu/libQt6Widgets.so.6+0x12ac
#17  0x7fcb3bb53040 in Gui::GUIApplication::notify(QObject*, QEvent*) from /app/freecad/lib/libFreeCADGui.so+0xd0
#18  0x7fcb387a5808 in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /usr/lib/x86_64-linux-gnu/libQt6Core.so.6+0x168
#19  /usr/lib/x86_64-linux-gnu/libQt6Widgets.so.6(+0x221228) [0x7fcb39a21228]
#20  0x7fcb399a167d in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /usr/lib/x86_64-linux-gnu/libQt6Widgets.so.6+0x8d
#21  0x7fcb3bb53040 in Gui::GUIApplication::notify(QObject*, QEvent*) from /app/freecad/lib/libFreeCADGui.so+0xd0
#22  0x7fcb387a5808 in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /usr/lib/x86_64-linux-gnu/libQt6Core.so.6+0x168
#23  0x7fcb38ffec5b in QGuiApplicationPrivate::processKeyEvent(QWindowSystemInterfacePrivate::KeyEvent*) from /usr/lib/x86_64-linux-gnu/libQt6Gui.so.6+0x19b
#24  0x7fcb3906d29c in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /usr/lib/x86_64-linux-gnu/libQt6Gui.so.6+0xac
#25  /usr/lib/x86_64-linux-gnu/libQt6XcbQpa.so.6(+0x64046) [0x7fcb33271046]
#26  /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x633f6) [0x7fcb36b133f6]
#27  /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(+0xc40c7) [0x7fcb36b740c7]
#28  /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_iteration+0x33) [0x7fcb36b12883]
#29  0x7fcb38ac29b3 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /usr/lib/x86_64-linux-gnu/libQt6Core.so.6+0x73
#30  0x7fcb387b31e3 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) from /usr/lib/x86_64-linux-gnu/libQt6Core.so.6+0x1a3
#31  0x7fcb387ae7c1 in QCoreApplication::exec() from /usr/lib/x86_64-linux-gnu/libQt6Core.so.6+0xb1
#32  0x7fcb3ba687bd in Gui::Application::runApplication() from /app/freecad/lib/libFreeCADGui.so+0xd4d
#33  FreeCAD(+0x96e3) [0x55c89ac4f6e3]
#34  /usr/lib/x86_64-linux-gnu/libc.so.6(+0x2a188) [0x7fcb3802b188]
#35  /usr/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x8b) [0x7fcb3802b24b]
#36  FreeCAD(+0x9b15) [0x55c89ac4fb15]
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by pieterhijma**
This PR fixes expression simplification for expression functions. For example a simplify on expression `sqrt(4)` would crash.

The PR contains several tests for this as well in a first commit. Without the second commit, running the test case segfaults.

## Issues

Closes #22766

### CODE REVIEW

**Comment by pieterhijma** [comment]
@benj5378 and @chennes, I've also added a copyright header, currently with @wwmayer's name and mine (Werner wrote most of the tests). I thought that was warranted because I added a new type of test for expressions. If you feel your name should be in the header as well, feel free to do so.

File: src/App/Expression.cpp [hunk 1]
```diff
@@ -2625,7 +2625,7 @@ Expression *FunctionExpression::simplify() const
         // All constants, then evaluation must also be constant
 
         // Clean-up
-        for (auto it : args)
+        for (auto it : a)
```
Comment (chennes) [inline src/App/Expression.cpp]: This is the sort of error that is basically caused by poor variable naming-- maybe we should take this opportunity to do better. `simplifiedExpressions`? Sort of a "lipstick on a pig" situation, I admit, with the non-local allocation requiring local cleanup, but it's a step in the right direction anyway.

Comment (pieterhijma) [reply src/App/Expression.cpp]: I fully agree, I'll make the change.

**Comment by chennes** [comment]
One last nit to pick before I merge - can you switch to the newer copyright header (the one that doesn't have an obsolete mailing address in it :) ).

**Comment by chennes** [comment]
@mnesarco is going to test this

**Comment by mnesarco** [comment]
## Before

```
Program received signal SIGSEGV, Segmentation fault.
#0  /lib/x86_64-linux-gnu/libc.so.6(+0x45330) [0x7a5da8a45330]
#1  0x7a5dab479706 in App::Expression::getPyValue() const from /devel/FreeCAD/FreeCAD_pixi/build/debug/lib/libFreeCADApp.so+0x36
#2  0x7a5dab488a3a in App::FunctionExpression::evaluate(App::Expression const*, int, std::vector<App::Expression*, std::allocator<App::Expression*> > const&) from /devel/FreeCAD/FreeCAD_pixi/build/debug/lib/libFreeCADApp.so+0x3c3a
#3  0x7a5dab48b790 in App::FunctionExpression::_getPyValue() const from /devel/FreeCAD/FreeCAD_pixi/build/debug/lib/libFreeCADApp.so+0x30
#4  0x7a5dab47970f in App::Expression::getPyValue() const from /devel/FreeCAD/FreeCAD_pixi/build/debug/lib/libFreeCADApp.so+0x3f
#5  0x7a5dab478c82 in App::Expression::eval() const from /devel/FreeCAD/FreeCAD_pixi/build/debug/lib/libFreeCADApp.so+0x32
#6  0x7a5dab48b95a in App::FunctionExpression::simplify() const from /devel/FreeCAD/FreeCAD_pixi/build/debug/lib/libFreeCADApp.so+0x1ba
#7  build/debug/tests/App_tests_run(+0x155abf) [0x63083e623abf]
#8  build/debug/tests/App_tests_run(+0x270564) [0x63083e73e564]
#9  build/debug/tests/App_tests_run(+0x251c26) [0x63083e71fc26]
#10  build/debug/tests/App_tests_run(+0x231cb7) [0x63083e6ffcb7]
#11  build/debug/tests/App_tests_run(+0x23282c) [0x63083e70082c]
#12  build/debug/tests/App_tests_run(+0x23302d) [0x63083e70102d]
#13  build/debug/tests/App_tests_run(+0x2438f7) [0x63083e7118f7]
#14  build/debug/tests/App_tests_run(+0x271ff4) [0x63083e73fff4]
#15  build/debug/tests/App_tests_run(+0x253ea6) [0x63083e721ea6]
#16  build/debug/tests/App_tests_run(+0x243498) [0x63083e711498]
#17  build/debug/tests/App_tests_run(+0x21d811) [0x63083e6eb811]
#18  build/debug/tests/App_tests_run(+0x21d7ed) [0x63083e6eb7ed]
#19  /lib/x86_64-linux-gnu/libc.so.6(+0x2a1ca) [0x7a5da8a2a1ca]
#20  /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x8b) [0x7a5da8a2a28b]
#21  build/debug/tests/App_tests_run(+0x10a9d9) [0x63083e5d89d9]
Aborted (core dumped)
```

## After 

Tested, everything looks good.
- C++ Tests: All Green
- Python Tests: All Green except for `testPartCompoundCut2` but this test seems to fail/pass randomly and it is unrelated anyway.

**Comment by adrianinsaval** [comment]
should this be backported?

**Comment by pieterhijma** [comment]
Would not be a bad idea.
