### PR TITLE
GUI: Fix hints on high DPI screens

### LINKED ISSUE #21629: Gui: Status bar hints misshapen (macOS / high-DPI issue?)
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Problem description

The status bar hints (cool feature!) are sort of distorted and double-wide on my Mac.

Image

### Full version info

```shell
OS: macOS 15.5
Architecture: x86_64
Version: 1.1.0dev.41866 (Git)
Build date: 2025/05/26 16:31:05
Build type: Release
Branch: main
Hash: bc5616dbf6cbe3a2d88992dc9572d6f5b5bb502f
Python 3.11.12, Qt 6.8.3, Coin 4.0.3, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.2.5, IfcOpenShell 0.8.2, OCC 7.8.1
Locale: English/United Kingdom (en_GB)
Navigation Style/Orbit Style/Rotation Mode: Touchpad/Free Turntable/Drag at cursor
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Dark/
Logical DPI/Physical DPI/Pixel Ratio: 72/127.75/2
Installed mods: 
  * ThreadProfile 1.96.0
  * freecad.gears 1.3.0
  * OpenTheme 2024.9.1
  * fasteners 0.5.38
  * lattice2 1.0.0
  * CurvedShapes 1.0.13
  * sheetmetal 0.7.22
  * Curves 0.6.62
```

### Subproject(s) affected?

None

### Anything else?

_No response_

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by maxwxyz**
Fix hints on HiDPI screens.

## Issues
fixes #21629

## Before and After Images

Before:
grafik

After:
Bildschirmfoto 2025-06-04 um 13 14 59

### CODE REVIEW

File: src/Gui/InputHintWidget.cpp [hunk 1]
```diff
@@ -121,13 +128,13 @@ std::optional<const char*> Gui::InputHintWidget::getCustomIconPath(const InputHi
     }
 }
 
-QPixmap Gui::InputHintWidget::generateKeyIcon(const InputHint::UserInput key, const QColor color)
+QPixmap Gui::InputHintWidget::generateKeyIcon(const InputHint::UserInput key, const QColor color, int iconSize)
```
Comment (kadet1090) [inline src/Gui/InputHintWidget.cpp]: This should be simply called `height` as this will better describe what does it mean.

File: src/Gui/InputHintWidget.cpp [hunk 2]
```diff
@@ -41,29 +41,36 @@ void Gui::InputHintWidget::showHints(const std::list<InputHint>& hints)
...
         QBuffer buffer;
         image.save(&buffer, "png");
 
-        return QStringLiteral("<img src=\"data:image/png;base64,%1\" width=%2 height=24 />")
-            .arg(QLatin1String(buffer.data().toBase64()))
-            .arg(image.width());
+        return QStringLiteral("<img src=\"data:image/png;base64,%1\" width=%2 height=%3 />")
+            .arg(QString::fromLatin1(buffer.data().toBase64()))
+            .arg(iconSize)
+            .arg(iconSize);
```
Comment (kadet1090) [inline src/Gui/InputHintWidget.cpp]: This assumes that icon width and height is the same - which is untrue. For example "Escape" key will be wider.

File: src/Gui/InputHintWidget.cpp [hunk 3]
```diff
@@ -41,29 +41,36 @@ void Gui::InputHintWidget::showHints(const std::list<InputHint>& hints)
...
+        const qreal dpr = devicePixelRatioF();
 
         QPixmap image = [&] {
             QColor color = palette().text().color();
 
             if (auto iconPath = getCustomIconPath(key)) {
-                return factory.pixmapFromSvg(*iconPath,
-                                             QSize(24, 24),
+                QPixmap pixmap = factory.pixmapFromSvg(*iconPath,
+                                             QSize(iconSize * dpr, iconSize * dpr),
```
Comment (kadet1090) [inline src/Gui/InputHintWidget.cpp]: Why do we need it? pixmapFromSvg does already include multiplication by dpr

File: src/Gui/InputHintWidget.cpp [hunk 4]
```diff
@@ -121,13 +128,13 @@ std::optional<const char*> Gui::InputHintWidget::getCustomIconPath(const InputHi
...
 
-QPixmap Gui::InputHintWidget::generateKeyIcon(const InputHint::UserInput key, const QColor color)
+QPixmap Gui::InputHintWidget::generateKeyIcon(const InputHint::UserInput key, const QColor color, int iconSize)
 {
     constexpr int margin = 3;
     constexpr int padding = 4;
     constexpr int radius = 2;
-    constexpr int iconTotalHeight = 24;
-    constexpr int iconSymbolHeight = iconTotalHeight - 2 * margin;
+    const int iconTotalHeight = iconSize;
```
Comment (kadet1090) [inline src/Gui/InputHintWidget.cpp]: You don't need that const at all if you have parameter - just replace all `iconTotalHeigth` uses with `height` coming from parameter.

File: src/Gui/InputHintWidget.h [hunk 5]
```diff
@@ -45,7 +45,7 @@ class GuiExport InputHintWidget : public QLabel
 
 private:
     static std::optional<const char*> getCustomIconPath(InputHint::UserInput key);
-    static QPixmap generateKeyIcon(InputHint::UserInput key, QColor color);
+    static QPixmap generateKeyIcon(InputHint::UserInput key, QColor color, int iconSize);
```
Comment (kadet1090) [inline src/Gui/InputHintWidget.h]:
```suggestion
    static QPixmap generateKeyIcon(InputHint::UserInput key, QColor color, int height);
```

File: src/Gui/InputHintWidget.cpp (hunk 1 above)
Comment (maxwxyz) [reply src/Gui/InputHintWidget.cpp]: done

File: src/Gui/InputHintWidget.cpp (hunk 2 above)
Comment (maxwxyz) [reply src/Gui/InputHintWidget.cpp]: done

File: src/Gui/InputHintWidget.cpp (hunk 4 above)
Comment (maxwxyz) [reply src/Gui/InputHintWidget.cpp]: done

File: src/Gui/InputHintWidget.h (hunk 5 above)
Comment (maxwxyz) [reply src/Gui/InputHintWidget.h]: done

File: src/Gui/InputHintWidget.cpp (hunk 3 above)
Comment (maxwxyz) [reply src/Gui/InputHintWidget.cpp]: I don't know, but it works

Comment (kadet1090) [reply src/Gui/InputHintWidget.cpp]: pixmapFromSvg does that exact thing, this must be dropped, code at this level should not care about DPR

File: src/Gui/InputHintWidget.cpp [hunk 6]
```diff
@@ -44,26 +44,32 @@ void Gui::InputHintWidget::showHints(const std::list<InputHint>& hints)
...
                                              QSize(24, 24),
                                              {{0xFFFFFF, color.rgb() & RGB_MASK}});
+                pixmap.setDevicePixelRatio(dpr);
+                return pixmap;
             }
 
-            return generateKeyIcon(key, color);
+            QPixmap pixmap = generateKeyIcon(key, color);
+            pixmap.setDevicePixelRatio(dpr);
+            return pixmap;
```
Comment (kadet1090) [inline src/Gui/InputHintWidget.cpp]: That function should not be dpr aware. `generateKeyIcon` should be - and it is from what I see. `pixmapFromSvg` does contain required call too.

File: src/Gui/InputHintWidget.h [hunk 7]
```diff
@@ -45,7 +45,7 @@ class GuiExport InputHintWidget : public QLabel
 
 private:
     static std::optional<const char*> getCustomIconPath(InputHint::UserInput key);
-    static QPixmap generateKeyIcon(InputHint::UserInput key, QColor color);
+    QPixmap generateKeyIcon(InputHint::UserInput key, QColor color);
     static QString inputRepresentation(InputHint::UserInput key);
```
Comment (kadet1090) [inline src/Gui/InputHintWidget.h]:
```
    QPixmap generateKeyIcon(InputHint::UserInput key, QColor color);

    static std::optional<const char*> getCustomIconPath(InputHint::UserInput key);
    static QString inputRepresentation(InputHint::UserInput key);
```

It is good to group static and non static methods visually.

Comment (maxwxyz) [reply src/Gui/InputHintWidget.h]: done

**Review by kadet1090 — APPROVED** [review]
