### PR TITLE
PD: Fix loft between curved faces

### LINKED ISSUE #19183: Loft between faces no longer works
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Problem description

As be seen in the attached video between 4:30 and 5:08, in past versions the loft performed was possible.

[https://www.youtube.com/watch?v=e6GQJG_T2ew&list=PLWuyJLVUNtc0UszswD0oD5q4VeWTrK7JC&index=42](url)

In 1.1.0.dev it fails with "AdditiveLoft: Loft: At least one section is needed" error.

[LoftFail.FCStd.zip](https://github.com/user-attachments/files/18495627/LoftFail.FCStd.zip)

### Full version info

```shell
OS: Manjaro Linux (KDE/plasma/xcb)
Architecture: x86_64
Version: 1.1.0dev.39861 (Git)
Build type: Release
Branch: main
Hash: 4cb01753ed532263dddae60e40e8641df56f9185
Python 3.12.7, Qt 6.8.1, Coin 4.0.3, Vtk 9.3.1, OCC 7.8.1
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: OpenDark.qss/OpenDark/
Installed mods: 
  * Silk 0.1.5
  * Defeaturing 1.2.3
  * Curves 0.6.53
  * CurvedShapes 1.0.13
  * DynamicData 2.70.0
  * lattice2 1.0.0
  * sheetmetal 0.7.3
  * Manipulator 1.5.7
  * kicadStepUpMod 11.5.2
  * fasteners 0.5.35
  * OpenTheme 2024.9.1
  * ProDarkThemePreferencePack 1.0.0
  * freecad.gears 1.3.0
  * ExtremeProDark 2.9.0
```

### Subproject(s) affected?

PartDesign

### Anything else?

_No response_

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by 3x380V**
Inspired by a9100c1425

Fixes #19183

Also reported in the forum:
https://forum.freecad.org/viewtopic.php?p=806495
https://forum.freecad.org/viewtopic.php?t=88234
    
The actual reason for the failure is that the new code uses `FaceMakerBullseye` method which expects coplanar wires.
The code was using `FaceMakerCheese` previously which changed in LinkStage with their commit [PD: use FaceMakerBullseye for feature Loft](https://github.com/realthunder/FreeCAD/commit/93ce3edfe7ff714d24fdfea3a0ae1dde10714f19) and was imported here with TNP mitigations.
    
As changing it back would cause different regressions, lets try different facemakers until one succeeds.

### CODE REVIEW

**Comment by hyarion** [comment]
Maybe it does works, but reading the source code it sounds like a fluke.

From `std::string FaceMakerCheese::getBriefExplanation() const`:
> Supports making planar faces with holes, but no islands inside holes.

@DeepSOIC do you have any suggestion here?

**Comment by hyarion** [comment]
I think changing this would create another regression.
@3x380V could you check if this file works in the changed/new version?

[bullseyeloft.FCStd.zip](https://github.com/user-attachments/files/20892747/bullseyeloft.FCStd.zip)

image

**Comment by 3x380V** [comment]
@hyarion, yes it does work. Also note it is just changing things back to previous state. During TNP merge sometimes conflicts were not resolved properly, but I suggest you track the change from the offending commit listed in the commit log to double (triple actually) check.

**Comment by hyarion** [comment]
> @hyarion, yes it does work.

Thanks for verifying. 

> Also note it is just changing things back to previous state.

I understand that, but it seems like the two face makers have different features and problems. Cheese was the legacy one which should have been superseded by bullseye, so rolling it back has a high risk of creating new regressions for people that depends on the new behavior. We don't want to break backwards compatibility again.

Before we go forward it would be good to try to figure out what we remove (if anything). If there are features we don't want to remove, then we might need to find another solution to fix the regressions than a simple roll back.

**Comment by hyarion** [comment]
Ok, here's a regression, inspired by a comment in shapestring https://github.com/FreeCAD/FreeCAD/blob/main/src/Mod/Draft/draftobjects/shapestring.py#L277

[lofttt3.FCStd.zip](https://github.com/user-attachments/files/20898080/lofttt3.FCStd.zip)
image

As bullseye throws an exception for curved faces, would it be an option to make a waterfall solution similar to shapestring?

```c++
        auto faceMakers {
            "Part::FaceMakerBullseye",
            "Part::FaceMakerCheese",
            "Part::FaceMakerSimple",
        };
        for (auto faceMaker : faceMakers) {
            try:
                back = TopoShape(0).makeElementFace(backwires, nullptr, faceMaker);
            catch:
                continue;
            break;
        }
```

Or maybe create a CompositeFaceMaker which does this for us?
Or maybe accept regressions but make it customizable?

What do you think @3x380V?
It would also be lovely to hear @wwmayer 's thoughts on this.

**Comment by 3x380V** [comment]
Waterfall solution seem easiest, but I have no strong opinion here. And for the completeness, [change comes](https://github.com/realthunder/FreeCAD/commit/93ce3edfe7ff714d24fdfea3a0ae1dde10714f19) from @realthunder's fork and was imported with toponaming code.

**Comment by 3x380V** [comment]
@hyarion, face makers are throwing different kind of exceptions, some are `Standard_Failure` some are based on `Base::Exception`. Here, we are trying to intercept all of them to see how it will work. Perhaps we can give your `CompositeFaceMaker` idea a try if that proves useful also elsewhere.

File: src/Mod/PartDesign/App/FeatureLoft.cpp [hunk 1]
```diff
@@ -190,7 +190,23 @@ App::DocumentObjectExecReturn *Loft::execute()
...
+            };
+            for (const auto faceMaker : faceMakers) {
+                try {
+                    back = TopoShape(0).makeElementFace(backwires, nullptr, faceMaker);
+                    break;
+                }
+                catch (...) {
+                   if (&faceMaker == faceMakers.end()) {
+                       throw;
+                   }
```
Comment (hyarion) [inline src/Mod/PartDesign/App/FeatureLoft.cpp]: I understand that you want to check if we caught an exception at the last iteration, but does this really work?
Maybe we could check `back.IsNull()` after the for loop and throw there instead?

Comment (3x380V) [reply src/Mod/PartDesign/App/FeatureLoft.cpp]: I checked all used face maker implementations before adding this condition. They are inconsistent at least, but we are really falling back to `FaceMakerCheese` once `FaceMakerBullseye` fails (perhaps use only those two to be conservative?). I decided not to do this after loop but inside catch, so the same exception is reported to the upper layer. Again, no strong opinion here.

Comment (hyarion) [reply src/Mod/PartDesign/App/FeatureLoft.cpp]: Sorry I've had a lot this weekend, I'll take another look at this soon.

**Comment by yorikvanhavre** [comment]
Waiting for hyarion's review

File: src/Mod/PartDesign/App/FeatureLoft.cpp (hunk 1 above)
Comment (hyarion) [reply src/Mod/PartDesign/App/FeatureLoft.cpp]: Don't we get the address of the loop variable using `&faceMaker` instead of the pointer in the original list?
Something's telling me that this might not be safe.

To be on the safe side, we could just use normal c-style for loop with an index that we compare to the array length. What do you think?

**Comment by maxwxyz** [comment]
@3x380V reminder for https://github.com/FreeCAD/FreeCAD/pull/22165#discussion_r2202799199

File: src/Mod/PartDesign/App/FeatureLoft.cpp (hunk 1 above)
Comment (3x380V) [reply src/Mod/PartDesign/App/FeatureLoft.cpp]: Do you have something like this in mind?
```c++
            const char *faceMaker[] = {
                "Part::FaceMakerBullseye",
                "Part::FaceMakerCheese",
                "Part::FaceMakerSimple",
            };
            for (int i = 0; i < std::size(faceMaker); i++) {
                try {
                    back = TopoShape(0).makeElementFace(backwires, nullptr, faceMaker[i]);
                    break;
                }
                catch (...) {
                   if (i == std::size(faceMaker) - 1) {
                       throw;
                   }
                   continue;
                }
            }
```

Comment (hyarion) [reply src/Mod/PartDesign/App/FeatureLoft.cpp]: > Do you have something like this in mind?

Yes, it's a simple way of finding that we're at the last entry in a loop. Not sure if there is any easier way to do it in c++20 (in 23 it would be possible to enumerate an iterator like in Python, but where not there yet)

File: src/Mod/PartDesign/App/FeatureLoft.cpp [hunk 2]
```diff
@@ -213,7 +213,23 @@ App::DocumentObjectExecReturn *Loft::execute()
             std::vector<TopoShape> backwires;
             for(auto& sectionWires : wiresections)
                 backwires.push_back(sectionWires.back());
-            back = TopoShape(0).makeElementFace(backwires);
+            const char *faceMaker[] = {
+                "Part::FaceMakerBullseye",
+                "Part::FaceMakerCheese",
+                "Part::FaceMakerSimple",
+            };
+            for (int i = 0; i < std::size(faceMaker); i++) {
```
Comment (hyarion) [inline src/Mod/PartDesign/App/FeatureLoft.cpp]: There's a lint warning here:
`comparison of integers of different signs: 'int' and 'size_t' (aka 'unsigned long') [-Wsign-compare]`

```suggestion
            for (size_t i = 0; i < std::size(faceMaker); i++) {
```
Do you want to fix this yourself or should I add it as a separate commit before merging?

**Comment by 3x380V** [comment]
@hyarion, it seem you enabled auto-merge (squash). Not sure how that works exactly, but squashing commits is not right thing to do here (and in general none of my PRs is intended to be squashed) as it removes commit author information; note @Syres916 authored test, so I left his patch intact and it should be merged so.

**Comment by hyarion** [comment]
> @hyarion, it seem you enabled auto-merge (squash). Not sure how that works exactly, but squashing commits is not right thing to do here (and in general none of my PRs is intended to be squashed) as it removes commit author information; note @Syres916 authored test, so I left his patch intact and it should be merged so.

There was a glitch when I selected and confirmed merge commit, so when I reloaded the page it was back at squash as that was the last operation I did successfully.

I do know that you want to keep the commits and I really appreciate that you take the time to craft them the way you do. Thanks for pointing it out so I could change it before it automatically was merged with the wrong strategy.

**Comment by hyarion** [comment]
I’ll merge it manually instead to be 110% sure…
