### PR TITLE
Gui: sketcher: fix OVP cursor movement issues

### LINKED ISSUE #29248: Sketcher: dimension boxes (OVPs) input text in wrong order
### Problem description

https://github.com/FreeCAD/FreeCAD/labels/Type%3A%20Regression on https://github.com/FreeCAD/FreeCAD/labels/Mod%3A%20Sketcher

Many of the on-sketch dimension input boxes have trouble interpreting digit & comma keystrokes. Distance boxes seem unaffected but angle and scale are (on all tools that feature them, for instance `CreateLine`, `CreateArc*`, `CreateSlot`, `CreateBSpline*`, `CreateText`, `Rotate`, `Scale`, `Offset`).

Maybe related to #28026 and #22559.

Platform and locale seem irrelevant as AstoCAD/FreeCAD#136 reports the same problem on en_DE macOS.

### Workbench affected?

Sketcher

### Steps to reproduce

1. Create a Sketch
2. Use any of `CreateLine`, `CreateArc*`, `CreateSlot`, `CreateBSpline*`, `CreateText` and tab-focus to the angle fields
3. Try typing

Alternatively
1. Create a Sketch
2. Create any geometry
3. Use any of `Rotate`, `Scale`, `Offset` on said geometry
4. Try typing

### Expected behavior

Number input works as expected.

### Actual behavior

Number input barely works.

For instance, using `Scale` and typing:
* `1.5` → `.51`
* `12.3` → `2.31`
* `51.0` → `1.05`
* `.5` → `5`
* `12` → `21`
* `123` → `231`

Image

Video from @PaddleStroke's [dupe issue](https://github.com/FreeCAD/FreeCAD/issues/29254), where `90` is typed on an angle OVP with a result of `09`:

https://github.com/user-attachments/assets/7bd0be71-b11c-4799-a99d-790a5d6ebd91

It's impossible to properly erase with backspace or delete as their behaviour is inconsistent, and navigating with arrow keys is difficult as the cursor refuses to move most of the time, or only up to some of the typed digits.

### Versions

Tested on:
* Linux AppImage: GOOD in 1.1 & 1.2.0dev.20260303, BAD in 1.2.0dev.20260318 & 1.2.0dev.20260324
* Linux native: BAD in 7255c159444c73335aa4ca6fef37e650c55406c5

<details>
<summary>Version info of 1.2.0dev.20260318 (BAD)</summary>

```shell
OS: Void Linux (KDE/wayland)
Architecture: x86_64
Version: 1.2.0dev.20260318 (Git shallow) AppImage
Build date: 2026/03/18 23:42:42
Build type: Release
Branch: grafted,grafted
Hash: 7886ebae105b99f176cddbfc62a106ab06a6d021
Python 3.11.14, Qt 6.8.3, Coin 4.0.3, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.3.0, IfcOpenShell 0.8.2, OCC 7.8.1
Locale: English/United Kingdom (en_GB)
Navigation Style/Orbit Style/Rotation Mode: CAD/Rounded Arcball/Window center
Stylesheet/Theme/QtStyle: FreeCAD.qss/FreeCAD Dark/
Logical DPI/Physical DPI/Pixel Ratio: 96/92.6073/1
```

</details>

<details>
<summary>Version info of 1.2.0dev.20260303 (GOOD)</summary>

```shell
OS: Void Linux (KDE/wayland)
Architecture: x86_64
Version: 1.2.0dev.20260303 (Git shallow) AppImage
Build date: 2026/03/03 22:57:35
Build type: Release
Branch: grafted,grafted
Hash: 637463ac354f093e14dacfc5059eb70c2b1216fd
Python 3.11.14, Qt 6.8.3, Coin 4.0.3, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.3.0, IfcOpenShell 0.8.2, OCC 7.8.1
Locale: English/United Kingdom (en_GB)
Navigation Style/Orbit Style/Rotation Mode: CAD/Rounded Arcball/Window center
Stylesheet/Theme/QtStyle: FreeCAD.qss/FreeCAD Dark/
Logical DPI/Physical DPI/Pixel Ratio: 96/92.6073/1
```

</details>

### PR DESCRIPTION
**Pull request by alfrix**
this should fix https://github.com/FreeCAD/FreeCAD/issues/29248 with a completely different approach than #29263

basically i've simplified the logic to the maximum, we don't need to calculate or clamp anything, we just save the cursor before resizing and restore it afterwards, much simpler than the current code

@ElementW

### CODE REVIEW

File: src/Gui/EditableDatumLabel.cpp [hunk 1]
```diff
@@ -431,12 +435,14 @@ void EditableDatumLabel::setPlacement(const Base::Placement& plc)
     label->norm.setValue(SbVec3f(float(RN.x), float(RN.y), float(RN.z)));
 }
 
-void EditableDatumLabel::updateGeometry()
+void EditableDatumLabel::updateGeometry(QLineEdit* edit)
 {
-    if (!spinBox) {
+    if (!spinBox || !edit) {
```
Comment (ElementW) [inline src/Gui/EditableDatumLabel.cpp:440]: Is there a reason `edit` is a null-checked pointer instead of a reference? It doesn't have an `= nullptr` default so you had to have changed all call sites, both of which are wrapped in a pointer check already.

Comment (alfrix) [reply src/Gui/EditableDatumLabel.cpp:440]: Since qt events are asynchronous, a pointer is safer than a reference because it allows guarding against segfaults if a signal is processed while the object is being destroyed

Comment (ElementW) [reply src/Gui/EditableDatumLabel.cpp:440]: But the `edit` passed from the signal on line 226 is a capture, its value won't change for the duration of the signal handler registration, where said value is guaranteed non-null.

Comment (alfrix) [reply src/Gui/EditableDatumLabel.cpp:440]: i can remove the null-check if you like, i think it's safer to check, but the spinbox check is doing the heavy-lifting in this case since it's the parent

Comment (ElementW) [reply src/Gui/EditableDatumLabel.cpp:440]: I mean barely even matters, a reference would simply make it clearer a null can't be passed here. The performance and readability implications are basically nil.

**Review by FEA-eng — APPROVED** [review]
@maxwxyz Tested, fixes the issue

**Review by ElementW — CHANGES_REQUESTED** [review]
Nope, still broken but in other creative ways, especially on negative numbers, and the focus can get lost and regained in ways I cannot comprehend

https://github.com/user-attachments/assets/72391bb2-0626-4266-a0e5-e39915e0fe0d

Don't mind the keypress display too much, it missed/misinterpreted a lot, still trying to find a proper key display for Wayland desktops.

(oops I posted this as a suggested change, didn't mean to, this is just a regular comment)

**Comment by FEA-eng** [comment]
Ok, indeed, there are some issues with negative numbers, such as when you start from a negative angle and enter 3 digits.

**Comment by alfrix** [comment]
again the focus is not an issue with my pr, that behaviour exist on 1.1

you need to test the same situation and behaviour in 1.1 vs 1.2, negative numbers also tend to act up weirdly on 1.1

i've fixed the cursor jumping to the end which was caused by the rezising of the entry (resets to cursor to the end)

**Comment by ElementW** [comment]
Oh you're right the negatives are utterly broken in 1.1 too and so is the focus somewhat, though you changing the clamp conditions did change how that got triggered.

I guess this fix of yours brings back the 1.1 status quo. Sorry for the focus mixup.

**Comment by alfrix** [comment]
i've tested and the focus issue exists since the inception of the OVP, and i think i have a solution, gonna put it on a different PR since it's unrelated to this fix

**Review by ElementW — APPROVED** [review]

**Comment by chennes** [comment]
@kadet1090 I hope you don't mind me hitting the green button here. This fixes a bug that was very exasperating to me today, and even if not perfect, it is at least ~7873 times better than it was. Thanks, @alfrix for the PR, and @ElementW adn @FEA-eng for the reviews.
