### PR TITLE
#25474 Added read-only warnings when saving documents

### LINKED ISSUE #25474: FreeCAD Saves Over Files Marked as Read-Only (Windows) or Write-Protected (linux/windows)
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Problem description

**IS**: Users can open a freecad document file marked as read-only (windows) or without write permissions (linux/windows), make a change, and save it back to disk successfully (possibly clearing the write protection flag).

**SHOULD BE**: Users can open a freecad document file marked as read-only (windows) or without write permissions (linux/widnows), make a change, but get an error message when attempting to save it back to disk (before the save occurs).

### BACKGROUND
Due to the nature of freeCAD's backup file manager, the "original", "opened" *.FcStd file is never modified when a document is saved (unless the backup policy is disabled). Instead, other temp files are renamed _into_ the original file name. This action only requires write permission in the directory, not on the file. For some workflows (SVN repository with auto-prop svn:needs-lock), marking a file as read-only at the OS level is a crutch used to prevent accidental minor changes to versioned binary files.

### PROPOSED FIX

**1. Check for write-blocking attributes at the beginning of the Save process and give the user a warning that the file is write-protected and they should instead use the SaveAs feature.**

Once the[ "canonical_path" has been determined](https://github.com/FreeCAD/FreeCAD/blob/main/src/App/Document.cpp#L1793), create a [FileInfo class](https://github.com/FreeCAD/FreeCAD/blob/main/src/Base/FileInfo.cpp) around that string. If the file exists but [isWritable()](https://github.com/FreeCAD/FreeCAD/blob/main/src/Base/FileInfo.cpp#L330) is false, then throw a [Base::FileException()](https://github.com/FreeCAD/FreeCAD/blob/main/src/Base/Exception.h#L251) with a message indicating the file is readOnly.

```
Base::FileInfo originalFileInfo(nativePath);
if (originalFileInfo.exists() && !originalFileInfo.isWritable()) {
    throw Base::FileException("Unable to save document because file is marked as read-only or write permission is not available.", originalFileInfo);
}
```

2. Update the FileInfo::isWirtable() method to additionally check the status of the windows "read only" file attribute [directly after the other two conditional checks](https://github.com/FreeCAD/FreeCAD/blob/main/src/Base/FileInfo.cpp#L339).

```
#ifdef FC_OS_WIN32
//requires import of <windows.h>
DWORD attributes = GetFileAttributes(FileName)
if (attributes == INVALID_FILE_ATRIBUTES){
    //Log the error? 
    //usually indicates some kind of network file issue, so the file is probably not writable
    return false;
}
if ((attributes & FILE_ATTRIBUTE_READONLY) != 0)
{
    return false;
}
#endif
```

### ALTERNATE SOLUTIONS

1. Save an FcBak file somewhere when attempting to save over a read-only file. I don't like this because it implies that the failure to save was an erro you might want to recover from, instead of an intentional workflow block.

2. Put the protections directly in the [BackupPolicy class](https://github.com/FreeCAD/FreeCAD/blob/main/src/App/BackupPolicy.cpp) where the file overwriting is actually happening.

### Full version info

```shell
OS: Windows 11 build 26100
Architecture: x86_64
Version: 1.2.0dev.20251118 (Git shallow)
Build date: 2025/11/18 21:54:51
Build type: Release
Branch: main
Hash: be7d41dea75f7f2966d7b431d24f7060c6907339
Python 3.11.14, Qt 6.8.3, Coin 4.0.3, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.3.0, IfcOpenShell 0.8.2, OCC 7.8.1
Locale: English/United States (en_US)
Navigation Style/Orbit Style/Rotation Mode: CAD/Trackball/Drag at cursor
Stylesheet/Theme/QtStyle: FreeCAD Light.qss/FreeCAD Light/
Logical DPI/Physical DPI/Pixel Ratio: 96/101.521/1
Installed mods: 
  * AddonManager 2025.11.4
  * fasteners 0.5.43
  * Render 2024.12.15
```

### Subproject(s) affected?

None

### Anything else?

Forum post: https://forum.freecad.org/viewtopic.php?p=857875
Recent work on file/directory writability:
* https://github.com/FreeCAD/FreeCAD/pull/23351
* https://github.com/FreeCAD/FreeCAD/pull/24114/files

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by BurksEngineering**
## Problem description
IS: Users can open a freecad document file marked as read-only (windows) or without write permissions (linux/windows), make a change, and save it back to disk successfully (possibly clearing the write protection flag).

SHOULD BE: Users can open a freecad document file marked as read-only (windows) or without write permissions (linux/widnows), make a change, but get an error message when attempting to save it back to disk (before the save occurs).

## Background
Due to the nature of freeCAD's backup file manager, the "original", "opened" *.FcStd file is never modified when a document is saved (unless the backup policy is disabled). Instead, other temp files are renamed into the original file name. This action only requires write permission in the directory, not on the file. For some workflows (SVN repository with auto-prop svn:needs-lock), marking a file as read-only at the OS level is a crutch used to prevent accidental minor changes to versioned binary files.

## Issues
closes #25474

## Before and After Images
Before: no prompt when saving a read-only or write-protected file.
After: Verification the windows read-only file attribute is respected
image
After: Verification the windows ACL write protection is respected
image

### CODE REVIEW

File: src/Base/FileInfo.cpp [hunk 1]
```diff
@@ -336,6 +336,45 @@ bool FileInfo::isWritable() const
     if (fs::is_directory(path)) {
         return directoryIsWritable(path);
     }
+    #ifdef FC_OS_WIN32
+    //convert filename from UTF-8 to windows WSTRING
+    std::wstring_convert<std::codecvt_utf8<wchar_t>> utf8ToWstringConverter;
```
Comment (chennes) [inline src/Base/FileInfo.cpp]: This is deprecated (C++'s unicode support is... not wonderful). See https://github.com/FreeCAD/FreeCAD/pull/24464

Comment (BurksEngineering) [reply src/Base/FileInfo.cpp]: Thanks for bringing this up!
After looking into this further i see that [base::FileInfo already has a helper class for getting the wstring of the current file's path](https://github.com/FreeCAD/FreeCAD/blob/3ab8dbe19431e7152ea452e02cc1ae4e870856e8/src/Base/FileInfo.cpp#L247). D'oh!
I will adjust my changes to use the existing implementation of [ConvertToWideString](https://github.com/FreeCAD/FreeCAD/blob/3ab8dbe19431e7152ea452e02cc1ae4e870856e8/src/Base/FileInfo.cpp#L62).

File: src/Base/FileInfo.cpp [hunk 2]
```diff
@@ -336,6 +336,44 @@ bool FileInfo::isWritable() const
...
+    if (attributes == INVALID_FILE_ATTRIBUTES) {
+        // Log the error?
+        std::clog << "GetFileAttributes failed for file: " << FileName << '\n';
+        // usually indicates some kind of network file issue, so the file is probably not writable
+        return false;
+    }
+    if ((attributes & FILE_ATTRIBUTE_READONLY) != 0) {
+        return false;
+    }
+    // TEST if file is truley writable, because windows ACL does not map well to POSIX perms,
```
Comment (chennes) [inline src/Base/FileInfo.cpp]:
```suggestion
    // TEST if file is truly writable, because windows ACL does not map well to POSIX perms,
```

**Comment by chennes** [comment]
Works as advertised, thanks again!
