### PR TITLE
Sketcher:  Do not consider missing external geometry to be an error; highlight i…

### LINKED ISSUE #16361: Sketcher: Design approach to missing External Geometry References
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

After pulling in an external geometry, and using a coincedent of the end of a line to a point, the end of the line jumps to the correct spot, however the line can still be moved after that. It should be stuck to the point

### Full version info

```shell
OS: Linux Mint 21.3 (X-Cinnamon/cinnamon)
Word size of FreeCAD: 64-bit
Version: 1.0.0RC1.38643 (Git)
Build type: Unknown
Branch: main
Hash: fe40748c10503eed367840239db3e0f81873e359
Python 3.10.12, Qt 5.15.3, Coin 4.0.0, Vtk 9.1.0, OCC 7.5.1
Locale: English/Canada (en_CA)
Installed mods: 
  * freecad.gears 1.0.0
  * 3D_Printing_Tools
  * CycloidGearBox
  * FeedsAndSpeeds 0.5.0
  * Ondsel-Lens 2024.1.22.01
  * ExplodedAssembly
  * Nodes 0.1.36
  * 3DfindIT 1.2.0
  * A2plus 0.4.63
  * MeshRemodel 1.9.22
  * lattice2 1.0.0
  * fasteners 0.5.10
  * Assembly3 0.12.2
  * Assembly4 0.50.7
  * POV-Ray-Rendering
  * PieMenu 1.2.7
  * CurvedShapes 1.0.5
```

### Subproject(s) affected?
The console says:
1  <Exception> FeatureDressUp.cpp(209): Invalid edge link: ;#11cf:12;:H44f,F.Face11
16:29:11  Fillet001: Invalid edge link: ;#11cf:12;:H44f,F.Face11
16:29:17  <Sketch> SketchObject.cpp(9135): External geometry BearingCover#Sketch006.e5 missing reference: Pad003.;#bc5;:H-44d,E

Which is true, there is no Pad003. The extrnal geometry should not be showing.  
None

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by bgbsww**
…n conflict color.  Fix #16361

### CODE REVIEW

**Comment by bgbsww** [comment]
@kadet1090 If you have further UI suggestions, or corrections to this, please let me know.

File: src/Mod/Sketcher/App/SketchObject.cpp [hunk 1]
```diff
@@ -9135,7 +9137,7 @@ void SketchObject::rebuildExternalGeometry(bool defining, bool addIntersection)
         if(!refSet.count(egf->getRef())) {
             FC_ERR( "External geometry " << getFullName() << ".e" << egf->getId()
                     << " missing reference: " << egf->getRef());
-            hasError = true;
+             hasError = true;
```
Comment (chennes) [inline src/Mod/Sketcher/App/SketchObject.cpp:9140]:
```suggestion
            hasError = true;
```
