### PR TITLE
Sketcher: Fix Freeze in Offset with too large negative value

### LINKED ISSUE #22218: Sketcher freezes if offset a rectangle with a too big negative value
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Problem description

Sketcher on XY plane, I draw a rectangle, i.e. 1m x 1m or whatever. Then I select the rectangle, click on the offset tool and enter (i.e. by mistake, it happens!) a negative offset with dimension too big, bigger than the rectangle (i.e. -2m), Freecad hangs / freezes.
If I try the same with a circle then a blast of error messages appears in the report window, but at least the program does not freeze.
With a circle I have:
`23:07:21  <Exception> makeOffset2D: result of offsetting is null!
23:07:22  <Exception> makeOffset2D: result of offsetting is null!
23:07:23  Unhandled exception in ViewProvider::eventCallback: makeOffset2D: result of offsetting is null!
(Event type: SoLocation2Event, object type: SketcherGui::ViewProviderSketch)
23:07:23  Unhandled exception in ViewProvider::eventCallback: makeOffset2D: result of offsetting is null!
(Event type: SoLocation2Event, object type: SketcherGui::ViewProviderSketch)`
(the output is 277 lines long...)
With the circle I have an error even if I visually drag the offset with the mouse to a very narrow value, i.e. -0.08, then just one message this time appears
`23:14:24  Unhandled exception in ViewProvider::eventCallback: makeOffset2D: result of offsetting is null!
(Event type: SoLocation2Event, object type: SketcherGui::ViewProviderSketch)
`
I've tested with 1.0.1 and I have this problem also (well, if I use the circle and the mouse, I have more error messages).

### Full version info

```shell
OS: Arch Linux (KDE/plasma/wayland)
Architecture: x86_64
Version: 1.1.0dev.42325 (Git) AppImage
Build date: 2025/06/24 17:49:05
Build type: Release
Branch: main
Hash: f3980c8a6fd65f82d3e61d229d26ad0eb57265c1
Python 3.11.13, Qt 6.8.3, Coin 4.0.3, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.2.5, IfcOpenShell 0.8.2, OCC 7.8.1
Locale: Italian/Italy (it_IT)
Navigation Style/Orbit Style/Rotation Mode: Blender/Trackball/Drag at cursor
Stylesheet/Theme/QtStyle: FreeCAD Light.qss/FreeCAD Light/
Logical DPI/Physical DPI/Pixel Ratio: 96/161.962/1
```

### Subproject(s) affected?

Sketcher

### Anything else?

_No response_

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by matthiasdanner**
## Issues

Fixes #22218 

The Problem here is an unsigned underflow in DrawSketchHandlerOffset::jointOffsetCurves, when the listOfOffsetGeoIds is Empty the for loop runs until the size_t maximum.

Also removes the error messages for circles. It's duplicated code not helping in this use case.

## Before and After Images

n/a

### CODE REVIEW

File: src/Mod/Sketcher/Gui/DrawSketchHandlerOffset.h [hunk 1]
```diff
@@ -344,6 +344,9 @@ class DrawSketchHandlerOffset: public DrawSketchHandlerOffsetBase
                        std::vector<int>& listOfOffsetGeoIds)
     {
         TopoDS_Shape offsetShape = makeOffsetShape();
+        if (offsetShape.IsNull()) {
+            return;
```
Comment (chennes) [inline src/Mod/Sketcher/Gui/DrawSketchHandlerOffset.h:348]: Should there be an error of some kind here? This looks like an invisible failure that the user gets no feedback on.

Comment (matthiasdanner) [reply src/Mod/Sketcher/Gui/DrawSketchHandlerOffset.h:348]: Sure, makes sense to present an error. But not here, this is also called, when the user moves the mouse.
I pushed a commit giving the user feedback, when he locks the offset in.

Are there any conventions on the error text or how the error should be presented?

**Comment by chennes** [comment]
Sorry for the delay here, @matthiasdanner --when testing this PR, I fell down this rabbit hole: https://github.com/FreeCAD/FreeCAD/issues/23628

**Comment by matthiasdanner** [comment]
Just rebased this to include the fix from #23853

**Comment by chennes** [comment]
Tested, works as advertised.
