### PR TITLE
[TD]Cosmetic vertex tag save/restore fail  (fix #21069)

### LINKED ISSUE #21069: Techdraw: PR19753 regression - files containing Axometric dimensions are not saved correctly causing the file to error on opening and work to be lost
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Problem description

Specifically Git Bisect found https://github.com/FreeCAD/FreeCAD/commit/2bbf6c7f6e5146c955f3d7110cb035a42e8ab30a to cause the issue as described in detail in https://forum.freecad.org/viewtopic.php?p=824451#p824256

The attached file was saved with a build prior to the above commit so opens error free but if saved as a different filename using the above commit there is no error on save but when subsequently opened the page is blank and an error in the Report View:

`Invalid Document.xml: End of document reached`

The tree is also corrupted:

Image

[Support_domad_Syres_with_axonometric_dim.FCStd.zip](https://github.com/user-attachments/files/19970992/Support_domad_Syres_with_axonometric_dim.FCStd.zip)

### Full version info

```shell
Hash: 2bbf6c7f6e5146c955f3d7110cb035a42e8ab30a
```

### Subproject(s) affected?

TechDraw

### Anything else?

_No response_

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by WandererFan**
This PR implements a fix for issue #21069.

### CODE REVIEW

File: src/Mod/TechDraw/App/Geometry.cpp [hunk 1]
```diff
@@ -1330,12 +1328,7 @@ void Vertex::Save(Base::Writer &writer) const
     writer.Stream() << writer.ind() << "<Cosmetic value=\"" <<  c2 << "\"/>" << endl;
     writer.Stream() << writer.ind() << "<CosmeticLink value=\"" <<  cosmeticLink << "\"/>" << endl;
     writer.Stream() << writer.ind() << "<CosmeticTag value=\"" <<  cosmeticTag << "\"/>" << endl;
-
-    //do we need to save this?  always recreated by program.
-//    const char r = reference?'1':'0';
-//    writer.Stream() << writer.ind() << "<Reference value=\"" <<  r << "\"/>" << endl;
-
-    Tag::Save(writer);
+    writer.Stream() << writer.ind() << "<VertexTag value=\"" <<  getTagAsString() << "\"/>" << endl;
```
Comment (benj5378) [inline src/Mod/TechDraw/App/Geometry.cpp:1331]: We need to keep sacing it as `<Tag />` so we can deprecate `<VertexTag />` sometime in the future and simplify logic. The solution should be `Tag::Restore` both accepting `<Tag />` and `<VertexTag />`.

Comment (WandererFan) [reply src/Mod/TechDraw/App/Geometry.cpp:1331]: If you have a Tag::Save here and another one in CosmeticVertex, you'll get 2 Tag entries in the xml.   When the time comes to remove VertexTag, we'll delete lines 1331 and 1355.

**Comment by WandererFan** [comment]
Merge meeting asked for (int) cast to be changed to use <int> template specialization.

**Comment by hyarion** [comment]
Correct me if I'm wrong, but doesn't this reintroduce `<VertexTag>` in documents again instead of migrating towards `<Tag>`? Also it also introduces the function `Vertex::restoreVertexTag` to restore tags, when I think the intention was to centralize all tag saving in `Tag` class?

You proposed a solution on https://github.com/FreeCAD/FreeCAD/issues/21069#issuecomment-2847113075, that is more simple, easy to remove (once migration is done) and within the intention of the original of centralizing the tag handling (https://github.com/FreeCAD/FreeCAD/pull/19753).
Why don't we use that instead?

**Comment by WandererFan** [comment]
@edi271: thanks for testing.  for case 3 above, is it the 1.0 version that can't read files made with this patch?  if it is a  version before 1.0, then I guess it is ok that v0.20 can't read v1.0 files

**Comment by edi271** [comment]
> @edi271: thanks for testing. for case 3 above, is it the 1.0 version that can't read files made with this patch? if it is a version before 1.0, then I guess it is ok that v0.20 can't read v1.0 files

The latest version I have that cannot open is:

OS: Ubuntu 22.04.5 LTS (ubuntu:GNOME/ubuntu/xcb)
Architecture: x86_64
Version: 1.1.0dev.40655 (Git) Conda AppImage
Build date: 2025/03/10 16:51:09
Build type: Release
Branch: main
Hash: f311bfc839a4c00eff9bfb294c4ec9f670410296
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, IfcOpenShell 0.7.0, OCC 7.7.2
Locale: German/Austria (de_AT)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Fusion
Logical DPI/Physical DPI/Pixel Ratio: 96/91.7275/1

**Comment by chennes** [comment]
@WandererFan we looked at this in the meeting, but it seems there is still some discussion, and a merge conflict.

**Comment by WandererFan** [comment]
Merge conflicts fixed.

What is the discussion?
