### PR TITLE
Fix #11449 3rdPart/salomesmesh vtk 9.3 compatibility

### LINKED ISSUE #11449: [Problem] Fails to build against VTK 9.3.0 (due to 3rd party salome mesh code)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

FreeCAD fails to build against latest VTK 9.3.0
```
  [19/4686] Building CXX object src/3rdParty/salomesmesh/CMakeFiles/SMDS.dir/src/SMDS/SMDS_FaceOfNodes.cpp.obj
  FAILED: src/3rdParty/salomesmesh/CMakeFiles/SMDS.dir/src/SMDS/SMDS_FaceOfNodes.cpp.obj 
  D:\M\msys64\clang64\bin\clang++.exe -DBOOST_PP_VARIADICS=1 -DCSFDB -DDIY_NO_THREADS -DH5_BUILT_AS_DYNAMIC_LIB -DHAVE_CONFIG_H -DHAVE_D3D -DHAVE_FFMPEG -DHAVE_FREEIMAGE -DHAVE_FREETYPE -DHAVE_OPENGL_EXT -DHAVE_OPENVR -DHAVE_RAPIDJSON -DHAVE_SNPRINTF -DHAVE_TBB -DHAVE_TK -DHAVE_VTK -DKISSFFT_DLL_IMPORT=1 -DOCC_CONVERT_SIGNALS -DPYCXX_6_2_COMPATIBILITY -DQT_NO_KEYWORDS -DSMDS_EXPORTS -DUNICODE -DVTK_OPENGL2_BACKEND -DWIN32 -DWNT -D_OCC64 -D_UNICODE -D_WINDOWS -Dkiss_fft_scalar=double -IC:/_/B/src/build-CLANG64/src/3rdParty/salomesmesh/SMDS_autogen/include -IC:/_/B/src/build-CLANG64 -IC:/_/B/src/build-CLANG64/src -IC:/_/B/src/FreeCAD-0.21.2/src -IC:/_/B/src/FreeCAD-0.21.2/src/3rdParty/salomesmesh/src/SMDS -IC:/_/B/src/FreeCAD-0.21.2/src/3rdParty/salomesmesh/src/Driver -IC:/_/B/src/FreeCAD-0.21.2/src/3rdParty/salomesmesh/src/DriverUNV -IC:/_/B/src/FreeCAD-0.21.2/src/3rdParty/salomesmesh/src/DriverDAT -IC:/_/B/src/FreeCAD-0.21.2/src/3rdParty/salomesmesh/src/DriverSTL -IC:/_/B/src/FreeCAD-0.21.2/src/3rdParty/salomesmesh/src/StdMeshers -IC:/_/B/src/FreeCAD-0.21.2/src/3rdParty/salomesmesh/inc -IC:/_/B/src/build-CLANG64/src/3rdParty/salomesmesh -isystem D:/M/msys64/clang64/include/opencascade -isystem D:/M/msys64/clang64/include/vtk -isystem D:/M/msys64/clang64/include/freetype2 -Wall -Wextra -Wpedantic -Wno-write-strings -march=nocona -msahf -mtune=generic -O2 -pipe -Wno-attributes -Wno-self-assign -Wno-sign-compare -Wno-logical-op-parentheses -Wno-reorder -Wno-switch -Wno-switch-enum -Wno-unknown-pragmas -Wno-unused-variable -Wno-unused-private-field -Wno-unused-function -Wno-sometimes-uninitialized -Wno-overloaded-virtual -Wno-dynamic-class-memaccess -Wno-comment -Wno-unused-parameter -Wno-extra-semi -Wno-deprecated-copy -Wno-missing-field-initializers -Wno-c++17-extensions -O3 -DNDEBUG -std=gnu++17 -DSMDS_EXPORTS -DUTILS_EXPORTS -pthread -fopenmp=libomp -MD -MT src/3rdParty/salomesmesh/CMakeFiles/SMDS.dir/src/SMDS/SMDS_FaceOfNodes.cpp.obj -MF src\3rdParty\salomesmesh\CMakeFiles\SMDS.dir\src\SMDS\SMDS_FaceOfNodes.cpp.obj.d -o src/3rdParty/salomesmesh/CMakeFiles/SMDS.dir/src/SMDS/SMDS_FaceOfNodes.cpp.obj -c C:/_/B/src/FreeCAD-0.21.2/src/3rdParty/salomesmesh/src/SMDS/SMDS_FaceOfNodes.cpp
  In file included from C:/_/B/src/FreeCAD-0.21.2/src/3rdParty/salomesmesh/src/SMDS/SMDS_FaceOfNodes.cpp:33:
  In file included from C:/_/B/src/FreeCAD-0.21.2/src/3rdParty/salomesmesh/inc/SMDS_Mesh.hxx:45:
  In file included from C:/_/B/src/FreeCAD-0.21.2/src/3rdParty/salomesmesh/inc/SMDS_VtkVolume.hxx:26:
  C:/_/B/src/FreeCAD-0.21.2/src/3rdParty/salomesmesh/inc/SMDS_UnstructuredGrid.hxx:71:26: error: virtual function 'GetMTime' has a different return type ('unsigned long') than the function it overrides (which has return type 'vtkMTimeType' (aka 'unsigned long long'))
     71 |   virtual VTK_MTIME_TYPE GetMTime();
        |           ~~~~~~~~~~~~~~ ^
  D:/M/msys64/clang64/include/vtk/vtkPointSet.h:208:16: note: overridden virtual function is here
    208 |   vtkMTimeType GetMTime() override;
        |   ~~~~~~~~~~~~ ^
  In file included from C:/_/B/src/FreeCAD-0.21.2/src/3rdParty/salomesmesh/src/SMDS/SMDS_FaceOfNodes.cpp:33:
  In file included from C:/_/B/src/FreeCAD-0.21.2/src/3rdParty/salomesmesh/inc/SMDS_Mesh.hxx:45:
  In file included from C:/_/B/src/FreeCAD-0.21.2/src/3rdParty/salomesmesh/inc/SMDS_VtkVolume.hxx:26:
  C:/_/B/src/FreeCAD-0.21.2/src/3rdParty/salomesmesh/inc/SMDS_UnstructuredGrid.hxx:99:39: warning: 'GetCellLinks' is deprecated: Use GetLinks() instead. [-Wdeprecated-declarations]
     99 |     return static_cast<vtkCellLinks*>(GetCellLinks());
        |                                       ^
  D:/M/msys64/clang64/include/vtk/vtkUnstructuredGrid.h:289:3: note: 'GetCellLinks' has been explicitly marked deprecated here
    289 |   VTK_DEPRECATED_IN_9_3_0("Use GetLinks() instead.")
        |   ^
  D:/M/msys64/clang64/include/vtk/vtkDeprecation.h:99:41: note: expanded from macro 'VTK_DEPRECATED_IN_9_3_0'
     99 | #define VTK_DEPRECATED_IN_9_3_0(reason) VTK_DEPRECATION(reason)
  
        |                                         ^
  
  D:/M/msys64/clang64/include/vtk/vtkDeprecation.h:77:44: note: expanded from macro 'VTK_DEPRECATION'
  
     77 | #define VTK_DEPRECATION(reason) __declspec(deprecated(reason))
  
        |                                            ^
  
  1 warning and 1 error generated.
```

### Full version info

```shell
0.21.2
```

### Subproject(s) affected?

None

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by adrianinsaval**
vtkMTimeType was introduced in vtk 7.1 so minimum required vtk version with this is 7.1 which available on ubuntu 20.04

@wwmayer

### CODE REVIEW

File: src/3rdParty/salomesmesh/src/SMDS/SMDS_UnstructuredGrid.cpp [hunk 1]
```diff
@@ -1026,7 +1026,12 @@ void SMDS_UnstructuredGrid::BuildLinks()
   GetLinks()->Allocate(this->GetNumberOfPoints());
   GetLinks()->Register(this);
 //FIXME: vtk9
+  #if VTK_VERSION_NUMBER < VTK_VERSION_CHECK(9,3,0)
```
Comment (wwmayer) [inline src/3rdParty/salomesmesh/src/SMDS/SMDS_UnstructuredGrid.cpp:1029]: Where are VTK_VERSION_NUMBER and VTK_VERSION_CHECK are defined?

Comment (adrianinsaval) [reply src/3rdParty/salomesmesh/src/SMDS/SMDS_UnstructuredGrid.cpp:1029]: https://kitware.github.io/paraview-docs/latest/cxx/vtkVersionMacros_8h.html

I'm not sure whre it gets included but compilation suceeded for me on arch and on ubuntu

Comment (adrianinsaval) [reply src/3rdParty/salomesmesh/src/SMDS/SMDS_UnstructuredGrid.cpp:1029]: Hhhmmm I'm not finding these on 7.1.1 source code though

Comment (adrianinsaval) [reply src/3rdParty/salomesmesh/src/SMDS/SMDS_UnstructuredGrid.cpp:1029]: yeah seems it was added in vtk 8 https://gitlab.kitware.com/vtk/vtk/-/commit/2b94edcd2b74fb6f523c96a01c6b930313053215

File: src/3rdParty/salomesmesh/src/SMDS/SMDS_UnstructuredGrid.cpp [hunk 2]
```diff
@@ -1026,7 +1026,12 @@ void SMDS_UnstructuredGrid::BuildLinks()
...
   GetLinks()->BuildLinks(this);
+  #else
+  GetLinks()->SetDataSet(this);
+  GetLinks()->BuildLinks();
+  #endif
```
Comment (adrianinsaval) [inline src/3rdParty/salomesmesh/src/SMDS/SMDS_UnstructuredGrid.cpp:1034]: how about:
```suggestion
  #if VTK_MAJOR_VERSION >= 9 && VTK_MINOR_VERSION >= 3
  GetLinks()->SetDataSet(this);
  GetLinks()->BuildLinks();
  #else
  GetLinks()->BuildLinks(this);
  #endif
```
these should be available on 7.1: https://gitlab.kitware.com/vtk/vtk/-/blob/v7.1.0/Common/Core/vtkVersionMacros.h.in?ref_type=tags

**Comment by wwmayer** [comment]
I think the PR should be fine as the version check macro is used inside the VTK_CELL_ARRAY_V2 which IIRC is also defined for >= vtk8.
