### PR TITLE
Fix python Test

### LINKED ISSUE #29069: freecad weekly test failures
### Problem description

I've been working on making a package of freecad weekly for opensuse tumbleweed
during this I found that 2 tests fail.
1532 - TestLineFormat.setQColorKeepsOpaqueColorsOpaque (SEGFAULT)
1533 - TestLineFormat.setQColorPreservesAlphaValue (SEGFAULT)

while attempting a local build I also see: 
866 - FileInfoTest.TestDirectoryContent (SEGFAULT)

but this might be build environment related as this test also fails:
863 - FileInfoTest.TestDirectoryPath (Failed)

but likely shouldn't segfault either. 

### Workbench affected?

None

### Steps to reproduce

build using obs on opensuse tumbleweed, spec file etc can be found here: https://build.opensuse.org/package/show/home:magnade/FreeCAD-weekly

### Expected behavior

not segfaulting

### Actual behavior

see above
attached is full build log from obs

[20260401-weekly-buildlog.txt](https://github.com/user-attachments/files/26484440/20260401-weekly-buildlog.txt)

### Development version About Info (in Safe Mode)

```shell
20260401 weekly sources, no package made yet so can't pull this.
```

### Last known good version (optional)

```shell
I believe I a working build of 1.1 at least once (still refining that package to submit into tumbleweed), I'll follow up whenever I get a working copy of that.
```

### PR DESCRIPTION
**Pull request by filippor**
## Issues

Fix all Tests

I see that for current build the tests are skipped
if needed it's possible to enable fedora build and test on main branch

## Before and After Images

before: https://artifacts.dev.testing-farm.io/9432aeea-390c-489e-995f-6141cce9f775/
after: https://artifacts.dev.testing-farm.io/ec8e9d49-c234-4227-b1cc-3f586c5d9f23/

This PR is splitted in #28038 #28039 #28040 #28041

### CODE REVIEW

File: tests/src/Base/FileInfo.cpp [hunk 1]
```diff
@@ -3,14 +3,37 @@
...
 {
+
+    std::string createUniqueTempDirectory(const std::string& prefix)
+    {
+        auto tempPath = std::filesystem::path(Base::FileInfo::getTempPath());
+
+        for (int suffix = 0;; ++suffix) {
+            auto candidatePath = tempPath / (prefix + "_" + std::to_string(suffix));
+            std::error_code ec;
+            if (std::filesystem::create_directory(candidatePath, ec)) {
```
Comment (hyarion) [inline tests/src/Base/FileInfo.cpp]: Looks like you create a new directory every time. How about using https://doc.qt.io/qt-6/qtemporarydir.html instead?

Comment (filippor) [reply tests/src/Base/FileInfo.cpp]: Yes the scope is to create a unique directory to avoid problems if tests are run in parallel with ctest -j#
Thanks I will update.

Comment (filippor) [reply tests/src/Base/FileInfo.cpp]: reverted see https://github.com/FreeCAD/FreeCAD/pull/28513#issuecomment-4155307639

**Comment by chennes** [comment]
When I run these tests in my local copy of FreeCAD (so with the GUI), I still see the following failure:
```
Traceback (most recent call last):
  File "/Users/chennes/Documents/FreeCAD/.pixi/envs/default/lib/python3.11/unittest/case.py", line 57, in testPartExecutor
    yield
  File "/Users/chennes/Documents/FreeCAD/.pixi/envs/default/lib/python3.11/unittest/case.py", line 623, in run
    self._callTestMethod(testMethod)
  File "/Users/chennes/Documents/FreeCAD/.pixi/envs/default/lib/python3.11/unittest/case.py", line 579, in _callTestMethod
    if method() is not None:
       ^^^^^^^^
  File "/Users/chennes/Documents/FreeCAD/build/debug/Mod/Fem/femtest/app/test_open.py", line 138, in test_femobjects_open_de9b3fb438
    self.compare_feature_pythons_class_app(self.document)
  File "/Users/chennes/Documents/FreeCAD/build/debug/Mod/Fem/femtest/app/test_open.py", line 272, in compare_feature_pythons_class_app
    self.assertEqual(SolverZ88, doc.SolverZ88.Proxy.__class__)
AssertionError: <class 'femobjects.solver_z88.SolverZ88'> != <class 'femsolver.z88.solver.Proxy'>
```
I take it you aren't seeing this problem?

**Comment by filippor** [comment]
https://artifacts.dev.testing-farm.io/6bb809b3-941e-4a2e-8e93-b1fac697bb41/

This is the latest report

**Comment by filippor** [comment]
@chennes local test run with calculix-ccx and pyNastran installed I get this error:

```
$ ./build/bin/FreeCAD -t femtest.gui.test_open.TestObjectOpen.test_femobjects_open_de9b3fb438
FreeCAD 1.2.0, Libs: 1.2.0devR46328 +66 (Git)
(C) 2001-2026 FreeCAD contributors
FreeCAD is free and open-source software licensed under the terms of LGPL2+ license.

Cannot access /home/filippor/.local/share/FreeCAD/v1-2/Mod/Freecad-Built-in-themes-beta/Classic light
import TestObjectCreate 
import TestObjectType 
import TestObjectOpen 
test_femobjects_open_de9b3fb438 (femtest.gui.test_open.TestObjectOpen.test_femobjects_open_de9b3fb438) ... load old document objects 


Traceback (most recent call last):
  File "/home/filippor/git/f-freecad/FreeCAD/build/Mod/Fem/femviewprovider/view_material_common.py", line 61, in claimChildren
    nonlin = self.Object.Nonlinear
<class 'AttributeError'>: 'FeaturePython' object has no attribute 'Nonlinear'
Traceback (most recent call last):
  File "/home/filippor/git/f-freecad/FreeCAD/build/Mod/Fem/femviewprovider/view_material_common.py", line 61, in claimChildren
    nonlin = self.Object.Nonlinear
<class 'AttributeError'>: 'FeaturePython' object has no attribute 'Nonlinear'
Traceback (most recent call last):
  File "/home/filippor/git/f-freecad/FreeCAD/build/Mod/Fem/femviewprovider/view_mesh_gmsh.py", line 212, in claimChildren
    def_childs = self.Object.MeshRefinementList
<class 'AttributeError'>: 'FeaturePython' object has no attribute 'MeshRefinementList'

ok

----------------------------------------------------------------------
Ran 1 test in 1.319s

OK
System exit

```
with safe mode 
```
./build/bin/FreeCAD --safe-mode -t femtest.gui.test_open.TestObjectOpen.test_femobjects_open_de9b3fb438
FreeCAD 1.2.0, Libs: 1.2.0devR46391 +11 (Git)
(C) 2001-2026 FreeCAD contributors
FreeCAD is free and open-source software licensed under the terms of LGPL2+ license.

FreeCAD is running in _SAFE_MODE_.
Safe mode temporarily disables your configurations and addons. Restart the application to exit safe mode.

Migrating Start Workbench to Start command... done.
import TestObjectCreate 
import TestObjectType 
import TestObjectOpen 
test_femobjects_open_de9b3fb438 (femtest.gui.test_open.TestObjectOpen.test_femobjects_open_de9b3fb438) ... load old document objects 



ok

----------------------------------------------------------------------
Ran 1 test in 1.001s

OK
System exit

```

and all TestFemApp `./build/bin/FreeCAD --safe-mode -t TestFemApp`
```
Program received signal SIGSEGV, Segmentation fault.
#0  /lib64/libc.so.6(+0x1a290) [0x7fdc41e27290]
#1  0x7fdc4311074d in QOpenGLContext::format() const from /lib64/libQt6Gui.so.6+0xd
#2  0x7fdc43110848 in QOpenGLContext::isOpenGLES() const from /lib64/libQt6Gui.so.6+0x28
#3  0x7fdc45565ffd in QOpenGLFramebufferObject::QOpenGLFramebufferObject(int, int, QOpenGLFramebufferObject::Attachment, unsigned int, unsigned int) from /lib64/libQt6OpenGL.so.6+0xed
#4  0x7fdc48301114 in NaviCubeImplementation::ensureFramebufferValid() from /home/filippor/git/f-freecad/FreeCAD/build/lib/libFreeCADGui.so+0x1ac
#5  0x7fdc483011df in NaviCubeImplementation::pickFace(short, short) from /home/filippor/git/f-freecad/FreeCAD/build/lib/libFreeCADGui.so+0x5f
#6  0x7fdc48302003 in NaviCubeImplementation::mouseMoved(short, short) from /home/filippor/git/f-freecad/FreeCAD/build/lib/libFreeCADGui.so+0xfb
#7  0x7fdc4830246c in NaviCubeImplementation::processSoEvent(SoEvent const*) from /home/filippor/git/f-freecad/FreeCAD/build/lib/libFreeCADGui.so+0x212
#8  0x7fdc482fe4ab in NaviCube::processSoEvent(SoEvent const*) from /home/filippor/git/f-freecad/FreeCAD/build/lib/libFreeCADGui.so+0x27
#9  0x7fdc482a8189 in Gui::View3DInventorViewer::processSoEvent(SoEvent const*) from /home/filippor/git/f-freecad/FreeCAD/build/lib/libFreeCADGui.so+0x39
#10  0x7fdc48262d32 in SIM::Coin3D::Quarter::EventFilter::eventFilter(QObject*, QEvent*) from /home/filippor/git/f-freecad/FreeCAD/build/lib/libFreeCADGui.so+0x15c
#11  0x7fdc424fdafa in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) from /lib64/libQt6Core.so.6+0x7a
#12  0x7fdc4383de8f in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /lib64/libQt6Widgets.so.6+0x7f
#13  0x7fdc43848856 in QApplication::notify(QObject*, QEvent*) from /lib64/libQt6Widgets.so.6+0xd66
#14  0x7fdc47a65f81 in Gui::GUIApplication::notify(QObject*, QEvent*) from /home/filippor/git/f-freecad/FreeCAD/build/lib/libFreeCADGui.so+0x133
#15  0x7fdc424fdd88 in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /lib64/libQt6Core.so.6+0x168
#16  0x7fdc438471f9 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) from /lib64/libQt6Widgets.so.6+0x629
#17  /lib64/libQt6Widgets.so.6(+0xbec82) [0x7fdc438bec82]
#18  /lib64/libQt6Widgets.so.6(+0xc1b63) [0x7fdc438c1b63]
#19  0x7fdc4383de9f in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /lib64/libQt6Widgets.so.6+0x8f
#20  0x7fdc47a65f81 in Gui::GUIApplication::notify(QObject*, QEvent*) from /home/filippor/git/f-freecad/FreeCAD/build/lib/libFreeCADGui.so+0x133
#21  0x7fdc424fdd88 in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /lib64/libQt6Core.so.6+0x168
#22  0x7fdc42cf441b in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) from /lib64/libQt6Gui.so.6+0xb7b
#23  0x7fdc42d5ef4c in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /lib64/libQt6Gui.so.6+0xac
#24  /lib64/libQt6Gui.so.6(+0x6fc2f4) [0x7fdc432fc2f4]
#25  /lib64/libglib-2.0.so.0(+0x41323) [0x7fdc40eeb323]
#26  /lib64/libglib-2.0.so.0(+0x4a278) [0x7fdc40ef4278]
#27  /lib64/libglib-2.0.so.0(g_main_context_iteration+0x33) [0x7fdc40ef4423]
#28  0x7fdc4282141d in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /lib64/libQt6Core.so.6+0x5d
#29  0x7fdc47995347 in Gui::ApplicationPy::sUpdateGui(_object*, _object*) from /home/filippor/git/f-freecad/FreeCAD/build/lib/libFreeCADGui.so+0x5b
#30  /lib64/libpython3.14.so.1.0(+0x184ad4) [0x7fdc44f84ad4]
#31  /lib64/libpython3.14.so.1.0(_PyObject_MakeTpCall+0x444) [0x7fdc44f4c2e4]
#32  /lib64/libpython3.14.so.1.0(_PyEval_EvalFrameDefault+0xa8e2) [0x7fdc44f6dbf2]
#33  /lib64/libpython3.14.so.1.0(+0x1d886c) [0x7fdc44fd886c]
#34  /lib64/libpython3.14.so.1.0(_PyEval_EvalFrameDefault+0x4af7) [0x7fdc44f67e07]
#35  /lib64/libpython3.14.so.1.0(+0x15fa45) [0x7fdc44f5fa45]
#36  /lib64/libpython3.14.so.1.0(+0x24e8cc) [0x7fdc4504e8cc]
#37  /lib64/libpython3.14.so.1.0(+0x2af1e6) [0x7fdc450af1e6]
#38  /lib64/libpython3.14.so.1.0(_PyObject_MakeTpCall+0x444) [0x7fdc44f4c2e4]
#39  /lib64/libpython3.14.so.1.0(_PyEval_EvalFrameDefault+0x13b6) [0x7fdc44f646c6]
#40  /lib64/libpython3.14.so.1.0(+0x1d886c) [0x7fdc44fd886c]
#41  /lib64/libpython3.14.so.1.0(_PyEval_EvalFrameDefault+0x4af7) [0x7fdc44f67e07]
#42  /lib64/libpython3.14.so.1.0(+0x15fa45) [0x7fdc44f5fa45]
#43  /lib64/libpython3.14.so.1.0(+0x24e8cc) [0x7fdc4504e8cc]
#44  /lib64/libpython3.14.so.1.0(+0x2af1e6) [0x7fdc450af1e6]
#45  /lib64/libpython3.14.so.1.0(_PyObject_MakeTpCall+0x444) [0x7fdc44f4c2e4]
#46  /lib64/libpython3.14.so.1.0(_PyEval_EvalFrameDefault+0x13b6) [0x7fdc44f646c6]
#47  /lib64/libpython3.14.so.1.0(+0x1d886c) [0x7fdc44fd886c]
#48  /lib64/libpython3.14.so.1.0(_PyEval_EvalFrameDefault+0x4af7) [0x7fdc44f67e07]
#49  /lib64/libpython3.14.so.1.0(+0x15fa45) [0x7fdc44f5fa45]
#50  /lib64/libpython3.14.so.1.0(+0x24e8cc) [0x7fdc4504e8cc]
#51  /lib64/libpython3.14.so.1.0(+0x2af1e6) [0x7fdc450af1e6]
#52  /lib64/libpython3.14.so.1.0(_PyObject_MakeTpCall+0x444) [0x7fdc44f4c2e4]
#53  /lib64/libpython3.14.so.1.0(_PyEval_EvalFrameDefault+0xc9b) [0x7fdc44f63fab]
#54  /lib64/libpython3.14.so.1.0(+0x15fa45) [0x7fdc44f5fa45]
#55  /lib64/libpython3.14.so.1.0(PyEval_EvalCode+0xb7) [0x7fdc45050c87]
#56  /lib64/libpython3.14.so.1.0(+0x292729) [0x7fdc45092729]
#57  /lib64/libpython3.14.so.1.0(+0x28c972) [0x7fdc4508c972]
#58  0x7fdc462abc14 in Base::InterpreterSingleton::runString[abi:cxx11](char const*) from /home/filippor/git/f-freecad/FreeCAD/build/lib/libFreeCADBase.so+0xfc
#59  0x7fdc48436864 in Gui::MainWindow::delayedStartup() from /home/filippor/git/f-freecad/FreeCAD/build/lib/libFreeCADGui.so+0xc2
#60  /home/filippor/git/f-freecad/FreeCAD/build/lib/libFreeCADGui.so(+0xc3ec07) [0x7fdc4843ec07]
#61  0x7fdc4255af1c in QObject::event(QEvent*) from /lib64/libQt6Core.so.6+0x14c
#62  0x7fdc4843362d in Gui::MainWindow::event(QEvent*) from /home/filippor/git/f-freecad/FreeCAD/build/lib/libFreeCADGui.so+0x6d7
#63  0x7fdc4383de9f in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /lib64/libQt6Widgets.so.6+0x8f
#64  0x7fdc47a65f81 in Gui::GUIApplication::notify(QObject*, QEvent*) from /home/filippor/git/f-freecad/FreeCAD/build/lib/libFreeCADGui.so+0x133
#65  0x7fdc424fdd88 in QCoreApplication::notifyInternal2(QObject*, QEvent*) from /lib64/libQt6Core.so.6+0x168
#66  0x7fdc42501979 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) from /lib64/libQt6Core.so.6+0x369
#67  /lib64/libQt6Core.so.6(+0x421f0f) [0x7fdc42821f0f]
#68  /lib64/libglib-2.0.so.0(+0x41323) [0x7fdc40eeb323]
#69  /lib64/libglib-2.0.so.0(+0x4a278) [0x7fdc40ef4278]
#70  /lib64/libglib-2.0.so.0(g_main_context_iteration+0x33) [0x7fdc40ef4423]
#71  0x7fdc4282141d in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /lib64/libQt6Core.so.6+0x5d
#72  0x7fdc4250ad63 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) from /lib64/libQt6Core.so.6+0x1a3
#73  0x7fdc42506649 in QCoreApplication::exec() from /lib64/libQt6Core.so.6+0xa9
#74  /home/filippor/git/f-freecad/FreeCAD/build/lib/libFreeCADGui.so(+0x13e7d1) [0x7fdc4793e7d1]
#75  /home/filippor/git/f-freecad/FreeCAD/build/lib/libFreeCADGui.so(+0x13eb61) [0x7fdc4793eb61]
#76  0x7fdc4793ef6b in Gui::Application::runApplication() from /home/filippor/git/f-freecad/FreeCAD/build/lib/libFreeCADGui.so+0x30f
#77  ./build/bin/FreeCAD() [0x401d0a]
#78  /lib64/libc.so.6(+0x35b5) [0x7fdc41e105b5]
#79  /lib64/libc.so.6(__libc_start_main+0x88) [0x7fdc41e10668]
#80  ./build/bin/FreeCAD() [0x400a05]

```

**Comment by chennes** [comment]
@marioalexis84 and/or @FEA-eng can you run these FEM tests locally and replicate that failure?

**Comment by filippor** [comment]
> @marioalexis84 and/or @FEA-eng can you run these FEM tests locally and replicate that failure?

I added more fix. to avoid Segmentation fault

**Comment by FEA-eng** [comment]
> @marioalexis84 and/or @FEA-eng can you run these FEM tests locally and replicate that failure?

In the latest weekly, all `TestFemApp` tests pass for me in Safe Mode:

image

Later, I can check how it works with this PR.

**Comment by marioalexis84** [comment]
> @marioalexis84 and/or @FEA-eng can you run these FEM tests locally and replicate that failure?

of course

**Comment by marioalexis84** [comment]
> When I run these tests in my local copy of FreeCAD (so with the GUI), I still see the following failure

@chennes That error is usually related to class migration of proxy objects. Old Python modules (in this case, z88/tasks.py and z88/solver.py) are likely still present in the build/install directory. Just remove them manually or perform a clean build.

> @marioalexis84 and/or @FEA-eng can you run these FEM tests locally and replicate that failure?


For me, this doesn't fix the Python3.14/Pyside6 crashes in console mode when running tests cases.

**Comment by filippor** [comment]
In this branch the test pass on fedora 43 with python 3.14 and pyside6 both local and in test farm

https://artifacts.dev.testing-farm.io/d1f65f5c-a94e-4d7f-aaa3-456ff8725216

**Comment by chennes** [comment]
OK, @filippor I think the test changes themselves should be good to merge now. Can you pull the automatic Fedora building back out now?

**Comment by filippor** [comment]
@chennes do I leave the fedora build and test active on main branch or we discuss it when we move the packaging on external repo?

**Comment by filippor** [comment]
now the automatic build is enabled only for release as in current main
