### PR TITLE
[Spreadsheet] Enable zoom in Spreadsheet

### LINKED ISSUE #6094: [Feature] Spreadsheet: Ability to Zoom in/out (per Excel and LibreCalc)
Issue imported from https://tracker.freecad.org/view.php?id=4410

* **Reporter:** TomB19
* **Date submitted:** 7/25/2020
* **FreeCAD version:** 
* **Category:** Feature
* **Status:** new
* **Tags:** 

# Original report text

I would like to request the ability to zoom spreadsheets.  This would be useful, as I appreciate being able to shrink the spreadsheet to get more information on the screen.

This feature has been implemented using Python by OpenBrain and posted in the forum.

This request is to add implement this feature, likely in C++, in the next release or whenever you feel appropriate.

https://forum.freecadweb.org/viewtopic.php?f=3&t=48517

# Steps to reproduce

https://forum.freecadweb.org/viewtopic.php?f=3&t=48517

# Other bug information

* **Priority:** normal
* **Severity:** feature
* **Category:** Feature
* **Updated:** 11/24/2021

### PR DESCRIPTION
**Pull request by xtemp09**
This commit implements zoom in _Spreadsheet WB_, making it look like any other spreadsheet editor. So far, the code looks like a dirty hack; to make it beautiful one needs huge amount of efforts, I estimate it at one month of work.

In the meantime, this is a patch. The commit creates a _QGraphicsView_ descendant and shows the table in viewport. _QGraphicsView_ allows magnification and animation, the latter can be added in the future. The commit adds an option for default zoom in settings.

The following items have to be considered by testers:

- I don't have an opportunity to test the commit on _Windows_ and _MacOS_. So far, I have tried it on _KUbuntu 22.04.4 LTS (Jammy Jellyfish)_ with _Qt 5.15.14_ and _Qt 6.7.2_.
- I don't have an opportunity to check the behavior with trackpad/trackball/touchpad. Perhaps, some unusual settings can also be tested, like altered scroll speed of the mouse wheel.
- I don't have an opportunity to test the commit on HiDPI platform, even though HiDPI is the reason to have zoom in the first place.
- The commit uses the percent sign without a space between the number and percent sign.
- This commit also fixes tab order of Spreadsheet settings in _Preferences_.

Closes #6094.

### CODE REVIEW

File: src/Mod/Spreadsheet/Gui/ZoomableView.cpp [hunk 1]
```diff
@@ -0,0 +1,228 @@
...
+
+void ZoomableView::zoomOut(void)
+{
+    setZoomLevel(m_zoomLevel - zoom_step_kb);
+}
+
+void ZoomableView::updateView(void)
+{
+    /* Qt has hardcoded margins because of which
+     * I have to manually calculate the geometry instead of using fitInView
```
Comment (luzpaz) [inline src/Mod/Spreadsheet/Gui/ZoomableView.cpp:168]:
```
/* Qt has hardcoded margins therefore we must
  * manually calculate the geometry instead of using fitInView
```

**Comment by luzpaz** [comment]
@xtemp09 any chance you can make a screencast of the feature in action ?

**Comment by xtemp09** [comment]
@luzpaz, 


https://github.com/user-attachments/assets/dc2ec926-ad62-44ad-8d5a-26d9b9367eee

**Comment by FEA-eng** [comment]
That's a really cool change, thanks.

**Review by luzpaz — COMMENTED** [review]
Thanks for fixing.

**Comment by luzpaz** [comment]
@johnocfii any chance you can test this on macOS ?

**Comment by JohnOCFII** [comment]
It hasn't merged yet, correct?  Today's pretty packed -- I don't have time to pull over the 9 modified files and re-build it locally - it could try it this weekend if still needed.

**Comment by luzpaz** [comment]
@JohnOCFII no rush. this will be in post-1.0

**Comment by JohnOCFII** [comment]
> @JohnOCFII any chance you can test this on macOS ?

Seems to work very well!  

This was built locally  from @xtemp09's Git zv branch:

Screenshot 2024-09-07 at 2 48 30 PM

Screenshot 2024-09-07 at 2 48 21 PM



```
OS: macOS 14.6.1
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38638 (Git)
Build type: Release
Branch: master
Hash: d6347a4b1516d2dc1e7f7e191073308ec049ac48
Python 3.11.8, Qt 5.15.8, Coin 4.0.2, Vtk 9.2.6, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * FeedsAndSpeeds 0.5.0
  * OpenTheme 2024.9.1
  * fasteners 0.5.28
  * Curves 0.6.47
```

**Comment by FEA-eng** [comment]
Tested, works as expected.

```
OS: Ubuntu 22.04.4 LTS (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38741 (Git)
Build type: Unknown
Branch: zv
Hash: 00f60aafca777204fba1a6ab12992d92ecd55b91
Python 3.10.12, Qt 5.15.3, Coin 4.0.0, Vtk , OCC 7.5.1
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
```

**Review by FEA-eng — APPROVED** [review]

**Comment by luzpaz** [comment]
Can this be merged soon ?

**Comment by hyarion** [comment]
From the description:
> So far, the code looks like a dirty hack; to make it beautiful one needs huge amount of efforts, I estimate it at one month of work.

@xtemp09 has the code been cleaned up or do you still consider it a dirty hack?

**Comment by xtemp09** [comment]
> @xtemp09 has the code been cleaned up or do you still consider it a dirty hack?



If one takes a look at the code of similar software, he will see how it is implemented ― via canvas and painting. In order to do this, one has to completely rewrite _Spreadsheets_. I used an incredibly simple solution ― put the widget onto _QGraphicsScene_ shown in _QGraphicsView_. On the bright side, it will allow something in the future, since _QGraphicsView_ allows magnification/rotation/animation and other things. Perhaps, in the future, somebody will implement something like animated highlighting.


If one takes a look at the screenshots or the video, he will see that there is an empty place a near the horizontal scrollbar. Similar software uses it as status bar. Once the PR is merged, I'll try to implement counting, so user can select and deselect cells and the "status bar" shows how many of them are selected. Possibly, if I get along with expressions, I'll add sum, average, min and max, like it is implemented in all other software.

**Comment by hyarion** [comment]
@xtemp09 I assume that you are done with this PR and think it's ready for merge then, cool 👍

**Review by hyarion — APPROVED** [review]
Looks good, zoom shortcuts should map correctly on macOS too.

I'm a bit surprised that there are no linting issues, as I think I've spotted some cases that should generate warnings.

Any case I think this is a good feature and implementation 👍

**Comment by luzpaz** [comment]
bumping for visibility

**Comment by chennes** [comment]
For the record, "bumping" has the exact opposite effect. During review meetings we sort by least-recently-updated, so touching a PR right before the meeting prevents us from seeing it (until we get caught up, anyway).

**Comment by luzpaz** [comment]
Oy, my bad. Thanks for the heads up

**Comment by xtemp09** [comment]
> For the record, "bumping" has the exact opposite effect. During review meetings we sort by least-recently-updated, so touching a PR right before the meeting prevents us from seeing it (until we get caught up, anyway).


If you sort the list of PRs, you will see that some of them were created long time ago, up to December 2019. What is the reason to keep pull requests open for many years? If they are no longer relevant, they have to be closed or amended.

**Comment by chennes** [comment]
@xtemp09 can you try running pre-commit locally and see if you can clean up that clang format issue that the CI is showing?

**Comment by hyarion** [comment]
it has a warning about `'ui_Sheet.h' file not found [clang-diagnostic-error]`

**Comment by xtemp09** [comment]
> @xtemp09 can you try running pre-commit locally and see if you can clean up that clang format issue that the CI is showing?


I don't know how to do that. I suppose, maintainer can always restart CI.
