### PR TITLE
Part: Do not allow loft where base and first segment are too close

### LINKED ISSUE #5855: [Problem] FreeCAD crashes on Loft creation when master-sketch added as a section
Issue imported from https://tracker.freecad.org/view.php?id=3751

* **Reporter:** sleeply4cat
* **Date submitted:** 12/28/2018
* **FreeCAD version:** 0.18
* **Category:** Bug
* **Status:** new
* **Tags:** Loft

# Original report text

May be related to #5642
Reproduces if the master-sketch added as a not last section of Loft.

# Additional information

```
$ freecad-daily FreeCAD 0.18, Libs: 0.18R15495 (Git) (freecad-daily:5562): 
IBUS-WARNING **: 13:29:16.710: Unable to connect to ibus: Could not connect: Connection refused 'ascii' codec can't decode byte 0xd0 in position 33: ordinal not in range(128) ** 
WARNING **: 13:29:21.446: invalid source position for vertical gradient ** 
WARNING **: 13:29:21.446: invalid source position for vertical gradient 
Program received signal SIGSEGV, Segmentation fault. 
#0 /lib/x86_64-linux-gnu/libc.so.6(+0x3ef20) [0x7f2e23e5af20] 
#1 /usr/lib/x86_64-linux-gnu/libTKTopAlgo.so.7(+0x17bcb5) [0x7f2de1d9bcb5]
#2 0x7f2de1d9c77e in BRepLib::EncodeRegularity(TopoDS_Shape const&, double) from /usr/lib/x86_64-linux-gnu/libTKTopAlgo.so.7+0x14e 
#3 0x7f2de0a7ada8 in BRepOffsetAPI_ThruSections::Build() from /usr/lib/x86_64-linux-gnu/libTKOffset.so.7+0xd28 
#4 0x7f2d91d9514b in PartDesign::Loft::execute() from /usr/lib/freecad-daily/lib/_PartDesign.so+0x7db 
#5 0x7f2e2641e035 in App::DocumentObject::recompute() from /usr/lib/freecad-daily/lib/libFreeCADApp.so+0x155 
#6 0x7f2de55af55b in Part::Feature::recompute() from /usr/lib/freecad-daily/lib/Part.so+0xb 
#7 0x7f2e263d2324 in App::Document::_recomputeFeature(App::DocumentObject*) from /usr/lib/freecad-daily/lib/libFreeCADApp.so+0xb4 
#8 0x7f2e263d9df3 in App::Document::recomputeFeature(App::DocumentObject*) from /usr/lib/freecad-daily/lib/libFreeCADApp.so+0x83 
#9 0x7f2d915fe490 in PartDesignGui::TaskLoftParameters::onSelectionChanged(Gui::SelectionChanges const&) from /usr/lib/freecad-daily/lib/PartDesignGui.so+0xf0 
#10 0x7f2e26edc896 in Gui::SelectionObserver::_onSelectionChanged(Gui::SelectionChanges const&) from /usr/lib/freecad-daily/lib/libFreeCADGui.so+0x56 
#11 0x7f2e26eeac3f in boost::signals2::detail::signal_impl<void (Gui::SelectionChanges const&), boost::signals2::optional_last_value<void>, int, std::less<int>, boost::function<void (Gui::SelectionChanges const&)>, boost::function<void (boost::signals2::connection const&, Gui::SelectionChanges const&)>, boost::signals2::mutex>::operator()(Gui::SelectionChanges const&) from /usr/lib/freecad-daily/lib/libFreeCADGui.so+0x20f
#12 0x7f2e26ee4f21 in Gui::SelectionSingleton::addSelection(char const*, char const*, char const*, float, float, float) from /usr/lib/freecad-daily/lib/libFreeCADGui.so+0x281
#13 0x7f2e26d49aca in Gui::SoFCUnifiedSelection::handleEvent(SoHandleEventAction*) from /usr/lib/freecad-daily/lib/libFreeCADGui.so+0xcba #14 0x7f2e237b6ea0 in SoNode::handleEventS(SoAction*, SoNode*) from /usr/lib/x86_64-linux-gnu/libCoin.so.80+0x80 #15 0x7f2e2355ba54 in SoAction::traverse(SoNode*) from /usr/lib/x86_64-linux-gnu/libCoin.so.80+0x64
#16 0x7f2e236c1425 in SoChildList::traverse(SoAction*, int, int) from /usr/lib/x86_64-linux-gnu/libCoin.so.80+0x165
#17 0x7f2e237ab436 in SoGroup::doAction(SoAction*) from /usr/lib/x86_64-linux-gnu/libCoin.so.80+0x56
#18 0x7f2e237ca7c7 in SoSeparator::doAction(SoAction*) from /usr/lib/x86_64-linux-gnu/libCoin.so.80+0x27
#19 0x7f2e237b6ea0 in SoNode::handleEventS(SoAction*, SoNode*) from /usr/lib/x86_64-linux-gnu/libCoin.so.80+0x80 #20 0x7f2e2355ba54 in SoAction::traverse(SoNode*) from /usr/lib/x86_64-linux-gnu/libCoin.so.80+0x64
#21 0x7f2e23566a4a in SoHandleEventAction::beginTraversal(SoNode*) from /usr/lib/x86_64-linux-gnu/libCoin.so.80+0x7a #22 0x7f2e2355d262 in SoAction::apply(SoNode*) from /usr/lib/x86_64-linux-gnu/libCoin.so.80+0x442
#23 0x7f2e236e0c19 in SoEventManager::actuallyProcessEvent(SoEvent const*) from /usr/lib/x86_64-linux-gnu/libCoin.so.80+0x69
#24 0x7f2e26dc2dce in SIM::Coin3D::Quarter::QuarterWidget::processSoEvent(SoEvent const*) from /usr/lib/freecad-daily/lib/libFreeCADGui.so+0x1e 
#25 0x7f2e26dcae26 in SIM::Coin3D::Quarter::SoQTQuarterAdaptor::processSoEvent(SoEvent const*) from /usr/lib/freecad-daily/lib/libFreeCADGui.so+0x56 
#26 0x7f2e26df41a9 in Gui::View3DInventorViewer::processSoEventBase(SoEvent const*) from /usr/lib/freecad-daily/lib/libFreeCADGui.so+0x9 
#27 0x7f2e26dd93c9 in Gui::BlenderNavigationStyle::processSoEvent(SoEvent const*) from /usr/lib/freecad-daily/lib/libFreeCADGui.so+0x219
#28 0x7f2e26dd4848 in Gui::NavigationStyle::processEvent(SoEvent const*) from /usr/lib/freecad-daily/lib/libFreeCADGui.so+0xf8
#29 0x7f2e26df4123 in Gui::View3DInventorViewer::processSoEvent(SoEvent const*) from /usr/lib/freecad-daily/lib/libFreeCADGui.so+0x63
#30 0x7f2e26dbd21c in SIM::Coin3D::Quarter::EventFilter::eventFilter(QObject*, QEvent*) from /usr/lib/freecad-daily/lib/libFreeCADGui.so+0x1ac
#31 0x7f2e24938a16 in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) from /usr/lib/x86_64-linux-gnu/libQtCore.so.4+0x86
#32 0x7f2e24e6501c in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /usr/lib/x86_64-linux-gnu/libQtGui.so.4+0x6c
#33 0x7f2e24e6c136 in QApplication::notify(QObject*, QEvent*) from /usr/lib/x86_64-linux-gnu/libQtGui.so.4+0x476
#34 0x7f2e26b967c8 in Gui::GUIApplication::notify(QObject*, QEvent*) from /usr/lib/freecad-daily/lib/libFreeCADGui.so+0x88
#35 0x7f2e249388ad in QCoreApplication::notifyInternal(QObject*, QEvent*) from /usr/lib/x86_64-linux-gnu/libQtCore.so.4+0x8d
#36 0x7f2e24e6b73d in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) from /usr/lib/x86_64-linux-gnu/libQtGui.so.4+0x14d
#37 /usr/lib/x86_64-linux-gnu/libQtGui.so.4(+0x249452) [0x7f2e24ee9452]
#38 0x7f2e24ee8ce3 in QApplication::x11ProcessEvent(_XEvent*) from /usr/lib/x86_64-linux-gnu/libQtGui.so.4+0x16b3
#39 /usr/lib/x86_64-linux-gnu/libQtGui.so.4(+0x272592) [0x7f2e24f12592]
#40 /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x2e7) [0x7f2e1d63f387]
#41 /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x4c5c0) [0x7f2e1d63f5c0]
#42 /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_iteration+0x2c) [0x7f2e1d63f64c]
#43 0x7f2e2496920e in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /usr/lib/x86_64-linux-gnu/libQtCore.so.4+0x7e
#44 /usr/lib/x86_64-linux-gnu/libQtGui.so.4(+0x272666) [0x7f2e24f12666]
#45 0x7f2e2493712f in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /usr/lib/x86_64-linux-gnu/libQtCore.so.4+0x3f
#46 0x7f2e24937495 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) from /usr/lib/x86_64-linux-gnu/libQtCore.so.4+0x1b5
#47 0x7f2e2493d459 in QCoreApplication::exec() from /usr/lib/x86_64-linux-gnu/libQtCore.so.4+0x99
#48 0x7f2e26b22c7a in Gui::Application::runApplication() from /usr/lib/freecad-daily/lib/libFreeCADGui.so+0x16ba
#49 freecad-daily(main+0x6db) [0x55f64076043b]
#50 /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7f2e23e3db97] #51 freecad-daily(_start+0x2a) [0x55f6407615ea]][/quote]
```

# Steps to reproduce

1. Create two sketches on different planes
2. Activate a Loft tool
3. Select sketch A as base
4. Add sketch A as a section
5. Add sketch B as a section
6. FreeCAD crashes after clicking on the sketch B

https://youtu.be/fKxVAzo2-0A

# Other bug information

* **Priority:** normal
* **Severity:** minor
* **Category:** Bug
* **OS: Ubuntu 18.04.1**
* **Platform:** Linux
* **Updated:** 2/6/2021

# Discussion from Mantis ticket

### Comment by sleeply4cat 2018-12-28 11:12
omg, sorry. Attached a log by the right way.

Also, build info:
OS: Ubuntu 18.04.1 LTS
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.18.15495 (Git)
Build type: Release
Branch: master
Hash: 9c7128ea77fc1046e11ebf2fbeb41216446eac4f
Python version: 2.7.15rc1
Qt version: 4.8.7
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: English/UnitedStates (en_US)

### PR DESCRIPTION
**Pull request by AIRCAP**
Do not allow loft where the segment shapes are too close ( fix #5855 )

A loft or pocket only makes sense if the segments used for it have some minimum separation. Having the shapes identical causes segfaults in OCCT

Checking for CoG is a hack. Identical shapes have identical CoG - but an identical CoG does not necessarily mean identical shapes - however it can be argued that a shape that is not offset at least somewhat in the direction of the loft doesnt make a valid shape for a loft (it will typically freeze OCCT instead of crashing it) and a sufficiently suitable shape will have a different CoG

throwing the exception will make it easy to identify if there ever is a case where this is a bad thing - and exceptions are better than segfaults.

### CODE REVIEW

**Comment by AIRCAP** [comment]
probably shouldn#t be merged atm, i think there#s a better way
also build pipelines are cutrrently not working

**Comment by AIRCAP** [comment]
ok NOW it fixes it

File: src/Mod/Part/App/TopoShapeExpansion.cpp [hunk 1]
```diff
@@ -4157,14 +4157,23 @@ TopoShape& TopoShape::makeElementLoft(const std::vector<TopoShape>& shapes,
                   "Need at least two vertices, edges or wires to create loft face");
     }
 
+    int i=0;
+    Base::Vector3d center1,center2;
     for (auto& sh : profiles) {
+        if (i>0) {
+            if (sh.getCenterOfGravity(center1) and profiles[i-1].getCenterOfGravity(center2) and center1.IsEqual(center2,Precision::Confusion())) {
```
Comment (hyarion) [inline src/Mod/Part/App/TopoShapeExpansion.cpp:4164]: While it's technically not wrong to use `and` in c++, I did not find any other instances of it in FreeCAD, so maybe we should go with the more common `&&` operator?
```suggestion
            if (sh.getCenterOfGravity(center1) && profiles[i-1].getCenterOfGravity(center2) && center1.IsEqual(center2,Precision::Confusion())) {
```

**Comment by chennes** [comment]
The CI failure has been fixed in main and on the 1.0 release branch -- could you please rebase on current main to get that fix and re-trigger the CI?

**Comment by AIRCAP** [comment]
messed up the rebase - should work now - my main branch was on the wrong commit

File: src/Mod/Part/App/TopoShapeExpansion.cpp (hunk 1 above)
Comment (AIRCAP) [reply src/Mod/Part/App/TopoShapeExpansion.cpp]: i changed it to &&

**Comment by yorikvanhavre** [comment]
backported
