### PR TITLE
Gui: Detect spnav daemon disconnect to prevent 100% CPU

### LINKED ISSUE #17809: 100% CPU use after spacenavd is stopped
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Steps to reproduce:

1. Have spacenavd installed and running on system.
2. Start FreeCAD and open any document in 3D view.
3. If you have a spacemouse, it will work. However the bug will occur even if you have no physical devices.
4. Kill spacenavd
5. FreeCAD continues to work but uses 100% CPU.

The 100% CPU load will continue even if you restart spacenavd, and space mouse will not work until FreeCAD is restarted.

### Full version info

```shell
FreeCAD_weekly-builds-39175-conda-Linux-x86_64-py311.AppImage (also occurs with 1.0RC2)

OS: Ubuntu 22.04.5 LTS (ICEWM/icewm-session/xcb)
Architecture: x86_64
Version: 1.1.0dev.39175 (Git) Conda AppImage
Build type: Release
Branch: main
Hash: 46831f4c86a1679d48f63273b92cd755522e42f9
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
Installed mods: 
  * dxf_library
  * ThreadProfile 1.84.0
  * Assembly4 0.50.2
```

### Subproject(s) affected?

None

### Anything else?

Backtrace from gdb:

<pre>
#0  __GI___select (nfds=19, readfds=readfds@entry=0x7fffffffc380, writefds=writefds@entry=0x0, exceptfds=exceptfds@entry=0x0, timeout=timeout@entry=0x7fffffffc370)
    at ../sysdeps/unix/sysv/linux/select.c:61
#1  0x00007ffff7e521c9 in event_pending (s=<optimized out>) at src/spnav.c:360
#2  0x00007ffff7e533d7 in spnav_poll_event (event=0x7fffffffc530) at src/spnav.c:502
#3  0x00007ffff5a8b5e9 in Gui::GuiNativeEvent::pollSpacenav() () from /tmp/.mount_FreeCADJOdpa/usr/bin/../lib/libFreeCADGui.so
#4  0x00007ffff2eeb964 in ?? () from /tmp/.mount_FreeCADJOdpa/usr/bin/../lib/libQt5Core.so.5
#5  0x00007ffff2eee9f4 in QSocketNotifier::activated(int, QSocketNotifier::QPrivateSignal) () from /tmp/.mount_FreeCADJOdpa/usr/bin/../lib/libQt5Core.so.5
#6  0x00007ffff2eef09e in QSocketNotifier::event(QEvent*) () from /tmp/.mount_FreeCADJOdpa/usr/bin/../lib/libQt5Core.so.5
#7  0x00007ffff3d703ae in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /tmp/.mount_FreeCADJOdpa/usr/bin/../lib/libQt5Widgets.so.5
#8  0x00007ffff5b69799 in Gui::GUIApplication::notify(QObject*, QEvent*) () from /tmp/.mount_FreeCADJOdpa/usr/bin/../lib/libFreeCADGui.so
#9  0x00007ffff2eb6b28 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /tmp/.mount_FreeCADJOdpa/usr/bin/../lib/libQt5Core.so.5
#10 0x00007ffff2f0b51d in ?? () from /tmp/.mount_FreeCADJOdpa/usr/bin/../lib/libQt5Core.so.5
#11 0x00007ffff1510ad7 in g_main_dispatch () from /tmp/.mount_FreeCADJOdpa/usr/bin/../lib/./libglib-2.0.so.0
#12 0x00007ffff1513ac7 in g_main_context_iterate_unlocked.constprop () from /tmp/.mount_FreeCADJOdpa/usr/bin/../lib/./libglib-2.0.so.0
#13 0x00007ffff15140ce in g_main_context_iteration () from /tmp/.mount_FreeCADJOdpa/usr/bin/../lib/./libglib-2.0.so.0
#14 0x00007ffff2f0aa36 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /tmp/.mount_FreeCADJOdpa/usr/bin/../lib/libQt5Core.so.5
#15 0x00007ffff2eb570b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /tmp/.mount_FreeCADJOdpa/usr/bin/../lib/libQt5Core.so.5
#16 0x00007ffff2ebd212 in QCoreApplication::exec() () from /tmp/.mount_FreeCADJOdpa/usr/bin/../lib/libQt5Core.so.5
#17 0x00007ffff5ac8784 in Gui::Application::runApplication() () from /tmp/.mount_FreeCADJOdpa/usr/bin/../lib/libFreeCADGui.so
#18 0x000055555555b8b7 in main ()
</pre>

I think `QSocketNotifier` created [here](https://github.com/FreeCAD/FreeCAD/blob/45d3864942c6928cec7dc18f95b1f222485756e5/src/Gui/3Dconnexion/GuiNativeEventLinux.cpp#L55) is trying to report that the socket is closed, but the handler only tries to read from the socket. The handler should somehow detect the closure and either retry after an interval or just disable the spacemouse.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Maik-0000FF**
When spacenavd stops or crashes while FreeCAD is running, one CPU core goes to 100% and stays there. The only recovery is killing FreeCAD. This happens on any spacenavd exit — USB disconnect, `systemctl stop spacenavd`, daemon crash.

The problem sits in `pollSpacenav()`. When the spnav socket enters EOF state, the kernel keeps reporting it as "readable" (that's how EOF works on Unix sockets). QSocketNotifier fires, `spnav_poll_event()` returns 0 — but 0 means "no events" and also "dead connection", libspnav doesn't tell them apart. So the cycle repeats in a tight loop.

The fix adds a check after an empty poll cycle: `recv(fd, &buf, 1, MSG_PEEK | MSG_DONTWAIT)`. MSG_PEEK doesn't consume data so it won't interfere with libspnav, and it returns 0 on EOF — which is the one thing `spnav_poll_event()` can't tell us. When EOF is detected, the QSocketNotifier gets disabled and the spnav connection is closed.

To make this possible, the QSocketNotifier is stored as a class member instead of a local variable in `initSpaceball()`. The destructor guards `spnav_close()` so it doesn't try to close an already-closed connection.

I verified this independently with a socketpair() reproducer (no hardware needed) — a dead socket produces ~40 million select() wakeups in 10 seconds, and `recv(MSG_PEEK)` detects the EOF immediately with no false positives on healthy sockets.

Tested on Arch Linux / KDE Plasma Wayland with SpaceNavigator (046d:c626) via spacenavd 1.3.1. Without the fix, `sudo systemctl stop spacenavd` pegs a core at 100% instantly. With the fix, CPU stays normal and FreeCAD logs "Lost connection to spacenav daemon. Restart FreeCAD to reconnect." No reconnect — restarting spacenavd still requires a FreeCAD restart, same as before, just without the CPU spike.

Fixes #17809

### CODE REVIEW

File: src/Gui/3Dconnexion/GuiNativeEventLinux.cpp [hunk 1]
```diff
@@ -35,6 +35,9 @@
 
 #include <QSocketNotifier>
 
+#include <cerrno>
+#include <sys/socket.h>
```
Comment (Lgt2x) [inline src/Gui/3Dconnexion/GuiNativeEventLinux.cpp:39]: Windows will not like that, is this code compiled on Linux only?

Comment (Maik-0000FF) [reply src/Gui/3Dconnexion/GuiNativeEventLinux.cpp:39]: Yes, this file is Linux-only — `GuiNativeEventLinux.cpp` is only compiled on Linux (see CMakeLists.txt). Windows and macOS have their own platform-specific files (`GuiNativeEventWin32.cpp`, `GuiNativeEventMac.cpp`).

Comment (Maik-0000FF) [reply src/Gui/3Dconnexion/GuiNativeEventLinux.cpp:39]: More specifically, `src/Gui/CMakeLists.txt` line 234 — inside the `IF(SPNAV_FOUND AND FREECAD_USE_3DCONNEXION_LEGACY)` block.

**Review by chennes — APPROVED** [review]
Tested - fixes the issue. Code looks good.

File: src/Gui/3Dconnexion/GuiNativeEventLinux.cpp (hunk 1 above)
Comment (Lgt2x) [reply src/Gui/3Dconnexion/GuiNativeEventLinux.cpp:39]: Thanks for confirming

Comment (Lgt2x) [reply src/Gui/3Dconnexion/GuiNativeEventLinux.cpp:39]: (although I'd appreciate talking with a human rather than a robot ;))

Comment (Maik-0000FF) [reply src/Gui/3Dconnexion/GuiNativeEventLinux.cpp:39]: I'm German

Comment (Lgt2x) [reply src/Gui/3Dconnexion/GuiNativeEventLinux.cpp:39]: hello German :)
