### PR TITLE
Gui: scale FPS counter with device pixel ratio on HiDPI displays

### LINKED ISSUE #28642: Core/UI: FPS displayed with unreadable small font
### Problem description

Image

See the screenshot, this is what I get after turning on "Show counter of frame per second" in the preferences. It uses an unreadable tiny font. 

Environment:

- Linux (Ubuntu)
- 4k Display, running with Wayland
- FreeCAD: 1.1.0, running from AppImage

### Workbench affected?

None

### Steps to reproduce

Just turn on the "Show counter of frame per second" and see if you can read it.

### Expected behavior

readable font size.

### Actual behavior

Too small font.

### Development version About Info (in Safe Mode)

```shell
OS: Ubuntu Resolute Raccoon (development branch) (ubuntu:GNOME/ubuntu/wayland)
Architecture: x86_64
Version: 1.1.0.20260325 (Git shallow) AppImage
Build date: 2026/03/25 02:17:53
Build type: Release
Branch: (HEAD detached at 34a971666)
Hash: 34a9716668b1ddeb55b914f1c5be644826bdbbbf
Python 3.11.14, Qt 6.8.3, Coin 4.0.3, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.3.0, IfcOpenShell 0.8.4, OCC 7.8.1
Locale: English/United States (en_US)
Navigation Style/Orbit Style/Rotation Mode: CAD/Rounded Arcball/Window center
Stylesheet/Theme/QtStyle: FreeCAD.qss/FreeCAD Dark/
Logical DPI/Physical DPI/Pixel Ratio: 96/106.227/2
Installed mods: 
  * freecad.gears 1.3.0
```

### Last known good version (optional)

```shell

```

### PR DESCRIPTION
**Pull request by Bojan9597**
Fixes #28642. The FPS bitmap font is rendered at a fixed physical pixel size, making it unreadably small on HiDPI displays. Pass `devicePixelRatio()` to the renderer and scale via `glPixelZoom` and character advance accordingly.

### CODE REVIEW

**Review by maxwxyz — CHANGES_REQUESTED** [review]
Please see above

File: src/Gui/Quarter/SoQTQuarterAdaptor.cpp [hunk 1]
```diff
@@ -649,7 +649,7 @@ void SIM::Coin3D::Quarter::SoQTQuarterAdaptor::draw2DString(
     const char* str,
     SbVec2s glsize,
     SbVec2f position,
-    Base::Color color = Base::Color(1.0F, 1.0F, 0.0F))  // retains yellow as default color
+    Base::Color color = Base::Color(1.0F, 1.0F, 0.0F))  // default color: yellow
```
Comment (chennes) [inline src/Gui/Quarter/SoQTQuarterAdaptor.cpp]: No reason to touch this now.

File: src/Gui/View3DInventorViewer.h [hunk 2]
```diff
@@ -603,6 +604,8 @@ class GuiExport View3DInventorViewer: public Quarter::SoQTQuarterAdaptor, public
 
     // stuff needed to draw the fps counter
     bool fpsEnabled;
+    QLabel* fpsCounter = nullptr;
+    unsigned long fpsCounterColor = 0;
```
Comment (chennes) [inline src/Gui/View3DInventorViewer.h]: Why only cache this one? There are two other parameter lookups happening every single frame, right?

Comment (Bojan9597) [reply src/Gui/View3DInventorViewer.h]: tthe fpsCounterColor cache isn't there to avoid the parameter lookup itself (  which is a cheap in-memory read) — it's to avoid calling setStyleSheet() every frame, which triggers Qt style recomputation. The other two lookups have no such expensive side effect, so caching them would add complexity without benefit.

File: src/Gui/Quarter/SoQTQuarterAdaptor.cpp (hunk 1 above)
Comment (Bojan9597) [reply src/Gui/Quarter/SoQTQuarterAdaptor.cpp]: You are right, I changed it because it seemed more straight forward. I have reverted it.

File: src/Gui/View3DInventorViewer.h (hunk 2 above)
Comment (chennes) [reply src/Gui/View3DInventorViewer.h]: Ah I see, I'd rename the variable then: it's not really that you're keeping track of the "counter color" at all, you're detecting a _change_ in the _axis label color_. So maybe `previousAxisLetterColor` or something along those lines.

Comment (Bojan9597) [reply src/Gui/View3DInventorViewer.h]: I have renamed it.
