### PR TITLE
Gui: fix ElideCheckbox

### LINKED ISSUE #21158: PartDesign: Hole function displays some checkboxes with incorrect margins
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Problem description

The checkboxes "Include in depth" and "Switch Direction" do not have space between the text as the other checkboxes do.
Compare these 2 with the "Threaded" below.

See:

Image

### Full version info

```shell
OS: Ubuntu 25.04 (ubuntu:GNOME/ubuntu-xorg/xcb)
Architecture: x86_64
Version: 1.1.0dev.41464 (Git)
Build date: 2025/04/28 16:20:16
Build type: Release
Branch: main
Hash: 8d6547d519ffb331cfba054b4db2750b3e71339b
Python 3.11.12, Qt 6.7.3, Coin 4.0.3, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 
shiboken , xerces-c 3.2.5, IfcOpenShell 0.8.2, OCC 7.8.1
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: OpenDark.qss/OpenDark/
Logical DPI/Physical DPI/Pixel Ratio: 96/145.143/1
Installed mods: 
  * Assembly4 0.50.19-dev
  * sheetmetal 0.7.22
  * DynamicData 2.74.0
  * Curves 0.6.61
  * InventorLoader 1.5.1
  * diff-tools 0.1.0
  * ose-piping
  * OpenTheme 2024.9.1
  * fasteners 0.5.38
  * Curves.backup1746105636.3777354 0.6.60 (Disabled)
  * osh-autodoc-workbench 0.2.3
  * OpticsWorkbench 1.2.0
  * lattice2 1.0.0
  * kicadStepUpMod 11.6.9
```

### Subproject(s) affected?

Core

### Anything else?

_No response_

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by alfrix**
This fixes #21158 and also some special states that weren't draw like hover and focus

### CODE REVIEW

File: src/Gui/ElideCheckBox.cpp [hunk 1]
```diff
@@ -29,44 +29,47 @@
 
 namespace Gui {
 
-const int CheckboxSpacing = 18;
-
 ElideCheckBox::ElideCheckBox(QWidget *parent)
-    : QCheckBox(parent) {
+    : QCheckBox(parent)
+    , m_IndicatorWidth(style()->pixelMetric(QStyle::PM_IndicatorWidth, nullptr, this))
+    , m_CheckBoxLabelSpacing(style()->pixelMetric(QStyle::PM_CheckBoxLabelSpacing, nullptr, this))
```
Comment (kadet1090) [inline src/Gui/ElideCheckBox.cpp:35]: Why is this calculated in the constructor and not in paint method? I think that methods from style are mostly intended to be used from the paint events, size hints, etc.

Comment (alfrix) [reply src/Gui/ElideCheckBox.cpp:35]: to be saved and reused, it's used on both sizeHints, on an early version i used it for the paint event too, i can make the individual calls in both sizeHint functions if you prefer that

Comment (kadet1090) [reply src/Gui/ElideCheckBox.cpp:35]: It potentially could become problematic if we use such checkbox and change stylesheet or FreeCAD theme. Then until this widget is recreated it will not be properly recalculated. 

You also do not pass option to it so it may not properly react to QSS changes especially pseudo classes (states) like :hover. I think that it would be better to repeat that call - it should be pretty cheap as functions like this are intended to be called from paint method.
