### PR TITLE
Gui: Workaround for crash on close of MDI window

### LINKED ISSUE #16616: Unexpected pop of Start page and crash when Start page is closed
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

The Freecad exhibits unexpected behaviour by switching from current document to Start page and crashes when the Start page is closed.

Reproduction: (See comments for more precise instructions!)
* start Freecad
* create new document and select it in tree view
* go to Property View dialog
* Edit any value and finish the editing by enter
* pres tab 2x -> the Start page tab becomes visible (WIERD)
* close the Start page -> crash

By the second <tab>, button on Status bar is activated (gets focus), but the focus is lost once the Start page pops-up.

Note: when the original document is selected (becomes visible) and then the tab with Start page is closed, there is no crash.

### Full version info

```shell
OS: Arch Linux (KDE)
Word size of FreeCAD: 64-bit
Version: 1.1.0dev.38779 (Git)
Build type: Release
Branch: makepkg
Hash: 4f83896290d8ffbab9b563872dfb281fbfcbc5af
Python 3.12.6, Qt 6.7.2, Coin 4.0.3, Vtk 9.3.1, OCC 7.8.1
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Dark/
```

### Subproject(s) affected?

None

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by pinkavaj**
Close #16616 

The Qt6 (up to Qt 6.7.3 now) contains bug, which can lead, under specific circumstances, to crash of the application, when the MDI window is closed. The circumstances are:

* at least 2 MDI windows needs to be open
* stylesheet must set different size (border, margin) for activated and un-activated tabBar tab
* the closed window must be inactive, but created before the window now active and open
* race condition must occur betwee the closing and resize event handlers for the tabBar (see qt bug for details)

So this bug only occures with Qt6 with the Dark or Light styles selected (no classic) and only if specific sequence of steps is followed during opening and closing the MDI windows.

The bug is in Qt code path executed when QMdiArea::ActivationHistoryOrder is set.

The other possible workaround might be to change all the affected stylesheets, but this seems to me impractical and also fragile, because the affected code path will be still active.

https://bugreports.qt.io/browse/QTBUG-129596

### CODE REVIEW

**Comment by pinkavaj** [comment]
Seems like the CI fialed, but IMHO the error is not related to the changes, or it is?

```
connect failed: No such file or directory
WRNERRCMSWRNERRCMSWRNERRCMSWRNERRCMSWRNERRCMSWRNERRCMSWRNERRCMSWRNERRCMSWRNERRCMSWRNERRCMSWRNERRCMSWRNERRCMSWRNERRCMS   Printing error
```

**Comment by pinkavaj** [comment]
@chennes Thx for pointing to correct error message.

I would appreciate a advise now. The test fails because after changing the activation order the deletion of doc No2 does not cause activation of doc No1. I'm really not sure if it is expected or not. Can anybody have an idea to share before I start deep-dive into the rabbit hole?

**Comment by pinkavaj** [comment]
Meh, when I disable the "Start page", the test pass locally. It looks like the next active window is "Start" page. The document for this window is of course NULL ...

File: src/Gui/Application.h [hunk 1]
```diff
@@ -30,6 +30,10 @@
 
 #include <App/Application.h>
 
+#if QT_VERSION >= QT_VERSION_CHECK(6,0,0) && QT_VERSION < QT_VERSION_CHECK(6,7,4)
```
Comment (adrianinsaval) [inline src/Gui/Application.h:33]: dow e have confirmation that this is fixed in qt 6.7.4?

Comment (pinkavaj) [reply src/Gui/Application.h:33]: Honestly not yet. It is P1 in Qt, but it is just educated wish. I'm tracking this, so probably NP to set no limit now.

Comment (adrianinsaval) [reply src/Gui/Application.h:33]: In that case it's better to only check qt > 6 and we'll add the upper limit when we have a confirmed fix in qt

Comment (pinkavaj) [reply src/Gui/Application.h]: Done
