### PR TITLE
Spreadsheet: Decrease default size

### LINKED ISSUE #15673: Lag on Spreadsheets CTRL+A Select All Command
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I noticed a lag in the CTRL+A keybind for select all in Spreadsheets. I was playing around with the EasyAlias macro and was testing the binding to see if I could make it a hotkey to improve the macro's use and workflow, and noticed the lag, as it frozen up the cell selections. Initially tested on a small 3x2 cell selection, and since have confirmed it seems to happen anytime a cell is selected. I expect that this might be some of Python's inherent slowness showing while having to touch the entire 16384x702 sheet. I cannot immediately confirm its not just an issue on my machine, perhaps the way the spreadsheet is being handled in memory could be optimized to reduce the lag when executing the command.

### Full version info

```shell
[code]
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 0.20.2.29603 (Git)
Build type: Release
Branch: releases/FreeCAD-0-20
Hash: 930dd9a76203a3260b1e6256c70c1c3cad8c5cb8
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * Assembly4 0.50.2
[/code]
```

### Subproject(s) affected?

Spreadsheet

### Anything else?

Thanks for the efforts to make a great tool greater

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #27147: Spreadsheet: Rightmost column disappears when inserting a new column
### Problem description

The "Insert column left/right" (and "delete column") feature doesn't increase (decrease) the column count shown to the user. As a result, if there is a value in column ZZ and the user adds a column, the value disappears and an error (`<Exception> DynamicProperty.cpp(212): Invalid property name '[A1'`) is thrown. Then, if a column is deleted, the value is shown again.

### Workbench affected?

Spreadsheet

### Steps to reproduce

Steps to reproduce:
1. Create a new document
2. Create a new spreadsheet
3. Insert value "1" into cell "ZZ1"
4. Right click on column "ZZ" and select "Insert column left"
5. The error is thrown
6. Remove the column "ZZ"
7. The value appears again

### Expected behavior

There should be a new column AAA, and cell AAA1 should have value 1.

### Actual behavior

The column disappears and an error is thrown.

### Development version About Info (in Safe Mode)

```shell
OS: Arch Linux (KDE/plasma/wayland)
Architecture: x86_64
Version: 1.2.0dev.20260120 (Git shallow) AppImage
Build date: 2026/01/20 21:54:07
Build type: Release
Branch: (HEAD detached at 9beca43)
Hash: 9beca4363ad327e453ee5a27f737537e31467901
Python 3.11.14, Qt 6.8.3, Coin 4.0.3, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.3.0, IfcOpenShell 0.8.2, OCC 7.8.1
Locale: C/Default (C)
Navigation Style/Orbit Style/Rotation Mode: CAD/Rounded Arcball/Window center
Stylesheet/Theme/QtStyle: FreeCAD.qss/FreeCAD Light/
Logical DPI/Physical DPI/Pixel Ratio: 96/85.6507/1.25
```

### Last known good version (optional)

```shell

```

### PR DESCRIPTION
**Pull request by greg19**
Fixes #15673 by decreasing the default sheet size. Fixes #27147.

### CODE REVIEW

**Comment by greg19** [comment]
Also impacts #25997 by reducing the affected file size from 25GiB to 238MiB.

**Comment by Lgt2x** [comment]
A proper fix for https://github.com/FreeCAD/FreeCAD/issues/15673 would required changing the spreadsheet memory model, I'd suggest editing the PR message to not auto-close the issue. Backporting to 1.1 this close to the release could be dangerous, this is not a behavior I'd expect to change between Release Candidates as a user. People may have files or workflows that use more than 1k lines.

**Comment by greg19** [comment]
> Backporting to 1.1 this close to the release could be dangerous, this is not a behavior I'd expect to change between Release Candidates as a user. People may have files or workflows that use more than 1k lines.

I agree, also considering that #15673 cannot be reproduced on 1.1rc2 (due to #27151). 

> A proper fix for https://github.com/FreeCAD/FreeCAD/issues/15673 would required changing the spreadsheet memory model

Can you elaborate more why you think changing the spreadsheet model is required? I know that it could be more efficient, but the main issue I see is that the default bounds of the sheet were chosen in a way that in the current memory model it's infeasible to issue any action on all of them. I understand that you can have an infinite spreadsheet with efficient modifications, but I'm not convinced that it's *required* in FreeCAD. How will the impact be different for the user?

**Comment by Lgt2x** [comment]
> Can you elaborate more why you think changing the spreadsheet model is required? I know that it could be more efficient, but the main issue I see is that the default bounds of the sheet were chosen in a way that in the current memory model it's infeasible to issue any action on all of them. I understand that you can have an infinite spreadsheet with efficient modifications, but I'm not convinced that it's required in FreeCAD. How will the impact be different for the user?

Sorry, I could have explained my thoughts a little more :)

What I mean is that the memory issue in the spreadsheet is due to its design. Excel or LibreOffice won't allocate memory proportional to the number of cells when you hit select all of them or even change the font color used on a large selection. They are probably working on spans, and rendering cells on the fly only when they show up on screen. To properly fix the memory problem, a deep rework of the Spreadsheet workbench is required. For this reason, I'd like to keep the original issue open, so that we know that the underlying problem with spreadsheet is not solved. While this is not absolutely required for FreeCAD, it would allow for more freedom on how users can use sheets, without ever having to be aware of the limitations on the number of cells.

That said, I think your fix is acceptable and should improve the situation for many users. Default bounds could still be subject to discussion though.

**Comment by greg19** [comment]
> For this reason, I'd like to keep the original issue open, so that we know that the underlying problem with spreadsheet is not solved.

To me #25997 better explains the memory problem you are referring to.

> They are probably working on spans, and rendering cells on the fly only when they show up on screen.

Do you suggest to rework the in-memory representation or file format? While changing only the in-memory representation doesn't seem to create any issues, it also doesn't bring much benefits without changing the file format: the "freeze" will only be moved from when the user issues an action to the moment of saving the file. The problem with changing the file format is that we need to migrate old files, so we suddenly have to maintain two file formats and the code that translates one to the other. That's why I'm concerned if this feature is impactful enough to complicate the code base.

> Default bounds could still be subject to discussion though.

Sure, I just went with what Google Sheets / Proton Sheets do. Any opinions?

**Comment by Lgt2x** [comment]
> To me https://github.com/FreeCAD/FreeCAD/issues/25997 better explains the memory problem you are referring to.

Indeed, we can keep that one open instead. Or better, create a new "Code quality" issue explaining the exact problem and proposed solution.

> Do you suggest to rework the in-memory representation or file format?

Both. Won't be a small task, but I'm confident we can find a way.

**Comment by greg19** [comment]
> cannot be reproduced on 1.1rc2 (due to #27151).

Actually I managed to reproduce the error without the Ctrl+A shortcut. Turns out you are able to select all cells by clicking here (which is a wild behavior IMO):

image

File: src/Mod/Spreadsheet/Gui/SheetModel.h [hunk 1]
```diff
@@ -70,7 +70,7 @@ private Q_SLOTS:
 
     QVariantList columnLabels, rowLabels;
 
-    static constexpr int maxRowCount = 16384, maxColumnCount = 26 + 26 * 26;
+    static constexpr int maxRowCount = 1000, maxColumnCount = 4 * 26;
```
Comment (hyarion) [inline src/Mod/Spreadsheet/Gui/SheetModel.h]: What happens with this change if someone has already made use of more than 1000 lines in an old file?

**Review by hyarion — COMMENTED** [review]
Would it be possible to make this dynamic in size instead and just start with A-Z, 1-1000, but allow more to be added?

File: src/Mod/Spreadsheet/Gui/SheetModel.h (hunk 1 above)
Comment (hyarion) [reply src/Mod/Spreadsheet/Gui/SheetModel.h]: I've made a test file which puts a value in the cell `QQ1010` and another in `B2` that references the value from `QQ1010`:
[qq1010.FCStd.zip](https://github.com/user-attachments/files/25190954/qq1010.FCStd.zip)

`QQ1010` still exists and can be accessed in expressions, but it is not possible to scroll to and see that cell.

**Comment by greg19** [comment]
> Would it be possible to make this dynamic in size instead and just start with A-Z, 1-1000, but allow more to be added?

I'll try to do that and add a test for it.

**Comment by hyarion** [comment]
> I've made it dynamic, including that it expands the view to contain all used cells. Do you think the test is still valuable in this case?

I'd say it is optional to add that test case, but it would be good to have to ensure we don't accidentally cut off someone's data in the future.

**Comment by hyarion** [comment]
detachment is fixed, but I get a crash when I add columns and then remove them:

https://github.com/user-attachments/assets/0897480e-24a3-4500-8401-667dbbbd4ca6

<details><summary>show stack trace</summary>
<p>

```
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=2, address=0x120104000)
  * frame #0: 0x0000000104943404 libQt6Widgets.6.dylib`QtPrivate::QPodArrayOps<QHeaderViewPrivate::SectionItem>::insert(long long, long long, QHeaderViewPrivate::SectionItem const&) + 400
    frame #1: 0x0000000104910a6c libQt6Widgets.6.dylib`QHeaderView::sectionsInserted(QModelIndex const&, int, int) + 480
    frame #2: 0x0000000104210be4 libQt6Core.6.dylib`void doActivate<false>(QObject*, int, void**) + 1392
    frame #3: 0x00000001040d4d88 libQt6Core.6.dylib`QAbstractItemModel::endInsertColumns() + 216
    frame #4: 0x0000000350897530 SpreadsheetGui.so`SpreadsheetGui::SheetModel::containInView(this=0x000000011fe581d0, address=(_row = 4, _col = 30, _absRow = false, _absCol = false)) at SheetModel.cpp:682:9
    frame #5: 0x0000000350897698 SpreadsheetGui.so`SpreadsheetGui::SheetModel::cellUpdated(this=0x000000011fe581d0, address=(_row = 4, _col = 30, _absRow = false, _absCol = false)) at SheetModel.cpp:688:5
    frame #6: 0x00000003508aa188 SpreadsheetGui.so`decltype(*std::declval<SpreadsheetGui::SheetModel*&>().*std::declval<void (SpreadsheetGui::SheetModel::*&)(App::CellAddress)>()(std::declval<App::CellAddress const&>())) std::__1::__invoke[abi:ne180100]<void (SpreadsheetGui::SheetModel::*&)(App::CellAddress), SpreadsheetGui::SheetModel*&, App::CellAddress const&, void>(__f=0x000000016fdf36d0, __a0=0x000000016fdf36e0, __args=0x000000016fdf39b8) at invoke.h:312:25
    frame #7: 0x00000003508aa0a0 SpreadsheetGui.so`std::__1::__bind_return<void (SpreadsheetGui::SheetModel::*)(App::CellAddress), std::__1::tuple<SpreadsheetGui::SheetModel*, std::__1::placeholders::__ph<1>>, std::__1::tuple<App::CellAddress const&>, __is_valid_bind_return<void (SpreadsheetGui::SheetModel::*)(App::CellAddress), std::__1::tuple<SpreadsheetGui::SheetModel*, std::__1::placeholders::__ph<1>>, std::__1::tuple<App::CellAddress const&>>::value>::type std::__1::__apply_functor[abi:ne180100]<void (SpreadsheetGui::SheetModel::*)(App::CellAddress), std::__1::tuple<SpreadsheetGui::SheetModel*, std::__1::placeholders::__ph<1>>, 0ul, 1ul, std::__1::tuple<App::CellAddress const&>>(__f=0x000000016fdf36d0, __bound_args=size=2, (null)=__tuple_indices<0UL, 1UL> @ 0x000000016fdf361f, __args=size=1) at bind.h:195:10
    frame #8: 0x00000003508aa040 SpreadsheetGui.so`std::__1::__bind_return<void (SpreadsheetGui::SheetModel::*)(App::CellAddress), std::__1::tuple<SpreadsheetGui::SheetModel*, std::__1::placeholders::__ph<1>>, std::__1::tuple<App::CellAddress const&>, __is_valid_bind_return<void (SpreadsheetGui::SheetModel::*)(App::CellAddress), std::__1::tuple<SpreadsheetGui::SheetModel*, std::__1::placeholders::__ph<1>>, std::__1::tuple<App::CellAddress const&>>::value>::type std::__1::__bind<void (SpreadsheetGui::SheetModel::*)(App::CellAddress), SpreadsheetGui::SheetModel*, std::__1::placeholders::__ph<1> const&>::operator()[abi:ne180100]<App::CellAddress const&>(this=0x000000016fdf36d0, __args=0x000000016fdf39b8) at bind.h:222:12
    frame #9: 0x00000003508a9eb0 SpreadsheetGui.so`fastsignals::detail::function_proxy_impl<std::__1::__bind<void (SpreadsheetGui::SheetModel::*)(App::CellAddress), SpreadsheetGui::SheetModel*, std::__1::placeholders::__ph<1> const&>, void, App::CellAddress const&>::operator()(this=0x000000016fdf36c8, args=0x000000016fdf39b8) at function_detail.h:80:10
    frame #10: 0x000000035140b6bc Spreadsheet.so`void fastsignals::detail::signal_impl::invoke<fastsignals::optional_last_value<void>, void, void (App::CellAddress const&), App::CellAddress const&>(this=0x000000016bbaefa8, args=0x000000016fdf39b8) const at signal_impl.h:33:5
    frame #11: 0x000000035139e70c Spreadsheet.so`fastsignals::signal<void (App::CellAddress), fastsignals::optional_last_value>::operator()(this=0x000000033f5941f8, args=0x000000016fdf39b8) const at signal.h:112:44
    frame #12: 0x000000035142c938 Spreadsheet.so`Spreadsheet::Sheet::updateProperty(this=0x000000033f593e00, key=(_row = 4, _col = 30, _absRow = false, _absCol = false)) at Sheet.cpp:846:5
    frame #13: 0x000000035142d470 Spreadsheet.so`Spreadsheet::Sheet::recomputeCell(this=0x000000033f593e00, p=(_row = 4, _col = 30, _absRow = false, _absCol = false)) at Sheet.cpp:941:9
    frame #14: 0x000000035142f22c Spreadsheet.so`Spreadsheet::Sheet::execute(this=0x000000033f593e00) at Sheet.cpp:1119:13
    frame #15: 0x00000001023ea67c libFreeCADApp.dylib`App::DocumentObject::recompute(this=0x000000033f593e00) at DocumentObject.cpp:168:22
    frame #16: 0x000000010232d58c libFreeCADApp.dylib`App::Document::_recomputeFeature(this=0x000000015c20b800, Feat=0x000000033f593e00) at Document.cpp:3041:32
    frame #17: 0x000000010232bf6c libFreeCADApp.dylib`App::Document::recompute(this=0x000000015c20b800, objs=size=0, force=false, hasError=0x0000000000000000, options=0) at Document.cpp:2751:31
    frame #18: 0x00000001024aa190 libFreeCADApp.dylib`App::DocumentPy::recompute(this=0x000000012bace500, args=0x0000000100ee2148) at DocumentPyImp.cpp:725:31
    frame #19: 0x00000001024a1234 libFreeCADApp.dylib`App::DocumentPy::staticCallback_recompute(self=0x000000012bace508, args=0x0000000100ee2148) at DocumentPy.cpp:2241:57
    frame #20: 0x0000000100b16a70 libpython3.11.dylib`cfunction_call + 284
    frame #21: 0x0000000100abee34 libpython3.11.dylib`_PyObject_MakeTpCall + 332
    frame #22: 0x0000000100bbc29c libpython3.11.dylib`_PyEval_EvalFrameDefault + 20436
    frame #23: 0x0000000100bb6324 libpython3.11.dylib`PyEval_EvalCode + 204
    frame #24: 0x0000000100c1a318 libpython3.11.dylib`run_mod + 144
    frame #25: 0x0000000100c1e014 libpython3.11.dylib`PyRun_StringFlags + 112
    frame #26: 0x0000000101146e20 libFreeCADBase.dylib`Base::InterpreterSingleton::runString(this=0x000000015b0454d0, sCmd="App.ActiveDocument.recompute()") at Interpreter.cpp:248:15
    frame #27: 0x0000000105e4861c libFreeCADGui.dylib`Gui::Command::_runCommand(file="/Users/nauck/projects/freecad/FreeCAD-pr/src/Mod/Spreadsheet/Gui/SheetTableView.cpp", line=372, eType=Doc, sCmd="App.ActiveDocument.recompute()") at Command.cpp:784:29
    frame #28: 0x0000000105e4848c libFreeCADGui.dylib`Gui::Command::_doCommand(file="/Users/nauck/projects/freecad/FreeCAD-pr/src/Mod/Spreadsheet/Gui/SheetTableView.cpp", line=372, eType=Doc, sCmd="App.ActiveDocument.recompute()") at Command.cpp:729:5
    frame #29: 0x000000035087dc9c SpreadsheetGui.so`SpreadsheetGui::SheetTableView::removeColumns(this=0x000000015fe751d0) at SheetTableView.cpp:372:5
    frame #30: 0x0000000350884578 SpreadsheetGui.so`QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (SpreadsheetGui::SheetTableView::*)()>::call(this=0x000000016fdf6be0)(), SpreadsheetGui::SheetTableView*, void**)::'lambda'()::operator()() const at qobjectdefs_impl.h:152:24
    frame #31: 0x000000035088448c SpreadsheetGui.so`void QtPrivate::FunctorCallBase::call_internal<void, QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (SpreadsheetGui::SheetTableView::*)()>::call(void (SpreadsheetGui::SheetTableView::*)(), SpreadsheetGui::SheetTableView*, void**)::'lambda'()>(args=0x000000016fdf6e08, fn=0x000000016fdf6be0) at qobjectdefs_impl.h:65:17
    frame #32: 0x00000003508843e8 SpreadsheetGui.so`QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (SpreadsheetGui::SheetTableView::*)()>::call(f=(SpreadsheetGui.so`SpreadsheetGui::SheetTableView::removeColumns() at SheetTableView.cpp:362), o=0x000000015fe751d0, arg=0x000000016fdf6e08) at qobjectdefs_impl.h:151:13
    frame #33: 0x000000035088433c SpreadsheetGui.so`void QtPrivate::FunctionPointer<void (SpreadsheetGui::SheetTableView::*)()>::call<QtPrivate::List<>, void>(f=(SpreadsheetGui.so`SpreadsheetGui::SheetTableView::removeColumns() at SheetTableView.cpp:362), o=0x000000015fe751d0, arg=0x000000016fdf6e08) at qobjectdefs_impl.h:199:13
    frame #34: 0x000000035088423c SpreadsheetGui.so`QtPrivate::QCallableObject<void (SpreadsheetGui::SheetTableView::*)(), QtPrivate::List<>, void>::impl(which=1, this_=0x000000016bda81a0, r=0x000000015fe751d0, a=0x000000016fdf6e08, ret=0x0000000000000000) at qobjectdefs_impl.h:570:21
    frame #35: 0x0000000104210be4 libQt6Core.6.dylib`void doActivate<false>(QObject*, int, void**) + 1392
    frame #36: 0x000000010b3a0a24 libQt6Gui.6.dylib`QAction::activate(QAction::ActionEvent) + 280
    frame #37: 0x0000000104991998 libQt6Widgets.6.dylib`QMenuPrivate::activateCausedStack(QList<QPointer<QWidget>> const&, QAction*, QAction::ActionEvent, bool) + 116
    frame #38: 0x000000010498f3c8 libQt6Widgets.6.dylib`QMenuPrivate::activateAction(QAction*, QAction::ActionEvent, bool) + 604
    frame #39: 0x0000000104996314 libQt6Widgets.6.dylib`QMenu::mouseReleaseEvent(QMouseEvent*) + 548
    frame #40: 0x0000000104aa0d4c libQt6Widgets.6.dylib`QWidget::event(QEvent*) + 112
    frame #41: 0x00000001049969cc libQt6Widgets.6.dylib`QMenu::event(QEvent*) + 1208
    frame #42: 0x0000000104b4c9c0 libQt6Widgets.6.dylib`QApplicationPrivate::notify_helper(QObject*, QEvent*) + 332
    frame #43: 0x0000000104b4eacc libQt6Widgets.6.dylib`QApplication::notify(QObject*, QEvent*) + 4896
```

</p>
</details> 

It has crashed for me 3/3 times by doing the steps from the video.

**Comment by greg19** [comment]
Can you check now? I fixed a incorrect use of `beginInsertColumns` which I believe was a UB (your steps didn't crash for me, but behaved weirdly). Now it works correctly for me.

File: src/Mod/Spreadsheet/Gui/SheetModel.cpp [hunk 2]
```diff
@@ -34,8 +34,11 @@
 #include <Gui/Application.h>
 #include <Gui/Command.h>
 #include <Mod/Spreadsheet/App/Sheet.h>
+#include <qabstractitemmodel.h>
+#include <qnamespace.h>
```
Comment (hyarion) [inline src/Mod/Spreadsheet/Gui/SheetModel.cpp]: Shouldn't we include `<QAbstractItemModel>` et al instead?

File: src/Mod/Spreadsheet/Gui/SheetTableView.h [hunk 3]
```diff
@@ -104,6 +103,7 @@ protected Q_SLOTS:
 
     void contextMenuEvent(QContextMenuEvent* e) override;
 
+    void _insertRowsColumns(bool after, Qt::Orientation orientation);
```
Comment (hyarion) [inline src/Mod/Spreadsheet/Gui/SheetTableView.h]: i don't find any references to this, is it dead code?

File: src/Mod/Spreadsheet/Gui/SheetModel.cpp [hunk 4]
```diff
@@ -65,53 +72,98 @@ SheetModel::SheetModel(Sheet* _sheet, QObject* parent)
...
+{
+    if (rows + count > CellAddress::MAX_ROWS) {
+        return false;
     }
+    beginInsertRows(parent, rows + 1, rows + count);
+    rows += count;
+    sheet->insertRows(row, count);
+    endInsertRows();
+    return true;
 }
```
Comment (hyarion) [inline src/Mod/Spreadsheet/Gui/SheetModel.cpp:105]: I've been steering at `beginInsertRows` for some time. To me it looks like this should be off by one as Qt's documentation says it is:
> first and last are the row numbers that the _new_ _rows_ will have _after_ they have been inserted.

I've tried it and it seems to work both with your way and when I change it to `beginInsertRows(parent, rows, rows + count - 1);`

Could you explain why I'm wrong ^^

File: src/Mod/Spreadsheet/Gui/SheetModel.cpp [hunk 5]
```diff
@@ -621,19 +669,38 @@ Qt::ItemFlags SheetModel::flags(const QModelIndex& /*index*/) const
...
-    QModelIndex j = index(range.to().row(), range.to().col());
-
-    Q_EMIT dataChanged(i, j);
+    containSheetDataInView();
+    if (range.from().row() < rows && range.from().col() < cols) {
+        QModelIndex i = index(range.from().row(), range.from().col());
+        QModelIndex j = index(range.to().row(), range.to().col());
+        Q_EMIT dataChanged(i, j);
+    }
 }
```
Comment (hyarion) [inline src/Mod/Spreadsheet/Gui/SheetModel.cpp:713]: Should we clamp range to `rows - 1` and `cols - 1` just to be safe?

File: src/Mod/Spreadsheet/Gui/SheetModel.cpp [hunk 6]
```diff
@@ -65,53 +72,98 @@ SheetModel::SheetModel(Sheet* _sheet, QObject* parent)
...
-    rangeUpdatedConnection.disconnect();
+    if (cols + count > CellAddress::MAX_COLUMNS) {
+        return false;
+    }
+    beginInsertColumns(parent, cols + 1, cols + count);
+    cols += count;
+    sheet->insertColumns(column, count);
+    endInsertColumns();
+    return true;
 }
```
Comment (hyarion) [inline src/Mod/Spreadsheet/Gui/SheetModel.cpp:122]: Isn't it bad to call `sheet->insertColumns(column, count);` between `beginInsertColumns` and `endInsertColumns` as calling it would trigger cell and range updates signals?
Moving it outside would ensure that we never can get nested begin and end pairs.

It would be:
```diff
    beginInsertColumns(parent, cols + 1, cols + count);
    cols += count;
--- sheet->insertColumns(column, count);
    endInsertColumns();
+++ sheet->insertColumns(column, count);
```

File: src/Mod/Spreadsheet/Gui/SheetModel.cpp (hunk 2 above)
Comment (greg19) [reply src/Mod/Spreadsheet/Gui/SheetModel.cpp]: Right, my LSP got that wrong

File: src/Mod/Spreadsheet/Gui/SheetModel.cpp (hunk 5 above)
Comment (greg19) [reply src/Mod/Spreadsheet/Gui/SheetModel.cpp:713]: Right, that was my intention but I forgot to do that

File: src/Mod/Spreadsheet/Gui/SheetModel.cpp (hunk 4 above)
Comment (greg19) [reply src/Mod/Spreadsheet/Gui/SheetModel.cpp:105]: You are right. I also fixed `rows` to `row`.

I did some digging in Qt source code, and it looks like QTableView just ignores the arguments you pass and repaints the entire view (re-querying all the data) anyway. QHeaderView just cares about the total number, and also does repainting with re-querying everything except column width (which it caches).

So, in theory what should break with this bug, is changing the widths of columns E, F, D and inserting on the left of `F` – it should introduce a column size mismatch. In practice you also need to comment out the document recompute in `SheetTableView` to observe it, I guess it invalidates the `QHeaderView` widths cache.

Anyway, should correct now.

File: src/Mod/Spreadsheet/Gui/SheetModel.cpp (hunk 6 above)
Comment (greg19) [reply src/Mod/Spreadsheet/Gui/SheetModel.cpp:122]: Qt says that "you must call endInsertColumns *after* inserting data into the model's underlying data store" so includes modifying the values, because it repaints afterwards.

In our case `sheet->insertColumns` emits `data_changed` anyway, so it will also repaint after it, so we can do both.

I'm not sure which approach is cleaner though. I've changed it to your approach for now because the nesting is also something I noticed could happen when you pointed out the previous bug.

File: src/Mod/Spreadsheet/Gui/SheetModel.h [hunk 7]
```diff
@@ -25,9 +25,11 @@
 #ifndef SHEETMODEL_H
 #define SHEETMODEL_H
 
+#include "fastsignals/connection.h"
 #include <QAbstractTableModel>
 
 #include <App/Range.h>
+#include <qcolor.h>
```
Comment (hyarion) [inline src/Mod/Spreadsheet/Gui/SheetModel.h]:
```suggestion
```

File: src/Mod/Spreadsheet/Gui/SheetTableView.cpp [hunk 8]
```diff
@@ -44,10 +45,10 @@
 #include <Gui/CommandT.h>
 #include <Gui/MainWindow.h>
 #include <Mod/Spreadsheet/App/Cell.h>
+#include <qnamespace.h>
```
Comment (hyarion) [inline src/Mod/Spreadsheet/Gui/SheetTableView.cpp]:
```suggestion
```

File: src/Mod/Spreadsheet/Gui/SheetTableView.cpp [hunk 9]
```diff
@@ -56,6 +57,31 @@ using namespace SpreadsheetGui;
 using namespace Spreadsheet;
 using namespace App;
 
+/// Gathers adjecent columns/rows into ranges. Returns the ranges in descending order.
```
Comment (hyarion) [inline src/Mod/Spreadsheet/Gui/SheetTableView.cpp]:
```suggestion
/// Gathers adjacent columns/rows into ranges. Returns the ranges in descending order.
```

File: src/Mod/Spreadsheet/Gui/SheetModel.cpp (hunk 6 above)
Comment (hyarion) [reply src/Mod/Spreadsheet/Gui/SheetModel.cpp:122]: I think the reentrant risk is worse than the double repaint. Qt's docs assume the model owns its data directly, but here the sheet is a separate layer.
We could write a comment to help the next person who comes across this:

```c++
    beginInsertColumns(parent, cols + 1, cols + count);
    cols += count;
    endInsertColumns();
    // Called after endInsertRows to avoid reentrant begin/end from sheet signals.
    sheet->insertColumns(column, count);
```
