### PR TITLE
TechDraw: fix incorrect transform of editable fields

### LINKED ISSUE #20964: TechDraw: User created template regression
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Problem description

Using https://wiki.freecad.org/TechDraw_TemplateGenerator#Resulting_macro the svg output is:

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<svg
  xmlns="http://www.w3.org/2000/svg" version="1.1"
  xmlns:freecad="http://www.freecad.org/wiki/index.php?title=Svg_Namespace"
  width ="420mm"
  height="297mm"
  viewBox="0 0 420 297">
    <g id="drawing-frame"
      style="fill:none;stroke:#000000;stroke-width:0.5;stroke-linecap:round">
      <rect width="390" height="277" x="20" y="10" />
      <rect width="400" height="287" x="15" y="5" />
    </g>

    <g id="titleblock"
      transform="translate(230,287)">
      <g id="titleblock-frame"
        style="fill:none;stroke:#000000;stroke-width:0.35;stroke-linecap:miter;stroke-miterlimit:4">
        <path d="m   0,  0 l   0,-63" />
        <path d="m   0,-63 l 180,  0" />
        <path d="m   0,-30 h 155" />
        <path d="m 155,  0 v -63" />
      </g>
      <g id="titleblock-text-non-editable"
        style="font-size:5.0;text-anchor:start;fill:#000000;font-family:osifont">
        <text x="  4.5" y="-43.5 ">Some static text</text>
        <text x="  4.5" y="-13.5 ">More static text</text>
        <text x="162.5" y="-3.5 " transform="rotate(-90,162.5,-3.5 )">Vertical static text</text>
      </g>
    </g>

    <g id="titleblock-editable-texts"
      style="font-size:7.0;text-anchor:start;fill:#0000d0;font-family:osifont">
      <text freecad:editable="EdiText-1" x="290" y="243.5">  <tspan>Some editable text</tspan>  </text>
      <text freecad:editable="EdiText-2" x="290" y="273.5">  <tspan>More editable text</tspan>  </text>
      <text freecad:editable="EdiText-3" x="403" y="282.5" transform="rotate(-90,403,282.5)">  <tspan>90° editable text</tspan>  </text>
    </g>

</svg>
```

Prior to #20220 the output was:

Image

Post #20220 it is now:

Image

Originally reported as a possible Python version issue https://forum.freecad.org/viewtopic.php?t=96562 that was discounted as a coincidence with the merge of the PR referenced.

### Full version info

```shell
OS: EndeavourOS (X-Cinnamon/cinnamon/xcb)
Architecture: x86_64
Version: 1.1.0dev.41402 (Git)
Build date: 2025/04/24 08:51:59
Build type: Release
Branch: main
Hash: a1b22388a8b74fe5757bc767a060102023a5119a
Python 3.13.2, Qt 6.8.3, Coin 4.0.3, Vtk 9.4.1, boost 1_87, Eigen3 3.4.0, PySide 
shiboken , SMESH 7.7.1.0, xerces-c 3.3.0, OCC 7.8.1
Locale: English/United Kingdom (en_GB)
Stylesheet/Theme/QtStyle: unset/FreeCAD Dark/fusion
Logical DPI/Physical DPI/Pixel Ratio: 96/96.075/1
Installed mods: 
  * FreeCAD-themes 2025.1.7
  * sheetmetal 0.7.22
  * Reinforcement
  * fasteners 0.5.38
```

### Subproject(s) affected?

TechDraw

### Anything else?

_No response_

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by benj5378**
## Issues

Fixes #20964

### CODE REVIEW

File: src/Mod/TechDraw/Gui/QGISVGTemplate.cpp [hunk 1]
```diff
@@ -240,26 +265,13 @@ void QGISVGTemplate::createClickHandles()
...
-            svgTemplate->PageResult.getValue());
-        return;
-    }
-
+    QByteArray svgCode = svgTemplate->processTemplate().toUtf8();
+    applyWorkaround(svgCode);
     QDomDocument templateDocument;
-    if (!templateDocument.setContent(&file)) {
+    if (!templateDocument.setContent(svgCode)) {
         Base::Console().Message("QGISVGTemplate::createClickHandles - xml loading error\n");
```
Comment (benj5378) [inline src/Mod/TechDraw/Gui/QGISVGTemplate.cpp:272]: Could this introduce a regression? This is the code already used in `QGISVGTemplate::load`, so I think it should be fine.

Comment (benj5378) [reply src/Mod/TechDraw/Gui/QGISVGTemplate.cpp:272]: @WandererFan there is no `QString` overload for `QDomDocument::setContent`, needs to be `QByteArray`

Comment (WandererFan) [reply src/Mod/TechDraw/Gui/QGISVGTemplate.cpp:272]: https://doc.qt.io/qt-5/qdomdocument.html#setContent-1
bool QDomDocument::setContent(const QString &text, bool namespaceProcessing, QString *errorMsg = nullptr, int *errorLine = nullptr, int *errorColumn = nullptr)

https://doc.qt.io/qt-6/qdomdocument.html#setContent
setContent(QAnyStringView text, QDomDocument::ParseOptions options = ParseOption::Default)

**Comment by WandererFan** [comment]
No underline or clickbox here.   Could not find the clickbox with random clicking in likely locations.

TemplateNoFieldSelect

**Comment by benj5378** [comment]
@WandererFan works on my machine. What about other templates like `A4_Landscape_ISO5457_minimal.svg`, are there any underlines in them?

image

**Comment by benj5378** [comment]
@FlachyJoe @Syres916, could you please test?

**Comment by WandererFan** [comment]
A4_Landscape_ISO5457_minimal.svg has no lines or clickbox that I can find.

A4_Landscape_ISO5457_minimal_noClickbox

**Comment by WandererFan** [comment]
QRectF textRect = m_svgRender->boundsOnElement(id);
returns an empty rectangle @ 0,0

QPolygonF tightTextPoly(tightTextRect);
has a very small boundingRect - (0.625 x 1.00 @ 0.312, -0.5)

Could this be a Qt version thing?  I'm testing on:
OS: Linux Mint 21.2 (X-Cinnamon/cinnamon/xcb)
Architecture: x86_64
Version: 1.1.0dev.41471 +1 (Git)
Build date: 2025/05/04 23:40:38
Build type: Unknown
Branch: PR21131
Hash: 79bd9e91cfcb789ffae77330f299cf417993a403
Python 3.10.12, **Qt 5.15.2**, Coin 4.0.0, Vtk 7.1.1, boost 1_74, Eigen3 3.4.0, PySide 5.15.2
shiboken 5.15.2, SMESH 7.7.1.0, xerces-c 3.2.3, OCC 7.8.0
Locale: English/Canada (en_CA)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
Logical DPI/Physical DPI/Pixel Ratio: 115/141.585/1
Installed mods: 
  * fasteners 0.5.21

**Comment by WandererFan** [comment]
If I understand these pages:
https://stackoverflow.com/questions/11253734/qsvgrenderer-boundsonelement-always-returns-size-0-0-for-text-elements
https://www.qtcentre.org/threads/8337-QSvgRenderer-boundsOnElement-returns-incorrect-QRectF
https://bugreports.qt.io/browse/QTBUG-32405

correctly there is/was a long standing bug in boundsOnElement() for text elements.  It was corrected in Qt6.2.

If we are still supporting Qt versions < 6.2, this solution will have problems.

**Comment by WandererFan** [comment]
I'm informed that we only support Qt >= 6.2.4, so I guess this is ok, but I can't test it.

**Comment by benj5378** [comment]
> Ubuntu LTS up to April 2029 has Qt5.15.13, surely FreeCAD is maintaining support aligned with this

@Syres916, no, Qt 5 has been dropped. We agreed to only support Ubuntu 22.04 on a dev meeting i believe, and 22.04 supports Qt 6. The motivation for dropping Qt 5 support is to avoid the burden of supporting two Qt versions. Further, Qt 5.15 has end of life 26th May 2025, and Qt 6 has been out for 5 years now.

**Comment by captain0xff** [comment]
I tested the PR on Qt6 (debian linux) and it seems to be working as expected.

**Comment by maxwxyz** [comment]
@benj5378 PR has a conflict

**Comment by yorikvanhavre** [comment]
This looks good to go (even with the Qt5 bug), but waiting on @WandererFan to decide

**Comment by sean9721** [comment]
I have a dumb question.  Are the blue lines at the bottom of the text fields supposed to be visible in the pdf export?  They do not show up in the dxf export.

Blue Lines
[Unnamed_Page_DN_AAA.pdf](https://github.com/user-attachments/files/20638510/Unnamed_Page_DN_AAA.pdf)

OS: Windows 10 build 19045
Architecture: x86_64
Version: 1.1.0dev.42095 (Git)
Build date: 2025/06/06 16:36:48
Build type: Release
Branch: main
Hash: 9c017b0dbf538c2570df7c3316355cdcdc3163f5
Python 3.11.13, Qt 6.8.3, Coin 4.0.3, Vtk 9.3.1, boost 1_86, Eigen3 3.4.0, PySide 6.8.3
shiboken 6.8.3, xerces-c 3.2.5, IfcOpenShell 0.8.2, OCC 7.8.1
Locale: English/United States (en_US)
Navigation Style/Orbit Style/Rotation Mode: CAD/Rounded Arcball/Window center
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Dark/
Logical DPI/Physical DPI/Pixel Ratio: 96/106.605/1

**Comment by WandererFan** [comment]
@sean9721: Absolutely not.  The blue lines should be turned off during export, then back on when the export is completed.

**Comment by sean9721** [comment]
@WandererFan

The blue lines don't disappear when I right click > _Toggle Frames_, or when pressing the _Turn View Frames On/Off_ button in Techdraw.  This happens with templates I created and the templates included with Freecad.  My previous post was done in safe mode.  I even tried the different PDF versions under Preferences > Import-Export > PDF.

**Comment by WandererFan** [comment]
coder note:
```
void QGISVGTemplate::updateView(bool update)
{
    if (update) {
        clearClickHandles();
        createClickHandles();   // <<<< turns click handles back on after 
                                //      ViewProviderTemplate::setMarkers turns them off
    }
    draw();
}
```

**Comment by WandererFan** [comment]
@sean9721 issue for this regression created here:
https://github.com/FreeCAD/FreeCAD/issues/21855
