### PR TITLE
Assembly: Solver messages

### LINKED ISSUE #18406: Assembly not solving even on small number of parts/joints
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Issue is kinda similar to #17917, but not much parts involved and I wasn't able to find workaround. 
Video below shows my test assembly using Fixed joints:

<video src="https://github.com/user-attachments/assets/a4f64fed-1c9c-42fe-b2f2-4a244bd806d1">Fixed joints</video>

Parts are fixed where they should be, but when trying to move what suppose to move - bunch of exceptions and nothing moves. 

Here is my attempt to use distance joints instead of fixed:

<video src="https://github.com/user-attachments/assets/bbab8f59-fe4a-43f1-88d1-7efe92fbcfa3">Distance joints</video>

Parts are everywhere, warnings and errors in the report view.

Test files in attached archive:
[assy_tests.zip](https://github.com/user-attachments/files/18071702/assy_tests.zip)

### Full version info

```shell
OS: Windows 11 build 26100
Architecture: x86_64
Version: 1.1.0dev.39503 (Git) Conda
Build type: Release
Branch: main
Hash: da45328f6f9b35cbbdc7167d7faadb6a07634bdb
Python 3.11.11, Qt 5.15.15, Coin 4.0.3, Vtk 9.3.0, OCC 7.8.1
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: FreeCAD Light.qss/FreeCAD Light/Fusion
Installed mods: 
  * CurvedShapes 1.0.8
  * Curves 0.6.28
  * fasteners 0.5.21
  * Foamcut 0.1.5
  * Marz 0.1.5
  * OpenTheme 2024.9.1
  * PieMenu 1.8.1
  * SmartReportFields1.xlsx
```

### Subproject(s) affected?

Assembly

### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by PaddleStroke**
Fix https://github.com/FreeCAD/FreeCAD/issues/18406
image

Please squash

### CODE REVIEW

File: src/Mod/Assembly/App/AssemblyUtils.cpp [hunk 1]
```diff
@@ -743,5 +743,65 @@ void syncPlacements(App::DocumentObject* src, App::DocumentObject* to)
...
+// namespace as it's an implementation detail of getAssemblyComponents.
+void collectComponentsRecursively(const std::vector<App::DocumentObject*>& objects,
+                                  std::vector<App::DocumentObject*>& results)
+{
+    for (auto* obj : objects) {
+        if (!obj) {
+            continue;
+        }
+
+        if (auto* asmLink = dynamic_cast<Assembly::AssemblyLink*>(obj)) {
```
Comment (kadet1090) [inline src/Mod/Assembly/App/AssemblyUtils.cpp]:
```suggestion
        if (auto* asmLink = freecad_cast<Assembly::AssemblyLink*>(obj)) {
```
?

File: src/Mod/Assembly/App/AssemblyUtils.cpp [hunk 2]
```diff
@@ -743,5 +743,65 @@ void syncPlacements(App::DocumentObject* src, App::DocumentObject* to)
...
+            continue;
+        }
+        else if (obj->isLinkGroup()) {
+            auto* linkGroup = static_cast<App::Link*>(obj);
+            for (auto* elt : linkGroup->ElementList.getValues()) {
+                results.push_back(elt);
+            }
+            continue;
+        }
+        else if (auto* group = dynamic_cast<App::DocumentObjectGroup*>(obj)) {
```
Comment (kadet1090) [inline src/Mod/Assembly/App/AssemblyUtils.cpp]:
```suggestion
        else if (auto* group = freecad_cast<App::DocumentObjectGroup*>(obj)) {
```

File: src/Mod/Assembly/App/AssemblyUtils.cpp [hunk 3]
```diff
@@ -743,5 +743,65 @@ void syncPlacements(App::DocumentObject* src, App::DocumentObject* to)
...
+            collectComponentsRecursively(group->Group.getValues(), results);
+            continue;
+        }
+        else if (auto* link = dynamic_cast<App::Link*>(obj)) {
```
Comment (kadet1090) [inline src/Mod/Assembly/App/AssemblyUtils.cpp]:
```suggestion
        else if (auto* link = freecad_cast<App::Link*>(obj)) {
```

File: src/Mod/Assembly/Gui/Commands.cpp [hunk 4]
```diff
@@ -0,0 +1,230 @@
...
+        return nullptr;
+    }
+
+    auto* vp = doc->getInEdit();
+    if (!vp || !vp->isDerivedFrom(ViewProviderAssembly::getClassTypeId())) {
+        return nullptr;
+    }
+
+    auto* assemblyVP = static_cast<ViewProviderAssembly*>(vp);
+    return assemblyVP->getObject<AssemblyObject>();
```
Comment (kadet1090) [inline src/Mod/Assembly/Gui/Commands.cpp]:
```suggestion
    auto* vp = doc->getInEdit();
    if (auto* assemblyVP = freecad_cast<ViewProviderAssembly*>(vp)) {
        return assemblyVP->getObject<AssemblyObject>();
    }
    
    return nullptr;
```

A bit less conditions and a bit easier to read.

File: src/Mod/Assembly/Gui/Commands.cpp [hunk 5]
```diff
@@ -0,0 +1,230 @@
...
+
+    std::vector<App::DocumentObject*> objectsToSelect;
+    std::vector<App::DocumentObject*> allParts = getAssemblyComponents(assembly);
+
+    // Iterate through all collected parts and check their connectivity
+    for (App::DocumentObject* part : allParts) {
+        if (!assembly->isPartConnected(part)) {
+            objectsToSelect.push_back(part);
+        }
+    }
```
Comment (kadet1090) [inline src/Mod/Assembly/Gui/Commands.cpp:224]: I think that `std::copy_if` could be used here?

**Review by kadet1090 — COMMENTED** [review]
Overall solid, few nitpicks here and there and it does change translations so probably should not be included in the 1.1 release.

**Comment by PaddleStroke** [comment]
> so probably should not be included in the 1.1 release.

IMO this makes the assembly workbench much more reliable for users since a lot create overconstrained assembly. Well worth a few untranslated strings. But if it does not make it for 1.1 it's actually better for me because it will be in AstoCAD 1.1 ;)

**Comment by pierreporte** [comment]
This is a great addition.

**Comment by kadet1090** [comment]
Hi! This PR has seemingly some conflicts due to recent update to the code style. Good news is that in case of that PR formatting changes are the only conflicts so I could update it automatically.

I can update your PR myself or if you want to do it yourself you can find the rebased changes on my fork in branch `pull-24623` (https://github.com/kadet1090/FreeCAD/tree/pull-24623). If you want to use them you can:
1. Check them out locally using `git fetch git@github.com:kadet1090/FreeCAD.git pull-24623`
2. Use `git reset --hard pull-24623` on your PR branch to use my rebased changes
3. `git push --force` to update your PR

If instead you prefer to do the necessary rebasing manually, here is a handy guide: https://github.com/FreeCAD/FreeCAD/discussions/25217.

**Comment by PaddleStroke** [comment]
> I can update your PR myself

That would be great thanks.

File: src/Mod/Assembly/App/AssemblyObject.h [hunk 6]
```diff
@@ -277,10 +278,10 @@ class AssemblyExport AssemblyObject: public App::Part
...
     int lastSolverStatus;
 
-    std::vector<int> lastConflicting;
-    std::vector<int> lastRedundant;
-    std::vector<int> lastPartiallyRedundant;
-    std::vector<int> lastMalformedConstraints;
+    std::vector<App::DocumentObject*> lastRedundantJoints;
+    std::vector<App::DocumentObject*> lastConflictingJoints;
+    std::vector<App::DocumentObject*> lastPartialRedundantJoints;
+    std::vector<App::DocumentObject*> lastMalformedJoints;
```
Comment (kadet1090) [inline src/Mod/Assembly/App/AssemblyObject.h]: Since you are storing pointers to document objects here - is there anything that ensures lifetime of the objects, i.e. that they won't be deleted and references left dangling here?

File: src/Mod/Assembly/Gui/TaskAssemblyMessages.cpp [hunk 7]
```diff
@@ -71,23 +73,26 @@ void TaskAssemblyMessages::updateToolTip(const QString& link)
 
 void TaskAssemblyMessages::onLabelStatusLinkClicked(const QString& /*str*/)
```
Comment (kadet1090) [inline src/Mod/Assembly/Gui/TaskAssemblyMessages.cpp]:
```suggestion
void TaskAssemblyMessages::onLabelStatusLinkClicked(const QString& str)
```

File: src/Mod/Assembly/Gui/ViewProviderAssembly.cpp [hunk 8]
```diff
@@ -1616,38 +1621,42 @@ void ViewProviderAssembly::UpdateSolverInformation()
...
         signalSetUp(QStringLiteral("empty"), tr("Empty Assembly"), QString(), QString());
     }
-    else if (dofs < 0 || hasConflicts) {  // over-constrained
+    else if (dofs < 0 || /*hasConflicts*/ hasRedundancies) {  // over-constrained
+        // Currently the solver does not distinguish between conflicts and redundancies.
+        /*signalSetUp(QStringLiteral("conflicting_constraints"),
+                    tr("Over-constrained:") + QLatin1String(" "),
+                    QStringLiteral("#conflicting"),
+                    QStringLiteral("(%1)").arg(objListHelper(assembly->getLastConflicting())));*/
+        // So for now we report like follows:
```
Comment (kadet1090) [inline src/Mod/Assembly/Gui/ViewProviderAssembly.cpp:1643]: Is there benefit for keeping such dead code? It will rot and won't be useful anyway once we start doing any updates to that.

**Comment by pierreporte** [comment]
I wanted to test this but I get the following build errors with Pixi. They are all related to the Assembly workbench.

<details>
<summary>Terminal output</summary>

```
[6306/6729] Building CXX object src/Mod/Assembly/Gui/CMakeFiles/AssemblyGui.dir/TaskAssemblyMessages.cpp.o
FAILED: [code=1] src/Mod/Assembly/Gui/CMakeFiles/AssemblyGui.dir/TaskAssemblyMessages.cpp.o 
/home/thomas/Projets/FreeCAD/code/FreeCAD/.pixi/envs/default/bin/ccache /home/thomas/Projets/FreeCAD/code/FreeCAD/.pixi/envs/default/bin/clang++ -DAssemblyGui_EXPORTS -DBOOST_DATE_TIME_DYN_LINK -DBOOST_DATE_TIME_NO_LIB -DBOOST_PP_VARIADICS=1 -DBOOST_PROGRAM_OPTIONS_DYN_LINK -DBOOST_PROGRAM_OPTIONS_NO_LIB -DBOOST_REGEX_DYN_LINK -DBOOST_REGEX_NO_LIB -DBOOST_THREAD_DYN_LINK -DBOOST_THREAD_NO_LIB -DFMT_SHARED -DHAVE_CONFIG_H -DNDEBUG -DPYCXX_6_2_COMPATIBILITY -DQT_CONCURRENT_LIB -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_KEYWORDS -DQT_OPENGLWIDGETS_LIB -DQT_OPENGL_LIB -DQT_PRINTSUPPORT_LIB -DQT_SVGWIDGETS_LIB -DQT_SVG_LIB -DQT_UITOOLS_LIB -DQT_WIDGETS_LIB -DQT_XML_LIB -DSALOME_USE_64BIT_IDS -D_OCC64 -I/home/thomas/Projets/FreeCAD/code/FreeCAD/build/debug/src/Mod/Assembly/Gui/AssemblyGui_autogen/include -I/home/thomas/Projets/FreeCAD/code/FreeCAD/build/debug -I/home/thomas/Projets/FreeCAD/code/FreeCAD/.pixi/envs/default/include/eigen3 -I/home/thomas/Projets/FreeCAD/code/FreeCAD/build/debug/src -I/home/thomas/Projets/FreeCAD/code/FreeCAD/src -I/home/thomas/Projets/FreeCAD/code/FreeCAD/src/3rdParty/OndselSolver -I/home/thomas/Projets/FreeCAD/code/FreeCAD/build/debug/src/Mod/Assembly/Gui -I/home/thomas/Projets/FreeCAD/code/FreeCAD/src/3rdParty/FastSignals/libfastsignals/include -I/home/thomas/Projets/FreeCAD/code/FreeCAD/src/Gui -I/home/thomas/Projets/FreeCAD/code/FreeCAD/src/Gui/Quarter -I/home/thomas/Projets/FreeCAD/code/FreeCAD/src/Gui/PreferencePages -I/home/thomas/Projets/FreeCAD/code/FreeCAD/src/Gui/Selection -I/home/thomas/Projets/FreeCAD/code/FreeCAD/src/Gui/StyleParameters -I/home/thomas/Projets/FreeCAD/code/FreeCAD/build/debug/src/Gui -I/home/thomas/Projets/FreeCAD/code/FreeCAD/src/Gui/.. -I/home/thomas/Projets/FreeCAD/code/FreeCAD/build/debug/src/Gui/.. -I/home/thomas/Projets/FreeCAD/code/FreeCAD/build/debug/src/Gui/Language -I/home/thomas/Projets/FreeCAD/code/FreeCAD/build/debug/src/Gui/propertyeditor -I/home/thomas/Projets/FreeCAD/code/FreeCAD/build/debug/src/Gui/TaskView -I/home/thomas/Projets/FreeCAD/code/FreeCAD/build/debug/src/Gui/Quarter -I/home/thomas/Projets/FreeCAD/code/FreeCAD/build/debug/src/Gui/DAGView -isystem /home/thomas/Projets/FreeCAD/code/FreeCAD/.pixi/envs/default/include/opencascade -isystem /home/thomas/Projets/FreeCAD/code/FreeCAD/.pixi/envs/default/include/freetype2 -isystem /home/thomas/Projets/FreeCAD/code/FreeCAD/.pixi/envs/default/include/qt6/QtCore -isystem /home/thomas/Projets/FreeCAD/code/FreeCAD/.pixi/envs/default/include/qt6 -isystem /home/thomas/Projets/FreeCAD/code/FreeCAD/.pixi/envs/default/include/qt6/QtXml -isystem /home/thomas/Projets/FreeCAD/code/FreeCAD/.pixi/envs/default/include -isystem /home/thomas/Projets/FreeCAD/code/FreeCAD/src/3rdParty/PyCXX -isystem /home/thomas/Projets/FreeCAD/code/FreeCAD/.pixi/envs/default/include/python3.11 -isystem /home/thomas/Projets/FreeCAD/code/FreeCAD/src/3rdParty -isystem /home/thomas/Projets/FreeCAD/code/FreeCAD/.pixi/envs/default/lib/qt6/mkspecs/linux-g++ -isystem /home/thomas/Projets/FreeCAD/code/FreeCAD/.pixi/envs/default/include/qt6/QtConcurrent -isystem /home/thomas/Projets/FreeCAD/code/FreeCAD/.pixi/envs/default/include/qt6/QtWidgets -isystem /home/thomas/Projets/FreeCAD/code/FreeCAD/.pixi/envs/default/include/qt6/QtGui -isystem /home/thomas/Projets/FreeCAD/code/FreeCAD/.pixi/envs/default/include/qt6/QtDBus -isystem /home/thomas/Projets/FreeCAD/code/FreeCAD/.pixi/envs/default/include/qt6/QtOpenGL -isystem /home/thomas/Projets/FreeCAD/code/FreeCAD/.pixi/envs/default/include/qt6/QtOpenGLWidgets -isystem /home/thomas/Projets/FreeCAD/code/FreeCAD/.pixi/envs/default/include/qt6/QtPrintSupport -isystem /home/thomas/Projets/FreeCAD/code/FreeCAD/.pixi/envs/default/include/qt6/QtSvg -isystem /home/thomas/Projets/FreeCAD/code/FreeCAD/.pixi/envs/default/include/qt6/QtSvgWidgets -isystem /home/thomas/Projets/FreeCAD/code/FreeCAD/.pixi/envs/default/include/qt6/QtNetwork -isystem /home/thomas/Projets/FreeCAD/code/FreeCAD/.pixi/envs/default/include/qt6/QtUiTools -isystem /home/thomas/Projets/FreeCAD/code/FreeCAD/.pixi/envs/default/include/qt6/QtUiPlugin -isystem /home/thomas/Projets/FreeCAD/code/FreeCAD/.pixi/envs/default/include/shiboken6 -isystem /home/thomas/Projets/FreeCAD/code/FreeCAD/.pixi/envs/default/include/PySide6 -isystem /home/thomas/Projets/FreeCAD/code/FreeCAD/.pixi/envs/default/include/PySide6/QtCore -isystem /home/thomas/Projets/FreeCAD/code/FreeCAD/.pixi/envs/default/include/PySide6/QtGui -isystem /home/thomas/Projets/FreeCAD/code/FreeCAD/.pixi/envs/default/include/PySide6/QtWidgets -Wall -Wextra -Wpedantic -Wno-write-strings -fdiagnostics-color  -Wno-undefined-var-template -g -O0 -DFC_DEBUG -std=c++20 -fPIC -pthread -fPIC -MD -MT src/Mod/Assembly/Gui/CMakeFiles/AssemblyGui.dir/TaskAssemblyMessages.cpp.o -MF src/Mod/Assembly/Gui/CMakeFiles/AssemblyGui.dir/TaskAssemblyMessages.cpp.o.d -o src/Mod/Assembly/Gui/CMakeFiles/AssemblyGui.dir/TaskAssemblyMessages.cpp.o -c /home/thomas/Projets/FreeCAD/code/FreeCAD/src/Mod/Assembly/Gui/TaskAssemblyMessages.cpp
/home/thomas/Projets/FreeCAD/code/FreeCAD/src/Mod/Assembly/Gui/TaskAssemblyMessages.cpp:76:9: error: use of undeclared identifier 'str'
   76 |     if (str == QStringLiteral("#conflicting")) {
      |         ^
/home/thomas/Projets/FreeCAD/code/FreeCAD/src/Mod/Assembly/Gui/TaskAssemblyMessages.cpp:81:14: error: use of undeclared identifier 'str'
   81 |     else if (str == QStringLiteral("#redundant")) {
      |              ^
/home/thomas/Projets/FreeCAD/code/FreeCAD/src/Mod/Assembly/Gui/TaskAssemblyMessages.cpp:86:14: error: use of undeclared identifier 'str'
   86 |     else if (str == QStringLiteral("#dofs")) {
      |              ^
/home/thomas/Projets/FreeCAD/code/FreeCAD/src/Mod/Assembly/Gui/TaskAssemblyMessages.cpp:91:14: error: use of undeclared identifier 'str'
   91 |     else if (str == QStringLiteral("#malformed")) {
      |              ^
4 errors generated.
[6313/6729] Building CXX object src/Mod/Assembly/Gui/CMakeFiles/AssemblyGui.dir/ViewProviderAssembly.cpp.o
FAILED: [code=1] src/Mod/Assembly/Gui/CMakeFiles/AssemblyGui.dir/ViewProviderAssembly.cpp.o 
/home/thomas/Projets/FreeCAD/code/FreeCAD/.pixi/envs/default/bin/ccache /home/thomas/Projets/FreeCAD/code/FreeCAD/.pixi/envs/default/bin/clang++ -DAssemblyGui_EXPORTS -DBOOST_DATE_TIME_DYN_LINK -DBOOST_DATE_TIME_NO_LIB -DBOOST_PP_VARIADICS=1 -DBOOST_PROGRAM_OPTIONS_DYN_LINK -DBOOST_PROGRAM_OPTIONS_NO_LIB -DBOOST_REGEX_DYN_LINK -DBOOST_REGEX_NO_LIB -DBOOST_THREAD_DYN_LINK -DBOOST_THREAD_NO_LIB -DFMT_SHARED -DHAVE_CONFIG_H -DNDEBUG -DPYCXX_6_2_COMPATIBILITY -DQT_CONCURRENT_LIB -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_KEYWORDS -DQT_OPENGLWIDGETS_LIB -DQT_OPENGL_LIB -DQT_PRINTSUPPORT_LIB -DQT_SVGWIDGETS_LIB -DQT_SVG_LIB -DQT_UITOOLS_LIB -DQT_WIDGETS_LIB -DQT_XML_LIB -DSALOME_USE_64BIT_IDS -D_OCC64 -I/home/thomas/Projets/FreeCAD/code/FreeCAD/build/debug/src/Mod/Assembly/Gui/AssemblyGui_autogen/include -I/home/thomas/Projets/FreeCAD/code/FreeCAD/build/debug -I/home/thomas/Projets/FreeCAD/code/FreeCAD/.pixi/envs/default/include/eigen3 -I/home/thomas/Projets/FreeCAD/code/FreeCAD/build/debug/src -I/home/thomas/Projets/FreeCAD/code/FreeCAD/src -I/home/thomas/Projets/FreeCAD/code/FreeCAD/src/3rdParty/OndselSolver -I/home/thomas/Projets/FreeCAD/code/FreeCAD/build/debug/src/Mod/Assembly/Gui -I/home/thomas/Projets/FreeCAD/code/FreeCAD/src/3rdParty/FastSignals/libfastsignals/include -I/home/thomas/Projets/FreeCAD/code/FreeCAD/src/Gui -I/home/thomas/Projets/FreeCAD/code/FreeCAD/src/Gui/Quarter -I/home/thomas/Projets/FreeCAD/code/FreeCAD/src/Gui/PreferencePages -I/home/thomas/Projets/FreeCAD/code/FreeCAD/src/Gui/Selection -I/home/thomas/Projets/FreeCAD/code/FreeCAD/src/Gui/StyleParameters -I/home/thomas/Projets/FreeCAD/code/FreeCAD/build/debug/src/Gui -I/home/thomas/Projets/FreeCAD/code/FreeCAD/src/Gui/.. -I/home/thomas/Projets/FreeCAD/code/FreeCAD/build/debug/src/Gui/.. -I/home/thomas/Projets/FreeCAD/code/FreeCAD/build/debug/src/Gui/Language -I/home/thomas/Projets/FreeCAD/code/FreeCAD/build/debug/src/Gui/propertyeditor -I/home/thomas/Projets/FreeCAD/code/FreeCAD/build/debug/src/Gui/TaskView -I/home/thomas/Projets/FreeCAD/code/FreeCAD/build/debug/src/Gui/Quarter -I/home/thomas/Projets/FreeCAD/code/FreeCAD/build/debug/src/Gui/DAGView -isystem /home/thomas/Projets/FreeCAD/code/FreeCAD/.pixi/envs/default/include/opencascade -isystem /home/thomas/Projets/FreeCAD/code/FreeCAD/.pixi/envs/default/include/freetype2 -isystem /home/thomas/Projets/FreeCAD/code/FreeCAD/.pixi/envs/default/include/qt6/QtCore -isystem /home/thomas/Projets/FreeCAD/code/FreeCAD/.pixi/envs/default/include/qt6 -isystem /home/thomas/Projets/FreeCAD/code/FreeCAD/.pixi/envs/default/include/qt6/QtXml -isystem /home/thomas/Projets/FreeCAD/code/FreeCAD/.pixi/envs/default/include -isystem /home/thomas/Projets/FreeCAD/code/FreeCAD/src/3rdParty/PyCXX -isystem /home/thomas/Projets/FreeCAD/code/FreeCAD/.pixi/envs/default/include/python3.11 -isystem /home/thomas/Projets/FreeCAD/code/FreeCAD/src/3rdParty -isystem /home/thomas/Projets/FreeCAD/code/FreeCAD/.pixi/envs/default/lib/qt6/mkspecs/linux-g++ -isystem /home/thomas/Projets/FreeCAD/code/FreeCAD/.pixi/envs/default/include/qt6/QtConcurrent -isystem /home/thomas/Projets/FreeCAD/code/FreeCAD/.pixi/envs/default/include/qt6/QtWidgets -isystem /home/thomas/Projets/FreeCAD/code/FreeCAD/.pixi/envs/default/include/qt6/QtGui -isystem /home/thomas/Projets/FreeCAD/code/FreeCAD/.pixi/envs/default/include/qt6/QtDBus -isystem /home/thomas/Projets/FreeCAD/code/FreeCAD/.pixi/envs/default/include/qt6/QtOpenGL -isystem /home/thomas/Projets/FreeCAD/code/FreeCAD/.pixi/envs/default/include/qt6/QtOpenGLWidgets -isystem /home/thomas/Projets/FreeCAD/code/FreeCAD/.pixi/envs/default/include/qt6/QtPrintSupport -isystem /home/thomas/Projets/FreeCAD/code/FreeCAD/.pixi/envs/default/include/qt6/QtSvg -isystem /home/thomas/Projets/FreeCAD/code/FreeCAD/.pixi/envs/default/include/qt6/QtSvgWidgets -isystem /home/thomas/Projets/FreeCAD/code/FreeCAD/.pixi/envs/default/include/qt6/QtNetwork -isystem /home/thomas/Projets/FreeCAD/code/FreeCAD/.pixi/envs/default/include/qt6/QtUiTools -isystem /home/thomas/Projets/FreeCAD/code/FreeCAD/.pixi/envs/default/include/qt6/QtUiPlugin -isystem /home/thomas/Projets/FreeCAD/code/FreeCAD/.pixi/envs/default/include/shiboken6 -isystem /home/thomas/Projets/FreeCAD/code/FreeCAD/.pixi/envs/default/include/PySide6 -isystem /home/thomas/Projets/FreeCAD/code/FreeCAD/.pixi/envs/default/include/PySide6/QtCore -isystem /home/thomas/Projets/FreeCAD/code/FreeCAD/.pixi/envs/default/include/PySide6/QtGui -isystem /home/thomas/Projets/FreeCAD/code/FreeCAD/.pixi/envs/default/include/PySide6/QtWidgets -Wall -Wextra -Wpedantic -Wno-write-strings -fdiagnostics-color  -Wno-undefined-var-template -g -O0 -DFC_DEBUG -std=c++20 -fPIC -pthread -fPIC -MD -MT src/Mod/Assembly/Gui/CMakeFiles/AssemblyGui.dir/ViewProviderAssembly.cpp.o -MF src/Mod/Assembly/Gui/CMakeFiles/AssemblyGui.dir/ViewProviderAssembly.cpp.o.d -o src/Mod/Assembly/Gui/CMakeFiles/AssemblyGui.dir/ViewProviderAssembly.cpp.o -c /home/thomas/Projets/FreeCAD/code/FreeCAD/src/Mod/Assembly/Gui/ViewProviderAssembly.cpp
/home/thomas/Projets/FreeCAD/code/FreeCAD/src/Mod/Assembly/Gui/ViewProviderAssembly.cpp:299:13: error: use of undeclared identifier 'taskSolver'
  299 |             taskSolver = new TaskAssemblyMessages(this);
      |             ^
/home/thomas/Projets/FreeCAD/code/FreeCAD/src/Mod/Assembly/Gui/ViewProviderAssembly.cpp:300:42: error: use of undeclared identifier 'taskSolver'
  300 |             taskView->addContextualPanel(taskSolver);
      |                                          ^
/home/thomas/Projets/FreeCAD/code/FreeCAD/src/Mod/Assembly/Gui/ViewProviderAssembly.cpp:343:45: error: use of undeclared identifier 'taskSolver'
  343 |             taskView->removeContextualPanel(taskSolver);
      |                                             ^
/home/thomas/Projets/FreeCAD/code/FreeCAD/src/Mod/Assembly/Gui/ViewProviderAssembly.cpp:1616:10: warning: unused variable 'hasConflicts' [-Wunused-variable]
 1616 |     bool hasConflicts = assembly->getLastHasConflicts();
      |          ^~~~~~~~~~~~
/home/thomas/Projets/FreeCAD/code/FreeCAD/src/Mod/Assembly/Gui/ViewProviderAssembly.cpp:1618:10: warning: unused variable 'hasPartiallyRedundant' [-Wunused-variable]
 1618 |     bool hasPartiallyRedundant = assembly->getLastHasPartialRedundancies();
      |          ^~~~~~~~~~~~~~~~~~~~~
2 warnings and 3 errors generated.
[6314/6729] Automatic MOC and UIC for target PartDesignGui
AutoUic: /home/thomas/Projets/FreeCAD/code/FreeCAD/src/Mod/PartDesign/Gui/TaskPadPocketParameters.ui: Warning: The name 'verticalLayout_22' (QHBoxLayout) is already in use, defaulting to 'verticalLayout_221'.
/home/thomas/Projets/FreeCAD/code/FreeCAD/src/Mod/PartDesign/Gui/TaskPadPocketParameters.ui: Warning: The name 'verticalLayout_22' (QVBoxLayout) is already in use, defaulting to 'verticalLayout_222'.
[6315/6729] Automatic MOC and UIC for target TechDrawGui
ninja: build stopped: subcommand failed.

```
<details>

File: src/Mod/Assembly/Gui/ViewProviderAssembly.cpp (hunk 8 above)
Comment (PaddleStroke) [reply src/Mod/Assembly/Gui/ViewProviderAssembly.cpp:1643]: I don't see the point of removing it as we may be able to get more information in the future to distinguish redundant / conflicting. In which case that will have to be rewriten.

**Comment by PaddleStroke** [comment]
@pierreporte I think the build is fixed now. Let's check how the CI does to confirm this.

File: src/Mod/Assembly/App/AssemblyObject.h (hunk 6 above)
Comment (PaddleStroke) [reply src/Mod/Assembly/App/AssemblyObject.h]: Ah damn you are right, we need to store object names to prevent this possible issue. This is going to need to change many things

Comment (PaddleStroke) [reply src/Mod/Assembly/App/AssemblyObject.h]: Updated, now we are storing the object names. Preventing any dangling pointers issue

**Comment by pierreporte** [comment]
I was able to build. A discussion with the DWG has started.

**Comment by PaddleStroke** [comment]
The discussion : https://discord.com/channels/870877411049357352/1163884496031064134/threads/1462877713365860442

**Comment by PaddleStroke** [comment]
Can this go in now? @kadet1090

**Comment by kadet1090** [comment]
> Can this go in now? @kadet1090

Code is ok, but it's still waiting for opinion from DWG - once I have a summary that I can post I'll do that and merge.

**Comment by kadet1090** [comment]
From the DWG perspective the feature is useful but it's not clear if the way that the messages are presented is the best one possible. While the consistency with sketcher is good to see, the context of assembly can be a bit different and it should be taken into account. The group however does not see anything that should block merge of this PR the rest of work could be done later, once we gather feedback and have time to actually work with it for longer time.

**Comment by kadet1090** [comment]
Given how many possible cases with assemblies there are it won't be possible to fully test it by one person - let's just push it to weekly and wait for feedback.

**Comment by maxwxyz** [comment]
@PaddleStroke any idea why the solver messages are not displayed anymore? https://github.com/FreeCAD/FreeCAD/pull/30937 cannot be tested.

**Comment by PaddleStroke** [comment]
Yes it's a regression from the per-document undo stack. There is an open issue here : https://github.com/FreeCAD/FreeCAD/issues/29390

Theo was working on a fix, but I think he got overwhelmed by issues to fix. I'm not sure where this stands
