### PR TITLE
Fix Suppressed context menu action

### LINKED ISSUE #28253: PartDesign: suppressed right click option doesn't auto recompute
### Problem description

https://github.com/user-attachments/assets/97294f71-74e3-471a-b820-a6b5e1fea600

This is a fresh install of 1.1-rc3 on an Windows 11 Arm PC

The right click menu toggles the suppressed state but doesn't actually suppress the feature. Using the properties menu does suppress the feature.

### Workbench affected?

Part Design

### Steps to reproduce

See video

### Expected behavior

That the right click menu suppress option actually suppresses

### Actual behavior

See video

### Development version About Info (in Safe Mode)

```shell
1.1-rc3
```

### Last known good version (optional)

```shell

```

### PR DESCRIPTION
**Pull request by FlachyJoe**
Recompute the document when the menu action is clicked.
Fix #28253

### CODE REVIEW

File: src/Gui/ViewProviderSuppressibleExtension.cpp [hunk 1]
```diff
@@ -90,14 +90,18 @@ QIcon ViewProviderSuppressibleExtension::extensionMergeColorfullOverlayIcons(con
 void ViewProviderSuppressibleExtension::extensionSetupContextMenu(QMenu* menu, QObject*, const char*)
 {
     auto vp = getExtendedViewProvider();
-    auto obj = vp->getObject()->getExtensionByType<App::SuppressibleExtension>();
+    auto obj = vp->getObject();
+    auto sObj = obj->getExtensionByType<App::SuppressibleExtension>();
     // Show Suppressed toggle action if the Suppressed property is visible
-    if (obj && !obj->Suppressed.testStatus(App::Property::Hidden)) {
-        Gui::ActionFunction* func = new Gui::ActionFunction(menu);
+    if (obj && !sObj->Suppressed.testStatus(App::Property::Hidden)) {
```
Comment (chennes) [inline src/Gui/ViewProviderSuppressibleExtension.cpp]: `obj` can't be null, but `sObj` can...
```suggestion
    if (sObj&& !sObj->Suppressed.testStatus(App::Property::Hidden)) {
```
